fwupd/fwupd

- man/Makefile.am
This fixes this error:
fwupdmgr.sgml:1: parser error : StartTag: invalid element name
<!doctype refentry PUBLIC "-//OASIS//DTD DocBook V4.1//EN" [
^
fwupdmgr.sgml:1: parser error : Extra content at the end of the document
<!doctype refentry PUBLIC "-//OASIS//DTD DocBook V4.1//EN" [
^
unable to parse fwupdmgr.sgml
no element found at line 1, column 0, byte 0 at /usr/lib/perl5/vendor_perl/XML/Parser.pm line 187.
Makefile:612: recipe for target 'fwupdmgr.1' failed
> man/Makefile.am: Add --sgml to docbook2man invocation

- man/Makefile.am
This reverts commit b4143665fe46ad71379de41441dd36cd6be39066.
docbook-utils' docbook2man doesn't have a --sgml flag
and is arguably a more modern utility compared to docbook2man
from docbook2X
> Revert "man/Makefile.am: Add --sgml to docbook2man invocation"

- configure.ac
- src/Makefile.am
Fix build failure when building with --disable-colorhug.
> build: gusb is required even without colorhug

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-result.c
- libfwupd/fwupd-self-test.c
- src/fu-util.c
Previously running get-devices would show the device_id as the top level indicator.  Something like this on a Precision 5510:
```
ro__sys_devices_pci0000_00_0000_00_01_0_0000_01_00_0
Guid:                 2b07aa6b-6b41-5e92-8f2f-ff742f711a81
DisplayName:          GM107GLM [Quadro M1000M]
Provider:             Udev
Flags:                internal|locked
DeviceVendor:         NVIDIA Corporation
Created:              2016-04-14
Trusted:              none
ro__sys_devices_pci0000_00_0000_00_02_0
Guid:                 8ec3e242-65bd-58ee-9c5e-b28f1e32e7ae
DisplayName:          Skylake Integrated Graphics
Provider:             Udev
Flags:                internal|locked
DeviceVendor:         Intel Corporation
Created:              2016-04-14
Trusted:              none …
```
> Re-order output of get-devices to be easier to read

- docs/libfwupd/Makefile.am
This fixes the following error:
```
warning: failed to load external entity "../xml/fwupd-version.xml"
../libfwupd-docs.xml:40: element include: XInclude error : could not load ../xml/fwupd-version.xml, and no fallback was found
```
> build: Fix gtk-doc build when srcdir != builddir

- Makefile.am
- README.md
- configure.ac
- contrib/fwupd.spec.in
- src/Makefile.am
- src/fu-main.c
- src/fu-provider-dell.c
- src/fu-provider-dell.h
- src/fu-self-test.c
Dell systems from 2015 support field update-able TPMs that also can switch modes.  This adds support for them including switching modes via the newly added unlock mechanisms.
Dell TB15 and WD15 docks can also be updated on Dell systems with Type-C.  This is the initial work necessary to be able to support polling information about their updates.  Currently a virtual dock device is created when a USB device on the dock (Realtek NIC specific VID/PID) is detected.
This isn't really the ideal end approach for a variety of reasons.  The main one is there are multiple individual firmware components that can be updated on the dock via the same payload mechanism and flash mechanism.  This means that you really want to query all the components to evaluate whether an update should be offered.
What …
> Add support for Dell TPM 1.2/2.0 updates and initial support for dock information

- src/Makefile.am
If UEFI is disabled, but Dell non-ESRT capsule support enabled, fwupd fails to
link against libfwup as needed.
> trivial: link against fwup

- configure.ac
This restores all providers to be enabled by default, but if dependencies are missing for any then they will be disabled without causing an autotools error.
This should allow tools that require external libraries to be pulled in explicitly such as jhbuild to not complain, but still make the default solution for packagers easier to follow too.
As part of this, there is now a summary output in configure to it should be apparent that fwupd was built without some optional components if dependencies weren't included or a provider was forced to --disable-$provider
> Adjust autotools logic for providers

- libdfu/dfu-device.c
- src/fu-provider-usb.c
- src/plugins/fu-plugin-steelseries.c
In fwupd, a few of usb devices are not closed when there are some failures of operations. This issue will cause fwupd has some orphan USB nodes inside during fwupd is running. A orphan USB node might introduce memory leak and block some runtime power features as well.
The objective of this commit  it to close this kind of USB device.
> close USB devices before error returns

- data/org.freedesktop.fwupd.service.in
Without this the fwupd process will leak into the dbus cgroup.
> Uncomment SystemdService parameter in the dbus service file.

- configure.ac
- plugins/thunderbolt/README.md
- plugins/thunderbolt/fu-plugin-thunderbolt.c
The changes include what we have discussed here: [4ff3169](https://github.com/hughsie/fwupd/commit/4ff3169556b391ab9808df5bcea063a830c1bd07)
It also aligns with v1.0.0 of libtbtfwu released yesterday ([d83532a](https://github.com/01org/thunderbolt-software-user-space/commit/d83532a9945a0156bd13a0627d3c999fc5166bd5)) and uses the new option of FW update progress reporting.
Last but not least, we handle safe-mode in a way that shows the controller to the user but prevents auto-updating.
> Updates for thunderolt plugin, including matching v1.0.0 of libtbtfwu

- plugins/thunderbolt/Makefile.am
- plugins/thunderbolt/fu-plugin-thunderbolt.c
Per discussion with @ybernat  and @hughsie:
Dell systems are known to have the Model ID the same as the SystemID
that can be recovered from libsmbios.  If the thunderbolt controller
is in safe mode, identify with this ID to allow the controller to be
flashed with a good FW.
> thunderbolt: Add special handling for safe mode on Dell systems

- docs/man/Makefile.am
- docs/man/dfu-tool.sgml
- docs/man/fwupdmgr.sgml
The following changes had to be made to successfully compile with docbook2X which is shipped with Gentoo. Additionally, a patch to configure.ac is needed to turn docbook2man into docbook2man.pl but that is not part of this patch. It's only part of my build script.
It was not tested against classic docbook2man but I guess it should work.
> Fix issues when compiling with docbook2X

- configure.ac
- libdfu/dfu-format-elf.c
- libdfu/dfu-tool.c
- plugins/altos/fu-device-altos.c
- plugins/udev/fu-rom-tool.c
My compiler doesn't understand -Wno-discard-qualifiers so drop it and
fix the warnings instead. I think it is better to explicitly fix them
anyways instead of just to ignore the discarded const qualifier in
general.
I think the option should be avoided in hand-written code. The warning
is there for a reason: To protect you from possibly overwriting data you
expect to not be modified when passing pointers around.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41215
> Fix compiler warnings

- meson.build
It looks like this was missed during the migration to meson
> Set HAVE_POLKIT_0_114 when polkit is newer than 0.114

- meson.build
Adds regex command used for comparing firmware versions.
----
With  0.6.8 updating Unifying Receiver fails for me with:
```
version of bootloader incorrect: failed predicate [BOT01.0[0-3]_* regex BOT01.02_B0014]
```
> Increase minimum required AppStream-Glib version to 0.6.13

- contrib/fwupd.spec.in
- docs/man/meson.build
- docs/meson.build
- meson_options.txt
Reduce the minimum build-time dependencies.
---
Please consider adding options for building the documentation (which looks like developers only) and man pages: this would reduce the dependencies for building on a minimal system.
docbook2man is currently an automagic dependency for the man pages, but this in itself causes problems for e.g. Gentoo where it ends up being safer to make it a mandatory dependency. This patch requires it if you have enabled the man pages option.
I've made changes to the spec file to enable them both to keep the current behaviour, but can't test it.
> Make documentation and man pages optional

- data/meson.build
- meson.build
- meson_options.txt
- src/fu-util.c
Make systemd and ConsoleKit support an optional compile time flag
with both enabled by default. If both are used, the ifdef/elif will
ensure only the systemd calls are used so there's no conflict.
> Add support for ConsoleKit2

- .travis.yml
- contrib/ci/build_and_install_debs.sh
- contrib/ci/build_and_install_rpms.sh
- plugins/test/fu-plugin-test.c
- src/fu-self-test.c
This lets the tests be installed onto a system without FakeDevices showing up.
> Only use the test runner plugin when CI is set in the env

- libdfu/meson.build
- libfwupd/meson.build
- meson_options.txt
I'm working on packaging fwupd for OpenEmbedded, or more specifically,
https://github.com/intel/intel-iot-refkit.
OE currently has technical problems with gobject-introspection when
using meson. This is going to be addressed eventually, but some
intermediate solution is needed. As gir data is not needed for fwupd,
it would be great if it could be made optional. That might also be
useful in other builds that try to build only what's really needed.
Depends on a similar change in appstream-glib, see
https://github.com/hughsie/appstream-glib/pull/182.
> gir creation optional

- plugins/ebitdo/fu-ebitdo-tool.c
When my SNES30 controller was in bootloader mode, it wouldn't update, and when it was in controller mode, it tried and failed. Now, it prints out the instructions on how to reset the device if it's in controller mode, and if it's in bootloader mode, it successfully installs the firmware update from the .DAT file.
> Make flashing ebitdo devices actually work

- meson.build
The same fixes as I seem to be making everywhere. Probably as a result of using old GCC on Debian Jessie. Still, let’s fix it.
> Build fixes: C99 and feature test macros

- plugins/tbtfwu/fu-plugin-tbtfwu.c
A typo ended up putting an extra `)` on line 227 of the tbtfwu plugin. This PR fixes that typo.
> Remove extra `)`

- contrib/debian/control
- contrib/firmware-packager/README.md
- contrib/firmware-packager/firmware-packager
- contrib/firmware-packager/meson.build
- contrib/fwupd.spec.in
- contrib/meson.build
- meson.build
These commits add a python script to create fwupd compatible cab files from Microsoft .exe files. This allows a user to update their firmware with fwupd even if the vensor hasn't yet made firmware packages available on the LVFS. 
Resolves #103
> Add firmware-packager Script

- meson.build
- plugins/thunderbolt/meson.build
A couple of fixes when building with `-Denable-systemd=false -Denable-thunderbolt=true`.
> Meson build fixes

- contrib/ci/Dockerfile-arch
umockdev package is now available in the community repository
of Arch Linux
https://github.com/hughsie/fwupd/issues/187
> thunderbolt plugin can be tested on Arch Linux now

- plugins/thunderbolt/fu-plugin-thunderbolt.c
We want thunderbolt to claim the device and not to race with the
udev plugin.
> thunderbolt: add new devices without delay

- libfwupd/fwupd-enums.h
- plugins/test/fu-plugin-test.c
- src/fu-engine.c
- src/fu-plugin-private.h
- src/fu-plugin-vfuncs.h
- src/fu-plugin.c
- src/fu-plugin.h
- src/fu-self-test.c
This could be used, for instance, to set a property on ThunderBolt controllers
inside Dell computers saying that they support forcing the power level during
coldplug. It could also be used to set the dock type for the synapticsmst hub.
Adding this level of complexity allows us to avoid the creep of HAVE_DELL and
HAVE_LENOVO into seemingly unrelated plugins, and also allows us to have
multiple vendor plugins providing the same end result with two different
vendor-specific mechanisms.
> Allow plugins to set metadata on devices created by other plugins

- plugins/thunderbolt/meson.build
This change should restore building fwupd with the new thunderbolt
plugin on older systems.
> thunderbolt: only build tests if glib >= 2.52

- plugins/dell/fu-plugin-dell.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- Set initial (invalid) GUID for TBT controller (otherwise device doesn't add)
- Don't set updatable unless GUID has been refreshed (otherwise someone could update from GUID TBT-safemode)
- Correct the string used for GUID in Dell plugin (was looking at decimal not hex)
I found these problems by manually setting safe mode in code.  I haven't actually tested on a system really in safe mode.  It would be appreciated if @ybernat could check on a system truly instrumented in safe mode if there are other deficiencies.
> trivial: fix TBT controller safe mode handling on Dell

- plugins/dell/fu-plugin-dell.c
Currently, when compiling I get the following warnings:
```
[150/178] Compiling C object 'plugins/dell/fu_plugin_dell@sha/fu-plugin-dell.c.o'.
../thunderbolt_sw_2-fwupd/plugins/dell/fu-plugin-dell.c: In function ‘fu_plugin_device_registered’:
../thunderbolt_sw_2-fwupd/plugins/dell/fu-plugin-dell.c:827:41: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘int’ [-Wformat=]
device_id = g_strdup_printf ("TBT-%04x%04x", 0x00d4,
~~~^
%04x
../thunderbolt_sw_2-fwupd/plugins/dell/fu-plugin-dell.c:827:45: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘int’ [-Wformat=]
device_id = g_strdup_printf ("TBT-%04x%04x", 0x00d4,
~~~^
%04x
sysinfo_get_dell_system_id ());
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
[164/178] Compiling C …
```
> trivial: fix compilation warning

- plugins/dell/fu-dell-common.c
- plugins/dell/fu-dell-common.h
- plugins/dell/fu-plugin-dell.c
- plugins/dell/fu-plugin-dell.h
- plugins/dell/fu-self-test.c
- plugins/synapticsmst/fu-plugin-synapticsmst.c
This decouples the Synaptics plugin and Dell plugin more.  The remaining connection for looking up system ID and dock ID will require more delicate surgery at a later time.
> Dell improvements

- libdfu/dfu-cipher-xtea.c
- libdfu/dfu-device.c
- libdfu/dfu-element.c
- libdfu/dfu-patch.c
- libdfu/dfu-self-test.c
- libdfu/dfu-target.c
- libdfu/dfu-tool.c
- libfwupd/fwupd-client.c
- plugins/dfu/fu-plugin-dfu.c
- plugins/raspberrypi/fu-plugin-raspberrypi.c
- plugins/synapticsmst/fu-self-test.c
- plugins/udev/fu-rom-tool.c
- plugins/udev/fu-rom.c
- plugins/uefi/fu-plugin-uefi.c
- plugins/unifying/fu-plugin-unifying.c
- plugins/unifying/lu-device-bootloader.c
- plugins/unifying/lu-tool.c
- src/fu-common.c
- src/fu-engine.c
- src/fu-self-test.c
Many unused variables and const-correctness warnings.
There are some more serious/complicated issues that I'm not sure what is the correct way to fix, so adding them as issues to discuss.
> trivial: cleanup for many compilation warnings from clang

- plugins/thunderbolt/fu-plugin-thunderbolt.c
Following @superm1 steps [here](https://github.com/hughsie/fwupd/commit/1790115c933f57670ec5250ce6d4d5faa0987293), I added a similar message for Thudnerbolt.
A review also for [the wiki page itself](https://github.com/hughsie/fwupd/wiki/Thunderbolt:-Validation-failed-or-unknown-device) would be much appreciated.
> thunderbolt: refer to the wiki on image validation failure

- plugins/thunderbolt/fu-self-test.c
- plugins/thunderbolt/fu-thunderbolt-image.c
Add a small test case. Uncovered already two tiny glitches:
```
FuPluginThunderbolt-DEBUG: expected image validation error [ctl, ctl]: Given location is outside of the given FW ((null))
FuPluginThunderbolt-DEBUG: expected image validation error [dev, dev]: The FW image file is for a host controller
FuPluginThunderbolt-DEBUG: expected image validation error [bad, dev]: The FW image file is for a host controller
FuPluginThunderbolt-DEBUG: expected image validation error [ctl, bad]: Given location is outside of the given FW ((null))
FuPluginThunderbolt-DEBUG: expected image validation error [bad, bad]: Given location is outside of the given FW ((null))
```
NB: the `(null)` and the "for a host controller". Added two simple fixes for those. Now they read:
```
FuPluginThunderbolt-DEBUG: …
```
> Test case for image validation

- contrib/PKGBUILD
- contrib/fwupd.spec.in
- meson_options.txt
- plugins/meson.build
It's not super useful. If this has no bad effects for a couple of releases we
can either remove it completely or move the functionality to the test plugin.
> usb: Disable the fallback USB plugin

- plugins/altos/fu-device-altos.c
- plugins/colorhug/fu-plugin-colorhug.c
- plugins/dfu/dfu-device.c
- plugins/dfu/dfu-device.h
- plugins/dfu/dfu-self-test.c
- plugins/dfu/dfu-tool.c
- plugins/dfu/fu-plugin-dfu.c
- plugins/dfu/meson.build
- plugins/ebitdo/fu-device-ebitdo.c
- plugins/ebitdo/fu-ebitdo-tool.c
- plugins/ebitdo/fu-plugin-ebitdo.c
- plugins/steelseries/fu-plugin-steelseries.c
- plugins/unifying/lu-device.c
- plugins/unifying/meson.build
- plugins/usb/fu-plugin-usb.c
- src/fu-device-locker.c
- src/fu-device-locker.h
- src/fu-engine.c
- src/fu-plugin.h
- src/fu-self-test.c
- src/meson.build
We can use the power of g_autoptr() to automatically close devices that have
gone out of scope. This allows us to drop the AUTO_OPEN_DEVICES flag which was
making us look bad in powertop.
This is WIP, but I figured it would be good to get some early review.
> Add FuDeviceLocker to simplify device open/close lifecycles

- contrib/fwupd.spec.in
- plugins/dell/fu-dell-common.c
- plugins/dell/fu-plugin-dell.c
- plugins/meson.build
- plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c
- plugins/thunderbolt-power/meson.build
This is a WIP with more testing still needed.  Early feedback welcome however.
It wraps around this API being introduced in kernel 4.14:
http://git.infradead.org/linux-platform-drivers-x86.git/commit/d08e3b522bdaccde031a394039b299bfd8c18492
> Add support for the new kernel API for force power

- plugins/uefi/fu-plugin-uefi.c
- src/fu-engine.c
- src/fu-plugin-private.h
- src/fu-plugin.c
- src/fu-plugin.h
The only things that plugins can declare is that they should be run before,
after or never with regard to another plugin.
> Allow plugins to depend on each other

- po/make-images
This was causing problems building on Jessie, and turns out to be unused
anyway:
AttributeError: 'gi.repository.PangoCairo' object has no attribute 'font_map_get_default'
Signed-off-by: Philip Withnall <withnall@endlessm.com>
> po/make-images: Drop unnecessary fontmap

- .travis.yml
- contrib/ci/Dockerfile-ubuntu.in
- contrib/ci/README.md
- contrib/ci/dependencies.txt
- contrib/debian/fwupd.postinst
- contrib/debian/fwupd.preinst
Thanks to @xnox confirming that the systemd postinst bug related to /etc/resolv.conf remaining immutable is fixed can turn on Ubuntu for CI instead of Debian on one of the jobs.
I was originally going to turn on a 6th job, but it seems that maximum number of parallel jobs for Travis is 5, so this increases build time.
> Swap out debian-clang for ubuntu-clang

- plugins/dell/fu-dell-common.c
- plugins/dell/fu-dell-common.h
- plugins/dell/fu-plugin-dell.c
Thanks to fu-smbios it's really easy to block plugins from running on systems they shouldn't now.
Block a few cases that we know the Dell plugin shouldn't be used (and allow easy ways to add more systems to those lists).
> Control more of where Dell plugin runs

- data/tests/builder/meson.build
Previous failure:
```
[1/182] /bin/tar --xform 's,.*/,,' --create --file data/tests/builder/firmware.tar ../fwupd-1.0.0/data/tests/builder/source.bin ../fwupd-1.0.0/data/tests/builder/startup.sh
FAILED: data/tests/builder/firmware.tar
/bin/tar --xform 's,.*/,,' --create --file data/tests/builder/firmware.tar ../fwupd-1.0.0/data/tests/builder/source.bin ../fwupd-1.0.0/data/tests/builder/startup.sh
/bin/tar: ../fwupd-1.0.0/data/tests/builder/source.bin: Member name contains '..'
/bin/tar: ../fwupd-1.0.0/data/tests/builder/startup.sh: Member name contains '..'
/bin/tar: Exiting with failure status due to previous errors
```
> trivial: Use absolute-names in tar command for creating test data file

- contrib/PKGBUILD
The helper specify `-D b_lto=true` though, so override that since it fails to build with it.
> ci: Make use of arch-meson in PKGBUILD

- plugins/dell/fu-plugin-dell.c
- plugins/dell/fu-plugin-dell.h
It's due to multiple uses of libsmbios in a single application (fwupd and libfwup both using it).  Adjust behavior to prevent this from happening.
> There was a crash reported in the dell plugin recently

- docs/libfwupd/libfwupd-docs.xml
- plugins/dfu/dfu-target.c
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/nitrokey/fu-nitrokey-device.c
- plugins/unifying/lu-device.c
- src/fu-debug.c
- src/fu-debug.h
- src/fu-main.c
This allows end-users testing a specific plugin to start fwupd with an extra
command line parameter, e.g. `--plugin-verbose=unifying` to output a lot of
debugging information to the console for that specific plugin.
Plugins can either use the environment variable, or get the verbose mode using
fu_plugin_get_verbose().
This replaces a lot of ad-hoc environment variables with different naming
conventions.
> Add fu_plugin_get_verbose() to enable per-plugin debugging

- plugins/altos/fu-altos-device.c
- plugins/altos/fu-plugin-altos.c
- plugins/dfu/fu-plugin-dfu.c
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/ebitdo/fu-plugin-ebitdo.c
- plugins/nitrokey/fu-nitrokey-device.c
- plugins/raspberrypi/fu-self-test.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/thunderbolt/fu-self-test.c
- plugins/unifying/fu-plugin-unifying.c
- src/fu-device.c
- src/fu-device.h
- src/fu-engine.c
- src/fu-main.c
- src/fu-pending.c
- src/fu-self-test.c
It's actually less scary to see a SHA1 hash than it is to see a path like
/sys/devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.2. It's also way easier to
copy and paste into the various fwupdmgr command that require a device ID.
If we also move to a model where plugins can be changed during different stages
of the update (e.g. during detach) then the device might change connection type
and then the sysfs path not only becomes difficult to paste, but incorrect.
Session software doesn't care about the format of the device ID (it is supposed
to be an implementation detail) and so there's no API or ABI break here.
> Use a SHA1 hash for the internal DeviceID

- src/fu-engine.c
- src/fu-self-test.c
This allows clients to just select the 'first' FwupdRelease for the newest if
there are multiple installable releases.
Fixes https://github.com/hughsie/fwupd/issues/319
> Sort the output of GetUpgrades correctly

- meson.build
- src/fu-self-test.c
Adjust the disabling of the s390x CI test to only run when on newer
gcab.
> Test version of gcab to determine which tests to run (Closes: #318)

- plugins/thunderbolt/fu-plugin-thunderbolt.c
Kernel 4.15 adds support for Thunderbolt P2P devices via
CONFIG_THUNDERBOLT_NET.  When turned on and activated fwupd will
show an empty device representing the IP connection between machines.
These devices aren't useful in fwupd and should be filtered.
> thunderbolt: only accept thunderbolt_device device types

- plugins/altos/fu-plugin-altos.c
- plugins/colorhug/fu-plugin-colorhug.c
- plugins/ebitdo/fu-plugin-ebitdo.c
- plugins/nitrokey/fu-plugin-nitrokey.c
- plugins/steelseries/fu-plugin-steelseries.c
- plugins/usb/fu-plugin-usb.c
- src/fu-engine.c
- src/fu-plugin-private.h
- src/fu-plugin-vfuncs.h
- src/fu-plugin.c
This saves all the USB plugins from connecting to the context and managing the
device lifecycle and allows devices that uses FuUsbDevice to be removed
automatically.
This makes supported plugins *much* smaller indeed.
> Add a fu_plugin_device_added_usb() dedicated vfunc

- plugins/altos/fu-altos-device.c
- plugins/altos/fu-altos-device.h
- plugins/altos/fu-altos-tool.c
- plugins/altos/fu-plugin-altos.c
- plugins/colorhug/fu-colorhug-device.c
- plugins/colorhug/fu-colorhug-device.h
- plugins/colorhug/fu-plugin-colorhug.c
- plugins/dell/fu-plugin-dell.c
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/ebitdo/fu-ebitdo-device.h
- plugins/ebitdo/fu-ebitdo-tool.c
- plugins/ebitdo/fu-plugin-ebitdo.c
- plugins/raspberrypi/fu-plugin-raspberrypi.c
- plugins/raspberrypi/fu-self-test.c
- plugins/synapticsmst/fu-plugin-synapticsmst.c
- plugins/test/fu-plugin-test.c
- plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/uefi/fu-plugin-uefi.c
- plugins/unifying/fu-plugin-unifying.c
- src/fu-device.c
- src/fu-device.h
- src/fu-engine.c
- src/fu-self-test.c
This makes more sense; we're updating the device, not the plugin itself.
This also means we don't need to funnel everything through callbacks like
GFileProgressCallback and we can also update the state without adding an
explicit callback to each derived device type.
> Set the progress and state on the FuDevice, not the FuPlugin

- data/remotes.d/README.md
- data/tests/firmware-nopath.conf
- libfwupd/fwupd-remote.c
- libfwupd/fwupd-self-test.c
If a remote like LVFS outputs <location>foo.cab</location> without a prepended
hostname and path then we should use the metadata URI hostname and path instead.
This allows us to trivially mirror a firmware repository, although clients using
older versions of libfwupd will not work without this patch. We should encourage
people to use `FirmwareBaseURI` for a long time yet.
> Support AppStream metadata with relative <location> URLs

- README.md
The certificate for fwupd.org is invalid for the www subdomain thus killing links to www.fwupd.org
This can be easily fixed here by updating the links
Ideally, the server should be configured to redirect www.fwupd.org to fwupd.org
> Remove www. from links to fwupd.org

- meson.build
- src/fu-common-cab.c
- src/fu-common-cab.h
- src/fu-engine.c
- src/fu-self-test.c
- src/meson.build
Using old versions of gcab we could only do one thing: extract the files in the
cabinet archive to a new directory in /tmp, and then fwupd would have to read
them back in to memory to parse them. This was both inelegant and wasteful, and
probably not an awesome idea from a security or privacy point of view.
Using libgcab >= 1.0 we can decompress to a GBytes blob, and then verify the
firmware and metainfo file without anything being written to disk.
As this is a security sensitive operation, move the fwupd-specific helper code
out of libappstream-glib and also add a lot of internal self tests.
The gcab code will have to remain in libappstream-glib for a long time, but we
don't have to use it. Handling the cab file here also allows us to fix two
long-standing bugs:
* MetaInfo or firmware …
> Use the new functionality in libgcab >= 1.0 to avoid writing temp files

- po/make-images.sh
to prevent it from adding timestamps to .gz headers
to make package builds reproducible
See https://reproducible-builds.org/ for why this is good.
> Use gzip -n

- plugins/dell/fu-plugin-dell.c
Thundebolt controller usually takes some time to wakeup and without
this the update will most likely fail.
> dell: Add a delay when calling update_prepare

- meson.build
- plugins/uefi/fu-plugin-uefi.c
The work for this landed in what will turn into efivar 33.
Later down the road when efivar 33 is in most the major distros
this can be removed and a requirement set for efivar 33.
> Fix UX capsule reference to the one in efivar

- plugins/uefi/fu-plugin-uefi.c
These are devices that UEFI capsule support is turned off in BIOS
setup.  Unlocking them can turn UEFI capsule support
> uefi: Add a device name for locked devices (#364)

- data/installed-tests/fwupdmgr.sh
- src/fu-util.c
In real user tests this was a pain point where we had to manually explain that
they needed to reboot.
> Offer to reboot when processing an offline update

- plugins/ebitdo/ebitdo.quirk
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/ebitdo/fu-ebitdo-tool.c
This causes problems with the real DS4 controller.
Furthermore in MacOS mode fwupd doesn't actually work properly
anyhow (Closes #381)
> plugins/ebitdo: Stop matching DS4 controller VID/PID

- libfwupd/fwupd-self-test.c
Some sandbox environments won't allow creating this file, so skip
this test.
We're still running it on all Travis CI test cases though.
> libfwupd: Allow skipping machine ID self test (Fixes #403)

- plugins/uefi/fu-plugin-uefi.c
This is to support the action plan mentioned in https://github.com/rhboot/fwupdate/issues/66
> uefi: Report if UX capsule was supported in the report metadata

- data/remotes.d/lvfs-testing.conf
- data/remotes.d/lvfs.conf
The current CDN (~$100/month) is kindly sponsored by Amazon, but that won't
last forever. In the future we can switch to a 'dumb' provider like BunnyCDN
for 1/10th of the cost.
Use a CNAME we control to make switching CDN providers easy in the future.
> Use a CNAME to redirect to the correct CDN for metadata

- src/fu-util.c
This makes it more obvious for people that don't know about ctrl-d
> Allow exiting device prompt with a "0" device too

- libfwupd/meson.build
- Name the bindings the same as the pkgconfig file
- Update the GIR bindings to include the appropriate header file which updates
the Vala bindings
> Fix Vala bindings:

- plugins/thunderbolt/fu-thunderbolt-image.c
For unknown device only vendor and model IDs should be checked
Signed-off-by: Yehezkel Bernat <yehezkel.bernat@intel.com>
> thunderbolt: correct handling of unknown devices

- po/make-images
This prevents the following error:
UnicodeEncodeError: 'utf-8' codec can't encode characters in
position 26-28: surrogates not allowed
> Use the right encoding for the label in make-images

- src/fu-util.c
This allows us to use PolicyKit, which means we will get prompted for
authorization if logged in as a user without permissions.
Fixes https://github.com/hughsie/fwupd/issues/455
> Reboot using logind, not directly using systemd

- libfwupd/fwupd-remote-private.h
- libfwupd/fwupd-remote.c
- libfwupd/fwupd-remote.h
- libfwupd/fwupd.map
- po/POTFILES.in
- src/fu-config.c
- src/fu-util.c
We need to show this agreement text in every fwupd frontend and exporting a
helper function allows us to do two things:
* Share the semi-complicated code (and fallback) to avoid copy and pasting
* Easily change the code in the future, for instance allowing merging Metainfo
and AppStream metadata without updating all the front ends with new logic.
> Export fwupd_remote_get_agreement()

- libfwupd/fwupd-client.c
- meson.build
- plugins/altos/fu-altos-device.c
- plugins/altos/fu-altos-firmware.c
- plugins/amt/fu-plugin-amt.c
- plugins/csr/fu-csr-tool.c
- plugins/dell/fu-dell-smi.c
- plugins/dell/fu-plugin-dell.c
- plugins/dfu/dfu-tool.c
- plugins/synapticsmst/synapticsmst-common.h
- plugins/synapticsmst/synapticsmst-tool.c
- plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/thunderbolt/fu-self-test.c
- plugins/uefi/fu-plugin-uefi.c
- plugins/unifying/lu-context.c
- plugins/unifying/lu-device-bootloader.h
- plugins/unifying/lu-device.c
- plugins/unifying/lu-hidpp-msg.h
- plugins/unifying/lu-tool.c
- src/fu-common.c
- src/fu-history.c
- src/fu-keyring-pkcs7.c
- src/fu-main.c
- src/fu-util.c
GLib creates two static inline functions for paramaters that may
not be used that set off warnings in clang but not gcc.
Ignore these on clang builds.
> Disable -Wunused-function on clang builds (Closes #467)

- plugins/test/meson.build
- plugins/upower/meson.build
This is a workaround for what looks like a compiler bug introduced
in Debian and Ubuntu gcc-7.
After the compiler bug is sorted in Debian testing it should be
reverted.
> trivial: Compile upower and test plugins with -O0 (Closes: #472)

- plugins/uefi/meson.build
- plugins/uefi/uefi.conf.in
This will make it more obvious which path it's defaulting to
> uefi: Match the bootdir argument to fill in uefi.conf by default

- data/bash-completion/fwupdmgr
- libfwupd/fwupd-client.c
- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd.map
- plugins/amt/fu-plugin-amt.c
- plugins/dell/fu-plugin-dell.c
- plugins/synapticsmst/fu-plugin-synapticsmst.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/thunderbolt/fu-thunderbolt-known-devices.h
- plugins/uefi/fu-plugin-uefi.c
- plugins/unifying/lu-device-peripheral.c
- src/fu-device-list.c
- src/fu-device-private.h
- src/fu-device.c
- src/fu-device.h
- src/fu-engine.c
- src/fu-plugin.c
- src/fu-self-test.c
- src/fu-util.c
This allows us to find out the logical parent device, for instance in composite
devices with more than one firmware image for a single device.
> Add fwupd_device_get_id_parent()

- data/bash-completion/fwupdmgr
- src/fu-util.c
They are hidden from get-devices, get-updates, and get-topology
They can be viewed by adding '--show-all-devices' to command line
> fwupdmgr: Hide devices that aren't updatable by default

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- src/fu-device-private.h
- src/fu-device.c
- src/fu-main.c
- src/fu-self-test.c
For comment -- I'm not particularly happy with the name of `child_flags`. Other ideas welcome.
> Allow plugins to define the order composite firmwares are installed

- contrib/fwupd.spec.in
- data/remotes.d/meson.build
- src/fu-config.c
This means we can avoid loading a ton of non-fwupd files, and reduces our
running RSS from 5.4Mb to 2.8Mb. Old versions of appstream-glib caches a lot of
the localization string data which we just don't care about for firmware files.
> Do not use the system metainfo location

- plugins/uefi/fu-plugin-uefi.c
Several places in the UEFI plugin operate on the default GUID rather
than iterating a list of GUIDs.  This is normally fine since UEFI
GUIDs are tied to the ESRT and normally one FuDevice shouldn't
have multiple GUIDs.
The alternate GUID was added to set parents accordingly but this
caused no CAB files to be able to install.
Fixes: cc664d7d (amt: Put the AMT device as a child under the system UEFI firmware)
> uefi: Set the alternate GUID for parenting later

- plugins/uefi/fu-plugin-uefi.c
- src/fu-device.c
- src/fu-device.h
Using just the default GUID is fragile and might break if the GUIDs get added
in the 'wrong' order or if the GUID list is sorted.
Fixes https://github.com/hughsie/fwupd/issues/518
> uefi: Search all available GUIDs when matching hardware

- data/bash-completion/fwupdtool
- data/bash-completion/fwupdtool.in
- data/bash-completion/meson.build
- src/fu-engine.c
- src/fu-engine.h
- src/fu-plugin-list.c
- src/fu-plugin-private.h
- src/fu-plugin.c
- src/fu-tool.c
When developing code it's really convenient to only run the new plugin. This
means you don't have to wait for the other hardware to initialize and there
are no side-effects from other plugins when installing firmware.
You can specify multiple plugins as globs, for instance:
fwupdtool get-devices \
--plugin-whitelist wacom \
--plugin-whitelist "thunderbolt*"
> Allow whitelisting plugins in fwupdtool

- data/org.freedesktop.fwupd.metainfo.xml
This is required for flathub as fwupd can send the optional firmware report to
the LVFS web service.
> trivial: Add a OARS content rating

- src/fu-hwids.c
- src/fu-self-test.c
As it turns out, the major and minor BIOS version should also be
represented in hex format in the hash, but in contrast to the
enclosure type, always on 2 digits, padded if necessary.  There is no
decimal value in any of the hashes, it seems.
The previous data, I tested with didn't include major/minor version
numbers bigger than 9, so the issue didn't materialize.
> More Microsoft compatibility fixes around bios major/minor version

- plugins/uefi/fu-plugin-uefi.c
Fixes: 988e73c414e866483dd07fc8aeb37bf65aab9e44
> trivial: uefi: Don't return NULL matching devices

- .gitignore
- .travis.yml
- contrib/ci/Dockerfile-flatpak.in
- contrib/ci/README.md
- contrib/ci/dependencies.xml
- contrib/ci/flatpak.sh
- contrib/ci/generate_docker.py
- contrib/org.freedesktop.fwupd.json
This allows me to make a flatpak, and either export it to a store like "flathub" (although, the store is more geared-up for GUI applications rather than tools that need to be run as root...) or more usefully to a single-file flatpak bundle that means I can install a .cab file on older version of RHEL.
I don't think producing a flatpak on every commit (i.e. wiring it up to travis) makes sense. On one hand it might be useful to see if fwupd still builds against all the deps, but on the other it's hugely wasteful as we'd have no flatpak cache and so we'd download the big runtime and build every dep on every new PR. I'm also not sure how you'd tell flatpak builder to use a git URI of `file://../..`.
I used the tarball releases of all the deps except smbios_c and fwupd itself as flathub …
> Add support for building a flatpak bundle

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/ebitdo/fu-ebitdo-device.h
- plugins/ebitdo/fu-plugin-ebitdo.c
- plugins/unifying/lu-device-bootloader.c
This is useful to present to the user using the command line, and means each
FuDevice-deriving object does not have to handle this.
> trivial: Add a FuDevice flag to show the device is in bootloader mode

- .gitignore
- contrib/ci/Dockerfile-snap.in
- contrib/ci/snap.sh
- contrib/snap/fwupdtool.wrapper
- contrib/snap/libefivar-fixpkgconfig/Makefile
- contrib/snap/snapcraft.yaml
- snap
There are 4 build systems that can be used for generating snaps:
* Travis CI (in a docker container)
* build.snapcraft.io
* Launchpad
* LXC
So after reading and experimenting with the pros/cons of the various different approaches I think the best thing to do is to keep snapcraft.yaml in tree (contrib/snap/) and them symlink the snap directory to top level (to let it build with build.snapcraft.io).
Here's my reasoning:
1) You don't need to cache credentials into Travis that will expire in 1 year.
2)  It will build automatically on pushes to master and publish them to the "edge" channel in the snap store.  That means anyone running a distro with snapd can easily test master with fwupdtool.
3) Using LXC locally means just that - need to generate snaps on demand.
I've done some tests with …
> Add snap build scripts

- src/fu-engine.c
- src/fu-plugin.c
Fixes a segfault that occurs during cleanup of USB plugins.
When g_module_close was called memory allocated by the plugin would
get freed leading to the finalize method for object class pointing
to garbage.
> Clean up plugins as the last step of engine cleanup (Closes: #550)

- src/fu-engine.c
This can be used to select the AA.BB.CC.DD format rather than the default
AA.BB.CCDD format for firmware versions. This allows us to support new vendor
requirements without adding more complicated rules to the quirk file.
> trivial: Allow firmware files to select a quad version format

- src/fu-device.c
- src/fu-self-test.c
With some instrumented testing I was finding that without
FWUPD_DEVICE_FLAG_INSTALL_PARENT_FIRST being set that the parent
was installing first.
The parent was getting set to order "0" and child order "1".  So when the array was sorted, parents were getting installed first.
> trivial: Correct the install task ordering

- COMMITMENT
This is part of more broader commitment Red Hat along with IBM, Google, and
Facebook made in November 2017.
More on this can be found online:
https://www.redhat.com/en/blog/fostering-greater-open-source-development &
https://www.redhat.com/en/about/gplv3-enforcement-statement
> Add COMMITMENT file as part of GPL Common Cure Rights Commitment

- meson.build
Commit 83d46b05792 bumped the minimum meson version to 0.46.0
This makes building on current Ubuntu LTS release more difficult
as it contains 0.45.0.
Instead conditionalize the build to run that code when on newer
meson.
This commit can be reverted when it's appropriate to bump meson
build dependency.
> Continue to allow building with older meson

- contrib/ci/README.md
- contrib/ci/debian_s390x.sh
- contrib/fwupd.spec.in
- meson.build
- meson_options.txt
- plugins/meson.build
- plugins/redfish/README.md
- plugins/redfish/fu-plugin-redfish.c
- plugins/redfish/fu-redfish-client.c
- plugins/redfish/fu-redfish-client.h
- plugins/redfish/fu-redfish-common.c
- plugins/redfish/fu-redfish-common.h
- plugins/redfish/fu-self-test.c
- plugins/redfish/meson.build
Redfish is an open industry standard specification and schema that helps enable
simple and secure management of modern scalable platform hardware.
This has only ever been tested using an emulator and not on real hardware.
> redfish: Add a plugin that uses the Redfish API

- plugins/redfish/fu-redfish-client.c
In the redfish emulator, "/redfish/v1" returns "ServiceVersion".
However, in the HPE API explorer(*), it returns "RedfishVersion".
This commit checks both member and print the one that is available.
(*) https://ilorestfulapiexplorer.ext.hpe.com/
> redfish: Amend the retrieval of version

- contrib/firmware-packager/firmware-packager
- libfwupd/generate-version-script.py
- plugins/dfu/contrib/parse-avrdude-conf.py
- po/make-images
- po/test-deps
According to Fedora policy env must not be used as it could be overridden by
values in the PATH.
For details, https://fedoraproject.org/wiki/Packaging:Guidelines#Shebang_lines
> Do not use /usr/bin/env in the shebang line

- plugins/dell/fu-plugin-dell.c
- plugins/dell/fu-plugin-dell.h
The minimum version of libsmbios is now 2.4, so don't include any
code blacklisting running on known failing systems.
> trivial: dell: drop blacklist of old systems

- plugins/synapticsmst/fu-plugin-synapticsmst.c
- plugins/synapticsmst/synapticsmst-device.c
- plugins/synapticsmst/synapticsmst-device.h
At least in my experience there's some situations that dock information doesn't show up, but this shouldn't block synaptics from init.
If the dock information is available then show that in the device name
and restrict the GUIDs created.
If it's not available, then just create GUIDs for all known docks
> synapticsmst: Drop the dependency on Dell plugin to populate devices

- plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c
This should help issues where the TBT controller takes a longer
time to run at cold boot startup.
Refer to https://bugzilla.kernel.org/show_bug.cgi?id=199631 for
more information.
> thunderbolt-power: Reset the timer on every TBT add uevent

- src/fu-engine.c
Some firmware depends on this component, which we absorbed in the last release.
See also: https://github.com/hughsie/fwupd/issues/614
> trivial: Add a virtual provide of com.redhat.fwupdate

- src/fu-device-list.c
- src/fu-device-private.h
- src/fu-device.c
- src/fu-engine.c
- src/fu-plugin-list.c
- src/fu-plugin-private.h
- src/fu-plugin.c
- src/fu-plugin.h
- src/fu-self-test.c
In this instance, we define the 'same device' to be a FuDevice that has at
least one matching GUID. We allow the plugins to define which one is 'better'
than other plugins, and use this to only have one FuDevice for the physical
device.
Alternative to https://github.com/hughsie/fwupd/pull/604
> Allow different plugins to add the same device

- plugins/uefi/efi/meson.build
Fixes https://github.com/hughsie/fwupd/issues/631
> uefi: Don't override _FORTIFY_SOURCE when building the EFI binary

- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-common.c
- plugins/uefi/fu-uefi-common.h
- plugins/uefi/fu-uefi-tool.c
Additionally, if the user specified something invalid, do not autodetect the
ESP but return with a journal error. It seems wrong to ignore what the user
explicitly set and perhaps do something dangerous.
Alternative to https://github.com/hughsie/fwupd/pull/599
> uefi: Check the user-supplied ESP path

- plugins/uefi/fu-uefi-device.c
Before:
```
$ /usr/lib/fwupd/fwupdate --info
Information for the update status entry 0:
Information Version: 7
Firmware GUID: {00000000-0000-0000-0000-000000000000}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Capsule Flags: 0x00131072x
Hardware Instance: 0
Update Status: attempt-update
Capsule File Path: /EFI/ubuntu/fw/fwupd-7ceaf7a8-0611-4480-9e30-64d8de420c7c.cap
```
After:
```
$ /usr/lib/fwupd/fwupdate --info
Information for the update status entry 0:
Information Version: 7
Firmware GUID: {7ceaf7a8-0611-4480-9e30-64d8de420c7c}
Capsule Flags: 0x00131072x
Hardware Instance: 0
Update Status: attempt-update
Capsule File Path: /EFI/ubuntu/fw/fwupd-7ceaf7a8-0611-4480-9e30-64d8de420c7c.cap
```
> uefi: Fix encoding the GUID into the capsule EFI variable

- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/thunderbolt/fu-thunderbolt-image.c
This adds NVM image validation for Titan Ridge based Thunderbolt 3 devices. In addition there are few other improvements over the current code:
-  PD (Power Delivery) pointer validation
-  EAGAIN handling to other places reading nvm_version
> NVM image validation for Titan Ridge devices and other improvements

- data/meson.build
- plugins/uefi/fu-uefi-common.c
/boot is a special cased directory when using ProtectSystem=full
Due to this, it's marked read only even if it's listed in ReadWritePaths.
Allow folks to use this for their ESP, but they need to create /boot/EFI
in advance of starting fwupd.
> uefi: Handle /boot properly (Closes: #627)

- src/fu-engine.c
This isn't useful for most people and just takes up space in the logs.
When there is a problem it's typically specifically with a plugin
and at that time we ask them to run the daemon with verbose anyway.
> trivial: fu-engine: downgrade "Using Plugins %s" to debug

- plugins/synapticsmst/fu-plugin-synapticsmst.c
It generally won't be interesting on most systems, but if a supported
Dell USB device is connected to a non-dell system it can be updated
then.
> synapticsmst: Run the plugin on non-dell systems

- src/fu-engine.c
At least in my experience coldplug can take a while (especially when
Thunderbolt is involved).
> fu-tool: Show a message during initialization

- src/fu-tool.c
This is the same problem that happened with 3f9a1c182a4b05d641680e9505c24e10d75cfe3e.
The USB plugins got closed but left a dangling reference to a device.
> fu-tool: Fix a segfault caused by cleanup of USB plugins

- contrib/snap/fwup-efi-signed/Makefile
- contrib/snap/fwup-efi-signed/download-fwupd
It took some time for the round trip to sort out.  Download the latest
signed fwupd binary rather than fwupdate binary.
> trivial: snap: Download signed fwupd instead of signed fwupdate

- meson.build
- po/make-images.sh
- po/meson.build
This overrides the interpreter used for building UEFI labels.
> meson: Add a new configuration option 'python3'

- plugins/uefi/fu-uefi-common.c
systemd-automount will unmount the ESP when not in use for some
people.  This causes automatic ESP detection to fail.
In this case the ESP will need to be added to the conf file and
then this commit will let it keep working.
> uefi: Add 'autofs' to supported filesystems (Closes: #660)

- src/fu-util.c
The frontend was never notified of the release (and didn't parse the CAB) so
it doesn't know at this time what the version of the release is and
so this shows a NULL assertion at the time.
> fu-util: When processing "install" command don't try to show current release

- plugins/dell/fu-plugin-dell.c
- plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c
- plugins/upower/fu-plugin-upower.c
- src/fu-engine.c
- src/fu-plugin-private.h
- src/fu-plugin-vfuncs.h
- src/fu-plugin.c
Configure the UEFI plugin to support reading in quirks for the flags, and for Dell systems to specifically not require AC for the update to be scheduled.
> Allow overriding AC power requirements with --force

- plugins/colorhug/fu-colorhug-device.c
- plugins/colorhug/meson.build
- plugins/csr/fu-csr-device.c
- plugins/dfu/dfu-self-test.c
- plugins/dfu/dfu-target-avr.c
- plugins/dfu/dfu-target-stm.c
- plugins/dfu/meson.build
- plugins/wacomhid/fu-wac-device.c
- plugins/wacomhid/fu-wac-module-bluetooth.c
- plugins/wacomhid/fu-wac-module-touch.c
- plugins/wacomhid/fu-wac-module.c
- src/fu-chunk.c
- src/fu-chunk.h
- src/fu-self-test.c
- src/meson.build
Five plugins (soon to be 7) are linking to the DFU plugin just for this simple
segment-aware chunking functionality. Move this into common code to make
building simpler.
> trivial: Move out the byte-array chunking to libfwupdprivate

- plugins/unifying/lu-device-peripheral.c
- plugins/wacomhid/fu-wac-device.c
This fixes a trivial duplicated line, and corrects a check if a flag is set in an error path. This is just to fix some warnings, and is untested as I do not have wacom hardware to test with.
> Fix a few warnings

- data/meson.build
- plugins/uefi/fu-uefi-common.c
This is a similar problem to #627 (which was fixed by 9bdbbc5ca).
Add special handling to allow writing to `/efi/EFI`
> uefi: Add special handling for /efi (Closes #680)

- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-bootmgr.c
- plugins/uefi/fu-uefi-bootmgr.h
- plugins/uefi/fu-uefi-device.c
- plugins/uefi/uefi.conf
(Saw you forgot to add PR for this)
This doesn't require shim, so for this uncommon case add a configure option.
Fixes https://github.com/hughsie/fwupd/issues/669
> uefi: Allow upgrades using a self-signed fwupd.efi binary

- plugins/dfu/dfu-device.c
- plugins/dfu/dfu-tool.c
- src/fu-device-locker.c
- src/fu-device.c
- src/fu-device.h
- src/fu-usb-device.c
- src/fu-usb-device.h
This just reduces our API surface a little, no behaviour change.
> trivial: Use the new subclassed device methods

- contrib/fwupd.spec.in
- plugins/flashrom/README.md
- plugins/flashrom/example/build.sh
- plugins/flashrom/example/com.Flashrom.Laptop.metainfo.xml
- plugins/flashrom/example/random-tool
- plugins/flashrom/example/startup.sh
- plugins/flashrom/flashrom.quirk
- plugins/flashrom/fu-plugin-flashrom.c
- plugins/flashrom/meson.build
- plugins/meson.build
This reworks the old `purism` plugin to be a generic flashrom mechanism that can be used by any vendor by dropping in a quirks file.
> flashrom: Add a plugin for updating using the flashrom command line tool

- plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c
This is new support for bolt supported by
https://gitlab.freedesktop.org/bolt/bolt/merge_requests/101
> thunderbolt-power: Use bolt force power API if available

- plugins/synapticsmst/fu-plugin-synapticsmst.c
- plugins/synapticsmst/synapticsmst-device.c
- plugins/synapticsmst/synapticsmst-device.h
- plugins/synapticsmst/synapticsmst.quirk
This flag is intended for devices that the restart procedure will
be performed as part of a transactional update by an external
controller.
None of the currently supported devices need this flag.
> synapticsmst: Allow using a custom flag 'skip-restart'

- plugins/altos/fu-plugin-altos.c
- plugins/colorhug/colorhug.quirk
- plugins/dfu/dfu.quirk
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/nitrokey/nitrokey.quirk
- plugins/unifying/lu-device-runtime.c
- src/fu-device-list.c
- src/fu-device.c
- src/fu-device.h
- src/fu-quirks.h
These are GUIDs that are related to the main device, but should not be used for
quirk matching. For instance, we might want to list the GUIDs for a bootloader
mode, but we don't want to import all the quirks for the bootloader when in the
runtime mode.
> Add support for counterpart GUIDs

- src/fu-progressbar.c
We can't pretend we're accurate to 10m in the precision of the float when we're
doing things like USB re-enumeration which can take several seconds. I believe
users want some indication of 'should I wait or go do something else' rather
than any precise timings.
> trivial: Display a more natural string for the time remaining

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/colorhug/fu-colorhug-device.c
- plugins/colorhug/fu-plugin-colorhug.c
- plugins/dfu/fu-plugin-dfu.c
- plugins/ebitdo/fu-plugin-ebitdo.c
- src/fu-device-list.c
- src/fu-device-list.h
- src/fu-engine.c
- src/fu-self-test.c
This means that individual plugins do not have to manage thier own GUsbDevice
lifecycle and call g_usb_context_wait_for_replug().
This is only lightly tested and is for sanity review only :)
> Allow the device list to take care of waiting for the device replug

- plugins/amt/fu-plugin-amt.c
- plugins/synapticsmst/fu-plugin-synapticsmst.c
- plugins/uefi/fu-uefi-device.c
- src/fu-device-list.c
Recent changes in the daemon have caused these devices to start matching
as existing devices based on platform ID comparisons.
> plugins: Set platform IDs for non-USB/non-UDEV plugins

- src/fu-device.c
This fixes issues where the child gets the same ID as the parent.
> fu-device: Add platform ID after creating GUID for children

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- src/fu-install-task.c
This flag isn't really intended for production, but more for development
to allow setting a quirk for a device during a transition period.
Setting the flag causes FwupdInstallFlags to contain
FWUPD_INSTALL_FLAGS_FORCE whether or not --force was passed on the tool
command line.
As an example use case earlier versions of a Thunderbolt module may contain DROM corresponding to one model ID and transition to another model ID.  Even if lying about the GUIDs supported by the device via a quirk the Thunderbolt validation will fail because the device isn't intended for that system.
> Add a new device flag "force" that will always override validation

- plugins/dell/dell.quirk
- plugins/synapticsmst/synapticsmst.quirk
- plugins/thunderbolt/meson.build
- plugins/thunderbolt/thunderbolt.quirk
These quirks aren't really needed if compiled without the Dell plugin
since they just set the parentage.
> trivial: move all Dell dock related quirks into dell.quirk

- libfwupd/fwupd-device-private.h
- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-enums.h
- libfwupd/fwupd.map
- src/fu-device.c
- src/fu-device.h
- src/fu-main.c
This moves the storing of the serial number into the daemon and
when the calling process is UID 0 includes it in device output
> Include serial number in daemon device output when trusted

- src/fu-device.c
device ID might not yet be initialized, so just show the word
"unknown"
> trivial: fu-device: don't show messages with (null) for device ID

- plugins/unifying/fu-unifying-peripheral.c
- plugins/unifying/fu-unifying-runtime.c
- src/fu-device.c
- src/fu-device.h
- src/fu-self-test.c
This is used by two device types in the unifying plugin, and soon to be one
other new plugin.
> trivial: Move the poll setup into common code

- src/fu-engine.c
Fixes part of http://gitlab.gnome.org/GNOME/gnome-software/issues/341
> fu-engine: Don't show devices pending a reboot in GetUpgrades

- .gitignore
- contrib/standalone-installer/README.md
- contrib/standalone-installer/assets/header.py
- contrib/standalone-installer/make.py
This is meant to produce standalone installer binaries that can operate
on machines without current tools or internet access.
It works by wrapping around the container technologies snap and flatpak
and putting all the pieces together.
> contrib: Add a standalone installer creation script

- plugins/nvme/meson.build
- plugins/nvme/nvme.quirk
I've seen a firmware image that the version was "80001C0T" for this
disk and as such this is not a "quad" version number.
> trivial: nvme: Remove quirk for Hynix SSD

- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd.map
- src/fu-device.c
- src/fu-device.h
- src/fu-quirks.h
This time is provided to frontends to be able to show estimates
before a user would agree to flash the device.
> Add support for devices to show an estimated flash time (Closes: #765)

- src/fu-device-list.c
- src/fu-engine.c
This sets up handling for replug on composite devices.  If one device causes another to go into replug, the plugin can indicate this in `composite_prepare`  and then the daemon will do the right thing to find the device before calling update on it.
Regarding tests, I'm aware that this is fragile and I would like some advice which aspect should actually have the tests because it almost feels like the whole flow needs to be modeled in a test meaning a test that produces a few devices like this, instantiates a plugin, sets up relationships and then calls out to the daemon to do install tasks from a CAB with a few things in it.  It's sorta a big test then..
> Composite device replug support

- src/fu-debug.c
This makes it easier for tools to still remain functional but capture
relevant debugging logs by calling `fwupdtool` with `--verbose 2>log`
> fu-debug: Redirect all debugging output to stderr instead of stdout

- src/fu-engine.c
I've found that this message comes up sometimes due to reprobing order
and it shouldn't be considered important enough to generate a warning.
> trivial: fu-engine: downgrade couldn't find new device message to debug

- contrib/vscode/README.md
- contrib/vscode/build.sh
- contrib/vscode/launch.json
- contrib/vscode/launcher.sh
At least for me it was a challenge to get the debugger properly
configured to allow debugging fwupd when built in tree.
This should allow very simple debugging.
> contrib: Add information on how to use debugging scripts

- plugins/dell-dock/fu-dell-dock-i2c-mst.c
> dell-dock: correct a scenario where an error message might not be set

- plugins/dell-dock/dell-dock.quirk
- plugins/dell-dock/fu-dell-dock-i2c-mst.c
When updating over I2C instead of DP aux one of the calls for unlock isn't happening anymore, fix that.
> Add missing unlock call for MST via dell_dock plugin

- contrib/ci/Dockerfile-fedora.in
- contrib/ci/Dockerfile-flatpak.in
- contrib/ci/dependencies.xml
- contrib/ci/flatpak.sh
- contrib/fwupd.spec.in
- contrib/org.freedesktop.fwupd.json
- meson.build
- src/fu-common-cab.c
- subprojects/libxmlb.wrap
This allows composite firmware to be ordered in an explicit way. Needs CI fixes, but those depend on a libxmlb 0.1.3 release which I can do Monday.
> Sort the firmware sack by component priority

- plugins/dell-dock/fu-plugin-dell-dock.c
- plugins/synapticsmst/fu-plugin-synapticsmst.c
Although this is (currently) slower to flash with, bad behavior
and corner case scenarios such as these don't occur:
* Flickering during enumeration
* Monitor plugged in during enumeration but not during flash
* Heavy DP traffic slowing down update significantly
* Sandboxes without access to `/dev/drm_dp_auxY` unable to flash
* Exercising existing graphics driver bugs leading to system freezes.
Additionally this removes a lot of code in dell_dock that was put
in place specifically to be able to support waking up the MST hub
to try to use DP aux for flashing.
Now DP aux will only be used to flash when fwupd is compiled
without `dell_dock`.
> dell-dock: Prefer to flash VMM5331 via I2C instead of DP aux

- plugins/ebitdo/ebitdo.quirk
The USB ids clash with the Xbox controller ids. This makes the Xbox controller unusable since fwupd unloads the device just after connecting it and fails to update it not being a 8bitdo device.
This is specially critical since the Xbox controller is one of the most commonly used.
As seen here: https://github.com/paroj/xpad/issues/114
> ebitdo: remove clashing SF30/SN30 pro device ids

- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- src/fu-common-version.c
- src/fu-common-version.h
- src/fu-device.c
- src/fu-device.h
- src/fu-self-test.c
The most important change here is that versions without dots (not a 'semver')
are treated as 'PLAIN' rather than 'UNKNOWN'.
> Guess the version format when it is not provided

- contrib/ci/Dockerfile-fedora.in
- meson.build
- src/fu-engine.c
- subprojects/libxmlb.wrap
This speeds up matching for GUIDs by about 90%, taking the query from 3.17ms to
about 0.33ms on my Thinkpad. This is more important for slow ARM hardware,
where strcmp() is more expensive than on x64.
> Create a silo index to speed up GUID queries

- plugins/dell/dell.quirk
- src/fu-engine.c
This metadata key is now unnecessary, as firmwares are expected to set the
version format in the metadata.
If the metadata is missing, the LVFS allows a per-vendor default for non-semver
release versions which is now unconditionally set in metadata.
> Remove DaemonVersionFormat=quad

- src/fu-archive.c
- src/fu-archive.h
- src/fu-self-test.c
- src/meson.build
This allows plugins to load an archive supplied as the 'deliverable' of the
cabinet archive. This means plugins can bundle up a set of images in a cross
platform way, for instance adding boot.img+os.img+manifest.xml into a zip file,
rather than having to (ab)use the DfuSe file format or deal with libarchive
directly.
> Provide a way for plugins to decompress a custom archive to ram

- src/fu-device.c
- src/fu-device.h
This matches the behaviour of fu_device_add_guid().
> trivial: Allow calling fu_device_has_guid() with non-GUID text

- src/fu-progressbar.c
This fixes the progressbar going crazy when using fwupdmgr with zh_CN.
> trivial: Correctly calculate the erase length for all locales

- plugins/dfu/dfu.quirk
- plugins/dfu/fu-plugin-dfu.c
This makes startup quicker as we no longer have to probe every USB device, and
is now possible with the new GUIDs we added. Devices not using the
specification-provided values can (and already are) worked around with quirks.
> dfu: Require a specific USB class and subclass for DFU mode

- plugins/unifying/fu-plugin-unifying.c
Require a quirk match for Unifying hardware to avoid probing a lot of USB
devices at startup.
> trivial: Speed up daemon startup

- plugins/dell-dock/fu-dell-dock-i2c-mst.c
This mirrors the update process over DP aux to run the ESM update
first.
The thought process is as follows:
The "version" displayed doesn't show ESM version, only standard
bank version.
So if the update fails for the ESM then because the update of the
standard happening first it would never be flashed.
> trivial: dell-dock: reverse MST update order for I2C

- src/fu-device.c
- src/fu-self-test.c
This converts versions like 'v1.2.3' into a valid semver of '1.2.3' if the
version format has been set.
Fixes https://github.com/hughsie/fwupd/issues/884
> Sanitize the version if the version format has been specified

- plugins/dell/fu-self-test.c
- plugins/uefi/efi/fwupdate.c
- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-bootmgr.c
- plugins/uefi/fu-uefi-device.c
- plugins/uefi/fu-uefi-device.h
This allows using better heuristics and potentially phasing this out in the future.
This idea was mentioned in #889 .
It's not yet tested. @hughsie can you arrange for one of the affected machines that need header added to be tested against it?
> uefi: Append the header on capsules without headers from Linux

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd.map
- plugins/altos/fu-plugin-altos.c
- plugins/colorhug/fu-plugin-colorhug.c
- plugins/csr/fu-plugin-csr.c
- plugins/dell-dock/fu-plugin-dell-dock.c
- plugins/dfu/fu-plugin-dfu.c
- plugins/ebitdo/fu-plugin-ebitdo.c
- plugins/fastboot/fu-plugin-fastboot.c
- plugins/flashrom/fu-plugin-flashrom.c
- plugins/nvme/fu-plugin-nvme.c
- plugins/redfish/fu-plugin-redfish.c
- plugins/rts54hid/fu-plugin-rts54hid.c
- plugins/rts54hub/fu-plugin-rts54hub.c
- plugins/synapticsmst/fu-plugin-synapticsmst.c
- plugins/test/fu-plugin-test.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/uefi/fu-plugin-uefi.c
- plugins/unifying/fu-plugin-unifying.c
- plugins/wacom-usb/fu-plugin-wacom-usb.c
- src/fu-engine.c
- src/fu-plugin.h
Future metadata from the LVFS will set the protocol the firmware is expected to
use. As vendors love to re-use common terms like DFU for incompatible protocols,
namespace them with the controlling company ID with an approximate reverse DNS
namespace.
This also allows more than one plugin to define support for the same protocol,
for instance rts54hid+rts54hub and synapticsmst+dell-dock.
> Allow plugins to define support for a 'well-known' protocol

- plugins/synapticsmst/README.md
Hi fwupd developers,
First of all many thanks for your all efforts and work put into this project!
This PR adds the Dell TB18DC docking station to the readme of the synapticsmst plugin which might be helpful to others in the future. 
I have a Dell Precision 7530 with a TB18DC dock. Upgrading the Synaptics MST chips failed with the official tools on Windows, but the fwupd lists them properly so it turned out that they have the latest (3.12.0.2) firmware so all of my unsuccessful efforts of the upgrade was pointless on Windows.
> Add TB18DC to the synapticmst plugin list

- meson.build
- plugins/altos/meson.build
- plugins/amt/meson.build
- plugins/colorhug/meson.build
- plugins/csr/meson.build
- plugins/dell-dock/meson.build
- plugins/dell-esrt/meson.build
- plugins/dell/meson.build
- plugins/dfu/meson.build
- plugins/ebitdo/meson.build
- plugins/fastboot/meson.build
- plugins/flashrom/meson.build
- plugins/nitrokey/meson.build
- plugins/nvme/meson.build
- plugins/redfish/meson.build
- plugins/rts54hid/meson.build
- plugins/rts54hub/meson.build
- plugins/steelseries/meson.build
- plugins/superio/meson.build
- plugins/synapticsmst/meson.build
- plugins/test/meson.build
- plugins/thunderbolt-power/meson.build
- plugins/thunderbolt/meson.build
- plugins/udev/meson.build
- plugins/uefi/meson.build
- plugins/unifying/meson.build
- plugins/upower/meson.build
- plugins/wacom-usb/meson.build
- src/meson.build
This allows us to find undefined references at compile time, not runtime.
> Fix building with -Wl,-z,defs

- src/fu-main.c
Downgrade this to debugging instead. (Fixes: #912)
> fu-main: remove incompatible locale error message

- plugins/dell-dock/dell-dock.quirk
- plugins/dell-dock/fu-dell-dock-common.c
- plugins/dell-dock/fu-dell-dock-common.h
- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/dell-dock/fu-dell-dock-i2c-mst.c
This resets the minimum requirement in fwupd to board ID #4.  Really it's still all API compatible, but cleans up the code for stuff that will never be seen in production.
> dell-dock: Fixes for board 4

- plugins/modem-manager/fu-mm-device.c
A modem may report several "update methods" via the
MMModemFirmwareUpdateMethod flags.
E.g. there may be cases where some files should be downloaded via
fastboot, and other files via QMI PDC.
> modem-manager: MMModemFirmwareUpdateMethod is a flag mask

- plugins/dell-dock/fu-dell-dock-i2c-ec.c
Some SKUs of board 4 and later have silicon that will not work with anything
but EC19 or later.  So once flashed up to EC19 prohibit downgrades below that
to keep from bricking devices.
> trivial: dell-dock: Prohibit downgrades on board 4 or later below EC19

- plugins/upower/fu-plugin-upower.c
On any devices that normally would require checking for AC also
check that at least one battery on the system has at least 30% to
perform an update.
Fixes: #925
> upower: Add support for checking battery percentage

- plugins/uefi/fu-uefi-bgrt.c
Microsoft description about the Status is:
The Status field of the BGRT describes whether the image is currently
displayed on the screen. This is not applicable to the firmware update
display capsule.
Many thanks to Steven Chang for identifying this issue.
Fixes: https://github.com/hughsie/fwupd/issues/935
> uefi: Do not check the BGRT status before uploading a UX capsule

- src/fu-engine.c
If the device is rebooted into a different shape, the plugin managing
the device may also be different.
This would be the case for plugins that just subclass the update_detach()
method, and leave to other plugins the actual required update procedure.
> Check if plugin changed after the device attaches or detaches

- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
It's currently a hodge podge of commands that can install files not
always invoking a reboot or shutdown.
Move the actual code into `fu-util-common.c` and make sure that all
`install` and `update` functions call it now.
> fu-util/fu-tool: sync up reboot and shutdown behavior

- src/fu-common-cab.c
This prevents a critical warning from gcab_folder_get_file_by_name()
> trivial: Never allow the content checksum filename to be NULL

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd.map
- src/fu-engine.c
The source URL allows us to comply with our various obligations when shipping
firmware built from GPL licensed sources. The details URL allows vendors to
include a link to a full HTML details page about the specific release.
> Add support for a per-release source and details URL

- libfwupd/fwupd-common.c
- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-tool.c
- src/fu-util.c
The idea is that if the user should know something about the device update
"after" it's succesfully completed then the plugin can set `UpdateMessage`
for the device and a client can show it.
An example would be a device that doesn't reboot on its own and the user
needs to power cycle it manually.
> Add support for an `UpdateMessage` and display it in tools

- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-bootmgr.c
- plugins/uefi/fu-uefi-bootmgr.h
- plugins/uefi/fu-uefi-device.c
Some hardware from Lenovo deduplicates UEFI Boot entries, and uses the old
string 'Linux-Firmware-Updater' to avoid removing the firmware update entry.
Although this is forbidden in the UEFI specification we shouldn't break
firmware updates from old firmware versions.
Provide a quirk for this, and automatically whitelist anything with the LENOVO
SMBIOS Manufacturer.
> uefi: Add a quirk to use the legacy bootmgr description

- src/fu-device-private.h
- src/fu-device.c
- src/fu-main.c
- src/fu-tool.c
When calling with a CAB as an install argument, this needs to be
manually populated since the release won't be built.
> fu-tool: Show UpdateMessage if applicable for install command

- plugins/upower/fu-plugin-upower.c
When unable to read battery value this should return FALSE to indicate
AC power.
This was the error showing up otherwise:
```
20:36:34:0982 FuPluginUpower       failed to get OnBattery value, assume on AC power
20:36:34:0982 FuPlugin             performing composite_cleanup() on dell_dock
20:36:34:0982 FuIdle               uninhibiting: performing update
failed to update_prepare using upower: Cannot install update when not on AC power unless forced
```
> trivial: upower: correct a logic error from ed021ab

- src/fu-progressbar.c
- src/fu-progressbar.h
- src/fu-tool.c
- src/fu-util.c
If fwupdmgr or fwupdtool are scripted all the erasing of lines and
progressbars are much less useful.
Without this fix this is what logs look like:
```
Decompressing?           [-                                      ]Decompressing?           [***************************************]
Loading?                 [ -                                     ]Loading?                 [ -                                     ]Loading?                 [***************************************]
Decompressing?           [  - …
```
> fu-progressbar: be more quiet when running non-interactive

- plugins/ata/fu-ata-device.c
- plugins/ata/fu-self-test.c
During download and activation we have to reset the drive to apply the new
firmware. If the kernel gets an unexpected ATA reset then it might panic.
Default to activating the command on the next drive power-up to be safe.
Many thanks to the Dell storage team for the advice.
> ata: Default to the non-activation 0xE subcommand

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/ata/fu-ata-device.c
- plugins/nvme/fu-nvme-device.c
- plugins/nvme/fu-self-test.c
- plugins/wacom-raw/fu-plugin-wacom-raw.c
- plugins/wacom-raw/fu-wacom-emr-device.c
- src/fu-device-private.h
- src/fu-device.c
- src/fu-device.h
- src/fu-self-test.c
This allows hardware from OEMs to *not* match generic firmware supplied by the
device manufacturer. The idea being, that the OEM will supply firmware that
will actually work on the device.
Based on a patch from Mario Limonciello, many thanks.
> Defer the InstanceID->GUID hashing until after setup

- contrib/ci/dependencies.xml
- contrib/fwupd.spec.in
- contrib/snap/snapcraft-master.yaml
- libfwupd/fwupd-common.c
- libfwupd/fwupd-common.h
- libfwupd/fwupd-device.c
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- libfwupd/meson.build
- meson.build
- plugins/amt/fu-plugin-amt.c
- plugins/amt/meson.build
- plugins/ata/fu-ata-device.c
- plugins/dell/fu-plugin-dell.c
- plugins/nvme/fu-nvme-device.c
- snap/snapcraft.yaml
- src/fu-device.c
- src/fu-hwids.c
- src/fu-quirks.c
This also allows us to write mixed-endian structures and adds tests. As part of
this commit we've also changed the API of something that's not yet been in any
tarball release, so no pitchforks please.
> Add fwupd_guid_from_string() to drop dep on uuid

- data/remotes.d/lvfs-testing.metainfo.xml
- data/remotes.d/lvfs.metainfo.xml
These warnings were coming up in the Debian build:
```
W: fwupd source: inconsistent-appstream-metadata-license data/remotes.d/lvfs-testing.metainfo.xml (cc0 != cc0-1.0)
W: fwupd source: inconsistent-appstream-metadata-license data/remotes.d/lvfs.metainfo.xml (cc0 != cc0-1.0)
```
> trivial: Correct the license for some metadata files

- plugins/udev/fu-plugin-udev.c
The udev plugin is somewhat special as it uses a non-subclassed FuDevice that
never gets 'opened'.
This means that we never automatically call fu_device_setup() and thus the
instance IDs are not converted into GUIDs before the device is added.
> udev: Manally call fu_device_setup() to convert the instance IDs

- plugins/ata/fu-ata-device.c
- plugins/nvme/fu-nvme-device.c
Dell storage team confirmed that nothing shorter than 6 will ever
be used and so this heuristic can be stronger.
> trivial: storage: Update minimum Dell component ID length to 6

- contrib/firmware-packager/meson.build
- meson_options.txt
fwupd installs by default firmware-packager (a python3 script) into
the CrOS image. CrOS does not support python3 interpreter and fails
passing the TestValidInterpreter. Removing this script from the default
installation fixes the issue.
TEST=emerge-sarien fwupd
BUG=chromium:857263,b/121131967
Change-Id: I855c7994fd15faa0ce3d520734537674d7538b4e
> fwupd: Hide firmware-packager behind meson option

- .lgtm.yml
Following conversation on the lgtm discussion forum: https://discuss.lgtm.com/t/fwupd-project-not-detected-as-c-project/1742
This should allow LGTM.com to build the C code. Once it's merged i'll trigger this on LGTM.
> Add C build configuration for LGTM.com

- .lgtm.yml
Looks like I forgot one little thing, in my testing I somehow had created this directory and thought it already existed in the repo, forgetting to add it as a build step:
https://lgtm.com/logs/e70808197d3d89717166824b4a7070ce6aa41bdf/lang:cpp
> Ensure libxmlb dir exists for LGTM.com

- plugins/unifying/fu-plugin-unifying.c
- src/fu-device.c
The unifying version numbers are of the form 'RQR24.00_B0000' which means we
have to force the plugin to 'plain' version format to avoid stripping out the
non-semver chars.
Fixes https://github.com/hughsie/fwupd/issues/1018
> unifying: Fix regression when recovering from failed flash

- .circleci/config.yml
Once circle CI is enabled for fwupd this should hopefully build the fwupd snap on Circle CI.
If it works out well, we could potentially have this "publish" snaps to snapcraft as well rather than using Launchpad.
> Add support to run snap build in CircleCI

- .circleci/config.yml
* Publish master snaps to edge after build.
* Publish tagged snaps to the stable channel after build.
I added the variable `SNAPCRAFT_LOGIN_FILE` to circleci.
So assuming this all works https://build.snapcraft.io/user/hughsie will need to get the launchpad builder turned off so they don't conflict too.
> circleci: Manage the lifecycle of the snap

- plugins/dell-dock/fu-dell-dock-i2c-ec.c
EC23 is the last version that will be supported on board 4 SKUs with
base PD firmware versions 18+.
* If on EC23 already, don't mark the device as updatable anymore.
* Flashing EC24 or later when currently on EC 22 or less will potentially
cause bricked docks that can't enumerate, so prevent this scenario
during update path.
> dell-dock: Filter the last supported payloads of certain board 4 SKUs

- plugins/nvme/fu-nvme-device.c
The order of events when casting causes an access to unintended memory.
```
0x00007ffff7bc19df in fwupd_guid_to_string (guid=0x8000000090d0, flags=FWUPD_GUID_FLAG_MIXED_ENDIAN) at ../libfwupd/fwupd-common.c:550
550		memcpy (&gnat, guid, sizeof(gnat));
(gdb) bt
#0  0x00007ffff7bc19df in fwupd_guid_to_string (guid=0x8000000090d0, flags=FWUPD_GUID_FLAG_MIXED_ENDIAN) at ../libfwupd/fwupd-common.c:550
#1  0x00007fffdbddd195 in fu_nvme_device_get_guid_safe (buf=0x7fffffffce70 "\\\034\\\034FI83Q060610103M66   BC501 NVMe SK hynix 128GB", ' ' <repeats 15 times>, "80001C0T\004", <incomplete sequence \344\254>, addr_start=3110) at ../plugins/nvme/fu-nvme-device.c:83
#2  0x00007fffdbddd60c in fu_nvme_device_parse_cns_maybe_dell (self=0x5555558cc8a0, buf=0x7fffffffce70 "\\\034\\\034FI83Q060610103M66 …
```
> trivial: libfwupd: correct a segfault when building a GUID

- contrib/debian/fwupd.install
- contrib/fwupd.spec.in
- data/meson.build
- data/org.freedesktop.fwupd.metainfo.xml
- data/org.freedesktop.fwupd.svg
For this we need to register as a console application (which fwupdtool is, I
suppose) and also supply a usable icon.
I've used the new GNOME icon theme guidelines so please add a drop shadow
before using: https://gitlab.gnome.org/GNOME/Initiatives/issues/2
> Show in Flathub correctly

- plugins/uefi/efi/fwupdate.c
Hey there!
I tried updating my system (Thinkpad T460) today. `fwupdmgr` finished its job and suggested a reboot. After booting into the UEFI updater I got to see this text for >3 minutes:
```
Found update fwupd- ...
Adding new capsule
```
This is reproducible with `v1.2.4` and `master`.
I tried debugging this by inserting a bunch of printfs:
```diff
diff --git a/plugins/uefi/efi/fwupdate.c b/plugins/uefi/efi/fwupdate.c
index 5dd32729..bbddb849 100644
--- a/plugins/uefi/efi/fwupdate.c
+++ b/plugins/uefi/efi/fwupdate.c
@@ -594,18 +594,28 @@ static EFI_STATUS
fwup_set_update_statuses(FWUP_UPDATE_TABLE **updates)
{
EFI_STATUS rc;
+       fwup_debug(L"fwup_set_update_statuses");
for (UINTN i = 0; i < FWUP_NUM_CAPSULE_UPDATES_MAX; i++) {
+               fwup_debug(L"probing i=%d", i);
+ …
```
> uefi: fix segfault in fwup_set_update_statuses

- meson.build
> meson: print stderr of python3 command instead of stdout

- po/make-images.sh
Allows people to specifiy a white-space separated value for them
Void Linux runs them under qemu-user-static like so
`qemu-aarch64-static -L ./usr/aarch64-linux-gnu
./usr/aarch64-linux-gnu/usr/bin/python3`
> po/make-images.sh: quote LOCALEDIR and PYTHON3

- .circleci/config.yml
- contrib/ci/Dockerfile-snap.in
- contrib/ci/flatpak.py
- contrib/ci/snapcraft-wrapper
Snap broke because of a libc6 transition that happened causing all sorts of weird breakage.
Flatpak broke because of strict json decoding.
> Hopefully fix snap and flatpak CI

- plugins/flashrom/fu-plugin-flashrom.c
- plugins/uefi/fu-uefi-pcrs.c
- src/fu-common.c
- src/fu-common.h
- src/fu-self-test.c
- src/fu-tool.c
In some situations SELinux prevents fwupd from executing tpm2_pcrlist, but the
failure mode is that the process just hangs and never completes. This causes
systemd to time out the fwupd daemon startup and then errors to be shown in
GNOME Software.
To prevent this happening, add an optional timeout argument to
fu_common_spawn_sync() and cancel the subprocess if it takes longer than this
to complete.
See https://bugzilla.redhat.com/show_bug.cgi?id=1665701 for details.
> Do not fail to start the daemon if tpm2_pcrlist hangs

- contrib/debian/fwupd.install
- contrib/fwupd.spec.in
- data/bash-completion/fwupdmgr
- data/bash-completion/fwupdtool.in
- data/fwupd.shutdown.in
- data/meson.build
- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd.map
- plugins/ata/fu-ata-device.c
- plugins/ata/fu-plugin-ata.c
- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/dell-dock/fu-plugin-dell-dock.c
- plugins/test/fu-plugin-test.c
- policy/org.freedesktop.fwupd.policy.in
- snap/hooks/install
- src/fu-device.c
- src/fu-device.h
- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
- src/fu-plugin-private.h
- src/fu-plugin-vfuncs.h
- src/fu-plugin.c
- src/fu-self-test.c
- src/fu-tool.c
- src/fu-util.c
- src/org.freedesktop.fwupd.xml
This command is intended to be called later for functionality that may not be safe at standard runtime.
The two cases that are envisioned so far:
* Calling ATA microcode activate command (`0xF`) when filesystem is not mounted
* Calling dell-dock's dock reboot when rebooting a machine if the update was pending
I've not plumbed it up to systemd yet, mostly because i'm a little bit confused by whether the action should live in `/lib/systemd/system-shutdown` or a unit that requires `umount.target`.  In either case, I think that will be a follow up PR.
CC @djcampello,
This is something that matches what we talked about using for logout.  I think we'll need to store something to `pending.db` and then a shell script could potentially launch it on logout.
> Add support for delayed activation command

- data/org.freedesktop.fwupd.metainfo.xml
The following warnings were displayed by Debian appstream metadata
validation.
```
metainfo-validation-issue
Validation of the metainfo file found a problem: Found empty 'url' tag.
metainfo-validation-issue
Validation of the metainfo file found a problem: Type 'console-application' component, but no information about binaries in $PATH was provided via a provides/binary tag.
metainfo-validation-issue
Validation of the metainfo file found a problem: Found empty 'url' tag.
```
> trivial: modify appstream metadata for some warnings

- libfwupd/fwupd-device.c
- libfwupd/fwupd-self-test.c
Rather than displaying:
"Flags" : 9,
Use the more understandable:
"Flags" : [
"updatable",
"require-ac"
],
> trivial: Export the FwupdDevice flags as readable JSON

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-install-task.c
- src/fu-install-task.h
- src/fu-keyring-utils.c
- src/fu-keyring-utils.h
- src/fu-self-test.c
In the future we'll want to use this flag to signify if the release is an
upgrade, downgrade, below the version-lowest, or if it is locked in some way.
> Rename FwupdRelease:trust-flags to FwupdRelease:flags

- .circleci/config.yml
- .travis.yml
This should hopefully make daily CI runs operate faster by balancing
some across Travis CI and some across Circle CI.
> trivial: ci: move s390x build into CircleCI

- contrib/debian/fwupd.install
- contrib/fwupd.spec.in
- data/bash-completion/fwupdmgr
- data/fwupd-offline-update.service.in
- po/POTFILES.in
- src/fu-offline.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
- src/meson.build
If another offline update task is run at the same time, e.g. pk-offline-update
from PackageKit then we might corrupt the package database when the client
D-Bus request times out.
Copy the fixes from PackageKit so that the offline updates work together.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1685471
> Do not reboot when failing to start fwupd during offline updates

- .lgtm.yml
- subprojects/libxmlb.wrap
Although it's an optional bump, this is needed for
88dc0f4bf088de7892447cdff8e8cea5e77d5383 to fully work.
> trivial: bump libxmlb subproject dependency

- libfwupd/fwupd-common.c
On some hardware the SHA1 checksum is not set and so we want to use the SHA256
hash value as well.
The LVFS doesn't currently read the ChecksumDevice value and so nothing will
explode serverside when changing this type from 'string' to 'array of strings'.
> Include all device checksums in the LVFS report

- data/fwupd.service.in
Instead of referring to just *gdm.service* use the alias *display-manager.service* instead to allow other display managers like *sddm* too.
> fwpup.service: use display-manager.service instead of gdm.service

- src/fu-engine.c
- src/fu-keyring-pkcs7.c
This ensures the certificate is always present even before the user has
generated a report or manually signed test data.
Also, if the GnuTLS version is too old just log a message and continue.
> Ensure the PKCS-7 client certificate exists at startup

- plugins/superio/fu-superio-common.h
- plugins/superio/fu-superio-device.c
I'm not sure why we can't just use SIO_LDNxx_IDX_CHIPID1, but lets do the same
as the vendor tool in case there is a good reason that I don't know about.
> superio: Get the chip size from the EC rather than hardcoding

- src/fu-plugin-vfuncs.h
- src/fu-plugin.c
Some devices (e.g. Wacom, DFU and SuperIO) require the device to be in
'bootloader' mode before the device checksums can be populated.
Rather than each plugin handle both the open()->detach()->detach()->close()
sequence handle this in the plugin loader. It's not super-easy to do the right
thing for the failure case, and having two new dedicated vfuncs makes it a lot
simpler.
> Add optional vfuncs to allow detaching and attaching verify()

- src/fu-tool.c
This is a vestigate of `fwupdtool` originally only being used for
`install-blob`.  Now that it can do a local `update` command and
local `install` command, it's important to update the history
database from `fwupdtool` as well.
> fu-tool: save history from stuff installed with `fwupdtool`

- src/fu-history.c
Always return the newest-created device when there are multiple results.
Might fix https://github.com/hughsie/fwupd/issues/1118
> Return the newest device when using fu_history_get_device_by_id()

- meson_options.txt
- plugins/uefi/fu-uefi-common.c
- plugins/uefi/meson.build
fu_uefi_get_esp_path_for_os() generates the path to the OS directory
based on "ID" in /etc/os-release, and it may not work for some distros.
Take openSUSE as an example, the "ID" for openSUSE Leap is
"opensuse-leap" and that for openSUSE Tumbleweed is "opensuse-tumbleweed".
However, both of them use the same OS directory in the ESP, i.e.
"/EFI/opensuse".
This commit adds a new build option, efi-osdir, to allow the packager to
specify the name of OS directory at build time instead of the runtime
detection.
> uefi: add a new option to specify the os name

- plugins/ata/fu-ata-device.c
I had thought this should be implicit from standby immediate command
but it isn't.
> ata: Flush cache before standby and activate

- src/fu-history.c
If the history database is corrupt or the daemon crashed during the migration
the history object fails to load, which in turn fails the daemon startup.
Rather than leaving the user with a broken system (which also shows UI to that
effect in gnome-software) delete the existing file and start afresh. Nothing
in the history database is that important anyway.
> Recreate the history database if migration failed

- .travis.yml
It's currently failing with no changes caused by fwupd.
```
Step 10/16 : RUN pip3 install pillow pygobject
---> Running in 613ba74c32ce
Collecting pillow
Downloading https://files.pythonhosted.org/packages/81/1a/6b2971adc1bca55b9a53ed1efa372acff7e8b9913982a396f3fa046efaf8/Pillow-6.0.0.tar.gz (29.5MB)
Complete output from command python setup.py egg_info:
running egg_info
creating pip-egg-info/Pillow.egg-info
writing dependency_links to pip-egg-info/Pillow.egg-info/dependency_links.txt
writing top-level names to pip-egg-info/Pillow.egg-info/top_level.txt
writing pip-egg-info/Pillow.egg-info/PKG-INFO
writing manifest file 'pip-egg-info/Pillow.egg-info/SOURCES.txt'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-6xakdwq1/pillow/setup.py", line …
```
> trivial: disable CentOS CI

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
Some firmwares only update one part of the system, e.g. the EC or ME firmware.
Other updates include all the updates needed for the whole system, and vendors
have been doing different things with the component name due to this.
To fix, add an enumerated set of firmware 'scopes' that can be set by the
uploader in the metainfo.xml file (or changed the LVFS) which automatically
set the name suffix.
Only append the translated version in the client when LVFS::UpdateScope has
not been set, as the LVFS is still operating in compatibility mode and setting
the <name> with the prefix. Add the support to fwupd now so we can switch in
about 6 months time.
> Add a component property to express the firmware scope

- src/fu-engine.c
- src/fu-self-test.c
This ensures that child devices are updated before the receiver as the update
protocol may be changed during the update.
Fixes https://github.com/hughsie/fwupd/issues/1139
> Add support for the not-child extension from Logitech

- src/fu-engine.c
For me this seems to fix #1130 and match the right device.
Repro steps:
1. Clear pending.db
2. Start with ATA firmware X.
3. Flash ATA firmware Y.
4. Reboot machine (activate runs on shutdown)
5. Verify running on ATA firmware Y.
6. Verify that `fwupdmgr activate` return `No firmware to activate`.
> fu-engine: Clear activation flag on old firmware not new (Fixes: #1130)

- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-plugin-modem-manager.c
- plugins/modem-manager/fu-qmi-pdc-updater.c
- plugins/modem-manager/fu-qmi-pdc-updater.h
This MR avoids having the module be detected with any specific carrier config selected ("DF", default) after a firmware upgrade. As soon as the MCFG files have been downloaded to the device, we can right away select the one we want to use (based on the last firmware version reported, which includes the carrier config ID embedded).
This logic is needed to have the firmware update process working correctly when there is no SIM inserted, as the carrier selection automagic in ModemManager only works when there is a valid SIM inserted.
> ModemManager/qmi-pdc: activate config as part of the FW upgrade process

- src/fu-common-version.c
- src/fu-self-test.c
Failing the semver checks we want to fall back to PLAIN, rather than UNKNOWN.
> Detect version number like RQR24.06_B0030 as 'plain'

- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-common.c
- plugins/uefi/meson.build
When booted with secure boot and a hand install I noticed that I wasn't getting an error related to a missing secure boot binary, which was completely unexpected to me.
It's because the build path was leaked into the binary and was not really being checked.
> UEFI Fixes

- src/fu-device-private.h
- src/fu-device.c
- src/fu-udev-device.c
- src/fu-usb-device.c
These are dangerous GUIDs that shouldn't generally be used by any device
for distribution of firmware updates. They'll potentially apply to
devices outside of the vendor they were created for.
Additionally if two USB devices with common interface classes are
on the system, they may lead to one device not being populated by
fwupd.
Fixes https://github.com/hughsie/fwupd/issues/1162
> Only use class-based instance IDs for quirk matching

- plugins/ata/fu-ata-device.c
- plugins/nvme/fu-nvme-device.c
- src/fu-engine.c
* Make noise when VersionFormat isn't set
* Fix VersionFormat to be clear for Dell storage devices
> Version Format adjustments

- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
The lines are almost impossible to read as they are not wrapped and not
delimited from the normal script output. Add a box around to make them stand out:
╔══════════════════════════════════════════════════════════════════════════════╗
║ The LVFS is a free service that operates as an independent legal entity and  ║
║ has no connection with Fedora. Your distributor may not have verified any    ║
║ of the firmware updates for compatibility with your system or connected      ║
║ devices. All firmware is provided only by the original equipment             ║
║ manufacturer.                                                                ║
║                                                                              ║
║ Enabling this functionality is done at your own risk, which means you have …
> Display the remote warning on the console in an easy-to-read way

- contrib/standalone-installer/assets/header.py
- contrib/standalone-installer/make.py
Allow setting a minimum fwupd version requirement using `--minimum`.
If running on a distro with apt, try to use this to detect an already
installed version and compare what was passed in to `--minimum`.
* If new enough version, use the built in version
* If too old of a version or not specified, require package removal.
> standalone-installer: Be smarter about existing installed fwupd

- src/fu-util-common.c
Arch apparently sets all proxies to zero length and this causes
problems for fwupd.
> fu-util-common: Support empty proxy strings (Fixes: #1199)

- src/fu-main.c
It's taken 3 years to get from 20kB to 1Mb, and so it'll take longer than Ubuntu
16.04 is supported to grow an order of magnitude bigger. Plus, if we have 10Mb
of XML we probably need to rethink the metadata format a bit...
> Raise the metadata limit to 10Mb

- plugins/superio/fu-superio-it89-device.c
Apparently Star Labs have been using this for some time. It's still important
to reboot after the update has been performed.
> Allow SuperIO updates to be done live

- .circleci/config.yml
Split up the promotion step into a separate workflow with it's own
filters.
According to https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
every dependency needs its own tag filter, so hopefully this should
fix automatic deployment.
> trivial: circleci: try to fix automatic snap deployment

- plugins/uefi/uefi.quirk
Added AMI fix for the "duplicate entry" issue to firmware version 1.0.4 - quirk is needed to install new version
> Lite Mk II flag for use-shim-unique

- plugins/synapticsmst/fu-plugin-synapticsmst.c
When converting to instances we forgot to add the GUIDs to the device
as well.
> synapticsmst: fix GUID generation (Closes: #1207)

- plugins/uefi/fu-plugin-uefi.c
A failure report on LVFS shows that NixOS wasn't able to launch
efibootmgr.
> trivial: uefi: use the path for efibootmgr that was detected

- contrib/debian/rules
By default, "--wrap-mode=nodownload" switch is provided. It means that no
fallback subproject will be used (only packages from Debian archives will
be accepted). We need to build the flashrom from source, hence modification
of this switch is needed.
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
- [*] Code fix
> contrib/debian/rules: allow for building subprojects from source

- RELEASE
- po/meson.build
Target to run the contrib/fix_translation.py scripts with the correct path. Update the RELEASE documentation to use the new target instead of calling the script "manually".
> Add meson target to fix translations

- contrib/ci/fedora.sh
On Fedora 30 x86_64 I got:
```
docker run --privileged -t -v `pwd`:/build fwupd-fedora
...
Complete!
+ cp /root/rpmbuild/RPMS/noarch/fwupd-tests-1.2.10-0.1alpha.fc29.noarch.rpm /root/rpmbuild/RPMS/x86_64/fwupd-1.2.10-0.1alpha.fc29.x86_64.rpm /root/rpmbuild/RPMS/x86_64/fwupd-debuginfo-1.2.10-0.1alpha.fc29.x86_64.rpm /root/rpmbuild/RPMS/x86_64/fwupd-debugsource-1.2.10-0.1alpha.fc29.x86_64.rpm /root/rpmbuild/RPMS/x86_64/fwupd-devel-1.2.10-0.1alpha.fc29.x86_64.rpm dist
cp: target 'dist' is not a directory
```
> Fix Fedora docker build missing directory: dist

- libfwupd/fwupd-error.c
- libfwupd/fwupd-error.h
- plugins/upower/fu-plugin-upower.c
- src/fu-engine.c
Users are getting confused when they're being told that AC power is required
when they are already on AC power... but the battery is too low to perform the
update.
> Add a specific error code for the low battery case

- plugins/wacom-usb/wacom-usb.quirk
remove those Bluetooth PIDs as Wacom doesn't support updating from Bluetooth interface.
Signed-off-by: Jeff <jeff.gu@wacom.com>
- [*] Code fix
> remove some unsupported device PIDs

- plugins/thunderbolt/fu-plugin-thunderbolt.c
Fixes: b3aa793539 ("thunderbolt: Convert the instance IDs as we never open the device")
> trivial: thunderbolt: catch failure setting up device

- contrib/ci/centos.sh
- contrib/ci/fedora.sh
- meson_options.txt
When upstream libflashrom contains all the required API upstream we can build
this by default.
> Disable the flashrom plugin by default

- src/fu-engine.c
If the version is not specified then treat it as just 'exists'.
> Allow specifying <firmware>GUID</firmware> to check any version exists

- plugins/dell/fu-plugin-dell.c
- plugins/redfish/fu-plugin-redfish.c
- src/fu-hwids.c
- src/fu-plugin.c
- src/fu-smbios.c
This difficult to debug bug only showed up when the fwupd service was stopped,
which the user never noticed, but services like abrt were still keen to report.
The root issue was that the call to fu_plugin_get_smbios_data() in
fu-plugin-uefi.c:fu_plugin_startup() was freeing the returned const GBytes,
which rippled down all the way to a double-free deep in libxmlb.
It's somewhat unusual to have a const GBytes, so just change the plugin helper
to returned a ref'd copy, on the logic a potential 16 byte memory leak is better
than a double-free when the next plugin gets the logic the wrong way around.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1734746
> Fix a crash when stopping the fwupd service

- .circleci/config.yml
- contrib/ci/abidiff.suppr
- contrib/ci/check-abi
- contrib/ci/dependencies.xml
This adds a script which can check for ABI breaks between two Git
revisions:
$ ./contrib/ci/check-abi.sh
The CI is set up to run it automatically between the tip of the branch
being tested and the last release tag.
Based on the work by Mathieu Bridon <bochecha@daitauha.fr>, many thanks.
> Verify we don't break the ABI

- plugins/modem-manager/meson.build
- plugins/modem-manager/modem-manager.quirk
The DW5821e in modem mode uses the 0x81D7 PID, but when it boots in
fastboot mode it uses the 0x81D6 PID. The upgrade procedure was able
to automatically match these two devices because they both shared the
very generic per-VID (0x413C) GUID, but this is no longer operational
since commit 8ef139faba, as the very generic GUIDs have been removed
for matching purposes.
So, define a quirk for the DW5821e, in order to add a counterpart
GUID to make device matching work properly again.
Fixes https://github.com/hughsie/fwupd/issues/1271
> modem-manager: add counterpart GUID for the DW5821e

- plugins/altos/fu-altos-device.c
- plugins/colorhug/fu-colorhug-device.c
- plugins/csr/fu-csr-device.c
- plugins/dell-dock/fu-dell-dock-status.c
- plugins/dfu/dfu-cipher-xtea.c
- plugins/dfu/dfu-format-dfuse.c
- plugins/dfu/dfu-format-metadata.c
- plugins/dfu/dfu-patch.c
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/modem-manager/fu-qmi-pdc-updater.c
- plugins/rts54hid/fu-rts54hid-device.c
- plugins/rts54hid/fu-rts54hid-module.c
- plugins/synaptics-prometheus/fu-synaprom-config.c
- plugins/unifying/fu-unifying-bootloader.c
- plugins/unifying/fu-unifying-runtime.c
- plugins/wacom-usb/fu-wac-device.c
- plugins/wacom-usb/fu-wac-module-bluetooth.c
- src/fu-common.c
- src/fu-common.h
- src/fu-self-test.c
There are several subtle bugs in various places in fwupd caused by not treating
user-provided offsets into buffers as unsafe. As fwupd runs as root we have to
assume that all user firmware is evil, and also that devices cannot be trusted.
Make a helper to put all the logic into one place and convert all users.
> Never use memcpy() in a possibly unsafe way

- plugins/thunderbolt/fu-plugin-thunderbolt.c
This controller isn't flashable in fwupd, but fwupd can display information
about it.
* Use a generic device ID (similar to safemode)
* Build device name attribute from DMI data
> thunderbolt: Fix logic to work properly with ICL thunderbolt controller

- src/fu-config.c
- src/fu-engine.c
- src/fu-util.c
Normally the flag 'supported' is used to indicate that devices can
update from a remote such as LVFS.
Running `#fwupdmgr get-updates` in this situation will show a message
for each device that is already up to date as well as messages for
devices that have updates available.
If no devices contain the supported flag, `# fwupdmgr get-updates`
will show no output, which is confusing to some people.
Show "No updatable devices" instead for those situations.
> trivial: If no devices support updates, show messaging (Closes: #1295)

- contrib/debian/fwupd.install
- contrib/fwupd.spec.in
- data/bash-completion/fwupdmgr.in
- data/meson.build
- data/motd/85-fwupd.motd.in
- data/motd/README.md
- data/motd/fwupd-refresh.service.in
- data/motd/fwupd-refresh.timer
- data/motd/meson.build
- src/fu-util-common.c
- src/fu-util.c
Second try on this.  Hopefully this is generic enough that it will work in all scenarios.  All an admin needs to do is run and it should work on most distros.
```
```
Fixes Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921820
Introduce a new --log option to fwupdmgr that will log stdout to an argument.
If run under systemd, prefix that argument with $RUNTIME_DIRECTORY.
Add a new systemd unit and associated timer to regularly refresh metadata.
After the metadata refresh is complete, save the output to the motd location.
The timer and service are disabled by default and can be enabled by an admin.
> Add support to integrate into the motd (Fixes: #1270)

- plugins/uefi/fu-self-test.c
- plugins/uefi/fu-uefi-pcrs.c
A first [release candiate](https://github.com/tpm2-software/tpm2-tools/releases/tag/4.0-rc0) for tpm2-tools 4.0 has been tagged. This is a major release that contains many [backwards-incompatible changes](https://github.com/tpm2-software/tpm2-tools/blob/c02b68d56f1ce7a67b1be580b7efe128d26447bf/CHANGELOG.md#40-rc0---2019-08-19). fwupd only uses `tpm2_pcrlist`, which has been renamed to `tpm2_pcrread` and its output format has been slightly changed from
```
$ tpm2_pcrlist 
sha1 :
0  : ffffffffffffffffffffffffffffffffffffffff
[...]
sha256 :
0  : ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
[...]
```
to
```
$ tpm2_pcrread 
sha1:
0 : 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[...]
sha256:
0 : 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[...]
```
This …
> uefi: add support for tpm2-tools 4.X

- src/fu-debug.c
- src/fu-device.c
- src/fu-device.h
- src/fu-engine.c
- src/fu-plugin-private.h
- src/fu-plugin-vfuncs.h
- src/fu-plugin.c
This allows the plugin to cause a superclassed ->rescan() to be called in
response to some vague hardware change.
> Add fu_device_rescan() and a FuDevice->rescan() vfunc

- src/fu-engine.c
- src/fu-self-test.c
Although not always useful (due to patches being backported) being able to
depend on a specific kernel version might save our bacon in the future.
> Include the kernel release as a runtime version

- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
This makes devices, releases, remotes, history and updates all use tree output.
I think it looks most successful when you look at what get-updates output can do:
```
No upgrades for Thunderbolt controller in Dell dock, current is 43.00: 40.00=older
No upgrades for Package level of Dell dock, current is 01.00.08.01: 01.00.04.01=older
No upgrades for RTS5413 in Dell dock, current is 01.21: 01.21=same
No upgrades for RTS5487 in Dell dock, current is 01.47: 01.47=same
No upgrades for VMM5331 in Dell dock, current is 05.04.00: 05.03.10=older
No upgrades for WD19TB, current is 01.00.00.02: 01.00.00.00=older
○
└─XPS 13 9380 System Firmware:
│   Device ID:           6c24a747f97668873b761558e322398a91dbf394
│   Current version:     0.1.6.0
│   Minimum Version:     0.1.6.0
│   Vendor: …
```
> Use tree output for everything possible

- plugins/unifying/fu-unifying-bootloader.c
The new firmware for receivers with the nordic chips are using the 0x04
record type. This was previously not handled when parsing the file,
causing wrong behavior when trying to update the device. This patch
tries to properly deal with the record types, being them 0x04 or other.
> unifying: fix incomplete hex file parsing

- src/fu-common.c
- src/fu-util-common.c
- src/fu-util.c
This was lost in the move to tree output
```
$ fwupdmgr get-details tpm.cab
Decompressing…           [***************************************]
○
└─XPS 13 9380 TPM 2.0:
│   Device ID:           1a433daa3acb71e6befadcf2b1a783c1549663b1
│   Description:         Updating the system firmware improves performance.
│
│   Flags:               internal|updatable|require-ac|registered|needs-reboot
│
└─TPM 2.0 Update:
Version:           7.2.0.2
Summary:           Firmware for the Dell TPM 2.0
License:           proprietary
Size:              1.1 MB
Vendor:            Dell Inc.
Flags:             none
```
> fu-util: show release output in get-details again

- plugins/dell/README.md
- plugins/dell/fu-plugin-dell.c
- plugins/dell/fu-self-test.c
- plugins/dell/meson.build
- src/fu-common.c
These are a more scalable way to apply firmware across a variety of
platforms.
An example:
```
XPS 13 7390 TPM 2.0
DeviceId:             c56e9f77cfee65151bdef90310776f9d62827f5a
Guid:                 a4352c96-f8d7-526c-8485-7f84085f348e <- 0962-2.0
Guid:                 6eaf178c-8b69-5016-9b51-1d866cd2ae2f <- DELL-TPM-2.0-NPCT
Guid:                 9c4af226-139b-562a-b27c-98dcf46b4b72 <- DELL-TPM-2.0-NPCT-75x
Guid:                 67c02020-e1c5-5ca7-ad89-7fa1dfde6465 <- DELL-TPM-2.0-NPCT-75x-\u0002\u0001
Guid:                 7967697a-ee78-5dd4-846f-6eda95960009 <- DELL-TPM-2.0-NPCT-75x-\u0002\u0001-rls
Summary:              Platform TPM device
Plugin:               uefi
Flags:                internal|require-ac|registered
Vendor:               Dell Inc.
Version:              7.2.1.0 …
```
> dell: Use TSS to query and build TPM vendor strings for GUIDs

- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
- plugins/dell/fu-plugin-dell.c
- plugins/dell/fu-self-test.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/uefi/fu-plugin-uefi.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util.c
- src/org.freedesktop.fwupd.xml
Before:
```
○
├─XPS 13 7390 TPM 2.0:
│     Device ID:           c56e9f77cfee65151bdef90310776f9d62827f5a
│     Summary:             Platform TPM device
│     Current version:     7.2.1.0
│     Vendor:              Dell Inc.
│     Update Error:        Updating disabled due to TPM ownership
│     Flags:               internal|require-ac|registered
└─XPS 13 7390 System Firmware:
Device ID:           b6c08fb9e5384d9d101853cc1ca20cf0ce2df2e2
Current version:     0.1.1.1
Minimum Version:     0.1.1.1
Vendor:              Dell Inc.
Flags:               internal|updatable|require-ac|registered|needs-reboot
```
After:
```
○ XPS 13 7390
│
├─TPM 2.0:
│     Device ID:           c56e9f77cfee65151bdef90310776f9d62827f5a
│     Summary:             Platform TPM device
│     Current version:     7.2.1.0
│ …
```
> fu-util-common: try to show DMI product name only once

- contrib/PKGBUILD
- contrib/ci/arch.sh
- contrib/ci/generate_docker.py
- Moved version discovery routine to PKGBUILD
- Set PKGEXT to .pkg.tar to avoid the package being compressed
- Added --needed to pacman arguments when installing the dependencies to
avoid reinstalling packages
> ci: arch: minor improvements

- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/uefi.quirk
- src/fu-plugin.c
- src/fu-plugin.h
The fwupd UEFI plugin refuses to start if bit 3 of the "BIOS Characteristics
Extension Byte 2" (13h) is cleared. Bit 3 is UEFI Specification is supported.
Fixes https://github.com/fwupd/fwupd/issues/1342
> Add a DMI quirk for the Minnowboard Turbot

- contrib/fwupd.spec.in
- plugins/meson.build
- plugins/uefi-recovery/README.md
- plugins/uefi-recovery/fu-plugin-uefi-recovery.c
- plugins/uefi-recovery/meson.build
- plugins/uefi-recovery/uefi-recovery.quirk
- plugins/uefi/fu-plugin-uefi.c
The factory-shipped MinnowBoardMAX board has firmware that does not include
the ESRT table. Create a 'fake' UEFI device with the lowest possible version
so that it can be updated to any version firmware.
All the HwId GUIDs are used for the fake UEFI device, and so should be used in
the firmware metadata for releases that should recover the system.
> uefi-recovery: Add a plugin to add a fake ESRT entry for device recovery

- contrib/fwupd.spec.in
- data/meson.build
Since D-Bus 1.9.18 configuration files installed by third-party should
go in share/dbus-1/system.d. The old location is for sysadmin overrides.
> Move D-Bus conf file to datadir/dbus-1/system.d

- src/fu-debug.c
The value G_LOG_LEVEL_MASK includes debugging, which tpm2-abrmd is certainly
allowed to use.
Fixes https://github.com/fwupd/fwupd/issues/1353
> Do not crash when starting tpm2-abrmd

- libfwupd/fwupd-common.c
The LVFS already knows how to deal with arrays of strings, so this is a forwards
and backwards compatible change.
Fixes https://github.com/fwupd/fwupd/issues/1363
> Include all GUIDs when uploading a report

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-util-common.c
When the LVFS switches over to outputting <issues> rather than appending to the
update description we need to be in a position to display the new data.
> Support <issues> in AppStream metadata

- src/fu-device.c
Although, we have to use the converted instance IDs rather than the GUIDs as
fu_device_setup() has not typically been called at this point.
> Call the set_quirk_kv() vfunc for the superclassed object

- plugins/dell-esrt/fu-plugin-dell-esrt.c
- plugins/uefi/fu-plugin-uefi.c
When the system doesn't support UEFI capsule updates no firmware version
is displayed for the BIOS.  Fix this by creating a dummy device:
```
├─System Firmware:
│     Device ID:           123fd4143619569d8ddb6ea47d1d3911eb5ef07a
│     Current version:     1.7.0
│     Vendor:              Dell Inc.
│     Update Error:        UEFI Capsule updates not available or enabled
│     Flags:               internal|require-ac|registered|needs-reboot
```
If the dell-esrt plugin determines that capsule updates can be enabled
however, make the device it creates replace the dummy device:
```
├─Dell UEFI updates:
│     Device ID:           123fd4143619569d8ddb6ea47d1d3911eb5ef07a
│     Summary:             Enable UEFI Update Functionality
│     Current version:     0
│     Update Error:        Firmware …
```
> uefi, dell-esrt: Show firmware version when capsule updates unavailable

- src/fu-firmware.c
- src/fu-firmware.h
- src/fu-self-test.c
- src/fu-srec-firmware.c
- src/fu-srec-firmware.h
At least two vendors are not using SREC according to the spec. They are using
it like a recipe to write specific values at specific addresses.
All the logic like line lengths and checksumming (and therefore all the various
checks for malicious firmware are still valid), so provide a new function to
just tokenize the file and to not assign a padded image.
> Allow parsing a raw SREC file

- src/fu-tool.c
-o <arg> will redirect stdout to <arg>, -O <arg> what we want to be
using, it saves the file to <arg>.
> trivial: fix wget command in fu-tool.c

- snap/hooks/install
CC @LinuxOnTheDesktop 
There was a regression on snap that you could only catch on fresh install.  It didn't happen in upgrades or channel refreshes (which is what was tested).
> Fix snap fresh installation

- src/fu-common.c
- src/fu-common.h
- src/fu-progressbar.c
- src/fu-util-common.c
This fixes the output when using locales like zh_CN.utf-8
> Align the key values to the text *width* not the number of bytes

- plugins/dell-dock/fu-dell-dock-hub.c
This was more fallout from 7afd7cba0d327b155b2201c9fbb5414ced9cfe06
which led to write_size being set to 0 and an endless loop.
> trivial: dell-dock: correct another write_size error

- libfwupd/fwupd-self-test.c
Ubuntu's buildds seem to have changed and this is causing test suite
failures.
> trivial: libfwupd: skip tests if machine-id is empty too

- src/fu-engine.c
- src/fu-engine.h
- src/fu-self-test.c
We don't need to enumerate USB and UDev devices in the self tests. In the case
where the probe fails (due to a permissions error, as not running as root) we
don't want the tests to fail.
> Do not enumerate physical devices when running the internal self tests

- plugins/dell/fu-plugin-dell.c
- plugins/dell/fu-self-test.c
- plugins/uefi/fu-self-test.c
- plugins/uefi/fu-uefi-pcrs.c
Avoids situations that the TSS doesn't handle well such as TPM1.2.
> trivial: dell: make failures to add GUIDs non-fatal (Fixes: #1396)

- plugins/dell/fu-self-test.c
- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-bootmgr.c
- plugins/uefi/fu-uefi-common.c
- plugins/uefi/fu-uefi-common.h
- plugins/uefi/fu-uefi-device.c
- plugins/uefi/fu-uefi-tool.c
- plugins/uefi/fu-uefi-udisks.c
- plugins/uefi/fu-uefi-udisks.h
- plugins/uefi/meson.build
This is also 1.3.3 material, early comments appreciated.
There is definitely a memory leak going on with the dbus comms.  Can tell from
```g_atomic_ref_count_dec: assertion 'g_atomitc_int_get (arc) > 0``` showing up in the logs but I'm not sure what i'm doing wrong.  If you spot it, appreciated!
> Detect unmounted ESP (Fixes: #1405)

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd.map
- src/fu-engine.c
Somewhat embarrassingly we were not actually showing the 8bitdo manual detach
images because... we were not actually exporting them. I don't know how this
ever worked in GNOME Software, but it would also explain the low 'success' rate
of the 8bitdo firmware on the LVFS.
This will also be used by Logitech in the future for the C1 Unifying devices.
To work in gnome-softare, this also needs the matching functionality to call
gs_app_add_screenshot() with the new exported data.
> Export the instructions for detaching the device

- src/fu-util-common.c
Just provide a translated string for this most common of cases.
> Never show LicenseRef-proprietary to the end user

- src/fu-util.c
Updating firware is sometimes scary, and for user-facing CLI tools we ought to
show some kind of reassurance than it went well.
Fixes some of https://github.com/fwupd/fwupd/issues/1409
> Add some success messages when CLI tasks have completed

- src/fu-udev-device.c
These seem to be caused by udev_parent being `NULL`.
```
19:26:06:0220 GLib-GObject         g_object_ref: assertion 'G_IS_OBJECT (object)' failed
19:26:06:0220 GUdev                g_udev_device_get_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
19:26:06:0220 GUdev                g_udev_device_get_parent: assertion 'G_UDEV_IS_DEVICE (device)' failed
19:26:06:0221 GLib-GObject         g_object_ref: assertion 'G_IS_OBJECT (object)' failed
19:26:06:0221 GUdev                g_udev_device_get_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
19:26:06:0221 GUdev                g_udev_device_get_parent: assertion 'G_UDEV_IS_DEVICE (device)' failed
19:26:06:0221 GLib-GObject         g_object_ref: assertion 'G_IS_OBJECT (object)' failed
19:26:06:0221 GUdev …
```
> trivial: fu-udev-device: fix some assertions

- contrib/debian/fwupd.preinst
- data/motd/fwupd-refresh.service.in
It was reported in Debian a problem with the unit failing to start.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932617
It looks to me it's caused by a change in behavior in systemd 242 that it will chown directories when running so that means that both fwupdmgr (confined via systemd DynamicUser) and fwupd can't both take it.  So give fwupdmgr it's own persistent cache directory instead.
Also it seems that there might be a bug with runtime directory behavior in systemd as a very simple reproducer causes the problems.  Disable the motd population for now until we have a better grasp on it.
https://github.com/systemd/systemd/issues/13688
> Some systemd fixes

- data/remotes.d/lvfs-testing.conf
- data/remotes.d/lvfs.conf
- libfwupd/fwupd-remote.c
- libfwupd/fwupd-remote.h
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-util-common.c
- src/fu-util.c
This is not 1.3.2 material, I'm expecting it fits into the bigger stuff that you want to overhaul reporting some in 1.3.3.
The basic idea is to extend the nag to either be:
* Less annoying to people who never want to upload stuff
* Less annoying to people who want to help as much as possible
The configuration option is a daemon property with the idea being if someone opts in from one client but uses another the other clients can follow the same behavior.
> Add support for automatically uploading reports

- src/fu-util.c
Before:
```
Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Upload report now? (Requires internet connection):0.	Do not upload %u reports at this time, but prompt again for future updates6
1.	Do not upload %u reports, and never ask to upload reports for future updates
2.	Upload %u reports just this one time, but prompt again for future updates
3.	Upload %u reports this time and automatically upload reports after completing future updates
```
After:
```
Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Upload report now? (Requires internet connection):
0.	Do not upload reports at this time, but prompt again for future updates
1.	Do not upload reports, …
```
> Fixup the report message

- data/bash-completion/fwupdmgr.in
- src/fu-tool.c
- src/fu-util.c
I'm not proud of how many times I've done:
1. browse fwupd.org
2. find device
3. `fwupdmgr install $URL --allow-reinstall`
Or `fwupdmgr downgrade` just to have something to easily reinstall.
I can't be alone, so here is a way to make it easier :yellow_heart: 
> Add a top level reinstall command to fwupdmgr

- plugins/thunderbolt/fu-thunderbolt-image.c
This seems like a bug, as `FALSE` == `0` == `VALIDATION_PASSED`
Am I missing something?
> thunderbolt: Fix usage of incorrect type for return value

- plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c
Avoid checking if bolt supports force-power in coldplug (early on) because that will dbus-activate boltd, even on systems where there is no actual thunderbolt hardware and thus also no force-power support. Since boltd does use the very same kernel mechanism that fwupd would use when boltd is not around this can not lead to any regressions.
Type of pull request: Somewhat between fix and feature.
Cc: @ybernat
> thunderbolt-power: avoid checking for bolt support

- plugins/synaptics-rmi/README.md
- plugins/synaptics-rmi/fu-synaptics-rmi-device.c
Firmware may be suitable for all products that match the 'major ID' and so we
should provide an extra GUID to use in this case.
> synaptics-rmi: Also add the product ID as a GUID without the minor version

- plugins/altos/fu-altos-device.c
- plugins/csr/fu-csr-device.c
- plugins/dfu/dfu-device.c
- plugins/optionrom/fu-optionrom-device.c
- plugins/superio/fu-superio-it89-device.c
- src/fu-device.c
- src/fu-device.h
- src/fu-plugin.c
Returning a GBytes is not good enough when the device may be returning multiple
partitions which have to be stored as FuFirmwareImage objects.
> Read firmware back from the device as a FuFirmware

- src/fu-firmware-image.c
- src/fu-firmware-image.h
- src/fu-self-test.c
This matches the behaviour of FuFirmware.
> trivial: Add klass->to_string for superclassed FuFirmwareImage objects

- plugins/wacom-raw/fu-wacom-emr-device.h
Actually trying to instantiate the object leads to:
Specified class size for type 'FuWacomEmrDevice' is smaller than the
parent type's 'FuWacomDevice' class size.
Fixes https://github.com/fwupd/fwupd/issues/1456
> wacom-emr: Fix a regression for EMR devices

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/ebitdo/ebitdo.quirk
- plugins/ebitdo/fu-ebitdo-device.c
- src/fu-device-list.c
- src/fu-engine.c
These controllers don't come back into the correct mode for fwupd after flash so 3 failures occur:
1. Waiting for replug
2. Trying to attach to application mode again
3. Trying to reload for version info
Skip those steps so that the flash process completes successfully.
> Fix 8bitdo SN30/SF30 error reporting

- src/fu-udev-device.c
If the parent device is hooked up via I2C that's a pretty good
indication that the touchpad is internal to the device.
> trivial: synaptics: use parent udev device to indicate `internal`

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/optionrom/fu-optionrom-device.c
- plugins/superio/fu-superio-device.c
- plugins/superio/fu-superio-it89-device.c
- plugins/synaptics-prometheus/fu-synaprom-device.c
- plugins/test/fu-plugin-test.c
- plugins/uefi/fu-uefi-device.c
- src/fu-common-version.c
- src/fu-common-version.h
- src/fu-device.c
- src/fu-device.h
- src/fu-engine.c
- src/fu-plugin.c
- src/fu-util.c
Don't show output for all devices - it doesn't work for most of them.
I also found that running verify on my Synaptics touchpad device puts it
into a pretty bad state until reboot.  That's of course a problem on
it's own, but at least prompting for it will prevent it from easily
happening.
> trivial: make verify and verify-update safer

- plugins/synaptics-cxaudio/synaptics-cxaudio.quirk
I saw a mention that they're actually CX21986 and had some on hand.
They do enumerate:
```
├─Pixel USB-C earbuds:
│     Device ID:           672c087de09848d9e7ee32aa1dea2fbeb8b81e6b
│     Summary:             CX21986 USB audio device
│     Current version:     71.133.20
│     Bootloader Version:  03.01.00.00
│     Vendor:              Google (USB:0x18D1)
│     Install Duration:    3 seconds
│     Flags:               updatable|registered
│     GUIDs:               d76048a5-ca69-5cb8-ac86-d418d70c5f29
│                          98043a29-72c5-549b-ad23-de4e2db20a14
│                          93279fe8-d478-531b-9637-05d026be3c2e
│                          8b71f776-f6d0-549d-9547-42740b24bbbc
```
> trivial: synaptics-cxaudio: Add Google Pixel buds

- plugins/colorhug/fu-colorhug-device.c
If calling `ch_strerror` with some values returns `NULL` which makes
the `GError` not get populated.
```
(self=0x560d7b57e160 [FuPlugin], device=0x560d7b5c4520 [FuColorhugDevice], symbol_name=0x560d7a3d4258 "fu_plugin_update_attach", device_func=0x560d7a3a4ac1 <fu_plugin_device_attach>, error=0x7ffc57a51040) at ../src/fu-plugin.c:1049
(self=0x560d7b4b9830 [FuEngine], device_id=0x560d7b64f200 "d45c9d222f7eeb3987c6a7674478bc6aec127b3f", blob_fw2=0x560d7b62c0d0, flags=FWUPD_INSTALL_FLAG_NONE, error=0x7ffc57a51150)
at ../src/fu-engine.c:2001
at ../src/fu-engine.c:2064
at ../src/fu-engine.c:1687
at ../src/fu-engine.c:1441
(gdb) print error_local
$1 = (GError_autoptr) 0x0
```
> trivial: colorhug: fix a crash that occurs when flashing sometimes

- contrib/fwupd.spec.in
- meson_options.txt
- plugins/coreboot/README.md
- plugins/coreboot/fu-coreboot-common.c
- plugins/coreboot/fu-plugin-coreboot.c
- plugins/coreboot/fu-plugin-coreboot.h
- plugins/coreboot/meson.build
- plugins/meson.build
- src/fu-plugin.c
- src/fu-plugin.h
Detect and parse current coreboot version.
An update mechanism isn't implemented as the kernel interface isn't
stable yet and will be implemented in a seperate commit.
Tested on coreboot enabled machine.
Example output:
coreboot System Firmware
DeviceId:             81104bde9db7cb037936659ea727c739f47a5029
Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a <- main-system-firmware
Guid:                 661cc3dc-620e-5de6-b50f-e908aaf481c9 <- LENOVO&ThinkPad T410&2537VG5&coreboot&CBET4000 4.10-991-ga726bfeb7d-dirty
Guid:                 8a05bfaf-6915-54dc-aecb-1c1416a7be8e <- LENOVO&ThinkPad T410&2537VG5&coreboot
Summary:              Open Source system boot firmware
Plugin:               coreboot
Flags:                internal|registered
Vendor:               LENOVO
Version: …
> plugins: Add coreboot plugin

- plugins/coreboot/fu-coreboot-common.c
- plugins/coreboot/fu-plugin-coreboot.c
- plugins/coreboot/fu-plugin-coreboot.h
```
../plugins/coreboot/fu-plugin-coreboot.c:96:7: error: assigning to 'gchar *' (aka 'char *') from 'const gchar *' (aka 'const char *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
name = fu_plugin_coreboot_get_name_for_type (plugin, NULL);
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../plugins/coreboot/fu-plugin-coreboot.c:98:8: error: assigning to 'gchar *' (aka 'char *') from 'const gchar *' (aka 'const char *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
name = fu_plugin_get_dmi_value (plugin, FU_HWIDS_KEY_PRODUCT_NAME);
```
> trivial: coreboot: fix a clang compiler error

- data/motd/fwupd-refresh.service.in
- src/fu-util.c
This was reported in Debian:
> approximately a few times a day fwupd is automatically called as "fwupd
> refresh". Unfortunately on my system it gets stuck in a busy loop trying
> to read from a stream. I believe that it fails to read, but it also
> fails to acknowledge an error condition, therefore keeping trying.
> 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942568
To me it looks like LVFS is disabled and trying to enable from systemd which isn't going so great.
> trivial: don't try to enable LVFS from systemd

- plugins/dell/fu-plugin-dell.c
It appears to only happen on non-dell systems trying to look up system
ID through `sysinfo_get_dell_system_id`
Other than CI non-dell systems won't be running this code.
> trivial: dell: work around a memory leak caught by address sanitizer

- contrib/debian/fwupd.install
- contrib/fwupd.spec.in
- data/motd/fwupd-refresh.preset
- data/motd/meson.build
- meson.build
Makes `fwupd-refresh.service` strictly opt-in.
Some distros are defaulting to all systemd services on and causing
more refreshes than desirable by default, especially when using
both `gnome-software` and `fwupd-refresh.service`
> Add a systemd preset file for `fwupd-refresh.service`

- src/fu-firmware.c
- src/fu-firmware.h
In the future, for firmware that supports getting a version we can check the
parsed version matches the version specified in the metainfo file.
> Add fu_firmware_set_version()

- src/fu-common.c
- src/fu-common.h
This allows us to put the offsets-to-offset checks in the right place.
> trivial: Add fu_common_read_uint16_safe()

- src/fu-usb-device.c
Some vendors use a space to fill, rather than NUL to terminate the string.
Keeping the space makes fwupdmgr and gnome-firmware look broken.
> Strip trailing whitespace from USB descriptors

- src/fu-tool.c
Makes using `fwupdtool detach` easier to use.
> trivial: fu-tool: Allow `detach`/`attach` to prompt for device

- src/fu-self-test.c
Currently the test runs for 100ms and looks to see that at least 8 times
the poll function callback hit.
This normally works well enough, but during self tests it depends upon
too much timing and leads to failures sometimes:
```
** (/<<PKGBUILDDIR>>/obj-s390x-linux-gnu/src/fu-self-test:50432): DEBUG: 15:37:55.189: poll cnt=0
*# DEBUG: poll cnt=1
** (/<<PKGBUILDDIR>>/obj-s390x-linux-gnu/src/fu-self-test:50432): DEBUG: 15:37:55.199: poll cnt=1
*** (/<<PKGBUILDDIR>>/obj-s390x-linux-gnu/src/fu-self-test:50432): DEBUG: 15:37:55.209: poll cnt=2
** (/<<PKGBUILDDIR>>/obj-s390x-linux-gnu/src/fu-self-test:50432): DEBUG: 15:37:55.227: poll cnt=3
*# DEBUG: poll cnt=4
** (/<<PKGBUILDDIR>>/obj-s390x-linux-gnu/src/fu-self-test:50432): DEBUG: 15:37:55.255: poll cnt=4
*# DEBUG: poll cnt=5
** …
```
> trivial: fu-self-test: increase timeout for polling self tests

- contrib/ci/dependencies.xml
- contrib/debian/lintian/fwupd
- meson.build
- plugins/uefi/efi/generate_binary.sh
- plugins/uefi/efi/meson.build
If the tool is available at build time use it to this.
> uefi: use `genpeimg` to mark ASLR and DP/NX on EFI binary

- plugins/ebitdo/ebitdo.quirk
This should get the plugin enumerating the SN30Pro+ and have it behave like the SN30Pro (expecting it to boot back up in Nintendo Switch mode after flashing)
> ebitdo: Add SN30Pro+ to recognized quirk list (Fixes: #1503)

- plugins/synaptics-prometheus/fu-synaprom-device.c
We can't use the IOTA mechanism in bootloader mode, and failing to create the
FuSynapromDevice object means we can't recover the hardware if the flash failed.
> synaptics-prometheus: Don't add a config-subdevice in bootloader mode

- data/bash-completion/fwupdtool.in
- src/fu-engine.c
- src/fu-engine.h
- src/fu-tool.c
To debug flashing failures it's sometimes requried to get a SPI dump of the
hardware to analysis.
Add a debug-only command that lets us dump the device from the engine.
> Allow verifying the device image itself from fwupdtool

- plugins/thunderbolt/README.md
- plugins/thunderbolt/fu-plugin-thunderbolt.c
Systems with multiple host controllers will most likely have a different
NVM image for each controller but there is no guarantee that the device_id
within the NVM image varies from one controller to another.
To account for this, build a GUID that contains the last element of the
Thunderbolt controller's udev path.
Sample GUID strings from an XPS 9380 (which only contains one host controller):
```
│     GUIDs:               0f401ed2-b847-532a-adc8-3193fc737be6 ← TBT-00d408af-native
│                          92516c2c-c6b6-5a30-a4c1-6722aa6ae2e0 ← TBT-00d408af-native:0-0
```
This commit follows the presumption that the kernel will enumerate the controllers
in the same order every time.
FYI: This hasn't actually been tested on a system with multiple host controllers …
> thunderbolt: Create a unique GUID including Thunderbolt controller path

- plugins/altos/fu-altos-device.c
- plugins/ata/fu-ata-device.c
- plugins/modem-manager/fu-mm-utils.c
- plugins/modem-manager/fu-mm-utils.h
- plugins/nvme/fu-nvme-device.c
- plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/unifying/fu-unifying-runtime.c
- src/fu-udev-device.c
- src/fu-udev-device.h
Just move the G_DEFINE_AUTOPTR_CLEANUP_FUNC to the internal header to avoid
forgetting to define this in each plugin.
> trivial: Fix a compile error with older versions of gudev

- plugins/fastboot/fu-fastboot-device.c
Set `IS_BOOTLOADER` unconditionally when in fastboot mode. This seems logically
what it is; a degraded mode that's able to update firmware without runtime
functionality.
Fixes https://github.com/fwupd/fwupd/issues/1532
> fastboot: Fix a regression when updating modem firmware

- contrib/fwupd.spec.in
- subprojects/flashrom.wrap
Once upstream flashrom tags a release (>1.1) this should be updated
and as it starts to flow into distros turned on by default.
> flashrom: switch to upstream source

- src/fu-udev-device.c
The read property from hidraw HID_ID is 0018:00002D1F:00004946 where
the vendor id 2D1F starts from offset 9 from base address.
This change probes the hidraw vid/pid with a wanted plugin properly.
> udev-device: fix offset of vendor id of hidraw devices

- plugins/synaptics-rmi/fu-synaptics-rmi-device.c
- src/fu-udev-device.c
Seeing these lately:
```
13:10:56:0973 FuDeviceLocker       failed to close device: Bad file descriptor
13:10:56:0981 FuEngine             failed to add udev device /sys/devices/pci0000:00/0000:00:02.0: failed to open (null): Bad address
```
> Fix some probe errors with recent changes 

- src/fu-udev-device.c
- src/fu-udev-device.h
Right now different integer sizes are used willy nilly and could
conceivably lead to overflow issues.
Additionally the values that come out of the kernel for `HID_ID`
are actually 8 digits, so they should be represented by a larger
data type.
This is a follow up for #1535 which is still correct, but this should hopefully scale better and be less fragile.
> fu-udev-device: Adjust bounds checking to be safer

- src/fu-usb-device.c
If for any reason loading these strings fail (e.g. the DW5821e/eSIM
module fails to load the product string when running the fastboot USB
layout), do not make the whole open operation fail. Instead, default
to an empty string, e.g. so that the same operation is no longer
attempted any more.
> usb: make loading vendor/product/serial strings non-fatal

- plugins/synapticsmst/fu-synapticsmst-device.c
This device was showing up from a LG 38UC99-W USB-C monitor
```
VMM0000:
Device ID:           d762543f8c20f636e6fff031a000078d3e10c600
Summary:             Multi-Stream Transport Device
Current version:     0.00.000
Vendor:              Synaptics
GUIDs:               42addef4-40f9-5e89-b925-d564e35ed368 ← MST-(null)-vmm0000-0
cf8c03c5-18bf-53c4-971f-4a08f88932b5 ← MST-(null)-0
e9427b6a-7389-5461-a592-1da5f8ec99fd ← MST-(null)
Device Flags:        • Updatable
```
> synapticsmst: filter invalid chip IDs

- RELEASE
- contrib/PKGBUILD
- contrib/ci/debian.sh
- contrib/ci/fedora.sh
- contrib/get-version.py
- meson.build
- plugins/synapticsmst/fu-plugin-synapticsmst.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
This is inspired by a change in flashrom to read the version string for meson
dynamically.
When making a release just put the version into `.version` to make the tarball
and tag the release as approriate.
No need for "post release version bump", this happens automatically from git
now by there being a dirty commit.
> Move the version definition of a release into `.version`

- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
- src/fu-main.c
- src/fu-util.c
- src/org.freedesktop.fwupd.xml
The check is mostly for making sure that if someone installs a snap that
they don't try to use a non-snapped command line client or vice versa.
However this makes development annoying because it is common to launch
the daemon manually in verbose mode without systemd when checking a
problem.  So allow setting an environment variable to make the client
ignore this check.
> fu-util: Allow overriding daemon/client check with environment variable

- plugins/modem-manager/fu-mm-device.c
The devices managed by this plugin expose version strings that are to
be treated as plain ASCII and compared just as plain ASCII.
- [X ] Improvement
> modem-manager: explicitly use plain version format

- plugins/uefi/efi/generate_binary.sh
Fixes #1530
I have not been able to reproduce the hang / crash in QEMU without a .cap. @okias Would you mind testing this?
> efi: use a wildcard section copy for final EFI generation

- src/fu-tool.c
- src/fu-util.c
Recently had a discussion on the expected behavior of calling
`#fwupdmgr update`/`fwupdtool update` with `--allow-reinstall`
in place.
It wasn't working which was confusing to the reporter, but I
feel that flag should only be usable with `install`.  Upgrades
are for upgrades and downgrades are for downgrades.  Reinstalls are
for reinstall.
> trivial: fu-util/fu-tool: explicitly block unsupported flags

- plugins/vli-usbhub/fu-vli-usbhub-device.c
- src/fu-usb-device.c
- src/fu-usb-device.h
Unfortunately we can't remove the usb2 and usb3 custom flags as we don't yet
depend on a new enough GUsb version.
> trivial: Detect the USB version automatically

- src/fu-ihex-firmware.c
- src/fu-ihex-firmware.h
The raw lines are required for some unspecified hardware.
> Tokenize the Intel Hex file before parsing

- plugins/uefi/efi/generate_binary.sh
command is a shell builtin unlike which, which might not be available.
While at it, let us also make the variables space-safe.
> uefi: Make generate_binary.sh more robust

- src/fu-engine.c
- src/fu-plugin-private.h
- src/fu-plugin.c
The plugins are not opened for this function so of course they
won't set their build hashes.
Fixes errors like this:
`uefi should call fu_plugin_set_build_hash()`
> fwupdtool: don't show a warning when calling `get-plugins`

- plugins/meson.build
The option was set but wasn't being used.
> trivial: plugins: only build coreboot when option set

- src/fu-device.c
- src/fu-history.c
- src/fu-idle.c
- src/fu-plugin.c
Linux doesn't care if you use g_rw_lock_reader_unlock() on a write lock, but
Windows really does.
> Use the correct unlocker when using GRWLock

- libfwupd/generate-version-script.py
This was also causing the _get_type() symbol to be ignored for objects without
any class methods except constructors.
> Ensure the _get_type() gets the same ABI version as the constructor

- libfwupd/fwupd-common.c
- libfwupd/fwupd-self-test.c
- meson.build
- plugins/dfu/dfu-tool.c
- plugins/flashrom/fu-plugin-flashrom.c
- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-tool.c
- src/fu-agent.c
- src/fu-common.c
- src/fu-main.c
- src/fu-offline.c
- src/fu-plugin.c
- src/fu-tool.c
- src/fu-util.c
DATADIR is an enumerated type in MinGW, and the other names are very generic.
> trivial: Use prefixes for DATADIR in config.h for portability

- src/fu-util-common.c
Current behavior for the prompt:
```
Y … Restart & Update
y … Restart & Update
N … Tool abort & Update complete after next Power cycle
n …Tool abort & Update complete after next Power cycle
0 … Pause -> (Push anykey) -> Restart & Update
* … Pause -> (Push anykey) -> Restart & Update
“”(Enter Only) … Restart & Update
```
If someone just keeps pressing enter without reading the system will reboot
which might lead to data loss.
Set the default scenario to abort reboot, so they can just see the message
to reboot instead.
> fu-util-common: Invert default behavior for reboot and shutdown prompts

- plugins/vli-usbhub/fu-vli-usbhub-device.c
- plugins/vli-usbhub/vli-usbhub-lenovo.quirk
- plugins/vli-usbhub/vli-usbhub.quirk
> vli-usbhub: Whitelist the PD and I²C devices

- libfwupd/fwupd-self-test.c
- meson.build
- plugins/uefi/fu-uefi-device.c
- plugins/uefi/fu-uefi-vars.c
- src/fu-common.c
- src/fu-common.h
- src/fu-engine.c
- src/fu-test.c
This also allows us to add a Win32 implementation if required in the future.
> trivial: Allow compiling without <fnmatch.h>

- docs/fwupd-docs.xml
- src/fu-engine.c
- src/fu-engine.h
- src/fu-plugin-private.h
- src/fu-plugin.c
- src/fu-self-test.c
This will allow us to export FuPlugin in the future without dragging in the
private fu-history.h too.
> trivial: Untangle FuHistory from FuPlugin

- docs/fwupd-docs.xml
- plugins/dfu/dfu-tool.c
This is a debug-only command line program, and we don't want plugins to have
access to the animated progressbar header in the future.
> trivial: Do not use FuProgressbar in dfu-tool

- contrib/debian/tests/ci
- data/installed-tests/fwupdmgr.sh
There have been a few transient failures on autopkgtest that are currently very difficult to debug.  Try to improve the installed-tests to work better on autopkgtest and to show verbose daemon logs when failures have happened.
> Improve debugging on autopkgtest

- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-device.c
It turns out this is useful for debugging.
> Export the device protocol to the client --verbose output

- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
This has not been in any tarball release and so isn't a ABI break.
> trivial: Convert the VersionRaw value to a uint64_t for future use

- plugins/wacom-raw/wacom-raw.quirk
These will all support the recovery feature added by 59970600adc171a183dddb90908e88b73727b832
> trivial: wacom-raw: mark all Moffett SKUs as self recovery

- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/ata/fu-ata-device.c
- plugins/nvme/fu-nvme-device.c
This allows us to specify with more detail how the device is opened.
> Add fu_udev_device_set_flags()

- contrib/ci/Dockerfile-debian.in
- contrib/ci/build_windows.sh
- contrib/ci/dependencies.xml
- contrib/fwupd.spec.in
- libfwupdplugin/fu-udev-device.c
- meson.build
- meson_options.txt
- plugins/dell/fu-plugin-dell.c
- plugins/meson.build
- plugins/tpm/README.md
- plugins/tpm/fu-plugin-tpm.c
- plugins/tpm/fu-tpm-device.c
- plugins/tpm/fu-tpm-device.h
- plugins/tpm/meson.build
- plugins/tpm/tpm.quirk
This plugin does not yet allow the device to be upgraded, and is provided for
information only.
> Add a new plugin that exposes the system TPM device firmware version

- src/fu-install-task.c
Currently devices with a matching GUID will match any metadata that
has the same GUID.
For Dell in the future there will be a situation that the same GUID
is supported by two different FwupdDevice objects but the payload
required for the different objects will vary.
So start matching the protocol and the GUID both to make sure that
the right Fwupd device gets matched from the metadata.
> fu-install-task: Enforce that device protocol matches metadata

- po/POTFILES.in
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
- src/fu-remote-list.c
- src/fu-remote-list.h
- src/meson.build
It's confusing to have FuConfig load both the daemon.conf file and also keep
track of the enabled remotes. It's also wasteful of memory to keep the GKeyFile
alive the entire time.
Logically these are different pools of information and should be managed by
different objects. This allows us to implement reload() in a sane way.
> Split out the remote loading from FuConfig

- plugins/synaptics-rmi/synaptics-rmi.quirk
Right now vendor string is detected by walking up the udev chain
until a vendor is found.  On some systems this is finding incorrect
data such as `Intel Corporation` for the vendor on the touchpad.
As the plugin only supports Synaptics devices, Correct it by hardcoding
vendor to `Synaptics`.
Sample output:
```
└─Touchpad:
Device ID:           b26933c085b020ecf84c490812458523aee710ac
Current version:     1.5.2767034
Bootloader Version:  54.0
Vendor:              Synaptics (HIDRAW:0x06CB)
GUIDs:               f4384034-9243-5334-8075-a534be913e46 ← HIDRAW\VEN_06CB&DEV_76AF&REV_00
424bd00e-9789-5cdf-a12a-3c81bc4676d6 ← HIDRAW\VEN_06CB&DEV_76AF
140f4458-951b-5bb9-85e2-879bd5b02615 ← SYNAPTICS_RMI\TM3038-003
b29d3c85-cd0e-503e-9c7e-f6731c1eaf2d ← SYNAPTICS_RMI\TM3038
Device Flags:        • …
```
> trivial: synaptics-rmi: hardcode Vendor string

- src/fu-engine.c
These messages are useful for debugging but not to users.  Many issues
get filed because they're cryptic and users can't do anything about them.
Downgrade the actual messages to debugging in the engine, and just send
back a generic message for clients.
Fixes: #1659
Fixes: #1261
> engine: don't expose bootloader version errors to users

- plugins/coreboot/meson.build
This fixes the build when using samurai in place of ninja.
> plugins/coreboot: Add missing fu_hash dependency

- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- plugins/nvme/fu-nvme-device.c
- plugins/optionrom/fu-optionrom-device.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
Fixes bugs like https://github.com/fwupd/fwupd/issues/1673
> Don't always get the vendor ID for udev devices using the parent

- contrib/ci/Dockerfile-fedora.in
- src/fu-main.c
We can just rescan hardware if required; near OOM it's just more important to
free what we can and get out of the way.
> Shut down automatically when there is system memory pressure

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- src/fu-install-task.c
- src/fu-self-test.c
- src/fu-util-common.c
These are devices that we have to be careful with the version numbers, for
instance only updating from versions that have already had data migration
completed.
The new flag can be set in quirk files or on the objects directly.
> Allow quirking devices that always require a version check

- src/fu-remote-list.c
This should notify the daemon of changes before the inotify letting
the data store get reloaded and fix autopkgtest race conditions.
Fixes: #1648
> fu-remote-list: emit a changed signal when modifying a remote

- contrib/ci/debian.sh
There appears to have been some transient failure over the holiday that pre-empted this commit getting added that I can tell.  I think it's since been fixed, confirming CI works now.
This reverts commit 9e8037483a8899608746554af58b0c675ddd9f66.
> Revert "trivial: Attempt to fix Debian CI"

- .travis.yml
- contrib/ci/debian.sh
- src/fu-common-version.c
- src/fu-common-version.h
- src/fu-engine.c
- src/fu-install-task.c
- src/fu-self-test.c
This is a backport from master (see commit messages for details on the commits that were backported).
From my tests with 1_2_X today:
```
.
.
.
XPS 13 9380 System Firmware
DeviceId:             6c24a747f97668873b761558e322398a91dbf394
Guid:                 ce945437-7358-49f1-95d8-6b694a10a755
Plugin:               uefi
Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
Checksum:             SHA1(6ddd903e2a0e59dd22e626257b38ac0737e574ac)
Checksum:             SHA256(4bdad6114fdbce849c3682ca72fa8a07f49cc61ed0a196cc02dc10a5df523383)
Vendor:               Dell Inc.
Version:              0.1.8.0
VersionLowest:        0.1.8.0
VersionFormat:        quad
Icon:                 computer
Created:              2020-01-07
.
.
.
Decompressing… …
```
> 1_2_x: Fix always being able to reinstall same firmware on dell system

- libfwupdplugin/fu-firmware-image.c
- plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c
There's no reason to prevent NULL, and doing so means the caller has to check
before setting the value. Only one subclassed type was actually doing this...
> trivial: Allow setting an ID of NULL for the FuFirmwareImage

- src/fu-engine.c
The PEM data is larger than 2kB, which was a crazy-small max size for a
signature. Make this a more respectable 1Mb so that we can load PKCS-7
signatures with full certificate info included.
This wasn't being tested in the self tests as it only affects data read from
the remote file descriptor.
> Correctly import PKCS-7 remote metadata

- contrib/debian/fwupd.postinst
> trivial: debian: Don't use --parents when rmdir'ing /var/*/fwupdate

- plugins/synaptics-mst/fu-synaptics-mst-device.c
Synaptics versions are encoded as BCD, the largest version that will
ever be represented in this field is '99'.
Using 3 digits in this field has caused multiple problems in upgrades from
LVFS.
1. Devices are being upgraded when not necessary.
IE `5.3.10 > 5.3.010`
2. Device upgrades are deemed failures as follows:
```
BootTime=1571436076,
CompileVersion(com.redhat.efivar)=37,
CompileVersion(com.redhat.fwupdate)=12,
CompileVersion(org.freedesktop.fwupd)=1.3.2,
CompileVersion(org.freedesktop.gusb)=0.3.0,
CpuArchitecture=x86_64,
DistroId=fedora,
DistroVariant=workstation,
DistroVersion=32,
FirmwareId=1915,
Flags=4194346,
Guid=f15aa55c-9cd5-5942-85ae-a6bf8740b96c,
MachineId=97aa89528b88d9631867a4e20c68a5208124ef592e19d05f0c5e7d22bd4d7afb,
Plugin=synapticsmst, …
```
> trivial: synaptics-mst: adjust last part of triplet to be 2 digits not 3

- contrib/ci/fedora.sh
RPM doesn't allow '-' in the version number,
so this must be fixed if also when building from
an untagged git tree.
sanitize_for_ci() from get-version.py
fixes it only when build is CI environment.
Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
> ci: fedora: force correct rpm package version

- contrib/ci/generate_docker.py
Fedora doesn't distribute docker anymore, instead
it uses podman for the containers.
It is possible to alias podman to docker, but
it's less hassle if it will work just out of the box.
The fix here is simple the podman is a fallback if
docker is not found.
Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
> ci: allow working with podman w/o aliases

- contrib/fwupd.spec.in
This is similar to commit 1ff11646305 ("trivial: debian/control*: Update
for fwupdate transition") but to provide a fwupdate transition in RHEL 8
where the fwupdate{,efi} packages are still present.
There is no need to do this for Fedora, since the fwupdate packages have
already been retired.
> trivial: provide a fwupdate transition for RHEL 8

- plugins/vli/README.md
- plugins/vli/fu-vli-device.c
In some composite dock hardware there are two USB devices exported to the host,
both with the same VID:PID values. We need to use the device type (e.g. VL812B3)
to differenciate the devices and install the correct fw on the correct device.
@memily
> vli: Add the DEV instance ID to all devices

- data/tests/lockdown/locked/lockdown
- data/tests/lockdown/none/lockdown
- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- plugins/superio/fu-plugin-superio.c
This should avoid at least one cause of this showing up in dmesg every time fwupd starts:
```
Lockdown: fwupd: /dev/mem,kmem,port is restricted; see man kernel_lockdown.7
```
> Detect kernel lockdown

- plugins/uefi/fu-uefi-device.c
It seems that fwupd.efi is picking up both fwupdate-* and fwupd-*
entries that are sitting around in efivarfs.
> Cleanup ancient fwupdate-* EFI variables too (Fixes: #1739)

- plugins/uefi/efi/meson.build
gnu-efi 3.0.11 moves a few files around, e.g.
/usr/lib64/gnuefi/elf_x64_efi.lds -> /usr/lib64/gnuefi/x64/efi.lds
...and this causes the UEFI EFI helper to fail to link.
Add support for the 'new' paths and fall back to the old ones.
Fixes https://github.com/fwupd/fwupd/issues/1736
> Support the new gnuefi file locations

- .circleci/config.yml
This should allow using a git client provided by the OS, not CircleCI.
Hopefully it helps the deployment job for the next release.
> trivial: Re-order circleci commands

- src/fu-engine-helper.c
This matches the optional other lines that show updates.
Current experience:
```
Welcome to Ubuntu Focal Fossa (development branch) (GNU/Linux 5.4.0-12-generic x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
* Multipass 1.0 is out! Get Ubuntu VMs on demand on your Linux, Windows or
Mac. Supports cloud-init for fast, local, cloud devops simulation.
https://multipass.run/
1 device has a firmware upgrade available.
Run `fwupdmgr get-upgrades` for more information.
10 updates can be installed immediately.
0 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Last login: Thu Jan 16 21:00:01 2020 from 127.0.0.1
```
Updated experience:
```
Welcome to …
```
> trivial: fu-engine-helper: Add whitespace to motd

- plugins/uefi/efi/fwup-debug.c
- plugins/uefi/efi/fwup-efi.c
- plugins/uefi/efi/fwupdate.c
This code is obviously causing regressions and the algorithm in use for deleting the various boot variables needs some adjusting.  For now, revert that commit to unbreak systems and perhaps algorithm can be adjusted later.
> Revert 7b15a4d646845496da18ddff6a48e83f6d50173a

- src/fu-install-task.c
- src/fu-self-test.c
This fixes the upgrade from 5101AALB to 51H0AALB, which fwupd was comparing as '5101' > '51'.
> Do not use fu_common_vercmp() when the device verfmt is PLAIN

- contrib/fwupd.spec.in
- plugins/upower/fu-plugin-upower.c
- plugins/upower/meson.build
- plugins/upower/upower.conf
Dell's behavioral spec for this aligns the threshold for this at 10%
rather than 30%.
Validation engineers have have a flurry of reports about this behavioral difference when comparing it to Windows.  So align it to the Dell spec.  If this is contentious as a general adjustment, I can adjust the PR to examine the vendor from SMBIOS data and have a Dell value in addition to general value.
> upower: Decrease minimum battery requirement to 10%

- plugins/uefi/efi/meson.build
This fixes the Flatpak build of fwupd.
> uefi: Find the correct lds and crt name when specifying -Defi_ldsdir

- src/fu-engine.c
If the device replugs, then we were doing `g_set_object(&device, device_tmp)`
which worked, but had the unfortunate effect of not unwinding properly as
`device` was a function parameter rather than a local variable.
The observed effect using `watch ((GObject*)$1)->ref_count` was the refcount was
double-decremented and thus we got a critical warning on the final valid unref.
Fix this by copying the function parameter to a local variable which we can
then change if the device replugs.
> Fix a critical warning when installing some firmware

- plugins/uefi/efi/fwupdate.c
Currently if there is an invalid boot entry for firmware update, the fwupd
EFI program will not call UpdateCapsule(), even if there is a valid entry.
For example, if the following entries exist the firmware update will fail:
HD(1,GPT,A672BBCA-325E-4D6F-91E1-DD57FAA85A9C)/\EFI\rhel\fw\fwupdate-6cialq.cap ... /*Valid entry*/
HD(1,GPT,E8176B29-6F73-43F2-AE8E-05E09DE20EE5)/\EFI\fedora\fw\fwupd-6dcbd5ed-e82d-4c44-bda1-7194199ad92a.cap ... /*InValid entry*/
Ensure capsule update is happening even if a valid capsule entry exists.
Signed-off-by: Bhaskar Upadhaya <bupadhaya@marvell.com>
> uefi: Apply capsule update even with single valid capsule

- RELEASE
- plugins/uefi/generate-quirk.py
- plugins/uefi/meson.build
- plugins/uefi/uefi-lvfs-generated.quirk
The UEFI ESRT table just gives us a table of GUIDs with some basic flags, and
isn't very useful to end users. This is acceptable for Dell as there is only
typically one ESRT entry, which is for the system firmware. On typical Lenovo
hardware there might be half-a-dozen different 'Device' entries which all look
very similar.
As it's not possible to get a channel-of-data from the ODMs to fwupd, use the
existing LVFS metadata to generate some better names for these devices.
Although this looks like a lot of repeated data, libxmlb helpfully dedupes the
strings for us, making the quirk store only slightly larger.
Also, I've deliberately made this a manual step as we're not going to have
internet access on distro builders, and I'd also like the fwupd tarball output
to be deterministic and …
> Generate an additional UEFI quirk file using the stable LVFS metadata

- contrib/ci/dependencies.xml
- contrib/debian/control.in
- contrib/debian/fwupd.install
- contrib/debian/gen_signing_json
- contrib/debian/lintian/fwupd
- contrib/debian/rules
- contrib/debian/signing-template/fwupd-SIGNARCH-signed.install
- contrib/debian/signing-template/rules
Include some updates from packaging in Debian, and then also shuffle some binaries that users can execute around to `usr/lib`.
See #1783 for more details.
CC:
@bigon
@martinezjavier
> Move binaries around to better adhere to FHS 3.0

- contrib/ci/README.md
- contrib/ci/generate_dependencies.py
- contrib/ci/generate_docker.py
Sometimes it is desirable to create a build environment
outside of docker.
Move dependencies parser to a standalone python script
and call it from generate_docker.py
Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
- [v] Feature
> ci: use standalone script to generate build dependencies

- libfwupdplugin/fu-plugin-private.h
- libfwupdplugin/fu-plugin-vfuncs.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fwupdplugin.map
Sometimes the plugin will want to influence the subclassed device, for instance
by reading a per-plugin config file. At the moment there's no way to do this,
as even _device_registered() is explicitly designed for devices *not* created
by the plugin itself.
Even if _device_registered() was changed to include the plugin creating the
object it would still happen well after the device has done _probe() and/or
_setup() and would probably be too late to do anything useful.
> Add a plugin vfunc to run after subclassed FuDevice creation

- libfwupdplugin/fu-common-version.c
- libfwupdplugin/fu-common-version.h
- libfwupdplugin/fwupdplugin.map
- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/dell-dock/fu-dell-dock-i2c-tbt.c
- plugins/modem-manager/fu-plugin-modem-manager.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- src/fu-engine.c
- src/fu-install-task.c
- src/fu-offline.c
- src/fu-util.c
In 1de7cc we checked the version format when checking for update, but there are
many other places that are doing verfmt-insensitive comparisons. For instance,
the predicates in <requires> all fail if the device version format is plain.
his breaks updating some NVMe drives where the `ne` requirements are not
semantic versions.
To avoid trying to catch all the bugs in different places, and in case we have
a future verfmt that should be treated another way, refactor this out in to a
common function and deprecate the old function.
> Always check for PLAIN when doing vercmp() operations

- src/fu-device-list.c
- src/fu-self-test.c
Some Dell devices offer the exact same GUID in UEFI as well as in NVME
plugins.  These devices can be flashed in either way, but the payload
for them is different.
The UEFI payload includes relevant headers and metadata to be acceptable
from a capsule.  The NVME payload is raw data that the drive will process.
Since baa9e75ca86f29239de03f7ab86a3e1309c37ac0, fwupd should enforce that
the correct device is flashed with the correct protocol.
> fu-device-list: Check protocol before de-duping devices

- libfwupdplugin/fu-common-cab.c
- libfwupdplugin/fu-self-test.c
- meson.build
- src/fu-self-test.c
We can fall back to the subproject version if required for CI targets.
> Remove support for GCab less than v1.0

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupdplugin/fu-quirks.h
- plugins/dell/dell.quirk
- plugins/dell/fu-plugin-dell.c
- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-device.c
- src/README.md
- src/fu-engine.c
- src/fu-util-common.c
It appears just choosing 'if Dell then QUAD else TRIPLET' isn't good enough.
> Allow server metadata to set the version format on some devices

- plugins/nvme/fu-nvme-device.c
We've never come across a drive that uses anything other than plain.
> nvme: Do not try to handle integer version numbers

- libfwupdplugin/fu-quirks.c
Type of pull request: [ X ] Code fix
Use xb_builder_source_add_simple_adapter instead
xb_builder_source_add_adapter to avoid sniffing MIME type for output xml
contents
> Use xb_builder_source_add_simple_adapter

- src/fu-engine.c
In Chrome OS /etc/machine-id is not available on the sandbox
environment. Chrome OS specifically rotate it constantly and is
considered PII.
Signed-off-by: Daniel Campello <campello@chromium.org>
- [ x ] Code fix
> Do not fail loading in /etc/machine-id is not available

- contrib/debian/fwupd.install
- contrib/fwupd.spec.in
- data/fish-completion/fwupdmgr.fish
- data/fish-completion/meson.build
- data/meson.build
I saw this repository already contains a completion script for bash. This PR adds a completion script for fish shell.
In case you don't like including it here, I could also submit it to the fish repository. However, it usually is preferred to ship completion scripts by upstream projects and bash is already included here.
What I have not done so far is adding the script to the spec file. It would belong into `/usr/share/fish/vendor_completions.d`.
> Added completion script for fish shell

- src/fu-remote-list.c
At the moment we're returning plain text for the embargo remotes and AppStream
markup for LVFS remotes. This fixes the warning on the console:
$ fwupdmgr enable-remote lenovo_thinkpad-embargo
failed to compile foo: Document must begin with an element (e.g. <book>)
> Always return AppStream markup for remote agreements

- plugins/vli/fu-vli-usbhub-i2c-device.c
Apparently the Windows tool ignores the first byte, so we should too.
> vli: Set the MSP430 version format to pair

- data/fish-completion/fwupdmgr.fish
Just a small addition to the fish shell completion script I previously contributed. When completing device IDs, it now shows the device name as a description. This makes it easier to select the correct hex value.
Though, it is of limited use when most of the devices are just "UEFI Device Firmware".
By the way, @superm1 I think your bash completion broke when output format for `get-devices` and `get-remotes` changed a while back. Completing device and remote IDs in bash is currently not working.
> Improved fish shell completion

- data/bash-completion/fwupdmgr.in
- src/fu-util-common.c
Thanks @exploide for the notification it was broken.  Resolve `get-devices` and `get-remotes` output to work properly.  Hopefully by slicing and dicing `fwupdagent` output the `get-devices` is less likely to break in the future.
> Fix bash completion

- .circleci/config.yml
(This is merging to 1_3_X)
We don't use snap channels (currently), so we don't want a potential
1.3.10 to overwrite a 1.4.1 in the future.
Also we want documentation to always be the latest.
> disable snap and doc deployment for 1_3_X

- data/fwupd.shutdown.in
I think that this file has been forgotten, when the movement of fwupdtool to bindir has been done. At least I get an error message now during shutdown.
> fix fwupd.shutdown.in according to the movement of fwupdtool to bindir

- src/fu-engine.c
The cabinet file's extension name disregards uppercase or lowercase
> trivial: case insensitive while explorering cabinet files

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupdplugin/fu-common-version.c
- libfwupdplugin/fu-self-test.c
CPU microcode is distributed with a hexadecimal version.
Without this, UEFI device firmware for microcode shows with master:
```
Current version:     200
```
Various formats to try to render it:
```
•	Plain: 200
•	BCD: 0.0.0.128
•	Quad:  0.0.0.128
```
With this PR (and a quirk to set `VersionFormat` in place) renders as
```
Current version:     0x000000c8
```
> Add hexadecimal version format

- src/meson.build
Otherwise build fails with:
src/meson.build:196:2: ERROR: Unknown variable "fwupdagent".
Gentoo-bug: https://bugs.gentoo.org/711682
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>
> Don't build/install fwupdagent man page if agent build is not requested

- contrib/snap/activate-shutdown/fwupd-activate.service
Instead of using `RequiresMountsFor=/snap/fwupd/current`, which will not work since `/snap/fwupd/current` is a symlink [1].
This will work since the mount units generated by snapd all have `Before=snapd.service`, so will be stopped after `snapd.service` during shutdown.
With `After=snapd.service`, `fwupd-activate.service` will then stop before `snapd.service`, at a point when all snap mount units are still alive.
Fixes the issue where `fwupd-activate.service` hangs when stopped, causing a stop job timeout during shutdown.
[1] See https://github.com/systemd/systemd/issues/8907
Closes #1654
@superm1 @hughsie
> Start fwupd-activate.service after snapd.service

- src/fu-device-list.c
Use only one GMainLoop in FuDeviceList; we can only iterate one loop at a time
anyway, and having the mainloops per-item complicates the lifecycle of the
fu_device_list_wait_for_replug() functionality considerably.
> Fix a difficult-to-trigger daemon hang when replugging devices

- data/fish-completion/fwupdmgr.fish
I learned in #1872 that `update` can take a device ID. This PR reflects that in fish autocompletion.
> trivial: update command consumes device ids in fish shell completion

- contrib/fwupd.spec.in
- libfwupdplugin/fu-firmware-image.c
- plugins/ccgx/README.md
- plugins/ccgx/fu-ccgx-common.h
- plugins/ccgx/fu-ccgx-cyacd-firmware-image.c
- plugins/ccgx/fu-ccgx-cyacd-firmware-image.h
- plugins/ccgx/fu-ccgx-cyacd-firmware.c
- plugins/ccgx/fu-ccgx-cyacd-firmware.h
- plugins/ccgx/fu-plugin-ccgx.c
- plugins/ccgx/meson.build
- plugins/meson.build
These are visually similar to Intel hex files, but different enough to demand
their own parser. Multiple images can be stored in one firmware file, with the
`addr` set to the SiliconID and the `idx` set to the position in the file.
> ccgx: Add a firmare parser for cyacd files

- libfwupdplugin/fu-hid-device.c
- libfwupdplugin/fu-hid-device.h
- libfwupdplugin/fu-plugin.h
- libfwupdplugin/fu-usb-device.h
- libfwupdplugin/fwupdplugin.map
- libfwupdplugin/meson.build
- plugins/csr/fu-csr-device.c
- plugins/csr/fu-csr-device.h
- plugins/dell-dock/fu-dell-dock-hid.c
- plugins/dell-dock/fu-dell-dock-hub.c
- plugins/dell-dock/fu-dell-dock-hub.h
- plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.c
- plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.h
- plugins/rts54hid/fu-rts54hid-device.c
- plugins/rts54hid/fu-rts54hid-device.h
- plugins/rts54hid/fu-rts54hid-module.c
- plugins/synaptics-cxaudio/fu-synaptics-cxaudio-device.c
- plugins/synaptics-cxaudio/fu-synaptics-cxaudio-device.h
- plugins/wacom-usb/fu-wac-device.c
- plugins/wacom-usb/fu-wac-device.h
- plugins/wacom-usb/fu-wac-module.c
Quite a few plugins use HID commands to communicate with the hardware. At the
moment we have ~6 implementations of SET_REPORT and are soon to add one more.
Move this into common code.
> Add FuHidDevice abstraction

- plugins/csr/fu-csr-device.c
This was changed to Intel hex in 7afd7cba0d327b155b2201c9fbb5414ced9cfe06,
probbaly due to a copy-paste mistake. Change it back to DFU.
Fixes https://github.com/fwupd/fwupd/issues/1890
> csr: Parse the firmware as a DFU file

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.h
- plugins/ata/fu-ata-device.c
- plugins/ata/fu-self-test.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
- plugins/vli/fu-vli-device.c
- plugins/wacom-raw/fu-wacom-device.c
Sometimes we only want to add the instance ID to get the quirk matches, and it
is confusing to see the "fake" IDs in the 'fwupdmgr get-devices' output.
> trivial: Export fu_device_add_instance_id_full() for plugins to use

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
Sometimes plugins need to retry various commands send to hardware, either due
to unreliable transfers (e.g. using USB bulk) or from slightly quirky hardware.
Between them they seem to get various things wrong; either the error messages
are repeated and thus difficult to parse, or they just get the memory handling
of `g_propagate_prefixed_error()` wrong.
Providing a helper object we can reduce the amount of boilerplate. Additionally
we can support a 'reset' function that can try to automatically recover the
hardware for specific error domains and codes.
> Add FuDeviceRetry helper object

- plugins/thunderbolt/README.md
- plugins/thunderbolt/fu-plugin-thunderbolt.c
Here's the third try at a GUID that is unique but consistent enough when two controllers on the host system share the same vendor ID and device ID.
> Swap out GUID for multiple controllers with same ID

- meson.build
- src/fu-main.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
This fixes the common problem encountered when developing plugins:
./src/fwupdmgr get-devices
Unsupported daemon version 1.4.0, client version is 1.4.0-179-gcf8095d5
> trivial: Use the same source version string between daemon and client

- snap/snapcraft.yaml
libjcat bumped the meson dep up newer than we were using.
> trivial: snap: build using meson 0.54

- plugins/ccgx/README.md
- plugins/ccgx/ccgx.quirk
- plugins/ccgx/fu-ccgx-hpi-device.c
The VID:PID of the device in HPI mode is shared between multiple vendors, and
so we need to use both the silicon ID and the application ID to match specific
firmware updates.
> ccgx: Add extra instance IDs to match specific firmware

- plugins/vli/fu-vli-pd-device.c
The default re-enumeration delay is not sufficient.
> vli: Wait for the VL103 to timeout to fix detach

- data/daemon.conf
- plugins/dfu/dfu.quirk
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
At least to discuss.  This fixes all my Logitech peripherals not showing up.  I finally now understand the experience for stuff not currently connected too and why the DJ changes are important.
@FFY00 I think that the plugin will need to respond to change events to update version string (both connect and disconnect most likely).
Fixes: #1877
> logitech_hidpp: show devices for all peripherals not just supported ones

- contrib/ci/generate_docker.py
- src/fu-self-test.c
This ports the fix https://github.com/hughsie/libjcat/commit/6ac46df8e754006b0e8900e16a8ee6412a8d7360
from libjcat to fwupd 1_3_X.  master is not affected.
> trivial: fix self tests for empty `/etc/machine-id` (LP: #1870051)

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-util-common.c
Show it in the various command line tools if it has been set by the vendor.
Fixes https://github.com/fwupd/fwupd/issues/1945
> Export the release creation time

- plugins/vli/fu-plugin-vli.c
- plugins/vli/fu-vli-usbhub-pd-device.c
The cleanup action for the FuVliUsbhubPdDevice is correct, but was not
conditionalized in the composite cleanup, which meant we would reboot twice
for a normal USB hub update.
Move the parent reboot into the right place, although this does mean we might
reboot twice in the rare event of scheduing a FuVliUsbhubPdDevice *and*
FuVliUsbhubDevice update in the same transaction -- but resetting the device
state between updates is arguably correct anyway...
> vli: Only reboot the USB hub once

- libfwupd/fwupd-remote.c
- libfwupd/fwupd-remote.h
- libfwupd/fwupd.map
- libfwupd/meson.build
- src/fu-util.c
Switch to downloading the signature first, which we can then load to get the
suffixed build-specific URL of the actual metadata file. You need to have
libjcat 0.1.1 installed and fwupd built against the new version for this to
work.
Fixes https://github.com/fwupd/fwupd/issues/391
> Load the signature to get the aliased CDN-safe version of the metadata

- data/meson.build
The README says: "A test suite that can be used to interact with a fake device is installed when configured with `-Ddaemon=true` and `-Dtests=true`", so actually only install these tests when tests are enabled.
> Install the installed-tests only if tests are enabled

- plugins/logitech-hidpp/fu-logitech-hidpp-peripheral.c
This should fix flashing firmware when there are >= 2 receivers plugged in.
Fixes https://github.com/fwupd/fwupd/issues/1951
> logitech-hidpp: Do not add peripheral devices for receiver in BL mode

- plugins/ccgx/ccgx.quirk
Update message is moved to cab file.
See https://github.com/hughsie/lenovo-cypress-firmware.
> ccgx: remove update message

- data/device-tests/devices/realtek-rts5855.json
- data/device-tests/devices/starlabs-phison-ata.json
- data/device-tests/devices/synaptics-prometheus.json
- data/device-tests/devices/wacom-intuos-bt-m-bluetooth.json
- data/device-tests/devices/wacom-intuos-bt-m-main.json
- data/device-tests/hardware.py
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/colorhug/fu-colorhug-device.c
- plugins/dfu/dfu-device.c
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/fastboot/fu-fastboot-device.c
- plugins/jabra/fu-jabra-device.c
- plugins/nitrokey/fu-nitrokey-device.c
- plugins/vli/fu-vli-device.c
- plugins/wacom-usb/fu-wac-device.c
- plugins/wacom-usb/fu-wac-module.c
- src/fu-device-list.c
Doing this unconditionally means we accidentally 'bleed' one device mode into
another in a non-obvious way. For instance, a device might have two operating
modes with different GUIDs. If firmware is supplied for both modes in the same
cabinet archive then we might accidentally match the 'wrong' firmware when
the daemon has observed a mode switch and added the counterpart GUIDs.
We only really need the counterpart GUIDs when switching between Jabra and DFU
devices where the DFU bootloader VID:PID is not manually tagged with
`CounterpartGuid` in a quirk file. In the general case lets keep it simple to
avoid difficult to find bugs.
> Only auto-add counterpart GUIDs when required

- src/fu-device-list.c
This was missed for the conversion of 1e571730d0b39574c3d7f2d0cc38e7c859205dbc
> Fix a crash when removing device parents

- data/device-tests/devices/logitech-rqr12-signed.json
- data/device-tests/devices/logitech-rqr12.json
- data/device-tests/devices/logitech-rqr24-signed.json
- data/device-tests/devices/logitech-rqr24.json
- data/device-tests/hardware.py
This allows us to run the device tests with all 4 supported types of unifying
dongles plugged in at the same time.
> trivial: Allow filtering the device-test by the protocol

- data/device-tests/devices/lenovo-03x7609-vli-tier1.json
- data/device-tests/devices/lenovo-03x7609-vli-tier2.json
- libfwupdplugin/fu-plugin.c
- plugins/colorhug/fu-colorhug-device.c
- plugins/ep963x/fu-ep963x-device.c
- plugins/logitech-hidpp/fu-logitech-hidpp-peripheral.c
- plugins/synaptics-prometheus/fu-synaprom-config.c
- plugins/synaptics-prometheus/fu-synaprom-device.c
- plugins/synaptics-rmi/fu-synaptics-rmi-device.c
- plugins/synaptics-rmi/fu-synaptics-rmi-v5-device.c
- plugins/vli/fu-vli-pd-device.c
- plugins/wacom-raw/fu-wacom-device.c
This is nice in theory, until you need to look at the bootloader status of the
parent, or of a different device entirely. Handle this in plugins for the few
cases we care about and stop setting or clearing IS_BOOTLOADER manually just to
get the vfuncs to be run.
Note: I do not think we want to use cleanup() for attaching devices not in
bootloader states -- as cleanup is only run at the end of the composite update.
> Do not conditionalize attach() and detach() on IS_BOOTLOADER

- libfwupd/fwupd-self-test.c
- libfwupd/meson.build
```
ok 10 /fwupd/client{remotes} # SKIP no valid daemon: Error calling StartServiceByName for org.freedesktop.fwupd: Failed to activate service 'org.freedesktop.fwupd': timed out (service_start_timeout=25000ms)
ok 11 /fwupd/client{devices} # SKIP no valid daemon: Error calling StartServiceByName for org.freedesktop.fwupd: Failed to activate service 'org.freedesktop.fwupd': timed out (service_start_timeout=25000ms)
```
> trivial: skip some self tests if system isn't set up properly

- meson.build
In this case git exists, but there's no git checkout and so the source version
is an empty string.
> Define SOURCE_VERSION when building a package

- plugins/logitech-hidpp/fu-logitech-hidpp-peripheral.c
These are a regression of 9e755e2a5 when devices are asleep.
However due to the current kernel and daemon architecture, logitech devices
are not checked again at any time so if the device isn't awake when
fwupd is started or the unifying dongle is plugged in it won't be present.
This will be changed in the future when the kernel has change events
associated with devices waking up.
Fixes: #1973
> logitech_hidpp: decrease verbosity of messages that hid++ ID is missing

- data/installed-tests/meson.build
On NixOS, we want to install installed tests to a different prefix. Factoring out the path into a variable will make it easier for us to patch the path.
> build: Re-use installed tests directory

- plugins/ebitdo/fu-ebitdo-device.c
- src/fu-engine.c
The idea here is that the device would not come back after it was restarted,
and skipping the attach in the engine was only working around the fact that the
ebitdo did not split out an ->attach() function.
We can't really blame it; we only decoupled the _IS_BOOTLOADER requirement
for ->attach() recently...
> Do not skip attach() if the device is marked _WILL_DISAPPEAR

- src/fu-device-list.c
The fu_device_list_replace() function does this automatically.
> trivial: Remove double call to g_source_remove()

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-quirks.h
- libfwupdplugin/fwupdplugin.map
- src/fu-engine.c
This allows us to use a proxy even if the proxy device was created in a
different plugin or where the GTypes are not known to each other.
> Allow devices to match the proxy device by GUID

- src/fu-engine.c
Cached metadata was not working for setting the supported flag because
of a difference in version format.  The version format needs to be applied
to the device before applying the supported flag.
This particularly helps UEFI devices which set the version format to number
but in practice all metadata sets it to something different.
Fixes: #2005
> fu-engine: Refresh device name and format before setting supported flag

- data/meson.build
- meson.build
- meson_options.txt
Replaces #2004
It is a good practice to install files relative to our own variables
bassi.io/articles/2018/03/15/pkg-config-and-paths
and it is required on systems like NixOS.
Unfortunately, systemd allows overriding the root prefix,
see also systemd/systemd@1c2c7c6,
so we cannot just do that.
Let's at least make the systemd installation prefix overridable.
This will also allow us to drop `systemdsystemunitdir` option since
systemd hardcodes it to `${rootprefix}/lib/systemd/system`.
> build: Allow overriding prefix for systemd file installation

- libfwupd/fwupd-common.c
- libfwupd/fwupd-common.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- libfwupdplugin/fu-device.c
The returned ID is the result of the SHA1 hash of the actual device ID. This
does not match anything found by the client, and so the install fails.
The symbol is exported as I think the device ID is an important identifier and
used in various fwupd tools.
When backported to the stable branch the verification should just be a static
function in src/fu-engine.c rather than a new symbol.
> Fix the DeviceID set by GetDetails

- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-engine.h
- src/fu-tool.c
- src/fu-util.c
The GUID is the only stable identifier, and allowing using the GUID makes it
much easier to test specific devices.
> Allow specifying the device on the command line by GUID

- plugins/thunderbolt/fu-plugin-thunderbolt.c
USB4 Controllers were showing up like this:
USB4 Controller:
Device ID:           3df660bc4bdb67fd6fc101b34c6fd8cd235e3f97
Summary:             Unmatched performance for high-speed I/O
Current version:     00.00
Update Error:        Device is in safe mode
GUID:                4d86f168-e1cc-5995-afd3-ae9df6a14f5e -> TBT-safemode
Device Flags:         Internal device
Requires AC power
cc @djcampello
> thunderbolt: Don't show safe mode errors for USB4 host controllers

- plugins/vli/fu-vli-usbhub-device.c
- plugins/vli/fu-vli-usbhub-pd-device.c
- plugins/vli/vli-usbhub-lenovo.quirk
If these devices really are shared SPI then we don't need to redirect the attach to another device and can directly handle the quirk in the usb hub device.  tl;dr: I over-thought the problem.
> vli: Use GPIOB to reset the VL817 found in two Lenovo products

- src/fu-tool.c
- src/fu-util.c
Avoid a wall of text and instead direct people to `--help` output.
Also sync up this section of code between `fu-util.c` and `fu-tool.c`
> Clarify invalid arguments display (Fixes: #2045)

- plugins/uefi/fu-plugin-uefi.c
This forces the daemon to convert the main-system-firmware instance ID to a
GUID, which allows us to find it using fu_device_list_get_by_guid()
> uefi: Manually call fu_device_setup() during coldplug

- data/daemon.conf
This was causing dozens of regressions to be reported.
> Switch the default of EnumerateAllDevices to false

- data/org.freedesktop.fwupd.metainfo.xml
This release came out after 1_3_X branched but long before 1.40 release
so these entries are confusing to be missing.
Fixes: #2059
> trivial: add missing changelog entry for 1.3.9

- plugins/cpu/fu-cpu-device.c
- plugins/cpu/fu-cpu-device.h
New enough hardware to have this feature isn't going to be in the marketplace
for a while. To use that newer hardware requires a very recent kernel (5.6 at
least, although it will probably be at least 5.9 by the time the hardware is
released).
The CET status will be used in future functionality.
> cpu: Parse the CPU flags to detect the CET status

- libfwupdplugin/fu-plugin-private.h
- libfwupdplugin/fu-plugin-vfuncs.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fwupdplugin.map
This allows per-plugin actions after the device has been open()ed and started.
> Add a vfunc that gets run after the device has been added

- plugins/acpi-facp/fu-plugin-acpi-facp.c
- plugins/linux-lockdown/fu-plugin-linux-lockdown.c
- plugins/linux-tainted/fu-plugin-linux-tainted.c
On a system that is not at all locked down running an old kernel several
of the items are a bit confusing.
```
Runtime Suffix -!
✔  fwupd plugins: OK
✔  Linux Kernel: OK
✘  Linux Kernel: Could not open file
✘  Linux Swap: Not encrypted
```
> trivial: reword the security cases for a few plugins

- plugins/dfu/dfu-device.c
- plugins/dfu/dfu-target-stm.c
- plugins/dfu/dfu-tool.c
flash stm32f7 ends with log error,  This is PR validates dfuMANIFEST state to return earlier.
```
device-write:	93%
(dfu-tool:308390): FuPluginDfu-DEBUG: 04:26:52.185: got #00aa chunk @0x8065000 of size 2048
(dfu-tool:308390): FuPluginDfu-DEBUG: 04:26:52.188: got #00ab chunk @0x8065800 of size 2048
(dfu-tool:308390): FuPluginDfu-DEBUG: 04:26:52.188: setting percentage 94% of device-verify
device-write:	94%
(dfu-tool:308390): FuPluginDfu-DEBUG: 04:26:52.191: got #00ac chunk @0x8066000 of size 2048
(dfu-tool:308390): FuPluginDfu-DEBUG: 04:26:52.194: got #00ad chunk @0x8066800 of size 2048
(dfu-tool:308390): FuPluginDfu-DEBUG: 04:26:52.194: setting percentage 95% of device-verify
device-write:	95%
(dfu-tool:308390): FuPluginDfu-DEBUG: 04:26:52.197: got #00ae chunk …
```
> check dfuMANIFEST state before validating successful write

- plugins/cpu/fu-cpu-device.c
- plugins/cpu/fu-cpu-device.h
- plugins/cpu/fu-plugin-cpu.c
This only checks that it was available from the CPU.
To be complete an additional check should be made to show that it
was actually enabled from the firmware.
This will require a kernel modification though because MSR access
will be forbidden from userland while in kernel lockdown.
> cpu: Add support for a security attribute related to Intel TME

- plugins/linux-spi-lpc/fu-plugin-linux-spi-lpc.c
- plugins/pci-bcr/fu-plugin-pci-bcr.c
Add obsoletes to attributes added by linux-spi-lpc if we're using the kernel
support for hidden PCI devices.
> pci-bcr: Fail HSI:1 if the BCR register cannot be loaded

- meson.build
On Ubuntu and Fedora try to look for existing dbx database
directories.
> trivial: if not specified try to use some better dbx defaults

- libfwupdplugin/fu-security-attrs-private.h
- libfwupdplugin/fu-security-attrs.c
- libfwupdplugin/fu-self-test.c
- src/fu-engine.c
Show the fwupd version in the HSI string so items can be cross
referenced to the spec from when they were first added
> trivial: add versioning into HSI measurement

- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
- src/org.freedesktop.fwupd.xml
The 'product name' is not typically what the hardware is known as. We need the
vendor and family if the user is going to recognise the hardware.
> Export the host vendor and family

- contrib/ci/dependencies.xml
- contrib/fwupd.spec.in
These aren't needed anymore since moving to libjcat
Note: snap still keeps them because libjcat builds in snap and
needs them.
> trivial: drop libgpgme deps

- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/dell-dock/fu-dell-dock-i2c-ec.h
- plugins/dell-dock/fu-plugin-dell-dock.c
Should be helpful in reproducing failure reports.
If no opposition, I do intend to backport this back as far as possible too in hopes it increases the content in failure reports.
> dell-dock: Capture the dock SKU in metadata

- src/fu-engine.c
I have found this confusing myself that even if plugins have the dash in
the name the daemon needs to internally use underscores.
> fu-engine: Allow --plugin-whitelist to use dashes instead of underscores

- meson.build
- plugins/uefi/efi/meson.build
Fixes cross compilation for arm with clang which provides cpuid.h
but helpfully has this error:
```
#if !(__x86_64__ || __i386__)
#error this header is for x86 only
#endif
```
Fixes: #2131
> trivial: detect `cpuid.h` and also look for host architecture

- libfwupdplugin/fu-plugin.c
- plugins/dell/fu-self-test.c
See also: https://github.com/fwupd/fwupd/issues/2119
Reported-by: Anton Farygin <rider@altlinux.org>
Based on a patch by Gleb Fotengauer-Malinovskiy <glebfm@altlinux.org>
> Skip module unloading only if we are actually running under valgrind

- src/fu-engine.c
In f430da0 we added code that was supposed to copy the verfmt from the component
to the device. We accidentally overwrote the component-provided <name> because
the device had _MD_SET_NAME set.
Use the specific function to just set the verfmt like we intended.
> Fix regression when using GetDetails on a device with _MD_SET_NAME set

- contrib/ci/dependencies.xml
- contrib/fwupd.spec.in
- meson.build
- plugins/cros-ec/README.md
- plugins/cros-ec/cros-ec.quirk
- plugins/cros-ec/data/lsusb-servo-micro.txt
- plugins/cros-ec/fu-cros-ec-common.c
- plugins/cros-ec/fu-cros-ec-common.h
- plugins/cros-ec/fu-cros-ec-usb-device.c
- plugins/cros-ec/fu-cros-ec-usb-device.h
- plugins/cros-ec/fu-plugin-cros-ec.c
- plugins/cros-ec/meson.build
- plugins/meson.build
- subprojects/gusb.wrap
- [ X] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
Initial checkin of the Chrome OS EC USB plugin. For now, this will check and provide the version number of a Servo Micro debug dongle. (https://chromium.googlesource.com/chromiumos/third_party/hdctools/+/refs/heads/master/docs/servo_micro.md).
Further changes will add support for the firmware file format and complete the mechanism of flashing the payload, as well as adding support for other USB targets.
> Initial Chrome OS EC plugin 

- src/fu-engine.c
Although this is something that we have always done on the LVFS, corporate
deployments that resign the firmware or metadata might not be signing the files
in the same way.
Always require a timestamp to prevent allowing an inadvertent rollback attack.
> Always enforce the metadata signature has a valid timestamp

- plugins/dell/fu-self-test.c
- plugins/uefi/fu-uefi-device.c
Adding an extra header makes the firmware reject the GUID in the real
header.
> trivial: uefi: fix dell TPM updates

- contrib/ci/build_windows.sh
- snap/snapcraft.yaml
Introducing newer gusb caused these builds to run gusb as a subproject
and hence the introspection binaries were looked for.
Fixes: cd65ae ("Require libgusb 0.3.3")
> trivial: fix windows and snap CI

- .github/ISSUE_TEMPLATE/bug-report-wd19.md
This is to direct people from https://github.com/fwupd/fwupd/wiki/LVFS-Triaged-Issue%3A-WD19%2A%3A-Device-ID-was-not-found/_edit
At some point I think we may remove it and collapse back to a generic report.  For now I would rather gather explicit details about the dock that aren't part of the generic report.
> trivial: add a bug report target for Dell WD19

- plugins/ccgx/ccgx.quirk
- [v] Code fix
Make "InstallDuration" include "RemoveDelay" for HP DMC Dock because HP dock actually updates firmware during device removal.
> ccgx: modify install duration for dmc device

- src/fu-main.c
This happens often enough when people switch from snap to distro
package that we should mention it in non-verbose logs.
Fixes: #2112
> fu-main: Make it clearer what lost name is and bump it to warning

- src/fu-engine.c
Ensure the historical error is set for failed NEEDS_REBOOT UEFI devices that do
not set LastAttemptStatus.
> Record the UEFI failure in more cases

- plugins/uefi/fu-uefi-device.c
In a very small ESP situation it's possible that the amount of free
space is insufficient until it's actually been cleaned.
Fixes: #2179
> uefi: check for free space after cleaning up ESP

- plugins/tpm-eventlog/fu-tpm-eventlog-parser.c
One of the core problems is that systems with both sha1 and sha256
were miscalculating.
Fixes: #2181
> tpm-eventlog: fix PCR0 calculation

- plugins/dell-dock/fu-dell-dock-i2c-ec.c
To a user it's not obvious if being unplugged means host or AC adapter.
Unplugging from AC adapter will prevent the dock from completing an
update.
> trivial: dell-dock: clarify the pending update message (#2185)

- src/fu-util.c
```
(fwupdmgr:185983): FuMain-CRITICAL **: 15:20:57.044: fu_util_time_to_str: assertion 'tmp != 0' failed
```
> trivial: fu-util: correct an assertion when no remotes configured

- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/dell-dock/fu-plugin-dell-dock.c
Unfortunately module type has more than I previously realized.  This wasn't caught because of the large number of options that can be plugged into the dock.
The meanings that previously were applied fortunately worked for
the most important case (130-180W TBT) but didn't for single C, dual
C or small power (45W) cases.
Since composite_prepare was trying to read and interpret these, it
causes failures when these other ones are encountered.
I reproduced this on a 130W adapter plugged into a single C (type 0x4).
This meant the update wouldn't install since NULL was returned for the
type.
In case a new module ID is added later, also return an "unknown" for
the metadata.
> dell-dock: Add more module types to the enum

- plugins/vli/fu-vli-usbhub-i2c-device.c
They do not need to query the device, so ->setup() is not required.
> vli: Set the i2c instance IDs in probe()

- contrib/fwupd.spec.in
- plugins/bios/fu-plugin-bios.c
- plugins/bios/meson.build
- plugins/dell-esrt/fu-plugin-dell-esrt.c
- plugins/meson.build
- plugins/uefi/fu-plugin-uefi.c
This plugin is only enabled when coreboot isn't detected.
It intentionally does not check for EFI to be disabled at startup
since it can also notify the user that UEFI capsule updates are
disabled on the system even if running in UEFI mode.
> Add a new plugin for legacy BIOS

- plugins/modem-manager/modem-manager.quirk
I don't actually know for sure this will fix it sufficiently or it's the correct vendor ID in this instance, so hopefully @wicadmin or @aleksander0m  you can double check it.
> trivial: add Vendor ID into Modem manager devices

- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/dell-dock/fu-plugin-dell-dock.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/thunderbolt/fu-thunderbolt-device.c
- plugins/thunderbolt/thunderbolt.conf
This allows delaying the activation of Thunderbolt firmware until
shutdown/reboot or when the dock is unplugged.
This functionality requires features in the kernel:
https://lore.kernel.org/linux-usb/20200622143035.25327-1-mario.limonciello@dell.com/T/#t
Matrix of cases to support:
* Distro Old Linux kernel (doesn't support authenticate on disconnect)
- WD19TB: Should have `skips-restart` flag set
No flush or activate features called in `thunderbolt` plugin.
`dell_dock` plugin will activate at end of composite update
- All other devices: Shouldn't have flags set
Should authenticate in Thunderbolt plugin.
`1 > nvm_authenticate`
* Distro New Linux kernel (supports authenticate on disconnect)
- WD19TB: Should have `usable-during-update` flag set but not `skips-restart`
Should flush image to …
> Add support for a delayed activation flow for Thunderbolt

- src/fu-history.c
This saves ~45Kb of RSS and has no measurable slowdown when reading from the
pending database.
> Disable the SQLite lookaside cache

- libfwupdplugin/fu-cabinet.c
- libfwupdplugin/fu-self-test.c
- src/fu-engine.c
Newer versions of libxmlb do not auto-cache XbNodes, and we have to opt-into
this behaviour for the _set_data() and _get_data() to work.
Although this is a behaviour change which also increases complexity, it lowers
our RSS usage by 200kB which is about a quarter of the total RSS used...
> Add XB_QUERY_FLAG_FORCE_NODE_CACHE

- plugins/modem-manager/fu-mm-device.c
Reading the sysfs file seemed to have also eaten the `\n` as mentioned
on a bug.
```
├DW5821e Snapdragon X20 LTE:
│     Device ID:           fa707b9af86ff44bc17316b6c3e5ea82aab3ce86
│     Summary:             Mobile broadband device
│     Current version:     T77W968.F1.0.0.4.2.GC.010
│     Vendor:              Dell Inc. (USB:0x413c
│     )
│     GUIDs:               64da2d58-8d1b-5e5b-b793-f88ba5a25a8f
│                          761d6124-0002-5185-b767-9adf67bf1a5e
│                          795e079d-093b-5503-aa59-35b832480e95
│     Device Flags:        • Updatable
```
> trivial: modem-manager: chomp vendor string

- plugins/thunderbolt/fu-thunderbolt-device.c
Trying to explain why ICL thunderbolt isn't updatable doesn't help
people.  It just causes fwupdmgr and fwupdtool to show the device
front and center with a confusing message.
Instead don't populate the message and by the default device filter
it will be hidden.
See #2212 for background.
> trivial: thunderbolt: don't set update error for missing nvmem

- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-device.c
We'll instead check this when the user tries to run an update.  This
allows them to sign a bootloader after the daemon starts (or remove
a signed bootloader after starting)
Fixes: #2219
> trivial: uefi: drop secure boot check at coldplug

- contrib/fwupd.spec.in
We ship 4 *tiny* python scripts that are useful for ODMs and other people
working with low level firmware blobs.
These helper utilities do not warrant dragging Python onto the CoreOS image.
> Drop the automatic /usr/bin/python3 rpmbuild dependency

- plugins/tpm-eventlog/fu-plugin-tpm-eventlog.c
- src/fu-util-common.c
After a release finishes installing, this isn't useful metadata.
Fixes: #2212
> fu-engine: only set update message from metadata on upgrades

- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-quirks.h
- src/fu-engine.c
The idea here is that we can show the user both a string and an optional
line-art image when the update has completed. The line art is often more well
understood for non-English speakers.
> Support LVFS::UpdateImage in GUI clients

- contrib/ci/fedora.sh
- contrib/debian/fwupd-tests.postinst
- contrib/debian/fwupd-tests.postrm
- contrib/debian/tests/ci
- data/bash-completion/fwupdtool.in
- data/daemon.conf
- data/installed-tests/README.md
- libfwupd/fwupd-client.c
- plugins/csr/fu-csr-device.c
- plugins/dell-esrt/fu-plugin-dell-esrt.c
- plugins/dell/fu-plugin-dell.c
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/uefi-dbx/README.md
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
- src/fu-tool.c
- src/org.freedesktop.fwupd.xml
Red Hat wants to drive an initiative in correcting problematic and potentially
divisive language in open source projects. These naming conventions and
descriptive phrases are hurtful and offensive to many of our colleagues across
the open source universe.
> Remove potentially problematic language

- plugins/uefi/fu-plugin-uefi.c
Don't even try to coldplug the device.
Fixes: #2237
> uefi: disable plugin if efivar is not supported

- plugins/ccgx/fu-ccgx-dmc-device.c
- plugins/ccgx/fu-ccgx-hpi-device.c
Remove Verify support in Lenvo and HP Dock. Those docks do not support read-firmware.
> ccgx: remove verify flag in plugin

- plugins/acpi-dmar/fu-plugin-acpi-dmar.c
If the system is missing a DMAR table, users can find out from
`fwupdtool/fwupdmgr security`.  No need to actually warn in the logs
every single time.
> trivial: acpi-dmar: lower missing DMAR table to debug

- plugins/ccgx/ccgx.quirk
Add 45% extra removal time for worst case
1. G5 Dock
Removal time = 203 sec = 140 + 140*0.45 (Actual time is 140 s)
Total install time = 233 sec = 30 (FW Writing) + 203 sec (removal time)
2. G2 Dock
Removal time  = 107 sec = 74 + 74*0.45  (Actual time is 74 s)
Total install time = 125 sec = 18 (FW Writing) + 107 sec (removal time)
> ccgx: add extra 45% removal time for worst case

- meson.build
This fixes the flathub gnome-firmware build.
> trivial: Require libjcat even when compiled with -Dbuild=library

- libfwupdplugin/fu-security-attrs.c
- libfwupdplugin/fu-security-attrs.h
- libfwupdplugin/fwupdplugin.map
- src/fu-engine.c
At the moment at startup we're calculating the attrs so we can export the HSI
string property on the D-Bus interface. Running `fwupdtool security` actually
gets all the security attributes at least twice!
> Cache the FuSecurityAttrs in the daemon

- plugins/ccgx/ccgx.quirk
Modify installation time for HP G2 Dock due to HP request.
> ccgx: modify installation time for hp g2 dock

- src/fu-util.c
If a system is configured without any downloadable remotes (e.g. with
a remote pointing to a local directory) the call of
fwupdmgr get-updates
fails by outputting "No remotes enabled." even though the call
"get-remotes" clearly shows the configured remote.
I found the following commit:
commit 991c95697e7f98585ec46c8cadfc1f7525e7f244
Author: Mario Limonciello <mario.limonciello@dell.com>
Date:   Wed Jun 17 15:23:13 2020 -0500
trivial: fu-util: correct an assertion when no remotes configured
introduced the problem. In the call chain:
fu_util_get_updates
-> fu_util_perhaps_refresh_remotes
-> fu_util_check_oldest_remote
the function fu_util_check_oldest_remote now returns FALSE if no
remote of kind FWUPD_REMOTE_KIND_DOWNLOAD is found.
The function fu_util_perhaps_refresh_remotes then returns …
> fu-util: Allow get-updates without download remotes

- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
This is required when the calling application needs the low-level soup-session
with the user agent set correctly rather than using the helper methods like
fwupd_client_download_bytes().
This is what GNOME Software needs to handle the GsApp progress completion.
> trivial: Export fwupd_client_ensure_networking()

- .github/pull_request_template.md
- plugins/synaptics-mst/fu-plugin-synaptics-mst.c
Related to https://github.com/fwupd/fwupd/issues/2278
The fwupd repository used to be located in @hughsie 's personal silo but is now located within the organization @fwupd . Currently the links to the old repository get redirected to the new repository. This pull request replaces the links to the old repo with the ones to the new repo.
> Replace github.com/hughsie with github.com/fwupd for two files

- plugins/vli/fu-vli-pd-device.c
- plugins/vli/vli-pd.quirk
- [ x ] Feature
During some testing for USB-C to HDMI adapter, we found that one copy of the VL103 PD FW was getting installed (at 0x02XXXX only instead of both 0x02XXXX and 0x03XXXX). OEM wishes for two copies of the VL103 PD FW to be installed during update. Sorry.
> vli: vl103 has backup feature

- src/fu-device-list.c
New instances of a device may be interested in custom flags. Copy them
over on fu_device_list_replace.
fixes #2298
> Save custom flags on device replace

- src/fu-engine.c
fu_engine_install_blob may result in the device being reset during attach or
detach and needing to be replugged.
The device handle we're holding may be stale, but it is still used by the do
while loop itself for the ANOTHER_WRITE_REQUIRED test.
Similar to the other functions in the loop, let's get the device handle by id
in case that happened.
Original patch by Benson Leung <bleung@chromium.org>, many thanks.
Fixes https://github.com/fwupd/fwupd/issues/2297
> Refresh the handle to device before testing ANOTHER_WRITE_REQUIRED

- contrib/ci/Dockerfile-fedora.in
- contrib/fwupd.spec.in
- contrib/generate-version-script.py
- libfwupdplugin/fwupdplugin.map
This resulted in losing g_usb_source_set_callback@LIBGUSB_0.1.0 which causes a
build failure when building gusb as a subproject.
> trivial: Don't skip methods on plain structs

- libfwupd/fwupd-client.c
- src/fu-tool.c
This adds a new kind of remote for local metadata (similar to LOCAL) and
remote firmware files (similar to DOWNLOAD). In this way the device can
control the available firmware without having to keep a local copy of
the firmware itself. This option is also useful to setup a remote mirror
with just firmware files without the complete LVFS website support.
Type of pull request: Feature
> fwupd-remote: Download remote firmware on local remote

- plugins/uefi-dbx/README.md
- plugins/uefi-dbx/fu-dbxtool.c
- plugins/uefi-dbx/fu-efi-signature-common.c
- plugins/uefi-dbx/fu-efi-signature-common.h
- plugins/uefi-dbx/fu-efi-signature.c
- plugins/uefi-dbx/fu-efi-signature.h
- plugins/uefi-dbx/fu-plugin-uefi-dbx.c
- plugins/uefi-dbx/fu-uefi-dbx-device.c
- plugins/uefi-dbx/fu-uefi-dbx-device.h
- plugins/uefi-dbx/meson.build
The GUID is built using the SHA256 of the certificates in the KEK.
> uefi-dbx: Allow updating the dbx using the LVFS

- contrib/ci/debian.sh
- contrib/ci/ubuntu.sh
- contrib/debian/rules
Cleaner fix for https://github.com/fwupd/fwupd/pull/2289
> Don't run debian packaging when subproject is active

- plugins/dfu/dfu-target.c
The nr_chunks is defined as an unsigned short, the max value is
65536. Assume the transfer_size reported by device is 4096, the
maximum size of DFU firmware supported is 65536 * 4096 = 256MB.
To support larger DFU firmware, we can change the guint16 to
guint32.
> dfu: Support download of large DFU firmware

- meson.build
systemd 246 replaced the variable names (https://github.com/systemd/systemd/commit/4908de44b0a0409f84a7cdc5641b114d6ce8ba03).
The old ones are kept for backwards compatibility but some of them interpolate new variable names so redefining them breaks.
Curiously, only systemdshutdowndir is affected by that here.
> build: fix systemd_root_prefix for systemd 246

- plugins/dfu/dfu-tool.c
- plugins/dfu/dfu.quirk
A new quirk "DfuRemovalDelay" is added. This allows us to specify
a device removal delay for re-enumeration. This is required if
it takes longer time than the default
(FU_DEVICE_REMOVE_DELAY_RE_ENUMERATE) for the device being detached
to DFU or attached to normal mode.
> dfu: Introduce a qurik to specify device removal delay

- plugins/dfu/dfu-device.c
- plugins/dfu/dfu.quirk
As described in DFU protocol (7. Manifestation Phase), after the
firmware reprogramming is done, if bitWillDetach = 1, it doesn't
require the host to issue a USB bus reset, but the device can
generate a detach-attach sequence itself to go back to normal.
Add a quirk flag "no-bus-reset-attach" to skip the bus reset in
dfu_device_attach(), and increase the "RemoveDelay" as well.
> dfu: Allow device to attach to normal without a bus reset

- plugins/nvme/fu-nvme-device.c
- plugins/vli/fu-vli-usbhub-pd-device.c
This object derives from FuDevice rather than FuVliDevice and so does not
inherit the NO_GUID_MATCHING flag like other devices.
Fixes https://github.com/fwupd/fwupd/issues/2364
> vli: Do not dedupe USB hub PD devices

- plugins/thunderbolt/fu-thunderbolt-device.c
Error will show up if (priv->physical_id == NULL) on
fu_device_ensure_id(). This method is called after probe but before
setup on fu_device_open.
Call fu_device_set_physical_id() on fu_thunderbolt_device_probe()
for the retimer case.
Fixes https://github.com/fwupd/fwupd/issues/2371
Change-Id: I0e462fff5e8abf6073318f6424b6736afc8259b8
> thunderbolt: Call fu_device_set_physical_id() during probe for retimer

- plugins/synaptics-cxaudio/synaptics-cxaudio.quirk
This ensures we perform the updates in this order:
* cxaudio
* vli
* thunderbolt
As any other order causes enumeration failures.
Fixes some of https://github.com/fwupd/fwupd/issues/2377
> synaptics-cxaudio: Fix the topology of the audio device on the TR dock

- plugins/thunderbolt/fu-thunderbolt-device.c
nvm_version will not export in SW CM, there is no point in fwupd
displaying a device for it.
> thunderbolt: ignore host controller in SW CM mode (Fixes: #2373)

- src/fu-tool.c
Without udisks2 installed the list of volumes is empty and fwupdtool
esp-list segfaults.
> Check returned volumes before accessing them

- plugins/dell-dock/fu-plugin-dell-dock.c
This makes sure that if an update is pending (as stored in the EC), Thunderbolt
won't show in a needing update state again.
Fixes: #2374
> dell-dock: mirror updatable flag into thunderbolt

- data/bash-completion/fwupdmgr.in
- data/bash-completion/fwupdtool.in
- data/fish-completion/fwupdmgr.fish
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
When one result is obsoleted by another, then do not show the old result by
default.
Additionally hide the HSI URLs as this was designed more for GUI clients like
gnome-firmware than CLI tools such as fwupdmgr.
> Do not show HSI obsoleted attributes by default

- plugins/uefi/fu-uefi-pcrs.c
069449e tried to avoid issues with all zero TPM PCR's, but caused
a problem with any byte was zero.
> uefi: correct a logic error in TPM PCR reading (Fixes: #2382)

- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- libfwupdplugin/fwupdplugin.map
This is the same format specified by Microsoft in "Identifiers for PCI Devices"
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/identifiers-for-pci-devices
> Allow plugins to match using the SUBSYS IDs

- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-firmware.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
The function fu_firmware_add_image() has the comment text 'If an image with the
same ID is present it is replaced' which has not been true for some time.
This was removed, as the common case of adding two images with no ID would only
leave one. However, some plugins do actually want to dedupe on the ID or IDX,
so provide a flag they can set which enables this functionality without
introducing regressions into other plugins.
> Add FuFirmwareFlags to allow opt-in dedupe of added images

- plugins/bios/fu-plugin-bios.c
We're telling people on PPC64 to switch to UEFI mode...
> bios: Only compile when UEFI is available

- data/org.freedesktop.fwupd.metainfo.xml
- libfwupd/fwupd-enums.h
- src/fu-util-common.c
Related to https://github.com/fwupd/fwupd/issues/2345
This fixes the wording issue discussed in https://github.com/fwupd/fwupd/issues/2345 . A system that has the flag "require_ac" does not actually run on alternating current. The device runs on direct current but just needs to be plugged into an external power source / an outlet.
> flag_require_ac documentation: System requires external power source

- libfwupdplugin/fu-firmware-image.c
- libfwupdplugin/fu-firmware-image.h
- libfwupdplugin/fwupdplugin.map
We provided the FuFirmwareImage->parse() vfunc, but did not provide any way to
actually call it...
> Add the missing fu_firmware_image_parse()

- plugins/uefi/fu-uefi-tool.c
Set the ESP when creating the device with a known GUID.
Fixes https://github.com/fwupd/fwupd/issues/2406
> uefi: Fix critical warning regression with 'fwupdate -a'

- data/bash-completion/fwupdtool.in
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-firmware.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- plugins/altos/fu-altos-device.c
- plugins/csr/fu-csr-device.c
- plugins/dfu/dfu-device.c
- plugins/optionrom/fu-optionrom-device.c
- plugins/optionrom/fu-rom.c
- plugins/optionrom/fu-rom.h
- plugins/superio/fu-superio-it89-device.c
- plugins/vli/fu-vli-pd-device.c
- plugins/vli/fu-vli-pd-parade-device.c
- plugins/vli/fu-vli-usbhub-device.c
- plugins/vli/fu-vli-usbhub-pd-device.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-tool.c
Conceptually we were trying to stuff subtly different actions into one vfunc:
* Read firmware from the device to update the verification checksums
* Read a firmware blob from the device for debugging
For the first action we might want to mask out the sections of the flash with
serial numbers (so the verification hashes match the ones published on the LVFS)
and for the second we want just a raw ROM file from the hardware with no
pre-processing that we can compare against an external SPI dumper.
Split out ->dump_firmware to get the raw blob, and allow plugins to also
implement ->read_firmware() if they have to mask out specific offsets or remove
specific images from the FuFirmware container.
In the common case when masking is not required, fall back to using a 'binary'
FuFirmware …
> Add fu_device_dump_firmware()

- data/bash-completion/fwupdmgr.in
- data/bash-completion/fwupdtool.in
- src/fu-tool.c
- src/fu-util.c
This change allows to get available updates for a given device. This is
similar to what is done for the update and activate commands.
- [ X ] Feature
> Allow to filter get-updates on device-id

- plugins/uefi-dbx/fu-uefi-dbx-common.c
Use one of the errors mapping to FWUPD_UPDATE_STATE_FAILED_TRANSIENT to avoid
uploading a failure report for something the user has to fix, i.e. update the
distro shim package.
> uefi-dbx: Do not upload a failure report for a failed dbx check

- src/fu-device-list.c
If we wait for the child of a composite device to reappear and *then* go on to
update the replugged parent in the same transaction then we still use the old
GUsbDevice as the add event is still pending when we quit the replug loop.
Just schedule an idle action to quit the loop to allow the child *and* parent
to be added on replug.
Fixes https://github.com/fwupd/fwupd/issues/2376
> Quit the replug loop on idle

- plugins/dfu/dfu-device.c
- plugins/superio/fu-superio-it89-device.c
- plugins/vli/fu-vli-pd-device.c
- src/fu-engine.c
This allows us to handle this in the plugin, which might mean detaching the
*proxy* device. It's also very important as a few plugins reboot the device
in ->attach() to get the new firmware version, which isn't required for a dump.
This partially reverts a58510b2460e780f8488e399d83252290b7f97ce and does the
detach and attach in the few plugins where actually required.
> Do not auto-detach when dumping firmware

- libfwupd/fwupd-client.c
- src/fu-tool.c
This recent regression was caused when porting libfwupd to the async model.
Fixes https://github.com/fwupd/fwupd/issues/2360
> libfwupd: Actually use the JCat file to select the metadata file

- libfwupdplugin/fu-common.c
- plugins/uefi/fu-plugin-uefi.c
When support for dynamically mounting disks was added for https://github.com/fwupd/fwupd/commit/25ba41579fb170cf3a29cb2753733172a54984cd
udisks2 became a harder dependency and it was less obvious to users.
Create devices but show an error in why devices aren't updatable if
it's not found.
Users can still configure ESP manually in `uefi.conf`
Fixes: #2444
> uefi: Make udisks2 errors more apparent

- plugins/uefi/fu-uefi-device.c
Setting the default to number causes problems when the release
is set to 'quad'.
This regression was introduced by b097603800c03f6f99e2d559f60b4891d5fa0a88 in 1_4_X and master :sob: 
I'm not sure what we should set the version requirement on the CAB as a result since 1_3_X worked right.
> trivial: uefi: when registering devices take their version format

- plugins/bcm57xx/fu-bcm57xx-device.c
- plugins/bcm57xx/fu-bcm57xx-recovery-device.c
- Use pci function 0 instead of 1 when flashing firmware.
In certain situations, the BCM5719 NVM controller can lockup if
a function other than 0 is used to read from NVM word-by-word like
the kernel driver does.
- Fix APE_MODE offset in BAR[2] to enable proper resetting of the APE.
- Remove unnededed NVRam lock when resetting the APE.
Signed-off-by: Evan Lojewski <github@meklort.com>
> bcm57xx: Improve reliability when flashing

- libfwupdplugin/fu-udev-device.c
- meson.build
- src/fu-polkit-agent.c
- <sys/poll.h> should be <poll.h>
- <sys/errno.h> should be <errno.h>
In the case of <errno.h>, no other source file has guards for including
it, so their detection was removed.
---
There are a few weird defines, such as `HAVE_IOCTL_H`, which aren't used for all source files - some have `#ifdef`s to include `<sys/ioctl.h>`, others include it unconditionally. Should this be the case? I can make a PR to make it consistent, if desired.
> Fix header names and remove check for <sys/errno.h>.

- data/fwupd.shutdown.in
EXIT_NOTHING_TO_DO needs to be caught by the shutdown script too.
Fixes: #2463
> trivial: fix shutdown error on fwupdtool activate

- contrib/fwupd.spec.in
Install tests in the rpm package only when tests are enabled.
Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
> contrib: fwupd.spec : install tests only when enabled.

- libfwupdplugin/fu-common-version.c
- libfwupdplugin/fu-self-test.c
This fixes the error: 'Update Error: device version not updated on success,
0x00000002 != 0x0002' -- it seems a bit crazy to have to specify 32 bits of
zero digits in the firmware.metainfo.xml
> Parse the HEX version before comparing for equality

- plugins/elantp/fu-elantp-hid-device.c
- plugins/elantp/fu-elantp-i2c-device.c
If somehow chk->data_sz is bigger than blksz then we would write past the end
of the allocated buffer.
> elantp: Fix three impossible to hit bugs spotted by Coverity

- src/fu-engine.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
Enable switch-branch any time a branch other than the default exists.
Based on a patch by Evan Lojewski <github@meklort.com>, many thanks.
> Set _HAS_MULTIPLE_BRANCHES when release differs from device

- src/meson.build
This fixes error introduced by 11b71f49787190a9924ad35dec33180b9d4f0081
ERROR: Unknown variable "polkit".
> trivial: Fix build error on build=standalone and polkit=true

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupdplugin/fu-plugin.c
- src/fu-engine.c
- src/fu-util-common.c
```
$ sudo mv /usr/lib/x86_64-linux-gnu/libtss2-esys.so.0.0.0 /usr/lib/x86_64-linux-gnu/libtss2-esys.so.0.0.0.renamed
$ sudo fwupdtool get-devices --plugins=uefi
14:15:48:0735 FuEngine             cannot load: failed to open plugin /usr/local/lib/x86_64-linux-gnu/fwupd-plugins-3/libfu_plugin_uefi.so: libtss2-esys.so.0: cannot open shared object file: No such file or directory
Loading…                 [-                                      ]14:15:48:0753 FuEngine             failed to update history database: device ID b6c08fb9e5384d9d101853cc1ca20cf0ce2df2e2 was not found
Loading…                 [***************************************]
WARNING: Plugin depdendencies missing
No detected devices
```
> Show an error when a plugin is missing dependencies (Fixes: #1526)

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- plugins/goodix-moc/fu-goodixmoc-device.c
- plugins/synaptics-prometheus/fu-synaprom-common.c
- plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c
The GLib g_byte_array_set_size() function does not zero the contents if the
array size is larger, which leads to unpredictable output when using valgrind.
> Add fu_byte_array_set_size()

- src/fu-engine.c
- src/fu-main.c
- src/fu-self-test.c
This can allow running daemon as a specific user and let client run as that same specific user and be considered the trusted user to communicate with the daemon.
> When compiled without PK require signed payloads for Install/Activate commands and root user for all other commands

- plugins/elantp/elantp.quirk
- plugins/elantp/fu-elantp-hid-device.c
- plugins/elantp/fu-elantp-i2c-device.c
Here's what I had in mind.  Untested:
In probe routine, check whether they are actually i2c-hid touchpad
by looking at pid.
fixes #2494
> trivial: match all elan devices in quirk

- plugins/elantp/elantp.quirk
- plugins/elantp/fu-elantp-hid-device.c
- plugins/elantp/fu-elantp-i2c-device.c
1. Modify the correct input for the iap reg (byte -> word).
2. Add new HWID for ThinkPad X1 Carbon Gen 9.
> elantp: Modify the correct input for the iap reg.

- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
- src/fu-self-test.c
Checking this requirement at daemon startup meant that trust was
evaluated before releases could actually be checked.
It's only important to check at install time.
> trivial: Split check for signed metadata when no polkit

- src/fu-device-list.c
- src/fu-self-test.c
We need to check if the device is in the remove timeout before unconditionally
replacing a device on insert.
Fixes https://github.com/fwupd/fwupd/issues/2510
> Fix regression when filtering different priorities

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
The same plugin name was being added to the device from the quirk file more than
once, and so we enumerated the device *again* and tried to add a duplicate
device -- the device list correctly refusing to do so.
Check the plugin name does not already exist before adding it, and add a self
test to catch this for the future.
> Fix probe warning for the Logitech Unifying device

- plugins/uefi/fu-uefi-device.c
This allows us to delete the previous log if debugging is now disabled.
> Enable the FWUPDATE_VERBOSE variable when deploying the update

- contrib/ci/arch.sh
Upstream tpm2-tss [is moving](https://github.com/tpm2-software/tpm2-tss/pull/1542#issue-334294643) from [ibmswtpm](http://ibmswtpm.sourceforge.net/) to [swtpm](https://github.com/stefanberger/swtpm) as the default TPM simulator. ibmswtpm still works fine and will be kept around for the foreseeable future, but adapt to the upstream decision in case ibmswtpm should ever get dropped from the official Arch Linux repositories (currently there are no plans to do so).
> contrib/ci: switch TPM simulator from ibmswtpm to swtpm

- plugins/thunderbolt/fu-thunderbolt-device.c
This means that the user performed a challenge to authorize the
device.
Fixes: #2526
> thunderbolt: recognize authorized value of '2' as well

- plugins/uefi/fu-uefi-tool.c
Before:
Information for the update status entry 0:
Information Version: 7
Firmware GUID: {ddc0ee61-e7f0-4e7d-acc5-c070a398838e}
Capsule Flags: 0x00000000x
Hardware Instance: 0
Update Status: attempted
Capsule File Path: /EFI/fedora/fw/fwupd-ddc0ee61-e7f0-4e7d-acc5-c070a398838e.cap
failed: Error opening file /sys/firmware/efi/efivars/fwupd-671d19d0-43c-
4852-98d9-1ce16f9967e4-0-0abba7dc-e516-4167-bbf5-4d9d1c739416: No such file
or directory
failed: Error opening file /sys/firmware/efi/efivars/fwupd-a9971959-9246-
4a5b-b2f2-ba6fdcb19349-0-0abba7dc-e516-4167-bbf5-4d9d1c739416: No such file
or directory
After:
Information for the update status entry 0:
Information Version: 7
Firmware GUID: {ddc0ee61-e7f0-4e7d-acc5-c070a398838e}
Capsule Flags: 0x00000000x
Hardware Instance: 0
Update Status: …
> Show a less scary fwupdate output for devices without info

- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-device.c
The FuDevice derives from FwupdDevice, and yet both objects have a (potentially
different) parent and set of children. This is super confusing, and just not
required.
Removing the duplication also removes a sizable memory leak when hotplugging
composite devices as the parent was ref'd by the child and the child was ref'd
by the parent in different objects... Fun to debug...
> Remove the duplicate parent-child data in FwupdDevice and FuDevice

- data/fish-completion/fwupdmgr.fish
Just updated the fish completions to conform with v1.5.0.
By the way, I noticed in the `--help` output:
```
unblock-firmware [CHECKSUM]       Blocks a specific firmware from being installed
```
This is a copy and waste error, isn't it? Probably should be `Unblocks a...`
> Updated fish completions to 1.5.0

- contrib/ci/dependencies.xml
- meson.build
- snap/snapcraft.yaml
- src/fu-main.c
- src/meson.build
This makes sure that the main process won't get SIGTERM on shutdown.
Inspired from a patch by Jonathan Kang <jonathankang@gnome.org>
> Notify the service manager when idle-quitting

- docs/hsi.xml
- libfwupdplugin/fu-security-attrs.c
- libfwupdplugin/fu-self-test.c
- src/fu-engine.c
- src/fu-util-common.c
The logic here is that the attestation is more than just the PCR0 value, and
multiple device firmware (such as EC, ME, etc.) needs to be included to validate
the system.
By the same logic, updates for the system firmware do not tell the whole story,
and confuse HSI as a specification. Remove them.
> Remove HSI update and attestation suffixes

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/uefi/fu-uefi-device.c
- src/fu-engine.c
- src/fu-util-common.c
In this case, we want to set the generic ESRT entry to have the icon 'battery'.
> Allow components to set the icon from the metadata

- data/installed-tests/fwupdmgr.sh
Most of the installed tests will skip if files needed to be fetched
from network are not available.  Do the same thing for fwupdmgr
tests.
Fixes: #2566
> trivial: installed-tests: skip tests requiring network by default

- plugins/synaptics-mst/fu-synaptics-mst-device.c
On failure, you get this:
no device found on drm_dp_aux5: Memory query failed: failed to write command
failed to get device after update: failed to wait for detach replug
> synaptics-mst: Improve reliability by waiting 2 seconds after writing data

- plugins/uefi/fu-plugin-uefi.c
- plugins/uefi/fu-uefi-bootmgr.c
- plugins/uefi/fu-uefi-bootmgr.h
- plugins/uefi/fu-uefi-common.c
- plugins/uefi/fu-uefi-common.h
- plugins/uefi/fu-uefi-device.c
- plugins/uefi/uefi.conf
Per discussion of #2513, Ubuntu Core was going to use UEFI removable
path as default esp path, and it needs to change some parts around
getting the esp path and searching the shim app path. Also, a new option
"FallbacktoRemovablePath" is added into uefi.conf to be applied in this
case, and it will be false by default.
> uefi: a new option for uefi configuration to use UEFI removable path

- contrib/PKGBUILD
- contrib/debian/rules
- contrib/fwupd.spec.in
- meson.build
- meson_options.txt
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
Anyone can easily add this, but it makes it clearer that by default hand
build, snap, and flatpak are not checked by anyone.
> Add a flag to indicate if packages are supported

- plugins/bcm57xx/fu-bcm57xx-device.c
- src/fu-engine.c
We still want to return TRUE, rather than falling through as if the requirement
type was unknown.
Fixes https://github.com/fwupd/fwupd/issues/2578
> trivial: Fix a logic thinko to unbreak switch-branch

- plugins/vli/vli-usbhub-lenovo.quirk
I'm not sure whomst is responsible for making the fix; but an ODM noticed that TR_Gen2 was missing the realtex flag in the quirk files and requested help.
> trivial: tr_gen2 has same rtd21xx as mini dock

- plugins/uefi/fu-plugin-uefi.c
Comment from https://github.com/fwupd/fwupd/issues/2553#issuecomment-728218741
makes it clear that test suite should ignore some of environment.
> trivial: uefi: don't let user's environment fail UEFI/Dell test suite

- libfwupd/fwupd-client-sync.c
- libfwupd/fwupd-client-sync.h
- libfwupd/fwupd.map
I'm porting gnome-software to use this new API and this would be a very useful
thing to provide. No async API as we want to avoid writing temp files in most
cases -- this is just for legacy apps.
> libfwupd: Add fwupd_client_download_file()

- data/tests/firmware-base-uri.conf
- data/tests/firmware-nopath.conf
- libfwupd/fwupd-remote.c
The snap-store intends to ship an updated libfwupd library but
to use it with whatever version daemon is on the host system.
This means that the library needs to still work with older metadata
signing types.
This fixes the following error in that scenario:
```Failed to update metadata for lvfs: Keyring kind jcat not supported```
CC @kenvandine
> libfwupd: Restore recognizing gpg and pkcs7 types still

- libfwupdplugin/fu-cabinet.c
- src/fu-engine.c
- src/fu-main.c
This would allow us to add other component types in the future, for instance a
'generic' type that adds information to the composite device.
Any generic components would need to have a requirement of 1.5.2 to avoid
showing a runtime warning when trying to get the local file details.
> Restrict loading component types of firmware

- src/fu-main.c
`fu_main_daemon_method_call` stores a pointer to a `guint64` in the `priv->sender_features` hashtable.  However, wherever this pointer is extracted from the hashtable, it is casted to a `FwupdFeatureFlags*` and dereferenced.  Since `guint64` does not have the same size as `FwupdFeatureFlags`, this is undefined behaviour.  On a big endian system, the typical result will be that the higher order bits of the `guint64` are accessed, giving a `0` result.
> fu-main: Fix sender_features insert with wrong size

- src/fu-engine.c
- src/fu-remote-list.c
This restores compatibility when running with a new daemon and old remote files
and properly fixes all combinations of the regression casued by the commit
2f49da7f4e9ed300c91956531e3dbdb4da628da5 which appeared in the 1.5.2 release.
> Allow the client to send PKCS7 and GPG signatures

- src/fu-engine.c
Should hopefully fix this failure:
```
Plugin thunderbolt
UpdateError device version not updated on success, 43.00 != 40.00
VersionNew 43.00
VersionOld 40.00
```
> trivial: fu-engine: If a device is using delayed activation don't flag failure

- plugins/bcm57xx/fu-bcm57xx-common.c
- plugins/bcm57xx/fu-bcm57xx-dict-image.c
- plugins/bcm57xx/fu-bcm57xx-firmware.c
- plugins/bcm57xx/fu-bcm57xx-stage1-image.c
- plugins/bcm57xx/fu-bcm57xx-stage2-image.c
The function `fu_bcm57xx_nvram_crc` calls `GUINT32_FROM_BE` on a locally computed number, which makes absolutely no sense.  AFAICT this is an attempt to wall-paper over the fact that the call to `fu_common_read_uint32_safe` incorrectly uses `G_BIG_ENDIAN` instead of `G_LITTLE_ENDIAN` to read the (little endian) CRC value from the fw image.
This "worked" on little-endian, since `GUINT32_FROM_BE` would swap the CRC backwards, so that it compared equal to the CRC fetched from the image, which was also backwards.  But on big-endian `GUINT32_FROM_BE` naturally does nothing and so the comparison fails.
> bcm57xx: Fix CRC check

- contrib/ci/build_windows.sh
- contrib/ci/ubuntu.sh
- contrib/fwupd.spec.in
- meson_options.txt
- plugins/meson.build
- snap/hooks/install
Fixes: #2634
When it's upstream, we may consider to change this for some distros.
> trivial: make platform integrity plugin optional and disabled by default

- contrib/ci/arch.sh
Update cache (which also requires to update the system) to avoid cache issues like the one seen in https://github.com/fwupd/fwupd/pull/2633
@superm1 In answer to https://github.com/fwupd/fwupd/pull/2633#issuecomment-737500794, the cache was only updated during Docker build (`-y` subaction). So since you splitted that to be daily, the cache would not be refreshed. I’m not sure against which kind of distro breakage you want to protect, but refreshing the cache and installing new packages requires to upgrade installed packages (`-u` subaction, to avoid e.g. ABI breakage), so it’s not very different from re-generating the Docker image (just a bit faster).
> contrib/ci: Fix Arch cache issues

- libfwupd/fwupd-client-sync.c
- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
Use the 'default' main context by default so that we still get the signals
delivered via g_object_notify() but allow the library user to specify an
alternate GMainContext as required.
Using g_main_context_push_thread_default() works for PackageKit as signals are
returned using g_signal_emit() which is synchronous, and so doesn't use the
main context at all.
Use the same style of API which we did for libgusb all those years ago instead.
> Allow setting the GMainContext when used for sync methods

- plugins/ata/ata.quirk
I'm finally getting around to figuring out why I get occasional hard hangs after changing from a spindle to SSD.  I've disabled fwupd in the meantime to see if it makes a difference.  Adding the info since I don't see it already on the list per instructions.
> added my ssd giving the error

- libfwupd/fwupd-client.c
There is a small typo in libfwupd/fwupd-client.c.
Should read `runtime` rather than `rumtime`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, rumtime -> runtime

- contrib/fwupd.spec.in
- libfwupd/fwupd-client.c
- libfwupd/fwupd-remote.c
- meson.build
- plugins/redfish/fu-redfish-client.c
- src/fu-util-common.c
Some vendors really really want 1.5.x in newer RHEL versions, but the version
of curl is too old. Add #ifdefs so that we can emulate (somewhat imperfectly)
the 'new' CURLU functonality.
> Lower the CURL version required to fix build in RHEL

- contrib/ci/arch.sh
- contrib/ci/qt5-thread-test/meson.build
- contrib/ci/qt5-thread-test/qt-thread-test.cpp
This only runs on Arch to avoid giving the extra dependencies to all
the distro CI builds.
> Add a CI tester for running libfwupd with QT threads

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-dfu-firmware.c
- libfwupdplugin/fu-firmware-image.c
- libfwupdplugin/fu-fmap-firmware.c
- libfwupdplugin/fwupdplugin.map
- plugins/bcm57xx/fu-bcm57xx-dict-image.c
- plugins/bcm57xx/fu-bcm57xx-firmware.c
- plugins/bcm57xx/fu-bcm57xx-stage1-image.c
- plugins/bcm57xx/fu-bcm57xx-stage2-image.c
- plugins/cros-ec/fu-cros-ec-usb-device.c
- plugins/dfu/dfu-target-stm.c
- plugins/dfu/dfu-target.c
- plugins/ebitdo/fu-ebitdo-firmware.c
- plugins/thunderbolt/fu-thunderbolt-device.c
- plugins/uefi/fu-uefi-device.c
This is a safer version of g_bytes_new_from_bytes() which returns a GError
if the offsets are invalid rather than emitting a critical warning.
This prevents a critical warning and potential crash when parsing invalid
bcm57xx firmware.
> trivial: Add fu_common_bytes_new_offset()
