fwupd/fwupd

README.md

In particular, say that keys should always be on HSMs.
Signed-off-by: Peter Jones <pjones@redhat.com>

Make statements about storing private keys stronger.

---

data/Makefile.am

data/fwupd-offiline-update.service is not in AC_CONFIG_FILES so make sure to substitute bindir

Fix fwupd-offline-update.service

---

src/fu-main.c

Show a different error when checking for updates while on battery power

---

configure.ac
plugins/Makefile.am
plugins/synapticsmst/Makefile.am
plugins/synapticsmst/README.md
plugins/synapticsmst/fu-dell-flash.h
plugins/synapticsmst/fu-plugin-dell.h
plugins/synapticsmst/fu-plugin-synapticsmst.c
plugins/synapticsmst/synapticsmst-common.c
plugins/synapticsmst/synapticsmst-common.h
plugins/synapticsmst/synapticsmst-device.c
plugins/synapticsmst/synapticsmst-device.h
plugins/synapticsmst/synapticsmst-tool.c
po/POTFILES.in

This plugin introduces support for the Synaptics MST hubs used in Dell systems and docks.
It requires kernel 4.6 or later.
It's been developed in collaboration between Dell and Synaptics.
Once this pull request looks good, I'll squash it down to a few commits.

Merge Synaptics MST plugin

---

meson.build
plugins/dell/meson.build

Add fwup dependency in enable-dell and shared_module('fu_plugin_uefi')

enable-dell requires libfwup-dev

---

po/LINGUAS

Basque, Indonesian, and Kazakh are missing.

trivial: Update LINGUAS

---

README.md

README: Add more links to the README

---

README.md

README: Fix links syntax

---

contrib/ci/Dockerfile-debian-experimental
contrib/ci/Dockerfile-debian-unstable
contrib/ci/Dockerfile-fedora-25
contrib/fwupd.spec.in
meson.build
po/make-images
po/make-images.sh
po/meson.build

This generates a pile of .bmp files to use as our status messages.
Signed-off-by: Peter Jones <pjones@redhat.com>

Generate a pile of images for status messages during system firmware update.

---

po/ca.po
po/hr.po
po/make-images
po/make-images.sh
po/zh_CN.po

Maybe there's a better way to do this; I don't know.
Signed-off-by: Peter Jones <pjones@redhat.com>

Actually make sure our firmware status string will get translated.

---

po/POTFILES.in

I don’t know if anything else is needed to get it translated.

Add the AppStream metainfo file to POTFILES.in

---

plugins/amt/fu-plugin-amt.c
plugins/unifying/lu-device-peripheral.c

Some constness fixes to get Jenkins builds working

---

plugins/amt/fu-plugin-amt.c

Follow up and partial reversion of PR #174. :-(

Another attempt at fixing the UUID_LE compilation problem

---

.travis.yml
contrib/ci/Dockerfile-debian
contrib/ci/build_and_install_debs.sh
contrib/ci/build_and_install_pkgs.sh
contrib/ci/build_and_install_rpms.sh
contrib/ci/build_and_test.sh

When looking into the fwupd Debian package, I found some low-hanging fruits for improvements to the CI used in fwupd.

Some minor CI improvements

---

plugins/thunderbolt/fu-self-test.c

Test for pr #198; I verified locally that it detects the error.
I am planning on using the new `mock_tree_sync` also 
for `mock_tree_settle`, but will do that separately.

thunderbolt: test we handle change events properly

---

contrib/ci/build_and_install_rpms.sh
contrib/ci/build_and_test.sh
contrib/fwupd.spec.in

Signed-off-by: Yehezkel Bernat <yehezkel.bernat@intel.com>

Enable Thunderbolt plugin in CI and RPM packaging

---

plugins/thunderbolt/fu-thunderbolt-image.c

Completing what discussed in https://github.com/hughsie/fwupd/pull/214
Signed-off-by: Yehezkel Bernat <yehezkel.bernat@intel.com>

thunderbolt: add description to all FwLocation objects

---

contrib/PKGBUILD
contrib/ci/build_and_install_debs.sh
contrib/ci/build_and_install_rpms.sh
contrib/debian/rules
meson.build
meson_options.txt

Do NOT do this for normal package builds.

Use -Werror when building in Travis CI

---

plugins/unifying/fu-plugin-unifying.c

Fixes: https://github.com/hughsie/fwupd/issues/235

unifying: Disable if the kernel has no CONFIG_HIDRAW support

---

data/remotes.d/README.md
data/remotes.d/fwupd.conf
data/remotes.d/lvfs-testing.conf
data/remotes.d/lvfs.conf
data/remotes.d/vendor.conf
libfwupd/fwupd-remote.c
libfwupd/fwupd-remote.h
libfwupd/fwupd-self-test.c
src/fu-util.c

This allows us to show something useful in a GUI.

Add a human-readable title for each remote

---

libfwupd/fwupd-enums.c
libfwupd/fwupd-enums.h
src/fu-main.c
src/fu-progressbar.c

Using IDLE for this isn't right as we're basically blocked on the user.

Add a waiting-for-auth daemon state

---

plugins/ebitdo/fu-device-ebitdo.c

fix mispelled redesign

---

.github/ISSUE_TEMPLATE.md

Fixes: https://github.com/hughsie/fwupd/issues/300

Add note to GitHub issue template

---

data/builder/meson.build
data/installed-tests/meson.build
data/meson.build
data/pki/meson.build
data/remotes.d/meson.build
meson.build
plugins/dell/meson.build
plugins/dfu/meson.build
policy/meson.build
src/meson.build

As requested in https://github.com/hughsie/colord/pull/62, this patch unifies the directory selection inside the top-level meson file

build: Refactor directory selection

---

docs/libfwupd/libfwupd-docs.xml
plugins/altos/fu-altos-device.c
plugins/altos/fu-altos-device.h
plugins/altos/fu-plugin-altos.c
plugins/colorhug/fu-colorhug-device.c
plugins/colorhug/fu-colorhug-device.h
plugins/colorhug/fu-plugin-colorhug.c
plugins/ebitdo/fu-ebitdo-device.c
plugins/ebitdo/fu-ebitdo-device.h
plugins/ebitdo/fu-ebitdo-tool.c
plugins/ebitdo/fu-plugin-ebitdo.c
plugins/nitrokey/fu-nitrokey-device.c
plugins/nitrokey/fu-plugin-nitrokey.c
plugins/steelseries/fu-plugin-steelseries.c
plugins/usb/fu-plugin-usb.c
src/fu-device-locker.c
src/fu-plugin.h
src/fu-usb-device.c
src/fu-usb-device.h
src/meson.build

This allows us to move a lot of duplicated functionality out of each plugin.

Add FuUsbDevice helper object

---

src/fu-engine.c

`Not compatible with fwupd version 1.0.2, requires >= 1.0.3`
...is easier to understand than...
`Value of org.freedesktop.fwupd incorrect: failed predicate [1.0.3 ge 1.0.2]`

Show a nicer error message if the requirement fails

---

plugins/dfu/dfu-target-avr.c
plugins/dfu/fu-plugin-dfu.c
plugins/nitrokey/fu-nitrokey-device.c
plugins/udev/fu-plugin-udev.c
src/fu-self-test.c

Various compiler warning fixes including a crasher fix

---

contrib/PKGBUILD
contrib/ci/build_and_install_pkgs.sh
contrib/ci/build_and_install_rpms.sh
contrib/ci/build_debian_s390x.sh
contrib/debian/rules
contrib/fwupd.spec.in
meson.build
plugins/synapticsmst/meson.build

It seems to have been broken and not being applied to CI builds.
While fixing it, also turn it on for clang.

Fix -werror

---

contrib/ci/build_and_install_rpms.sh

Plan is to remove "old" name at some point (1.0?).

ci: mesonintrospect -> meson introspect

---

plugins/dell/fu-plugin-dell.c
plugins/dell/fu-self-test.c

I confirmed with TPM team that this should have been blocking owned TPM upgrade too.  Sorry about that, I'll backport this to stable branches too.

dell: block owned TPM updates (#339)

---

src/fu-engine.c

In the case of multiple <component> sections with different AppStream IDs, but
with the same GUID <provides>, filter using the requirements rather than just
choosing the first one.
This allows the update of Logitech devices with secure bootloaders. Many thanks
to Ogier Bouvier for identifying the problem.

Choose the correct component from provides matches using requirements

---

data/daemon.conf
src/fu-common-cab.c
src/fu-common-cab.h
src/fu-config.c
src/fu-config.h
src/fu-engine.c
src/fu-engine.h
src/fu-main.c
src/fu-self-test.c

We don't want to allow DoS-ing the daemon by trying to decompress a huge sparse
cabinet archive.

Do not try to parse huge compressed archive files

---

plugins/ebitdo/data/sf30pro.txt
plugins/ebitdo/ebitdo.quirk
plugins/ebitdo/fu-ebitdo-device.c
plugins/ebitdo/fu-ebitdo-tool.c

More details about the remaining challenges remain in the commit message.

Add SF30/SN30 pro support

---

src/fu-engine.c

The SUPPORTED flag is used when a device appears in the AppStream metadata of
any enabled remote, so when we rescan the modified store also ensure the flag
state is still correct.
Fixes https://github.com/hughsie/fwupd/issues/363

Rescan supported flags when refreshing metadata

---

plugins/synapticsmst/fu-plugin-synapticsmst.c

See https://github.com/hughsie/fwupd/issues/385 for the details

Fix Synaptics MST breakage on 1.0.2 and later

---

src/fu-common-cab.c

I assume they're trying to avoid compressing the firmware, but compressing the
metadata. Not insane, but slightly odd given the metadata is typically tiny.
Fixes: https://github.com/hughsie/fwupd/issues/392

Support split cabinet archives as produced by Windows Update

---

src/fu-util.c
src/meson.build

Resolves half of https://github.com/hughsie/lvfs-website/issues/43

Show the user a URL when they report a known problem

---

plugins/thunderbolt/fu-plugin-thunderbolt.c

Fixes: https://github.com/hughsie/fwupd/issues/387

thunderbolt: Enforce the thunderbolt version is xx.yy

---

plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c

It seems 2s is not long enough on some hardware. We also get a much better
error message if the device fails to come back online.

Use a longer timeout when powering back the Thunderbolt device

---

plugins/unifying/lu-device-bootloader-nordic.c
plugins/unifying/lu-device-bootloader-texas.c
plugins/unifying/lu-device-bootloader.c
plugins/unifying/lu-device.h

Your mail reminded me this has been hanging on my hard drive since December.
This implementes updating signed logitech unifying receivers, both for RQR12 and RQR24
Signed-off-by: Ogier Bouvier <obouvier@logitech.com>

Support for updating signed Logitech unifying receivers

---

libfwupd/fwupd-client.c
libfwupd/fwupd-self-test.c

Fixes https://github.com/hughsie/fwupd/issues/409

Fix running the self tests when no fwupd is installed

---

contrib/firmware-packager/firmware-packager
plugins/thunderbolt/fu-thunderbolt-image.c

Add verification of TitanRidge Thunderbolt Controllers. Support building cab image from binary.

Thunderbolt: Add support for TitanRidge Thunderbolt controllers

---

plugins/uefi/fu-plugin-uefi.c

RFC for now, this is untested.
This approach I did will block the update when it's applied.  The other approach is to do it at initialization and remove `FWUPD_DEVICE_FLAG_UPDATABLE` if it's not mounted.
The downside of that approach is that you won't know why it's not updatable other than looking at fwupd journal.

uefi: Check that EFI system partition is mounted

---

plugins/thunderbolt-power/fu-plugin-thunderbolt-power.c

This leads to problems if it happens at the wrong time

thunderbolt-power: don't recoldplug (#457)

---

contrib/ci/Dockerfile-fedora.in
contrib/ci/centos.sh
meson.build
plugins/dfu/dfu-firmware.c
plugins/dfu/dfu-tool.c
plugins/uefi/fu-plugin-uefi.c
policy/meson.build
src/fu-engine.c
src/fu-self-test.c
src/fu-usb-device.c

It's been a while since these versions have been updated.  With Ubuntu's new LTS out, and Fedora releases with modern software dependencies, I think it's time to drop a lot of legacy code.

Update requirements to modern verions

---

src/fu-engine.c

We don't want to use the version= attribute as the HWIDs are not versions, and
thinkgs like globbing just doesn't make sense given they are from hashes.
Fixes the client side part of https://github.com/hughsie/lvfs-website/issues/110

Allow specifying hwids with OR relationships

---

src/fu-engine.c
src/fu-plugin-private.h
src/fu-plugin.c

Fixes https://github.com/hughsie/fwupd/issues/503

Do not call fu_plugin_init() on blacklisted plugins

---

contrib/fwupd.spec.in
data/bash-completion/fwupdmgr
data/bash-completion/fwupdtool
data/bash-completion/meson.build
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

Also amend the behavior of get-devices to match fwupdmgr

Bring get-topology to fwupdtool

---

src/fu-config.c

I don't see a reason it needs to be compulsory to have the daemon.conf in place, fwupd and fwupdtool are both setup to adopt sane defaults without it there.

trivial: Don't fail to start the daemon or fwupdtool if fwupd.conf is missing

---

contrib/fwupd.spec.in
plugins/meson.build
plugins/wacomhid/README.md
plugins/wacomhid/fu-plugin-wacomhid.c
plugins/wacomhid/fu-self-test.c
plugins/wacomhid/fu-wac-common.c
plugins/wacomhid/fu-wac-common.h
plugins/wacomhid/fu-wac-device.c
plugins/wacomhid/fu-wac-device.h
plugins/wacomhid/fu-wac-firmware.c
plugins/wacomhid/fu-wac-firmware.h
plugins/wacomhid/fu-wac-module-bluetooth.c
plugins/wacomhid/fu-wac-module-bluetooth.h
plugins/wacomhid/fu-wac-module-touch.c
plugins/wacomhid/fu-wac-module-touch.h
plugins/wacomhid/fu-wac-module.c
plugins/wacomhid/fu-wac-module.h
plugins/wacomhid/meson.build
plugins/wacomhid/wac-intuos.quirk

This is still WIP. The touch module firmware update hasn't been tested yet, but the other firmware types work fine. I figured I'd get this in for some early review as it's quite a chunk of code.

Add an experimental plugin to update some new Wacom tablets

---

plugins/redfish/fu-redfish-client.c

In the Members array of FirmwareInventory or SoftwareInventory, each
element of the array only contains the URI to the member. For example:
"Members":
[
{
"@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/1/"
},
{
"@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/2/"
},
{
"@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/3/"
}
]
We have to get the real member object through the given URI.

redfish: Fetch the inventory member correctly

---

plugins/thunderbolt/fu-plugin-thunderbolt.c
plugins/thunderbolt/fu-self-test.c
plugins/thunderbolt/fu-thunderbolt-image.c

This pull request contains fixes for review comments after the Titan Ridge support patch series was merged.
There is one additional commit that makes the Thunderbolt plugin to parse nvm_version everywhere in the same way.

Thunderbolt fixes

---

src/fu-common.c
src/fu-self-test.c

1) Skip firmware builder functions if missing CONFIG_USER_NS
2) Skip if detecting a patched kernel that has namespaces turned off
3) Don't fail if the error is -EPERM
Fixes FTBFS on Debian pbuilder and unprivileged docker.

src/fu-self-test: Make builder tests more resilient

---

src/fu-progressbar.c

For many devices this won't matter, but for some devices I've experienced flash times that are nominally 5 minutes.  I also have one device that takes over 40 minutes to flash (although I hope that we can optimize that better...)

fu-progressbar: Show a time estimate after update has started

---

src/fu-install-task.c

…PG/PKCS7
Currently if you download a CAB file from LVFS and try to install it
on a daemon compiled without GPG it will fail to install since LVFS has signed
it.  You had to make an intentional decision to disable GPG.
Allow this scenario to work just as if the CAB file were unsigned, but save
a warning in the logs that it happened.

fu-install-task: Don't fail update installation if compiled without GPG

---

plugins/synapticsmst/fu-plugin-synapticsmst.c
plugins/synapticsmst/synapticsmst-device.c
plugins/synapticsmst/synapticsmst-device.h
plugins/synapticsmst/synapticsmst.quirk

This should allow trivially adding support for new
Tesla/Leaf/Panamera devices by a quirk.

synapticsmst: Move GUID generation into quirks

---

src/fu-device.c

Probe does not require the device to be open and can be used automatically.

trivial: Run FuDevice:probe() when adding children

---

plugins/uefi/fu-plugin-uefi.c
plugins/uefi/fu-uefi-common.c
plugins/uefi/fu-uefi-common.h
plugins/uefi/fu-uefi-tool.c
plugins/uefi/uefi.conf

Fixes https://github.com/hughsie/fwupd/issues/670

uefi: Check the amount of free space on the ESP

---

plugins/thunderbolt/fu-plugin-thunderbolt.c

It should only be used for the one (optionally) non-critical failure
in valiation failing.

trivial: thunderbolt: don't reuse GError error_local in update function

---

contrib/ci/Dockerfile-ubuntu.in
contrib/ci/dependencies.xml
contrib/ci/ubuntu.sh
plugins/amt/fu-plugin-amt.c
plugins/dell/fu-self-test.c
plugins/uefi/fu-uefi-device.c
plugins/wacomhid/fu-wac-device.c
plugins/wacomhid/fu-wac-firmware.c

I'd ideally like to have clang's static analyzer run automatically, so I think the increase in CI time might be worth it.

static analysis changes

---

plugins/dfu/dfu-tool.c

Marked some CL options for translation

---

plugins/synapticsmst/synapticsmst-common.c
plugins/synapticsmst/synapticsmst-device.c

I received a private report on ESM update failures occurring on Panamera with master.  I believe it's a logic error in the update path for ESM.
Make some adjustments to more closely mirror the regular update path.
I have successfully upgraded/downgraded about 5 times with this change in place, so I do believe it's safe.
cc @ryanchang0624 for any comments

Fix reported failure on ESM update

---

src/fu-engine.c
src/fu-self-test.c

At the moment firmware can declare that it has certain requirements, for
instance the existing firmware version, the bootloader version, or the
vendor ID of the device.
In some situations we actually want to check the firmware version of a
*different* device. Good examples here would be only allowing an EC upgrade if
a specific BIOS update has already been done, or only allowing a wireless
reciever to be updated if the attached wireless devices have been updated first.
To use this, you can do something like:
<requires>
<id compare="ge" version="1.1.3">org.freedesktop.fwupd</id>
<firmware compare="ge" version="0.9.0">guid-of-other-device</firmware>
</requires>

Allow firmware files to depend on versions from other devices

---

README.md

As discussed in https://github.com/hughsie/lvfs-website/pull/172, I have added KDE Discover in Other frontends section of Readme.md. I enumerated it with previous entries, please let me know for any changes required.

Readme Updated: Added KDE Discover as one more graphical front-end available for fwupd.

---

src/fu-main.c
src/fu-tool.c

This helps to prevent conflicts of the daemon trying to claim devices
at the same time as the tool.

fu-tool: Stop any running daemon over dbus before loading engine

---

src/fu-util.c

Apparently, most application support both the lower and upper case versions...
Fixes https://github.com/hughsie/fwupd/issues/815

Use HTTPS_PROXY if set

---

src/fu-engine.c

I'd like to also bring this back to 1_1_X, so in addition to regular review, would appreciate any thoughts around that.

Return parent devices first in requests to GetDevices

---

plugins/dell-dock/fu-dell-dock-i2c-mst.c

Since `dell_dock` is the priority plugin for MST flashing the VMM5331
no need to do delayed callbacks anymore.
When the `dell_dock` plugin bumps to EC 15 being the minimum requirement
even more code can also be dropped.

dell-dock: Drop delayed MST callback routine

---

plugins/dell-dock/README.md
plugins/dfu/README.md
plugins/nvme/README.md
plugins/rts54hid/README.md
src/README.md
src/fu-quirks.h

It's a bit of manual work transcribing these over, so before doing it all what do you think of this approach?

trivial: Add quirk documentation

---

contrib/simple_client.py

The client uses GObject introspection to use the libfwupd2 library.
The client offers a reduced set of commands, but may be useful in some
environments.

contrib: Add a simple python3 client

---

contrib/fwupd.spec.in
plugins/fastboot/README.md
plugins/fastboot/data/android/flashfile.xml
plugins/fastboot/data/lsusb.txt
plugins/fastboot/data/qfil/partition_nand.xml
plugins/fastboot/fastboot.quirk
plugins/fastboot/fu-fastboot-device.c
plugins/fastboot/fu-fastboot-device.h
plugins/fastboot/fu-plugin-fastboot.c
plugins/fastboot/meson.build
plugins/meson.build

Very much WIP, and almost completely untested.

Add a plugin to update hardware that supports fastboot

---

README.md

Not sure this makes sense front and center.

trivial: Add a snap badge for fwupd

---

src/fu-engine.c

Only run attach and detach if the device is in the wrong mode

---

src/fu-history.c

I forgot to include the protocol column when migrating to v3, so create a v4
which ignores the sqlite error if the column already exists.
Fixes https://github.com/hughsie/fwupd/issues/909

Correctly migrate the history database

---

data/bash-completion/fwupdtool.in
data/remotes.d/README.md
src/fu-engine.c
src/fu-engine.h
src/fu-tool.c

This is intended to be used with local repositories/metadata sources that are already configured.
This was tested using the changes here: https://github.com/hughsie/lvfs-website/pull/233

Add support for "update" command to fwupdtool

---

plugins/modem-manager/fu-plugin-modem-manager.c

ModemManager is a service that has its own lifecycle, usually managed
e.g. as a systemd service. So, instead of assuming that MM will be
available when fwupd boots (DBus auto-start won't work), we can create
the MMManager object and follow name-owner updates.
We'll setup object added/remove signals Only when the MMManager has a
valid name-owner path and when the reported runtime version is greater
or equal than the minimum supported one.

modem-manager: follow MM service

---

plugins/thunderbolt/fu-plugin-thunderbolt.c

This situation may happen in the future in systems where the TBT NVM is embedded
in a different location and only upgradable through system firmware.

trivial: thunderbolt: If unable to find inactive nvmem, don't mark updatable

---

plugins/uefi/efi/fwupdate.c

This simplifies memory management. Added here for comment; there's a lot of cleanups we could do in fwupdate.c and this seems like a good start.

Use GCC __cleanup__ features in the EFI loader

---

plugins/README.md

trivial: Clarify our position on proprietary plugins

---

src/fu-common-cab.c

This means the correct hash is shown when using `fwupdtool get-details` and
will be useful for future functionality."

Ensure cabinet archives always have a container checksum

---

contrib/PKGBUILD
contrib/ci/Dockerfile-fedora.in
contrib/ci/Dockerfile-flatpak.in
contrib/ci/dependencies.xml
contrib/ci/fedora.sh

We'll need this for some updated ModemManager deps soon.

trivial: Move Fedora CI to f29

---

plugins/fastboot/fu-fastboot-device.c

This performs the partition flashing operation, which was missing after the file download.

fastboot: flash the partition after downloading the file

---

plugins/dell/fu-plugin-dell.c

Fix some errors shown by dell plugin in corner case scenarios

---

plugins/dell-dock/README.md
plugins/dell-dock/dell-dock.quirk
plugins/dell-dock/fu-dell-dock-common.c
plugins/dell-dock/fu-dell-dock-common.h
plugins/dell-dock/fu-dell-dock-i2c-ec.c
plugins/dell-dock/fu-dell-dock-i2c-mst.c
plugins/dell-dock/fu-dell-dock-i2c-tbt.c
plugins/dell-dock/fu-dell-dock-status.c
plugins/dell-dock/fu-plugin-dell-dock.c

Default to passive mode on dell-dock with EC23+

---

libfwupd/fwupd-self-test.c

Replace the non-breaking space with a traditional space rather than changing
the expected output with #ifdef to allow running the tests with a daemon
compiled against an older glib2 version.

Fix the self tests when using glib2 >=2.59.0

---

contrib/ci/debian_s390x.sh
contrib/ci/ubuntu.sh
contrib/debian/rules

Disallow use of -Wl,-Bsymbolic-functions

---

src/fu-progressbar.c
src/fu-tool.c

Quiet fwupdtool/fwupdmgr even further

---

src/fu-tool.c

Correct some crashes with fwupdtool

---

plugins/dell-dock/fu-dell-dock-i2c-ec.c

Turns out we can't have nice things that work properly just yet :crying_cat_face: 

trivial: dell-dock: bump passive requirement to EC25+

---

.lgtm.yml
plugins/dell-dock/fu-dell-dock-i2c-mst.c
plugins/superio/fu-superio-device.c
plugins/uefi/fu-uefi-common.c
plugins/uefi/fu-uefi-device.c
plugins/wacom-usb/fu-wac-module-bluetooth.c
src/fu-device-metadata.h

trivial: Use the 0.1.5 snapshot when building the LGTM CI

---

.circleci/config.yml

trivial: circleci: run apt update before snapcraft

---

data/meson.build
meson.build
meson_options.txt
src/fu-util-common.c

Closed #798
- [ X] Feature
I have tested this changeset on top of 1.2.4 release on Gentoo system with OpenRC. In the PR changes are rebased on top of master.

Add elogind support

---

contrib/ci/Dockerfile-debian.in

This reverts commit e7ee71984389a48e0c6de3caf76c040c6eadcd8e.

Revert "contrib/debian: Switch to debian unstable"

---

plugins/uefi/fu-uefi-vars.c

uefi: Fix the self tests when running on Fedora SilverBlue

---

libfwupd/meson.build

trivial: Use newer Meson features

---

libfwupd/fwupd-device.c
libfwupd/fwupd-release.c

trivial: Use JSON arrays properly

---

contrib/standalone-installer/assets/header.py

Allow passing down to the fwupdmgr call both --allow-older and/or --allow-reinstall when using the standalone installer.

standalone-installer: new --allow-older and --allow-reinstall options

---

plugins/synapticsmst/synapticsmst-device.c
plugins/uefi/efi/fwupdate.c

I looked at the LGTM alerts and they do seem like they're good recommendations that make sense.

Pull in some fixes from LGTM alerts

---

contrib/debian/fwupd.install
contrib/fwupd.spec.in
data/bash-completion/fwupdagent
data/bash-completion/meson.build
meson_options.txt
po/POTFILES.in
src/fu-agent.c
src/meson.build

This currently just outputs the current list of devices with releases and makes
it possible to integrate firmware version reporting with other tools like mgmt.

Add the fwupdagent binary for use in shell scripts

---

contrib/firmware-packager/firmware-packager

fix makecab directive options

---

contrib/add-capsule-header.py

This may be helpful for OEMs and ODMs shipping 'bare' firmware.

Add a simple script to add a capsule header

---

src/fu-engine.c

There are a lot of failures in the LVFS with 'device version not updated on
success' and this is because we were looking at the original FuDevice, rather
than the FuDevice that came back after the bootloader replug phase.
Before doing the check get the new FuDevice to prevent failing the check with
a false positive.

Correctly get the check the new version for devices that replug

---

plugins/uefi/efi/fwupdate.c

Signed-off-by: Peter Jones <pjones@redhat.com>

Update the UEFI UX Capsule Header checksum when needed.

---

plugins/ata/fu-ata-device.c

This should flush all remaining writes and make the drive safe to
update.
I don't have the ability to actually test this though.

ata: send ATA standby immediate when activating firmware

---

plugins/uefi/fu-uefi-pcrs.c

Otherwise we can get a PCR0 of 'getcapability:getpcrallocationstatuserror'...

uefi: More carefully check the output from tpm2_pcrlist

---

plugins/synapticsmst/fu-plugin-synapticsmst.c

An undiagnosed kernel issue is leading to a kernel crash involving
DP aux reads with amdgpu involved.
It's been reproduced in kernel 4.15 with a DKMS version of amdgpu as
well as kernel 4.19 with amdgpu within the kernel.
```
[16862.519947] [drm:generic_reg_wait [amdgpu]] *ERROR* REG_WAIT timeout 10us * 160 tries - submit_channel_request line:246
[16862.519983] WARNING: CPU: 5 PID: 3015 at drivers/gpu/drm/amd/amdgpu/../display/dc/dc_helper.c:254 generic_reg_wait+0xe2/0x160 [amdgpu]
[16862.519984] Modules linked in: rfcomm snd_hda_codec_realtek snd_hda_codec_generic cmac bnep arc4 nls_iso8859_1 amdkfd amd_iommu_v2 amdgpu i915 dell_rbtn iwlmvm snd_soc_skl wmi_bmof dell_wmi intel_rapl x86_pkg_temp_thermal dell_laptop intel_powerclamp snd_soc_skl_ipc dell_smbios coretemp snd_soc_sst_ipc …
```

synapticsmst: blacklist plugin when using amdgpu (Fixes: #1121)

---

data/bash-completion/fwupdtool.in
src/fu-tool.c

fu-tool: Port get-history command to fwupdtool

---

plugins/thunderbolt/fu-plugin-thunderbolt.c

thunderbolt: Set require-ac for Thunderbolt devices (Fixes: #1142)

---

plugins/ebitdo/data/m30.txt
plugins/ebitdo/ebitdo.quirk
plugins/ebitdo/fu-ebitdo-device.c

Updated: Add support for 8BitDo M30.

---

po/LINGUAS
po/lt.po

l10n: Added Lithuanian translation

---

libfwupd/fwupd-enums.c
libfwupd/fwupd-enums.h
plugins/dell/fu-plugin-dell.c
plugins/uefi/fu-plugin-uefi.c
src/fu-engine.c

We don't need to report failures to do with AC or battery level to the LVFS.

Do not report transient failures

---

plugins/dfu/dfu-device.c

Fixes: https://github.com/hughsie/fwupd/issues/1152

Correctly parse DFU interfaces with extra vendor-specific data

---

plugins/dell-dock/dell-dock.quirk
plugins/dell-dock/fu-dell-dock-i2c-ec.c

Drop all TODO and quirks for older pre-production boards.

Clean up all TODO in dell-dock

---

src/fu-archive.h
src/fu-common-version.c
src/fu-common-version.h
src/fu-common.c
src/fu-common.h
src/fu-config.h
src/fu-device-private.h
src/fu-device.c
src/fu-engine.h
src/fu-idle.h
src/fu-keyring.h
src/fu-mutex.c
src/fu-mutex.h

Add missing gtk-doc documentation

---

plugins/uefi/fu-plugin-uefi.c

Help people to debug when their ESP isn't found.

trivial: uefi: clarify error message

---

meson.build
src/fu-common.c
src/fu-common.h
src/fu-util.c

Point people to a wiki page to explain what is happening and how to fix it.

trivial: fu-main: clarify missing PK file error

---

plugins/flashrom/fu-plugin-flashrom.c

Signed-off-by: Artur Raglis <artur.raglis@3mdeb.com>

flashrom: separate write and verify operation

---

plugins/ebitdo/ebitdo.quirk

Add support for 8bitdo USB Retro Receiver
There is an accompanying pull request here https://github.com/hughsie/8bitdo-firmware/pull/15

Add support for 8bitdo USB Retro Receiver

---

plugins/flashrom/flashrom.quirk

Signed-off-by: Artur Raglis <artur.raglis@3mdeb.com>

plugins/flashrom/flashrom.quirk: add LT1000 device

---

.lgtm.yml
snap/snapcraft.yaml

Fix lgtm cirlce ci

---

plugins/thunderbolt/fu-plugin-thunderbolt.c

trivial: Fix typos in error messages

---

plugins/uefi/fu-plugin-uefi.c

* In startup, check BIOS characteristics for UEFI supported instead of for /sys/firmware/uefi
* In coldplug check for /sys/firmware/uefi
* If /sys/firwmare/uefi missing, create a dummy device telling the user it is in legacy mode

uefi: Determine whether running in legacy mode or not (Fixes: #1220)

---

plugins/uefi/fu-plugin-uefi.c
src/fu-util.c

trivial: fix error handling for non UEFI case (#1220)

---

plugins/flashrom/fu-plugin-flashrom.c

Signed-off-by: Artur Raglis <artur.raglis@3mdeb.com>

flashrom: Fix no version format set

---

plugins/dell-dock/dell-dock.quirk
plugins/thunderbolt/fu-plugin-thunderbolt.c

trivial: Update icons for Thunderbolt and MST devices

---

data/meson.build

trivial: add cache directory into systemd unit rw paths

---

src/fu-tool.c

fu-tool: Port ability to update a single device from fwupdmgr

---

src/fu-history.c

Fixes https://github.com/hughsie/fwupd/issues/1196

Be more accepting when trying to recover a failed database migration

---

src/fu-common.c
src/fu-common.h
src/fu-device.c
src/fu-firmware-image.c
src/fu-firmware.c
src/fu-firmware.h
src/fu-self-test.c

This allows firmware to add to the existing image output and will be used for
future firmware types.

Add a ->to_string() vfunc to FuFirmware

---

plugins/unifying/README.md

unifying: update Solaar url

---

plugins/uefi/fu-plugin-uefi.c

trivial: uefi: set vendor name for system firwmare from DMI data

---

src/fu-common.c
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c
src/meson.build

Drop some data from to_string and json methods that shouldn't export in text frontends

---

.circleci/config.yml
.travis.yml
contrib/ci/ubuntu.sh

For now this is happening on every master build, but in the future
after it's working reliably it should be restricted to only tagged
builds.

WIP: Publish docs to fwupd.github.io using CircelCI

---

plugins/uefi/fu-self-test.c
plugins/uefi/fu-uefi-pcrs.c

A simple test for the existence of the node `/sys/class/tpm/tpm0` is
not enough to indicate that fwupd will be able to use the TPM.
Check the permissions of the devnode to make sure the underlying
library can access it.

trivial: uefi-self-test: Skip TPM2 PCR0 test if missing permissions

---

plugins/unifying/fu-unifying-bootloader.c
plugins/unifying/fu-unifying-common.h

unifying: fix timeout

---

plugins/thelio-io/README.md
plugins/thelio-io/fu-thelio-io-device.c
plugins/thelio-io/fu-thelio-io-device.h
plugins/thelio-io/thelio-io.quirk

I will be collecting any fixes needed to flash Thelio Io here.

Thelio Io fixes

---

plugins/unifying/unifying.quirk

https://github.com/fwupd/fwupd/pull/1337 fixed the timeout but I forgot to update the metadata.

unifying: fix timeout metadata

---

src/fu-util-common.c

This reverts commit dca4d6a5d69c46f7368b2f65b49b98d58f9217b8.
I've had two vendors ask me why the GUIDs have disappeared from the device.

Re-introduce GUID support to fwupdmgr and fwupdtool

---

data/bash-completion/meson.build
data/meson.build
data/remotes.d/meson.build
meson.build
meson_options.txt
src/meson.build

This allows us to easily build just libfwupd in a flatpak manifest without
installing dozens of deps to build things we're just going to delete anyway.

Allow disabling all plugins

---

libfwupd/fwupd-device.c

This caused some head scratching about the 'missing' values when doing
fu_device_to_string() before fu_device_convert_instance_ids() had been called.

Print the instance IDs if the GUIDs are unconverted

---

src/fu-ihex-firmware.c
src/fu-srec-firmware.c

Additionally, change the reported line to be indexed from 1 (rather than 0) as
most text editors show line 1 as the first line.

Add some more debugging to the SREC and IHEX parsers

---

libfwupd/fwupd-enums.c
libfwupd/fwupd-enums.h
src/fu-history.c
src/fu-self-test.c
src/fu-tool.c
src/fu-util-common.c
src/fu-util.c

Wip/superm1/device history 

---

src/fu-common.c

Embedded newline characters don't do so well.

trivial: fu-util-common: fix description wrapping (Fixes: #1378)

---

.circleci/config.yml
snap/snapcraft.yaml

This makes the snap build quicker by using more distro dependencies
and also fixes some unicode output errors.

snap: switch to core18

---

.github/stale.yml

trivial: add stalebot (Fixes: #1393)

---

libfwupd/fwupd-client.c
libfwupd/fwupd-client.h
libfwupd/fwupd-common.c
libfwupd/fwupd.map
src/fu-engine.c
src/fu-engine.h
src/fu-main.c
src/org.freedesktop.fwupd.xml

Fixes https://github.com/fwupd/fwupd/issues/1365

Fall back to /var/lib/dbus/machine-id when required

---

src/fu-util.c

Fixes https://github.com/fwupd/fwupd/issues/1400

Do not ask the user to upload a report if ReportURI is not set

---

src/fu-debug.c

This allows us to match the debug output of other legacy tools easier, which
allows us to compare output dumps for differences.

Add a --no-domain logging option

---

plugins/synaptics-rmi/fu-synaptics-rmi-device.c

Fixes https://github.com/fwupd/fwupd/issues/1427

synaptics-rmi: Ignore the ATTN reports from the hardware when reading DATA

---

src/fu-engine.c
src/fu-util.c

A couple of fixes related to report behavior prompts

---

plugins/thunderbolt/fu-plugin-thunderbolt.c

Use this attribute to determine whether or not to try to read 'native'
from the Thunderbolt NVM image at probe time.
This attribute is new to kernel 5.5:
https://git.kernel.org/pub/scm/linux/kernel/git/westeri/thunderbolt.git/commit/?h=next&id=b406357c572b29cdcf05f717c69ae0018fa6a146

thunderbolt: recognize new 'generation' sysfs attribute

---

src/fu-systemd.c
src/fu-tool.c

Fix the systemd stopping logic

---

src/fu-util.c

Avoid some extra roundtrips to the daemon if user has poked at some
files.

trivial: fu-util: add some extra checks around automatic reports

---

contrib/ci/arch.sh

Works around transient race conditions.

trivial: arch: ci: Wait some time for tpm_server to start up

---

plugins/thunderbolt/fu-plugin-thunderbolt.c

Currently ICL shows up like this:
```
├─Unknown Device:
│     Device ID:           d066959bf1b0da600f4fcaab5aa31cab3ff05eee
│     Summary:             Unmatched performance for high-speed I/O
│     Current version:     71.00
│     Update Error:        Missing non-active nvmem
│     Flags:               internal|require-ac|registered
│     GUID:                e72e778e-94f7-5ed2-b560-1c1262ee217c
```
Which isn't very useful to end users.  Instead show the generic name
`Thunderbolt Controller` which matches the behavior change we've made
in UEFI FW and Touchpad FW items too.
```
├─Thunderbolt Controller:
│     Device ID:           d066959bf1b0da600f4fcaab5aa31cab3ff05eee
│     Summary:             Unmatched performance for high-speed I/O
│     Current version:     71.00
│     Update Error: …
```

thunderbolt: some more clarifications when using ICL

---

contrib/fwupd.spec.in
meson_options.txt
plugins/emmc/README.md
plugins/emmc/emmc.quirk
plugins/emmc/fu-emmc-device.c
plugins/emmc/fu-emmc-device.h
plugins/emmc/fu-plugin-emmc.c
plugins/emmc/meson.build
plugins/meson.build
src/fu-engine.c
src/fu-plugin.c
src/fu-udev-device.c

Not tested yet (no binaries available)

Add eMMC plugin

---

plugins/uefi/fu-plugin-uefi.c
plugins/uefi/fu-uefi-common.c
plugins/uefi/fu-uefi-device.c
plugins/uefi/fu-uefi-tool.c
plugins/uefi/fu-uefi-udisks.c
plugins/uefi/fu-uefi-udisks.h
src/fu-device.c
src/fu-device.h
src/fu-engine.c

uefi: unmount the ESP if we mounted it

---

plugins/dfu/dfu-device.c
plugins/dfu/dfu.quirk

100% untested until hardware arrives.

dfu: Add a quirk for Realtek camera hardware

---

src/fu-engine.c

This matches the UDEV device add, and was missed from the original commit due
to a failed rebase.
Fixes https://github.com/fwupd/fwupd/issues/1512

trivial: Use the new possible_plugin support for USB devices too

---

data/bash-completion/fwupdmgr.in
data/bash-completion/fwupdtool.in
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

Use device safety flags to show prompts before installing updates

---

libfwupd/fwupd-error.c
libfwupd/fwupd-error.h
plugins/ebitdo/fu-ebitdo-device.c
plugins/unifying/fu-unifying-peripheral.c
src/fu-engine.c

unifying: notify users to replug when using dfu control (Fixes: #1383)

---

plugins/wacom-raw/wacom-raw.quirk

trivial: wacom: add vid/pid for panels in Moffett

---

meson.build
src/fu-udev-device.c
src/fu-udev-device.h

Flatpak shared-modules now ships gudev over 232.

Bump the required gudev version

---

plugins/wacom-raw/wacom-raw.quirk

trivial: wacom-raw: add more device IDs for Dell devices

---

plugins/modem-manager/fu-mm-device.c
plugins/modem-manager/modem-manager.quirk

ModemManager: added support for the DW5821e/eSIM variant

---

contrib/get-version.py

trivial: contrib/get-version.py: require git less hard

---

data/org.freedesktop.fwupd.service.in

Allows confined snaps to activate fwupd via D-Bus

---

plugins/modem-manager/modem-manager.quirk

modem-manager: add quirks for the Foxconn T77W968 modules

---

src/fu-engine.c
src/fu-self-test.c

For composite devices you might want to restrict the child device in respect
to the parent, for instance requiring the parent to have greater than a specific
version number.
The other useful thing to use this for is checking if the parent has a specific
GUID (of any version) which allows us to match against the common VID&PID
instance IDs. This would allow us to restrict a generic child device update to
a specific OEM vendor parent.
This is specified as <firmware depth="1" ...> to match the parent device and
<firmware depth="2" ...> to match the grandparent device.

Add support for matching <firmware> requirements on device parents

---

meson.build
subprojects/.gitignore
subprojects/gusb.wrap

This allows us to get closer to compiling on FreeBSD.

Allow compiling GUsb as a subproject

---

data/tests/builder/startup.sh
data/tests/spawn.sh
plugins/flashrom/example/build.sh
plugins/flashrom/example/random-tool
plugins/flashrom/example/startup.sh

Fix shebangs on scripts

---

plugins/coreboot/README.md
plugins/coreboot/coreboot.quirk
plugins/coreboot/fu-coreboot-common.c
plugins/coreboot/fu-plugin-coreboot.c
plugins/coreboot/fu-plugin-coreboot.h
plugins/coreboot/meson.build

Coreboot fixes

---

plugins/wacom-raw/wacom-raw.quirk

trivial: wacom: remove coretronic config from Moffett scope

---

plugins/dell-dock/fu-dell-dock-i2c-mst.c
src/fu-util.c

Two small bug fixes in fu-util and dell-dock plugin.

Various fixes

---

po/af.po
po/ca.po
po/cs.po
po/da.po
po/de.po
po/en_GB.po
po/fi.po
po/fur.po
po/hr.po
po/hu.po
po/id.po
po/it.po
po/ko.po
po/lt.po
po/nl.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sr.po
po/sv.po
po/tr.po
po/uk.po
po/zh_CN.po
po/zh_TW.po
src/fu-progressbar.c

Spotted this while reading through the code.

Replace 'scheduing' with 'scheduling'

---

plugins/synaptics-prometheus/fu-synaprom-device.c

Allow incremental version major and minor number

synaptics-prometheus: Allow incremental version

---

src/fu-tool.c

Throw exit status 0 (instead of 2) if there is no firmware to be updated

---

src/fu-engine.c
src/fu-tool.c
src/fu-util.c

Clarify error messages when no upgrades available

---

data/tests/daemon.conf
libfwupdplugin/fu-common.c
src/fu-remote-list.c
src/fu-self-test.c

Follow up from the `FuConfig` split up.

Adjust remote list path handling

---

README.md

Capitalize GNOME

---

plugins/dell-dock/fu-dell-dock-hub.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
src/fu-engine.c

Add some missing protocol definitions

---

data/bash-completion/fwupdagent
data/bash-completion/fwupdtool.in
libfwupdplugin/fu-common.c
libfwupdplugin/fu-device.c
libfwupdplugin/fu-plugin-vfuncs.h
libfwupdplugin/fu-plugin.c
plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.c
plugins/synaptics-rmi/fu-synaptics-rmi-device.c
plugins/tpm/fu-tpm-device.c
plugins/vli/fu-vli-usbhub-i2c-common.h
src/fu-agent.c
src/fu-install-task.c
src/fu-progressbar.c

Apparently this is wanted by the SOS team too.

Allow getting the list of updates in JSON format from fwupdagent

---

plugins/upower/fu-plugin-upower.c

Based on a patch by Crag Wang <Crag.Wang@dell.com>, many thanks.

Don't check the battery percentage if UPwer is unavailable

---

src/fu-engine.c

trivial: fu-engine: fix an assertion when system has no product ID

---

src/fu-engine.c

In case a plugin decides to make a version 5.3.10 instead of 5.3.010
these should match.

src: fu-engine: check version was updated by checking version

---

src/fu-engine-helper.c

trivial: fix plural translation (Fixes: #1732)

---

plugins/logitech-hidpp/fu-logitech-hidpp-hidpp.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c

Fix reboot of logitech devices

---

plugins/uefi/efi/meson.build

Fixes https://github.com/fwupd/fwupd/issues/1754

uefi: Fix a build regression with Fedora 30

---

plugins/ebitdo/fu-ebitdo-device.c

ebitdo: Fix the endpoint address logged in the error message

---

contrib/ci/build_windows.sh
contrib/debian/fwupd.install
contrib/debian/rules
contrib/fwupd.spec.in
contrib/setup-win32.nsi
contrib/snap/fwupdtool.wrapper
plugins/tpm-eventlog/fu-tpm-eventlog.c
plugins/tpm-eventlog/meson.build
plugins/uefi/meson.build
src/meson.build

Move some binaries to usr/bin

---

src/fu-tool.c
src/fu-util.c

trivial: fu-engine: remove some non-translatable strings (Fixes: #1678)

---

src/fu-tool.c

The title isn't initialized until the engine is started, so don't
try to read it too early.

trivial: fwupdtool: fix tree title

---

plugins/ata/ata.quirk

trivial: add an OUI quirk for a seagate disk

---

contrib/fwupd.spec.in
plugins/logind/README.md
plugins/logind/fu-plugin-logind.c
plugins/logind/meson.build
plugins/meson.build

Fixes https://github.com/fwupd/fwupd/issues/1814

Inihbit all power management actions using logind when updating

---

src/fu-engine.c
src/fu-tool.c
src/fu-util.c

Pull these out of #1807 to keep review easy.

Various fixes for get-details command

---

plugins/tpm-eventlog/fu-plugin-tpm-eventlog.c

trivial: send users to a wiki page for TPM PCR0 consturction errors

---

libfwupdplugin/fu-common-version.c
libfwupdplugin/fwupdplugin.map

trivial: update libfwupdplugin map for symbol backported to 1_3_X

---

plugins/ata/ata.quirk

Added the OUI quirks for
- Western Digital
- Intel

Add OUI quirk for Western Digital and Intel

---

contrib/fwupd.spec.in
plugins/cpu/README.md
plugins/cpu/fu-cpu-device.c
plugins/cpu/fu-cpu-device.h
plugins/cpu/fu-plugin-cpu.c
plugins/cpu/meson.build
plugins/meson.build

Add a read-only CPU microcode plugin

---

src/fu-engine.c
src/fu-engine.h
src/fu-install-task.c
src/fu-main.c
src/fu-tool.c

When these values are coming from the metadata in the CAB file, it's important to apply them to the checks used for these two commands.

Fix `get-details` and `install` for VersionFormat changes

---

plugins/uefi/fu-uefi-bootmgr.c

Since the entry is dynamically created this removes one area that
can potentially cause failures.
Helps: #1794

uefi: Don't use shim for non-secure boot configurations

---

src/fu-tool.c
src/fu-util.c

Fixes https://github.com/fwupd/fwupd/issues/1870

Add the optional device-id to the update --help output

---

plugins/logitech-hidpp/fu-logitech-hidpp-bootloader-texas.c
plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.c
plugins/logitech-hidpp/fu-logitech-hidpp-hidpp.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c

Fixes updates on signed receivers.

logitech: Correctly set the protocol

---

plugins/vli/fu-vli-pd-device.c

vli: Only consider the high nibble when building the sub-version

---

contrib/ci/generate_docker.py

trivial: fix ubuntu CI

---

contrib/ci/dependencies.xml

trivial: ci: exclude ia64 for flashrom

---

data/bash-completion/fwupdtool.in
src/fu-engine.c
src/fu-engine.h
src/fu-tool.c

Fwupdtool reinstall

---

plugins/ccgx/ccgx.quirk

- Add new DeviceInstanceId using Silicon ID and Application type

Add new DeviceInstanceId

---

plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.c

logitech_hidpp: set the bootloader protocol

---

src/fu-engine.c

Check the firmware requirements before adding SUPPORTED

---

src/fu-engine.c
src/fu-util-common.c

trivial: Add a new category for CPU microcode

---

plugins/ccgx/fu-ccgx-hid-device.c
plugins/ccgx/fu-ccgx-hpi-device.c

Based on a patch by  Ryan Lee <ryle@cypress.com>, many thanks.

ccgx: Retry the HID disconnect up to 5 times

---

plugins/ccgx/ccgx.quirk

- Code fix
Add Parent GUID for hyrbid dock

add parent guid for hybrid dock

---

contrib/ci/dependencies.xml
contrib/debian/rules

trivial: enable libjcat from Debian & Ubuntu distro builds

---

src/fu-device-list.c

In this case, a plugin was doing:
g_autoptr(FuDevice) parent = fu_device_get_parent (device);
Which is not valid as it is `(transfer none)` but that shouldn't be enough to
get the daemon to crash. If the FuDevice refcount drops to zero just print
a critical warning with the pointer (no FuDevice details are available) and
remove the FuDeviceItem from the device list.
Using `G_DEBUG=fatal-criticals` it is very easy to backtrace at the right place
and find out which naughty plugin needs to go on the thinking spot.

Do not crash the daemon if a plugin does something dumb

---

contrib/afl-fuzz.py
contrib/ci/flatpak.py
contrib/ci/generate_debian.py
contrib/ci/generate_dependencies.py
contrib/ci/generate_docker.py
contrib/firmware_packager/add_capsule_header.py
contrib/firmware_packager/add_dfu_header.py
contrib/firmware_packager/firmware_packager.py
contrib/firmware_packager/install_dell_bios_exe.py
contrib/firmware_packager/simple_client.py
contrib/fix_translations.py
contrib/generate-version-script.py
contrib/nvme-parse.py
contrib/standalone-installer/assets/header.py
contrib/standalone-installer/make.py
libfwupdplugin/fu-hash.py
plugins/dfu/contrib/parse-avrdude-conf.py

Use black to format python source in a consistent manner

---

libfwupdplugin/fu-device.c

The device might not know what mode it is running in until after the device has
been opened.

Allow a device to set the logical or physical ID during ->setup()

---

src/fu-tool.c
src/fu-util.c

Some various fixes related to GUID handling

---

meson.build
plugins/dell/fu-plugin-dell.c
plugins/uefi/fu-uefi-pcrs.c

This is not provided in RHEL 8 in the default build root.

Make tss2-esys conditional

---

plugins/ata/ata.quirk

trivial: Add OUI quirk for LITE-ON

---

plugins/ata/ata.quirk

trivial: Add OUI quirk for ADATA

---

.circleci/config.yml
contrib/ci/generate_news.py

trivial: potentially publish changelog to github release

---

plugins/wacom-raw/fu-wacom-device.c

wacom-raw: fixup switching to bootloader mode

---

plugins/tpm-eventlog/fu-tpm-eventlog.c

Some fixups for tpm-eventlog tool

---

plugins/ata/ata.quirk

trivial: Add OUI quirk for SanDisk

---

meson.build
plugins/ccgx/fu-ccgx-hpi-device.c
plugins/ep963x/fu-ep963x-device.c

Fixes https://github.com/fwupd/fwupd/issues/2068

Fix various build issues with -Wdiscarded-qualifiers

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fwupdplugin.map

Some plugins will be Intel specific.

trivial: Add a helper method to check for an Intel CPU

---

src/fu-engine.c
src/fu-util-common.c

Some HSI improvements

---

plugins/amt/fu-plugin-amt.c

amt: Add a security attestation for provisioning

---

plugins/synaptics-rmi/synaptics-rmi.quirk

Fixes https://github.com/fwupd/fwupd/issues/2052

synaptics-rmi: Essentially blacklist Dell K12A

---

plugins/ata/ata.quirk

ata: Add WD OUI quirk 000cca

---

plugins/ata/ata.quirk

Add two OUI quirks outputed by 'fwupdtool get-updates' on my computer.

Add two OUI quirks

---

plugins/cpu/fu-plugin-cpu.c

On a CPU that does support it the security check was still failing.

trivial: fix TME support

---

src/fu-engine.c

Fix HSI attestation checksum handling

---

plugins/synaptics-prometheus/fu-synaprom-device.c

sure the devices can be updated back to 0x01.

synaptics-prometheus: Force the minor version from 0x02 to 0x01 to make

---

libfwupd/fwupd-security-attr.h
plugins/cpu/fu-cpu-device.c
plugins/cpu/fu-cpu-device.h
plugins/cpu/fu-plugin-cpu.c
src/fu-security-attr.c

See https://en.wikipedia.org/wiki/Supervisor_Mode_Access_Prevention for details.

Add an HSI attribute for Intel SMAP

---

libfwupd/fwupd-security-attr.h
plugins/amt/fu-plugin-amt.c
src/fu-security-attr.c

This reverts commit f160e6b7fc75b5b5f5f3e42e0c391d5bede9de9e.

Revert "amt: Add a security attestation for provisioning"

---

src/fu-engine.c

One vendor is shipping a cab archive with two metadata files, both referencing
the same GUID. The 'correct' metainfo description is selected using a GUID
'other device' requirement. This works fine when installing, but breaks when
double clicking on the .cab file as both components are valid, and thus get
returned.
In this case, return the component that matches the requirement 'first' so that
it gets chosen by gnome-software as the default.

Check the device requirements when returning from GetDetails

---

libfwupd/fwupd-security-attr.h
plugins/pci-mei/fu-mei-common.c
plugins/pci-mei/fu-mei-common.h
plugins/pci-mei/fu-plugin-pci-mei.c
plugins/pci-mei/meson.build
src/fu-security-attr.c

Detect if the MEI device has known security issues

---

src/meson.build

trivial: fix issue with agent on but man off

---

src/fu-engine.c

Additionally, ignore the 'not found' error codes so we drop down to the release
missing error.
Fixes https://github.com/fwupd/fwupd/issues/2196

Check all AppStream components when verifying

---

plugins/ccgx/fu-ccgx-dmc-device.c

ccgx: add new protocol for dmc dock

---

plugins/modem-manager/README.md
plugins/modem-manager/fu-mm-device.c
plugins/modem-manager/modem-manager.quirk

trivial: modem-manager: add a protocol for updating the devices

---

src/fu-engine.c

This means we only parse the complicated xpath query once, rather than for
every GUID the device has.
The code flow is also simplified and split out into two functions.

Use libxmlb bound parameters to speed up te device verification

---

plugins/modem-manager/fu-qmi-pdc-updater.c
snap/snapcraft.yaml

trivial: snap: move to newer modem manager stuff

---

src/fu-util.c

trivial: fu-util: show a better error for non-responsive daemon

---

plugins/ccgx/ccgx.quirk
plugins/ccgx/fu-ccgx-hpi-device.c

1. Fix and Add Lenovo Hybrid Dock meta data in quirk file
2. Add HPI command retry to prevent command fail due to other events in Hybrid Dock

ccgx: add hybrid dock in quirk, add hpi cmd retry

---

plugins/tpm-eventlog/fu-plugin-tpm-eventlog.c

Don't make it front and center, mirroring a change in 1.5.x

trivial: move PCR0 message into journal output

---

src/fu-tool.c

Fixes half of https://github.com/fwupd/fwupd/issues/2223

Be more defensive when remotes are missing required keys

---

src/fu-debug.c

Convert warning messages to ASCII when logged

---

libfwupdplugin/fu-udev-device.c
libfwupdplugin/fwupdplugin.map

See https://github.com/fwupd/fwupd/pull/2235 for details
If that doesn't go through this one shouldn't either.

trivial: update various symbols to 1.4.5

---

plugins/rts54hid/README.md

fix alignment (in the code)

---

src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

Group devices in get-updates output

---

libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-udev-device.h
libfwupdplugin/fwupdplugin.map
plugins/thunderbolt/README.md
plugins/thunderbolt/fu-thunderbolt-device.c

(I don't actually have hardware that can test this, so it's best effort)

Add support for Thunderbolt retimers

---

po/de.po

This is just a small fix in a comment of the German translation file de.po.

fix syntax in German translation file (de.po)

---

plugins/cros-ec/README.md
plugins/cros-ec/fu-cros-ec-firmware.c
plugins/cros-ec/fu-cros-ec-firmware.h
plugins/cros-ec/fu-cros-ec-usb-device.c

Implement the pieces necessary to write firmware to cros-ec usb devices utilizing Protocol 6 or later.

cros-ec: cros-ec-usb-device write firmware

---

plugins/ccgx/README.md

1. Reorder section in readme.md due to Lenovo request.
2. Modify readme.md to remove customer specific information.

ccgx: modify readmd to remove customer info

---

plugins/superio/superio.quirk

Added quirk for LabTop Mk IV

---

contrib/ci/Dockerfile-ubuntu.in
contrib/ci/dependencies.xml
plugins/ccgx/fu-ccgx-hpi-device.c
plugins/cpu/fu-cpu-helper-cet.c
plugins/thunderbolt/fu-self-test.c
plugins/thunderbolt/fu-thunderbolt-device.c
plugins/tpm-eventlog/fu-plugin-tpm-eventlog.c
plugins/uefi/fu-plugin-uefi.c
src/fu-config.c
src/fu-engine.c
src/fu-self-test.c

trivial: move ubuntu ci to clang 10

---

data/bash-completion/fwupdmgr.in
data/daemon.conf
libfwupd/fwupd-client.c
libfwupd/fwupd-client.h
libfwupd/fwupd.map
src/fu-config.c
src/fu-config.h
src/fu-engine.c
src/fu-engine.h
src/fu-history.c
src/fu-history.h
src/fu-main.c
src/fu-util.c
src/org.freedesktop.fwupd.xml

Fixes https://github.com/fwupd/fwupd/issues/2280

Allow blocking specific firmware releases by checksum

---

plugins/synaptics-prometheus/README.md
plugins/synaptics-prometheus/fu-synaprom-config.c
plugins/synaptics-prometheus/synaptics-prometheus.quirk

synaptics-prometheus: generate new guid with configid and add pids to

---

po/POTFILES.in

Update POTFILES.in 200815

---

src/fu-util-common.c

This would fall back to X-System.

Add X-Configuration to use for dbx updates

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fwupdplugin.map
plugins/cpu/README.md
plugins/cpu/cpu.quirk
plugins/cpu/fu-cpu-device.c
plugins/cpu/fu-plugin-cpu.c
plugins/cpu/meson.build
plugins/pci-bcr/fu-plugin-pci-bcr.c

Fixes https://github.com/fwupd/fwupd/issues/2328

pcb-bcr: Use the correct BCR register for Bay Trail CPUs

---

plugins/dell-dock/fu-dell-dock-i2c-ec.c

Only add instance ID if it actually probes properly.
Otherwise this makes an invalid assumption that the device is a WD19
EC just because it had the correct hub in front.
Instead check the first time it's opened that the correct device
is identified (`EXPECTED_DOCK_TYPE`)

trivial: dell-dock: check for valid dock type on open

---

contrib/ci/dependencies.xml
contrib/ci/fedora.sh
contrib/ci/trust.sh
contrib/fwupd.spec.in
meson.build
plugins/cros-ec/fu-cros-ec-firmware.c
plugins/cros-ec/fu-cros-ec-firmware.h
plugins/cros-ec/fu-cros-ec-usb-device.c
subprojects/gusb.wrap

cros-ec: Read Only and Read Write update support

---

plugins/linux-lockdown/fu-plugin-linux-lockdown.c
plugins/linux-swap/fu-plugin-linux-swap.c
plugins/linux-tainted/fu-plugin-linux-tainted.c
plugins/thunderbolt/fu-self-test.c
src/fu-config.c
src/fu-main.c
src/fu-remote-list.c

Fixes https://github.com/fwupd/fwupd/issues/2350

Cancel the file monitor before disposal to avoid a potential deadlock

---

plugins/cpu/cpu.quirk
plugins/pci-bcr/fu-plugin-pci-bcr.c

Fixes https://github.com/fwupd/fwupd/issues/2328

cpu: Correct the BCR address for Atom Bay Trail

---

plugins/thunderbolt/fu-thunderbolt-device.c
src/fu-engine.c
src/fu-engine.h
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

Sort out TBT activation for WD19TB on non-disconnect

---

data/bash-completion/fwupdtool.in
src/fu-tool.c

This can be used to extract things like the OptionROM.

Add firmware-extract subcommand to fwupdtool

---

libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-udev-device.h
libfwupdplugin/fwupdplugin.map

trivial: Add fu_udev_device_get_number()

---

contrib/fwupd.spec.in
plugins/goodix-moc/README.md
plugins/goodix-moc/fu-goodixmoc-common.c
plugins/goodix-moc/fu-goodixmoc-common.h
plugins/goodix-moc/fu-goodixmoc-device.c
plugins/goodix-moc/fu-goodixmoc-device.h
plugins/goodix-moc/fu-plugin-goodixmoc.c
plugins/goodix-moc/goodixmoc.quirk
plugins/goodix-moc/meson.build
plugins/meson.build

Support updating firmware for Goodix MOC fingerprint sensors.

Add plugin for goodix fingerprint sensors

---

libfwupdplugin/fu-common-version.c
libfwupdplugin/fu-common.c
libfwupdplugin/fu-plugin.c
plugins/jabra/fu-plugin-jabra.c
plugins/thunderbolt/fu-thunderbolt-device.c
plugins/uefi/fu-plugin-uefi.c
src/fu-engine.c
src/fu-history.c

Your last change inspired some other things I thought should be cleaned up.

Lower some verbosity

---

src/fu-polkit-agent.c
src/fu-polkit-agent.h
src/fu-progressbar.c
src/fu-util.c
src/meson.build

This change will allow it to use pkcon over remote-shells (ssh) or
to use it witout a running GUI desktop environment in the background.
Should fix https://github.com/fwupd/fwupd/issues/2429

Use pkttyagent to request user passwords if running without GUI

---

src/fu-engine.c
src/fu-engine.h
src/fu-tool.c
src/fu-util.c

Also merge fu_engine_get_device and fu_engine_get_device_by_id

Fix get-updates and activate to use GUID in addition to device-id

---

libfwupd/fwupd-common.c
libfwupdplugin/fu-quirks.c
plugins/uefi/efi/fwupdate.c
src/fu-engine.c

Quiet down some more debugging

---

data/bash-completion/fwupdmgr.in
data/bash-completion/fwupdtool.in
libfwupd/fwupd-client.c
libfwupd/fwupd-enums.h
libfwupdplugin/fu-dfu-firmware.c
libfwupdplugin/fu-ihex-firmware.c
libfwupdplugin/fu-srec-firmware.c
plugins/ccgx/fu-ccgx-hpi-device.c
plugins/dfu/dfu-device.c
plugins/dfu/dfu-tool.c
plugins/synaptics-mst/fu-synaptics-mst-device.c
plugins/synaptics-prometheus/fu-synaprom-config.c
plugins/synaptics-prometheus/fu-synaprom-device.c
plugins/synaptics-rmi/fu-dump.c
plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c
plugins/thunderbolt/fu-thunderbolt-device.c
plugins/upower/fu-plugin-upower.c
plugins/vli/fu-vli-pd-firmware.c
src/fu-engine.c
src/fu-firmware-dump.c
src/fu-install-task.c
src/fu-main.c
src/fu-tool.c
src/fu-util.c

This allows us to turn off the tests like version format differences and
checking for downgrades.

Add a --allow-branch-switch to fwupdmgr

---

plugins/elantp/README.md
plugins/elantp/elantp.quirk
plugins/elantp/fu-elantp-hid-device.c
plugins/elantp/fu-elantp-i2c-device.c

Modify the firmware bin file size.
Modify firmware update flow when the firmware in bootloader mode.

elantp: Modify firmware update flow in bootloader mode

---

contrib/fwupd.spec.in
meson.build
plugins/bcm57xx/README.md
plugins/bcm57xx/bcm57xx.quirk
plugins/bcm57xx/fu-bcm57xx-common.c
plugins/bcm57xx/fu-bcm57xx-common.h
plugins/bcm57xx/fu-bcm57xx-device.c
plugins/bcm57xx/fu-bcm57xx-device.h
plugins/bcm57xx/fu-bcm57xx-dict-image.c
plugins/bcm57xx/fu-bcm57xx-dict-image.h
plugins/bcm57xx/fu-bcm57xx-firmware.c
plugins/bcm57xx/fu-bcm57xx-firmware.h
plugins/bcm57xx/fu-bcm57xx-recovery-device.c
plugins/bcm57xx/fu-bcm57xx-recovery-device.h
plugins/bcm57xx/fu-bcm57xx-stage1-image.c
plugins/bcm57xx/fu-bcm57xx-stage1-image.h
plugins/bcm57xx/fu-bcm57xx-stage2-image.c
plugins/bcm57xx/fu-bcm57xx-stage2-image.h
plugins/bcm57xx/fu-plugin-bcm57xx.c
plugins/bcm57xx/fu-self-test.c
plugins/bcm57xx/meson.build
plugins/meson.build

bcm57xx: Add a plugin that can update the BCM5719 network adapter

---

meson.build
meson_options.txt
plugins/uefi/efi/generate_binary.sh.in
plugins/uefi/efi/meson.build

uefi: add configuration option for objcopy utility.

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
libfwupdplugin/fwupdplugin.map
plugins/bcm57xx/fu-bcm57xx-device.c
plugins/dfu/dfu-device.c
plugins/rts54hid/fu-rts54hid-device.c
plugins/vli/fu-vli-device.c
plugins/vli/fu-vli-usbhub-msp430-device.c
plugins/wacom-raw/fu-wacom-aes-device.c

This makes the console a bit more helpful than just 'hanging'...

Add fu_device_msleep_with_progress helper()

---

plugins/cros-ec/cros-ec.quirk
plugins/cros-ec/fu-cros-ec-usb-device.c

cros-ec: RO/RW update with rw_sig support

---

contrib/ci/build_windows.sh
contrib/ci/trust.sh
meson.build
meson_options.txt
src/fu-main.c
src/fu-util.c
src/meson.build

Based on a patch from Daniel Campello at
https://chromium-review.googlesource.com/c/chromiumos/third_party/fwupd/+/2354521

Offer to compile daemon without polkit support

---

plugins/uefi/fu-uefi-bootmgr.c

trivial: increase debugging for for fu-uefi-bootmgr.c

---

src/fu-tool.c
src/fu-util.c

Fixes https://github.com/fwupd/fwupd/issues/2487

Do not include fullstops in the --help output

---

data/bash-completion/fwupdtool.in
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

Untested, I don't have anything I can test it with.  Please feel free to push and fixup as necessary!

Add switch-branch support to fwupdtool

---

plugins/synaptics-prometheus/synaptics-prometheus.quirk

synaptics-prometheus: add pids to quirk file

---

plugins/dell/fu-plugin-dell.c
plugins/tpm/fu-plugin-tpm.c
plugins/uefi/fu-plugin-uefi.c

Fixes https://github.com/fwupd/fwupd/issues/2391

Record the TPM version when reporting a UEFI update

---

src/fu-tool.c
src/fu-util.c

trivial: Do not list unsupported devices in switch-branch

---

plugins/vli/fu-vli-pd-firmware.c
plugins/vli/meson.build
plugins/vli/vli-usbhub-hyper.quirk

HYPER edits to vli plugin, discussed in #2376

vli:small hyper support edits

---

src/fu-main.c

The authentication happens earlier in `fu_main_install_with_helper`
so no need to make recursive calls from `fu_main_authorize_install_cb`
into `fu_main_authorize_install_queue`.
Just simplify the code in the non-polkit case.

trivial: fu-main: adjust polkit install flow

---

libfwupdplugin/fu-efivar.c
libfwupdplugin/fu-efivar.h
libfwupdplugin/fu-self-test.c
libfwupdplugin/fwupdplugin.map
plugins/uefi-dbx/fu-plugin-uefi-dbx.c
plugins/uefi/fu-plugin-uefi.c

Include the amount of NVRAM size in use in the LVFS failure report

---

data/fish-completion/fwupdmgr.fish
src/fu-util.c

I don't know if I need to regenerate the `.po` files, too. Did not do this yet.

trivial: fix description of unblock-firmware

---

src/fu-tool.c
src/fu-util.c

Fixes bugs like https://github.com/fwupd/fwupd/issues/2531

Show a link to discover more information about a specific plugin failure

---

contrib/ci/debian.sh
libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fu-volume-private.h
libfwupdplugin/fu-volume.c
libfwupdplugin/fu-volume.h
libfwupdplugin/fwupdplugin.map
plugins/linux-swap/fu-linux-swap.c
plugins/linux-swap/fu-self-test.c

Using a heuristic is certainly not awesome.
(I'm also not sure how to test this in the self tests....)

Use UDisks to find out if swap devices are encrypted

---

README.md

Fixes https://github.com/fwupd/fwupd/issues/2543

Add note to the README about not using Snap or Flatpak versions

---

src/fu-engine.c

The idea for a missing vendor-id would be that the LVFS sets the value
`NEVER_GOING_TO_MATCH` which is shown (along with the correct value) when the
user tries to **install** the firmware.
In 1.5.0 we correctly switched to filtering the devices by GUID and *then*
checking requirements before showing to the user.
In the missing vendor-id case the the poor ODM does not know why the device is
not showing up until they run the daemon in --verbose mode.
Relax the vendor-id checks when adding releases to devices, but of course leave
them in place for installing firmware. The ignore-vid-pid flag is not added
from `Install(a{sv})` and so this stays the same as before.

Ignore an invalid vendor-id when adding releases for display

---

libfwupdplugin/fu-smbios.c

This allows getting the HSI result on a Pinebook Pro laptop.

Set the SMBIOS chassis type to portable if a DT battery exists

---

src/fu-engine.c

trivial: fu-engine: skip empty cmdline commands

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-volume.c
libfwupdplugin/fu-volume.h
libfwupdplugin/fwupdplugin.map
src/fu-tool.c

Fall back to FAT32 internal partitions for detecting ESP

---

contrib/fwupd.spec.in
plugins/meson.build

trivial: disable bios plugin outside of systems with uefi

---

libfwupd/meson.build
meson.build

Allow building as a subproject

---

contrib/debian/fwupd.install
contrib/debian/rules

Fix some build failures in 1.5.x for Debian

---

data/device-tests/devices/hyper-no-sku-vli-tier1.json
data/device-tests/devices/hyper-no-sku-vli-tier3.json
data/device-tests/devices/lenovo-03x7608-vli-tier1.json
data/device-tests/devices/lenovo-03x7608-vli-tier3.json

Added regression testing files for tr_gen2 and hyper.

trivial: Add vli tr_gen2 and hyper regression test

---

contrib/debian/rules

Various improvements for contrib/debian/rules

---

contrib/debian/fwupd.install
contrib/fwupd.spec.in
meson.build
plugins/msr/meson.build
plugins/platform-integrity/meson.build
snap/hooks/install
snap/hooks/remove

Install modules-load configs in the correct directory

---

libfwupd/fwupd-client.c

Moving to the async libfwupd library design meant this optimization was lost.

Only download the remote metadata as required

---

libfwupd/fwupd-client.c
libfwupd/fwupd-client.h
libfwupd/fwupd.map

If we set a property, we should probably have a way to read it back...

libfwupd: Add fwupd_client_get_user_agent()

---

libfwupd/fwupd-client-sync.c

Set the thread-default context for the current thread before performing the
async operation.
Hopefully fixes https://github.com/fwupd/fwupd/issues/2600

Fix sync method when called from threads without a context

---

plugins/ata/ata.quirk

ata: Add OUI quirk for Toshiba

---

snap/hooks/install

Fix snap build and try to catch problems harder

---

plugins/modem-manager/fu-mm-device.c
plugins/modem-manager/fu-mm-device.h
plugins/modem-manager/fu-plugin-modem-manager.c

- [ X] Code fix
The MR includes some fixes to the modem-manager plugin, and some minor improvements.

modem-manager minor plugin fixes and updates

---

plugins/dfu/dfu-tool.c
plugins/tpm-eventlog/fu-tpm-eventlog.c
plugins/uefi-dbx/fu-dbxtool.c
plugins/uefi/fu-uefi-tool.c
src/fu-agent.c
src/fu-tool.c
src/fu-util.c

Fixes https://github.com/fwupd/fwupd/issues/2616

Mark more user-visible strings as translatable

---

plugins/ata/ata.quirk

Add quirk for Western Digital

---

libfwupdplugin/fu-udev-device.c

This allows the plugin to force a reload of the device using a new GUdevDevice
object. This is required as the values are cached in the immutable object.

Actually implement rescan in FuUdevDevice

---

libfwupdplugin/fu-udev-device.c

Fall back to the misc device for serio devices

---

plugins/uefi/uefi.quirk

Added Lite Mk III

---

contrib/firmware_packager/meson.build
contrib/firmware_packager/simple_client.py

trivial: simple_client: add a refresh metadata function

---

.github/workflows/main.yml

trivial: ci: fix ABI job (hopefully)

---

libfwupdplugin/fu-quirks.c
src/fu-engine.c

See https://github.com/hughsie/libxmlb/pull/67. This doesn’t bump the
hard version dependency.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
---
This is an updated version of #2331, updated as per recent changes in https://github.com/hughsie/libxmlb/pull/67#issuecomment-723125812. It’s marked as WIP until those libxmlb changes are finalised and land.

libfwupdplugin: Support new libxmlb query binding API

---

contrib/debian/fwupd.maintscript
contrib/debian/fwupd.preinst

Migrate debian conffile for modules-load.d

---

libfwupd/fwupd-client.c
libfwupdplugin/fu-cabinet.c
plugins/bcm57xx/fu-bcm57xx-firmware.c
plugins/vli/fu-vli-usbhub-msp430-device.c
src/fu-util.c

trivial: Remove several unused variables

---

plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c

synaptics-rmi: Fix a tiny memory leak when parsing firmware

---

plugins/solokey/fu-solokey-firmware.c

solokey: Prevent a critical warning when parsing invalid JSON data

---

plugins/goodix-moc/fu-goodixmoc-device.c

goodix-moc: Fix a potential crash when reading the USB request

---

libfwupdplugin/fu-fmap-firmware.c

libfwupdplugin: Do not overwrite GError when parsing invalid fmap

---

src/fu-util-common.c

Do not compare a double float to G_MAXUINT64

---

plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c

synaptics-rmi: Fix possible buffer over-read for corrupt firmware

---

po/POTFILES.in

Update POTFILES.in 201212

---

libfwupd/fwupd-common.c
meson.build

Don't assume we have memfd_create()

---

libfwupdplugin/fu-device.c
src/fu-engine.c
src/fu-tool.c
src/fu-util.c

None of these branches are important enough to provide fallbacks for.

trivial: Don't accidentally depend on GLib 2.54.3

---

libfwupd/fwupd-plugin.c
libfwupd/fwupd-security-attr.c
libfwupdplugin/fu-dfu-firmware.c
libfwupdplugin/fu-fmap-firmware.c
plugins/bcm57xx/fu-bcm57xx-common.c
plugins/bcm57xx/fu-bcm57xx-device.c
plugins/bcm57xx/fu-bcm57xx-recovery-device.c
plugins/ccgx/fu-ccgx-dmc-firmware.c
plugins/ccgx/fu-ccgx-firmware.c
plugins/ccgx/fu-ccgx-hpi-device.c
plugins/goodix-moc/fu-goodixmoc-common.c
plugins/jabra/fu-jabra-device.c
plugins/synaptics-cxaudio/fu-synaptics-cxaudio-firmware.c
plugins/synaptics-prometheus/fu-synaprom-firmware.c
plugins/vli/fu-vli-usbhub-rtd21xx-device.c
src/fu-keyring-utils.c

trivial: Require <string.h> for strlen() and memcpy()

---

libfwupd/fwupd-client.c
meson.build

This allows us to build on Ubuntu 16.04!

Lower libcurl requirement further still

---

data/bash-completion/fwupdmgr.in
data/motd/fwupd-refresh.service.in
src/fu-util.c

Correct overloaded use of --no-metadata-check

---

libfwupdplugin/fu-common.c

Fixes https://github.com/fwupd/fwupd/issues/2676

Do not use the Block.HintSystem boolean for ESP filtering

---

plugins/dfu/dfu-device.c
plugins/dfu/dfu-target.c

Perhaps fixes https://github.com/fwupd/fwupd/discussions/2687

dfu: Retry the GET_STATUS is DNLOAD_BUSY is returned

---

plugins/elantp/elantp.quirk

Add new HWID for Lenovo X13 Yoga Gen 2

elantp: Add new HWID for Lenovo X13 Yoga Gen 2.

---

plugins/rts54hid/fu-rts54hid-device.c

fixed rts54hid get report index error
Signed-off-by: Ricky Wu <Ricky_wu@realtek.com>

plugins: rts54hid fix get report index error

---

plugins/elantp/elantp.quirk

elantp: Add new HWID for Lenovo X13 Gen 2.

---

plugins/rts54hub/rts54hub.quirk

Signed-off-by: RickyWu <ricky_wu@realtek.com>
- [* ] Feature

plugins: rts54hub: add Lenovo HotRod VID/PID

---

plugins/hailuck/fu-hailuck-bl-device.c
plugins/hailuck/fu-hailuck-bl-device.h
plugins/hailuck/fu-hailuck-kbd-device.c
plugins/hailuck/fu-hailuck-kbd-device.h
plugins/hailuck/fu-hailuck-kbd-firmware.c
plugins/hailuck/fu-hailuck-kbd-firmware.h
plugins/hailuck/fu-hailuck-tp-device.c
plugins/hailuck/fu-hailuck-tp-device.h
plugins/hailuck/hailuck.quirk

The vendor is Hailuck as in one word, not Hai Luck.

hailuck: trivial: Fix the GType name

---

libfwupd/meson.build
libfwupdplugin/meson.build

Respect the -Ddefault_library meson define.

Do not hardcode building shared libraries

---

contrib/fwupd.spec.in
meson.build
plugins/meson.build
plugins/pixart-rf/README.md
plugins/pixart-rf/fu-plugin-pixart-rf.c
plugins/pixart-rf/fu-pxi-device.c
plugins/pixart-rf/fu-pxi-device.h
plugins/pixart-rf/fu-pxi-firmware.c
plugins/pixart-rf/fu-pxi-firmware.h
plugins/pixart-rf/meson.build
plugins/pixart-rf/pixart-rf.quirk

Add plugin to update PixArt RF devices

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fu-ihex-firmware.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/fwupdplugin.map
plugins/ccgx/fu-ccgx-firmware.c

Do not show unprintable chars from invalid firmware in the logs

---

contrib/fwupd.spec.in
docs/hsi.xml
libfwupd/fwupd-security-attr-private.h
meson.build
meson_options.txt
plugins/meson.build
plugins/uefi-pk/README.md
plugins/uefi-pk/fu-plugin-uefi-pk.c
plugins/uefi-pk/meson.build
src/fu-security-attr.c

Fixes https://github.com/fwupd/fwupd/issues/2695

Check the AMI test key if not installed for HSI-1

---

docs/hsi.xml
libfwupdplugin/README.md
libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fwupdplugin.map
plugins/acpi-dmar/fu-plugin-acpi-dmar.c
plugins/cpu/fu-plugin-cpu.c
plugins/msr/fu-plugin-msr.c
plugins/pci-bcr/fu-plugin-pci-bcr.c
plugins/pci-mei/fu-plugin-pci-mei.c

Detect the AMD TSME encryption state for HSI

---

libfwupd/fwupd-client-sync.c
libfwupd/fwupd-client.c
src/fu-agent.c
src/fu-tool.c
src/fu-util.c

Never iterate the global default main context

---

plugins/dfu/dfu-target-stm.c

stm-dfu: fix dnload wBlockNum wraparound

---

contrib/debian/fwupd.postinst
contrib/debian/fwupd.postrm
contrib/debian/fwupd.preinst

trivial: debian: migrate uefi->uefi_capsule in uefi.conf

---

contrib/ci/check-null-false-returns.py
contrib/ci/fedora.sh
plugins/dfu/dfu-device.c
plugins/dfu/dfu-tool.c
plugins/thunderbolt/fu-thunderbolt-firmware.c
plugins/wacom-usb/fu-wac-common.c

Check the return values of g_return_val_if_fail() in CI

---

contrib/ci/build_windows.sh
contrib/ci/centos.sh
contrib/ci/fedora.sh
contrib/fwupd.spec.in
meson.build
meson_options.txt
plugins/meson.build

trivial: Rename the meson option for plugin_synaptics_mst

---

src/fu-util-common.c

trivial: Show the translated update state in fwupdmgr

---

libfwupdplugin/fu-chunk.h
plugins/dell-dock/fu-dell-dock-i2c-ec.h
src/fu-systemd.c

trivial: Remove excess #include

---

libfwupdplugin/fu-archive.c
libfwupdplugin/fu-common.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/meson.build
meson.build
meson_options.txt
src/meson.build

Make libarchive optional for fuzzing

---

contrib/ci/check-null-false-returns.py
plugins/superio/fu-superio-device.c

And fix up the rather disapointing single place we got it wrong...

Make the null-false-returns script also process return type

---

src/fu-util-common.c

trivial: Show the device branch in fwupdmgr

---

plugins/flashrom/fu-flashrom-device.c

Added AC flag

---

plugins/dfu/README.md
plugins/dfu/dfu-device.c

dfu: Allow quirking the target transfer size

---

.lgtm.yml

trivial: add python3-gi-cairo to lgtm depends

---

libfwupd/fwupd-client-private.h
libfwupd/fwupd-client.c

Allow allow downloading from a list of possible URLs

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fu-self-test.c
libfwupdplugin/fwupdplugin.map

trivial: Add fu_common_uri_get_scheme() for future use

---

src/fu-engine.c

trivial: Do not fallback if reading from <artifact>

---

libfwupdplugin/fu-chunk-private.h
libfwupdplugin/fu-chunk.c

trivial: Allow building FuChunk objects from a XbNode

---

contrib/debian/control.in
contrib/firmware_packager/install_dell_bios_exe.py

helper scripts run.
Fixes: #2836

trivial: Make it easier to know what packages to install to let

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fwupdplugin.map
plugins/cros-ec/fu-cros-ec-usb-device.c
plugins/fastboot/fu-fastboot-device.c
plugins/hailuck/fu-hailuck-bl-device.c
plugins/optionrom/fu-rom.c
plugins/rts54hub/fu-rts54hub-device.c
plugins/superio/fu-superio-it89-device.c

See https://mail.gnome.org/archives/desktop-devel-list/2021-February/msg00000.html
for more details.

Add fu_memdup_safe()

---

snap/hooks/install

only copy files in hook if directory exists (Fixes: #2619)

---

plugins/bcm57xx/fu-bcm57xx-recovery-device.c

bcm57xx: Fix -Wcast-align issues spotted by clang

---

.github/workflows/main.yml
README.md
contrib/ci/oss-fuzz.py
libfwupdplugin/README.md
libfwupdplugin/fu-firmware-common.c
libfwupdplugin/fu-firmware-common.h
libfwupdplugin/fu-ihex-firmware.c
libfwupdplugin/fu-srec-firmware.c
libfwupdplugin/fwupdplugin.map
plugins/ccgx/fu-ccgx-firmware.c
plugins/dfu/dfu-device.c
plugins/hailuck/meson.build
plugins/jabra/fu-jabra-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.c
plugins/vli/fu-vli-usbhub-msp430-device.c
plugins/wacom-usb/fu-wac-firmware.c

Integrate oss-fuzz with the CI

---

plugins/csr/fu-csr-device.c
plugins/elantp/fu-elantp-i2c-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-peripheral.c
plugins/solokey/fu-solokey-device.c
plugins/synaptics-rmi/fu-synaptics-rmi-device.c
plugins/synaptics-rmi/fu-synaptics-rmi-v5-device.c
plugins/synaptics-rmi/fu-synaptics-rmi-v6-device.c
plugins/synaptics-rmi/fu-synaptics-rmi-v7-device.c
plugins/uefi-capsule/fu-uefi-common.c
plugins/vli/fu-vli-device.c
plugins/vli/fu-vli-pd-device.c
plugins/vli/fu-vli-usbhub-rtd21xx-device.c
plugins/wacom-raw/fu-wacom-aes-device.c
plugins/wacom-raw/fu-wacom-emr-device.c
plugins/wacom-usb/fu-wac-device.c

csr: Be more safe when reading firmware from the device

---

libfwupdplugin/fu-common.c

trivial: fu-common: fix fallback

---

libfwupdplugin/fu-dfuse-firmware.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30813

dfu: Do not allow DfuSe chunk data to include the DFU footer area

---

plugins/uefi-capsule/efi/generate_binary.py

The objcopy tool only has support for pei-x86_64 and pei-i386 targets, and
so trying to add a .sbat section for fwupdaa64.efi fails with this error:
objcopy: plugins/uefi-capsule/efi/fwupdaa64.efi: file format not recognized
To fix this issue, add the .sbat section to the ELF fwup.so shared object
and keep that section when generating the resulting fwupdaa64.efi binary.

uefi-capsule: Fix objcopy failing to add a .sbat section on aarch64

---

plugins/ccgx/fu-ccgx-firmware.c

ccgx: Fix division by zero for invalid firmware

---

libfwupdplugin/fu-srec-firmware.c

srec: Fix an overflow causing an infinite loop when parsing

---

plugins/ccgx/fu-ccgx-firmware.c

ccgx: Check for FPE when parsing the metadata section

---

libfwupdplugin/fu-firmware.c
libfwupdplugin/fu-firmware.h
libfwupdplugin/fu-smbios.c
libfwupdplugin/fwupdplugin.map
plugins/ccgx/fu-ccgx-dmc-firmware.c
plugins/ccgx/fu-ccgx-firmware.c
plugins/ebitdo/fu-ebitdo-firmware.c
plugins/vli/fu-vli-pd-firmware.c
plugins/vli/fu-vli-usbhub-firmware.c

A few plugins need this now, so move it into the base class.

Add fu_firmware_set_version_raw()

---

src/fu-backend.c
src/fu-backend.h
src/fu-engine.c

Do not fail to start the daemon for a single backend setup failure

---

plugins/pixart-rf/README.md
plugins/pixart-rf/fu-pxi-device.c
plugins/pixart-rf/pixart-rf.quirk

plugins: pixart: changed GUID and README

---

.github/workflows/main.yml

trivial: allow 1_4_X to trigger CI builds from Github workflows

---

plugins/pixart-rf/pixart-rf.quirk

pixart: Fix more supported PID

---

contrib/ci/arch.sh
contrib/ci/debian.sh
contrib/ci/fedora.sh

some of these might not be present if the containers got out of
sync.  it will be a no-op at worst.

trivial: install any missing dependencies in containers

---

plugins/pixart-rf/pixart-rf.quirk

Chicony Cheetos firmware update successfully in pixart-rf

Add cheetos quirk in pixart-rf

---

libfwupdplugin/fu-common.c

Fixes https://github.com/fwupd/fwupd/issues/2916

Convert MBR types to GPT GUIDs to help find the ESP

---

plugins/rts54hub/fu-rts54hub-rtd21xx-device.c

Test rts54hub rtd21xx

---

plugins/synaptics-rmi/fu-synaptics-rmi-ps2-device.c

synaptics-rmi: Read the PDT by calling the correct setup function

---

data/device-tests/devices/hyper-no-sku-vli-tier1.json
data/device-tests/devices/hyper-no-sku-vli-tier3.json

Updated link to Hyper fw test files on LVFS, per discussion in #2806.

vli:fw fix to LVFS

---

plugins/synaptics-rmi/fu-synaptics-rmi-device.c
plugins/synaptics-rmi/fu-synaptics-rmi-device.h
plugins/synaptics-rmi/fu-synaptics-rmi-ps2-device.c

Add a function to access private member variable to let it be modified in ps2 flow
- [ V ] Code fix

Add a function to access private member variable to let it be modified

---

plugins/superio/fu-superio-device.c
plugins/superio/fu-superio-device.h
plugins/superio/fu-superio-it85-device.c
plugins/superio/fu-superio-it89-device.c

superio: Simplify device setup using the parent_class

---

po/POTFILES.in

Update POTFILES.in 210227

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-plugin.c
plugins/thunderbolt/fu-thunderbolt-firmware.c

thunderbolt: if doing disconnected update flow, lie about the version

---

src/fu-engine.c

I broke this when adding test_ble.
Fixes https://github.com/fwupd/fwupd/discussions/2963

Fix the HSI plugin 'Disabled' state

---

plugins/flashrom/flashrom.quirk
plugins/pci-bcr/fu-plugin-pci-bcr.c
plugins/superio/superio.quirk

Updated StarLabs GUIDs + Merge "wip/hughsie/pci-bcr-mk4"

---

plugins/pixart-rf/fu-pxi-device.c

pixart: Filter the wrong report ID

---

plugins/ccgx/fu-ccgx-firmware.c

This much improves fuzzing performance.

ccgx: Allow ignoring CCGX firmware checksum failures

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fwupdplugin.map

Add missing uint64 read and write helpers

---

plugins/dell-dock/fu-dell-dock-i2c-ec.c

This may be used in the future for other expansion and determination.

trivial: dell-dock: Save the base type in private structure

---

data/device-tests/devices/lenovo-GX90T33021-vli-tier1.json
plugins/vli/vli-usbhub-lenovo.quirk

Addressing #2941: ODM changed U2 PID of Lenovo 1in3 Hub. Added in json test linked to LVFS.

vli:ODM changed U2 pid, add json test

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fu-self-test.c
libfwupdplugin/fwupdplugin.map

trivial: Add fu_common_align_up() for future usage

---

plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c

synaptics-rmi: Never create a zero-sized v10 container

---

src/fu-tool.c

Some fixups for Thunderbolt

---

plugins/solokey/fu-solokey-firmware.c
src/fuzzing/firmware/solokey.json
src/fuzzing/solokey.builder.xml

solokey: Add support for writing firmware

---

plugins/pixart-rf/fu-pxi-device.c

pixart: keep logical_id as HID_UNIQ

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fwupdplugin.map

trivial: Add fu_byte_array_align_up() for future usage

---

plugins/cros-ec/fu-cros-ec-usb-device.c

cros-ec: Fix up some uses of GError

---

plugins/pixart-rf/fu-pxi-firmware.c

pixart: Call finalize() on FuFirmware to avoid leaking

---

plugins/cros-ec/fu-cros-ec-usb-device.c

The RO partition's USB endpoint has been observed to occasionally hiccup
(usb disconnect and reenumeration) upon reboot and initial attach, causing a
failure to update a section. Rather that making this fatal, let's set
ANOTHER_WRITE_REQUIRED and allow us to handle the new USB device after
this event.
fixes #3012

cros-ec: Allow a failure to write a section, do another write

---

libfwupdplugin/fu-srec-firmware.c

Fixes https://oss-fuzz.com/testcase-detail/5468114109202432

srec: Detect overflow to avoid adding ~4GB of 0xFF padding

---

plugins/pixart-rf/fu-pxi-device.c

pixart: Add check result in fw upgrade response

---

src/fu-main.c

trivial: Use g_memdup2() for newer GLib versions

---

plugins/spi/fu-ifd-firmware.c

spi: Only show the flash_master output when debugging

---

contrib/qubes/src/qubes_fwupd_update.py
contrib/qubes/src/qubes_fwupdmgr.py
contrib/qubes/src/vms/fwupd_usbvm_validate.py
data/org.freedesktop.fwupd.metainfo.xml
libfwupd/fwupd-client.c
libfwupd/fwupd-release.c
libfwupdplugin/README.md
libfwupdplugin/fu-bluez-device.c
libfwupdplugin/fu-device.c
meson.build
plugins/hailuck/fu-hailuck-bl-device.c
plugins/logitech-hidpp/README.md
plugins/pixart-rf/README.md
plugins/redfish/README.md
plugins/spi/README.md
plugins/superio/README.md
plugins/uefi-capsule/fu-plugin-uefi-capsule.c
src/scripting.txt

trivial: Codespell fixes

---

libfwupd/fwupd-common.c
libfwupd/meson.build
libfwupdplugin/fu-common.c
libfwupdplugin/fu-efivar.c
libfwupdplugin/fu-udev-device.c
libfwupdplugin/meson.build
meson.build
src/fu-engine.c
src/fu-main.c
src/fu-self-test.c

Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>

fwupd port for BSD distros

---

plugins/spi/fu-efi-firmware-volume.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32249

spi: Fix a oss-fuzz detected critical warning

---

src/fu-bluez-backend.c

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1933838

Do not timeout when bluez fails to start

---

plugins/pixart-rf/fu-pxi-device.c

pixart: Modify ota retransmit flow

---

src/fu-engine.c
src/fu-util-common.c

Add four new category types for new firmware to use

---

src/fu-common-cab.c
src/fu-engine.c
src/fu-self-test.c

Fix using a very new libxmlb with a very old fwupd daemon

---

plugins/synaptics-cxaudio/fu-synaptics-cxaudio-device.c

synaptics-cxaudio: Retry GetReport to fix an enumeration failure

---

src/fu-engine.c

Do not show an invalid warning when the vendor-id requirement failed

---

src/fu-util.c

Some users are enabling updates-testing and then wondering why there are no more
firmware updates available. It appears after a 'fwupdmgr refresh' but that's
not obvious to end users who don't know about how this stuff is built.

Offer the user to refresh after enabling

---

plugins/pixart-rf/fu-pxi-device.c

pixart-rf: Retry the SetReport after a successfull firmware update

---

plugins/wacom-raw/fu-wacom-aes-device.c
plugins/wacom-raw/fu-wacom-device.c
plugins/wacom-raw/fu-wacom-device.h
plugins/wacom-raw/fu-wacom-emr-device.c

wacom-raw: Fix an impossible to hit overflow

---

src/fu-util.c

Although a 4-state question encodes all the possibilities entirely correctly,
it's not easy for end users to understand. Replace the 2x2 logic by two boolean
questions.
This also has the advantage that we only offer to make the upload automatic if
the initial upload actually succeeded.

Simplify asking the user about reviews

---

libfwupdplugin/fu-common-version.c
libfwupdplugin/fu-common-version.h
libfwupdplugin/fu-plugin.c
libfwupdplugin/fu-plugin.h
libfwupdplugin/fwupdplugin.map

We bumped soversion, so lets clean up the API.

trivial: Remove more deprecated API because we can

---

plugins/uefi-capsule/efi/crt0/crt0-efi-aarch64.S
plugins/uefi-capsule/efi/crt0/crt0-efi-arm.S
plugins/uefi-capsule/efi/crt0/meson.build
plugins/uefi-capsule/efi/generate_binary.py
plugins/uefi-capsule/efi/lds/elf_aarch64_efi.lds
plugins/uefi-capsule/efi/lds/elf_arm_efi.lds
plugins/uefi-capsule/efi/lds/elf_ia32_efi.lds
plugins/uefi-capsule/efi/lds/elf_x86_64_efi.lds
plugins/uefi-capsule/efi/meson.build

1_5_X: Backport sbat fixes from master for armhf

---

plugins/uefi/efi/crt0/crt0-efi-aarch64.S
plugins/uefi/efi/crt0/crt0-efi-arm.S
plugins/uefi/efi/crt0/meson.build
plugins/uefi/efi/generate_binary.py
plugins/uefi/efi/lds/elf_aarch64_efi.lds
plugins/uefi/efi/lds/elf_arm_efi.lds
plugins/uefi/efi/lds/elf_ia32_efi.lds
plugins/uefi/efi/lds/elf_x86_64_efi.lds
plugins/uefi/efi/meson.build

1_2_X: Backport sbat fixes from master for armhf

---

contrib/ci/ubuntu.sh
plugins/uefi/efi/crt0/crt0-efi-aarch64.S
plugins/uefi/efi/crt0/crt0-efi-arm.S
plugins/uefi/efi/crt0/meson.build
plugins/uefi/efi/generate_binary.py
plugins/uefi/efi/lds/elf_aarch64_efi.lds
plugins/uefi/efi/lds/elf_arm_efi.lds
plugins/uefi/efi/lds/elf_ia32_efi.lds
plugins/uefi/efi/lds/elf_x86_64_efi.lds
plugins/uefi/efi/meson.build

1_4_X: Backport sbat fixes from master for armhf

---

contrib/ci/ubuntu.sh
plugins/uefi/efi/crt0/crt0-efi-aarch64.S
plugins/uefi/efi/crt0/crt0-efi-arm.S
plugins/uefi/efi/crt0/meson.build
plugins/uefi/efi/generate_binary.py
plugins/uefi/efi/lds/elf_aarch64_efi.lds
plugins/uefi/efi/lds/elf_arm_efi.lds
plugins/uefi/efi/lds/elf_ia32_efi.lds
plugins/uefi/efi/lds/elf_x86_64_efi.lds
plugins/uefi/efi/meson.build

1_3_X: Backport sbat fixes from master for armhf

---

data/device-tests/devices/bizlink-no-sku-vli-tier1.json
data/device-tests/devices/bizlink-no-sku-vli-tier3.json

Uploaded fix to lvfs and updated json files. 
Minor request: the client wants their name on the device, "Vendor: BizLink Holding, Inc. (USB:0x06C4)". I'm not sure where to make this change. If you could please point me in the right direction I'll patch that request! Thanks.

vli: fix bizlink json tests

---

contrib/ci/fedora.sh
contrib/ci/flatpak.py
contrib/ci/generate_debian.py
contrib/ci/generate_dependencies.py
contrib/ci/generate_docker.py
contrib/ci/oss-fuzz.py
contrib/firmware_packager/add_capsule_header.py
contrib/firmware_packager/add_dfu_header.py
contrib/firmware_packager/firmware_packager.py
contrib/firmware_packager/install_dell_bios_exe.py
contrib/firmware_packager/simple_client.py
contrib/fix_translations.py
contrib/generate-version-script.py
contrib/qubes/src/fwupd_receive_updates.py
contrib/qubes/src/qubes_fwupd_heads.py
contrib/qubes/src/qubes_fwupd_update.py
contrib/qubes/src/qubes_fwupdmgr.py
contrib/qubes/src/vms/fwupd_common_vm.py
contrib/qubes/src/vms/fwupd_download_updates.py
contrib/qubes/src/vms/fwupd_usbvm_validate.py
contrib/qubes/test/test_qubes_fwupd_heads.py
contrib/qubes/test/test_qubes_fwupdmgr.py
contrib/standalone-installer/assets/header.py
contrib/standalone-installer/make.py
data/device-tests/hardware.py
libfwupdplugin/fu-hash.py
plugins/dfu/contrib/parse-avrdude-conf.py
plugins/uefi-capsule/efi/generate_binary.py
plugins/uefi-capsule/efi/generate_sbat.py

My thought here is that if something intentionally really doesn't match we can make an exception at that time.

Check with CI that all python code was formatted with black

---

.lgtm.yml
contrib/PKGBUILD
contrib/ci/dependencies.xml
contrib/fwupd.spec.in
plugins/uefi-capsule/make-images.py
po/test-deps
snap/snapcraft.yaml

This allows us to drop a build-time dep.

Write BMP data directly without using PIL

---

.github/workflows/main.yml

trivial: ci: don't run no-commit-to-branch during merges

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fu-self-test.c
libfwupdplugin/fwupdplugin.map
plugins/uefi-dbx/fu-efi-image.c

Fixes https://github.com/fwupd/fwupd/issues/3122

Add fu_bytes_get_data_safe() to check for zero sized data

---

.pre-commit-config.yaml

Add more things to the precommit list

---

libfwupdplugin/fu-context.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33155

trivial: Fix a small memory leak in the new FuContext code

---

contrib/ci/dependencies.xml
libfwupdplugin/fu-ihex-firmware.c
libfwupdplugin/fu-ihex-firmware.h
libfwupdplugin/fwupdplugin.map

Add fu_ihex_firmware_set_padding_value() for the analogix plugin

---

plugins/intel-spi/fu-intel-spi-device.c
plugins/wacom-raw/fu-wacom-aes-device.c

intel-spi: Fix compile error when errno is not available

---

meson.build
meson_options.txt
plugins/uefi-capsule/meson.build

A few tweaks to improve cross-compilation.

Cross-compile improvements

---

plugins/flashrom/fu-flashrom-lspcon-i2c-spi-device.c

Re-read the flag and version flash regions after an update to get the new device status.
Type of pull request: Code fix

flashrom: lspcon-i2c-spi: add reload method

---

meson.build
src/fu-tool.c

Fixes https://github.com/fwupd/fwupd/issues/3019

Use an OFD lock to prevent more than one fwupdtool process

---

src/fu-bluez-backend.c

If blues takes longer than 1500ms to successfully start, then we will call
fu_bluez_backend_connect_cb() with a freed FuBluezBackendHelper.
Hopefully fixes https://bugzilla.redhat.com/show_bug.cgi?id=1949491

Cancel the GDBusObjectManager operation to fix a potential crash

---

plugins/flashrom/fu-flashrom-lspcon-i2c-spi-device.c

https://review.coreboot.org/c/flashrom/+/51967 has not landed yet nor
the equivalent change in Chromium OS flashrom fork. This revert fixes
the breakage until that happens.
Type of pull request: Code fix

REVERT: flashrom/lspcon: avoid parsing sysfs paths

---

.github/workflows/main.yml

trivial: Hard limit the fuzz duration to 10 minutes

---

src/fu-util-common.c

trivial: Clarify a confusing error message

---

plugins/uefi-capsule/fu-uefi-common.c

Parse ID_LIKE according to 'man os-release':
"A space-separated list of operating system identifiers in the same
syntax as the ID= setting"

Fix /etc/os-release ID_LIKE field parsing

---

plugins/pixart-rf/pixart-rf.quirk

Add Cheetos mouse vendor & product id in pixart-rf qurik

Add cheetos mouse quirk in pixart-rf

---

src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

trivial: Add an optional title to fu_util_warning_box()

---

libfwupd/fwupd-device.c
libfwupd/fwupd-device.h
libfwupd/fwupd-enums-private.h
libfwupd/fwupd.map
libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
libfwupdplugin/fu-self-test.c
src/fu-engine.c
src/fu-engine.h
src/fu-main.c

Add a composite ID that is used to identify all devices in the same physical package

---

plugins/dfu/dfu.quirk
plugins/dfu/fu-dfu-device.c

dfu: Fix up some overzealous replacement when renaming the DFU files

---

contrib/ci/build_windows.sh
contrib/ci/dependencies.xml
libfwupd/fwupd-client.c
libfwupd/meson.build
meson.build
meson_options.txt
snap/snapcraft.yaml

Use libproxy to get the system proxy setting for a given URL

---

contrib/ci/Dockerfile-fedora.in

trivial: Move the Fedora CI to a supported release

---

contrib/ci/dependencies.xml
contrib/fwupd.spec.in

trivial: Don't restart pesign in the example spec file

---

libfwupdplugin/fu-cabinet.c
libfwupdplugin/fu-self-test.c

Fixes the other half of https://github.com/fwupd/fwupd/issues/3193

Support source artifact resources

---

libfwupd/fwupd-client.c

The call to g_proxy_resolver_get_default() is (transfer none) and so unref'ing
it causes GLib to get very upset. Also, move it to be per-FwupdClient rather
than per-request as it can be expensive to call in the PAC-runner case.

Fix a critical warning when downloading files

---

.circleci/config.yml

trivial: move circleci for windows build to fedora 33

---

plugins/upower/fu-plugin-upower.c

Fixes https://github.com/fwupd/fwupd/issues/3236

Do not prevent firmware updates on desktop hardware

---

libfwupdplugin/fu-srec-firmware.c
libfwupdplugin/fu-srec-firmware.h
libfwupdplugin/fwupdplugin.map
libfwupdplugin/meson.build

trivial: Make FuSrecFirmwareRecord usable from non-C languages

---

meson.build

Trivial changes to rework the MM plugin dependencies.

Fix dependencies of the ModemManager plugin

---

libfwupd/fwupd-client.c

This allows us to punt some smaller files onto the CDN.

Follow HTTP 3XX redirects when downloading files

---

plugins/rts54hub/fu-plugin-rts54hub.c
plugins/rts54hub/fu-rts54hub-rtd21xx-background.c
plugins/rts54hub/fu-rts54hub-rtd21xx-background.h
plugins/rts54hub/fu-rts54hub-rtd21xx-device.c
plugins/rts54hub/fu-rts54hub-rtd21xx-device.h
plugins/rts54hub/fu-rts54hub-rtd21xx-foreground.c
plugins/rts54hub/fu-rts54hub-rtd21xx-foreground.h
plugins/rts54hub/meson.build
plugins/rts54hub/rts54hub.quirk

Original code by Ricky Wu <ricky_wu@realtek.com>

rts54hub: Allow updating the RTD21xx devices in background mode

---

plugins/cpu/meson.build

Do not build fwupdcethelper if noinline,noclone fails

---

src/fu-tool.c

Some actions like firmware-parse should not need an OFD lock.

Only lock fwupdtool when loading the engine

---

libfwupdplugin/fu-context.c
plugins/upower/fu-plugin-upower.c

trivial: Fix critical warning when running fwupd as non-root

---

libfwupdplugin/fu-i2c-device.c
libfwupdplugin/fu-i2c-device.h
libfwupdplugin/fu-udev-device.c
libfwupdplugin/fwupdplugin.h
libfwupdplugin/fwupdplugin.map
libfwupdplugin/meson.build

Add a FuI2cDevice to abstract I²C devices

---

libfwupdplugin/fu-smbios.c
meson.build

Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>

fu-smbios.c: Add kenv support

---

plugins/pixart-rf/fu-pxi-device.c

pixart-rf: Fix uuid naming way

---

plugins/test/meson.build

Fixes https://github.com/fwupd/fwupd/issues/3272

trivial: Fix build failure of missing fu-hash.h

---

libfwupd/fwupd-common.c

Signed-off-by: Sergii Dmytruk <sergii.dmytruk@3mdeb.com>

Don't fail if memfd_create() is not available

---

src/fu-util.c

trivial: Fix a compile warning when there is no polkit

---

plugins/ata/ata.quirk
plugins/nvme/nvme.quirk

Add needs-shutdown flag for Kingston VID, remove wrong Kingston OUI

---

data/device-tests/devices/8bitdo-nes30pro.json
data/device-tests/devices/8bitdo-sf30pro.json
data/device-tests/devices/8bitdo-sfc30.json
data/org.freedesktop.fwupd.metainfo.xml
plugins/ebitdo/README.md
plugins/ebitdo/fu-ebitdo-device.c

trivial: Use new 8BitDo name

---

subprojects/gusb.wrap
subprojects/libjcat.wrap
subprojects/libxmlb.wrap

This gets us FreeBSD support for all the deps.

Update the subprojects to the latest released versions

---

src/fu-engine.c

Now we can flash firmware on FreeBSD this is important to collect.

Add the KernelName to the report metadata

---

plugins/vli/meson.build
plugins/vli/vli-usbhub-minibons.quirk

Added VID PID for Minibons device

---

plugins/vli/vli-usbhub-minibons.quirk

Set hub2.0 as subcomponent of hub3.0

---

plugins/ebitdo/ebitdo.quirk
plugins/ebitdo/fu-ebitdo-device.c

Add 8BitDo SN30v2 gamepad.

---

plugins/ebitdo/ebitdo.quirk
plugins/ebitdo/fu-ebitdo-device.c

Add 8BitDo SN30 for Android

---

plugins/ebitdo/ebitdo.quirk
plugins/ebitdo/fu-ebitdo-device.c

The v2.00 firmware of this sn30 pro for android has changed the PID.

Add SN30 Pro for Android firmware v2.00

---

contrib/ci/check-abi
libfwupd/fwupd-common.h
libfwupd/fwupd-enums-private.h
libfwupd/fwupd-enums.h
libfwupd/fwupd-security-attr-private.h

These help the gtk-doc documentation as well.

Short term documentation improvements

---

contrib/vscode/build.sh
contrib/vscode/launcher.sh
plugins/dell-dock/README.md
plugins/dell-dock/dell-dock.quirk
plugins/dell-dock/fu-dell-dock-i2c-ec.c
plugins/dell-dock/fu-dell-dock-i2c-ec.h
plugins/dell-dock/fu-plugin-dell-dock.c

TODO:
1. Update Dock EC lowest version from development to production
2. Upcoming commit to add support for firmware update over USB protocol

Add support for USB4 module in dell dock

---

contrib/ci/oss-fuzz.py
libfwupdplugin/fu-backend.c
libfwupdplugin/fu-backend.h
libfwupdplugin/fu-common-freebsd.c
libfwupdplugin/fu-common-linux.c
libfwupdplugin/fu-common-private.h
libfwupdplugin/fu-common-windows.c
libfwupdplugin/fu-common.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/fwupdplugin.map
libfwupdplugin/meson.build
plugins/uefi-capsule/fu-plugin-uefi-capsule.c
plugins/uefi-capsule/fu-self-test.c
plugins/uefi-capsule/fu-uefi-backend-freebsd.c
plugins/uefi-capsule/fu-uefi-backend-linux.c
plugins/uefi-capsule/fu-uefi-backend.h
plugins/uefi-capsule/fu-uefi-tool.c

Based on a patch by Sergii Dmytruk <sergii.dmytruk@3mdeb.com>
Closes #3316

Make fu_common_convert_to_gpt_type() FreeBSD compatible

---

data/remotes.d/meson.build

trivial: Include the LVFS remotes for the standalone build too

---

contrib/ci/Dockerfile-arch.in

trivial: Fix dockerfile for Arch (Closes: #3296)

---

README.md

trivial: switch from Travis badge to Github badge

---

contrib/ci/Dockerfile-arch.in

trivial: fixup Dockerfile for arch

---

plugins/synaptics-prometheus/synaptics-prometheus.quirk

synaptics-prometheus: add pid 0xd8 0xf0 0x103 to quirk file

---

src/fu-engine.c

Fix vendor-directory remotes for firmware with an <artifact> section

---

plugins/logitech-hidpp/fu-logitech-hidpp-device.c

logitech-hidpp: fix bug in type casting

---

libfwupdplugin/fu-dfu-firmware-private.h
libfwupdplugin/fu-dfu-firmware.c
libfwupdplugin/fu-dfu-firmware.h
libfwupdplugin/fu-dfuse-firmware.c
plugins/dfu/fu-dfu-device.c
plugins/dfu/fu-dfu-target.c

trivial: Export the DFU version constants into libfwupdplugin

---

plugins/logitech-hidpp/fu-logitech-hidpp-runtime-unifying.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime-unifying.h
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.h
plugins/logitech-hidpp/fu-plugin-logitech-hidpp.c
plugins/logitech-hidpp/logitech-hidpp.quirk
plugins/logitech-hidpp/meson.build

logitech-hidpp: make receiver runtime class derivable

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-self-test.c

trivial: Fix the FuDeviceInternalFlags conversion funcs

---

RELEASE
docs/fwupd.toml.in
docs/fwupdplugin.toml.in
docs/meson.build
meson.build
subprojects/gi-docgen.wrap

trivial: Add details into RELEASE process for forking stable branches

---

plugins/wacom-usb/fu-plugin-wacom-usb.c
plugins/wacom-usb/fu-wac-android-device.c
plugins/wacom-usb/fu-wac-android-device.h
plugins/wacom-usb/meson.build
plugins/wacom-usb/wacom-usb.quirk

wacom-usb: Show the user how to switch out of Android-mode

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-quirks.c
libfwupdplugin/fu-quirks.h

trivial: Allow setting device inhibits from quirk files

---

meson.build

Fix FreeBSD regression

---

plugins/superio/README.md

Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
- [X ] Documentation

superio/README.md: fix typo

---

.github/workflows/main.yml
.pre-commit-config.yaml
contrib/ci/oss-fuzz.py
contrib/codespell.cfg
contrib/generate-version-script.py
libfwupdplugin/fu-device.c
libfwupdplugin/fu-hash.py
meson.build
plugins/uefi-capsule/make-images.py

Move codespell to pre-commit

---

contrib/ci/check-headers.py
plugins/dfu/fu-dfu-device.c
plugins/dfu/fu-dfu-target-avr.c
plugins/dfu/fu-dfu-target-stm.c
plugins/dfu/fu-dfu-target.c

Rabbit hole of docgen changes

---

libfwupdplugin/fu-common.c

trivial: fix for expr check introduced in 3a48af58

---

libfwupdplugin/fu-usb-device.c
plugins/vli/fu-vli-device.c
plugins/vli/fu-vli-device.h
plugins/vli/fu-vli-usbhub-device.c

trivial: Show the USB class code when debugging

---

contrib/fwupd.spec.in
data/meson.build
data/power.quirk
plugins/upower/fu-plugin-upower.c
plugins/upower/meson.build
plugins/upower/upower.conf

Move power quirk out of upower

---

plugins/dell-dock/dell-dock.quirk
plugins/dell-dock/fu-dell-dock-common.h
plugins/dell-dock/fu-dell-dock-usb-usb4.c
plugins/dell-dock/fu-dell-dock-usb-usb4.h
plugins/dell-dock/fu-plugin-dell-dock.c
plugins/dell-dock/meson.build

dell-dock: add usb protocol for USB4 device

---

.github/ISSUE_TEMPLATE/bug-report-wd19.md

The WD19 has a special bug report template, and although I'll contribute
what I can to it, nominally Crag will be looking into the issues now.

trivial: update assignee for wd19 bug reports

---

src/fu-install-task.c

Fixes https://github.com/fwupd/fwupd/issues/3402

trivial: Always use the node cache when getting releases

---

README.md

trivial: add a badge for circle CI

---

plugins/uefi-capsule/fu-uefi-backend-linux.c

trivial: remove some unused variables

---

src/fu-util-common.c

This will make it easier to stand out when there is a problem.  

trivial: fu-util-common: output UpdateError in red

---

src/fu-util-common.c

trivial: Display multiple vendors IDs more clearly

---

plugins/linux-swap/meson.build

trivial: Do not run the linux swap tests on win32

---

plugins/dell-dock/README.md
plugins/dell-dock/dell-dock.quirk
plugins/dell-dock/fu-dell-dock-common.h
plugins/dell-dock/fu-dell-dock-i2c-ec.c
plugins/dell-dock/fu-dell-dock-i2c-ec.h
plugins/dell-dock/fu-dell-dock-usb-usb4.c
plugins/dell-dock/fu-dell-dock-usb-usb4.h
plugins/dell-dock/fu-plugin-dell-dock.c
plugins/dell-dock/meson.build

dell-dock: add support for USB4 device

---

contrib/ci/build_freebsd_package.sh
contrib/freebsd/Makefile

trivial: Use the upstream Makefile to disable plugins for FreeBSD

---

plugins/acpi-phat/fu-acpi-phat-version-element.c
plugins/cpu/meson.build
plugins/pixart-rf/fu-pxi-receiver-device.c
plugins/pixart-rf/fu-pxi-wireless-device.c

Clang cleanups

---

plugins/acpi-phat/fu-acpi-phat-health-record.c

acpi-phat: Fix a -Wcast-align issue detected with clang

---

data/remotes.d/README.md

- [ X ] Documentation
Typo fix. vendor.conf-directory vs vendor-directory.conf.

trivial: vendor-directory typo

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fwupdplugin.map

Allow calculating the CRC-16 with the CCITT polynomial

---

plugins/rts54hub/rts54hub.quirk

add Acer Dock ID
- [*] Feature

plugins: rts54hub: update rts54hub.quirk

---

libfwupd/fwupd-device.c
libfwupd/fwupd-device.h
libfwupd/fwupd.map
libfwupdplugin/fu-device.h

trivial: Export fwupd_device_has_icon()

---

src/fu-util-common.c

trivial: Fallback to text if the multiline description was invalid XML

---

libfwupd/fwupd-enums.c
libfwupd/fwupd-enums.h
libfwupdplugin/fu-plugin.c
src/fu-util-common.c

trivial: Provide FWUPD_PLUGIN_FLAG_AUTH_REQUIRED for future usage

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
libfwupdplugin/fu-self-test.c

Fixes https://github.com/fwupd/fwupd/issues/3454

Add a flag which inhibits children automatically

---

contrib/debian/fwupd.install
contrib/fwupd.spec.in
data/builder/meson.build

Fixes https://github.com/fwupd/fwupd/issues/3464

trivial: Move the builder docs to docdir

---

libfwupdplugin/fu-device.c

trivial: Correctly show negative device order numbers

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
plugins/hailuck/fu-hailuck-tp-device.c
plugins/intel-spi/fu-ifd-device.c
plugins/pixart-rf/fu-pxi-wireless-device.c
plugins/rts54hid/fu-rts54hid-module.c
plugins/rts54hub/fu-rts54hub-rtd21xx-device.c
plugins/synaptics-prometheus/fu-synaprom-config.c

This is a common pattern that is used in lots of plugins, so move the
logic into common code.

Add a flag to open and close with the parent device

---

src/fu-device-list.c
src/fu-self-test.c

trivial: Add some sanity checks to the device list

---

src/fu-device-list.c

trivial: Always clear timeout when replacing in the devicelist

---

src/fu-progressbar.c
src/fu-progressbar.h
src/fu-util.c

We need to use the private GMainContext we created.

Fix the progressbar spinner to actually work

---

libfwupd/fwupd-device.c
src/fu-engine.c

Allow the client to watch for more property changes

---

plugins/emmc/fu-emmc-device.c

The move to query sysattr for the name inadvertently changed the extent of
devices accepted by emmc probe. udev rules setup ID_NAME only for main
block device, but not for rpmb or boot, while 'name' sysattr is present
for all of them for they point to the same parent. The original check
for name was brittle either way and relied on a side effect of udev
subsystem. This CL introduces a proper filtering check that picks up only
the main devices. That is important because an attempt to perform an
update not on the main device returns a cryptic timeout error.

emmc: Filter out rpmb and boot block devices

---

contrib/ci/oss-fuzz.py
contrib/fix_translations.py
contrib/standalone-installer/assets/header.py
plugins/uefi-capsule/make-images.py

trivial: Fix Python linting issue spotted by Codacy

---

libfwupd/fwupd-device.c
src/fu-engine.c

This means we don't get asked to submit a report.

Never write 'unknown' update state on success

---

po/POTFILES.in

Update POTFILES.in 210718

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
libfwupdplugin/fu-plugin.c
libfwupdplugin/fwupdplugin.map
plugins/uefi-capsule/fu-plugin-uefi-capsule.c
plugins/uefi-capsule/fu-uefi-bootmgr.c
plugins/uefi-capsule/fu-uefi-common.c
plugins/uefi-capsule/fu-uefi-device.c
plugins/uefi-capsule/fu-uefi-device.h
plugins/uefi-capsule/uefi-capsule.quirk

update-capsule: Move FuUefiDevice to a derivable for future use

---

src/fu-engine.c

trivial: Fix critical warning on 'fwupdtool get-details'

---

src/fu-config.c

By default the daemon start if no configuration is present, but
the first time that an fd is accessed the following error shows up:
```
A maximum read size must be specified
```
This is because the maximum archive size wasn't initialized.

trivial: let daemon work when configuration missing

---

.github/workflows/create_containers.yml
.github/workflows/main.yml
contrib/ci/Dockerfile-void.in
contrib/ci/dependencies.xml
contrib/ci/void.sh
contrib/setup

Add VOID target

---

libfwupd/fwupd-remote.c

trivial: Do not set URIs of zero length

---

libfwupdplugin/fu-cabinet.c

trivial: Ignore the NUL suffix to fix loading new firmware with old GLib versions

---

plugins/realtek-mst/README.md

realtek-mst: Add a warning that extreme caution should be used

---

libfwupd/fwupd-enums.c
libfwupd/fwupd-enums.h
plugins/synaptics-prometheus/fu-synaprom-config.c
plugins/uefi-dbx/fu-uefi-dbx-device.c
src/fu-install-task.c
src/fu-self-test.c
src/fu-util-common.c

See https://github.com/fwupd/fwupd/issues/3554 for details.

Allow devices to only accept version upgrades

---

data/fwupd.service.in
data/meson.build

redfish: Allow starting when using RestrictAddressFamilies

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-self-test.c

Sanitize the device name harder

---

src/fu-engine.c

This speeds up fu-self-test, but more importantly fixes a intermittent
'ninja check' failure when a host USB device disconnects at exactly the
wrong time.
The FuUsbBackend code is unusual in that the setup() code sets up a
context (with a thread) which takes up to 2 seconds to timeout.

trivial: Do not set up the backends if there is no coldplug

---

plugins/powerd/fu-plugin-powerd.c

This is an extension of the powerd plugin skeleton, which has not yet landed. It serves to create and destroy /run/lock/power_override/fwupd.lock, which will hold the contents of getpid () and stop the device from being suspended while the file exists. The file will be created and written just before the update is put into motion and be destroyed once the update
finishes.

Inhibit suspend upstream

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h

Fall back to the parent if the child does not have a battery level set

---

plugins/dell-dock/meson.build

Closes: https://github.com/fwupd/fwupd/issues/3598

dell-dock plugin requires gusb

---

plugins/test/fu-plugin-test.c

Based on a patch by Twain Byrnes <binarynewts@google.com>, many thanks.
Use this to test:
sudo FWUPD_TEST_PLUGIN_XML="<config><delay_decompress_ms>100</delay_decompress_ms></config>" \
./src/fwupdtool --plugins test get-devices -v

test: Allow setting plugin parameters using an environment variable

---

plugins/logitech-hidpp/fu-logitech-hidpp-common.c

trivial: Ignore NUL chars in the device version

---

libfwupdplugin/fu-io-channel.c

trivial: Allow handling EPROTO in plugins

---

.pre-commit-config.yaml
contrib/ci/check-license.py
contrib/ci/out-of-tree-link/fwupd.c
contrib/ci/out-of-tree-link/fwupdplugin.c
plugins/flashrom/fu-plugin-flashrom.c

Precommit checks for license

---

contrib/ci/check-license.py

License checker fixes

---

libfwupdplugin/fu-device.c
src/fu-install-task.c

Fixes https://github.com/fwupd/fwupd/issues/3622

Recalculate the device inhibits when the flags property changes

---

libfwupdplugin/fu-plugin.c
libfwupdplugin/fu-plugin.h
src/fu-engine.c

Fixes https://github.com/fwupd/fwupd/issues/3625

Restart the daemon if any of the the plugin config files are modified

---

.pre-commit-config.yaml
contrib/ci/arch.sh
contrib/ci/build_freebsd_package.sh
contrib/ci/build_windows.sh
contrib/ci/centos.sh
contrib/ci/debian.sh
contrib/ci/debian_s390x.sh
contrib/ci/generate_docker.py
contrib/ci/generate_news.py
contrib/ci/get_test_firmware.sh
contrib/ci/snap.sh
contrib/ci/ubuntu.sh
contrib/ci/void.sh
contrib/firmware_packager/firmware_packager.py
contrib/snap/fwupd-command
contrib/vscode/launcher.sh
meson.build
meson_post_install.sh
plugins/redfish/tests/redfish.py
plugins/uefi-capsule/fu-ucs2.c
plugins/uefi-capsule/fwupd.grub.conf.in

I was glancing at codacity and fixed a few things that stood out, and also upped shellcheck to warning.

Various shell and static analysis improvements

---

plugins/synaptics-mst/fu-synaptics-mst-common.c
plugins/synaptics-mst/fu-synaptics-mst-common.h
plugins/synaptics-mst/fu-synaptics-mst-connection.h
plugins/synaptics-mst/fu-synaptics-mst-device.c

plugin/synaptics-mst: add support for cayenne/spyder

---

plugins/dell-dock/fu-plugin-dell-dock.c

dell-dock: handle activation until both ec and usb4 devices are probed

---

plugins/dell-dock/fu-dell-dock-common.h
plugins/dell-dock/fu-plugin-dell-dock.c

dell-dock: add device GUID earlier even setup yet done

---

src/fu-engine.c

trivial: Make the 'device ID was not found' messages more helpful

---

src/fu-device-list.c

This makes devices that come back in bootloader mode with no children
timeout, which is bad UX. We don't even need the feature now that we
can WAIT_FOR_REPLUG on multiple devices now.

Do not check wait_removed as multiple devices can be WAIT_FOR_REPLUG

---

plugins/uefi-capsule/fwupd.grub.conf.in

trivial: fix the grub configuration from 684bc03

---

src/fu-security-attr.c

I mistakenly told Kate there was no existing format, but of course
there is, and it makes sense for the formats to be the same.

Use the same JSON schema in the database as the upload

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fu-quirks.c
plugins/synaptics-mst/fu-self-test.c
plugins/synaptics-mst/fu-synaptics-mst-device.c
plugins/synaptics-mst/meson.build
plugins/synaptics-mst/synaptics-mst.quirk

Fixes https://github.com/fwupd/fwupd/issues/3701

synaptics-mst: Only probe devices that have opted-in

---

libfwupd/fwupd-release.c

trivial: Add two missing properties in the JSON output

---

docs/fwupd.toml.in
docs/fwupdplugin.toml.in
docs/meson.build
docs/urlmap.js
docs/urlmap_fwupd.js
docs/urlmap_fwupdplugin.js

trivial: create urlmap for each gi-docgen target rather than sharing

---

src/fu-engine.c

trivial: Disconnect all handlers, including the generic one

---

src/fu-tool.c
src/fu-util.c

trivial: Do not update the progressbar title for the device child

---

plugins/cpu/fu-cpu-device.c

trivial: Do not use deprecated GLib API

---

plugins/wacom-usb/fu-wac-firmware.c

Some files have a newline inbetween the AB sections.

wacom-usb: Fix a false positive in real world firmware

---

contrib/ci/dependencies.xml
contrib/ci/generate_dependencies.py
contrib/ci/generate_docker.py
contrib/setup

Generate dependencies improvements

---

plugins/logitech-hidpp/fu-logitech-hidpp-radio.c

logitech-hidpp: Use accurate FuProgress steps

---

docs/env.md
docs/fwupdplugin.toml.in
docs/hsi.md
docs/tutorial.md
libfwupdplugin/fu-self-test.c
plugins/logitech-hidpp/fu-logitech-hidpp-bootloader-texas.c
plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.c
plugins/logitech-hidpp/fu-logitech-hidpp-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-hidpp.c
plugins/synaptics-cape/fu-synaptics-cape-device.c
plugins/uefi-capsule/fu-self-test.c
subprojects/gi-docgen.wrap

Fixes https://github.com/fwupd/fwupd/issues/3760

Document some of the environment variables used by fwupd

---

plugins/redfish/fu-plugin-redfish.c
plugins/redfish/meson.build

redfish: Do not hardcode the KCS user_id to be 0x4

---

meson.build
plugins/analogix/fu-analogix-device.c
plugins/cros-ec/fu-cros-ec-usb-device.c
plugins/dfu/fu-dfu-device.c
plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c

This is something that I keep being asked to do...

Lower the GUsb dep to allow compiling on RHEL-8

---

data/meson.build

trivial: Do not install the device tests when using -Dtests=false

---

src/fu-util.c

trivial: do not fallback on missing GUID lookup

---

meson.build

This change enables the use of tests in Chrome OS. Fixes #3270

trivial: workaround for ERROR: Unknown variable "gcab"

---

.circleci/config.yml
.github/workflows/main.yml
.pre-commit-config.yaml
.tx/config
README.md
RELEASE
contrib/ci/flatpak.py
docs/env.md
docs/hsi.md
plugins/README.md

Fixes https://github.com/fwupd/fwupd/issues/3799

Rename the development branch from master to main

---

plugins/thunderbolt/fu-thunderbolt-device.c

thunderbolt: fix host controller probing

---

plugins/parade-lspcon/fu-parade-lspcon-device.c
plugins/vli/fu-vli-usbhub-rtd21xx-device.c

trivial: Remove some instances of 'slave' that crept in
