- libfwupd/fwupd-enums.h
- libfwupdplugin/fu-fmap-firmware.c
This speeds up the fuzzing task from 22ms to 33us.
> trivial: Allow turning off the FMAP binary search when fuzzing

- plugins/thunderbolt/fu-thunderbolt-firmware.c
- plugins/thunderbolt/fu-thunderbolt-firmware.h
CC @westeri, @YehezkelShB
This is based upon https://git.kernel.org/pub/scm/linux/kernel/git/westeri/thunderbolt.git/commit/?h=next&id=db0746e3399ee87ee5f957880811da16faa89fb8 but I found that parsing an image I have locally it's missing an ID 
0x1136.  So I think that's got to be added to kernel still too, no?
If you can please confirm the values I selected for these IDs.  Here's how a local binary parses.
```
FuThunderboltFirmwareUpdate:
Family:                 Maple Ridge
IsHost:                 true
IsNative:               true
DeviceId:               0x1136
VendorId:               0xd4
ModelId:                0xa58
FlashSize:              0x0
Generation:             0x4
Ports:                  0x2
HasPd:                  true
Section0:               0x4000
Section1: …
```
> thunderbolt: Add maple ridge firmware parsing support

- libfwupdplugin/fu-fmap-firmware.c
- plugins/cpu/fu-plugin-cpu.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
- src/fu-self-test.c
- src/fu-tool.c
Just avoid loading SMBIOS and re-generating remotes when all we want to use is
the firmware loader. It also speeds up the self tests somewhat too.
> Allow using fwupdtool as non-root for firmware commands

- plugins/dfu/dfu-device.c
I'm not returning FALSE here as it might break plugins.
> dfu: Show a warning if we fail to release the interface

- meson.build
> trivial: Actually check if __get_cpuid_count exists before using cpuid.h

- libfwupdplugin/fu-plugin.c
- plugins/altos/fu-plugin-altos.c
- plugins/bcm57xx/fu-plugin-bcm57xx.c
- plugins/ccgx/fu-plugin-ccgx.c
- plugins/cros-ec/fu-plugin-cros-ec.c
- plugins/ebitdo/fu-plugin-ebitdo.c
- plugins/elantp/fu-plugin-elantp.c
- plugins/ep963x/fu-plugin-ep963x.c
- plugins/fresco-pd/fu-plugin-fresco-pd.c
- plugins/hailuck/fu-plugin-hailuck.c
- plugins/solokey/fu-plugin-solokey.c
- plugins/synaptics-cxaudio/fu-plugin-synaptics-cxaudio.c
- plugins/synaptics-prometheus/fu-plugin-synaptics-prometheus.c
- plugins/synaptics-rmi/fu-plugin-synaptics-rmi.c
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/vli/fu-plugin-vli.c
We can work out the correct value automatically in all cases but one, and it's
less for the plugin author to get wrong...
> Make the 'id' for fu_plugin_add_firmware_gtype() optional

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/synaptics-prometheus/fu-synaprom-device.c
- src/fu-util-common.c
The fprint daemon only keeps the device open for 5 seconds and then releases it,
which seems like a small window to hit.
But! We're asking the user to authenticate with the same device we're about to
upgrade so a different part of the stack woke up the hardware just before we're
about to deploy an update onto it.
Just wait a couple of seconds to make sure the device is idle.
Fixes https://github.com/fwupd/fwupd/issues/2650
> synaptics-prometheus: Fix flashing a fingerprint reader that is in use

- libfwupd/meson.build
This fixes:
DEPRECATION: Library fwupd was passed to the "libraries" keyword argument of
a previous call to generate() method instead of first positional argument.
Adding fwupd to "Requires" field, but this is a deprecated behaviour that
will change in a future version of Meson.
> trivial: Fix a warning generated by new versions of meson

- contrib/ci/fedora.sh
- libfwupd/README.md
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- plugins/ata/fu-ata-device.c
- plugins/flashrom/fu-plugin-flashrom.c
- plugins/logitech-hidpp/fu-logitech-hidpp-peripheral.c
- plugins/nvme/fu-nvme-device.c
- plugins/synaptics-prometheus/fu-synaprom-device.c
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
- plugins/uefi-capsule/fu-uefi-device.c
- src/fu-engine.c
- src/fu-util-common.c
That giant uint64_t isn't looking so big now, and we'll want to add even more
to it in the future. Split out some private flags that are never useful to the
client, although the #defines will have to remain until we break API again.
> Do not export useless device attributes to the client

- libfwupdplugin/fu-efi-signature-list.c
- libfwupdplugin/fu-efi-signature.h
- plugins/uefi-dbx/fu-dbxtool.c
This was changed recently in https://sourceforge.net/p/edk2/code/29270/
> uefi-dbx: Ignore the legacy OVMF dummy GUID for the version

- src/fu-util.c
If the date is wrong, the SSL certificate may not be in a valid date range and
the user gets a rather unhelpful 'SSL handshake failed' error message.
Detect the most common case and show a warning when starting fwupdmgr.
Fixes https://github.com/fwupd/fwupd/issues/2723
> Show a console warning if the system clock is not set

- plugins/uefi-capsule/uefi_capsule.conf
in ee2e2c36749298e58b34dca163ea48a7fc925da6 the plugin name was changed
from uefi to uefi_capsule. while the config file name was changed, the
section name should also be changed.
fixes #2748
> rename config section in uefi_capsule.conf to plugin name

- libfwupdplugin/fu-plugin.c
- src/fu-util-common.c
Point people towards firwmare setup instead (Fixes: #1454)
> trivial: adjust error for no UEFI capsules

- contrib/debian/rules
Fixes: #2755
Need to double check the snap and older debian/ubuntu before merging this.
> trivial: debian: fix modules-load.d directory

- .github/workflows/create_containers.yml
Just because Arch fails to build or push one day, don't
make all the containers fail to build or push.
> trivial: for create containers workflow don't fail fast

- src/fu-tool.c
- src/fu-util.c
Since we added a CPU and everything has a CPU the error stopped
showing up.
> trivial: in the no updatable devices case, show error again

- src/fu-progressbar.c
Ignore the initial client state change from UNKNOWN to IDLE which was being set
as part of the fix in fb36f22.
Fixes https://github.com/fwupd/fwupd/issues/2766
> Do not show Unknown [***] for every client connection

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fwupdplugin.map
- src/fu-config.c
It is impossible to choose a static default that is appropriate for both a tiny
ARM IoT device and a giant Xeon server.
Fixes https://github.com/fwupd/fwupd/issues/2760
> Use a quarter of the RAM size as the archive maximum

- plugins/altos/altos.quirk
While the firmware is altos, the product is better known as "Altus-Metrum ChaosKey".
As in, I was confused to see:
```
$ sudo fwupdmgr update
• Altos ChaosKey has the latest available firmware version
...
```
I was expecting:
```
$ sudo fwupdmgr update
• Altus-Metrum ChaosKey has the latest available firmware version
...
```
@keith-packard
> altos: Clarify ChaosKey name

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
We only convert the instance IDs to GUID after setup() has been called, which
means if we add even more instance IDs to the device in functions like
fu_plugin_device_registered() they never actually get converted to the GUID
form too.
> Add GUIDs straight away if ->setup() has already been called

- plugins/pci-bcr/fu-plugin-pci-bcr.c
If BLE is set flashrom isn't going to work and the user would get a super scary
warning.
> flashrom: Do not allow flashing if BLE is enabled

- data/bash-completion/fwupdtool.in
- libfwupdplugin/fu-hwids.c
- libfwupdplugin/fu-hwids.h
- libfwupdplugin/fwupdplugin.map
- src/fu-tool.c
This is really useful when working out HwId quirk values for remote systems.
This is similar to what ComputerHardwareIds.exe allows:
FWUPD_SMBIOS_DATA="Family=Foo|Manufacturer=Bar|ProductSku" fwupdtool hwids
> Allow overriding SMBIOS data when using fwupdtool hwids

- libfwupdplugin/fu-common-version.c
- libfwupdplugin/fu-self-test.c
Return NULL if not valid, and handle tilde and dash where required.
> Always return a valid semver from fu_common_version_ensure_semver()

- plugins/pci-bcr/fu-plugin-pci-bcr.c
It's unusual, but if BIOS lock enable is enabled (so we cannot *change* the
value of BIOSWE) but the BIOS is already WE then we can write to the hardware
just fine.
> pci-bcr: Only mark the device non-updatable if WPD unset and BLE set

- plugins/tpm-eventlog/fu-plugin-tpm-eventlog.c
Although we could reconstruct the PCRn metadata on the LVFS from the (already
included) event log, it's much more scalable if the client just provides the
data that we want to filter by.
> Add the PCRs to the report metadata

- contrib/fwupd.spec.in
- plugins/meson.build
- plugins/system76-launch/README.md
- plugins/system76-launch/fu-plugin-system76-launch.c
- plugins/system76-launch/fu-system76-launch-device.c
- plugins/system76-launch/fu-system76-launch-device.h
- plugins/system76-launch/meson.build
- plugins/system76-launch/system76-launch.quirk
This plugin supports reading the keyboard firmware version at runtime and
rebooting the keyboard to USB DFU mode. Tested with firmware uploaded to
embargo-system76.
New plugin checklist:
> system76-launch: Add a plugin for the System76 Launch Configurable Keyboard

- src/fu-tool.c
In fwupd 1.5.1 and before, we allowed ESP on external device.
From 56d816a5, (Fall back to FAT32 internal partitions for detecting
ESP, 2020-11-11), we started to only consider internal devices only.
While it would be desirable to only consider internal devices for
fallback esp partition, there're some setup that put ESP on external
device, e.g. full disk encryption with /boot on a USB.
Let's allow external ESP again.
> esp-list: allow external ESP again

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
If we're creating the child device using `Children=FuFooDevice|FOO&I2C_01` in
the quirk file then there's not actually anywhere to call FuDevice->setup()
on the child.
The logical place to do it is when we setup the parent, which is a NOP if
already called for the child. We also don't need to convert the child instance
IDs as it's already being handled during the child setup.
Tested-By: Ricky Wu <ricky_wu@realtek.com>
> Run the child setup when calling the parent device

- libfwupd/README.md
- libfwupd/fwupd-client.c
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-tool.c
The metadata might want to pass more than one location URI to the client, for
instance if the file is available from more than one HTTP mirror.
Use the noun of location to match the AppStream <artifact> naming; this is the
last place where LVFS AppStream diverges from the official specification and
it would be good to bring fwupd back into line -- although the LVFS will have
to write both elements for a very long time.
See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
Also: we're not changing the format of the `Uri` GVariant key to preserve both
forward and backwards compatibility of the library. We can remove it when we
next break API.
> libfwupd: Add fwupd_release_add_location()

- libfwupd/README.md
- libfwupd/fwupd-client-sync.c
- libfwupd/fwupd-client-sync.h
- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
- src/fu-util.c
We forgot to include FwupdClientDownloadFlags when adding the original method
fwupd_client_install_release() -- and we want to use additional download flags
for operations in the future.
> libfwupd: Add fwupd_client_install_release2_async()

- plugins/dfu/dfu-device.c
- plugins/dfu/dfu-target.c
- plugins/dfu/dfu-target.h
This is a much more standard way of doing this.
> dfu: Show the DfuTargets when calling DfuDevice->to_string()

- .github/ISSUE_TEMPLATE/bug-report-uefi.md
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
- plugins/uefi-capsule/fu-uefi-bootmgr.c
- plugins/uefi-capsule/fu-uefi-bootmgr.h
- plugins/uefi-capsule/uefi-capsule.quirk
Some systems remove the BootXXXX entry we add (so we can run fwupdx64.efi) and
thus the firmware update does not run. Most commonly this failure is seen with
Lenovo systems that call the helpful option 'Boot Order Lock'.
Hopefully when we depend on the new kernel bios interface sysfs API in we can
check in ->prepare(), not after reboot, but until that we can mark the update
failure as transient as the user can actually fix the problem themselves.
Fixes https://github.com/fwupd/fwupd/issues/2801
> uefi-capsule: Check if the fwupd BootXXXX entry exists on failure

- plugins/dfu/dfu-device.c
- plugins/dfu/dfu-target.c
- plugins/dfu/dfu.quirk
This bootloader is *weird* -- the chip ID is the first two bytes of the serial
number and the data is offset and encoded in UTF-8, not UTF-16.
The sector information is also wrong. Gah!
> dfu: Add support for GD32VF103 as found in the Longan Nano

- libfwupd/fwupd-client.c
- libfwupd/fwupd-device.c
- libfwupd/fwupd-plugin.c
- libfwupd/fwupd-release.c
- libfwupd/fwupd-remote.c
- libfwupd/fwupd-security-attr.c
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-firmware-image.c
- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-plugin.c
- plugins/dfu/dfu-target.c
Fix the asan crash when feeding the value back into itself, e.g
fu_firmware_set_version (firmware, fu_firmware_get_version (firmware));
> trivial: Fix potential crash when doing crazy things

- src/fu-util.c
> trivial: Show the fwupd_release_to_string() output when verbose

- data/daemon.conf
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
This would allow, for instance, only allowing IPFS downloads or preferring
https over http downloads.
> Allow configuring URI scheme preferences

- plugins/cros-ec/fu-cros-ec-usb-device.c
The g_usb_device_bulk_transfer() function requires a mutable 'data' buffer, but
fwupd is sending file data and never wants the buffers modified.
> cros-ec: Make _do_xfer() outbuf const

- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-firmware.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
This allows a plugin to define a 'set' of firmwares that it would find
acceptable, for instance either accepting DFU, DfuSe or just a plain binary.
> Add fu_firmware_new_from_gtypes() for future usage

- src/fu-engine.c
If any update is scheduled for SuperIO, and something changes (such as entering
S3, disconnecting the charger) before the update is installed, then the update
will get stuck.
Fixes https://github.com/fwupd/fwupd/issues/2830
> Clear the pending flag if restarting the system

- contrib/firmware_packager/install_dell_bios_exe.py
uefi was renamed to uefi-capsule and now this script forgot the change.
Allow both to work so this script runs on new or older fwupd.
Fixes: #2840
> trivial: contrib/install_dell_bios_exe.py: recognize the plugin rename

- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
This is much easier to parse on the LVFS.
Fixes https://github.com/fwupd/fwupd/issues/2834
> uefi-capsule: Use an integer for EfivarNvramUsed

- contrib/ci/oss-fuzz.py
See https://gitlab.gnome.org/GNOME/json-glib/-/commit/7711cbc7f8d85d909bd4ccaa0c4c0f8d306f872f
> trivial: Use json-glib from master to get a fuzzing crash fix

- libfwupdplugin/fu-udev-device.c
fu_udev_device_ioctl() interprets the return value of ioctl() as the
error cause and generates a misleading error message (permission
denied).
Fix it to use errno for error checking and reporting.
> fu-udev-device.c: Fix ioctl error checking

- plugins/synaptics-prometheus/fu-synaprom-firmware.c
This fixes a timeout found by oss-fuzz.
> synaprom: Set a sane limit on the number of images that can be added

- contrib/ci/ubuntu.sh
- contrib/fwupd.spec.in
- plugins/uefi-capsule/efi/generate_binary.py
- plugins/uefi-capsule/efi/meson.build
Two reasons:
* It seems a bit antisocial to hard-require all this data without fair warning
* The aarch64 pesign crashes when trying to sign the binary with SBAT metadata
> Allow building without SBAT metadata

- contrib/PKGBUILD
Signed-off-by: Morten Linderud <morten@linderud.pw>
> contrib/PKGBUILD: Ensure pkgver gets expanded as an bash variable

- plugins/rts54hub/README.md
- plugins/rts54hub/fu-plugin-rts54hub.c
- plugins/rts54hub/fu-rts54hub-device.c
- plugins/rts54hub/fu-rts54hub-device.h
- plugins/rts54hub/fu-rts54hub-rtd21xx-device.c
- plugins/rts54hub/fu-rts54hub-rtd21xx-device.h
- plugins/rts54hub/meson.build
- plugins/rts54hub/rts54hub.quirk
add USBtoI2C functions to fu-rts54hub-device.c
add rtd21xx child device to rts54hub for FW update
Signed-off-by: RickyWu <ricky_wu@realtek.com>
> plugins: rts54hub add children device rtd21xx HDMI converter

- contrib/ci/fedora.sh
- contrib/debian/fwupd-tests.postinst
Let these get turned on no matter what we change in daemon.conf
> trivial: don't hardcode expected plugins list for CI

- .github/workflows/create_containers.yml
This should be dropped at some point hopefully when the new
docker release has landed.
See: https://github.com/actions/virtual-environments/issues/2658
Fixes: #2894
> trivial: ci: add a workaround for arch container generation issue

- plugins/synaptics-mst/fu-plugin-synaptics-mst.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
This is typically when the OEM is using the reference hardware design.
Prevent updates, as there might be a new bug introduced in the reference
firmware that only manifests on one OEM's product. It's up to the OEM to do the
testing and validation.
We need something to tie it back to a physical device model if it's using a
reference firmware and we want to update it.
> synaptics-mst: Do not allow updating a device with no customer ID

- contrib/fwupd.spec.in
- plugins/uefi-capsule/efi/generate_binary.py
- plugins/uefi-capsule/efi/generate_sbat.py
- plugins/uefi-capsule/efi/lds/elf_aarch64_efi.lds
- plugins/uefi-capsule/efi/lds/elf_ia32_efi.lds
- plugins/uefi-capsule/efi/lds/elf_x86_64_efi.lds
- plugins/uefi-capsule/efi/meson.build
The current approach of adding SBAT metadata after linking is creating
an image that is badly formed in 2 ways:
* The SBAT section's file offset and size are not a multiple of the
file alignment.
* The SBAT section has a virtual address of zero. EDK2 loads the header
here, and so it gets rejected.
This changes the approach to match shim, where an object file is
created with a .sbat section and then the linker takes care of placing
the section at a more appropriate virtual address.
> uefi-capsule: Ensure SBAT metadata is added correctly

- src/fu-main.c
Although glibc calls this when memory gets low automatically, we can invoke it
manually when we've loaded all plugins and coldplugged all devices.
This has no effect when using proper heap benchmarks like massif, but random
Reddit users just looking at the RSS column in an 'easy-to-use memory profiler'
will see a much lower numbers.
Where this feature might actually be useful is after a libxmlb metadata rebuild
where we dirtied a lot of heap just parsing XML.
> Drop unused heap pages after startup has completed

- libfwupdplugin/fu-bluez-device.c
References to opt_variant and val_variant are sunk in a subsequent
variant creation and consumed by g_dbus_proxy_call_sync. They don't need
to be freed in this context.
> Fix GVariant declarations in fu_bluez_device_write

- libfwupdplugin/fu-plugin.c
If the user explicitly specifies the device-id then we do not do the front-end
filtering. If the device detaches without being able to attach then the hardware
could be left in the bootloader state.
See https://github.com/fwupd/fwupd/issues/2926#issuecomment-784234180
> trivial: Only allow verify-update for plugins that support _CAN_VERIFY

- plugins/uefi-capsule/efi/lds/elf_arm_efi.lds
fixes FTBFS in Debian:
https://buildd.debian.org/status/fetch.php?pkg=fwupd&arch=armhf&ver=1.5.7-1&stamp=1614100547&raw=0
> trivial: add linker script for armhf

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fwupdplugin.map
- src/fu-backend.c
- src/fu-backend.h
- src/fu-bluez-backend.c
- src/fu-engine.c
- src/fu-udev-backend.c
- src/fu-usb-backend.c
This is typically a Linux sysfs path or USB platform ID and is used in a
different way to the physical ID. The physical ID is only set for some devices
after setup() and depends on the subsystem list, and this would not be defined
for devices that do not match a plugin.
This also fixes an regression where the FuDeviceList fails to match the new
FuUdevDevice device in fu_device_list_get_by_guids_removed() and instead
silently gets 'fixed up' only if FWUPD_DEVICE_FLAG_NO_GUID_MATCHING is not set.
This also allows us to move the various backends device caches to FuBackend as
we now have a suitable ID that is for just the backend to use.
> Add a backend ID to the device

- libfwupdplugin/fu-udev-device.c
I've not yet worked out the real bug, but it was unexpected to crash the daemon
when open failed, rather than for a critical misuse of the API.
> trivial: Set the GError when calling ioctl() on an un-opened device

- plugins/system76-launch/fu-system76-launch-device.c
- plugins/system76-launch/meson.build
This addresses https://github.com/fwupd/fwupd/discussions/2937. Some cleanup was done so that the response from the `RESET` command can be captured. Now both the `VERSION` and `RESET` commands go through `fu_system76_launch_device_command`.
An error is returned to the user indicating how to unlock the device if the `RESET` command is blocked. To support the use of `FWUPD_ERROR_NEEDS_USER_ACTION`, `fwupd` had to be linked.
> system76-launch: Prompt for unlock keypress if reset command is blocked

- libfwupdplugin/fu-bluez-device.c
- libfwupdplugin/fu-bluez-device.h
- libfwupdplugin/fwupdplugin.map
This adds three methods to bluez devices:
- fu_bluez_device_connect_signal: to register a callback for a signal
on a BlueZ object.
- fu_bluez_device_start_notify: to enable notifications for property
changes in a specific object.
- fu_bluez_device_stop_notify: to disable notifications for property
changes in a specific object.
NOTE that currently this is implemented for GATT characteristics only,
but can be extended to other types of objects.
Listening for property changes in a bluez characteristic requires a
long-lived connection or proxy, so this also refactors bluez device
UUIDs into a simple object that keeps the path, the proxy and the signal
id in case a callback is registered for this UUID.
An additional advantage of this is that fwupd no longer creates a
throwaway proxy object for …
> Support for GATT characteristic signals/notifications

- plugins/thunderbolt/fu-thunderbolt-device.c
```
18:28:37:0526 FuFirmware           fu_firmware_parse_full: assertion 'fw != NULL' failed
```
> thunderbolt: correct an assertion if kernel failed FW read

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/flashrom/flashrom.quirk
- plugins/flashrom/fu-flashrom-device.c
- plugins/flashrom/fu-plugin-flashrom.c
- plugins/uefi-recovery/fu-plugin-uefi-recovery.c
- plugins/uefi-recovery/uefi-recovery.quirk
- src/fu-engine.c
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util.c
At the moment plugins are doing this a few different ways; either looping
through the HwIds manually (e.g. flashrom) or setting a custom flag that is
checked in fu_plugin_setup (e.g. uefi-recovery).
Define a standard 'Plugin' HwId quirk to simplify plugins.
> Allow enabling plugins only matching a specific HwId

- plugins/superio/fu-plugin-superio.c
Fixes a regression in 79a217a2a617224465e02c8cd7ebb8d3c5277c25
> superio: Ensure quirks are set on the new devices

- subprojects/libxmlb.wrap
Newer revision of the libxmlb solves wrong MIME type problem at FreeBSD
Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>
> libxmlb.wrap: Bump revision

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/logitech-hidpp/fu-logitech-hidpp-peripheral.c
- src/fu-engine.c
We want to make it as easy as possible for devices to refuse to update on low
battery, as this will likely be one of the WWCB requirements.
Ideally devices will check the battery level inside the firmware, but by also
providing the battery level to fwupd we can give the user a warning *before*
the update has started and without switching the device into bootloader mode.
> Add fu_device_set_battery_level()

- plugins/uefi-capsule/efi/generate_sbat.py
When using "objcopy -O binary" to generate AArch64 EFI images, it
silently drops the sections without "alloc" or "load" or the sections
with "unload", and this caused the content of .sbat was skipped in the
final EFI image.
This commit sets the common read-only data section flags to .sbat to
make sure the content will be copied.
> uefi-capsule: Specify the section flags for .sbat

- plugins/uefi/efi/generate_sbat.py
When using "objcopy -O binary" to generate AArch64 EFI images, it
silently drops the sections without "alloc" or "load" or the sections
with "unload", and this caused the content of .sbat was skipped in the
final EFI image.
This commit sets the common read-only data section flags to .sbat to
make sure the content will be copied.
> backport uefi-capsule: Specify the section flags for .sbat for 1_3_X

- plugins/uefi/efi/generate_sbat.py
When using "objcopy -O binary" to generate AArch64 EFI images, it
silently drops the sections without "alloc" or "load" or the sections
with "unload", and this caused the content of .sbat was skipped in the
final EFI image.
This commit sets the common read-only data section flags to .sbat to
make sure the content will be copied.
> backport uefi-capsule: Specify the section flags for .sbat for 1_4_X

- plugins/uefi/efi/generate_sbat.py
When using "objcopy -O binary" to generate AArch64 EFI images, it
silently drops the sections without "alloc" or "load" or the sections
with "unload", and this caused the content of .sbat was skipped in the
final EFI image.
This commit sets the common read-only data section flags to .sbat to
make sure the content will be copied.
> backport uefi-capsule: Specify the section flags for .sbat for 1_2_X

- plugins/synaptics-rmi/synaptics-rmi.quirk
Apparently, some devices will not respond well to probing.
See bug https://bugs.launchpad.net/ubuntu/+source/linux-firmware/+bug/1886912
>  backport synaptics-rmi: Do not match all HIDRAW\VEN_06CB devices

- plugins/synaptics-rmi/synaptics-rmi.quirk
See https://bugs.launchpad.net/ubuntu/+source/linux-firmware/+bug/1886912 for background 
> backport: disable synaptics-rmi for 1-3-x

- src/fu-tool.c
Activate was no longer calling coldplug meaning even if devices were
in the pending database they wouldn't activate.
> fu-tool: fix a regression where activate stopped working in c7d870aa9

- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-firmware.h
- libfwupdplugin/fwupdplugin.map
The idea here is to return the size of the firmware, including the header,
footer or other encapsulation. It would be expected that this value would
include the alignment if provided.
> trivial: Add fu_firmware_get_size()

- plugins/flashrom/fu-flashrom-device.c
> Allow reading the PciBcrAddr quirk from flashrom devices

- plugins/flashrom/flashrom.quirk
PciBcr gets a false positive for `SPI write` and removes the updateable flag. chipsec correctly detects BIOSWE and BLE, by looking at 1f.5. Adjusting the visibility of 1f.5 in the firmware doesn't change the result of PcrBcr.
To get flashrom working, changed to not remove the updatable flag if the PcrBcrAddr quirk is 0 (but doesn't solve the false-positive issue).
```
HSI-1
✔ Intel DCI debugger:            Disabled
✔ SPI lock:                      Enabled
✔ SPI write:                     Disabled
✔ UEFI platform key:             Valid
✘ SPI BIOS region:               Unlocked
✘ TPM v2.0:                      Not found
```
```
[*] BC = 0x0000008B << BIOS Control (b:d.f 00:31.5 + 0xDC)
[00] BIOSWE           = 1 << BIOS Write Enable 
[01] BLE              = 1 << BIOS Lock Enable 
[02] SRC …
```
> Stopped updatable flag being removed if PciBcrAddr=0

- plugins/cros-ec/cros-ec.quirk
Baklava is based on Quiche and will work with cros-ec plugin.
fixes #3044
Add support for the D501 Baklava device. Basically a quiche variant.
> cros-ec: Add D501 Baklava device support

- plugins/cros-ec/fu-cros-ec-usb-device.c
outbuf == NULL is a valid condition in fu_cros_ec_usb_device_do_xfer. That's
how we use this function to specify a read with no outbound buffer, like the
reply at the end of sending a block.
Since 9b11af985f68 ("Add fu_memdup_safe()"), however, the call to fu_memdup_safe
always fails if outbuf, the dst, is NULL.
Fix this by moving this into the if (outbuf != NULL && outlen > 0)  block below.
Fixes: 9b11af985f68 ("Add fu_memdup_safe()")
fixes #3064
> cros-ec: Fix call to fu_memdup_safe in fu_cros_ec_usb_device_do_xfer

- plugins/cros-ec/fu-cros-ec-usb-device.c
Looks like this error message was copy/pasted from above.
Since we're testing whether actual != inlen, the error message should
output inlen.
> trivial: cros-ec: Fix error string to use inlen

- src/fu-tool.c
I stumbled across a sigfault when running `fwupdtool verify-update <guid>`:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055e0daadd547 in fu_util_get_device (priv=0x55e0dbbced00, id=0x0, error=0x7ffdf49d4938) at ../src/fu-tool.c:446
446		for (guint i = 0; id[i] != '\0'; i++) {
[Current thread is 1 (Thread 0x7f876abed8c0 (LWP 31473))]
(gdb) bt
#0  0x000055e0daadd547 in fu_util_get_device (priv=0x55e0dbbced00, id=0x0, error=0x7ffdf49d4938) at ../src/fu-tool.c:446
#1  0x000055e0daae2819 in fu_util_verify_update (priv=0x55e0dbbced00, values=0x55e0dbbb5ca0, error=0x7ffdf49d4938) at ../src/fu-tool.c:2220
#2  0x000055e0daae7aa1 in fu_util_cmd_array_run
(array=0x55e0dbbcee00, priv=0x55e0dbbced00, command=0x7ffdf49d6760 "verify-update", …
```
> fu-tool: fix array access in fw_util_verify_update

- plugins/uefi-capsule/efi/generate_sbat.py
The format is meant to be "<project>.<vendor>" with a period as a
separator.
Signed-off-by: Steve McIntyre <93sam@debian.org>
> Tweak the SBAT output for a vendor string

- meson.build
- src/fu-main.c
malloc_trim isn't a linux function, it's a GNU extension to malloc.  We
can check for it in meson.build, which avoids hardcoding platform
knowledge.
> Fix build on musl.

- contrib/ci/ubuntu.sh
We'll see if this is enough to get it disabled.
> trivial: ci: disable LTO for clang (fixes: #3089)

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-quirks.c
- libfwupdplugin/fu-quirks.h
- libfwupdplugin/fwupdplugin.map
- plugins/upower/fu-plugin-upower.c
- src/fu-engine.c
This allows a device to set a custom 'check battery level is X%' value from
either the plugin or from a quirk.
> Add fu_device_set_battery_threshold()

- plugins/flashrom/fu-flashrom-device.c
- plugins/flashrom/fu-plugin-flashrom.c
This change moves many of the logic at the plugin level to the device
level in order to support multiple devices updatable via libflashrom.
> flashrom: Update plugin to support multiple devices

- docs/hsi.xml
- libfwupd/fwupd-security-attr-private.h
- plugins/intel-spi/fu-ifd-common.c
- plugins/intel-spi/fu-ifd-common.h
- plugins/intel-spi/fu-ifd-device.c
- plugins/intel-spi/fu-ifd-device.h
- plugins/intel-spi/fu-ifd-firmware.c
- plugins/intel-spi/fu-intel-spi-common.c
- plugins/intel-spi/fu-intel-spi-common.h
- plugins/intel-spi/fu-intel-spi-device.c
- plugins/intel-spi/fu-intel-spi-device.h
- plugins/intel-spi/fu-pci-device.c
- plugins/intel-spi/fu-pci-device.h
- plugins/intel-spi/fu-plugin-intel-spi.c
- plugins/intel-spi/generate-quirk.py
- plugins/intel-spi/intel-spi.quirk
- plugins/intel-spi/meson.build
- src/fu-security-attr.c
If we need to export the EFI symbols into libfwupdplugin for other plugins we
can do that when we need them.
> Make intel-spi actually useful

- libfwupdplugin/fu-device.c
If only one plugin is enabled and there exists a device match for a GType that
has not been registered then the user sees a GType error about not being able
to create a device that wouldn't be created anyway.
By removing the error in the quirk parser we will catch actual errors in
fu_plugin_runner_backend_device_added() which actually does chcek for
FWUPD_PLUGIN_FLAG_DISABLED.
Fixes https://github.com/fwupd/fwupd/issues/3099
> Do not show a GType failure when using fwupdtool

- plugins/dfu/fu-dfu-tool.c
We were seeing:
```
,----
| (dfu-tool:1139827): GLib-WARNING **: 17:34:42.671: GError set over the top of a previous GError or uninitialized memory.
| This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
| The overwriting error message was: no device matches for 1234:abcd
`----
``
This is because we were attempting to overwrite libgusb's error with one
for fwupd, and glib rightfully complains. Since we're likely more
interested in the fwupd error (since it's specifically
FWUPD_ERROR_NOT_FOUND), let's ignore the error from gusb.
> dfu-tool: Avoid runtime warning (overriding error)

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/ata/fu-ata-device.c
- plugins/solokey/fu-solokey-firmware.c
- plugins/thunderbolt/fu-thunderbolt-firmware.c
- src/fu-engine.c
- src/fu-self-test.c
This was originally added for the WD19 which can actually advertise
it's own activation state from the hardware.
Fixes: #3106
> fu-engine: Don't inherit activation flags for devices

- contrib/ci/ubuntu.sh
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/ata/fu-ata-device.c
- src/fu-engine.c
- src/fu-self-test.c
The activation flag is stored into the history database, but not all
plugins will want to inherit it on coldplug the next time the daemon
is started.
For example the Dell Dock plugin will query this information from the
device and it will prevent getting into a bad state as a result.
Fixes: #3106
> Add a new internal flag for whether or not to inherit activation

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fwupdplugin.map
- plugins/upower/fu-plugin-upower.c
- plugins/upower/meson.build
- plugins/upower/upower.conf
- plugins/upower/upower.quirk
- src/fu-engine.c
This allows plugins to set the battery power state of the *machine* which means
we can automatically inhibit devices with FWUPD_DEVICE_FLAG_REQUIRE_AC set.
It also allows to set the BatteryThreshold to 25% for Lenovo hardware, and we
can override other vendors with further quirks as required.
Fixes https://github.com/fwupd/fwupd/issues/3084
> Set the system battery state and level on the FuContext shared state

- plugins/uefi-capsule/efi/crt0/crt0-efi-aarch64.S
- plugins/uefi-capsule/efi/crt0/crt0-efi-arm.S
- plugins/uefi-capsule/efi/crt0/meson.build
- plugins/uefi-capsule/efi/generate_binary.py
- plugins/uefi-capsule/efi/lds/elf_aarch64_efi.lds
- plugins/uefi-capsule/efi/lds/elf_arm_efi.lds
- plugins/uefi-capsule/efi/lds/elf_ia32_efi.lds
- plugins/uefi-capsule/efi/lds/elf_x86_64_efi.lds
- plugins/uefi-capsule/efi/meson.build
> Sync linker scripts and crt0 for arm/aarch64 with what the latest in shim

- plugins/flashrom/README.md
- plugins/flashrom/fu-flashrom-device.c
- plugins/flashrom/fu-flashrom-device.h
- plugins/flashrom/fu-flashrom-internal-device.c
- plugins/flashrom/fu-flashrom-internal-device.h
- plugins/flashrom/fu-plugin-flashrom.c
- plugins/flashrom/meson.build
This change allows other device types to derive from common flashrom
code in the flashrom-device type.
> flashrom: make fu-flashrom-device a derivable type

- libfwupdplugin/fu-plugin.c
- plugins/flashrom/README.md
- plugins/flashrom/flashrom.quirk
- plugins/flashrom/fu-flashrom-device.c
- plugins/flashrom/fu-flashrom-device.h
- plugins/flashrom/fu-flashrom-internal-device.c
- plugins/flashrom/fu-flashrom-lspcon-i2c-spi-device.c
- plugins/flashrom/fu-flashrom-lspcon-i2c-spi-device.h
- plugins/flashrom/fu-plugin-flashrom.c
- plugins/flashrom/meson.build
- src/fu-engine.c
Adds a new device type to the flashrom plugin for devices requiring the lspcon-i2c-spi programmer.
> Flashrom: add lspcon-i2c-spi support

- plugins/vli/vli-pd.quirk
This fixes flashing when in normal runtime mode.
Resolves https://github.com/fwupd/fwupd/issues/2940
> Mark the Lenovo VL103 no-power USB-C dongle as dual-image

- plugins/flashrom/fu-flashrom-lspcon-i2c-spi-device.c
Disable verification on sub-block-size write was not needed after all.
Type of pull request: Code fix
> trivial: flashrom: verify write to flag region

- src/fu-main.c
Mostly theoretical, although certainly possible when developing...
> Never allow D-Bus replacement when a firmware update is in operation

- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/flashrom/fu-flashrom-lspcon-i2c-spi-device.c
Parsing bus numbers out of sysfs paths may be fragile, so use udev to find the I2C bus matching a LSPCON device. Support for specifying an I2C bus by path rather than number is also required in flashrom, implemented at https://review.coreboot.org/c/flashrom/+/51967; the flashrom dependency will require an update to provide this support once merged upstream.
> flashrom/lspcon: avoid parsing sysfs paths

- meson.build
- src/fu-tool.c
Open file description locks are Linux-specific. If fwupd is not built
for Linux, it should use the traditional UNIX record locks (F_SETLK).
Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>
> fu-tool.c: Use traditional UNIX record locks if OFD is not available

- data/bash-completion/fwupdtool.in
- libfwupdplugin/fu-cabinet.c
- libfwupdplugin/fu-cabinet.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- src/fu-tool.c
This can be used like this:
fwupdtool firmware-sign firmware.cab rhughes_signed.pem rhughes.key
Test signing certificates can be generated using the example script here:
https://github.com/hughsie/libjcat/blob/master/contrib/build-certs.py although
these certificates should not be used for enterprise use.
> Add a utility to resign firmware files

- plugins/dfu/fu-dfu-tool.c
fu_dfu_tool_get_default_device returns a newly create FuDfuDevice `device`; but since it is marked as `g_autoptr`, it is destroyed when leaving the scope and the caller receives garbage.
```
,----
| ==697985== Invalid read of size 8
| ==697985==    at 0x4B50F49: g_type_check_instance_is_fundamentally_a (gtype.c:4080)
| ==697985==    by 0x4B3A988: g_object_unref (gobject.c:3421)
| ==697985==    by 0x406CF3: glib_autoptr_clear_GObject (gobject-autocleanups.h:27)
| ==697985==    by 0x406DD5: glib_autoptr_clear_FwupdDevice (gusb-autocleanups.h:17)
| ==697985==    by 0x406E9C: glib_autoptr_clear_FuDevice (fu-device.h:18)
| ==697985==    by 0x406EE3: glib_autoptr_clear_FuUsbDevice (fu-usb-device.h:22)
| ==697985==    by 0x406F6A: glib_autoptr_clear_FuDfuDevice (fu-dfu-device.h:19)
| ==697985== …
```
> fu_dfu_tool_get_default_device: Avoid use-after-free

- libfwupdplugin/fu-device.c
- plugins/flashrom/fu-flashrom-device.c
- src/fu-engine.c
If the device is on battery power, the device will have at least one inhibit
and be in FWUPD_DEVICE_FLAG_UPDATABLE_HIDDEN state.
It's still supported, and it's misleading to suggest there are no updates
available. Just check both flags.
Fixes the 3rd half (sic) of https://github.com/fwupd/fwupd/issues/3156
> Check FWUPD_DEVICE_FLAG_UPDATABLE_HIDDEN when calculating the SUPPORTED flag

- plugins/flashrom/fu-flashrom-lspcon-i2c-spi-device.c
While the PS175 will attempt to boot from the flash bank specified by the flag bytes, it does not always actually boot the specified bank because it also performs integrity checks on the target image. If those fail, it will instead boot from bank 3 which should always be treated as read-only.
In all cases, the device exposes a register on I2C that says which bank it actually booted from. Update the plugin to probe which bank the device has actually booted, rather than assuming it booted the one the flags say it should.
In support of this, replace the mutable static flash layout with making copies of a "pristine" layout. The mutable layout can easily cause unintended flash regions to be included in operations; making a copy of a layout that includes nothing and …
> flashrom/lspcon: probe device to determine actual active partition

- plugins/flashrom/fu-flashrom-lspcon-i2c-spi-device.c
> trivial: Use g_memdup2() on newer GLib versions

- meson_options.txt
- plugins/uefi-capsule/meson.build
This goes with https://github.com/fwupd/fwupd/pull/3153, and assuming it's merged will be what can go into 1.5.x to allow packagers to optionally choose to use subproject instead.
> 1_5_X: Add an option to avoid building UEFI binary

- meson_options.txt
- plugins/uefi/meson.build
> 1_4_X: Add an option to avoid building UEFI binary

- meson_options.txt
- plugins/uefi/meson.build
> 1_3_X: Add an option to avoid building UEFI binary

- meson_options.txt
- plugins/uefi/meson.build
> 1_2_X: Add an option to avoid building UEFI binary

- meson_options.txt
- plugins/uefi/meson.build
> 1_1_X: Add an option to avoid building UEFI binary

- libfwupdplugin/fu-cabinet.c
- libfwupdplugin/fu-self-test.c
Fixes half of https://github.com/fwupd/fwupd/issues/3193
> Support all hash types when loading cabinet archives

- src/fu-main.c
Actually use the composite ID for the given device ID.
Fixes the easier half of https://github.com/fwupd/fwupd/issues/3196
> Fix a regression in updating the WD19TB dock

- contrib/ci/build_windows.sh
- contrib/ci/dependencies.xml
- libfwupd/fwupd-client.c
- libfwupd/meson.build
- meson.build
- meson_options.txt
- snap/snapcraft.yaml
GProxyResolver will use libproxy only when required. TIL.
> Switch from libproxy to GProxyResolver

- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
For some users typing 'fwupdmgr update' just deploys all updates to all hardware,
and that might come as a shock. Ask the user to confirm all actions explicitly
and show the update notes in a warning box rather than plain text on the console.
> Ask the user to confirm all CLI actions

- meson.build
Reverts small part of 99832622e157067e40896815ace0f8f7a153e8af
`EFI_APP_LOCATION` conf var (or `FWUPD_EFIAPPDIR` env var) is needed for
```
fu_common_get_path (FU_KIND_PATH_EFIAPPDIR)
```
to function properly
> Fix regression in build system

- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-mm-utils.c
- plugins/modem-manager/fu-mm-utils.h
- plugins/modem-manager/fu-plugin-modem-manager.c
No longer rely on the modems being USB based, we can also support PCI based devices with the same protocols.
- [X ] Feature
> modem-manager: add generic support for PCI based modems

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- src/fu-tool.c
This allows for proper locking between executions of fwupdtool in
Chromium OS minijail environment. It is needed after commit
9cf5f8f7ff7b93473eabf21e8482bb8feace039a was introduced.
> Switch lock directory from /var/run to /run/lock

- libfwupdplugin/fu-device-locker.c
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-self-test.c
- plugins/fastboot/fu-fastboot-device.c
Fixes https://github.com/fwupd/fwupd/issues/3187
> Force the device locker to ->close() an aborted ->open()

- contrib/ci/dependencies.xml
This is needed as fwupd-efi uses the fwupd images, and pesign is a
build-time dep of the Fedora package.
> trivial: Add back pesign to the fwupd docker images

- plugins/colorhug/fu-colorhug-device.c
Reading the response works on Linux, but fails on FreeBSD.
> colorhug: Ignore the failure to get the reply on device reset

- plugins/uefi-capsule/fu-uefi-devpath.c
FreeBSD has Linux-like `<efivar-dp.h>` header, but it doesn't define type constants and it's not included implicitly by `<efivar.h>`.
> Enable building uefi-capsule plugin on FreeBSD 

- libfwupd/fwupd-client-private.h
Move the function prototype out of the GUnixInputStream-using ones.
> trivial: Fix a warning when compiling on Windows

- plugins/analogix/meson.build
Otherwise the following build error happens:
```
../fwupd-1.6.0/plugins/analogix/fu-analogix-device.c:54:10: error: ‘G_USB_DEVICE_DIRECTION_HOST_TO_DEVICE’ undeclared (first use in this function)
54 |          G_USB_DEVICE_DIRECTION_HOST_TO_DEVICE,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../fwupd-1.6.0/plugins/analogix/fu-analogix-device.c:54:10: note: each undeclared identifier is reported only once for each function it appears in
../fwupd-1.6.0/plugins/analogix/fu-analogix-device.c:55:10: error: ‘G_USB_DEVICE_REQUEST_TYPE_VENDOR’ undeclared (first use in this function)
55 |          G_USB_DEVICE_REQUEST_TYPE_VENDOR,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../fwupd-1.6.0/plugins/analogix/fu-analogix-device.c:56:10: error: ‘G_USB_DEVICE_RECIPIENT_DEVICE’ undeclared (first use …
```
> analogix plugin requires gusb

- src/fu-engine.c
- src/fu-self-test.c
This allow setting 'other-device' requirements of depth=0 to find
devices only with a common parent.
CC @CragW 
Matching documentation change: https://gitlab.com/fwupd/lvfs-website/-/merge_requests/1007
> fu-engine: Add support for a sibling requirement

- plugins/ebitdo/ebitdo.quirk
- plugins/ebitdo/fu-ebitdo-device.c
The PID information of N30 pro 2 (PID_9015) is different from that of SN30 Pro (PID_6001).
> Add N30 Pro 2 gamepad

- plugins/thunderbolt/fu-plugin-thunderbolt.c
The dell-dock plugin has a check whether or not to create the I2C based
child device based upon whether thunderbolt link is active during probe.
So there will never be a situation that daemon needs to de-duplicate and
set priority between the two plugins.
Stemmed from this conversation: https://github.com/fwupd/fwupd/pull/3327#discussion_r648245102
CC @CragW
> trivial: don't set priority between thunderbolt and dell-dock plugins

- libfwupdplugin/fu-efivar-freebsd.c
- libfwupdplugin/fu-efivar-impl.h
- libfwupdplugin/fu-efivar-linux.c
- libfwupdplugin/fu-efivar-windows.c
- libfwupdplugin/fu-efivar.c
- libfwupdplugin/meson.build
- meson.build
> libfwupdplugin: Implement fu-efivar-freebsd.c

- libfwupdplugin/fu-device.c
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-plugin-modem-manager.c
This already happens during setup, there shouldn't be a need to depend
on the private header to accomplish this.
> modem-manager: Do not convert instance IDs to GUIDs manually

- contrib/ci/build_freebsd_package.sh
- libfwupdplugin/fu-efivar-freebsd.c
- meson.build
- plugins/uefi-capsule/fu-uefi-backend-freebsd.c
- plugins/uefi-capsule/meson.build
- plugins/uefi-dbx/meson.build
***
Upstream kernel [patch](https://reviews.freebsd.org/D30104) was rejected in its original form. `sysctl()` interface was changed to `ioctl()` and it won't compile now without updated patch applied. Actually patch update wasn't yet sent upstream, but you can see it [here](https://github.com/3mdeb/freebsd-src/pull/2). We believe that's basically final form of the API.
I've also faced some issues with efivars, which weren't noticed during review. Maybe cherry-pick it separately.
> Update ESRT access implementation for FreeBSD

- plugins/synaptics-prometheus/fu-synaprom-device.c
Do not manually call config setup before adding the parent.
The ->setup() action is called on children explicitly in fu_device_setup()
after the parent device has all the required properties.
Fixes https://github.com/fwupd/fwupd/issues/3364
> synaptics-prometheus: Fix enumeration of the config child

- src/fu-install-task.c
If the device is inhibited no install tasks should run on it.
CC @CragW
> Fix blocking of updates for inhibited devices

- contrib/fwupd.spec.in
- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fwupdplugin.map
- plugins/synaptics-mst/fu-plugin-synaptics-mst.c
- plugins/synaptics-mst/meson.build
- plugins/synaptics-mst/synaptics_mst.conf
- plugins/thunderbolt/fu-plugin-thunderbolt.c
I've found that the original problem we had has been fixed in current kernels.  It appears to be fixed by https://github.com/torvalds/linux/commit/8ae5b1d78d4acbe9755570f26703962877f9108a
Running with an AMD Renoir system I can find that it probes properly as far back as kernel 5.8 (but can't check much earlier due to lack of kernel support for Renoir).
```
~/fwupd$ sudo fwupdtool get-devices --plugins synaptics-mst
Loading…                 [***************************************]
WARNING: This package has not been validated, it may not work properly.
20Y10015US
│
└─VMM5322:
Device ID:          81905eb4059e79f42c9f19fdcb195beeae5f38fa
Summary:            Multi-Stream Transport Device
Current version:    5.05.05
Vendor:             Synaptics (DRM_DP_AUX_DEV:0x06CB)
GUIDs: …
```
> Allow probing Synaptics MST w/ amdgpu on newer enough kernels

- plugins/vli/fu-vli-usbhub-device.c
Although this leads to the same end result, it's better to list the
InstanceIDs in order of specificity.
> vli: Call the superclassed probe explicitly

- libfwupd/fwupd-device.c
- libfwupd/fwupd-self-test.c
Add a suffix to any GUIDs that are currently unconverted InstanceIDs.
This makes plugin development much easier as you can now see why GUID
quirks in the subclassed ->setup() are not matching.
> libfwupd: Show unconverted GUIDs when debugging

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/vli/fu-vli-device.c
- plugins/vli/fu-vli-device.h
- plugins/vli/fu-vli-pd-device.c
- plugins/vli/fu-vli-usbhub-device.c
- plugins/vli/vli-usbhub-lenovo.quirk
Add a FuDevice->ready() vfunc that is run after ->setup()
This allows plugins to perform setup actions that require quirk matches
after the instance IDs have been converted. This allows us to also
remove FuVliDevice->setup() as the ordering chain has been broken.
There are two USB-3 hubs internally (with the same VID&PID), and the
MSP430 is only attached to the top-level one.
Fixes https://github.com/fwupd/fwupd/issues/3366
> vli: Be more specific when matching the MSP430

- plugins/wacom-usb/fu-wac-device.c
While the modern firmware interfaces report their version numbers in
big-endian form, reading the legacy Bluetooth module version via the
FU_WAC_REPORT_ID_GET_FIRMWARE_VERSION_BLUETOOTH report requires us to
actually parse a little-endian value. This difference was overlooked
when making changes to the version parsing code in commit 50a4ec70e6a8.
This commit restores the proper interpretation.
Fixes: 50a4ec70e6a8 (wacom_usb: Firmware versions are packed BCD, not "decimal")
> wacom-usb: Legacy Bluetooth module reports version numbers in little-endian

- plugins/wacom-usb/wacom-usb.quirk
Both the wired-only and wireless-capable versions of the CTL-4100 /
CTL-6100 will switch into "Android mode" if their string descriptors are
read too many times. A previous commit added the "no-serial-number"
flag to the wireless variants to work around this problem; this commit
adds the flag to the wired-only variants.
> wacom-usb: Add "no serial" flag to other CTL-X100 products

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fwupdplugin.map
- src/fu-engine.c
- src/fu-self-test.c
Of course, this only works if the parent and child both *export* a
FuDevice of the same physical kind, e.g. USB.
> Use the parent physical ID to autoset the device parent

- meson.build
Sets the minimum required version to 0.50.0 since we are using features
which are not available prior to that release:
WARNING: Project specifies a minimum meson_version '>=0.47.0' but uses
features which were added in newer versions:
* 0.49.0: {'/ with string arguments'}
* 0.50.0: {'install arg in configure_file'}
> Bump minimum required meson version to correct build warning

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/dfu/fu-dfu-device.c
- plugins/jabra/fu-plugin-jabra.c
If this is shared between plugins it needs to be specified in a shared
place.
> Use an internal device flag rather that using a custom flag

- src/fu-engine.c
- src/fu-self-test.c
This allows OEMs to suggest that certain components are updated to specific
versions, but allowing end-users to override this as required.
> Add support for soft-requirements that can be ignored with --force

- subprojects/fwupd-efi.wrap
It's all build system improvements.
> trivial: get the fwupd-efi 1.1 release instead

- plugins/vli/fu-vli-usbhub-pd-device.c
This was missed when porting the MSP430 and RTD21XX chips.
> vli: Fix regression in enumerating the PD device

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- plugins/ccgx/fu-ccgx-dmc-device.c
- plugins/colorhug/fu-colorhug-device.c
- plugins/cros-ec/fu-cros-ec-usb-device.c
- plugins/dell-dock/fu-dell-dock-hub.c
- plugins/dell-dock/fu-dell-dock-hub.h
- plugins/dell-dock/fu-plugin-dell-dock.c
- plugins/dfu-csr/fu-dfu-csr-device.c
- plugins/dfu/fu-dfu-common.h
- plugins/dfu/fu-dfu-device.c
- plugins/dfu/fu-dfu-target-avr.c
- plugins/dfu/fu-dfu-target.c
- plugins/intel-spi/fu-intel-spi-device.c
- plugins/nvme/fu-nvme-device.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
- plugins/uefi-capsule/fu-uefi-device.c
- plugins/uefi-capsule/fu-uefi-device.h
- plugins/vli/fu-vli-pd-device.c
- plugins/vli/fu-vli-usbhub-device.c
- src/fu-device-list.c
The CustomFlags feature is a bit of a hack where we just join the flags
and store in the device metadata section as a string. This makes it
inefficient to check if just one flag exists as we have to split the
string to a temporary array each time.
Rather than adding to the hack by splitting, appending (if not exists)
then joining again, store the flags in the plugin privdata directly.
This allows us to support negating custom properties (e.g. ~hint) and
also allows quirks to append custom values without duplicating them on
each GUID match, e.g.
[USB\VID_17EF&PID_307F]
Plugin = customflag1
[USB\VID_17EF&PID_307F&HUB_0002]
Flags = customflag2
...would result in customflag1,customflag2 which is the same as you'd
get from an enumerated device flag doing the same thing.
> Allow adding and removing custom flags on devices

- plugins/superio/README.md
- plugins/superio/fu-plugin-superio.c
- plugins/superio/fu-superio-device.c
- plugins/superio/fu-superio-device.h
- plugins/superio/fu-superio-it55-device.c
- plugins/superio/fu-superio-it55-device.h
- plugins/superio/fu-superio-it85-device.c
- plugins/superio/fu-superio-it89-device.c
- plugins/superio/meson.build
- plugins/superio/superio.quirk
- src/fu-tool.c
***
The provided implementation targets Tuxedo laptops that use IT5570. Latest attempt to support this EC was in #3413.
> Add IT5570 to the superio plugin

- contrib/ci/dependencies.xml
- contrib/fwupd.spec.in
- meson.build
- plugins/modem-manager/README.md
- plugins/modem-manager/fu-mbim-qdu-updater.c
- plugins/modem-manager/fu-mbim-qdu-updater.h
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-plugin-modem-manager.c
- plugins/modem-manager/meson.build
This MR adds the mbim-qdu support for firmware downloading (some modifications based on #3208) , it will be used for T99W175 module of Foxconn.
> (V2) MBIM QDU support for firmware downloading in the MM plugin

- plugins/rts54hub/rts54hub.quirk
fixed USB\VID_0BDA&PID_5420 and USB\VID_0BDA&PID_5420&I2C_01 fw size range
> plugins: rts54hub: rts54hub.quirk update

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
This means we don't display something like 'Logitech Logitech Product'
when showing the devices on one line.
This is now required in two plugins so move it to common code. Also
support setting the properties in either order to prevent regressions
when using the device name as part of the instance ID.
> Remove the vendor string from the device name where required

- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
Some devices may 'discover' child devices during poll, rather than the
more usual case of adding them as children during setup.
> Watch for children added or removed after setup has been completed

- src/fu-device-list.c
At the moment we saving the new state as 'unknown' which explains why
we're getting so few LVFS reports uploaded for USB devices that perform
a replug...
Tested with a ColorHug2.
> Copy the device update state when replugging

- plugins/acpi-phat/fu-acpi-phat-health-record.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35761
> acpi-phat: Prevent a corrupt PHAT table from allocating ~4GB of memory

- plugins/altos/fu-altos-device.c
- plugins/ata/fu-ata-device.c
- plugins/dell-esrt/fu-plugin-dell-esrt.c
- plugins/dell/fu-plugin-dell.c
- plugins/elantp/fu-elantp-hid-device.c
- plugins/elantp/fu-elantp-i2c-device.c
- plugins/goodix-moc/fu-goodixmoc-device.c
- plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.c
- plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
- plugins/nvme/fu-nvme-device.c
- plugins/solokey/fu-solokey-device.c
- plugins/superio/fu-superio-device.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
- plugins/synaptics-prometheus/fu-synaprom-config.c
- plugins/test/fu-plugin-test.c
- plugins/uefi-capsule/fu-uefi-device.c
- plugins/uefi-dbx/fu-uefi-dbx-device.c
- plugins/vli/fu-vli-pd-device.c
- plugins/vli/fu-vli-pd-parade-device.c
- plugins/vli/fu-vli-usbhub-device.c
- plugins/vli/fu-vli-usbhub-msp430-device.c
- plugins/vli/fu-vli-usbhub-pd-device.c
This is supposed to be 'Sentence case' with no trailing fullstop.
> Standardize some of the device summary text

- plugins/uefi-capsule/fu-uefi-backend-freebsd.c
- plugins/uefi-capsule/fu-uefi-backend-linux.c
This isn't actually doing anything as setting a physical ID invalides
the manually-set ID.
> trivial: Don't set a device ID if setting a physical ID

- libfwupd/fwupd-device.c
- libfwupd/fwupd-self-test.c
This fixes the self tests on old GLib versions as the order of the
GHashTableIter is not guaranteed to be stable.
> trivial: Print the GUIDs in the order they were added

- libfwupdplugin/fu-firmware.c
We were silently depending on 2.61.0 by accident.
> trivial: Don't fail tests on old GLib versions

- plugins/redfish/fu-redfish-backend.c
- plugins/redfish/fu-redfish-request.c
- plugins/redfish/fu-redfish-request.h
Making the redfish plugin disabled on RHEL 8 was... unpopular.
> redfish: Restore compatibility with old libcurl versions

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- src/fu-device-list.c
- src/fu-self-test.c
At the moment the device list auto-removes children when the parent is
removed. This was originally working around the bug that the child
devices had no backend ID, and thus were not matched like the parent
in fu_engine_backend_device_removed_cb() and removed automatically.
Using the workaround means that the children are potentially removed
before the parent depending on the order of the device list -- which
might be modified by replug events.
I think the old cleanup is probably an anti-pattern, and going forward
composite devices should probably define _NO_AUTO_REMOVE_CHILDREN but
we don't want to change this behaviour for plugins already expecting
the old flow, or for devices with no parent backend IDs.
> Add a device flag to control child removal

- src/fu-device-list.c
- src/fu-device-list.h
- src/fu-engine.c
- src/fu-self-test.c
This also means we no longer pass in just one device to the
fu_device_list_wait_for_replug() function, but we rather wait for *all*
of the active devices.
This also cleans up the confusion on whether the engine should wait for
the 'root' device or the child device as either (or both) can be set as
required.
This makes the replug far more predictable for devices that have
children even in bootloader mode.
> Allow multiple devices to set WAIT_FOR_REPLUG

- plugins/emmc/fu-emmc-device.c
/run/udev/data/b* location of eMMC devices appears to be inaccessible
early on in the boot process which makes fwupd to skip eMMC devices if
the daemon started too early. ID_NAME udev attribute is effectively
copied from the sysfs attribute [1], thus making use of it is more
reliable.
[1] https://kernel.googlesource.com/pub/scm/linux/hotplug/udev/+/1ed38f41749dde482e164e692255b60c38b5d876/etc/udev/rules.d/60-persistent-storage.rules#42
> emmc: use sysattr insted of udev attr lookup for device name

- plugins/emmc/fu-emmc-device.c
At this point it has to be present, but better have the check for
correctness sake.
Follow up of https://github.com/fwupd/fwupd/commit/64fa633e3029ff619a2de86e85e7fbb60cc40225
> emmc: add check that "name" sysattr is not NULL

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fwupdplugin.map
- plugins/modem-manager/README.md
- plugins/modem-manager/fu-firehose-updater.c
- plugins/modem-manager/fu-firehose-updater.h
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-mm-utils.c
- plugins/modem-manager/fu-mm-utils.h
- plugins/modem-manager/meson.build
Introduces support for firehose update and qcdm port handling for modem-manager plugin.
Same as #3373 , but adds copying of firehose binary into /lib/firmware/qcom folder and some minor bug fixes.
> Add firehose update with fw copy

- plugins/redfish/fu-redfish-device.c
Although, this only seems provided for PSU devices...
> redfish: Use the HotPluggable attribute if provided

- libfwupd/fwupd-remote.c
- libfwupdplugin/fu-bluez-device.c
- libfwupdplugin/fu-hid-device.c
- libfwupdplugin/fu-i2c-device.c
- libfwupdplugin/fu-ihex-firmware.c
- libfwupdplugin/fu-srec-firmware.c
- plugins/intel-spi/fu-ifd-device.c
- plugins/intel-spi/fu-pci-device.c
- plugins/vli/fu-vli-device.c
I assume at some point we forgot to remove it when converting an object
from FINAL to DERIVABLE and the anti-pattern just got copied around the
codebase...
> trivial: Remove the unused parent instance from the private struct

- plugins/vli/fu-vli-usbhub-firmware.c
This regressed in c255034574c725583afac4a6c7eed901b8ac2d7f which caused
ThinkPad Thunderbolt 3 Workstation Dock updates to fail.
Fixes https://github.com/fwupd/fwupd/issues/3460
> vli: Fix a regression when installing VL820Q7 firmware

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fwupdplugin.map
- plugins/vli/fu-vli-usbhub-device.c
The benefit of using the proxy device is that we can 'use' the proxy
device for device access, but 'report' the progress on the passed
FuDevice instance.
This means the front-end reports the device status correctly when
updating composite devices that us proxies.
The comment always said we should move it to the daemon if another
plugin started doing this, and that is now.
> Open the device proxy in the engine where required

- libfwupdplugin/fu-self-test.c
- plugins/dell/fu-self-test.c
- plugins/uefi-capsule/fu-self-test.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-remote-list.c
- src/fu-remote-list.h
- src/fu-self-test.c
This also speeds up the tests as the amount of pointless i/o is reduced.
Fixes https://github.com/fwupd/fwupd/issues/3522
> trivial: Do not save the self test quirk silo to disk

- plugins/test/fu-plugin-test.c
This commit is a solution to the issue filed at
https://github.com/fwupd/fwupd/issues/3501. It sets a the AC power flag for the
fake webcam device.
> Addition of FWUPD_DEVICE_FLAG_REQUIRE_AC Flag to fu-plugin-test.c

- plugins/powerd/fu-plugin-powerd.c
This adds a condition in the power plugin that permits updates for devices that don't take
any power conditions into account.
> powerd: Adding case for devices that ignore power

- plugins/powerd/fu-plugin-powerd.c
This moves the condition that permits updates for devices that don't account for power so that the plugin passes updates before a method call is made.
> powerd: Moving ignore power case before method call

- plugins/test/fu-plugin-test.c
- src/fu-engine.c
- src/fu-self-test.c
Currently the SUCCESS state overrides NEEDS_REBOOT, thus making the
devices considered for successive get-upgrades within same boot. The
change preserves the NEEDS_REBOOT state. It also adds a missed
'changed' signal, which otherwise would skip updating the persistent
state.
> fu-engine: Preserve NEEDS_REBOOT on successful update

- libfwupdplugin/fu-cabinet.c
This was only true by accident. We'll need another fix for the LVFS to
add the missing NUL to restore compatibility for older clients.
Fixes https://github.com/fwupd/fwupd/issues/3533
> Do not assume the metainfo file is NUL-terminated

- CONTRIBUTING.md
- contrib/reformat-code.py
This is basically implementing `git diff -U0 | clang-format-diff-11 -p1 | sed '/^+/s/g_autoptr (/g_autoptr(/g;/^+/s/sizeof (/sizeof(/g;/^+/s/g_auto (/g_auto{/g' | patch -p0`
> reformat-code.py: add argumentless mode for formatting diffs

- plugins/powerd/fu-plugin-powerd.c
This adds a condition to the powerd plugin that passes updates on devices
that do not give provide valid battery information or whose battery
information is unknown, such as Chromeboxes, which have no battery to
read.
> powerd: Enable updates on devices without battery

- .github/workflows/main.yml
There have been a few jobs that were left running an hour pulling
a file, and that shouldn't block us and waste CI minutes.
> trivial: ci: timeout freebsd CI after 20 minutes

- plugins/dfu/dfu.quirk
Specify the Flags in dfu.qurik for Poly Studio R30, P5 and E70.
> dfu: Add support for more Poly usb devices

- .pre-commit-config.yaml
- CONTRIBUTING.md
- contrib/reformat-code.py
This should let someone who failed to set it up the first time before they committed easily run it.
Workflow I envision:
1. Person does some cool new feature but forgot to run contrib/setup first.
2. We tell them to fix it up, adjust for pre-commit CI failure
3. They run `./contrib/setup`, but their commit is still unhappy because pre-commit runs "during" commit.
4. They run `./contrib/reformat-code.py master` and their code is reformatted.
> Some adjustments to make contrib/reformat-code.py more friendly

- plugins/powerd/fu-plugin-powerd.c
This CL moves the battery information retrieval into a new function,
called "fu_plugin_powerd_callback()", which returns the information in a
struct.
This information is then used in fu_plugin_update_prepare() for battery
checks. There is also a g_timeout_add() function being created in
fu_plugin_startup() in order to enable the plugin to repeatedly send a method
call to powerd.
fu_plugin_update_prepare is removed as its functionality is now handled
by src/fu-engine.c
> powerd: Creating recurring powerd callback

- plugins/powerd/meson.build
snap has an older glib and the plugin fails to compile.
> trivial: only build powerd on new enough glib

- plugins/redfish/fu-plugin-redfish.c
- src/fu-plugin-list.c
We don't want to show the big warning about the missing ESRT on server
hardware that is managed by a BMC:
WARNING: UEFI capsule updates not available or enabled in firmware setup
See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
> redfish: Disable the uefi_capsule plugin if coldplug succeeded

- plugins/dfu/dfu.quirk
Specify the Flags in dfu.qurik for Poly Studio P21's camera.
> dfu: Add support for Poly Studio P21 usb device

- plugins/elantp/fu-elantp-hid-device.c
FuElantpHidDevice derives from FuUdevDevice, not FuUsbDevice -- and the
former does not define a class->setup vfunc.
Fixes https://github.com/fwupd/fwupd/issues/3548
> elantp: Fix a crash when starting the daemon

- plugins/realtek-mst/fu-realtek-mst-device.c
- plugins/realtek-mst/realtek-mst.quirk
The RTD2141B has the same update protocol as RTD2142, but the Chromebook
targets that use it require us to find the drm_dp_aux_dev i2c channel
differently because the AMD display driver doesn't give each output a
unique name in sysfs like the Intel one does, so it must be found by walking sysfs from the drm
device representing an output (which does have a unique name).
cc @djcampello
> realtek-mst: add support for RTD2141B

- plugins/redfish/fu-plugin-redfish.c
- plugins/redfish/fu-redfish-backend.c
- plugins/redfish/redfish.quirk
- src/fu-tool.c
- src/fu-util.c
Some versions of XCC do not send the Base.1.10.ResetRequired message.
> redfish: Add a per-vendor quirk to set all devices as requiring a reboot

- plugins/ebitdo/fu-ebitdo-device.c
Limits copying the get version response payload to the size of the out buffer.
Devices that return a larger payload pack the necessary version information at the beginning of the payload.
Fixes: #1661
> Fix detection of 8Bitdo wireless usb adapter

- plugins/modem-manager/fu-qmi-pdc-updater.c
> modem-manager: add support for compiling libqmi-glib 1.26.0 and later

- libfwupdplugin/fu-plugin-private.h
- libfwupdplugin/fu-plugin-vfuncs.h
- libfwupdplugin/fu-plugin.c
- plugins/jabra/fu-plugin-jabra.c
- plugins/logind/fu-plugin-logind.c
- plugins/powerd/fu-plugin-powerd.c
- src/fu-engine.c
All the other vfuncs have 'plugin, device, flags' but prepare and
cleanup vfuncs being 'plugin, flags, device' order has been triggering
my OCD for the last few years.
We've just broken the symbol names, so it's the right time to fix this.
> Fix cleanup and plugin to have the correct args order

- contrib/setup
gi-docgen requires 3.3.3 or later, but some of the distro packages
are too old.  Upgrade them to make the default
```
meson build
```
work out of the box
> trivial: contrib/setup: update markdown if it's too old

- plugins/vli/vli-usbhub.quirk
Thank you Mario, for bringing ./contrib/reformat-code.py to our attention. We were not aware a clang format script had been made. Much help!
Added VL819 and VL822 to vli-usbhub quirk file. We're not sure if our local fwupdmgr get-device is having cocktails with edit distance one but we'll attach our output for your viewing pleasure just in case...
> vli: VL819 into quirk

- plugins/dfu/dfu.quirk
- plugins/dfu/fu-dfu-common.h
- plugins/dfu/fu-dfu-device.c
Some Poly usb devices report zero in the bwPollTimeout field of
GET_STATUS request. The host can issue the next DFU_DNLOAD
request immediately without any delay.
Introduced a private flag to skip the default DNLOAD timeout
(5ms) fix. It could remarkably reduce the firmware downloading
time taking into account the large firmware (more than 500MB).
> dfu: Introduct a quirk to allow zero polltimeout in dfuDNLOAD.

- .github/workflows/main.yml
- contrib/ci/build_freebsd_package.sh
The changes fix two problems:
* The extension of the generated artifact is `.pkg`, not `.txz` 
* The generated `pkg-plist` was not taken into account during the package build
The build must be cleaned when the new `pkg-plist` appears. Build system creates stage directories based on the `pkg-plist`, which are used to create the package. 
PR fixes https://github.com/fwupd/fwupd/pull/3578.
> FreeBSD CI fix

- libfwupdplugin/fu-cabinet.c
- libfwupdplugin/fu-self-test.c
Archives uploaded to LVFS will have checksums written by hexdigest
and be set to lowercase, but hand generated archives this may not
be true.
For maximum compatibility with the most fwupd versions they should
be written in lowercase, but in case they aren't, convert to lowercase.
Reference https://github.com/fwupd/firmware-lenovo-thinkpad/issues/145
> Forcefully set checksums found in cabinet files to lowercase

- plugins/tpm-eventlog/meson.build
Reproducible by manually calling failing build targets first
```
ninja -C build plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog-common.c.o
ninja: Entering directory `build'
[1/1] Compiling C object plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog-common.c.o
FAILED: plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog-common.c.o
cc -Iplugins/tpm-eventlog/fwupdtpmevlog.p -Iplugins/tpm-eventlog -I../plugins/tpm-eventlog -I. -I.. -Ilibfwupd -I../libfwupd -Ilibfwupdplugin -I../libfwupdplugin -I/usr/include/libxmlb-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/gudev-1.0 -I/usr/include/json-glib-1.0 -I/usr/include/gusb-1 -I/usr/include/libusb-1.0 -I/usr/include/tss2 …
```
> trivial: fix a compilation dependency error (Fixes: #3657)

- plugins/dfu/dfu.quirk
Add VID (AVer) & PID (ATLAS CAM / CAM520 Pro2) in dfu qurik
> dfu: add quirks for AVer ATLAS CAM/CAM520 Pro2

- meson.build
this patch makes meson look for gi-docgen on the host system instead in cross paths
> trivial: make gi-docgen a host dependency on cross

- plugins/dell-dock/fu-dell-dock-common.h
- plugins/dell-dock/fu-plugin-dell-dock.c
This commit resolves a warning message at runtime:
- no GUIDs for device ...
fu_device_add_child emits a child-added signal afterwards the engine
try to add given device and verify whether GUIDs is set.
> dell-dock: add device GUID earlier even setup yet done

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- src/fu-util-common.c
This is for devices that are still registered with a receiver but are
no longer in range or in a high power state.
> Add support for an 'unreachable' device flag

- data/device-tests/hardware.py
This also fixes the bug where you can't recover a Unifying device stuck
in bootloader mode if the 'default' protocol is not the one that matches.
> device-tests: Do not use a deprecated method

- plugins/uefi-capsule/README.md
Capsule update on-disk was added a while ago.
Document the config file changes and limitations on firmwares that's
doesn't support RT->SetVariable
Signed-off-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
- [ x] Documentation
> uefi-capsule: Update documentation for CoD

- libfwupd/fwupd-common.c
- libfwupd/fwupd-device.c
- libfwupd/fwupd-release.c
Don't assume zero always means 'skip'.
> Show HSiLevel=0 attributes in JSON security output

- src/fu-engine.c
- src/fu-history.c
- src/fu-history.h
- src/fu-security-attr.c
- src/fu-security-attr.h
Converting all security attributes to JSON and write them into hsi_security tables to record the changing of HSI valuer.
This commit consists of two-part:
1. Add a hsi_history table and schema.
2. JSON conversion and DB writing.
> Converting security attribute into json and write to hsi_history table.

- plugins/uefi-capsule/fu-uefi-cod-device.c
- plugins/uefi-capsule/fu-uefi-grub-device.c
- plugins/uefi-capsule/fu-uefi-nvram-device.c
We want to be able to differenciate failures for a specific update
method, e.g. finding if should be enabling CoD by default or not.
> uefi-capsule: Add the apply method to the uploaded report

- contrib/ci/dependencies.xml
- contrib/ci/ubuntu.sh
- data/tests/efi/efivars/meson.build
- data/tests/efi/meson.build
- data/tests/meson.build
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/meson.build
- plugins/ata/fu-self-test.c
- plugins/nvme/fu-self-test.c
- plugins/platform-integrity/fu-plugin-platform-integrity.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
Beyond the failures that happened in ATA and NVME plugins, other parts in the codebase are making writes into `data/tests` or `plugins/synaptics-mst/tests`.  We shouldn't be allowing this at all.  Fix those and then enforce that everything touched is in `build/` or `/tmp` during the run.
> Run self tests as nobody for at least one CI target

- libfwupd/fwupd-security-attr.c
- libfwupd/fwupd-security-attr.h
- libfwupd/fwupd.map
- plugins/cpu/fu-cpu-device.c
- plugins/intel-spi/fu-intel-spi-device.c
- plugins/msr/fu-plugin-msr.c
- plugins/pci-bcr/fu-plugin-pci-bcr.c
- plugins/pci-mei/fu-plugin-pci-mei.c
- plugins/tpm-eventlog/fu-plugin-tpm-eventlog.c
- plugins/tpm/fu-plugin-tpm.c
- plugins/uefi-pk/fu-plugin-uefi-pk.c
- src/fu-tool.c
This indicates the GUID in some way contributed to the result decided.
It also allows us to match the submitted HSI results back to a firmware
stream on the LVFS, which allows us to allow vendors to see a subset of
results for uploaded devices.
> Allow adding GUIDs to each HSI security attr

- src/fu-engine.c
No active firmware on the LVFS depends on either.
> Remove the hardcoded legacy runtime requirements

- libfwupdplugin/fu-srec-firmware.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38196
> trivial: Fix a tiny memory leak for an invalid SREC file

- plugins/tpm-eventlog/fu-tpm-eventlog-device.c
> trivial: system firmware may primarily use sha256 bank instead sha1

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/vli/fu-vli-usbhub-device.c
This fixes a regression caused by 15b668c, we should have been more careful.
Fixes https://github.com/fwupd/fwupd/issues/3732
> Fix a regression in flashing the Dell dock

- plugins/flashrom/fu-flashrom-cmos.c
- plugins/flashrom/fu-flashrom-cmos.h
- plugins/flashrom/fu-flashrom-internal-device.c
- plugins/flashrom/meson.build
Reset the CMOS based on a private flag. Tested on coreboot using an
offset of 123. Required when a CMOS layout or default option has
changed as the resulting flash will have 0's for the modified option.
> plugins/flashrom: Add private flag to reset CMOS

- plugins/wacom-usb/fu-wac-firmware.c
Half a million new-lines was taking a long time to parse.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38381
> wacom-usb: Abort on invalid SREC files early to avoid a fuzzing timeout

- plugins/flashrom/fu-flashrom-cmos.c
ioperm returns -1 for an error and 0 for success
> plugins/flashrom: Fix logic in reset cmos

- plugins/superio/fu-plugin-superio.c
- plugins/superio/fu-superio-device.c
- plugins/superio/superio.quirk
The chipset doesn't define the port like I guessed, as Tuxedo and Star
Labs both want to use a 0x5570 with different values.
> superio: Make the ports and timeouts specific to the DMI model

- contrib/ci/dependencies.xml
- contrib/ci/void.sh
i tried to update the ci integration for void linux.
the current packaged version is here
https://github.com/void-linux/void-packages/blob/master/srcpkgs/fwupd/template
should you need to correct something
it would be great to run a regular xbps-src build,
which would show cross compilation issues.
> update void linux ci target

- plugins/pixart-rf/fu-pxi-receiver-device.c
We actually check for fu_device_add_guid() not being an actual GUID,
but in the future we'll be warning if we do this magic fallback as it
hides not-quite-GUID typos.
No behaviour change.
> pixart-rf: Use the correct method to add an instance ID

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
Typically, this can be triggered with:
* create parent
* set parent physical ID
* add new child to parent
* set parent logical ID
> Update the child composite ID if the parent changes

- src/fu-util.c
Typo? Merge artifact? Who knows.
> trivial: Remove the double warning when reinstalling composite firmware

- plugins/msr/fu-plugin-msr.c
I'm finding errors in a crostini container that the MSR plugin tries
to run and fails later.  The plugin just shouldn't be passing startup
if /dev/cpu isn't present.
> trivial: msr: only run if /dev/cpu is present

- plugins/uefi-recovery/fu-plugin-uefi-recovery.c
- src/fu-tool.c
Some plugins will need to check hardware in `fu_plugin_startup` and `fwupdtool get-plugins` will show invalid output even when run as root.  To fix this, initialize smbios reading for the context.
CC @therealjuanmartinez
> Improve get-plugins

- plugins/dell/fu-plugin-dell.c
Since commit 078beaf, device de-duplication between plugins doesn't
work anymore.  Both the TPM and Dell plugin create a device with an
identical physical ID and no logical ID.  This makes the device list
think whichever plugin probes second is just updating the first.
To avoid this problem, set a logical ID in the Dell plugin, ensuring
that the device ID built from physical + logical is different from the
TPM plugin.
The side effect of this is that both devices will export into the device
list, but the TPM plugin's devices will not be upgradable.
> Fix probing the Dell TPM (Fixes: #3759)

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-ihex-firmware.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-srec-firmware.c
- libfwupdplugin/fwupdplugin.map
- plugins/ccgx/fu-ccgx-firmware.c
- plugins/wacom-usb/fu-wac-firmware.c
Using fu_common_strnsplit() has the drawback that a malicious user (or
a fuzzer!) could create a file with 5,000,000 newlines, and then pass
that into any parser that tokenizes into lines. This causes millions of
tiny allocations and quickly dirties hundreds of megabytes of RSS due
to heap overheads.
Rather than splitting a huge array and then processing each line, set
up a callback to process each line and only allocate the next string if
the token was parsed correctly. This means that we only dup the buffer
just once before we start parsing rather than allocating everything and
then failing at the first hurdle.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38696
> Add new API for splitting an untrusted string

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fwupdplugin.map
- plugins/dfu/fu-dfu-tool.c
- plugins/logitech-hidpp/fu-logitech-hidpp-radio.c
- plugins/modem-manager/fu-plugin-modem-manager.c
- plugins/synaptics-prometheus/fu-synaprom-config.c
- plugins/vli/fu-vli-usbhub-pd-device.c
- src/fu-tool.c
Quite a few plugins are using a FuDeviceLocker to detach then attach in
the error path, and finding them isn't easy as we explicitly cast to a
FuDeviceLockerFunc.
For sanity, just provide both symbols so we can do the right thing in
both cases. It seems like a sensible thing to allow.
Fixes https://github.com/fwupd/fwupd/issues/3771
> Restore the ABI for fu_device_detach() and provide new symbols

- plugins/README.md
The commit 6b0e66354b1b7007cb525a3d3c8280bf9001e880 moved the header to
libfwupdplugin.
> plugin: fix URL to fu-device-metadata.h

- data/bash-completion/fwupdmgr.in
- data/bash-completion/fwupdtool.in
- data/daemon.conf
- libfwupd/README.md
- libfwupd/fwupd-enums.h
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
- src/fu-main.c
- src/fu-tool.c
- src/fu-util.c
This functionality broke a number of releases ago as part of
implementing device inhibition and was just noticed now.
Instead of fixing it, the preference seems to be to remove the
functionality as it exists today as inhibitions can happen for
a number of reasons.
To still allow people to override these power warnings (such as during
development) add a new daemon configuration item that can be used.
Fixes: #3778
> Remove support for `--ignore-power` by frontends

- data/remotes.d/lvfs.conf
- data/remotes.d/meson.build
- libfwupd/fwupd-self-test.c
- meson_options.txt
This is a patch that I have to regenerate almost every rebase. Just
move it upstream as it's probably not RHEL specific.
> Allow installing the LVFS remote, but disabled

- contrib/setup
This will help for any local checkouts using the old branch name.
> trivial: add a helper to contrib/setup to rename branches

- libfwupd/fwupd-context-test.c
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd-thread-test.c
- libfwupdplugin/fu-fuzzer-main.c
- libfwupdplugin/fu-self-test.c
- plugins/ata/fu-self-test.c
- plugins/dell/fu-self-test.c
- plugins/dfu/fu-dfu-self-test.c
- plugins/dfu/fu-dfu-target-stm.c
- plugins/dfu/fu-dfu-target.c
- plugins/lenovo-thinklmi/fu-self-test.c
- plugins/nvme/fu-self-test.c
- plugins/optionrom/fu-self-test.c
- plugins/redfish/fu-self-test.c
- plugins/synaptics-mst/fu-self-test.c
- src/fu-self-test.c
Note that g_assert() should not be used in unit tests, since it is a
no-op when compiling with G_DISABLE_ASSERT. Use g_assert() in production
code, and g_assert_true() in unit tests.
See https://github.com/fwupd/fwupd/issues/3790
> trivial: Do not use g_assert() in self test code

- libfwupdplugin/fu-cfu-common.c
- libfwupdplugin/fu-cfu-common.h
- libfwupdplugin/fwupdplugin.h
- libfwupdplugin/fwupdplugin.map
- libfwupdplugin/meson.build
- plugins/elanfp/fu-elanfp-device.c
- plugins/elanfp/meson.build
We need these in the CFU plugin too.
> trivial: Export the CFU enum conversion functions

- plugins/superio/fu-superio-device.c
The GUIDs are in use by old firmware, and so of course we have to
continue adding them.
See https://github.com/fwupd/fwupd/pull/3734#issuecomment-919829988
> superio: Continue to add the SuperIO-IT8587 instance IDs

- plugins/synaptics-cape/README.md
- plugins/synaptics-cape/fu-synaptics-cape-device.c
- plugins/synaptics-cape/fu-synaptics-cape-firmware.c
- plugins/synaptics-cape/synaptics-cape.quirk
Add new option can receive HID report over Interrupt In endpoint
instead of control endpoint. This new option is enabled by default and
can be turned off by setting 'InReportViaInterrupt = off' in quirk file.
This commit also fixes a false error within software reset function.
> synaptics-cape: Add interrupt endpoint support

- plugins/uefi-capsule/make-images.py
It would seem that some EFI BMP loaders are unable to flip the image
and hang when trying to load the UX capsule.
This was a real PITA to debug.
Many thanks to Sean Rhodes <sean@starlabs.systems> for all the help.
> Write the BMP image upside down to avoid using a negative bitmap height

- src/fu-engine.c
The commit 488f2e1f37b163c5e32ee340d3fad3b7ea79119e has moved some parsers and has created a typo in the `efi-firmware-volume` ID.
> fu-engine: Fix typo in the efi-firmware-volume ID

- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
If bgrt is the same size as the screen, show ux-capsule on top of bgrt.
> plugins/uefi-capsule: Force ux-capsule over full size bgrt

- plugins/uefi-capsule/uefi-capsule.quirk
#3823 makes it work, so enable for all.
> plugins/uefi-capsule: Enable ux-capsule for all starlabs laptops

- plugins/flashrom/fu-flashrom-internal-device.c
Resetting the CMOS on branch switch will cause a lock on reboot which
requires hard power off.
> plugins/flashrom: Reset CMOS aftering writing region

- libfwupdplugin/fu-hid-device.c
- libfwupdplugin/fu-hid-device.h
Also, print the interface number and EP addresses in the ->to_string
handler.
> Allow using interrupt transfers for HID devices

- libfwupdplugin/fu-cabinet.c
- meson.build
This is new in version 1.5, but may be backported.
> trivial: Use new libgcab API where possible

- libfwupdplugin/fu-device.c
This allows us to perform a callback when the parent instance is set or
changed.
> trivial: Notify when the FuDevice:parent is set

- plugins/synaptics-rmi/meson.build
if synaptics-rmi is disabled and gnutls is not used, the configure fails
move the synaptics-rmi test check behind the "plugin_synaptics_rmi" option
the issue presents as:
```
plugins/synaptics-rmi/meson.build:44:2: ERROR: Unknown variable "gnutls".
```
> synaptics-rmi: fix meson configure when building tests

- contrib/fwupd.spec.in
- plugins/uefi-capsule/meson.build
- plugins/uefi-capsule/tests/example/.gitignore
- plugins/uefi-capsule/tests/example/build.sh
- plugins/uefi-capsule/tests/example/firmware.metainfo.xml
Enable the 'test' plugin in /etc/fwupd/daemon.conf and then use
something like:
fwupdmgr install plugins/test/example/firmware.cab
Fixes https://github.com/fwupd/fwupd/issues/3441
> Add a test UEFI device that can be used to test capsules

- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-plugin.h
- libfwupdplugin/fwupdplugin.map
- plugins/elantp/fu-plugin-elantp.c
- plugins/redfish/fu-plugin-redfish.c
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
During my fwupd startup fu_plugin_has_custom_flag gets called 21 times
which causes all HWIDs to be enumerated with 346 calls to the quite
expensive fu_context_lookup_quirk_by_id() function.
Move the flag to a private hashset and enumerate the HWIDs only during
startup. There's nothing plugin specific about them anyway...
> Speed up daemon startup by 15%

- plugins/uefi-recovery/fu-plugin-uefi-recovery.c
> uefi-recovery: Set the device context to remove a daemon warning

- libfwupdplugin/fu-plugin.c
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
This means that if the user has a single ESRT entry with a GUID of
00000000-0000-0000-0000-000000000000 then none of them work correctly.
Fixes https://github.com/fwupd/fwupd/issues/3950
> uefi-capsule: Skip devices that fail coldplug

- meson.build
The flashrom plugin can use inb/outb to do a CMOS reset. The build gates
this on whether io.h exists (since bc43ad), but on musl the io.h header
can exist but inb/outb won't be defined.
Thus, fwupd builds with musl on non-x86 platforms will fail to link. Fix
this by checking for both io.h and that outb() is defined.
Signed-off-by: Ross Burton <ross.burton@arm.com>
> build: check that outb is present in io.h

- libfwupdplugin/fu-plugin.c
This comment became outdated with #3940, where the `NULL` check for `priv->ctx` that followed by early return was removed
> trivial: remove outdated comment

- plugins/thunderbolt/fu-thunderbolt-device.c
By not exposing either UPDATABLE or UPDATABLE_HIDDEN the device is
hidden in gnome-firmware. Do what all the other devices do.
> thunderbolt: Use fu_device_inhibit() to correctly use UPDATABLE_HIDDEN

- libfwupd/fwupd-device.c
- libfwupd/fwupd-self-test.c
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
- src/fu-self-test.c
We never show the fu_device_to_string() output to the user in normal
circumstances, and it's super useful for it to match the FuFirmware
format.
> trivial: Use the device GType as the debugging root

- plugins/dfu/fu-dfu-device.c
This was a regression caused in aaa77c6f513d65c38d70b95447460c8ed220dca5.
> dfu: Fix all devices that rely on use-any-interface

- libfwupdplugin/fu-fuzzer-firmware.c.in
We want to abort early rather than relying on other problems like segfault or OOM.
> trivial: Crash the fuzzer on critical warning

- plugins/tpm/meson.build
On 0.58.1:
ERROR: Bad source of type 'SharedModule' in target 'tpm-self-test'.
> trivial: Fix build error with old meson versions

- libfwupd/fwupd-common.c
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-util-common.c
This allows us to map a specific component on the LVFS without guessing
by using the generated checksum.
> Export the component release ID over DBus

- plugins/intel-spi/fu-intel-spi-device.c
- plugins/intel-spi/generate-quirk.py
- plugins/intel-spi/intel-spi.quirk
This was missed in the addition of 40c7f7ba21a58593c74ee5f5e4766e64036a3c4d
> intel-spi: Use lowercase flag names

- libfwupd/fwupd-client.c
- libfwupd/fwupd-self-test.c
This probably regressed in 70f9124545e35c1e55915594722f5aa8c7b7edcc as
the callers actually expect an error in the GDBusError domain, rather
than one fixed up in the FwupdError domain.
Fixes https://github.com/fwupd/fwupd/issues/4014
> Fix running the tests when fwupd is not installed

- libfwupdplugin/fu-cabinet.c
Fixes https://github.com/fwupd/fwupd/issues/4022, but requires a newer
libxmlb to be installed.
> Show an error when loading XML with multiple <component> tags

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-util-common.c
These allow us to tag components as being part of a set, e.g. a BKC.
> Add support for LVFS component tags

- libfwupdplugin/fu-archive-firmware.c
- libfwupdplugin/fu-archive-firmware.h
- libfwupdplugin/fwupdplugin.h
- libfwupdplugin/fwupdplugin.map
- libfwupdplugin/meson.build
- plugins/fastboot/fu-fastboot-device.c
- src/fu-engine.c
Add a FuFirmware superclass that allows us to parse an new archive in the archive. We already do this for fastboot and we're about to add another.
> Add FuArchiveFirmware

- data/bash-completion/fwupdmgr.in
- data/daemon.conf
- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
- src/fu-config.c
- src/fu-config.h
- src/fu-engine-helper.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
- src/fu-util.c
- src/org.freedesktop.fwupd.xml
Install or downgrade firmware on all devices to make the system match
a well known set. This allows two things:
* factory recovery where a device in the field has been upgraded
* ensuring a consistent set of tested firmware for a specific workload
A tag is assigned either during upload or added post-upload on the LVFS
which is included in the metadata. A single firmware can be marked with
multiple tags, and tags can be duplicated for different firmwares.
> Allow an option sync to a known set of firmware versions

- libfwupdplugin/fu-device-locker.c
The things we're closing is probably a FuUsbDevice subclass which has
the GUsbDevice as an instance variable, not a subclass of GUsbDevice.
> trivial: Do not check the device superclass when closing

- src/fu-history.c
This behaviour now matches the D-Bus interface document.
> trivial: Use 0 for no limit on security attributes

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/thunderbolt/fu-plugin-thunderbolt.c
- plugins/thunderbolt/fu-self-test.c
- plugins/thunderbolt/fu-thunderbolt-device.c
- plugins/thunderbolt/fu-thunderbolt-device.h
- src/fu-udev-backend.c
- src/fu-usb-backend.c
This change offline ports in the host controller
for retimers to enumerate in the NDA case.
-offline and rescan usb4 ports
-this enable enumeration of the retimers
-updates nvm to the enumerated retimers
-online usb4 port this will de-enumerate retimers
BUG=b:187506425
TEST=emerge-volteer fwupd
Change-Id: I1fde5675f27e91e18951b72f24fbec4113410807
> thunderbolt: set ports offline on host controller

- meson.build
- src/fu-remote-list.c
This can be reproduced using sysctl fs.inotify.max_user_instances=25
and then running the daemon.
> Fixup the GLib error message when inotify/max_user_instances is too low

- contrib/ci/build_windows.sh
- meson_options.txt
- plugins/cpu/meson.build
I think using the plugin_uefi_pk option was probably a typo.
> trivial: Add the missing plugin_cpu

- libfwupdplugin/fu-plugin.c
At the moment only the order is considered, and the rest is unspecified
by the filesystem.
> Make the plugin startup order deterministic

- plugins/fastboot/README.md
- plugins/fastboot/fastboot.quirk
- plugins/fastboot/fu-fastboot-device.c
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/modem-manager.quirk
The Quectel EG25-G modem is used in the [Pine64 PinePhone](https://pine64.org/pinephone) and [PinePhone Pro](https://pine64.org/pinephonepro) .
By default it ships with an old firmware version which can be upgraded to newer versions from Quectel or a more open firmware developed at https://github.com/Biktorgj/pinephone_modem_sdk.
The current `fwupd` version sees the Quectel EG25-G through the `modem-manager` plugin as upgradable using the `fastboot` plugin. However, the Quectel EG25-G fastboot bootloader is picky when you interact with it:
- Blocksize must be `16384` bytes, not a byte more or less. If you still try another size, the next chunk the `fastboot` plugin writes to the modem fails which reboots the bootloader. I discovered this by analyzing the USB traffic …
> modem-manager: add Quectel EG25-G modem support

- plugins/fastboot/fastboot.quirk
- plugins/modem-manager/fu-mm-device.c
With #4076 merged, I have a following up MR:
I did more tests with bigger firmware packages and in some rare cases, 100ms between every read/write operation is too low for a stable upgrade process. Increasing this to 250ms improves the upload stability a lot.
Without it, it might be that the upgrade process stalls after ~5-10 minutes as the bootloader doesn't respond anymore.
To improve the safety of upgrades, I added a flag to the `modem-manager` to require AC power before starting the upgrade.
This is more safe as you don't want to brick the modem due to an empty battery on a laptop or in my case a phone.
- Pine64 PinePhone
- Quectel EG25-G modem
- postmarketOS edge
- fwupd 90baeaabbc94589512642fe970eecbd852ae3532
CC: @aleksander0m @ivanmikh
> Quectel EG25-G: improve upload stability and require AC power

- contrib/ci/fwupd_setup_helpers.py
```
Install developer-friendly **unsafe** PolicyKit rules into /etc/polkit-1/rules.d? (y/N) n
Traceback (most recent call last):
File "/home/supermario/fwupd/./contrib/ci/fwupd_setup_helpers.py", line 154, in <module>
test_markdown()
File "/home/supermario/fwupd/./contrib/ci/fwupd_setup_helpers.py", line 34, in test_markdown
import markdown
ModuleNotFoundError: No module named 'markdown'
Collecting markdown
Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
|████████████████████████████████| 97 kB 1.1 MB/s
Collecting importlib-metadata>=4.4
Downloading importlib_metadata-4.8.2-py3-none-any.whl (17 kB)
Collecting zipp>=0.5
Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Installing collected packages: zipp, importlib-metadata, markdown
Successfully installed importlib-metadata-4.8.2 …
```
> trivial: contrib/setup: if markdown isn't installed don't show an error

- plugins/flashrom/flashrom.quirk
Remove "number" version format to allow different versioning (i.e. 7.4 and 8)
> plugins/flashrom: Remove number version format for StarLabs

- plugins/uefi-capsule/README.md
- plugins/uefi-capsule/uefi_capsule.conf
The ESP is autodetected only if UDisks is available, but this was not explicitly documented so far.
Fixes #4103
> uefi-capsule: clarify UDisks requirement for ESP autodetection

- plugins/uf2/fu-uf2-firmware.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42789
> uf2: Fix fuzzer timeout when parsing an invalid UF2 file

- plugins/modem-manager/fu-plugin-modem-manager.c
Modem removals are logged, but nothing is logged when a modem is added.
Makes it easier for debugging.
> modem-manager: log when modem is added

- plugins/modem-manager/README.md
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/modem-manager.quirk
- Add support for setting the firmware branch in `modem-manager` plugin.
- Read firmware branch using a custom AT command from the modem.
- Configure the quirk for the Quectel EG25-G modem to use `AT+GETFWBRANCH` as custom AT command to get the firmware branch
**Alternative firmware running 0.5.1 on branch `FOSS-002`**:
```
└─QUECTEL Mobile Broadband Module:
Device ID:          976c4a39e87f61e6940ea6a8d39c583cfa99615f
Summary:            Quectel EG25-G modem
Current version:    0.5.1
Vendor:             QUALCOMM INCORPORATED (USB:0x2C7C)
Release Branch:     FOSS-002
GUIDs:              db379a33-254f-5140-b37e-d36ae7e5c039
1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125 …
```
> Modem manager branch support

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
- plugins/uefi-capsule/uefi-capsule.quirk
- plugins/upower/fu-plugin-upower.c
- src/fu-engine.c
Most vendors do not mirror the firmware update to an external display,
and some don't behave correctly when the lid is shut and the machine is
docked.
Fixes https://github.com/fwupd/firmware-lenovo/issues/181
> Do not allow UEFI updates when the lid is closed

- snap/snapcraft.yaml
Github has a read-only mirror of FDO gitlab which is expected to
be more reliable than FDO gitlab.
> trivial: snap: pull from github instead of gitlab

- plugins/dfu/dfu-tool.1
- plugins/uefi-capsule/fwupdate.1
- plugins/uefi-dbx/dbxtool.1
- src/fwupdagent.1
- src/fwupdmgr.1
- src/fwupdtool.1
They're marked in the man page as section 8 but installed into 1.
They should be installed into 1 as they're not admin tools.
> trivial: fix man page sections

- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fu-usb-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/analogix/fu-analogix-device.c
- plugins/ccgx/fu-ccgx-hpi-device.c
- plugins/colorhug/fu-colorhug-device.c
- plugins/cros-ec/fu-cros-ec-usb-device.c
- plugins/elanfp/fu-elanfp-device.c
- plugins/fastboot/fu-fastboot-device.c
- plugins/goodix-moc/fu-goodixmoc-device.c
- plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
- plugins/logitech-hidpp/fu-logitech-hidpp-bootloader.c
- plugins/steelseries/fu-steelseries-device.c
- plugins/steelseries/fu-steelseries-gamepad.c
- plugins/synaptics-prometheus/fu-synaprom-device.c
- plugins/system76-launch/fu-system76-launch-device.c
It's a common action for plugins to call FuUsbDevice->open() then claim
interfaces, and then release them just before FuUsbDevice->close().
It's also something a lot of plugins get wrong, so provide common code
to handle it correctly in one place.
> Add fu_usb_device_add_interface() for plugins to use

- src/fu-engine.c
Also, check both after ->register() rather than using a warning.
> trivial: Use inhibits for missing critical device data

- contrib/debian/rules
> trivial: disable logitech bulk controller on ubuntu by default

- libfwupdplugin/fu-backend.c
- libfwupdplugin/fu-backend.h
- libfwupdplugin/fwupdplugin.map
- src/fu-engine.c
- src/fu-usb-backend.c
Decrease the GUsb polling interval when any of the devices is in
`WAIT_FOR_REPLUG` on when running on Windows. Any device that can
re-enumerate much faster than the default 1000ms may be missed and the
detach may fail.
Linux doesn't have this problem as it has `LIBUSB_CAP_HAS_HOTPLUG`.
> Increase the chances of success of WAIT_FOR_REPLUG on WIN32

- plugins/redfish/fwupd-redfish.conf
This leads to reports of:
systemd-modules-load[1710]: Failed to insert 'ipmi_si': No such device
systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
> redfish: Do not autoload ipmi-si to avoid warning on non-server hardware

- src/fu-tool.c
This should make it so that the message doesn't pop up for someone
who has used udev rules that match permissions to do
```
fwupdtool install-blob --plugins=dfu foo.bin
```
Unless there really was a failure.
@hughsie, I know you considered this before, but I wanted to give it another thought and see if we can overcome anything negative by doing it this way.
> Move root user ID check message into the error path for commands

- plugins/dell-dock/fu-dell-dock-common.c
- plugins/dell-dock/fu-dell-dock-common.h
- plugins/dell-dock/fu-dell-dock-hub.c
- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/dell-dock/fu-dell-dock-i2c-mst.c
- plugins/dell-dock/fu-dell-dock-i2c-tbt.c
- plugins/dell-dock/fu-dell-dock-status.c
- plugins/dell-dock/fu-dell-dock-usb-usb4.c
- plugins/dell-dock/fu-plugin-dell-dock.c
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
- src/fu-device-list.c
At the moment a lot of the failures are only visible when running the
daemon in verbose mode, and the inhibit functionalit provides us a way
to unset FWUPD_DEVICE_FLAG_UPDATABLE from multiple places, as well as
setting the update error for the user to see why.
> Show why devices are not marked as updatable

- plugins/modem-manager/fu-plugin-modem-manager.c
When a modem is discovered through udev after upgrading it, the context was not passed.
This resulted in the following messages in the log:
```
FuDevice             no FuContext assigned for FuMmDevice:
```
Passing the context fixes it.
ModemManager gives all controls to fwupd when upgrading by inhibiting the modem through the modem-manager plugin.
However, after upgrading, the controls should be given back to ModemManager by uninhibiting the modem. That last part was missing in the case of udev discovery. Because of this, ModemManager saw the modem but didn't expose it as it remained inhibited. Restarting ModemManager or rebooting the device worked around the issue, but didn't solve the cause of it.
Therefore, uninhibit as well when a modem is rediscovered through …
> Modem modemanger udev context

- plugins/uefi-capsule/fu-uefi-bootmgr.c
- plugins/uefi-capsule/fu-uefi-common.c
- plugins/uefi-capsule/fu-uefi-common.h
The logic was built on the presumption of Ubuntu core which doesn't
have /etc/os-release.  Since other distributions do have /etc/os-release
adjust the logic to instead build the path explicitly.
> Fix the logic for removable fallback path in uefi-capsule

- plugins/ebitdo/ebitdo-legacy.quirk
- plugins/ebitdo/ebitdo.quirk
This is the ID assigned to STMicroelectronics... more specifically for
a mini LED display. It also seems to be used by other vendors who also
did not change the default from the devkit, e.g. the Vaydeer Multimedia
Console.
Fixes https://github.com/fwupd/fwupd/issues/4180
> trivial: Do not match the legacy bootloader VID/PID

- src/fu-util-common.c
By default it shows just a blank line right now.
> trivial: show uefi_recovery message in get-plugins output

- contrib/ci/dependencies.xml
- contrib/debian/control.in
- contrib/fwupd.spec.in
- data/bash-completion/fwupdmgr
- data/bash-completion/fwupdtool
- data/bash-completion/meson.build
- src/fu-tool.c
- src/fu-util.c
Merged fu_util_update_all() and fu_util_update_by_id() to simplify the
maintaince work and streamline the flow for consistent behavior across
a normal update for all updatable devices and a small set of chosen
devices.
This commit also added support for specifying mutliple DEVICE-IDs or
GUIDs in a single run, previously error message 'Invalid Argument' is
seen and soon aborted.
> trivial: allow multiple GUID or DEVICE-ID to update command

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
- src/fu-engine.c
trivial: get-details finishes all the components, don't error out immediately
Before:
```
WARNING: This package has not been validated, it may not work properly.
Decompressing…           [***************************************]
Not compatible with org.freedesktop.fwupd version 1.7.5, requires >= 1.9.13
```
After:
```
09:19:46:0241 FuEngine             ✘ Dock Package: Not compatible with org.freedesktop.fwupd version 1.7.5, requires >= 1.9.13
09:19:46:0241 FuEngine             ✘ EC: Not compatible with org.freedesktop.fwupd version 1.7.5, requires >= 1.9.13
09:19:46:0242 FuEngine             ✘ VMM6221 MST: Not compatible with org.freedesktop.fwupd version 1.7.5, requires >= 1.9.13
09:19:46:0242 FuEngine             ✘ USB 3.1 Generation 1: Not compatible with …
```
> trivial: get-details finishes all the components, don't error out immediately

- plugins/modem-manager/fu-firehose-updater.c
- plugins/modem-manager/fu-mm-device.c
Works around https://github.com/fwupd/fwupd/issues/4190 although we
still need to find the root cause.
> modem-manager: Fix a segfault on startup for some MBIM-QDU devices

- data/device-tests/nordic-hid-nrf52840-mcuboot.json
- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
The initial name of the varianle has been changed upon review in [nrf_desktop DFU PR](https://github.com/nrfconnect/sdk-nrf/pull/6343)
This commit align the naming with NRF desktop upstream and fix testing
images URLs for device testing.
> plugins/nordic-hid: fix the bootloader type detection

- docs/hsi.md
- plugins/msr/fu-plugin-msr.c
The kernel documentation for AMD memory encryption includes information
on both SME and SEV, but they are separate attributes. Read the attributes
separately.
Link: https://www.kernel.org/doc/html/v5.16/x86/amd-memory-encryption.html
> msr: make tsme security attribute match kernel doc more closely

- plugins/modem-manager/fu-mm-device.c
Some modems use a plain string as version while others use a
standardized version format. If such a format is provided by
the metadata, set it.
Thanks to @hughsie for the hint!
> modem-manager: use version format from metadata

- contrib/debian/rules
This enables the modem-manager plugin support in the debian packaging, creating a new libfu_plugin_modem_manager.so object under fwupd-plugins.
Having this plugin enabled will allow users to update firmwares via modem-manager on modems which are compatible, such as the EG25 from Quectel shipped with the PinePhone.
This is a follow-up of https://salsa.debian.org/efi-team/fwupd/-/merge_requests/8
> debian/rules: enable modem-manager plugin support

- data/installed-tests/fwupdmgr-p2p.sh
- data/installed-tests/fwupdmgr-p2p.test.in
- data/installed-tests/meson.build
- docs/env.md
- libfwupd/fwupd-client.c
- src/fu-main.c
This adds support for optionally using a UNIX domain socket where a
D-Bus daemon may not be running.
To use this, launch the daemon and clients with something like
`FWUPD_DBUS_SOCKET=/var/run/fwupd.sock fwupdmgr get-devices`
> Allow fwupd to operate without a D-Bus daemon

- meson.build
- meson_options.txt
This has several false positives in Fedora 36 and also slows down the
build considerably.
> trivial: Turn off -fanalyzer by default

- plugins/flashrom/flashrom.quirk
Add a quirk for NovaCustom NV4x devices.
These laptops are running coreboot and are updatable using flashrom.
The HwId GUID matches to both previous Insyde firmware and the current
Dasharo firmware. The Dasharo GUID matches to the devices running
Dasharo firmware. This way the device can be switched from Insyde
to Dasharo using `fwupdmgr switch-branch`.
Homepage: https://configurelaptop.eu/nv40-series/
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
> plugins/flashrom: add quirk for NovaCustom NV4x

- src/fu-engine.c
We've not needed this for several years, and no firmware on the LVFS actually uses this.
> trivial: Remove the unused com.redhat.fwupdate built version

- plugins/msr/fu-plugin-msr.c
This method does not indicate whether the kernel has enabled encryption.
That information is only visible from the kernel log at this time.
Continue to read the MSRs though, because if/when we get a method for the
kernel to export it we may use these as a basis of "support" but not a
indication of it being enabled.
encrypted:
```FuPluginMsr          SME/SEV check MSR: eax 01000f, ebx 016f
FuPluginMsr          PCI_MSR_AMD64_SYSCFG: 0f40000, sme_is_enabled=1
FuPluginMsr          PCI_MSR_AMD64_SEV: 00, sev_is_enabled=0
```
not_encrypted:
```
FuPluginMsr          SME/SEV check MSR: eax 01000f, ebx 016f
FuPluginMsr          PCI_MSR_AMD64_SYSCFG: 0f40000, sme_is_enabled=1
FuPluginMsr          PCI_MSR_AMD64_SEV: 00, sev_is_enabled=0
```
> Drop the AMD SME check for security attributes (Fixes: #4176)

- src/fu-engine.c
I broke this when optimizing fu_context_lookup_quirk_by_id() to only
take a GUID. Mea culpa.
Fixes https://github.com/fwupd/fwupd/issues/4250
> trivial: Fix the vendor to battery threshold mapping

- plugins/thunderbolt/fu-thunderbolt-retimer.c
-this is indeed needed to reflect the updated version
Signed-off-by: Kranthi Kuntala <kranthi.kuntala@intel.corp-partner.google.com>
Change-Id: Id4751d531528590cc93c08db0d0939a547f4d59f
> [thunderbolt] remove the skip-restart flag for retimer

- plugins/thunderbolt/fu-thunderbolt-device.c
I think this accidentally got inverted during the retimer split.
> thunderbolt: Set the update timeout if required

- plugins/tpm/fu-plugin-tpm.c
- plugins/tpm/fu-tpm-eventlog-common.c
> tpm: Fix a critical warning when loading an empty TPM eventlog item

- plugins/thunderbolt/fu-thunderbolt-controller.c
> trivial: don't replug if thunderbolt device supports auth on disconnect

- src/fu-engine.c
The LVFS has been changed to do the same, and no real vendors have
added EOL information yet.
> trivial: Move the date_eol attribute to the component node

- contrib/debian/control.in
- plugins/uefi-capsule/fu-uefi-common.c
Some distribution hopes to not install the not-signed EFI app by default.
However, for the corner case, the user might still want to use not-signed
one (maybe to work around bugs or do testing). This implements
a logic that uses the not-signed EFI app as the secure boot is off, and
if it does not exist, then we fall back to using the signed one.
I have not tested this patch. I think that change looks trivial. I'll try to
test it as soon as I can and update the result here.
I created this PR on a release sooner and earlier basis.
Please kindly share if you think the direction of this change is fine
with you or not.
- [V] Feature
> fall back to signed EFI app as secure boot is off.

- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-mm-device.h
- plugins/modem-manager/fu-plugin-modem-manager.c
- plugins/modem-manager/modem-manager.quirk
This allows protocol code like Sahara to use GUsb.
> modem-manager: Assign the FuUsbDevice to the FuMmDevice

- contrib/fwupd.spec.in
- plugins/msr/fu-plugin-msr.c
- plugins/msr/meson.build
- plugins/msr/msr.conf
Starting with linux kernel 5.18 the SME flag will be removed from
/proc/cpuinfo when it's not activated.
Link: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=08f253ec3767bcfafc5d32617a92cee57c63968e
> Restore AMD SME check

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-i2c-device.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fwupdplugin.map
- plugins/mtd/fu-mtd-device.c
The only users of `SERIO\FWID` and `I2C\NAME` are already 'safe' and
the device GUIDs should all be unchanged.
There are no current users of the `MTD\NAME` instance IDs, and these
are the ones that may be more unpredictable and in need of sanity.
> Sanitize the instance ID parts more carefully

- contrib/debian/tests/ci
Generally we don't want this - but for the autopkgtest case it's OK.
Fixes: #4299
> trivial: allow fwupd.service to be run in containers for autopkgtest

- plugins/genesys/fu-genesys-usbhub-device.c
> trivial: genesys: fix some warnings about unused symbols on old gusb

- .lgtm.yml
- contrib/ci/build_windows.sh
- contrib/ci/check-abi
- contrib/freebsd/Makefile
- contrib/fwupd.spec.in
- meson_options.txt
- snap/snapcraft.yaml
We can swap the default to auto-detection once the auto-features branch
has landed.
> trivial: Turn off GPIO support by default

- plugins/dell/fu-self-test.c
- plugins/uefi-capsule/fu-uefi-device.c
- plugins/uefi-capsule/fu-uefi-device.h
This is to provide an escape hatch for vendors debugging, without having to recompile fwupd from source.
> uefi-capsule: Add a private flag for devices that never want a capsule header

- plugins/thunderbolt/fu-plugin-thunderbolt.c
- this is needed for the retimer to be accessible after update
- and to bring the port back to online
Signed-off-by: Kranthi Kuntala <kranthi.kuntala@intel.corp-partner.google.com>
Change-Id: I2234ebe23a55fc03f9ef30c1ea10febfe46a2003
> [thunderbolt] Add 5 secs delay after nvm update

- plugins/vli/vli-usbhub.quirk
This should be harmless on an actual devboard, and not break products
using the default VID/PID *without* any shared PD chip.
> vli: Do not assume any VL82x reference firmware has shared PD

- meson.build
- src/fu-engine.c
Although we can compile against older versions, we can't actually work
as current firmware.jcat metadata from the LVFS needs these commits:
https://github.com/hughsie/libjcat/commit/109399e1f28cec84b43c355b2be77bac38943df7
https://github.com/hughsie/libjcat/commit/583df67e3ee25201f1e1830ae6d92bf846c082a3
If it helps, 0.1.4 was released in October *2020*.
> Require libjcat 0.1.4

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/vli/meson.build
- plugins/vli/vli-usbhub-dell.quirk
- src/fu-engine.c
Although 2109:2820 and 2109:0820, the firmware revision of 3003 is
specific to that hardware.
Fixes https://github.com/fwupd/fwupd/issues/4305
> vli: Skip probing the Dell DA300 device

- plugins/flashrom/flashrom.quirk
Add FirmwareSizeMax = 0x800000 for StarLite Mk II and Mk III to allow
switching from AMI to coreboot firmware.
> plugin/flashrom: Add MaxSize quirk for Lite II and III

- libfwupd/fwupd-client.c
- libfwupd/fwupd-common.c
- libfwupd/fwupd-device.c
Not totally sure this is worthwhile, but it triggered a failure in the
RHEL tests we do - and it's less work to fix it than argue.
> trivial: Don't leak the string even on critical failure

- libfwupdplugin/fu-self-test.c
Wrap the spawned script with an explicit call to the /bin/bash
interpreter needed when running tests in a cross compiled enviroment.
Also increase the timeout for the spawned script to execute to give
enough time for the print to happen in the much slower virtualized
environment.
> fwupdplugin-self-test: fix spawn tests for qemu

- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
- src/org.freedesktop.fwupd.xml
> trivial: Add daemon configuration key 'OnlyTrusted' to dbus Properties

- plugins/ccgx/fu-ccgx-hpi-device.c
A simple copy+paste typo -- these need to be actual IDs for firmware
matching rather than only for quirks.
Fixes https://github.com/fwupd/fwupd/issues/4382
> ccgx: Add the correct instance IDs to the HPI device

- plugins/gpio/fu-gpio-device.c
Set the GPIO open flags as without the fd is not opened.
Fixes https://github.com/fwupd/fwupd/issues/4388
> trivial: Actually open the GPIO device before querying the chipinfo

- plugins/wacom-raw/wacom-raw.quirk
wacom-raw is required to support several Lenovo products.
Therefore, some items have been added to "wacom-raw.quirk".
Signed-off-by Tatsunosuke Tobita <tatsunosuke.tobita@wacommfg.corp-patner.google.com>
- [ x] Feature
> plugins/wacom-raw: Add several Lenovo products

- plugins/flashrom/flashrom.quirk
- plugins/flashrom/fu-flashrom-device.c
Flashrom is primarily used with coreboot, which has a pair version number
currently 4.16. As such, chance the default to pair so that fewer quirks
are required.
> plugin/flashrom: Change the default format from triplet to pair

- src/fu-device-list.c
Uninhibit the returning device if no firmware update has been performed.
> Fix the 'Device has been removed' warning incorrectly seen on devices

- plugins/redfish/fu-redfish-backend.c
- plugins/redfish/redfish.quirk
This fixes the problem when the UEFI update depends on a specific BMC
version -- including the backup BMC device means we checking that both
the primary and the backup were above a specific version.
I don't think it's ever useful to show the backup BMC device, so just
don't include it as an enumerated device.
Fixes https://github.com/fwupd/fwupd/issues/4404
> redfish: Don't add the backup BMC device as it shares the same GUIDs

- plugins/tpm/fu-tpm-eventlog-common.c
To debug the eventlog reconstruction issues we need the raw blob,
rather than just the printable text.
> Do not throw away the TPM eventlog when uploading to the LVFS

- plugins/genesys/fu-genesys-usbhub-device.c
The idea behind those changes is to prepare the genesys plugin for upgrading the genuine Genesys Logic Hubs products.
These products uses `USB\VID_05E3&PID_0610` which is not set in the quirk file yet; will be in a dedicated PR, once the support is fully functional.
The support for genuine Genesys Logic Hubs is splited into several PR. This one is the second of the serie.
In short, this PR:
- Print the Genesys IC if it is not yet supported by the plugin.
- Fails silently if the IC is not yet supported.
> genesys: trivial rework some usbhub errors

- plugins/genesys/README.md
- plugins/genesys/fu-genesys-scaler-device.c
- plugins/genesys/fu-genesys-usbhub-device.c
- plugins/genesys/fu-genesys-usbhub-firmware.c
- plugins/genesys/genesys.quirk
The idea behind those changes is to prepare the genesys plugin for upgrading the genuine Genesys Logic Hubs products.
These products uses `USB\VID_05E3&PID_0610` which is not set in the quirk file yet; will be in a dedicated PR, once the support is fully functional.
The support for genuine Genesys Logic Hubs is splited into several PR. This one is the first of the serie.
In short, this PR:
- Adds add the public key to the instance-id to with precision the HP hub; M24fd and M27fd have different firmwares; public-keys are differents at least.  
- Adds the private flag `has-public-key` which tells the plugin the device support public-key and do authentication on attach/detach. This feature is specific to HP devices. The Genesys Logic products do not use this feature.
- …
> genesys: Identify hp usbhubs with public key

- src/fu-engine.c
- src/fu-self-test.c
This ensures that two different clients cannot update the same device,
as there's a window where we're waiting for the device to come back in
bootloader mode where we might accept a request from a different client.
As a side effect it also means we no longer store the UPDATABLE flag
in the history database -- which is fine as it's pretty useless anyway;
the device had to have been UPDATABLE to be updated in the first place.
> Take a device inhibit when updating a device

- data/daemon.conf
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
This is a feature that seems useful, but one that no vendor has actually
asked for. It's also of limited use for peripheral devices.
Showing the instance IDs by default is also going to make it much easier
to explain to hardware vendors where the GUIDs come from.
Fixes https://github.com/fwupd/fwupd/issues/4445
> Show the device serial number and instance IDs by default

- plugins/genesys/README.md
- plugins/genesys/fu-genesys-common.h
- plugins/genesys/fu-genesys-usbhub-device.c
- plugins/genesys/fu-genesys-usbhub-firmware.c
- plugins/genesys/genesys.quirk
---
- There are many bonding types of chip, and a firmware has built for customize request with specific chip. Therefore, we have to create a unique instance-id to avoid updating wrong firmware.
- There is a `bonding` byte in `FuGenesysDynamicToolString`, the byte also indicate current running bank.
- There has a unique public key for HP products; other products do not have a unique key to indicate products.
- When running mask code bank, the characteristics only
1.  **chip**, the value in `FuGenesysStaticToolString`, e.g. "352310", "359010".
2.  **bonding**, the value in `FuGenesysDynamicToolString`, each bonding already defined supporting DFP number.
- When running bank 1st/2nd, the firmware already customized, obviously characteristics are
1. `VID`  / `PID` / …
> genesys: usbhub: support for gl3590 and other generic case with customized tool string info

- plugins/vli/fu-vli-device.c
This is always set as '00000000000000000000001' and thus is unhelpful.
> vli: Do not set the serial number

- plugins/flashrom/flashrom.quirk
Add NS5x GUID and missing NV4x guids for devices running older firmware versions.
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
> plugins/flashrom/flashrom.quirk: update NovaCustom GUIDs

- plugins/uefi-capsule/uefi-capsule.quirk
The firmware for the HP Dev One (upcoming Linux laptop) does not support a UX capsule.
> Add HP Dev One quirk with no-ux-capsule flag

- plugins/uefi-capsule/uefi-capsule.quirk
Backport of #4479. Please tag a release sometime after this, so we can release firmware with a version requirement.
> trivial: Add HP Dev One quirk with no-ux-capsule flag (1.7.x)

- contrib/fwupd.spec.in
- plugins/acpi-dmar/meson.build
- plugins/acpi-ivrs/meson.build
These tables are only for Intel and AMD which don't provide non x86_64
products.
> trivial: only enable IVRS and DMAR plugins on x86_64

- plugins/flashrom/fu-flashrom-device.c
We were using an 'undocumented' local copy of the flash size, when
FuDevice was setting the [ignored] standard device property.
> flashrom: Allow quirking the flashrom flash size

- plugins/genesys/README.md
- plugins/genesys/fu-genesys-usbhub-device.c
The private flag has-pubkey will be introduced with version 1.8.0.
If I am not mistaken, those changes are not back-ported to branch 1.7.y (1.7.7); therefore, the that private is will be available starting by version 1.8.0.
> genesys: usbhub: Fix typo

- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
- src/fu-tool.c
If we rely on a fix in fwupd-efi, the firmware may want to depend on it.
Although we're adding a compile time version provide, normally the
fwupd-efi.pc file is actually shipped in the binary package.
> Add the fwupd-efi version as a firmware requirement

- plugins/synaptics-cxaudio/synaptics-cxaudio.quirk
ThinkPad USB-C Dock Gen2 Audio firmware update version 49-0E-41 changed the PID from A396 to 30D1
> Add entry with new PID for ThinkPad USB-C Dock Gen2 Audio

- src/fu-tool.c
When using fwupdmgr install we pass all the possible devices and then
loop each one. If loading the requirement failed for a specific one
just continue to the next device rather than aborting too early.
Fixes https://github.com/fwupd/fwupd/issues/4509
> Fix regression in 'fwupdtool install foo.cab'

- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-mm-device.h
- plugins/modem-manager/fu-plugin-modem-manager.c
Fixes https://github.com/fwupd/fwupd/issues/4394
> modem-manager: Remove the cache item and use a shadow device instead

- libfwupdplugin/fu-security-attrs.c
- libfwupdplugin/fu-self-test.c
To a user there is no point to explicitly showing two failures for
encrypted RAM if the system supports SME and TSME both.
To show them a single failure, de-duplicate the attributes by appstream
ID during depsolve.
If the plugin didn't explicitly set obsoletes and two attributes are both
failures and both share the same appstream ID obsolete one of them.
> Automatically obsolete negative duplicate attributes

- plugins/pci-psp/fu-plugin-pci-psp.c
If the system loads ccp but the ccp driver doesn't export attributes
we should mark the CPU plugin as not supported.
> trivial: pci_psp: test an attribute to declare missing data

- .gitignore
- data/daemon.conf
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
- src/fu-engine.h
- src/fu-main.c
This key is used to specify that a dedicated user runs the fwupd
client process and sensitive strings such as the serial number should
be shared with the calling process.
(Fixes: #4524)
> Add support for a new TrustedUids key

- libfwupdplugin/fu-device.c
Some plugins rely on adding more instance IDs after the device has been
added.
> Do not clear the instance-id hash during ->setup()

- plugins/bios/fu-plugin-bios.c
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
> trivial: bios: Add an attribute to fail HSI in legacy BIOS mode

- plugins/flashrom/README.md
- plugins/flashrom/flashrom.quirk
- plugins/flashrom/fu-flashrom-device.c
- plugins/flashrom/fu-flashrom-device.h
- plugins/flashrom/fu-plugin-flashrom.c
This is follow up on [Enabling support for ME unlock](https://groups.google.com/g/fwupd/c/e6yE6xy5Hjg) discussion on ML.
What it's needed in the end:
1. Reading lock status from HSFS and sharing it for two use cases:
1. State verification before unlocking.
2. State verification before flashing ME firmware.
2. Ability to unlock ME.
3. Ability to flash ME firmware.
How it's done in this PR in its WIP state:
1. Sharing ME lock status via `FuContext`.  Value is set by `intel-spi` plugin.  Consumed in `superio` and `flashrom`.
2. Via `unlock` command for IT55 `superio` device, because unlocking is done through EC.
3. Happens in `flashrom` plugin.  Device for ME firmware is added if ME region is unlocked.
Things to consider:
1. What's the best way of presenting ME flashing to the user?  I guess …
> Feature: Clevo/Tuxedo me unlock

- src/fu-progressbar.c
Fixes https://github.com/fwupd/fwupd/issues/4540
> Only show the CLI time remaining for predictable status phases

- .github/workflows/create_containers.yml
- contrib/ci/fedora.sh
- plugins/dell/fu-dell-smi.c
> Fix a CI failure for any distro using git >= 2.35.3

- src/meson.build
According to the D-Bus API Design Guidelines, the D-Bus interface files
for public API should be installed so that other services can load them.
> Install D-Bus introspection data even if introspection is disabled

- plugins/genesys/fu-genesys-scaler-device.c
overrun-buffer-arg: Overrunning array buf of 64 bytes by passing it to
a function which accesses it at byte offset 65 using argument len + 3UL
> genesys: Fix a potential buffer overread spotted by Coverity

- contrib/debian/fwupd.postinst
- contrib/debian/rules
- data/motd/fwupd-refresh.preset
- data/motd/fwupd-refresh.service.in
- data/motd/meson.build
- meson_options.txt
This PR does a few things:
* Disable `fwupd-refresh.timer` by default as well.  I think we have too many circumstances this can lead to a failure to make it a default to enabled everywhere.  It should be enabled by packaging until when we have this sorted out.
* Add new configuration option to choose to set a static user by packaging
* Modifications to Debian packaging to create a user by default.
> Adjust handling of fwupd-refresh.service

- plugins/ccgx/fu-ccgx-dmc-device.c
Changes 
1. Fix “failed to get device before update reload: ..." error happens sometimes when it waits for device replug.
- Set "FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG" flag before sending a trigger code to the device.
2. Fix  typo of function name.
> ccgx: fix wrong failure to replug

- data/pki/meson.build
Unfortunately you can't detect the meson option:
```
../data/pki/meson.build:4:4: ERROR: Having a colon in option name is forbidden, projects are not allowed to directly access options of other subprojects.
```
So hardcode in top level meson.build that Windows doesn't take GPG.
> trivial: set up win32 build not to take GPG by default

- contrib/ci/dependencies.xml
- contrib/ci/fwupd_setup_helpers.py
Before we were only being explcit for Debian and Ubuntu and that meant
the missing attribute meant different things depending on the OS.
> Always be arch-explicit for OS deps

- plugins/scsi/fu-plugin-scsi.c
- plugins/scsi/fu-scsi-device.c
- plugins/scsi/scsi.quirk
This makes it match the eMMC and SATA plugins, and means we can more easily
walk up to the parent SCSI controller, rather than trying to find the correct
block child.
No functional changes, other than now we also read the disk serial number, and
use one less udev subsystem match.
> scsi: Rearchitect the plugin to match a block device

- plugins/colorhug/colorhug.quirk
- plugins/colorhug/fu-colorhug-device.c
This fixes updating from ColorHug(1) devices on old firmware versions,
but doesn't affect ColorHug2.
> colorhug: Never set a NULL version when the FW inface data is NULL

- contrib/build-windows.sh
- contrib/ci/build_windows.sh
- contrib/mingw64.cross
This should probably move to /usr/share/mingw/toolchain-mingw64.meson
and this patch can be reverted when that happens.
> Use exe_wrapper = '/usr/bin/wine' when cross-compiling

- contrib/mingw64.cross
- src/fu-debug.c
- src/fwupd-windows.mc
- src/meson.build
This means we don't get the 'No description found, please repair'
message when viewing messages in the Windows Event Viewer.
> Build a dummy event message file for Windows

- data/device-tests/steelseries-rival-3-wireless.json
This adds a Json device-test for the Steelseries Rival 3 Wireless device.
> trivial: Add device-test for Steelseries Rival 3 Wireless

- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-enums.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-device.c
- plugins/powerd/fu-plugin-powerd.c
- plugins/steelseries/fu-steelseries-sonic.c
- plugins/upower/fu-plugin-upower.c
- src/fu-daemon.c
- src/fu-engine.c
- src/fu-util-common.c
- src/org.freedesktop.fwupd.xml
This allows us to show the current value and the threshold on the CLI
and in tools like gnome-firmware.
> Move the battery attributes down into libfwupd

- contrib/debian/tests/ci
debian: debci: don't stderr-fail the autopkgtest on modprobe error
it's optional as tests can be skipped, if mtdram module isn't there
This is a fixup for the previous PR #4641 and related to https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1973598
> debian: debci: don't stderr-fail the autopkgtest on modprobe error

- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/ccgx/fu-ccgx-dmc-device.c
- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/scsi/fu-scsi-device.c
- src/fu-engine.c
- src/fu-tool.c
- src/fu-util-common.c
This allows us to make smarter policy decisions in the future on when
to show unavailable updates. It also means we can show translated
text in the frond-end clients.
Only problems the user can "fix" are enumerated. For example, opening
the laptop lid, or charging the device battery.
> Specify an enumerated problem when inhibiting devices

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- src/fu-engine.c
- src/fu-release.c
- src/fu-tool.c
- src/fu-util.c
When typing 'fwupdmgr get-updates' show the updates that *could* be
installed if the inhibit was removed.
Do not unconditionally do this, as some clients such as gnome-software
assume that all updates returned by GetUpdates() are updatable with
Install() -- and in a GUI we only want to show the updates we can apply
*right now*. When the inhibit is removed (e.g. AC power is connected)
the GUI client will notify the user as required, unlike a CLI tool.
Fixes https://github.com/fwupd/fwupd/issues/4629
> Allow clients to opt-in to showing updates with inhibits

- src/fu-daemon.c
Always return to IDLE even in event of an auth error.
Fixes https://github.com/fwupd/fwupd/issues/4649
> Do not leave the daemon in 'decompressing' state

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/ccgx/fu-ccgx-dmc-device.c
- plugins/colorhug/fu-colorhug-device.c
- src/fu-device-list.c
Only opt-in plugins that have been tested -- unconditionally enabling
this may cause regressions on devices like docks.
Fixes https://github.com/fwupd/fwupd/issues/4378
> Allow a plugin to only use the RemoveDelay when waiting for replug

- src/fu-daemon.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-self-test.c
We emit to the client from the daemon, and also proxy the status from
the engine, i.e. we're setting the same property in two places.
When the client requests the last-set status, recover the value sent
from the lowest layer (the daemon) rather than the engine. The former
gets reset back to IDLE automatically, the latter does not.
Fixes https://github.com/fwupd/fwupd/issues/4649
> Store the last-set status in the daemon

- plugins/msr/fu-plugin-msr.c
> trivial: Do not use the unset MSR ucode version

- plugins/corsair/fu-corsair-bp.c
- plugins/corsair/fu-corsair-bp.h
- plugins/corsair/fu-corsair-device.c
- [*] Code fix
This fixes cases when a device sends spurious report after the enumeration. Flushing happens in ->setup() before sending commands. Flushing is done by reading data from an endpoint and ignoring it.
> corsair: Flush input endpoint before sending commands

- .github/workflows/create_containers.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- contrib/fwupd.spec.in
- plugins/redfish/fwupd-redfish.conf
- plugins/redfish/meson.build
This produces startup failures on images that do not ship that exact
module, e.g. guest-images.
Just rely on the kernel driver to be auto-loaded when required.
Fixes https://github.com/fwupd/fwupd/issues/4550
> redfish: Never manually modprobe ipmi-devintf

- libfwupdplugin/fu-udev-device.c
- plugins/scsi/fu-scsi-device.c
We don't want to include the SCSI LUN in the physical ID, as this is a
logical concept not relating to the hardware device.
Use the UDev devtype to find the 'correct' parent.
> scsi: Use the SCSI target to correctly set the physical ID

- plugins/intel-spi/generate-quirk.py
- plugins/intel-spi/intel-spi.quirk
Correct the BIOS Control Device, which is should be 31.
This can be found on Intel doc numbers:
* 334819 (APL)
* 336561 (GLK)
> plugins/intel-spi: Correct BIOS Control Device

- plugins/uefi-capsule/fu-uefi-device.c
In theory, hardware with FMP should have fw_type=0x4 in the ESRT which
sets `_NO_CAPSULE_HEADER_FIXUP` -- but in reality that is not always
the case.
> uefi-capsule: Do not generate a capsule header for the FMP GUID

- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-progress.c
- libfwupdplugin/fu-progress.h
- libfwupdplugin/fu-self-test.c
- src/fu-engine.c
Using `fu_progress_finished(fu_progress_get_child(progress))` is IMHO
a hacky workaround.
> Add a progress flag to indicate for when the child returns early

- docs/env.md
- libfwupdplugin/fu-progress.c
- libfwupdplugin/fu-progress.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- src/fu-daemon.c
- src/fu-engine.c
- src/fu-tool.c
With `--verbose` this will print a dump of startup times onto the
console so that we can debug which plugin is slowing down system
startup. For example:
../src/fu-engine.c:5409:plugins-coldplug [108.55ms]:
../plugins/amt/fu-plugin-amt.c:437:amt [27.14ms]:
../plugins/amt/fu-plugin-amt.c:437:create-context [12.66ms]
../plugins/amt/fu-plugin-amt.c:437:get-version [8.44ms]
../plugins/amt/fu-plugin-amt.c:437:add-device [3.95ms]
> Add startup profiling functionality

- libfwupdplugin/fu-udev-device.c
Change-Id: I907bb3958b624ff5f887cbc192f54448354d9d5c
--- Make "unset" check for version simillar to model/device where unset can be 0x00 or 0xFF
> Fix setting version for udev devices

- plugins/emmc/README.md
- plugins/emmc/fu-emmc-device.c
Those are required if we need to re-map FW versions with quirks. Some
devices physical version number are not consecutively mapped to logical
version number.
Change-Id: Id6adf2ec6c54319b1e3d8b142eacac3e27db0ef0
> Add eMMC guids to include FW version

- plugins/corsair/corsair.quirk
Vendor has decided to remove these devices from the initial supported
device list:
* SABRE RGB PRO WIRELESS Gaming Mouse
* SLIPSTREAM WIRELESS USB Receiver
> corsair: remove support for some devices

- plugins/modem-manager/fu-plugin-modem-manager.c
We don't show messages in the logs about unable to probe other
device types by default, MM should be no different.
This gets rid of this message coming up every fwupd startup on a
EM05-G:
"failed to probe MM device: modem cannot be put in programming mode"
> trivial: quiet the modem manager error about unable to probe

- plugins/lenovo-thinklmi/fu-self-test.c
- plugins/synaptics-cape/fu-synaptics-cape-device.c
- src/fu-main.c
> synaptics-cape: Fix a big endian compile warning

- plugins/system76-launch/fu-system76-launch-device.c
Fixes https://github.com/fwupd/fwupd/issues/4762
> system76-launch: Wait for device to re-enumerate if unlocked and reset

- plugins/dell-dock/fu-dell-dock-common.h
- plugins/dell-dock/fu-dell-dock-hub.c
- plugins/dell-dock/fu-dell-dock-hub.h
- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/dell-dock/fu-dell-dock-i2c-ec.h
- plugins/dell-dock/fu-plugin-dell-dock.c
The usb3 hub 413c:b06f may be added to the plugin ahead of ec device
while dock type is yet known at that time. Cache the hub until ec can
tell the instance id, then add it to the plugin.
> dell-dock: cache hub device and add it until ec is added

- .circleci/config.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- contrib/ci/Dockerfile-ubuntu.in
This reverts commit 8035b48158b20df02908424e69e5475efd7ab2de.
> Revert "trivial: move some jobs back to Ubuntu 20.04 to fix CI"

- plugins/dfu/dfu.quirk
- plugins/dfu/fu-dfu-common.h
- plugins/dfu/fu-dfu-device.c
Some Poly usb devices will STALL the dfu detach request if the
audio/video is streaming. By setting the high byte of wIndex
in detach control request to 1, it could bypass the streaming
status check.
> dfu: Add Force-Detach to bypass audio/video streaming check

- plugins/dell-dock/fu-plugin-dell-dock.c
- src/fu-device-list.c
dell-dock: don't show thunderbolt's usb4 device, if inhibited
Some users might be confused by the inhibited message,
they might think the upgrade failed,
so the idea is to hide the inhibited device with a "hidden" inhibit id. 
>  trivial: don't show devices with inhibit id: hidden

- libfwupdplugin/fu-self-test.c
Fixes https://github.com/fwupd/fwupd/issues/4791
> Skip uSWID self tests when compiled without cbor support

- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-firmware.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
Some firmware stacks images hierarchically, and it's useful to be able
to get the parent when unrolling them out into a linear format.
> Add fu_firmware_get_parent() for future use

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
For some reason the Azure mirror is failing *again* with systemd.
This doesn't seem to affect the Circle CI builds this time though.
> trivial: revert back to Ubuntu 20.04 for the github workflows

- contrib/fwupd.spec.in
> trivial: fedora: don't require dell plugin for synaptics-mst anymore

- contrib/debian/rules
an MIR has been completed in Ubuntu for this.
https://bugs.launchpad.net/ubuntu/+source/protobuf-c/+bug/1956617
> Enable protobuf-c (and relevant plugins) based on them in Ubuntu

- plugins/intel-spi/generate-quirk.py
- plugins/intel-spi/intel-spi.quirk
APL doesn't have a PCH so change it to ich. This change makes no
difference, and is just for correctness.
> plugins/intel-spi: (nit) Change APL from pch to ich

- data/device-tests/steelseries-aerox-3-wireless.json
Some of URLs disappeared. Marked all versions from the
commit as persistent on LVFS to avoid CABs loss.
> trivial: fix URLs for SteelSeries Aerox3 device test

- libfwupdplugin/fu-plugin.c
This removes at least two open(),probe(),setup(),close() chains for the
common case where the vfuncs are not implemented.
> Avoid duplicate device actions where possible

- libfwupdplugin/fu-smbios.c
When support was added for falling back to SMBIOS data from the kernel
in /sys/class/dmi, we inadvertently stopped caring about the data parsed
directly from DMI tables as first priority.  This caused a regression in
hwids from some OEMs that relied upon IDs that could only be properly built
from DMI tables, not the kernel /sys/class/dmi interface.
Link: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1982103
Fixes: 464425fb5 ("SMBIOS: try reading from /sys/class/dmi if direct access fails")
Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>
> fu-smbios: Fix parsing smbios data

- contrib/ci/arch.sh
`yu` was added in 014e5526ff4f8430c7709eb2b8094f0767af8437 to solve cache issues.
But since then several other invocations of pacman have been added and doing so constantly is pointless, as you are unlikely to see new upgrades while the CI is running (and it might not be desired either). It also breaks testing older versions of fwupd as seen in GH-4860. So upgrade only once at the beginning and keep installing from the same cache afterwards.
> contrib/ci: do not upgrade Arch continuously

- contrib/ci/fwupd_setup_helpers.py
- contrib/setup
if meson wasn't installed by pip it won't have a version string
> trivial: fixup setup helpers to install right version of meson

- src/tests/host-emulate/meson.build
Busybox only supports the short option '-k'. (#4866)
Using this instead of '--keep' allows fwupd to be built on systems like Alpine Linux where /bin/gzip is supplied by Busybox.
> Make host-emulate/meson.build compatible with Busybox

- docs/env.md
- libfwupdplugin/fu-efi-firmware-file.c
- libfwupdplugin/fu-fuzzer-firmware.c.in
- plugins/bcm57xx/fu-bcm57xx-dict-image.c
- plugins/synaptics-cape/fu-synaptics-cape-device.c
- plugins/synaptics-cape/fu-synaptics-cape-firmware.c
- plugins/synaptics-rmi/fu-synaptics-rmi-v5-device.c
- plugins/uf2/fu-uf2-firmware.c
At the moment the log is ~150,000 lines, and quite a bit of CPU time is
being spent just generating ignored XML for successful runs.
> trivial: Reduce the debug output when fuzzing

- src/fu-engine.c
- src/fu-security-attr.c
- src/fu-security-attr.h
We need these in at least two projects (gnome-control-center, cockpit)
and it makes sense to store these where we define the new IDs.
> Add a title and long translated description for security attributes

- contrib/ci/dependencies.xml
- contrib/ci/fedora.sh
This would have caught the recent memory corruption automatically.
> Use -Db_sanitize=address,undefined in Fedora CI

- libfwupd/fwupd-bios-attr.c
- libfwupd/fwupd-bios-attr.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-security-attr.c
- libfwupd/fwupd-security-attr.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-bios-attrs.c
- libfwupdplugin/fu-bios-attrs.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- plugins/acpi-facp/fu-plugin-acpi-facp.c
- plugins/iommu/fu-plugin-iommu.c
- plugins/lenovo-thinklmi/fu-plugin-lenovo-thinklmi.c
- plugins/pci-psp/fu-plugin-pci-psp.c
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
- src/fu-self-test.c
This will allow clients to be able to suggest to users to change BIOS settings to try to fix security problems.
> Add support to map BIOS attributes to Security Attributes

- libfwupd/fwupd-security-attr.c
- libfwupd/fwupd-security-attr.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-security-attr.c
We can't very-well ask the user to 'change it back' if we do not tell
them what it is set to already.
> Store the current BIOS value in a security attribute

- plugins/flashrom/flashrom.quirk
Set BcrAddr to 0x0 for all coreboot devices, so that the check of
BIOS Control is skipped as coreboot won't forcibly set this.
> plugins/flashrom: Skip BC check for coreboot devices

- contrib/ci/Dockerfile-debian.in
- contrib/ci/generate_debian.py
- contrib/ci/generate_docker.py
- contrib/debian/fwupd-doc.install
- contrib/debian/rules
Should fix building Debian stable containers
Fixes: #4901
> trivial: ci: debian: Use helper script to install dependencies instead.

- contrib/debian/rules
Fixes: a19b6f23e ("trivial: ci: debian: Use helper script to install dependencies instead. (#4906)")
> trivial: fix a docs directory check inversion

- libfwupdplugin/fu-security-attr.c
If an attribute is read only, then we'll have a failure trying to
set it.  So don't offer a target value so clients won't try to set
an attribute.x
> trivial: don't set target BIOS attribute for read only attributes

- libfwupdplugin/fu-bios-attrs.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/tests/bios-attrs/dell-xps13-9310/dell-wmi-sysman/attributes/SecureBoot/current_value
- libfwupdplugin/tests/bios-attrs/lenovo-p14s-gen1/thinklmi/attributes/SecureBoot/current_value
The firmware from both Dell and Lenovo actually blocks this, but the
error message is pretty confusing.
```
$ sudo fwupdtool set-bios-setting SecureBoot Disable
17:39:40:0249 FuBiosAttrs          KERNEL BUG: thinklmi doesn't export a 'type' attribute
Loading…                 [-                                      ]
failed to write 7 bytes to 17: Invalid argument
```
> trivial: don't let people try to turn off UEFI secure boot

- data/bash-completion/fwupdmgr
- libfwupd/fwupd-bios-attr-private.h
- libfwupd/fwupd-bios-attr.c
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-self-test.c
- libfwupdplugin/fu-bios-attrs-private.h
- libfwupdplugin/fu-bios-attrs.c
- src/fu-daemon.c
- src/fu-util-bios-attr.c
- src/fu-util.c
The only information that is secret is the `current_value`.
Augment the d-bus call to determine whether the caller needs this
information.
* If `fwupdmgr` is launched as root it will be provided.
* If `fwupdmgr` is launched with `--authenticate` it will be requested
and PK will be engaged.
> Allow running get-bios-settings without root or PK

- plugins/flashrom/flashrom.quirk
- plugins/superio/superio.quirk
Add the HwId for the Star LabTop Mk III when using coreboot firmware,
as this differs to AMI.
> plugins/{superio,flashrom}: Add LabTop Mk III HwId

- libfwupdplugin/fu-udev-device.c
- plugins/elantp/elantp.quirk
Some interesting i2c devices have a generic name, e.g. 'Synopsys'.
> Add instance IDs that include the kernel driver

- contrib/build-openbmc.sh
- contrib/build-windows.sh
- contrib/ci/build_macos.sh
- contrib/ci/build_windows.sh
- meson.build
- meson_options.txt
- plugins/acpi-dmar/meson.build
- plugins/acpi-facp/meson.build
- plugins/acpi-ivrs/meson.build
- plugins/cpu/meson.build
- plugins/iommu/meson.build
- plugins/linux-lockdown/meson.build
- plugins/linux-sleep/meson.build
- plugins/linux-swap/meson.build
- plugins/linux-tainted/meson.build
- plugins/msr/meson.build
- plugins/pci-bcr/meson.build
- plugins/pci-mei/meson.build
- plugins/pci-psp/meson.build
- plugins/tpm/meson.build
- plugins/uefi-pk/meson.build
This allows us to disable it automatically on architectures that
aren't supported and OSes that aren't supported.
Link: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1987067
> Convert HSI into a meson tristate-feature

- docs/env.md
- libfwupdplugin/fu-bios-attrs.c
The `--verbose` output for getting BIOS setting info is very noisy
on Lenovo systems due to a mismatch for the driver behavior and
kernel API.
Hide most of it behind an optional environment variable
`FWUPD_BIOS_SETTING_VERBOSE`.
> trivial: Make BIOS setting parsing errors less verbose by default

- data/bash-completion/fwupdmgr
- libfwupd/fwupd-client-sync.c
- libfwupd/fwupd-client-sync.h
- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- src/fu-daemon.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-self-test.c
- src/fu-tool.c
- src/fu-util-bios-attr.c
- src/fu-util-bios-attr.h
- src/fu-util.c
- src/org.freedesktop.fwupd.xml
The JSON payload is ideally generated from `fwupdmgr get-bios-settings --json`
with all attributes expected to be included as additional arguments.
> Add support to set BIOS settings using a JSON payload

- libfwupd/fwupd-security-attr-private.h
- libfwupd/fwupd-security-attr.h
- src/fu-util-common.c
We do not want to show added or removed HSI tests in this UI.
> Only show *changed* events in the fwupdmgr security output

- src/fu-engine.c
The invalid HSI prefix should be "HSI:INVALID" not "HSI-INVALID".
After fixing, the HSI for invalid chassis is shown as follows.
> fu-engine: HSI prefix fixing for invalid chassis

- contrib/fwupd.spec.in
- data/bios-settings.d/README.md
- data/bios-settings.d/meson.build
- data/meson.build
- libfwupdplugin/fu-bios-settings-private.h
- libfwupdplugin/fu-bios-settings.c
- libfwupdplugin/fwupdplugin.map
- src/fu-daemon.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-self-test.c
- src/fu-tool.c
- src/fu-util-bios-setting.c
With this change, system administrators can place JSON files in `/etc/fwupd/bios-settings.d` which will set up fwupd to enforce their BIOS settings policy.
Some open discussion questions:
1. Should settings modified this way also be marked "read only"?
2. Should the default directory be created at fwupd startup?
3. Should the empty directory be shipped with packages?
4. Should an empty JSON file be shipped?
5. Should we make a wiki page for how to use BIOS settings (they're getting a lot more complex!), or `fwupd.github.io` page for it?
> Add support for default BIOS settings policy

- plugins/elantp/README.md
- plugins/elantp/elantp.quirk
- plugins/elantp/fu-elantp-hid-device.c
- plugins/elantp/fu-elantp-i2c-device.c
- plugins/elantp/fu-elantp-i2c-device.h
- plugins/elantp/fu-plugin-elantp.c
These non-HID devices are bind with the elan_i2c driver, and quirks uses ACPI/DeviceTree information for matching, same as the driver method.
After the firmware update, it needs to switch back to absolute report mode and rebind the driver to update the information.
> ELANTP: Added support for absolute reporting (non-HID) devices

- src/fu-engine.c
The logic being that if we're emulating another system we're possibly
on a VM, and that's possibly going to report that it isn't a desktop.
I also think it makes sense to serialize out the FuSmbios object
to-and-from JSON, but that's a patch for another day.
> Force the chassis type to be valid if emulating

- libfwupdplugin/fu-bios-settings.c
- po/POTFILES.in
- src/fu-util-bios-setting.c
We'll want all clients to be able to get translations from updated descriptions.  So move this into the daemon so at least the right English string is set by default.
Clients can then look up from there.
While making this change, also prepare for better lookups for read-only as well.
> Move BIOS Settings descriptions database into the daemon

- src/fu-engine.c
After policy applies for the first time, you don't want to show
messaging to users that the policy can't apply the next time.
> trivial: bios-settings: don't show error for nothing to do

- libfwupdplugin/fu-efi-signature-list.c
- plugins/uefi-dbx/fu-dbxtool.c
Use a hardcoded list of last-set dbx checksums to fix the reported version
when required.
> Fix applying the latest DBX update on machines with 20200729.x64 installed

- plugins/tpm/fu-plugin-tpm.c
There isn't any reason that we need to have a system advertising a
GUID with `main-system-firmware` in order to check that PCR0 reconstruction
matches what the TPM actually has.
Fixes: #4961
> tpm: Don't require uefi capsule updates for checking TPM PCR0

- plugins/cpu/fu-cpu-device.c
According to Intel, EDX[bit 20] corresponds to IBT feature, *not* ECX.
Fixes half of https://github.com/fwupd/fwupd/issues/4960
> Correctly detect CET IBT

- plugins/usi-dock/fu-usi-dock-mcu-device.c
sometimes the device is busy and will exceed the timer limit.
> usi-dock: Extend delay time before reload

- docs/meson.build
- src/fu-tool.c
- src/fu-util.c
There is no point to offering the security argument to the tools if HSI was disabled
at compile time.
> trivial: disable `security` arg when HSI disabled

- contrib/ci/build_windows.sh
- libfwupd/fwupd-client-sync.c
- libfwupd/fwupd-client.c
- src/fu-util.c
This makes `fwupdmgr.exe` "work".  We still don't have the ability to pass CAB files or metadata between client and daemon, but it's a step in that direction.
> Add a Service for Windows

- .circleci/config.yml
- docs/meson.build
RPM based distros cannot replace a directory with a symlink without a giant hack.
> Install the symlink the other way around

- .github/workflows/main.yml
We've never found a different in compilation between 10.15 and 11.
> trivial: Only build CI for macos-11

- .circleci/config.yml
The deploy job failed at 1.8.4 release, move up to a current version
of golang instead to fix this.
> trivial: update golang container for msi publishing

- docs/test-deps.py
We require at least 3.3.3, but if they don't have anything at least show a message.
> trivial: show a better error why docs fails if markdown not installed

- plugins/modem-manager/fu-mm-device.c
Fixes https://github.com/fwupd/fwupd/issues/4998
> modem-manager: Fix a critical warning when issuing Secure Boot AT commands

- libfwupdplugin/fu-backend.c
- libfwupdplugin/fu-device.c
- src/fu-bluez-backend.c
- src/fu-bluez-backend.h
- src/fu-engine.c
- src/fu-udev-backend.c
- src/fu-udev-backend.h
- src/fu-usb-backend.c
- src/fu-usb-backend.h
This isn't required right now, but new functionality is much easier to add if
we know the context has always been set.
> Ensure the context is set for all backends

- src/fu-engine.c
> trivial: Fix a tiny memory leak when loading BIOS settings

- libfwupdplugin/fu-udev-device.c
- plugins/mtd/fu-self-test.c
The autopkgtest environment in Ubuntu seems to not be preparing the mtdram device properly. Sometimes the udev node "exists" but the /dev/mtd0 does not exist.
Look for this explicitly and skip the test if it happens.
> Try harder to make sure mtdram env setup

- contrib/ci/dependencies.xml
- contrib/ci/fwupd_setup_helpers.py
Recently noticed that a bunch of weird architectures are failing in Debian because they happen to not have `clang-format`.  That's fine if they want to build, but make sure the dependencies that we use for our CI environment don't leak into `debian/control`.  This should help avoid those failures.
> Fixes for debian/control

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fwupdplugin.map
This seems like a useful thing regardless.
> trivial: Export fu_device_set_quirk_kv() for future use

- plugins/ccgx/fu-ccgx-hpi-device.c
PVS: It's odd that 'sizeof()' operator evaluates the size of a pointer to a class, but not the size of the 'metadata' class object.
> ccgx: Write all the metadata block as intended

- plugins/vbe/fu-vbe-simple-device.c
PVS: The null pointer is passed into 'g_byte_array_append' function.
> vbe: Fix a crash when dumping firmware

- plugins/synaptics-mst/fu-synaptics-mst-device.c
PVS: Parameter 'payload_len' is always rewritten in function body before being used.
> synaptics-mst: Check the firmware payload size when updating cayenne

- plugins/mtd/mtd.quirk
Pine64 PinePhone Pro has an SPI device which is handled by the MTD plugin and comes with Tow-Boot pre-installed from the factory. Expose it as Tow-Boot and mark the firmware type with uSWID for version extraction. However, it does not provide uSWID data so users have to manually upgrade to a Tow-Boot version with uSWID data support first.
Depends on a fix for #5021 first, fix available in #5023
> mtd: expose Pine64 PinePhone Pro MTD as Tow-Boot

- src/fu-util-common.c
Sometimes even if fwupd can't upgrade these devices they're interesting to end users because they may show information that can otherwise only be obtained by tearing apart firmware or using extra arguments.
Amend the default behavior to let these show up.
> trivial: fu-util-common: RO devices w/ FW versions are interesting

- plugins/msr/fu-plugin-msr.c
I swear this used to do it at one point, but I noticed it was missing recently.
> cpu: Add the microcode version to the CPU device

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fwupdplugin.map
This allows the backend to identify the specific device for a specific phase.
For instance, there might be a pre-update runtime, a bootloader and a post-update runtime and allowing tags to be saved to the backend object allows us to identify each version of the same physical device.
This takes us one step closer to emulating a complete byte-perfect end-to-end update without actual hardware installed.
> Allow adding backend tags to devices

- plugins/pixart-rf/fu-pxi-firmware.c
- plugins/pixart-rf/fu-self-test.c
This was probably broken in https://github.com/fwupd/fwupd/commit/0c51630991725d29255a4e4774f92185f6a24aaa
Mea culpa.
> pixart-rf: Fix the endianness of the magic

- plugins/redfish/meson.build
Although typically we set the password using fu_plugin_set_secure_config_value() or something like Ansible or Puppet -- the user could just edit the file with vim and we still want the permissions set correctly.
> redfish: Set the permissions of redfish.conf at install time

- .github/workflows/create_containers.yml
- .github/workflows/main.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- libfwupdplugin/fu-quirks.c
We want to also skip the compiled-in GResource quirks if loading the context with _NO_CACHE.
> trivial: Fix self tests when using -Dgresource_quirks=enabled

- contrib/ci/check-headers.py
- contrib/migrate.py
- data/daemon.conf
- libfwupdplugin/README.md
- libfwupdplugin/fu-context-private.h
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- libfwupdplugin/fu-volume.c
- libfwupdplugin/fu-volume.h
- libfwupdplugin/fwupdplugin.map
- plugins/uefi-capsule/README.md
- plugins/uefi-capsule/fu-plugin-uefi-capsule.c
- plugins/uefi-capsule/fu-uefi-tool.c
- plugins/uefi-capsule/uefi_capsule.conf
- plugins/uefi-dbx/fu-dbxtool.c
- plugins/uefi-dbx/fu-uefi-dbx-common.c
- plugins/uefi-dbx/fu-uefi-dbx-common.h
- plugins/uefi-dbx/fu-uefi-dbx-device.c
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
- src/fu-tool.c
We now have two plugins getting the ESP values, and we only allow hardcoding the ESP in uefi_capsule.conf. We also have *another* override in the `FWUPD_UEFI_ESP_PATH` environment variable.
Make all this a lot simpler by moving the ESP+BDP code to `FuContext`, which also means we can handle the override (via the config file) in the engine, and the override (in the command line tools) using the same mechanism.
Also, automate the migration of the `OverrideESPMountPoint` -> `EspLocation` when loading the engine.
Fixes https://github.com/fwupd/fwupd/issues/5042
> Move the getting the ESP to the context

- docs/meson.build
We want /usr/share/docs/fwupd/libfwupd for the docs that can be referenced from index.html, and a symlink of /usr/share/docs/libfwupd for devhelp.
This fixes the rpmbuild warning:
> trivial: Install the devhelp symlinks relative

- plugins/android-boot/fu-android-boot-device.c
In case no version is found, android-boot plugin uses a fall back version (0.0.0) but no version format is set. Therefore, fwupd uses format 'plain' as default which is not correct as 0.0.0 is a triplet.
> android-boot: set default version format

- libfwupd/fwupd-self-test.c
- plugins/dell/fu-self-test.c
- plugins/lenovo-thinklmi/fu-self-test.c
- plugins/thunderbolt/fu-self-test.c
- src/fu-self-test.c
It's way more helpful to print the GError message than just an boolean failure.
> trivial: Always use g_assert_no_error() first

- libfwupdplugin/fu-common-private.h
- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-volume.c
- libfwupdplugin/fu-volume.h
- libfwupdplugin/fwupdplugin.map
- libfwupdplugin/meson.build
Only build libfwupdplugin source files once; we were only using one non-exported symbol and so move that to the exported map so we can just link the library in the self tests.
> trivial: Speed up the build by about 9%

- src/meson.build
Just compile daemon sources into libfwupdpluginbuiltin.
> trivial: Make the build simpler by not using libfwupdengine

- plugins/modem-manager/fu-mm-device.c
In case of Firehose, firmware update mechanism depends on the device bus (PCI or USB) and driver type.
Currently `fu_device_get_physical_id` is used to determine PCI devices. This approach is not perfect since USB devices can be sitting on the PCI bus as well.
Also, loading of the firehose programmer is implemented in the MHI driver, so we should only use this update mechanism for the devices that use `mhi-pci-generic` driver.
This commit adds `mm_modem_get_drivers` to determine devices that use `mhi-pci-generic` driver.
> modem-manager: check driver name instead of bus type

- contrib/generate-metainfo.py
- data/meson.build
We have to include the entire history in git, and also to generate the NEWS file, but this reduces the size of the on-disk file by 116Kb.
> Only include the last 5 releases in the installed metainfo file

- libfwupdplugin/fu-plugin-private.h
- libfwupdplugin/fu-plugin.c
- plugins/synaptics-mst/fu-self-test.c
- plugins/thunderbolt/fu-self-test.c
- src/fu-engine.c
It turns out using tss2_esys is slow (200ms) -- and now we know.
> Add some more profiling to debug custom device GType creation

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-capsule/fu-uefi-common.c
- plugins/uefi-capsule/fu-uefi-common.h
Look for a plausible path existing, still continuing to the first entry on failure as before. This makes it "work" for more people out-of-the-box.
> uefi-capsule: Try harder when trying to find the default ESP

- plugins/vli/fu-vli-usbhub-device.c
- plugins/vli/vli-goodway.quirk
The daemon wants to auto-add the parent relationship from the analogix device to the VLI device automatically, which is arguably more correct anyway.
No behaviour change, but the tree output in fwupdmgr will be reversed now.
> vli: Remove the incorrect ParentGuid to prevent confusion

- plugins/modem-manager/fu-mm-device.c
fwupd does not know if the firmware is signed or unsigned unless the Quectel secureboot commands set this flag. Assume that the firmware is unsigned by default, which is the case for most firmware unless they have they support the secureboot AT commands. If that's the case, the right flag will be set anyway.
`fwupdtool` prints this error with `fwuptool refresh`:
```
FuEngine             modem_manager device does not define payload QUECTEL Mobile Broadband Module 
```
> plugins: modem-manager: assume firmware is unsigned

- plugins/wacom-usb/wacom-usb.quirk
Wacom has added a new PID for a change in the second gen IPS
- [ x] Feature
> wacom_usb: Update quirks with new PID for v2 of 2nd-gen Intuos Pro Small

- libfwupdplugin/fu-mei-device.c
- libfwupdplugin/fu-mei-device.h
- plugins/amt/fu-amt-device.c
This means the GUID matches what the kernel exports in sysfs.
> Use EFI-style GUIDs when connecting the MEI interface

- libfwupdplugin/fu-quirks.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/tests/quirks.d/tests.quirk
There are two reasons for this. First is that GKeyFile is quite inefficient, using a large amount of heap memory when loading. Given we don't actually use the merge and replace functionality of GKeyFile and we only need line-by-line access we can parse this ourselves and reduce the peak RSS considerably.
This also accidentally fixes another bug. Moving from multiple quirk files to a single builtin.quirk meant that multiple subsystem plugins were deduped -- which isn't really what we wanted. For example, this now works:
[MEI]
Plugin = one
[MEI]
Plugin = two
> Do not use GKeyFile to parse quirk files

- docs/env.md
- libfwupdplugin/fu-efi-signature-list.c
HP include extra keys that means the version is higher than expected.
> Only count the Microsoft hashes when getting the dbx version

- src/fu-engine.c
- src/fu-release.c
- src/fu-release.h
- src/fu-self-test.c
This means we might be able to offer two versions of firmware for the same device, where one has additional requirement such as a CHID.
The idea here is to allow OEMs to distribute thier own superset dbx updates on the LVFS without having to invent an anti-CHID requirement type.
> Consider the release priority when returning results

- src/fu-engine.c
The LVFS crept over this limit yesterday. I've put some emergency commits in place that take it back down to 800KB, and I'll focus next week on getting it much lower than that.
The real problem is that we thought that g_input_stream_read_bytes() was using `count` as the chunk size, not the total size. Raise the total size to 32MB and chunk in 32kB blocks to reduce the RSS peak when loading metadata.
Fixes https://github.com/fwupd/fwupd/issues/5173
> Allow parsing metadata more than 1MB in size

- libfwupdplugin/fu-device.c
- plugins/uefi-pk/fu-uefi-pk-device.c
- plugins/uefi-pk/fu-uefi-pk-device.h
- plugins/uefi-pk/fu-uefi-pk-plugin.c
- plugins/uefi-pk/meson.build
This does not serve much purpose now, but would be useful if we need to know more about the installed PK from other plugins. If nothing else it makes the `--verbose` output more helpful.
> Split out FuUefiPkDevice as a device for future use

- libfwupdplugin/fu-coswid-firmware.c
CBOR supports removing the array for only one base element, which the python uSWID tools now support; allow parsing this in fwupd.
> Support loading COSWID when only one role has been set

- src/fu-engine.c
> trivial: load hwinfo early so plugins can use the info timely

- src/fu-util-common.c
the structure is old->new, so from tained to not tainted should be: "Kernel is no longer tainted" not "Kernel is tainted"
Fixes: #5199
> trivial: fix a host security event message

- plugins/ccgx/ccgx.quirk
QSI's original Godzilla Creek reference, and one variant I just happen to have, the Anker Thunderbolt 4 Mini.
> Add two Godzilla Creek docks to ccgx

- libfwupdplugin/fu-efi-signature-list.c
Noticed this missing in https://github.com/fwupd/fwupd/issues/5211
> trivial: add missing log domain for efi signature list

- plugins/elantp/fu-elantp-i2c-device.c
- plugins/elantp/fu-elantp-i2c-device.h
> elantp: Derive from FuI2cDevice to allow a I2C\NAME_ quirk match

- plugins/elantp/elantp.quirk
Modify the matching method from `I2C\MODALIAS_` to `I2C\NAME_`
It depends on #5212 and has been tested to work.
> elantp: Updating the quirks of the ABS touchpad of Chromebook

- data/device-tests/analogix-anx7518.json
- plugins/analogix/fu-analogix-device.c
The device needs to switch to the new firmware bank, and no automated way currently exists to reboot the chip.
> analogix: Devices need to be removed and re-inserted after update has completed

- src/fu-engine.c
We want the specific BiosVersion when adding entries to the uefi-dbx.quirk -- as often the dbx update will work only with newer BIOS versions.
> Record more host DMI data when submitting a report

- data/bash-completion/fwupdtool
- src/fu-tool.c
Only set _NO_SEARCH when specified, and do not piggy-back on the --force command line option.
Fixes https://github.com/fwupd/fwupd/issues/5227
> Fix a regression when using fwuptool install-blob with FMAP firmware

- libfwupdplugin/fu-device.c
If using old metadata (or when the device does not hard-require an update message) just use something generic that cannot be replaced client-side.
> trivial: Do not show a critical warning without a request ID

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-self-test.c
- plugins/flashrom/fu-flashrom-plugin.c
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- src/fu-engine-helper.c
- src/fu-engine-helper.h
- src/fu-engine.c
- src/fu-util-common.c
Recently we had an update that changed the system-defined Platform Key, and we've certainly had updates in the past that changed the Boot#### variables.
Store some core ACPI and UEFI system integrity state and make sure that it is exactly the same when the system comes back from the requried reboot.
> Check system integrity when installing UEFI updates

- plugins/wacom-usb/wacom-usb.quirk
The use-runtime-version flag was initially used with the Intuos Pro Small (2nd-gen USB v2) to force the use of the legacy code path. The legacy code path was required because of a bug in the identification of the Bluetooth (I6) firmware.
It has been decided that the bug will be fixed before any fimware changes are released, removing the need to use the legacy code path.
> wacom-usb: remove the use-runtime-version flag from IPS

- plugins/goodix-moc/goodixmoc.quirk
Add support for the coming GF3258WNC(MOC) fingerprint device.
> Add Goodix GF3258WNC support

- plugins/elantp/fu-elantp-hid-haptic-device.c
> elantp: Use fu_device_retry_full() to avoid a Coverity warning

- plugins/dfu-csr/fu-dfu-csr-device.c
The last chunk of data has zero size, and so never copy from a NULL source.
Fixes https://github.com/fwupd/fwupd/issues/5251
> dfu-csr: Fix a critical warning when deploying firmware

- docs/meson.build
- meson.build
There is no guarantee that Python environment used for the build contains the same `markdown` version as the one used for running `gi-docgen`. For example, Nixpkgs uses a self-contained Python environment for the latter, so `markdown` package is not even available in fwupd build environment. Fortunately, gi-docgen 2022.2 already checks for `markdown` version so we can omit our own check for newer gi-docgen versions.
cc @eli-schwartz who added the check to gi-docgen.
> build: Do not check markdown version for gi-docgen 2022

- plugins/synaptics-rmi/fu-synaptics-rmi-device.c
- plugins/synaptics-rmi/fu-synaptics-rmi-v5-device.c
Correct the register parsing, properties2 only exists when the bit in properties1 is set.
> synaptics-rmi: Fix the issue when updating non-secure devices

- plugins/goodix-moc/goodixmoc.quirk
Framework Laptops use this device.
Output from `fwupdtool get-devices`:
```
├─Fingerprint Sensor:
│     Device ID:          4295296d98b3ba38c72f6baa33d24f03a1d428f6
│     Summary:            Match-On-Chip fingerprint sensor
│     Current version:    01000252
│     Vendor:             Goodix (USB:0x27C6)
│     Install Duration:   10 seconds
│     Serial Number:      UID2E43190D_XXXX_MOC_B0
│     GUIDs:              1e8c8470-a49c-571a-82fd-19c9fa32b8c3 ← USB\VID_27C6&PID_609C
│                         34def4c7-9461-5a32-a945-5dde0ca57d88 ← USB\VID_27C6&PID_609C&REV_0100
│     Device Flags:       • Updatable
│                         • Device can recover flash failures
│                         • Signed Payload
```
Signed-off-by: Daniel Schaefer <dhs@frame.work>
> goodix-moc: Add quirk for GF5288WNC used on Framework

- plugins/elantp/fu-elantp-hid-device.c
ELAN Touchpads with product ids between 0x3000 and 0x4000 can sometimes end up in bootloader mode (due to not having a valid firmware, for example)
The bootloader has a product id outside of the range checked by fu_elantp_hid_device_probe, resulting in the device disappearing from get-devices when it's in that mode, which makes it seem dead.
This expands the range of that check to include 0x400 so that it is possible to upload a valid firmware to it.
----
As requested by this comment https://github.com/fwupd/fwupd/issues/5281#issuecomment-1327298367
(We could alternatively keep it as `< 0x3000` and add another condition to allow `0x400` only)
Fixes: https://github.com/fwupd/fwupd/issues/5281
See also: https://github.com/fwupd/fwupd/issues/2926
> elantp: Include 04F3:0400 (bootloader) as a valid i2c-hid touchpad

- contrib/codespell.cfg
- src/fu-engine.c
This can be used in gnome-control-center when building the security report.
Fixes https://github.com/fwupd/fwupd/discussions/5262
> Add more metadata to the report attributes

- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-release.c
- libfwupd/fwupd-release.h
- libfwupd/fwupd-report-private.h
- libfwupd/fwupd-report.c
- libfwupd/fwupd-report.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.h
- libfwupd/fwupd.map
- libfwupd/meson.build
- src/fu-release.c
- src/fu-util-common.c
- src/fu-util-common.h
Some front end clients are going to be allow-listing updates based on what the release was tested on, or by who the testing team was.
Export this data from each report when requested.
> Add FwupdReport to expose the signed reports from QA teams

- meson.build
On Arch Linux fwupd is almost reproducible except for the timestamp recorded in the generated gzip file.
This can be observed in this [diffoscope report](https://reproducible.archlinux.org/api/v0/builds/371445/diffoscope). Arch Linux differs from other distributions in reproducibility in that it does not strip non-determinism during it's build (like for example Debian).
> build: don't record timestamp in builtin.quirk.gz

- contrib/fwupd.spec.in
addresses the build error "sh: line 1: noreplace: command not found"
When performing a source build on rpm based systems, one may get messages of the form:
`sh: line 1: noreplace: command not found`
(seen in fedora koji build logs such as: https://kojipkgs.fedoraproject.org//packages/fwupd/1.8.7/3.fc38/data/logs/x86_64/build.log )
line 362 of fwupd.spec.in file is
` %config%(noreplace).....`
which appears to be an error, and should be
`%config(noreplace).....`
as elsewhere in the spec.
> remove errant % in spec file

- src/fu-engine.c
If the user uploads a report to the LVFS we don't currently get the fwupd version data in this case. And it makes the LVFS unhappy.
> Add the fwupd version to the HSI result if the chassis is invalid

- plugins/uefi-capsule/fu-uefi-device.c
Plenty of vendors rely upon this behavior, so we don't need to be making noise in logs for them.
> trivial: uefi-capsule: decrease warning about missing header to debug

- plugins/mtd/fu-self-test.c
Explicitly load_hwinfo at start of mtd self test
```
.# Start of mtd tests
.# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
.# XbSilo-DEBUG: attempting to load /tmp/.E94WW1
.# XbSilo-DEBUG: failed to load silo: blob too small
Bail out! FuContext-FATAL-CRITICAL: cannot use HWIDs before calling ->load_hwinfo()
(/usr/libexec/installed-tests/fwupd/mtd-self-test:1758): FuContext-CRITICAL **: 23:27:43.095: cannot use HWIDs before calling ->load_hwinfo()
```
> trivial: fix autopkgtest failure

- src/fu-release.c
All three devices with that flag support reinstalling the current version for testing.
> Allow reinstalling on devices with only-version-upgrade set

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-plugin.c
This only have any protective effect if we're using multiple threads -- which we're not. Removing these unused locks does not affect startup speed, but does drop the idle RSS by ~10kB.
> Remove plugin and device GRWLocks

- plugins/ti-tps6598x/fu-ti-tps6598x-device.c
Speed up the write by removing the delay after SFWd write:
- 100ms (current): 3m 16s
- no delays: 1m 45s
> ti-tps6598x: remove the delay on write

- libfwupdplugin/fu-volume.c
Fixes https://github.com/fwupd/fwupd/issues/5313
> Allow getting the ESP when there is a block device with no filesystem

- contrib/fwupd.spec.in
- libfwupdplugin/fu-archive-firmware.c
- libfwupdplugin/fu-archive-firmware.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.map
- libfwupdplugin/meson.build
- libfwupdplugin/tests/meson.build
It's useful to get images from archives by a specific filename extension.
> Add fu_archive_firmware_get_image_fnmatch() for future use

- plugins/synaptics-cape/fu-synaptics-cape-device.c
- plugins/synaptics-cape/synaptics-cape.quirk
The device with PID=0x00298 has PID=0x0286 with the outdated FWre. This change allows to recognize and update devices in the field to the recent FWre version.
See: Google tracker issue 257197851
> synaptics-cape: add the PID 0x0286

- data/daemon.conf
- src/fu-config.c
- src/tests/daemon.conf
Right now when someone removes the `daemon.conf` conffile for whatever reason, we end up with the test and test_ble plugins enabled and also some defaults don't match.
Adjust the handling of this file such that:
1) All keys are configured with their default value.
2) Commenting out a key should keep the default value.
3) Modifying a key sets a new value.
> Make no-conffile behavior more expected

- src/fu-engine-helper.c
This is created before the UEFI capsule plugin adds the new BootXXXX entry on NVRAM systems.
> Skip the fwupdx64.efi BootXXXX entry when measuring system integrity

- libfwupdplugin/fu-cabinet.c
- meson.build
The GCab decompression code is *scary* low level C that has not had any security auditing other than by the fuzzer (which found plenty of memory-safety bugs).
Supporting LZX is useless at best, and could be a security exploit at worst.
> Do not allow LZX compressed cabinet archives

- plugins/flashrom/flashrom.quirk
> plugins/flashrom: Allow 32MiB images for the StarBook Mk VI

- plugins/modem-manager/README.md
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/modem-manager.quirk
Hi,
New Quectel RM520 PCIe modem is based on Qualcomm SDX6x and requires a different firehose binary for the update process.
RM520 differs from other Quectel PCIe modems only by PID, so this merge request adds device ID to the FuMmDevice structure and uses it to select the correct binary in `fu_mm_copy_firehose_prog` 
Thanks and happy holidays!
> Add device ID and support for Quectel RM520 

- libfwupdplugin/fu-pefile-firmware.c
- libfwupdplugin/fu-pefile-firmware.h
- libfwupdplugin/fwupdplugin.h
- libfwupdplugin/fwupdplugin.map
- libfwupdplugin/meson.build
- src/fu-engine.c
This will eventually allow us to reconstruct a SBoM using a UEFI file volume.
This can be used like this `fwupdtool firmware-parse efi/fwupdx64.efi pefile` to produce:
<firmware gtype="FuPefileFirmware">
<data size="0xef59">MZ.</data>
<firmware>
<id>.text</id>
<offset>0x2d0</offset>
<size>0x7bab</size>
<data size="0x7bab">H...QRH.=....H.5</data>
</firmware>
...
<firmware gtype="FuCoswidFirmware">
<id>fwupd-efi:fwupdx64</id>
<idx>0x7</idx>
<version>1.4</version>
<offset>0xc4e0</offset>
<size>0xce</size>
<data size="0xce">..een-US</data>
<version_scheme>semver</version_scheme>
<product>fwupdx64</product>
<summary>EFI helpers to install system firmware</summary>
<colloquial_version>1.3-7-g881a508</colloquial_version>
<link>
<href>https://spdx.org/licenses/LGPL-2.0.html</href> …
> Add a pefile firmware parser

- plugins/emmc/README.md
- plugins/emmc/fu-emmc-device.c
I had no idea anyone was using this, so apologies. The instance ID is completely wrong, but it is effectively D-Bus ABI and we need to support old firmware in the field.
> emmc: Add back a legacy GUID to fix a regression

- libfwupdplugin/fu-backend.c
This matches what the plugin does and means there's no critical warning when adding to the hash table.
> trivial: Set the backend ID when added

- src/fu-engine.c
This also fixes a critical warning about the child progress not being completed.
> Do not show a warning when coldplugging an unsupported backend

- libfwupdplugin/fu-bluez-device.h
- libfwupdplugin/fu-cfi-device.h
- libfwupdplugin/fu-hid-device.h
- libfwupdplugin/fu-i2c-device.h
- libfwupdplugin/fu-mei-device.h
- libfwupdplugin/fu-udev-device.h
- libfwupdplugin/fu-usb-device.h
Remove the FuDeviceClass padding, as this library now loaded using an rpath rather than a shared library with a static API. This matches what we did for the FuFirmwareClass objects a while ago.
> trivial: Reduce runtime RSS requirement for each device subclass

- libfwupdplugin/fu-volume.c
These paths may be used for bind mounts, which we can't accurately discover. Leave a message in the logs accordingly, but allow these paths.
fixes: #5185
> Respect user requested paths for ESP even if they aren't volumes

- docs/hsi-tests.d/org.fwupd.hsi.Amd.PlatformRollbackProtection.json
- plugins/pci-psp/fu-pci-psp-device.c
> Update documentation to indicate that loading "OS Optimized Defaults" may enable security processor rollback protection on Lenovo systems.

- plugins/uefi-capsule/fwupd.grub.conf.in
commit 684bc0381 ("trivial: fix various shellcheck warnings") adds call to ${grub_probe} without any argument which causes grub2-probe to return an error, and generating grub configuration fails.
Add --version argument to avoid the error, and redierct the output to /dev/null so that it's not included in the grub configuration file.
The commit also adds superfluous single quotes causing another error:
/usr/sbin/grub2-probe: error: cannot find a GRUB drive for `${grub_probe} --target=device \${ESP}` | sed -e "s/^/\t/".  Check your device.map.
Remove the single quotes again.
Fixes: #5424
Fixes: 684bc0381 ("trivial: fix various shellcheck warnings")
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
> uefi-capsule: Do not call grub2-probe without arguments

- meson.build
- src/fu-engine.c
By using libxmlb correctly we can avoid rebuilding the metadata if the directory is unchanged. This means the initial 'generation' is unchanged in speed, but subsequent loads are almost instant as the archives are not decompressed.
> Speed up startup by a huge amount when using directory remotes

- plugins/emmc/fu-emmc-device.c
It used to be generated with decimal, not hexadecimal values.
Change-Id: I2a6a5bdea50e2d08a7de9f65a1f9a03de29e1591
- [X ] Code fix : Fixes https://github.com/fwupd/fwupd/commit/0035a921d3ede1ed79083639dafc16f18579159c
> emmc: correct legacy GUID generation

- data/bash-completion/fwupdmgr
- data/fish-completion/fwupdmgr.fish
- libfwupd/fwupd-client-sync.c
- libfwupd/fwupd-client-sync.h
- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- libfwupdplugin/fu-context.h
- src/fu-daemon.c
- src/fu-engine.c
- src/fu-util-common.c
- src/fu-util.c
- src/org.freedesktop.fwupd.xml
On edge hardware a process may want to disable firmware updates as it might be a bad time to allow an upgrade.
> Allow desktop software to inhibit devices to prevent updates

- libfwupdplugin/fu-context.c
It's perfectly okay to have no HWIDs defined.
Should help with https://github.com/fwupd/fwupd/issues/5402
> Do not make any of the HWIDs setup failures fatal

- plugins/wacom-usb/fu-wac-device.c
Sometimes the flash process will randomly hang and time-out when sending data to the device. We currently do not use any retry logic, so if this happens the flash attempt is treated as a failure. This can be a source of worry or frustration, especially if subsequent manual retries fail in a similar way.
Adding FU_HID_DEVICE_FLAG_RETRY_FAILURE to the list of flags used when calling fu_hid_device_set_report allows fwupd to try sending a block multiple times if such a time-out (or other error) occurs. This makes the flash process less prone to failure.
Signed-off-by: Jason Gerecke <jason.gerecke@wacom.com>
> wacom-usb: Retry set_report on failure

- plugins/modem-manager/fu-sahara-loader.c
FuSaharaLoader being NULL is a normal case for devices that only support Firehose and don't use Sahara QDL port.
Therefore assert should not be used.
Reported here #5428 
> modem-manager: remove improper use of assert

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-self-test.c
- libfwupdplugin/fu-device.c
- src/fu-device-list.c
- src/fu-engine.c
- src/fu-util-common.c
We already had this as an inhibit, but this was not translated client-side.
We also need to propagate the problem to the bootloader device if the device replugs during firmware update.
> Add a device problem for 'update-in-progress'

- src/fu-engine.c
The fu_engine_get_device() function is called at the start of each phase. Duplicate calls are at best confusing, and at worst could cause a 'device failed to come back' failure.
> Remove duplicate calls to fu_device_list_wait_for_replug()

- subprojects/fwupd-efi.wrap
fwupd-efi 1.4 enforces that NX bit is set by default. This won't affect most users, it should only affect those that compile by hand and don't have fwupd-efi installed already.
> trivial: update fwupd-efi to 1.4

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fwupdplugin.map
It turns out we do not want to know the current phase of the device, and we can achieve the same thing tagging the GUsbDevice manually and clearing the events at exactly the correct time.
> Remove unused API for setting backend tags

- libfwupdplugin/fu-context-private.h
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-self-test.c
- plugins/lenovo-thinklmi/fu-self-test.c
- plugins/mtd/fu-self-test.c
- plugins/synaptics-mst/fu-self-test.c
- plugins/uefi-capsule/fu-uefi-tool.c
- src/fu-engine.c
- src/fu-tool.c
This is moderately expensive to call as it processes each requirement on each release on each device, so the last thing we want to do is call it *twice*.
> trivial: Remove duplicate call to fu_engine_ensure_device_supported()

- libfwupdplugin/fu-quirks.c
This can save 250us on each query (of which we do a *lot*), and reduces the number of queries by about half if the user is using a libxmlb version that can convert from `_BOUND_TEXT` to `_BOUND_INDEX_TEXT`.
The more devices detected, the bigger the difference, and without this patch fixing libxmlb would break fwupd as we'e been searching with an index, but not actually providing one.
> Use indexes when building the quirk prepared queries

- libfwupdplugin/fu-usb-device.c
- src/fu-engine.c
If the device does not replug, and we change the GUsbDevice because the phase changed we don't want reprobe the hardware.
If we reprobe then the emulated device will request extra data compared to the real device, which will cause emulation to fail.
> Do not invalidate the probe for emulated devices

- plugins/ti-tps6598x/fu-ti-tps6598x-device.c
No functional change, but a few less i/o operations when inserting the dock.
> ti-tps6598x: Ignore the 'wrong' USB device class before calling ->setup()

- .clang-format
This explains why Mario and I had different precommit settings.
> trivial: Fix clang-format of JSON files for newer versions of clang

- libfwupdplugin/fu-smbios.c
The SMBIOS specification says:
Maximum size of SMBIOS Structure Table, pointed to by the
Structure Table Address, in bytes. The actual size is guaranteed
to be less or equal to the maximum size.
So, the firmware is actually allowed to return a DMI blob smaller than the specified size.
Fixes https://github.com/fwupd/fwupd/issues/5486
> Use the correct range check when parsing SMBIOS

- plugins/cros-ec/fu-cros-ec-usb-device.c
This allow us to emulate the device as the buffer contents are now 100% predictable and replayable.
> cros-ec: Clear the bulk transfer buffer to zero before using

- docs/env.md
- libfwupd/fwupd-common.c
- snap/snapcraft.yaml
This should fix #5485. Depends on https://github.com/snapcore/snapd/pull/12545
> snap: read the host os-release instead of base snap

- src/fu-engine.c
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
For example:
$ fwupdmgr local-install --json foo.zip
{
"Error" : {
"Domain" : "FwupdError",
"Code" : 7,
"Message" : "failed to open foo.zip"
}
}
Fixes https://github.com/fwupd/fwupd/issues/5499
> Print errors as JSON objects when using --json

- src/fu-tool.c
Converting 'simple' non-nested formats like Intel Hex into nested formats like DfuSe needs us to create a binary child firmware to avoid missing data.
Fixes https://github.com/fwupd/fwupd/issues/5493
> Fix fwupdtool firmware-convert to work with image-less formats

- libfwupdplugin/fu-device.c
We go to great pains to set the parent to the MAX of the child delays, but we don't actually set the children to have the new parent value.
This means if you update the child device without the parent in the transaction we don't always wait for all the USB devices to come back -- which is what the acquiesce delay is designed to do.
Fixes an intermittant device test for the Wacom USB tablet.
> Ensure composite devices all share the same acquiesce delay

- plugins/analogix/fu-analogix-device.c
My Analogix USB device has a Billboard interface, with bNumEndpoints=0.
When emulating the interface is NULL, and in runtime the array can *never* be NULL, so I think this check was added in error.
> analogix: Do not check the endpoints before selecting an interface

- snap/snapcraft.yaml
When installing a capsule, optional reboot is done by fwupdmgr instead of fwupd. This means fwupdmgr needs the permission to do that.
> snap: allow fwupdmgr to shutdown

- plugins/ccgx/ccgx.quirk
- plugins/ccgx/fu-ccgx-dmc-device.c
- plugins/ccgx/fu-ccgx-dmc-devx-device.c
- plugins/ccgx/fu-ccgx-dmc-devx-device.h
This is one less thing for vendors to work out.
> ccgx: Auto-set the remove-delay now we parse the devx components

- plugins/logitech-hidpp/fu-logitech-hidpp-device.c
- plugins/logitech-hidpp/fu-logitech-hidpp-plugin.c
The kernel should have loaded hidraw support by the time that we probe
a device.  This fixes logitech devices not showing up after startup
if they weren't plugged in initially.
Fixes: #5525
> trivial: logitech-hidpp: move the check for CONFIG_HIDRAW into probe

- plugins/ccgx/ccgx-noinst.quirk
- plugins/ccgx/ccgx.quirk
- plugins/ccgx/fu-ccgx-dmc-device.c
This means most devices do not need to specify additional quirks.
> ccgx: Make the default image type for FuCcgxDmcDevice to be DMC_COMPOSITE

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/uefi-capsule/uefi-capsule.quirk
- src/fu-engine.c
The firmware in this case fixes the battery charging, and as the battery is *internal* the user isn't able to apply the fix.
Fixes https://github.com/fwupd/firmware-lenovo/issues/315
> Allow installing some battery firmware updates when the power is too low

- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- libfwupdplugin/fwupdplugin.map
- plugins/amd-gpu/README.md
- plugins/amd-gpu/amd-gpu.quirk
- plugins/amd-gpu/fu-amd-gpu-device.c
- plugins/amd-gpu/fu-amd-gpu-device.h
- plugins/amd-gpu/fu-amd-gpu-plugin.c
- plugins/amd-gpu/fu-amd-gpu-plugin.h
- plugins/amd-gpu/meson.build
- plugins/amd-pmc/fu-amd-pmc-device.c
- plugins/cpu/fu-cpu-device.c
- plugins/meson.build
- plugins/pci-psp/fu-pci-psp-device.c
- plugins/tpm/fu-tpm-v2-device.c
For dGPUs this adds the VBIOS version into the device created by the optionrom plugin.
For APUs this adds the VBIOS version into a device that hangs off the APU.
For example on APU:
```
└─Ryzen 5 PRO 6650U with Radeon Graphics:
│   Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│   Vendor:             AMD
│   GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│                       22f9ecf4-588d-5c0a-8326-6ebff3655c6d ← CPUID\PRO_0&FAM_19
│                       52f8f9af-1ca9-5352-bef4-ceb232c888a5 ← CPUID\PRO_0&FAM_19&MOD_44
│                       e94372a3-3ffb-5d1c-a579-c415b7313e52 ← CPUID\PRO_0&FAM_19&MOD_44&STP_1
│   Device Flags:       • Internal device
│
├─Graphics Processing Unit (GPU):
│     Device ID:        2287ee908298807e95f89a9b7c1a435c1a634e33
│ …
```
> Fetch vbios version from sysfs

- libfwupdplugin/fu-self-test.c
These add over 1000ms to the run time, and also do not work well when virtualized via qemu.
Fixes https://github.com/fwupd/fwupd/issues/5547
> Do not run the FuProgress self tests by default

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- libfwupdplugin/fwupdplugin.map
- plugins/powerd/fu-powerd-plugin.c
- plugins/upower/fu-upower-plugin.c
- src/fu-engine.c
This should be no beahviour change, but it allows the powerd and upower plugins to provide more information in the future.
Fixes https://github.com/fwupd/fwupd/issues/3386
> Be more nuanced when considering if the system is on AC power

- contrib/ci/void.sh
- contrib/fwupd.spec.in
- contrib/snap/dfu-tool.wrapper
- contrib/snap/fwupdagent.wrapper
- data/bash-completion/meson.build
- meson_options.txt
- snap/snapcraft.yaml
- src/meson.build
This just flips the default.  Distros that need it for real compatibility reason (like RHEL?) could still -`Dcompat_cli=true`
> Stop shipping compat_cli by default

- libfwupdplugin/fu-common.c
Fix the bounds check so we never pass a bufsz of zero to fu_strsplit().
Resolves: https://github.com/fwupd/fwupd/issues/5575
> Fix a critical warning when parsing an empty kernel cmdline

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fwupdplugin.map
- plugins/logitech-hidpp/fu-logitech-hidpp-device.c
- plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
- plugins/optionrom/fu-optionrom-device.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
- plugins/synaptics-rmi/fu-synaptics-rmi-hid-device.c
- src/fu-engine.c
This might include snapshot data like GUdevDevice that is only very rarely useful after ->probe has been completed.
This reduces the idle RSS by ~200kB on my laptop.
> Remove data only useful for ->probe() when the device has been added

- contrib/snap/fwupd-command
- contrib/snap/fwupd.wrapper
- contrib/snap/fwupdtool.wrapper
we don't need to make a copy of /etc in ~ for fwupdmgr
fixes: #5579
> trivial: snap: only copy /etc and /var for tools that run as root

- .github/workflows/matrix.yml
- contrib/build-openbmc.sh
If we're building for OpenBMC then we might not have USB -- and it's perfectly valid to just use plugin methods and not backends.
> Do not check for at least one loaded backend

- src/fu-daemon.c
- src/fu-util.c
autopkgtest is failing with 1.8.12.  I don't think it's a config problem (we set it in `contrib/debian/tests/ci`) but rather getting masked.  This should help get the correct error passed up.
> Don't mask autopkgtest failures

- contrib/debian/fwupd-tests.install
- contrib/debian/rules
- data/device-tests/meson.build
- data/installed-tests/fwupd.sh
Here is the error that was being masked:
```
Emulating for /usr/share/fwupd/device-tests/hughski-colorhug2.json
failed to load emulation data: GUsb version too old to load backends
FAIL: fwupd/fwupd.test (Child process exited with code 1)
```
To make the build more flexible, don't set up this device test unless we know we were compiled against a new enough gusb.
> Fix the debci failure

- data/motd/fwupd-refresh.service.in
systemd documentation indicates to use this for units starting after network is up. Whether that fixes the problem at hand I don't know but we should at least match the suggestion.
Link: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
Link: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2008699
> trivial: use `Wants=` in fwupd-refresh unit

- libfwupd/fwupd-remote-private.h
- libfwupd/fwupd-remote.c
- libfwupd/fwupd.map
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- src/fu-engine.c
This allows the device to set the flag and then 'fwupdmgr reinstall' works correctly without internet access. This is probably a good idea for network devices that have different loadable firmwares depending on configuration, e.g. inserted SIM card.
Fixes https://github.com/fwupd/fwupd/discussions/5592
> Optionally retain firmware in a backup remote

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fwupdplugin.map
- src/fu-daemon.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-tool.c
It does not need the engine object, it's completely self-contained.
It's really inefficient to call this multiple times, but we need to refactor the trust flags before we can call this from `fu_release_load()`.
> Move the handling of FU_DEVICE_INTERNAL_FLAG_MD_SET_XXX to the device

- libfwupdplugin/fu-device.c
We want to preserve flags like FU_DEVICE_INTERNAL_FLAG_MD_SET_VERFMT.
> Copy the internal flags when incorporating devices

- src/fu-engine.c
This fixes vendor directory remotes on ChromeOS.
> Accept application/octet-stream when the mime database is missing

- plugins/elantp/fu-elantp-i2c-device.c
The FuElantpI2cDevice does not call the FuI2cDevice->probe() function and so the name does not get automatically set.
> elantp: Set the i2c name properly

- libfwupdplugin/fu-mem.c
> trivial: Allow using G_BYTE_ORDER when using fu_memwrite_uintXX()

- libfwupdplugin/fu-efi-signature-list.c
This is required because again Microsoft removed hashes in the x64 DBXUpdate 20230314 update.
> Add the latest dbx version version fixups

- contrib/ci/Dockerfile-fedora.in
- subprojects/fwupd-efi.wrap
Needed for https://github.com/fwupd/fwupd-efi/pull/40
Will trigger a build before merging this to make sure that works rather than waiting 24 hours.
> trivial: Move Fedora CI container from 37 to 39

- plugins/wacom-usb/fu-wac-module.c
The ID6 module is sensitive to retry timing, so match what the Wacom Windows firmware update tool does.
> wacom-usb: Fix flashing the new Intuos BT S

- plugins/uefi-capsule/fu-uefi-device.c
The fix of 0eec0c4a66a5e8a5957172e34fb675cfce646617 was incorrect as the hash table takes allocated strings, and mount_point is g_autofree.
Fixes https://github.com/fwupd/fwupd/issues/5656
> uefi-capsule: Fix possible crash when getting UEFI report metadata

- docs/hsi-tests.d/org.fwupd.hsi.PrebootDma.json
The url to the IVRS documentation was down, so I updated it using the one at UEFI ACPI-related documents
> trivial: Update the url to the AMD IVRS specification

- libfwupdplugin/fu-bios-settings.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/AMDMemoryGuard/current_value
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/AMDMemoryGuard/display_name
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/AMDMemoryGuard/possible_values
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/AMDMemoryGuard/type
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/AlarmDate/current_value
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/AlarmDate/display_name
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/AlarmDate/type
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/StartupSequence/current_value
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/StartupSequence/display_name
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/StartupSequence/possible_values
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/StartupSequence/type
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/WindowsUEFIFirmwareUpdate/current_value
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/WindowsUEFIFirmwareUpdate/display_name
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/WindowsUEFIFirmwareUpdate/possible_values
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/WindowsUEFIFirmwareUpdate/type
- libfwupdplugin/tests/bios-attrs/lenovo-p620-6.3/thinklmi/attributes/pending_reboot
- meson.build
- meson_options.txt
- plugins/lenovo-thinklmi/fu-self-test.c
- plugins/lenovo-thinklmi/tests/firmware-attributes/locked/thinklmi/attributes/BootOrderLock/display_name
- plugins/lenovo-thinklmi/tests/firmware-attributes/reboot-pending/thinklmi/attributes/BootOrderLock/display_name
- plugins/lenovo-thinklmi/tests/firmware-attributes/unlocked/thinklmi/attributes/BootOrderLock/display_name
The plan for this is that we offer a compile option to turn on compatibility with older kernels.
Proposal:
* In ~March 2024 we'll change default for this option to false.
* In ~September 2024 we'll drop all the compatibility code
This PR is currently marked draft because it's pending one more kernel fix to adjust the `current_value` sysfs file to behave properly.  It will be adjusted and marked ready after that is landed in mainline.
@mrhpearson  FYI.
> Adjust thinklmi handling
