plugins/flashrom/flashrom.quirk
=> plugins/flashrom: Update StarBook GUID

plugins/uefi-capsule/fu-uefi-device.c
=> uefi-capsule: Use accurate FuProgress values

plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-common.c, plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
Explicitly set the device to Device(USB) mode. Appliance & BYOD mode not supported
=> Explicitly set to device mode

plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
Retry if device is not in IDLE state
Replace original PR: https://github.com/fwupd/fwupd/pull/3818
=> Retry if device is not in IDLE state

plugins/pixart-rf/pixart-rf.quirk
=> Add more  device for support pixart_rf

plugins/flashrom/fu-flashrom-internal-device.c
=> plugins/flashrom: Always shutdown after flashing

meson_options.txt, plugins/fastboot/meson.build
Fixes https://github.com/fwupd/fwupd/issues/3920
=> Add a configure option for fastboot support

docs/hsi.md, plugins/pci-mei/fu-plugin-pci-mei.c
=> trivial: Add some more details to the HSI specification

plugins/pci-mei/fu-mei-common.c
14.1.53.1649 appeared which showed that the logic was funcky.
=> Fix the CSME CVE detection

src/fu-security-attr.c, src/fu-security-attr.h, src/fu-util-common.c
=> Fix 'trivial: fwupdtool security' to show sane results

contrib/ci/oss-fuzz.py, plugins/cpu/fu-plugin-cpu.c
=> trivial: fix CI failure on fwupd 1.5.x

plugins/dell-dock/dell-dock.quirk, plugins/dell-dock/fu-dell-dock-common.h, plugins/dell-dock/fu-dell-dock-hub.c, plugins/dell-dock/fu-dell-dock-hub.h, plugins/dell-dock/fu-dell-dock-i2c-ec.c, plugins/dell-dock/fu-dell-dock-i2c-ec.h, plugins/dell-dock/fu-dell-dock-i2c-mst.c, plugins/dell-dock/fu-plugin-dell-dock.c
=> dell-dock: Add atomic support to 1_6_X

.github/workflows/greetings.yml
=> Add a welcome message for any new contributors

.github/workflows/main.yml
this will allow us to monitor health for 1.5.x even if not getting
commits.
=> trivial: enable weekly build for 1.5.x

.github/workflows/main.yml, contrib/ci/oss-fuzz.py, plugins/dell-dock/fu-dell-dock-i2c-mst.c
=> trivial: enable Github actions for 1.6.x CI

contrib/fwupd.spec.in
=> Version lock plugins to the daemon in the example spec file

docs/hsi.md
Fixes https://github.com/fwupd/fwupd/issues/3941
=> trivial: Fix several broken links in the HSI specification

plugins/logind/meson.build
=> Build logind plugin for elogind-enabled systems

plugins/dell-dock/dell-dock.quirk, plugins/dell-dock/fu-dell-dock-common.h, plugins/dell-dock/fu-dell-dock-hub.c, plugins/dell-dock/fu-dell-dock-hub.h, plugins/dell-dock/fu-dell-dock-i2c-ec.c, plugins/dell-dock/fu-dell-dock-i2c-ec.h, plugins/dell-dock/fu-dell-dock-i2c-mst.c, plugins/dell-dock/fu-plugin-dell-dock.c
=> dell-dock: Add atomic support to 1_5_X

plugins/vli/fu-vli-device.c
=> vli: Fix a tiny memory leak on idle exit

libfwupdplugin/fu-device.c
=> trivial: Use GObject notify when modifying the proxy

data/installed-tests/fwupd.sh, data/installed-tests/fwupdmgr.sh, plugins/uefi-capsule/fwupd.grub.conf.in
It's trivial to use sh instead of bash, and some people may not want bash pulled in.
=> Use sh instead of bash

plugins/lenovo-dock/fu-lenovo-dock-common.c, plugins/lenovo-dock/fu-lenovo-dock-common.h, plugins/lenovo-dock/fu-lenovo-dock-firmware.c, plugins/lenovo-dock/fu-lenovo-dock-mcu-device.c, plugins/lenovo-dock/lenovo-dock.quirk
=> lenovo-dock: patches for update flow

src/fu-tool.c
=> Wait for device reboot when using fwupdtool detach

docs/hsi.md
=> trivial: Use more standard English in the HSI specification

libfwupdplugin/fu-udev-device.c, libfwupdplugin/fu-udev-device.h, libfwupdplugin/fwupdplugin.map
=> Allow setting the FuUdevDevice bind-id at runtime

docs/hsi.md
=> trivial: Add some Impact sections to HSI attributes

libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, libfwupdplugin/fu-quirks.c, libfwupdplugin/fu-quirks.h, libfwupdplugin/fwupdplugin.map, plugins/altos/fu-altos-device.c, plugins/analogix/fu-analogix-device.c, plugins/dfu-csr/fu-dfu-csr-device.c, plugins/ebitdo/fu-ebitdo-device.c, plugins/elanfp/fu-elanfp-device.c, plugins/ep963x/fu-ep963x-device.c, plugins/hailuck/fu-hailuck-bl-device.c, plugins/pixart-rf/fu-pxi-receiver-device.c, plugins/pixart-rf/fu-pxi-wireless-device.c, plugins/solokey/fu-solokey-device.c, plugins/vli/fu-vli-usbhub-msp430-device.c, plugins/wacom-raw/fu-wacom-device.c, plugins/wacom-usb/fu-wac-device.c, plugins/wacom-usb/fu-wac-module-touch.c
This also allows us to remove quite a lot of boilerplate from plugins.
=> Allow overriding the firmware GType from a quirk file

libfwupdplugin/fu-security-attrs-private.h, libfwupdplugin/fu-security-attrs.c, libfwupdplugin/fwupdplugin.map, plugins/tpm/fu-plugin-tpm.c, plugins/tpm/fu-self-test.c, plugins/tpm/meson.build
Also, add end-to-end tests for this so it can never happen again.
Fixes https://github.com/fwupd/fwupd/issues/3972
=> tpm: Actually add the v1.2 device

data/daemon.conf, libfwupdplugin/fu-hwids.c
To use this create a file in /var/lib/fwupd/hwids.conf
=> Allow overriding HwId data from a config file

libfwupd/fwupd-client.c
=> trivial: Do not show a critical warning is LANG is unset

contrib/firmware_packager/firmware_packager.py
=> firmware_packager.py: Fix templated values in XML

src/fu-tool.c
bash-completion does not need any changes.
=> fwupdtool: Show get-details command argument FILE

plugins/elanfp/fu-elanfp-firmware.c
=> elantp: Fix a tiny memory leak when parsing firmware

plugins/ccgx/fu-ccgx-dmc-firmware.c
Fixes https://oss-fuzz.com/testcase-detail/5426177995046912
=> ccgx: Fix a critial warning found by the fuzzer

libfwupdplugin/fu-quirks.c
=> Show a daemon warning if quirk flags are malformed

plugins/uefi-capsule/fu-uefi-bootmgr.c
=> trivial: Work around two false positives when compiling with gcc -Os

.github/workflows/main.yml, .pre-commit-config.yaml, contrib/run-tests.sh, contrib/setup
Was suggested by @superm1 when I mentioned it during a code review, but now that I've done it I'm not sure because it adds some significant delay before a push can complete.
=> Run tests before pushing

plugins/elanfp/fu-elanfp-firmware.c
Fixes https://oss-fuzz.com/testcase-detail/6107550261575680
=> elanfp: Add some sanity checks to the firmware parser

data/pki/meson.build
=> trivial: Only install files that are going to be used

libfwupdplugin/fu-firmware.c, libfwupdplugin/fu-firmware.h, libfwupdplugin/fu-fuzzer-firmware.c.in
=> Do not leak when calling fu_firmware_parse() multiple times

libfwupdplugin/fu-firmware.c
=> trivial: Never print NULL in the FuFirmware flag output

contrib/PKGBUILD, contrib/ci/build_windows.sh, contrib/ci/debian_s390x.sh, contrib/debian/rules, contrib/fwupd.spec.in, meson_options.txt, plugins/powerd/meson.build, plugins/upower/meson.build, snap/snapcraft.yaml
In some cases you really know that the daemon is never going to exist.
=> Make Upower and powerd support optional

libfwupdplugin/fu-usb-device.h
=> trivial: Fix a warning when compiling without USB support

src/fu-engine.c
=> trivial: Don't add the fallback FDE warning for all devices

data/pki/meson.build, snap/snapcraft.yaml, subprojects/gi-docgen.wrap, subprojects/libjcat.wrap, subprojects/libxmlb.wrap
=> trivial: Update subproject versions to latest

data/motd/meson.build, src/fu-engine-helper.c
This has to be a file, not a file-in-a-directory.
Fixes https://github.com/fwupd/fwupd/issues/4047
=> Enable the MOTD integration when using pam_motd

libfwupdplugin/fu-cfi-device.c
=> trivial: cfi: Fix up a typo

plugins/synaptics-prometheus/synaptics-prometheus.quirk
This is used in some upcoming systems
=> trivial: synaptics-prometheus: add another product ID

plugins/cfu/fu-cfu-module.c
=> cfu: Add a missing version setter

plugins/parade-lspcon/fu-parade-lspcon-device.c
=> parade-lspcon: Add a missing error check

plugins/synaptics-cape/fu-synaptics-cape-device.c
=> synaptics-cape: Do not assume we can align uint8_t to uint32_t automatically

plugins/logitech-hidpp/fu-logitech-hidpp-runtime-bolt.c
=> logitech-hidpp: Use endian-safe version functions

libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, plugins/thunderbolt/fu-plugin-thunderbolt.c, plugins/thunderbolt/fu-thunderbolt-device.c, src/fu-udev-backend.c, src/fu-usb-backend.c
=> trivial: Properly namespace _INTERNAL_FLAG_NO_AUTO_REMOVE

plugins/modem-manager/fu-mm-device.c, plugins/modem-manager/fu-mm-device.h, plugins/modem-manager/fu-plugin-modem-manager.c
=> modem-manager: Set the context when the device is constructed

libfwupdplugin/fu-device.c, libfwupdplugin/fu-self-test.c
=> Copy private flags from donor devices

libfwupdplugin/fu-common.c, libfwupdplugin/fu-common.h, libfwupdplugin/fu-fmap-firmware.c, libfwupdplugin/fu-self-test.c, libfwupdplugin/fwupdplugin.map
=> Add fu_memmem_safe() with fallback code for win32

libfwupdplugin/fu-common.c, libfwupdplugin/fu-common.h, libfwupdplugin/fwupdplugin.map
=> Add fu_common_get_contents_stream() for future usage

plugins/nordic-hid/fu-nordic-hid-archive.c, plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
=> nordic-hid: Fix a few small memory leaks

plugins/cros-ec/cros-ec.quirk
=> add new device Belkin docking station : VID050D/PID003F

libfwupd/fwupd-security-attr.c, src/fu-util.c
Fixes https://github.com/fwupd/fwupd/issues/4099
=> trivial: Handle old JSON-Glib more gracefully

plugins/usi-dock/fu-plugin-usi-dock.c, plugins/usi-dock/fu-usi-dock-common.h, plugins/usi-dock/fu-usi-dock-mcu-device.c
=> usi-dock: This plugin prohibits firmware updates from thunderbolt

libfwupd/fwupd-device.c, libfwupd/fwupd-device.h, libfwupd/fwupd.map
=> trivial: Add fwupd_device_get_root() for GUI use

contrib/snap/fwupd-command, libfwupdplugin/fu-plugin.c, libfwupdplugin/fu-plugin.h, libfwupdplugin/fwupdplugin.map, plugins/redfish/fu-plugin-redfish.c, plugins/redfish/meson.build, snap/snapcraft.yaml
=> snap: use newer json-glib (Fixes: #4099)

meson.build
=> trivial: Fix compiling with -Dbuild=library

libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, plugins/redfish/fu-redfish-device.c, plugins/uefi-capsule/fu-uefi-device.c, src/fu-engine.c
=> Allow devices to opt-in to metadata-provided vendor strings

plugins/pixart-rf/pixart-rf.quirk
=> Add new device support pixart-rf

plugins/nvme/fu-nvme-device.c
Ignore NVMe-over-Fabrics devices when probing. Otherwise, logs might be
flooded with error messages:
03:10:53:0251 FuEngine             failed to add device /sys/devices/virtual/nvme-fabrics/ctl/nvme1: failed to find device with subsystems pci, only got nvme,nvme-fabrics
These devices are not supported as they are not on the PCI subsystem.
Signed-off-by: Enzo Matsumiya <ematsumiya@suse.de>
=> nvme: ignore NVMe-over-Fabrics devices

plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
=> logitech-bulkcontroller: Assign the update interface correctly

docs/tutorial.md
Just dumping this here before I go on holidays, I'll keep working on this when I come back.
These are some things I found useful while coding and debugging. It could be better integrated into the tutorial or maybe put in a different place. Also, I'm not sure documenting the vfuncs is a brilliant idea, but feel free to edit/delete as much as you want. Of course, some things might be out of place or plain wrong, so consider this a work in progress.
=> doc: add developers guidelines and howtos

plugins/logitech-hidpp/fu-logitech-hidpp-device.c
=> logitech-hidpp: Always hardcode the vendor for FuLogitechHidPpDevice

plugins/cros-ec/fu-cros-ec-firmware.c, plugins/cros-ec/fu-cros-ec-firmware.h, plugins/cros-ec/fu-cros-ec-usb-device.c
Also, simplify the helper that's passed to the retry function.
=> cros-ec: Add progress completion when writing blocks

data/device-tests/google-servo-micro.json
=> trivial: Add a device test for the Servo Micro hardware

subprojects/gusb.wrap, subprojects/libxmlb.wrap
=> trivial: Update subprojects to latest versions

plugins/tpm/fu-tpm-eventlog-parser.c
There is one eventlog item with zero size.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2038167
=> trivial: Do not abort with a critical warning for a weird TPM event log

src/fu-tool.c
=> trivial: Do not attempt to stop the daemon when running as user

src/fu-tool.c, src/fu-util-common.c, src/fu-util-common.h, src/fu-util.c
=> trivial: Add support for 'fwupdtool get-plugins --json'

meson.build, plugins/uefi-capsule/fu-uefi-common.h
Fixes https://github.com/fwupd/fwupd/issues/4181
=> Fix compiling with new versions of efivar

src/fu-tool.c
=> trivial: Do not show progressbar status reports when using --json

src/fu-util-common.c
=> trivial: Add more translations for HSI events

plugins/modem-manager/fu-mm-device.c
Fixes https://github.com/fwupd/fwupd/issues/4190
=> modem-manager: Only try to get the branch if there exists an AT port

libfwupd/fwupd-error.c, libfwupd/fwupd-error.h, plugins/redfish/fu-plugin-redfish.c, plugins/redfish/fu-redfish-request.c, plugins/redfish/meson.build
=> redfish: Change an expired password when required

plugins/rts54hub/fu-rts54hub-rtd21xx-background.c, plugins/rts54hub/fu-rts54hub-rtd21xx-device.c, plugins/rts54hub/fu-rts54hub-rtd21xx-device.h, plugins/rts54hub/fu-rts54hub-rtd21xx-foreground.c, plugins/vli/fu-vli-usbhub-rtd21xx-device.c
=> trivial: Change some problematic language that crept in

src/fu-engine.c
=> trivial: Add the missing keys for the daemon ModifyConfig method

meson.build
=> Use GCC static analysis when available

README.md, src/fu-engine.c
Fixes https://github.com/fwupd/fwupd/issues/4040
=> Allow specifying the BKC locally

libfwupdplugin/fu-common.c, libfwupdplugin/fu-common.h, src/fu-config.c
This is super useful for debugging immutable systems like ChromeOS.
=> Allow overriding daemon parameters using /var/etc/fwupd/daemon.conf

plugins/dell-dock/fu-plugin-dell-dock.c
=> dell-dock: fix a segfault if device isn't added yet

subprojects/fwupd-efi.wrap
=> trivial: Update the built subproject version of fwupd-efi

src/fu-util-common.c
=> Translate the firmware flags when using fwupdmgr

contrib/ci/ubuntu.sh
=> trivial: ci: fix ubuntu ci

.circleci/config.yml, contrib/ci/Dockerfile-fedora.in
=> trivial: Move the CI to Fedora 35

src/fu-engine-request.c, src/fu-engine-request.h, src/fu-main.c, src/org.freedesktop.fwupd.xml
This makes it easier to test the installed fwupd for the installed tests.
=> Allow the root user to ask the daemon to quit

src/fu-util.c
=> trivial: Always use the GCancellable in fwupdmgr

contrib/firmware_packager/install_dell_bios_exe.py, contrib/firmware_packager/simple_client.py
See https://github.com/fwupd/fwupd/issues/3644 for details.
Fixes https://github.com/fwupd/firmware-dell/issues/105
=> Fix install_dell_bios_exe.py by removing extraneous code

plugins/msr/fu-plugin-msr.c
=> trivial: msr: add more debugging data for register status

plugins/ata/meson.build, plugins/nvme/meson.build, plugins/synaptics-mst/fu-self-test.c, plugins/synaptics-mst/meson.build, plugins/thunderbolt/fu-self-test.c, plugins/thunderbolt/meson.build, plugins/thunderbolt/tests/quirks.d/thunderbolt.quirk
=> trivial: use src directory for quirks for ata and nvme plugins

src/fu-engine.c, src/fu-tool.c, src/fu-util-common.c, src/fu-util-common.h, src/fu-util.c
To use this, do: `fwupdmgr --version --json`
=> Add support for outputting versions in JSON format

plugins/nordic-hid/README.md
=> plugins/nordic-hid: extend the doc with tested HW

.circleci/config.yml
=> trivial: Try to debug the close_range() issue a bit more

libfwupdplugin/fu-smbios.c
Fixes https://github.com/fwupd/fwupd/issues/4253
=> Get the SMBIOS table on Windows

src/fu-engine.c
=> Get the host machine ID when running on Windows

libfwupd/fwupd-enums.c, libfwupd/fwupd-enums.h, src/fu-engine.c, src/fu-util-common.c
This probably means it is unlikely to get any new security updates.
=> Allow marking a device as EOL

src/fu-engine.c, src/fu-plugin-list.c
=> flashrom: Fix loading devices in coreboot mode

plugins/intel-spi/fu-ifd-device.c, plugins/intel-spi/fu-ifd-device.h, plugins/intel-spi/fu-intel-spi-device.c
=> trivial: Use FuContext when creating FuIfdDevice children

src/fu-engine.c, src/fu-util-common.c
=> trivial: Add new category type for video display

libfwupdplugin/fu-common-version.c, libfwupdplugin/fu-common-version.h, libfwupdplugin/fu-device.c, libfwupdplugin/fu-self-test.c, libfwupdplugin/fwupdplugin.map
=> flashrom: Try harder to convert to a correct verfmt semver

plugins/amt/fu-plugin-amt.c
=> Do not include the vendor name in the AMT device

src/fu-tool.c, src/fu-util.c
Fixes https://github.com/fwupd/fwupd/issues/4281
=> Show the user when devices are updatable by inhibited

plugins/flashrom/flashrom.quirk
=> plugins/flashrom: Add Star Lite Mk III coreboot GUID

.circleci/config.yml
See https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/
=> trivial: Don't -use 16.04 in CircleCI

plugins/thunderbolt/fu-thunderbolt-common.c
=> thunderbolt: Fix up some error handling when updating usb4 retimers

plugins/dell/fu-plugin-dell.c, plugins/tpm/fu-tpm-v2-device.c
=> Don't show TSS2 error messages by default (Fixes: #4291)

plugins/uefi-capsule/meson.build
=> trivial: Do not install test data for -Dtests=false

libfwupdplugin/fu-device.c
=> trivial: Show the firmware GType in the device ->to_string()

plugins/mtd/README.md, plugins/mtd/fu-mtd-device.c, plugins/mtd/fu-plugin-mtd.c
=> mtd: Add two more instance IDs to the MTD devices

data/installed-tests/fwupdmgr-p2p.sh, src/fu-util-common.c
=> Try to fix autopkgtests

libfwupdplugin/fu-udev-device.c, libfwupdplugin/fu-udev-device.h, libfwupdplugin/fwupdplugin.map
=> trivial: Add missing API wrapper for future functionality

README.md
People can get help through this repository or IRC/Matrix.
Fixes https://github.com/fwupd/fwupd/discussions/4320
=> README: add Where to get help? section

src/fu-tool.c, src/fu-util.c
=> Device prompting counter-proposal

plugins/modem-manager/fu-mm-device.c
Fixes https://github.com/fwupd/fwupd/issues/4319
=> modem-manager: Copy the AT retry behaviour in ModemManager

libfwupdplugin/fu-udev-device.c
=> trivial: Fix two potential critical warnings when finding devices

libfwupdplugin/fu-device.c, libfwupdplugin/fu-self-test.c
=> trivial: Strip leading and trailing spaces from the vendor name

meson.build
=> trivial: fix a meson build system failure with systemd

plugins/modem-manager/fu-plugin-modem-manager.c
Quectel EG25-G modem in the Pine64 PinePhone and PinePhone Pro can be
booted with the eg25-manager (user space) or modem-power (kernel space).
We only support the eg25-manager for upgrading these modems.
Based on a patch by Dylan Van Assche <me@dylanvanassche.be>, thanks.
=> modem-manager: Detect presence of modem-power driver

libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, libfwupdplugin/fu-quirks.h
=> trivial: Clarify the unit for the device remove delay

data/installed-tests/fwupdmgr-p2p.sh, data/installed-tests/meson.build
Fixes https://github.com/fwupd/fwupd/issues/4360
=> Do not hardcode the libexecdir to /usr/libexec

plugins/uefi-dbx/fu-plugin-uefi-dbx.c, plugins/uefi-dbx/meson.build, plugins/uefi-dbx/uefi-dbx.quirk
This list of hardware is provided by Microsoft.
=> uefi-dbx: No not allow the DBX update for specific motherboards

libfwupdplugin/fu-common.c
See https://github.com/fwupd/fwupd/pull/4372
=> Do not leak child processes when cancelling

libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, libfwupdplugin/fu-self-test.c, libfwupdplugin/fwupdplugin.map, src/fu-device-list.c
=> Do not show unconnected or unreachable devices in the client tools

libfwupd/meson.build, libfwupdplugin/fu-common-darwin.c, libfwupdplugin/fu-efivar-darwin.c, libfwupdplugin/meson.build, meson.build
This is more for curiosity than anything else.
=> Fix build for MacOS

libfwupdplugin/fu-device.c, libfwupdplugin/fu-plugin.c, plugins/dell-dock/fu-dell-dock-i2c-ec.c, plugins/dell-dock/fu-dell-dock-i2c-mst.c, plugins/dell-dock/fu-dell-dock-i2c-mst.h, plugins/dell-dock/fu-dell-dock-i2c-tbt.c, plugins/dell-dock/fu-dell-dock-status.c, plugins/dell-dock/fu-dell-dock-status.h, plugins/dell-dock/fu-plugin-dell-dock.c, plugins/dfu/fu-dfu-device.c, plugins/dfu/fu-dfu-device.h, plugins/dfu/fu-dfu-self-test.c, plugins/dfu/fu-dfu-tool.c, plugins/flashrom/fu-plugin-flashrom.c, plugins/thunderbolt/fu-plugin-thunderbolt.c, plugins/uefi-capsule/fu-plugin-uefi-capsule.c
=> Set the context in the right place more often

src/fu-util-common.c
Fixes https://github.com/fwupd/fwupd/issues/4400
=> Show the user a wiki page about the FDE warning

plugins/ata/fu-ata-device.c
=> ata: Add signed-payload for Phison devices

plugins/thunderbolt/fu-plugin-thunderbolt.c, plugins/thunderbolt/fu-thunderbolt-common.h, plugins/thunderbolt/fu-thunderbolt-controller.c, plugins/thunderbolt/thunderbolt.conf
=> thunderbolt: add configuration option to force retimer enumeration

.circleci/config.yml
=> trivial: Add one extra mingw package to fix CI

plugins/mtd/fu-self-test.c
=> trivial: Fix the mtd test when the prefix is read only

plugins/upower/fu-plugin-upower.c
=> upower: Support the new PENDING device states

plugins/genesys/fu-genesys-usbhub-device.c
=> genesys: usbhub: Fix memory leak

plugins/tpm/fu-tpm-eventlog-common.c
=> tpm: Fix eventlog replay for Intel TXT machines

plugins/logitech-hidpp/fu-logitech-hidpp-device.c
=> logitech-hidpp: Inherit the icon for the child device from the parent

libfwupd/fwupd-release.c
=> libfwupd: Add a FwupdRelease:remote-id property

contrib/setup
Fixes https://github.com/fwupd/fwupd/issues/4080
=> Detect SELinux before offering to install into /usr/local

plugins/modem-manager/fu-mm-device.c
=> modem-manager: Add signed-payload metadata for some Quectel devices

.pre-commit-config.yaml
=> trivial: bump python black version to fix CI

libfwupdplugin/fu-usb-device.c
See https://github.com/fwupd/fwupd/pull/4426#discussion_r836155609
=> Correctly probe USB-2 hubs with more than 7 ports

plugins/nvme/nvme.quirk
=> nvme: Add signed-payload for Western Digital hardware

docs/env.md, src/fu-main.c
This makes developing HSI tests and UIs much easier when using VMs or
containers.
=> Allow overriding the detected machine type

libfwupdplugin/fu-cfi-device.c, libfwupdplugin/fu-self-test.c, plugins/genesys/fu-genesys-scaler-device.c, plugins/genesys/fu-genesys-usbhub-device.c, plugins/vli/fu-vli-device.c
=> Add the CFI quirks in setup() so the device can be open

data/cfi.quirk, libfwupdplugin/fu-cfi-device.c, libfwupdplugin/fu-quirks.c
=> Use the CFI manufacturer ID to set the vendor

plugins/system76-launch/README.md, plugins/system76-launch/fu-system76-launch-device.c, plugins/system76-launch/system76-launch.quirk
=> Add System76 launch_lite_1

libfwupdplugin/fu-cfi-device.c
=> Add some default size values to the CFI device

plugins/genesys/fu-genesys-usbhub-device.c
Additionally, this regroups the call of a function and the test for the
returned value.
This fixes a minor issue that has escaped from my review :facepalm:.
=> genesys: usbhub: Fix test for static_tool_string value

plugins/linux-swap/fu-plugin-linux-swap.c
=> trivial: linux-swap: Don't create attribute unless kernel has support

contrib/fwupd.spec.in, docs/hsi.md, libfwupd/fwupd-security-attr-private.h, plugins/acpi-dmar/fu-plugin-acpi-dmar.c, plugins/acpi-ivrs/README.md, plugins/acpi-ivrs/fu-acpi-ivrs.c, plugins/acpi-ivrs/fu-acpi-ivrs.h, plugins/acpi-ivrs/fu-plugin-acpi-ivrs.c, plugins/acpi-ivrs/fu-self-test.c, plugins/acpi-ivrs/meson.build, plugins/meson.build, src/fu-security-attr.c, src/fu-util-common.c
=> Add support for ACPI IVRS table for HSI security attributes

plugins/scsi/fu-scsi-device.c
=> trivial: scsi: fix a segfault with USB SCSI device plugged in

libfwupd/fwupd-device.c
Fixes https://github.com/fwupd/fwupd/issues/4501
=> Add InstanceIds to the JSON device dump

plugins/uefi-capsule/fu-uefi-device.c
=> uefi-capsule: Use GByteArray to make code more modern

plugins/dell-dock/dell-dock.quirk, plugins/dell-dock/fu-dell-dock-i2c-ec.c
=> dell-dock: set minimum version of EC

contrib/firmware_packager/install_dell_bios_exe.py, contrib/firmware_packager/simple_client.py
trivial: temporarily disable lvfs signing to proceed BIOS.exe installation
=> trivial: temporarily disable lvfs signing to proceed BIOS.exe installation

plugins/dell-dock/fu-plugin-dell-dock.c
=> trivial: add device GUID to avoid warning message 'no GUIDs for device'

docs/hsi.md, libfwupd/fwupd-security-attr-private.h, plugins/msr/fu-plugin-msr.c, src/fu-security-attr.c
These are to be used by https://github.com/fwupd/fwupd/pull/4471
=> Add new security attributes

plugins/dell-dock/fu-plugin-dell-dock.c
=> dell-dock: set mst payload default unsigned

plugins/dfu/dfu.quirk
=> dfu: modified VID/PID for atlas camera.

plugins/redfish/fu-plugin-redfish.c, plugins/redfish/fu-redfish-legacy-device.c, plugins/redfish/fu-redfish-request.c, plugins/redfish/fu-redfish-request.h
=> redfish: Allow specifying the request type

plugins/redfish/README.md, plugins/redfish/fu-plugin-redfish.c, plugins/redfish/fu-redfish-device.c, plugins/redfish/fu-redfish-device.h, plugins/redfish/redfish.quirk
=> redfish: Restart the BMC after installing BCM updates

.github/stale.yml
=> trivial: Make the language in the stale job more pathetic

.github/workflows/create_containers.yml
=> trivial: allow manually running the container generation workflow

libfwupdplugin/fu-usb-device.c, plugins/dfu/fu-dfu-device.c, plugins/vli/fu-vli-usbhub-device.c
=> dfu: Use the correct icon automatically for USB webcams

libfwupd/fwupd-client.c
=> Add a sanity check when trying to refresh a non-download remote

SECURITY.md
=> Make the security policy reflect reality

contrib/ci/Dockerfile-fedora.in, contrib/ci/fedora.sh, contrib/debian/fwupd.postinst, contrib/debian/rules, data/motd/fwupd-refresh.preset, data/motd/fwupd-refresh.service.in, data/motd/meson.build, meson_options.txt, plugins/dell/fu-dell-smi.c
=> Backport fwupd-refresh solution to 1-7-x

libfwupdplugin/fu-common.c, libfwupdplugin/fu-common.h, libfwupdplugin/fwupdplugin.map
=> trivial: Add some new helper API for future functionality

libfwupdplugin/fu-firmware.c, libfwupdplugin/fu-self-test.c
=> Check the alignment when reading in raw firmware

libfwupdplugin/fu-common.c, libfwupdplugin/fu-common.h, libfwupdplugin/fu-self-test.c, libfwupdplugin/fwupdplugin.map, plugins/dfu-csr/fu-dfu-csr-device.c, plugins/dfu/fu-dfu-device.c
=> trivial: Add fu_common_read_uint24() helper for future code

plugins/synaptics-mst/fu-synaptics-mst-device.c
=> synaptics-mst: Read the fw-size in a more safe way

src/fu-util.c
Fixes https://github.com/fwupd/fwupd/issues/4576
=> trivial: Restore 'fwupdmgr install http://...' behaviour

plugins/parade-lspcon/fu-parade-lspcon-device.c
Fixes https://github.com/fwupd/fwupd/issues/4580
=> parade-lspcon: Fix regression when probing PS175 devices

plugins/flashrom/fu-flashrom-device.c
=> flashrom: Allow dumping firmware using fwupdtool

contrib/ci/build_windows.sh, libfwupdplugin/fu-self-test.c, src/fu-main.c
=> Fix the win32 CI tests

contrib/ci/Dockerfile-ubuntu.in
=> Use ubuntu:rolling to fix longstanding CI issue

contrib/ci/build_windows.sh, plugins/bios/meson.build
=> trivial: disable bios plugin for Win32

plugins/scsi/README.md, plugins/scsi/fu-scsi-device.c
Change-Id: I5573b1890135d1fd3b2f0cb8f95f74cbb3e21abe
=> scsi: Support updating firmware on UFS devices

libfwupd/fwupd-client-sync.c, libfwupd/fwupd-client.c
There's nothing we need as all the useragent data is client-side.
=> trivial: Do not connect the daemon to download files

contrib/ci/build_windows.sh
=> trivial: Reduce the size of the MSI by removing static libraries

src/fu-tool.c
=> trivial: Create a FwupdClient in fwupdtool

libfwupd/fwupd-client.c
=> Use the native CA store on Windows when possible

contrib/build-windows.sh, contrib/ci/build_windows.sh, contrib/ci/check-license.py, contrib/ci/check-null-false-returns.py
=> Adjustments for MOTD/NEWS/VERSION on Win32

libfwupd/fwupd-common.c
=> trivial: libfwupd: fix an unused variable in Win32

plugins/dfu/dfu.quirk
=> dfu: Update dfu quirk file for SPIT pccam's chips

src/fu-debug.c
=> Log errors and warnings to the win32 eventlog

libfwupd/fwupd-client.c, libfwupd/fwupd-common.h, src/fu-daemon.c, src/fu-daemon.h, src/fu-main-windows.c, src/fu-main.c, src/meson.build
=> Use StartServiceCtrlDispatcherA for the daemon on Windows

plugins/mtd/fu-self-test.c
=> trivial: skip mtd tests if not working off mtdram test device

plugins/steelseries/README.md, plugins/steelseries/fu-plugin-steelseries.c, plugins/steelseries/fu-steelseries-common.c, plugins/steelseries/fu-steelseries-common.h, plugins/steelseries/fu-steelseries-sonic.c, plugins/steelseries/fu-steelseries-sonic.h, plugins/steelseries/meson.build, plugins/steelseries/steelseries.quirk
=> steelseries: Add support for Rival 3 Wireless

libfwupdplugin/fu-bluez-device.c
=> bluetooth: Set version if REV has been set

plugins/ccgx/ccgx.quirk
=> ccgx: add Lenovo USB-C dock to the quirk file

libfwupd/fwupd-client.c, src/fu-tool.c, src/fu-util-common.c, src/fu-util-common.h, src/fu-util.c
We'll need this for future functionality when using client in fwupdtool.
=> trivial: Make the FwupdClient host properties RW

libfwupdplugin/fu-archive-firmware.c, libfwupdplugin/fu-archive-firmware.h, libfwupdplugin/fu-archive.c, libfwupdplugin/fu-archive.h, libfwupdplugin/fwupdplugin.map, libfwupdplugin/tests/archive.builder.xml, meson.build
This is an early work on implement the `_write()` support for `FuArchive` and `FuArchiveFirmware`.
=> archive: Add writing support

plugins/steelseries/fu-steelseries-sonic.c
This is an example on how to use the write support for an `FuArchiveFirmware`.
=> steelseries: sonic: Allow to read firmware

src/fu-util.c
=> trivial: util: Fix trailing space

docs/tutorial.md, plugins/steelseries/fu-plugin-steelseries.c
This fixes the commits 7eb053e97ae416ec0a8ff43b8995dce23dcbb0af and
9a5c69417aaa6367e5c0034d55dd10f9bc25b886.
=> trivial: Update with recent steelseries changes

libfwupd/meson.build, meson.build, plugins/thunderbolt/meson.build
=> Do not run some tests using -Db_sanitize=address

src/fu-engine.c, src/fu-util-common.c
=> Add X-UsbReceiver as an update category

src/fu-tool.c
=> fu-tool: Allow to request immediate actions from the end user

plugins/corsair/README.md, plugins/corsair/corsair.quirk, plugins/corsair/fu-corsair-bp.c, plugins/corsair/fu-corsair-bp.h, plugins/corsair/fu-corsair-common.h, plugins/corsair/fu-corsair-device.c, plugins/corsair/fu-corsair-device.h, plugins/corsair/fu-plugin-corsair.c, plugins/corsair/meson.build
Add new devices to the corsair plugin:
* KATAR PRO XT
* SABRE PRO
* KATAR PRO WIRELESS
=> corsair: add support for new devices

plugins/uefi-capsule/fwupdate.1
=> trivial: Typofix fwupdate(1) NAME

.circleci/config.yml
=> Attempt to fix CircleCI build issues

plugins/corsair/fu-corsair-device.c
Small improvements to subdevice handling:
* add IN endpoint flushing for a subdevice
* don't check for a subdevice if in bootloader mode
* add delay for a first subdevice check to prevent unneeded polling
=> corsair: improve subdevice handling

libfwupdplugin/fu-cfi-device.c, libfwupdplugin/fu-quirks.c, libfwupdplugin/fu-quirks.h
This adds the missing definitions for the CFI quirks.
=> trivial: Add quirk definitions for CFI

plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c, src/fu-tool.c
=> logitech-bulkcontroller: Only move the progressbar forwards when writing

.github/workflows/main.yml
=> Use the latest LTS version for CI

plugins/genesys/fu-genesys-usbhub-device.c
=> genesys: Do not claim interface 0

.github/workflows/create_containers.yml
=> trivial: fix publishing of docker containers

contrib/qubes/src/qubes_fwupd_heads.py, contrib/qubes/src/qubes_fwupdmgr.py, contrib/qubes/test/test_qubes_fwupd_heads.py, contrib/qubes/test/test_qubes_fwupdmgr.py
Following commits update Qubes OS fwupd wrapper to the newest Heads versioning. Also, these update URLs and checksums in the test cases and fix minor problems.
=> wip/3mdeb/qubes_fwupd_heads_versioning: qubes-fwupd Heads versioning 

libfwupdplugin/fu-progress.c, plugins/corsair/fu-corsair-device.c, src/fu-daemon.c, src/fu-engine.c
Fixes https://github.com/fwupd/fwupd/issues/4749
=> Fix a progress regression when installing archives with fwupdtool

data/bash-completion/fwupdagent, data/bash-completion/fwupdmgr, data/bash-completion/fwupdtool, data/bash-completion/meson.build, libfwupd/fwupd-device-private.h, libfwupd/fwupd-device.c, libfwupd/fwupd-self-test.c, libfwupd/fwupd.map, src/fu-engine-helper.c, src/fu-engine-helper.h, src/fu-engine.c, src/fu-tool.c
Very trivial changes on bash-completion.
=> Fix bash completion scripts

data/device-tests/corsair-harpoon-rgb-wireless.json, data/device-tests/meson.build, plugins/corsair/corsair.quirk
Add HARPOON RGB WIRELESS to the corsair plugin.
=> corsair: add HARPOON RGB Wireless mouse

docs/tutorial.md
Fixes https://github.com/fwupd/fwupd/issues/4755
=> trivial: Document the ->set_progress() vfunc

.circleci/config.yml, .github/workflows/codeql-analysis.yml, .github/workflows/main.yml, contrib/ci/Dockerfile-ubuntu.in, contrib/ci/debian.sh, contrib/ci/dependencies.xml, contrib/ci/fwupd_setup_helpers.py, contrib/ci/ubuntu.sh, contrib/setup
=> Fix the CI failures

libfwupdplugin/fu-udev-device.c, libfwupdplugin/fu-udev-device.h
=> Get the UDev vendor ID from the grandparent when required

contrib/ci/dependencies.xml
=> trivial: Add deps when building on aarch64

plugins/dell-dock/README.md
=> dell-dock: update doc to clarify the inhibition of usb4 device

.github/workflows/codeql-analysis.yml, contrib/PKGBUILD, contrib/build-openbmc.sh, contrib/build-windows.sh, contrib/ci/build_macos.sh, contrib/ci/build_windows.sh, contrib/ci/centos.sh, contrib/ci/check-abi, contrib/ci/debian_s390x.sh, contrib/ci/fedora.sh, contrib/ci/ubuntu.sh, contrib/debian/rules, contrib/freebsd/Makefile, contrib/fwupd.spec.in, contrib/vscode/build.sh, docs/meson.build, meson.build, meson_options.txt, snap/snapcraft.yaml
=> trivial: change docs to a meson feature (Fixes: #4791)

libfwupd/fwupd-enums.c, libfwupd/fwupd-remote-private.h, libfwupd/fwupd-remote.c, libfwupd/fwupd-self-test.c, libfwupd/fwupd.map, libfwupd/meson.build, libfwupd/tests/auth.conf, libfwupd/tests/auth/meson.build, libfwupd/tests/auth/metadata.xml.gz, libfwupd/tests/meson.build, libfwupdplugin/fu-cfu-offer.c, libfwupdplugin/fu-oprom-firmware.c, libfwupdplugin/fu-self-test.c, libfwupdplugin/fu-string.c, libfwupdplugin/fu-string.h, libfwupdplugin/fwupdplugin.map, libfwupdplugin/tests/cfu-offer.builder.xml
=> Add some coverage tests for FwupdRemote

plugins/dell-dock/fu-dell-dock-i2c-ec.c, plugins/dell-dock/fu-dell-dock-i2c-mst.c
made changes based on:
https://github.com/fwupd/fwupd/wiki/Daemon-Warning:-FuProgress-steps
=> dell-dock: Use accurate FuProgress steps for ec and mst

plugins/logitech-hidpp/README.md, plugins/logitech-hidpp/fu-logitech-hidpp-device.c
Add the legacy instance IDs to make old firmware work.
=> logitech-hidpp: Fix flashing the K750 keyboard

.pre-commit-config.yaml, contrib/ci/check-finalizers.py, plugins/corsair/fu-corsair-device.c
=> Add a precommit script to check for missing GObject finalizers

contrib/fwupd.spec.in, docs/meson.build
=> trivial: Continue to install the index page to fix the docs deployment

plugins/elanfp/elanfp.quirk, plugins/elanfp/fu-elanfp-device.c
Add new protocol for CFU update.
=> elanfp: Add new protocol for CFU update

plugins/uefi-capsule/README.md, plugins/uefi-capsule/fu-plugin-uefi-capsule.c
Fixes https://github.com/fwupd/fwupd/issues/4823
=> Do not use CoD even when advertized on non-aarch64 platforms

plugins/dell-dock/README.md
=> dell-dock: update doc to clarify the hidden inhibited usb4 device

plugins/ccgx/ccgx-noinst.quirk
=> ccgx: Add quirk entries for the Goshen Ridge EVB

src/fu-util.c
Fixes https://github.com/fwupd/fwupd/issues/4843
=> Do not return with rc=0 when devices are not found

plugins/amt/fu-amt-device.c
=> amt: Connect to the interface during ->open()

contrib/ci/arch.sh
=> contrib/ci: Backport #4862 to 1_7_X

libfwupdplugin/fu-quirks.c
=> trivial: don't use /proc/self/exe on Windows

plugins/ccgx/ccgx.quirk
Changes: 
- Add another USB VID/PID for Lenovo USB-C Dock to the quirk file.
=> ccgx:add new dock to the quirk file

plugins/cros-ec/cros-ec.quirk
=> cros-ec: Add Prism board

src/meson.build
Fixes https://github.com/fwupd/fwupd/issues/4874
=> Fix meson dist with -Dgresource_quirks=enabled

meson.build
=> trivial: Include the new 'leak' sanitizer in the opt-out list

docs/env.md, libfwupdplugin/fu-backend.c, libfwupdplugin/fu-backend.h, libfwupdplugin/fu-plugin-private.h, libfwupdplugin/fu-plugin.c, libfwupdplugin/fu-plugin.h, libfwupdplugin/fwupdplugin.map, plugins/dell/fu-plugin-dell.c, plugins/flashrom/fu-plugin-flashrom.c, plugins/gpio/fu-plugin-gpio.c, plugins/iommu/fu-plugin-iommu.c, plugins/linux-lockdown/fu-plugin-linux-lockdown.c, plugins/logind/fu-plugin-logind.c, plugins/modem-manager/fu-plugin-modem-manager.c, plugins/msr/fu-plugin-msr.c, plugins/pci-bcr/fu-plugin-pci-bcr.c, plugins/pci-mei/fu-plugin-pci-mei.c, plugins/redfish/fu-plugin-redfish.c, plugins/redfish/fu-redfish-backend.c, plugins/test/fu-plugin-test.c, plugins/tpm/fu-plugin-tpm.c, plugins/uefi-capsule/fu-plugin-uefi-capsule.c, plugins/uefi-capsule/fu-uefi-backend.c, plugins/uefi-pk/fu-plugin-uefi-pk.c, plugins/vbe/fu-plugin-vbe.c, src/fu-engine.c
This is really useful for debugging.
=> Allow plugins and backends to print debugging information to the console

plugins/iommu/fu-plugin-iommu.c
=> trivial: Show what the user should do for IOMMU failure

plugins/modem-manager/fu-mm-device.c
Add Quectel's specific AT command to check secure boot status of the modem firmware:
AT+QSECBOOT="status"
Typical responses are:
+QSECBOOT: "status",1
+QSECBOOT: "status",0
Firmware versions comparison method should still be used for EM05 modems since it does not expose AT port to the system.
=> modem-manager: add Quectel secure boot status AT command

.pre-commit-config.yaml, contrib/ci/check-potfiles.py
=> Check files are not missing from POTFILES.in during precommit

contrib/generate-emulation.py, libfwupd/fwupd-bios-attr.c, libfwupdplugin/fu-bios-attrs-private.h, libfwupdplugin/fu-bios-attrs.c, libfwupdplugin/fu-bios-attrs.h, libfwupdplugin/fwupdplugin.map, src/fu-engine.c, src/fu-util-bios-attr.c
=> Allow loading BIOS attributes for host emulation

plugins/usi-dock/usi-dock.quirk
Distinguish display names by cid according to customer requirements.
=> Distinguishing displayed names by CID

src/fu-security-attr-common.c
Fixes some of https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1989
=> trivial: Don't use the security attr result in the title

contrib/ci/check-potfiles.py, contrib/ci/populate-bios-attr-translations.py, libfwupdplugin/fu-bios-attrs.c, libfwupdplugin/tests/bios-attrs/dell-xps13-9310/strings.txt, po/POTFILES.in, src/fu-util-bios-attr.c
=> Add support for translation for the sample Dell BIOS setting strings

plugins/cros-ec/fu-cros-ec-usb-device.c
=> cros-ec: adding stay-in-ro command if EC is in bootloader

src/fu-util.c
=> Prompt users to fix BIOS configuration issues

src/fu-tool.c, src/fu-util.c
The discussion: https://github.com/fwupd/fwupd/discussions/4921
=> Install all devices with the same composite id in fwupdtool

src/fu-release.c
These are saved on the <release>, not the <component>.
Fixes half of https://github.com/fwupd/fwupd/issues/4929
=> Actually parse AppStream issues

src/fu-daemon.c
Fixes https://github.com/fwupd/fwupd/issues/4932
=> Do not assert when running with no plugins

plugins/linux-swap/fu-self-test.c
Fixes https://github.com/fwupd/fwupd/issues/4684
=> Allow self tests to pass when run in LXC zones

libfwupdplugin/fu-common.c
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2119436
=> Include vfat in the list of possible BDP partition types

plugins/linux-tainted/fu-plugin-linux-tainted.c
For example, working around a firmware bug in the kernel isn't really
what the HSI attribute was intended to measure.
=> Only fail the kernel tainted HSI test for specific taint reasons

libfwupd/fwupd-security-attr.c
=> Do not show HSI events where we changed the spec result value

libfwupdplugin/fu-udev-device.c
Some udev subsystems run probers to populate the values, rather than
just the kernel providing the sysfs files. Support reading these too.
=> Use ID_VENDOR_ID and ID_MODEL_ID fallbacks

docs/bios-settings.md, docs/fwupdplugin.toml.in, src/fu-util-bios-setting.c, src/fu-util.c
=> Add documentation for fwupd BIOS settings API

contrib/firmware_packager/simple_client.py
=> trivial: add get-bios-setting command to simple-client

libfwupdplugin/fu-firmware.c, libfwupdplugin/fu-firmware.h, libfwupdplugin/fwupdplugin.map
=> Add a new vfunc to check if two firmwares are compatible

libfwupdplugin/fu-bios-settings.c
Turning on UEFI secure boot on Lenovo systems with 3rd party CA turned off will cause a boot loop.
@mrhpearson FYI
=> trivial: don't allow turning on secure boot if 3rd party CA is off

contrib/ci/fwupd_setup_helpers.py, contrib/fwupd.spec.in, docs/hsi.md, docs/index.html, docs/meson.build, meson.build, snap/snapcraft.yaml, src/fu-tool.c, src/fu-util.c
I think we want our documentation more accessible as fwupd 1.8.4 will have more scrutiny of HSI and BIOS settings and such.
=> Documentation improvements for 1.8.4

plugins/elantp/fu-elantp-hid-device.c, plugins/elantp/fu-elantp-i2c-device.c
1. Fix missing initial firmware page size.
2. Remove duplicate add instance value.
=> elantp: fix missing initial value and remove duplicate code

docs/test-deps.py
Fixes: #4976
Suggested-by: eschwartz93@gmail.com
=> trivial: add an explicit check for python's packaging module

libfwupdplugin/fu-context.c, plugins/lenovo-thinklmi/fu-plugin-lenovo-thinklmi.c, plugins/lenovo-thinklmi/fu-self-test.c, plugins/lenovo-thinklmi/tests/etc/fwupd/daemon.conf, src/fu-engine.c
=> Fix lenovo-thinklmi and add a new case for it

data/device-tests/corsair-sabre-rgb-pro.json, data/device-tests/meson.build, plugins/corsair/corsair.quirk
Add SABRE RGB PRO Gaming mouse
=> corsair: add SABRE RGB PRO Gaming mouse

libfwupdplugin/fu-kernel.c, libfwupdplugin/fu-kernel.h, libfwupdplugin/fwupdplugin.map, src/fu-engine.c
=> Add shared functionality to get the parsed kernel cmdline

contrib/ci/dependencies.xml, contrib/ci/fwupd_setup_helpers.py, contrib/ci/generate_debian.py, contrib/debian/control.in, contrib/debian/fwupd.install, contrib/debian/rules
Some of these occurred downstream, but also more important debian/control generator wasn't working anymore.  Fix it.
=> Merge debian packaging changes

libfwupd/fwupd-context-test.c, libfwupd/fwupd-thread-test.c
=> trivial: Fix a -Wdeprecated-declarations issue

contrib/ci/debian.sh
=> trivial: Fix Debian CI harder

src/fu-config.c
PVS: Expression is always false
=> Limit the archive size to 25% of the RAM, or 4G

plugins/android-boot/fu-android-boot-device.c
Store strings during the lifetime of the plugin and free them when destroyed.
=> android-boot: fix segfault

libfwupdplugin/fu-firmware.c, libfwupdplugin/fu-intel-thunderbolt-nvm.c, plugins/bcm57xx/fu-bcm57xx-firmware.c, plugins/ccgx/fu-ccgx-firmware.c, plugins/elantp/fu-elantp-firmware.c, plugins/ep963x/fu-ep963x-firmware.c, plugins/fresco-pd/fu-fresco-pd-firmware.c, plugins/nordic-hid/fu-nordic-hid-firmware.c, plugins/pixart-rf/fu-pxi-firmware.c, plugins/steelseries/fu-steelseries-firmware.c, plugins/synaptics-cxaudio/fu-synaptics-cxaudio-firmware.c, plugins/synaptics-mst/fu-synaptics-mst-firmware.c, plugins/vli/fu-vli-pd-firmware.c, plugins/vli/fu-vli-usbhub-firmware.c
=> Set the firmware contents even when subclassing ->parse()

libfwupdplugin/fu-fdt-firmware.c
=> Fix a fuzzing crash when parsing malicious FDT data

libfwupdplugin/fu-volume.c, libfwupdplugin/fu-volume.h, libfwupdplugin/fwupdplugin.map, plugins/uefi-dbx/fu-uefi-dbx-common.c, src/fu-tool.c
Fixes https://github.com/fwupd/fwupd/issues/5035
=> Always check the BDP partitions when getting all the possible ESPs

.github/workflows/main.yml, snap/snapcraft.yaml
Void has been failing a while, let's tear it out for now until that can be fixed.
Also try to update the snap to current standards in hopes we can restore CI for it soon.
=> Some CI fixups

RELEASE
These are both requiring manual steps now, so document them in the release process.
=> trivial: Add RELEASE steps for flatpak and snap

data/motd/fwupd-refresh.service.in
=> trivial: wait for network to be online to run fwupd-refresh.service

contrib/generate-gresource-xml.py
=> trivial: Fix compile when using python 3.7 or older

.github/workflows/create_containers.yml
Give packages permission to fix the runner
=> Follow up for #5052

plugins/dfu/dfu.quirk
- [ v] Feature
I'm a Sonix (https://www.sonix.com.tw/) employee.
Because our company related CAM products need to use this software （fwupd） testing. 
So you need to change the dfu.quirk file
Please let me pass commit
Please email （leo_huang@sonix.com.tw） me if you have any questions. 
I'll improve
Thank you！
=> update the Quirk specifications for our Sonix CAM products

plugins/usi-dock/fu-usi-dock-mcu-device.c
sometimes initialization will report flash busy.
=> usi-dock: Add initialization retry to ensure flash ready

src/fu-security-attr-common.c
The original string is ambiguous to translate and logically incorrect.
=> trivial: Fix the Pre-boot DMA protection HSI long description

contrib/debian/control.in, contrib/debian/fwupd-doc.links, contrib/debian/fwupd.postinst, contrib/debian/lintian/fwupd
=> Some fixups for debian packaging from lintian report

snap/snapcraft.yaml
=> trivial: restore libcurl support in snap (Fixes: #5069)

contrib/fwupd.spec.in, src/meson.build
Split out all the common code into a library, that we can store in our private rpath.
=> trivial: avoid duplication of fu-util tools.

.github/workflows/main.yml, libfwupdplugin/fu-srec-firmware.c
=> trivial: Run the fuzzers for less time during PRs

src/fu-tool.c
=> trivial: Load the builtin plugins when parsing firmware using fwupdtool

contrib/fwupd.spec.in, src/meson.build
This speeds up the build, and further reduces the on disk size by 340kB.
=> Build FuEngine functionality into libfwupdengine

plugins/dfu/meson.build
=> trivial: fix dfu-tool linking

libfwupdplugin/fu-plugin.h, plugins/flashrom/fu-plugin-flashrom.c, plugins/modem-manager/fu-plugin-modem-manager.c
=> trivial: Do not require fu-hash.h for builtin plugins

src/meson.build
=> trivial: Remove unused build file from fwupdmgr

libfwupdplugin/fu-plugin.c, libfwupdplugin/fu-plugin.h, plugins/flashrom/fu-flashrom-plugin.c, plugins/flashrom/meson.build, plugins/modem-manager/fu-mm-plugin.c, plugins/modem-manager/meson.build
This would allow us to convert more easily to a built-in plugin in the future and means we match the source style used in 97% of the other plugins.
No logic changes.
=> Rename the source file and private data of modular plugins

libfwupd/fwupd-request.c, libfwupd/fwupd-request.h, libfwupd/fwupd-self-test.c, libfwupd/fwupd.map
=> Add FwupdRequestFlags for future usage

libfwupd/fwupd-request.c, libfwupd/fwupd-request.h, libfwupd/fwupd-self-test.c, plugins/steelseries/fu-steelseries-sonic.c, src/fu-tool.c, src/fu-util-common.c, src/fu-util-common.h, src/fu-util.c
Also add two more request IDs to make these specific enough to be useful.
=> Allow optionally translating request messages

.github/ISSUE_TEMPLATE/bug-report-general.md, .github/ISSUE_TEMPLATE/bug-report-uefi.md, .github/ISSUE_TEMPLATE/bug-report-wd19.md
Requested by https://github.com/fwupd/fwupd/issues/5123#issuecomment-1268404523
=> Use details balise for devices in issue templates

libfwupdplugin/fu-device-private.h, libfwupdplugin/fu-device.c, libfwupdplugin/fwupdplugin.map, src/fu-engine.c, src/fu-release.c, src/fu-release.h, src/fu-util-common.c
=> Use LVFS::UpdateRequestId to create a translated FwupdRequest

plugins/fpc/fu-fpc-device.c
=> FPC: Increase max firmware size to 400KB

libfwupdplugin/fu-usb-device.c
=> Add the correct instance ID for HUB devices

src/fu-debug.c
Fixes #5140
Note: I didn't actually test this because setting up a build environment for this would take up >10x more time than writing the actual fix. I guess whoever merges this will test anyway and has their things already setup.
=> Fix millisecond formatting

snap/snapcraft.yaml
=> trivial: snap: add some missing deps for classic snap

libfwupd/fwupd-device.c, libfwupd/fwupd-device.h, libfwupd/fwupd.map, libfwupdplugin/fu-device.h
=> Add fwupd_device_has_checksum() for future usage

snap/snapcraft.yaml
Many of the changes are that PR are generally applicable, so bring them in even in advance of moving to the confined snap.
@valentindavid
=> snap: Port some changes from #5062

plugins/fpc/fpc.quirk, plugins/fpc/fu-fpc-device.c
=> add FPC lenfy device support

snap/snapcraft.yaml
=> Fix snap EFI binary location

data/remotes.d/lvfs-testing.conf, data/remotes.d/lvfs.conf, data/remotes.d/meson.build
=> Use xz-compressed metadata to reduce bandwidth used by ~25%

libfwupd/fwupd-remote.c
=> trivial: Store .xz files with the correct filename

libfwupdplugin/fu-device.c, libfwupdplugin/fu-self-test.c
The baseclass is calling fu_device_build_instance_id_quirk() and when we incorporate the device we were only copying the 'proper' instance IDs and not the ones used for quirk matching -- which we need to match the devices that use keys containing MODALIAS for the Plugin key to be set.
=> Save the ONLY_QUIRK instance IDs to fix incorporation of i2c

libfwupdplugin/fu-udev-device.c, libfwupdplugin/fu-udev-device.h, libfwupdplugin/fu-usb-device.c, libfwupdplugin/fwupdplugin.map
=> Add a helper to get a GUsbDevice from a FuUdevDevice

docs/env.md, libfwupdplugin/fu-ihex-firmware.c
=> trivial: Be less verbose when parsing IHEX files

plugins/flashrom/fu-flashrom-device.c
=> flashrom: Only use the IFD when the system is Intel-based

src/fu-engine.c
The new xz metadata does not include the non-standard checksum target tags, and instead uses the standardized artifact checksum.
Support both metadata formats when setting the remote ID used for reports.
=> Correctly set the remote-id when using new-style xz-metadata

src/fu-history.c
=> Save the new release metadata when using fu_history_modify_device()

plugins/fpc/fu-fpc-device.c
=> fpc: Remove some dead code

plugins/analogix/fu-analogix-device.c
=> analogix: Fix potential division by zero when writing

contrib/upload-smc-license.py, docs/index.html, docs/supermicro-license.md
As requested in #4836. I'm not sure what else to put there.
=> docs: explain the smc bmc license issue

src/fu-engine-helper.c
=> Add more EFI keys to the integrity check list

plugins/intel-gsc/README.md
Intel Arc products do not require the host CSME to update Arc firmware. Firmware updates will work on both AMD and Intel platforms. Arc products have their own Graphics Security Control for firmware updates and leverage existing Intel technology like the MEI interface protocol to implement the firmware update flow.
Signed-off-by: Vitaly Lubart <vitaly.lubart@intel.com>
=> igsc: Fix README.md

data/remotes.d/meson.build
=> trivial: Fix lvfs-testing remote file

.gitignore, plugins/synaptics-mst/fu-self-test.c, plugins/synaptics-mst/tests/dmi, src/tests/dmi
=> trivial: Fix the tests on s390x

plugins/intel-usb4/fu-intel-usb4-device.c
=> intel-usb4: Ensure the device name is set with FuUsbDevice->setup

libfwupd/fwupd-release-private.h, libfwupd/fwupd-release.c, libfwupd/fwupd-self-test.c, libfwupd/fwupd.map
=> Add fwupd_release_incorporate() for future usage

src/fu-engine.c
=> Incorporate the device when merging in properties for GetDetails

src/fu-engine.c, src/fu-util-common.c
=> Add the X-Gpu category for new hardware support

libfwupd/fwupd-common.c, libfwupd/fwupd-common.h, libfwupd/fwupd.map, src/fu-engine.c
=> Load report data from /etc/lsb-release

docs/hsi-tests.d/org.fwupd.hsi.Iommu.json
=> Don't suggest iommu=pt to people (Fixes: #5304)

libfwupdplugin/fu-device.c
=> Return a more useful error if USB recovery() failed

libfwupdplugin/fu-self-test.c, libfwupdplugin/fu-version-common.c, libfwupdplugin/fu-version-common.h, libfwupdplugin/fwupdplugin.map
=> Add fu_version_from_uint24() for future usage

libfwupdplugin/fu-progress.c, libfwupdplugin/fu-progress.h
We're not going to subclass this, and making it final saves during startup:
* 300K calls of fu_progress_get_instance_private()
* 280K calls of fu_progress_get_step_weighting()
=> Convert FuProgress to a FINAL object

src/fu-tool.c, src/fwupdtool.1
=> Do not filter in fwupdtool for ->attach() if specifying --force

src/fu-engine.c
This means we do 15% less i/o at startup, which means we start a lot faster.
=> Only write devices.json once at startup, rather than for each device add

plugins/nvme/nvme.quirk
=> Add needs-shutdown flag for Solidigm NVMe device

src/fu-engine.c
This speeds up startup by ~9% on a machine with lots of devices attached.
=> Use the indexed query when getting releases for devices

src/fu-tool.c
=> trivial: Fix warning when running fwupdtool --version

libfwupdplugin/fu-byte-array.c, libfwupdplugin/fu-byte-array.h, libfwupdplugin/fu-self-test.c, libfwupdplugin/fwupdplugin.map
=> trivial: Add convenience API for future use

src/fu-engine.c
For example:
<requires>
<firmware depth="1">39cd2d79-f119-5e2b-ba57-0b101df5bebc|33c68fc5-fd3d-5cc8-951b-319368dfd6e8</firmware>
</requires>
=> Allow specifying OR parent requirements

src/fu-engine.c, src/fu-util-common.c
=> Add X-Dock and X-UsbDock update categories

data/bash-completion/fwupdtool, src/fu-tool.c
=> Add a 'get-report-metadata' command to allow debugging metadata collection

src/fu-engine.c
This regressed in 000e986dc8cd0c7e49bdb5d177dcfc91749351aa but we did not notice because devices with only one GUID (e.g. ESRT devices) still worked as before. Fix the error handling to only abort if none of the GUIDs are found.
=> Fix the regression to find all device GUID

libfwupdplugin/fu-volume.c, plugins/uefi-dbx/fu-uefi-dbx-common.c
I think this is only possible when a raw partition with no filesystem has the ESP or BDP UEFI GUID set in the partition table.
=> uefi-dbx: Ignore failure to mount the ESP if unsupported

plugins/tpm/fu-tpm-eventlog-common.c, plugins/tpm/fu-tpm-eventlog-common.h, plugins/tpm/fu-tpm-eventlog-parser.c, plugins/tpm/fu-tpm-plugin.c
=> tpm: Add support for sha384

plugins/tpm/fu-tpm-plugin.c
=> tpm: don't require event log to have all reconstructions

src/fu-engine.c
=> trivial: Do not emit DeviceChanged before DeviceAdded

libfwupd/fwupd-request.h, src/fu-util-common.c
=> Add a request ID for re-inserting the USB cable

libfwupdplugin/fu-bluez-device.c, libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, libfwupdplugin/fu-usb-device.c, libfwupdplugin/fwupdplugin.map, plugins/bcm57xx/fu-bcm57xx-device.c, plugins/bcm57xx/fu-bcm57xx-recovery-device.c, plugins/ccgx/fu-ccgx-dmc-device.c, plugins/cfu/fu-cfu-module.c, plugins/elantp/fu-elantp-hid-device.c, plugins/elantp/fu-elantp-i2c-device.c, plugins/focalfp/fu-focalfp-hid-device.c, plugins/fpc/fu-fpc-device.c, plugins/logitech-scribe/fu-logitech-scribe-device.c, plugins/msr/fu-msr-plugin.c, plugins/steelseries/fu-steelseries-fizz-tunnel.c, plugins/steelseries/fu-steelseries-gamepad.c, plugins/synaptics-cape/fu-synaptics-cape-device.c, plugins/tpm/fu-tpm-v2-device.c, plugins/uefi-capsule/fu-uefi-device.c, plugins/vli/fu-vli-pd-device.c, plugins/vli/fu-vli-usbhub-pd-device.c, plugins/wacom-raw/fu-wacom-emr-device.c, plugins/wacom-usb/fu-wac-device.c, plugins/wistron-dock/fu-wistron-dock-device.c
=> trivial: Add new convenience API to make plugins simpler

libfwupdplugin/fu-cabinet.c, src/fu-engine.c
=> Never allow using SHA-1 for checksum validation

plugins/linux-swap/meson.build, plugins/logitech-hidpp/meson.build, plugins/mtd/fu-self-test.c, plugins/mtd/meson.build, plugins/mtd/tests/dmi, plugins/nitrokey/meson.build, plugins/vli/meson.build
=> mtd: Use dummy SMBIOS data to fix self test on s390x

plugins/linux-swap/fu-self-test.c, plugins/redfish/fu-redfish-network.c
=> trivial: skip self tests that fail with G_IO_ERROR_NOT_DIRECTORY

plugins/synaptics-rmi/fu-synaptics-rmi-hid-device.c
=> synaptics-rmi: add support to USBHID devices

plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c, plugins/synaptics-rmi/fu-synaptics-rmi-v7-device.c
=> synaptics-rmi: add support to more firmware partitions

libfwupdplugin/fu-uswid-firmware.c
=> Always search for uSWID data in the image

plugins/dfu/README.md
=> dfu: Add some wisdom for vendors implementing devices

plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c, plugins/synaptics-rmi/fu-synaptics-rmi-v7-device.c
When the firmware partition contains signature, firmware would require an additional step to write signature.
=> synaptics-rmi: add support to write signature

docs/hsi-tests.d/org.fwupd.hsi.Amd.PlatformRollbackProtection.json
=> trivial: clarify documentation on PSP security processor (Fixes: #5394)

contrib/ci/check-abi, contrib/ci/fwupd_setup_helpers.py
=> Make CI failures from HTTP issues easier to follow

plugins/vbe/fu-vbe-device.c, plugins/vbe/fu-vbe-device.h, plugins/vbe/fu-vbe-plugin.c
This can be easily retrieved using LOCALSTATEDIR_PKG by the subclass.
=> vbe: Remove the stored VBE dir

meson.build
=> Fix installing with -Doffline=false

contrib/fwupd.spec.in, libfwupdplugin/meson.build
=> trivial: install dmi data into installed-tests

libfwupdplugin/fu-context-private.h, libfwupdplugin/fu-context.c, libfwupdplugin/fu-context.h, libfwupdplugin/fwupdplugin.h, libfwupdplugin/fwupdplugin.map, plugins/dell/fu-dell-plugin.c, plugins/lenovo-thinklmi/fu-self-test.c, plugins/mtd/fu-self-test.c, plugins/synaptics-mst/fu-self-test.c, plugins/uefi-capsule/fu-uefi-tool.c, src/fu-engine.c
=> trivial: Add FuContextHwidFlags for future usage

plugins/synaptics-rmi/fu-synaptics-rmi-device.h, plugins/synaptics-rmi/fu-synaptics-rmi-hid-device.c, plugins/synaptics-rmi/fu-synaptics-rmi-v7-device.c, plugins/synaptics-rmi/fu-synaptics-rmi-v7-device.h
This is for some secure-enabled devices that have no NIST function.
The 2nd commit is to modify the step to handle the partition in the new bootloader version, this partition needs to be erased separately and updated before erase_all command.
=> synaptics-rmi: add feature to verify signature

docs/hsi-tests.d/org.fwupd.hsi.SupportedCpu.json
This should hopefully help disambiguate when information isn't available what to do.
Fixes: #5415
=> trivial: update supported cpu documentation to add more info for AMD

libfwupdplugin/fu-plugin.c, plugins/redfish/meson.build
Also, don't attempt to change the permissions if the correct one is already set.
=> trivial: Make the installed-tests redfish.conf secure to avoid a warning

libfwupdplugin/fu-fdt-firmware.c
Newer versions of dtc agressively pack the string table, using *any* matching suffix rather than whole strings. This is specification compliant, but breaks if you use the offset as a hash key as a [premature] optimization.
Just use the string table as a flat block of memory rather than pre-parsing it.
This fixes reading the system FDT on new OpenBMC builds.
=> Improve FDT parsing compatibility

libfwupdplugin/fu-hwids-fdt.c
=> Parse the DT chassis-type when parsing the FDT

plugins/wacom-usb/fu-wac-module-bluetooth-id6.c, plugins/wacom-usb/fu-wac-module-bluetooth.c, plugins/wacom-usb/fu-wac-module-scaler.c, plugins/wacom-usb/fu-wac-module-touch.c
Make it easier to locate errors that occur when writing to the device.
=> wacom-usb: prefix errors that occur when writing to the device

libfwupdplugin/fu-context.c, libfwupdplugin/fu-context.h, libfwupdplugin/fwupdplugin.map
=> Add fu_context_remove_flag() for future use

src/fu-engine.c
This makes it possible to 'undo' the notification, for example.
=> Support unsetting specific device flags

libfwupd/fwupd-enums.c, libfwupd/fwupd-enums.h, libfwupdplugin/fu-usb-device.c, src/fu-util-common.c
=> trivial: Add a device flag specifying it is emulated

libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, libfwupdplugin/fu-self-test.c, libfwupdplugin/fu-usb-device.c, libfwupdplugin/fwupdplugin.map
=> Add fu_device_remove_backend_tag() for future use

src/fu-self-test.c, src/fu-usb-backend.c, src/tests/usb-devices-bootloader.json, src/tests/usb-devices-replace.json
=> Fix hotplug events when emulating devices

contrib/ci/dependencies.xml
This is so that it can be used by subproject fwupd-efi
=> Add python3-pefile/python-pefile to CI build deps

libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, libfwupdplugin/fwupdplugin.map, src/fu-device-list.c
=> trivial: Add fu_device_has_problem() to be consistent and hide details

src/fu-engine.c
=> Do not return emulated devices from GetHistory

libfwupdplugin/fu-archive.c
=> trivial: Correctly compress zip files in FuArchive

libfwupdplugin/fu-device.c
=> Propagate device tag to parent device

src/fu-util.c
=> trivial: Do not hardcode fwupdmgr as a binary name

src/fu-history.c, src/fu-self-test.c
=> Return an error when the pending db could not be updated

plugins/nvme/README.md, plugins/nvme/fu-nvme-device.c, plugins/nvme/nvme.quirk
=> nvme: Detect and warn users with the broken firmware 3B2QGXA7

contrib/ci/Dockerfile-fedora.in
=> Move the Fedora CI job to F37

data/bash-completion/fwupdmgr, data/fish-completion/fwupdmgr.fish, data/installed-tests/fwupdmgr-p2p.sh, libfwupd/fwupd-client-sync.c, libfwupd/fwupd-client-sync.h, libfwupd/fwupd-client.c, libfwupd/fwupd-client.h, libfwupd/fwupd.map, plugins/linux-swap/fu-self-test.c, src/fu-util.c
=> trivial: Fix Fedora CI when it cannot autostart udisks

plugins/ccgx/README.md, plugins/ccgx/ccgx.quirk, plugins/ccgx/fu-ccgx-dmc-common.c, plugins/ccgx/fu-ccgx-dmc-common.h, plugins/ccgx/fu-ccgx-dmc-device.c, plugins/ccgx/fu-ccgx-dmc-devx-device.c, plugins/ccgx/fu-ccgx-dmc-devx-device.h, plugins/ccgx/meson.build
=> ccgx: Add some more plugin debugging

libfwupdplugin/fu-device.c
=> trivial: Ignore device requests when emulated

plugins/gpio/gpio.quirk, plugins/thunderbolt/fu-thunderbolt-controller.c
=> Adjust family view for a few devices 

src/fu-engine.c
If we're doing multiple updates in a composite device then we don't need to update the MOTD in between each sub-component update. Similarly, if we're emulating lots of devices.
This speeds up emulating all the devices by two orders of magnitude.
=> Update the MOTD after 5s idle

plugins/ccgx/README.md
=> trivial: Add some additional docs about CCGX factory mode

libfwupd/fwupd-device.c, libfwupd/fwupd-device.h, libfwupd/fwupd-enums-private.h, libfwupd/fwupd.map, libfwupdplugin/fu-device-progress.c, libfwupdplugin/fu-device-progress.h, libfwupdplugin/fu-device.h, libfwupdplugin/fu-self-test.c, libfwupdplugin/fwupdplugin.map, libfwupdplugin/meson.build, src/fu-engine.c
Fixes part of https://github.com/fwupd/fwupd/issues/5522
=> Set the device percentage and status for the duration

contrib/ci/fedora.sh, meson.build
=> Fix -Dbuild=library target

plugins/uefi-capsule/fu-uefi-capsule-plugin.c, plugins/uefi-capsule/fu-uefi-common.h, plugins/uefi-capsule/fu-uefi-device.c, plugins/uefi-capsule/fu-uefi-device.h
See https://github.com/fwupd/firmware-lenovo/issues/257
=> uefi-capsule: Require at least 80MB free in the ESP

src/fu-util.c
=> Offer to enable emulation if disabled

plugins/uefi-capsule/fu-uefi-bootmgr.c, plugins/uefi-capsule/fu-uefi-capsule-plugin.c, plugins/uefi-capsule/fu-uefi-common.c, plugins/uefi-capsule/fu-uefi-common.h, plugins/uefi-capsule/fu-uefi-device.c, plugins/uefi-capsule/fu-uefi-device.h, plugins/uefi-capsule/fu-uefi-grub-device.c, plugins/uefi-capsule/uefi_capsule.conf, snap/snapcraft.yaml
=> Install and use shim in the confined snap

src/fu-engine.c
=> Use a heuristic to set ignore-system-power for all Lenovo batteries

plugins/uefi-capsule/fu-uefi-bootmgr.c
=> trivial: fix overwriting errors for existence of shim

libfwupdplugin/fu-acpi-table.c, libfwupdplugin/fu-acpi-table.h, libfwupdplugin/fwupdplugin.h, libfwupdplugin/fwupdplugin.map, libfwupdplugin/meson.build, plugins/acpi-dmar/fu-acpi-dmar.c, plugins/acpi-dmar/fu-acpi-dmar.h, plugins/acpi-ivrs/fu-acpi-ivrs.c, plugins/acpi-ivrs/fu-acpi-ivrs.h, src/fu-engine.c
=> Add a generic ACPI table parser

src/fu-engine.c
Fixes some of https://github.com/fwupd/fwupd/issues/5553
=> Only accept application/x-xz compression for the metadata payload

.github/workflows/snap-candidate.yml, snap/snapcraft.yaml
=> Some snap packaging improvements

src/fu-engine.c
=> trivial: Add a compile version for libxmlb

libfwupd/fwupd-client.c, libfwupdplugin/fu-archive.c, libfwupdplugin/fu-context.c, libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, libfwupdplugin/fu-quirks.c, libfwupdplugin/fu-quirks.h, libfwupdplugin/fu-string.c, libfwupdplugin/fu-string.h, src/fu-spawn.c, src/fu-spawn.h
=> trivial: Add the closure user_data to the introspection

src/fu-tool.c, src/fu-util.c
This means you can print the one thing you care about.
=> Allow filtering the output of get-devices by the device ID

plugins/uefi-capsule/README.md
I'm answering this question a lot, so add some UEFI-specific notes.
=> uefi-capsule: Add some wisdom on version formats

docs/fwupdplugin.toml.in, docs/only-trusted.md
=> trivial: Add some wisdom about self-signing updates for testing

libfwupd/fwupd-client.c
This fixes a regression introduced in https://github.com/fwupd/fwupd/pull/5528 where we added a critical warning if setting the package user agent before we retrieved the fwupd daemon version.
If we rebuild the user agent whenever we get new information it does not matter in which order these are set.
=> Allow setting the package user agent before the client has connected

src/fu-engine.c
Fixes https://github.com/fwupd/firmware-dell/issues/158
=> Fix a critical warning when parsing invalid metadata

AUTHORS, contrib/fwupd.spec.in
=> trivial: Remove the AUTHORS file, it's not remotely correct

plugins/powerd/fu-powerd-plugin.c
Fixes https://github.com/fwupd/fwupd/issues/3386, harder.
=> powerd: Use the ExternalPowerType information to better set AC levels

src/fu-daemon.c, src/fu-engine-helper.c, src/fu-engine-request.c, src/fu-engine-request.h, src/fu-engine.c, src/fu-release.c, src/fu-self-test.c, src/fu-tool.c
This makes it a lot easier to explain what we're asking the engine to do.
=> trivial: Turn FuEngineRequestKind into a bitfield

src/fu-engine.c
=> trivial: Reduce the verbosity when saving device state

contrib/pcap2emulation.py, docs/device-emulation.md
=> Add pcap file converter

contrib/fwupd.spec.in
=> trivial: Mark the /etc/grub.d/35_fwupd as a config file

libfwupdplugin/fu-byte-array.c, libfwupdplugin/fu-byte-array.h, libfwupdplugin/fwupdplugin.map
=> trivial: Add fu_byte_array_append_uint24() for future use

plugins/mtd/mtd.quirk
Fixes https://github.com/fwupd/fwupd/issues/5632
=> mtd: Fix the name of the Intel SPI controller

plugins/tpm/README.md, plugins/tpm/fu-self-test.c, plugins/tpm/fu-tpm-v2-device.c
=> tpm: Mark the device as updatable if it supports Field Upgrade

plugins/thunderbolt/fu-self-test.c
=> trivial: Fix a tiny memory leak in the thunderbolt self tests

README.md, docs/best-known-configuration.md, docs/fwupdplugin.toml.in
Fixes some of https://github.com/fwupd/fwupd/discussions/5641
=> Add some more docs on Best Known Configuration

src/fu-util.c
=> trivial: Fix 'fwupdmgr install FILE GUID'

README.md
=> Fix the continuous integration status in the README

plugins/synaptics-rmi/fu-synaptics-rmi-device.c, plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c, plugins/synaptics-rmi/fu-synaptics-rmi-v7-device.c, plugins/synaptics-rmi/fu-synaptics-rmi.struct, plugins/synaptics-rmi/meson.build
=> synaptics-rmi: Port to FuStruct for readability reasons

libfwupdplugin/fu-efi-firmware-section.c, libfwupdplugin/fu-efi.struct
=> trivial: Port EfiSection to FuStruct

.github/workflows/pull-request-reviews.yml
This will get us a newer clang-format
=> trivial: Use Ubuntu 22.04 for running pre-commit

plugins/steelseries/steelseries.quirk
=> steelseries: Fix the CounterpartGuid for the Aerox 3 Wireless Mouse

.pre-commit-config.yaml, CONTRIBUTING.md, contrib/ci/check-source.py, src/fu-polkit-agent.c
=> trivial: Add some guidance on what debug levels to use

plugins/nvme/README.md, plugins/nvme/fu-nvme-device.c, plugins/nvme/fu-nvme-plugin.c, plugins/nvme/nvme.quirk
=> nvme: Add support for CA3 activation

contrib/pcap2emulation.py
=> contrib/pcap2emulation: Fix 'usb_port' referenced before assignment

data/fish-completion/fwupdmgr.fish, src/fu-tool.c, src/fu-util.c
Documentation
Add trivial description for fwupd tool
=> trivial: Add description for help

libfwupdplugin/fu-dump.c
Fixes https://github.com/fwupd/fwupd/issues/5698
=> Reduce the DFU flashing speed by 100s when using huge firmware files

plugins/dell-dock/dell-dock.quirk, plugins/dell-dock/fu-dell-dock-plugin.c
(cherry-picked from dc8e247c47308b6da51e19c5b4b272a748d12ced)
=> dell-dock: trigger passive flow for usb4 from intel-usb4 plugin

libfwupd/fwupd-enums.c, libfwupd/fwupd-enums.h, libfwupd/fwupd-self-test.c, libfwupdplugin/fu-device.c, src/fu-util-common.c
=> Add a device problem for when the device is in use

data/fish-completion/fwupdmgr.fish
=> Add fish shell completion for get-plugins subcommand

plugins/pci-psp/fu-pci-psp-device.c
Store both to the "Secure Processor" device.
This is dependent upon [this kernel series.](https://lore.kernel.org/linux-crypto/20230420163140.14940-1-mario.limonciello@amd.com/T/#m38ab23d70d213ceb67440168b3f71ad2be3aa564
)
=> pci-psp: Read the AGESA Bootloader and TEE versions from the kernel

libfwupdplugin/fu-cfu-offer.c, libfwupdplugin/fu-cfu-payload.c, libfwupdplugin/fu-cfu.struct, plugins/cfu/README.md, plugins/cfu/fu-cfu-device.c, plugins/cfu/fu-cfu-module.c, plugins/cfu/fu-cfu-plugin.c, plugins/cfu/fu-cfu.struct, plugins/cfu/meson.build
Also, add and use more FuStruct helpers when writing firmware.
=> cfu: Implement enough of the specification to be able to update a device

src/fwupdmgr.md
Suggestions from John Westerdale, many thanks.
=> Add some extra contents to the manpage

docs/tutorial.md, libfwupdplugin/rustgen.py
We can't very well ask plugin authors to use it if the docs are in my head.
=> trivial: Document how to use rustgen

contrib/pcap2emulation.py
Enhance `pcap2emulation.py` script with USB CCID support.
=> contrib/pcap2emulation: Add CCID decoding support

libfwupdplugin/fu-config.c
If the user edits the daemon.conf manually (e.g. changing OnlyTrusted) then the package manager will not remove the file, and we use the built-in daemon migration code.
In this case we also write out the old default values which isn't the idea of the fwupd.conf file now we have the manpage. In the worst case we can have `ArchiveSizeMax=0` which breaks loading archives from vendor directories.
=> Do not migrate default values from daemon.conf to fwupd.conf

plugins/logitech-scribe/fu-logitech-scribe-device.c
Plugin failed when multiple Video devices are connected. e.g.: 
root@vc:~# v4l2-ctl --list-devices
Logitech Tap HDMI Capture (usb-0000:00:14.0-1.2):
/dev/video0
/dev/video1
/dev/media0
Logitech Scribe (usb-0000:00:14.0-7):
/dev/video2
/dev/video3
/dev/media1
Added filters to pick correct Scribe Video device
=> Support multiple video devices

src/fu-release.c
Fixes future bugs like https://github.com/fwupd/fwupd/issues/5781
=> trivial: Ignore unknown report metadata items with no key or value

libfwupd/fwupd-device.c
This allows us to watch for changes without polling.
=> Add a GObject property for FwupdDevice:version

src/fu-remote-list.c, src/fu-tool.c
=> Delete the obsolete .gz files if the remote is now using .xz

libfwupdplugin/fu-efi-signature-list.c
=> Add the latest dbx fixups for BlackLotus

libfwupdplugin/fu-device.c
This is needed for future functionality.
=> trivial: Add GObject properties for FuDevice private and internal flags

libfwupdplugin/fu-config.c
Fixes https://github.com/fwupd/fwupd/issues/5817
=> Ignore the immutable flatpak fwupd.conf file permissions

plugins/intel-gsc/igsc.quirk
=> intel-gsc: update official Intel product names

plugins/thunderbolt/thunderbolt.quirk
Change-Id: I51cbfbe7df4e5e737742f254baf13fd27b03f9ee
=> thunderbolt: disable retimer offline mode for rex

plugins/fpc/fu-fpc-device.c, plugins/fpc/fu-fpc.rs, plugins/fpc/meson.build
=> fpc: Convert to rustgen

plugins/usi-dock/README.md, plugins/usi-dock/fu-usi-dock-common.h, plugins/usi-dock/fu-usi-dock-dmc-device.c, plugins/usi-dock/fu-usi-dock-mcu-device.c, plugins/usi-dock/fu-usi-dock.rs
=> usi-dock: Use rustgen in more ways

plugins/aver-hid/README.md, plugins/aver-hid/aver-hid.quirk, plugins/aver-hid/fu-aver-hid-device.c, plugins/aver-hid/fu-aver-hid-device.h, plugins/aver-hid/fu-aver-hid-firmware.c, plugins/aver-hid/fu-aver-hid-firmware.h, plugins/aver-hid/fu-aver-hid-plugin.c, plugins/aver-hid/fu-aver-hid-plugin.h, plugins/aver-hid/fu-aver-hid.rs, plugins/aver-hid/meson.build, plugins/aver-hid/test/firmware.metainfo.xml, plugins/meson.build
=> merge Wip/hughsie/aver-hid

libfwupdplugin/fu-udev-device.c, plugins/logind/fu-logind-plugin.c
The open() call says than any valid result is 'a nonnegative integer'.
See also https://github.com/fwupd/fwupd/discussions/5841
=> Do not assume a file descriptor of zero is invalid

plugins/intel-gsc/fu-igsc-device.c, plugins/intel-gsc/fu-igsc.rs
=> intel-gsc: Define one more struct for rustgen

libfwupdplugin/fu-efi-firmware-filesystem.c
When fuzzing a 700KB FuEfiFirmwareFilesystem object we used 12MB of RSS when printing the XML -- which isn't insane, but is too much for oss-fuzz.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59249
=> Limit the number of file objects in the EFI filesystem

src/fu-engine.c
We fixed the client-side issue in f7c69d794b399fe962964bc4da20fba44dd572bc but we need to relax the daemon check too.
Fixes https://github.com/fwupd/fwupd/issues/4281
=> Show devices with problems in fwupdmgr get-upgrades

plugins/aver-hid/fu-aver-hid-device.c
=> aver-hid : there is no need to decompress twice

src/fu-console.c, src/fu-console.h, src/fu-tool.c, src/fu-util.c
In an update of 15 minutes, it's very easy to miss the immediate action required.
=> Beep the console when waiting for user input

plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
Suppress warning logs when a given hidraw instance does not handle configuration channel requests. A device may not support configuration channel at all (no configuration channel HID feature report). The configuration channel requests are handled only by the first HID instance on device (other instances reject the configuration channel operations).
=> plugins: nordic-hid: Suppress warning logs on device setup

plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
Change fixes issue with discovery of peripherals connected via dongle. Lack of configuration channel DFU support for one of the peripherals should not affect other peripherals and dongle.
Fixes: https://github.com/fwupd/fwupd/issues/5782
=> plugins: nordic-hid: Fix discovery of peripherals connected via dongle

libfwupdplugin/fu-efivar-linux.c, plugins/uefi-dbx/fu-uefi-dbx-device.c
Fixes: https://github.com/fwupd/fwupd/issues/5830
=> uefi-dbx: Record the EFI filesystem used in metadata reports

generate-build/generate-dbus-interface.py
Fixes https://github.com/fwupd/fwupd/issues/5898
=> Do not accidentally depend on python 3.9

libfwupdplugin/fu-volume.c, libfwupdplugin/fu-volume.h, plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2214191
=> Ignore small ESP block devices if there are multiple choices

plugins/ccgx-dmc/ccgx-dmc.quirk
Fixes https://github.com/fwupd/fwupd/issues/5829
=> Add support for the Belkin Thunderbolt 4 Core Hub dock

docs/tutorial.md, libfwupdplugin/fu-rustgen-struct.c.in, libfwupdplugin/fu-rustgen-struct.h.in, libfwupdplugin/fu-self-test.c, libfwupdplugin/fu-self-test.rs, libfwupdplugin/rustgen.py
=> Add support for nested structures in rustgen

libfwupdplugin/fu-self-test.c, libfwupdplugin/fu-string.c, libfwupdplugin/fu-string.h, plugins/acpi-phat/fu-acpi-phat-health-record.c, plugins/uefi-capsule/fu-uefi-capsule-plugin.c, plugins/uefi-capsule/fu-uefi-cod-device.c, plugins/uefi-capsule/fu-uefi-device.c, plugins/uefi-capsule/fu-uefi-tool.c, plugins/uefi-capsule/fu-uefi-update-info.c
This is something that's not trivial to do correctly and that we do quite a bit in EFI code -- and we're about to do even more.
=> Add utilities to convert to and from a UTF-16 byte array

libfwupdplugin/fu-firmware.c, libfwupdplugin/fu-firmware.h, libfwupdplugin/fu-self-test.c
=> Add fu_firmware_get_image_by_gtype() for future use

plugins/jabra-gnp/fu-jabra-gnp-device.c
With these changes fwupd is able to report the name of jabra-gnp devices, instead of displaying "(null)" or "Unknown device"
=> added device name read for jabra-gnp devices

src/fu-tool.c
Reset progress to ensure that it can be reused in `fu_util_install`.
Fixes: https://github.com/fwupd/fwupd/issues/5913
=> fu-tool: Improve progress handling in fu_util_install_release

RELEASE, SECURITY.md
=> trivial: Update SECURITY.md to reflect reality

data/bash-completion/fwupdtool, libfwupdplugin/fu-efivar-windows.c, src/fu-tool.c
=> Support reading and writing EFI variables on Windows

libfwupdplugin/fu-archive-firmware.c, libfwupdplugin/fu-dfuse-firmware.c, libfwupdplugin/fu-efi-device-path-list.c, libfwupdplugin/fu-efi-firmware-common.c, libfwupdplugin/fu-efi-firmware-filesystem.c, libfwupdplugin/fu-efi-signature-list.c, libfwupdplugin/fu-fdt-firmware.c, libfwupdplugin/fu-fdt-image.c, libfwupdplugin/fu-firmware.c, libfwupdplugin/fu-firmware.h, libfwupdplugin/fu-fit-firmware.c, libfwupdplugin/fu-fmap-firmware.c, libfwupdplugin/fu-ifd-bios.c, libfwupdplugin/fu-ifwi-cpd-firmware.c, libfwupdplugin/fu-ifwi-fpt-firmware.c, libfwupdplugin/fu-ihex-firmware.c, libfwupdplugin/fu-intel-thunderbolt-nvm.c, libfwupdplugin/fu-linear-firmware.c, libfwupdplugin/fu-pefile-firmware.c, libfwupdplugin/fu-self-test.c, libfwupdplugin/fu-uswid-firmware.c, plugins/acpi-phat/fu-acpi-phat-version-record.c, plugins/elanfp/fu-elanfp-firmware.c, plugins/goodix-tp/fu-goodixtp-brlb-firmware.c, plugins/goodix-tp/fu-goodixtp-gtx8-firmware.c, plugins/jabra-gnp/fu-jabra-gnp-firmware.c, plugins/nordic-hid/fu-nordic-hid-archive.c, plugins/synaptics-prometheus/fu-synaprom-firmware.c, plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c, plugins/wacom-usb/fu-wac-firmware.c
This is something we have to do quite a bit, so centralize.
=> Allow setting the maximum number of firmware child images

plugins/wacom-usb/fu-wac-module-bluetooth.c
=> wacom-usb: Fix a emulation failure on s390x

plugins/ccgx-dmc/ccgx-dmc.quirk
=> ccgx-dmx: Add CE-LINK TB4-Dock01

plugins/uefi-capsule/README.md, plugins/uefi-capsule/fu-acpi-uefi.c, plugins/uefi-capsule/fu-acpi-uefi.h, plugins/uefi-capsule/fu-uefi-capsule-plugin.c, plugins/uefi-capsule/fu-uefi-cod-device.c, plugins/uefi-capsule/fu-uefi-device.c, plugins/uefi-capsule/fu-uefi-device.h
=> uefi-capsule: Use a CapsuleOnDisk filename supported by InsydeH2O

plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
Change allows discovering devices without support for DFU over config channel. This allows to update firmware of peripheral devices connected via dongle that does not support DFU over config channel.
The physical ID no longer uses bootloader name to support devices that do not support DFU.
=> plugins: nordic-hid: Allow discovering devices without DFU support

libfwupdplugin/rustgen.py
This makes the logic much easier to understand, moving the specific rules into the correct item or obj classes. It also makes recursive structs work too.
=> More carefully manage rustgen exports

libfwupdplugin/fu-elf-firmware.c, libfwupdplugin/fu-elf-firmware.h, libfwupdplugin/fu-elf.rs, libfwupdplugin/fwupdplugin.h, libfwupdplugin/meson.build, src/fu-engine.c
This only parses 64-bit little endian ELF binaries.
=> Add a simple ELF parser

libfwupdplugin/fu-chunk.c, libfwupdplugin/fu-firmware.c, libfwupdplugin/fu-mem.c, libfwupdplugin/fu-mem.h, libfwupdplugin/fu-rustgen-struct.c.in, plugins/genesys/fu-genesys-scaler-device.c, plugins/goodix-tp/fu-goodixtp-brlb-device.c, plugins/goodix-tp/fu-goodixtp-gtx8-device.c, plugins/jabra-gnp/fu-jabra-gnp-device.c, plugins/nordic-hid/fu-nordic-hid-cfg-channel.c, plugins/redfish/fu-ipmi-device.c, plugins/steelseries/fu-steelseries-fizz-hid.c, plugins/steelseries/fu-steelseries-fizz.c, plugins/ti-tps6598x/fu-ti-tps6598x-device.c, plugins/wistron-dock/fu-wistron-dock-device.c
=> Add fu_memstrsafe() as a slightly safer fu_strsafe()

contrib/ci/oss-fuzz.py, libfwupdplugin/fu-csv-entry.c, libfwupdplugin/fu-csv-entry.h, libfwupdplugin/fu-csv-firmware-private.h, libfwupdplugin/fu-csv-firmware.c, libfwupdplugin/fu-csv-firmware.h, libfwupdplugin/fu-firmware.c, libfwupdplugin/fu-pefile-firmware.c, libfwupdplugin/fu-self-test.c, libfwupdplugin/fwupdplugin.h, libfwupdplugin/meson.build, libfwupdplugin/tests/csv.bin, libfwupdplugin/tests/csv.builder.xml, src/fu-engine.c
This is going to be useful for .sbat section parsing.
=> Add a CSV firmware parser

contrib/fwupd.spec.in, data/motd/fwupd-refresh.service.md, data/motd/meson.build, generate-build/generate-man.py
Fixes https://github.com/fwupd/fwupd/issues/815
=> trivial: Add fwupd-refresh.service.8

libfwupd/fwupd-enums-private.h, libfwupd/fwupd-security-attr.c, libfwupd/fwupd-security-attr.h, libfwupd/fwupd.map, plugins/acpi-dmar/fu-acpi-dmar-plugin.c, plugins/acpi-facp/fu-acpi-facp-plugin.c, plugins/acpi-ivrs/fu-acpi-ivrs-plugin.c, plugins/bios/fu-bios-plugin.c, plugins/cpu/fu-cpu-device.c, plugins/dell/fu-dell-plugin.c, plugins/intel-me/fu-intel-me-mca-device.c, plugins/intel-spi/fu-intel-spi-device.c, plugins/iommu/fu-iommu-plugin.c, plugins/lenovo-thinklmi/fu-lenovo-thinklmi-plugin.c, plugins/linux-lockdown/fu-linux-lockdown-plugin.c, plugins/linux-sleep/fu-linux-sleep-plugin.c, plugins/linux-swap/fu-linux-swap-plugin.c, plugins/linux-tainted/fu-linux-tainted-plugin.c, plugins/msr/fu-msr-plugin.c, plugins/pci-bcr/fu-pci-bcr-plugin.c, plugins/pci-mei/fu-pci-mei-plugin.c, plugins/pci-psp/fu-pci-psp-device.c, plugins/tpm/fu-tpm-plugin.c, plugins/uefi-capsule/fu-uefi-capsule-plugin.c, plugins/uefi-pk/fu-uefi-pk-device.c, src/fu-engine.c
This means the GUI can be much nicer, and allows us to more easily fix some in the future.
=> Add the expected result to each HSI test

libfwupd/fwupd-common.h, libfwupd/meson.build, libfwupdplugin/fu-efi-signature.c, libfwupdplugin/fu-efi-signature.h, libfwupdplugin/fu-efi.rs, libfwupdplugin/fu-ifd-common.c, libfwupdplugin/fu-ifd-common.h, libfwupdplugin/fu-ifd.rs, libfwupdplugin/fu-ifwi-fpt-firmware.c, libfwupdplugin/fu-rustgen-struct.c.in, libfwupdplugin/meson.build
=> trivial: Include fwupd_guid_t in the libfwupd introspection

contrib/cfu-inf-to-quirk.py, plugins/cfu/README.md
=> cfu: Provide a script to convert .inf entries to a .quirk block

data/device-tests/fpc-lenfy-moh.json
=> trivial: Add a device test for FPC Lenfy MoH

libfwupdplugin/fu-cfu-offer.c
=> trivial: Parse the CFU firwmare as surface verfmt

libfwupdplugin/fu-hid-device.c, libfwupdplugin/fu-hid-device.h
=> trivial: Add getters and setters for the HID EPs

plugins/cfu/cfu.quirk, plugins/cfu/fu-cfu-device.c, plugins/cfu/fu-cfu-module.c, plugins/cfu/fu-cfu.rs
This involved implementing more of the CFU protocol.
=> cfu: Add support for the Microsoft USB-C Travel Hub

.circleci/config.yml, contrib/ci/build_windows.sh
=> Do the Win32 CI build on a non EoL release

plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c, plugins/logitech-bulkcontroller/logitech-bulkcontroller.quirk, plugins/logitech-bulkcontroller/proto/antiflicker.proto, plugins/logitech-bulkcontroller/proto/ble_cfg.proto, plugins/logitech-bulkcontroller/proto/crash_info.proto, plugins/logitech-bulkcontroller/proto/device_attestation.proto, plugins/logitech-bulkcontroller/proto/device_common.proto, plugins/logitech-bulkcontroller/proto/device_info.proto, plugins/logitech-bulkcontroller/proto/device_mode.proto, plugins/logitech-bulkcontroller/proto/device_request.proto, plugins/logitech-bulkcontroller/proto/device_time.proto, plugins/logitech-bulkcontroller/proto/firmware_update.proto, plugins/logitech-bulkcontroller/proto/ota_manifest.proto, plugins/logitech-bulkcontroller/proto/rightsight.proto, plugins/logitech-bulkcontroller/proto/usb_msg.proto
Support new Logitech Huddle device, Updated required proto files
=> Support new Huddle device

libfwupdplugin/fu-config.c
We already made the configuration files optional, so it's incongruent to make failures to read a non-essential file fatal.
This fixes running fwupdtool firmware-parse as non-root.
=> trivial: make permission failures for loading config non-fatal

plugins/pixart-rf/fu-pxi-ble-device.c
=> pixart-rf: Parse the HID descriptor to get the report ID

plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Fixes https://github.com/fwupd/fwupd/issues/6024
=> trivial: Validate the ESP from all possible paths

src/fu-util.c
=> Replace a hard-to-translate command description

contrib/snap/fwupd-command, libfwupdplugin/fu-path.c, libfwupdplugin/fu-path.h, plugins/linux-swap/fu-linux-swap.c
Fixes: https://github.com/fwupd/fwupd/issues/5995
=> Use /var/lib/snapd/hostfs for finding swapfiles in snap

plugins/genesys/fu-genesys-scaler-device.c, plugins/genesys/fu-genesys-usbhub-codesign-firmware.c, plugins/genesys/fu-genesys-usbhub-dev-firmware.c, plugins/genesys/fu-genesys-usbhub-device.c, plugins/genesys/fu-genesys-usbhub-firmware.c, plugins/genesys/fu-genesys-usbhub-pd-firmware.c
---
To fix memory leak and refactor to clearly and simply.
=> genesys: usbhub: fix some issues

plugins/dfu/fu-dfu-device.c, plugins/dfu/fu-dfu-device.h, plugins/dfu/fu-dfu-target-avr.c, plugins/dfu/fu-dfu-target-private.h, plugins/dfu/fu-dfu-target-stm.c, plugins/dfu/fu-dfu-target.c
=> dfu: Use a much larger USB timeout for STM32 erase operations

plugins/genesys/fu-genesys-usbhub-device.c, plugins/genesys/fu-genesys-usbhub.rs
=> genesys: usbhub: extend codesign updating

contrib/ci/fedora.sh
=> trivial: Maybe fix the Fedora CI

.github/workflows/matrix.yml
=> trivial: Install two more things via brew for the MacOS CI target

contrib/ci/dependencies.xml, subprojects/libxmlb.wrap
=> trivial: Uprev libxmlb to get the macOS content type fixes

SECURITY.md
I have to do this for a new Red Hat process, and I think it's easier to keep up to date if it's upstream.
=> trivial: Add some Threat Modeling notes

plugins/dell-dock/README.md, plugins/synaptics-mst/README.md, plugins/thunderbolt/README.md
These were just off the top of my head and straightforward.  
=> Add some data flow diagrams for plugins

plugins/synaptics-prometheus/fu-synaprom-config.c, plugins/synaptics-prometheus/fu-synaprom-device.c, plugins/synaptics-prometheus/fu-synaprom-device.h, plugins/synaptics-prometheus/fu-synaprom-firmware.c, plugins/synaptics-prometheus/fu-synaprom-firmware.h, plugins/synaptics-prometheus/synaptics-prometheus.quirk
- [x ] Feature
Add support for Triton, the new ASIC. This update maintains the same update protocol but adapts to a different cryptographic key size.
=> synaptics-prometheus: add triton support

plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
Change introduces retry after a delay to workaround ioctl errors right after reconnection of BLE connected HID device.
=> plugins: nordic-hid: Add retry after delay in setup

plugins/vli/fu-vli-usbhub-device.c
Minor fix while testing, for Lenovo. Thanks!
=> vli: trivial fix

libfwupdplugin/fu-pefile-firmware.c
=> fu-pefile-firmware: Load effective size of section instead of raw size

contrib/build-windows.sh, contrib/ci/build_macos.sh, contrib/ci/build_windows.sh, contrib/ci/dependencies.xml, libfwupd/fwupd-client.c, libfwupd/meson.build, meson.build, meson_options.txt
=> Do not build the libsoup compatibility mode by default

contrib/ci/Dockerfile-fedora.in, contrib/ci/fedora.sh
=> trivial: Don't use an unstable Fedora for CI

libfwupdplugin/fu-kernel.c, libfwupdplugin/fu-self-test.c
=> trivial: Ignore the trailing \n in the kernel command line

src/fu-engine.c
I do not understand how this ever worked before...
Fixes https://github.com/fwupd/fwupd/issues/6101
=> Ensure the AppstreamId is set on historical releases

plugins/pixart-rf/pixart-rf.quirk
- [X ] Documentation
Add new HPAC device to quirk of pixart-rf plugin
=> Add new HPAC device support pixart-rf

src/fu-engine.c
Delete both the prepared update file, and record success only when the device has returned to runtime mode.
This fixes RPi UF2 updates, and also means we don't record success "too early".
=> Record the update state of success when the device is returned to runtime

plugins/system76-launch/README.md, plugins/system76-launch/fu-system76-launch-device.c, plugins/system76-launch/system76-launch.quirk, plugins/uf2/fu-uf2-device.c, src/fu-engine.c
Fixes https://github.com/fwupd/fwupd/issues/5787
=> Support UF2 flashing of System76 boards with RP2040

src/fu-engine.c
=> trivial: Do not save the history if using _NO_HISTORY

data/bash-completion/fwupdtool, src/fu-tool.c
=> Allow using fwupdtool get-devices --json

contrib/build-windows.sh, contrib/ci/build_windows.sh
=> trivial: Fix the win32 CI build

contrib/build-windows.sh, contrib/ci/build_macos.sh, contrib/ci/build_windows.sh, libfwupd/fwupd-client.c, libfwupd/fwupd-common.h, meson.build, meson_options.txt, src/fu-daemon.c, src/fu-main-windows.c, src/fu-main.c
=> trivial: Fix a compile error with Ddbus_p2p=true on macOS

src/fu-engine.c
=> trivial: Do not warn when adding an existing file to Passim

src/fu-tool.c
=> trivial: Allow calling 'fwupdtool get-plugins' as the user

src/fu-util.c
If the user has downloaded [an embargoed] .cab file and then tries to upload a report without enabling and refreshing the remote it will fail as the remote ID will not be set in the FwupdRelease.
In the common case (there is only one LVFS...) fall back to using the hardcoded LVFS remote when using --force.
=> Try to use the LVFS when using report-history --force

meson_options.txt
=> trivial: Reformat meson_options.txt to be less of a wall of text

src/meson.build
Fixes https://github.com/fwupd/fwupd/issues/6175
=> trivial: Fix parallel build, harder still

plugins/pixart-rf/fu-pxi-ble-device.c, plugins/pixart-rf/fu-pxi-common.c, plugins/pixart-rf/fu-pxi-common.h, plugins/pixart-rf/fu-pxi-firmware.c
This patch is for showing HPAC version of BLE device
=> hpac_version_ble

meson.build
=> trivial: Abort the compile when MSVC is detected

contrib/debian/fwupd.install, contrib/debian/fwupd.postinst, contrib/debian/rules, contrib/fwupd.spec.in, data/motd/fwupd.sysusers, data/motd/meson.build, meson.build, meson_options.txt
Fixes https://github.com/fwupd/fwupd/issues/6153
=> Install a sysusers.d systemd file when using -Dsystemd_unit_user=

libfwupdplugin/fu-coswid-firmware.c
This saves 20 bytes per identity, which can add up really fast. We've supported decoding the TAG_ID as a bytestring since 1.8.5 and I'm not sure why I didn't fix the ->write() function at the same time.
=> Write the coSWID TAG_ID as a bytestring when possible

libfwupd/fwupd-enums.c
=> trivial: Fix a typo when converting device problems

libfwupdplugin/fu-progress.c, libfwupdplugin/fu-self-test.c
This effectively reverts 29f06b98, and replaces it with something much smarter.
=> Allow an insane number of steps for FuProgress

libfwupdplugin/fu-bytes.c
This reduces our memory use for large firmware by about 30%.
=> Load files using mmap() when possible

plugins/linux-lockdown/meson.build, plugins/linux-sleep/meson.build, plugins/linux-swap/meson.build, plugins/linux-tainted/meson.build
=> trivial: Only compile the Linux-specific plugins on Linux

src/fu-engine.c
=> Add global information from the context into the report data

libfwupd/fwupd-enums.c, libfwupd/fwupd-enums.h, libfwupdplugin/fu-common.c, libfwupdplugin/fu-common.h, libfwupdplugin/fu-context.c, libfwupdplugin/fu-context.h, libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, plugins/linux-display/README.md, plugins/linux-display/fu-linux-display-plugin.c, plugins/linux-display/fu-linux-display-plugin.h, plugins/linux-display/meson.build, plugins/meson.build, plugins/uefi-capsule/fu-uefi-capsule-plugin.c, src/fu-engine.c, src/fu-util-common.c
Fixes https://github.com/fwupd/fwupd/issues/6187
=> Allow devices to require a connected display

snap/snapcraft.yaml
This will need a request from the store.
Fixes #6141
=> snap: Use raw-usb plug

contrib/PKGBUILD, contrib/fwupd.spec.in, data/meson.build, data/org.freedesktop.fwupd.plist, meson.build, meson_options.txt
=> Add a launchd agent for macOS

libfwupdplugin/fu-byte-array.c, libfwupdplugin/fu-byte-array.h, libfwupdplugin/fu-self-test.c
=> trivial: Add fu_byte_array_from_string for future use

libfwupdplugin/fu-kernel.c, libfwupdplugin/fu-kernel.h, libfwupdplugin/fu-path.c, libfwupdplugin/fu-path.h, libfwupdplugin/fu-self-test.c
=> Add functionality to parse the kernel config

plugins/modem-manager/fu-firehose-updater.c
=> trivial: Fix an impossible-to-hit coverity warning

libfwupdplugin/fu-progress.c, libfwupdplugin/fu-self-test.c
=> Do not show a critical warning when using step scaling

plugins/mediatek-scaler/fu-mediatek-scaler-device.c
=> mediatek-scaler: Fix 'structurally dead code' spotted by Coverity

plugins/wacom-usb/fu-wac-module-bluetooth-id6.c, plugins/wacom-usb/fu-wac-module-bluetooth-id9.c, plugins/wacom-usb/fu-wac-module-bluetooth.c, plugins/wacom-usb/fu-wac-module-scaler.c, plugins/wacom-usb/fu-wac-module-touch-id7.c, plugins/wacom-usb/fu-wac-module-touch.c, plugins/wacom-usb/fu-wac-module.c, plugins/wacom-usb/fu-wac-module.h
=> Update wacom-usb plugin timings

libfwupdplugin/fu-oprom-firmware.c, libfwupdplugin/tests/oprom.builder.xml
These are useful for showing the members from the PCIR structure.
=> oprom: capture vendor ID and device ID

plugins/amd-gpu/fu-amd-gpu-device.c, plugins/amd-gpu/fu-amd-gpu-device.h, plugins/amd-gpu/fu-amd-gpu-plugin.c, plugins/amd-gpu/fu-amd-gpu-plugin.h, plugins/amd-pmc/fu-amd-pmc-device.c, plugins/amd-pmc/fu-amd-pmc-device.h, plugins/amd-pmc/fu-amd-pmc-plugin.c, plugins/amd-pmc/fu-amd-pmc-plugin.h, plugins/pci-psp/fu-pci-psp-device.c, plugins/pci-psp/fu-pci-psp-device.h, plugins/pci-psp/fu-pci-psp-plugin.c, plugins/pci-psp/fu-pci-psp-plugin.h
Per guidance from legal, these should be dual licensed.
=> trivial: Update license for all AMD specific files

libfwupdplugin/fu-path.c, libfwupdplugin/fu-path.h
This can be used for building paths to character devices
=> trivial: Add a new FU_PATH_KIND_DEVFS for fu_path_from_kind()

.github/workflows/codeql-analysis.yml, contrib/PKGBUILD, contrib/ci/dependencies.xml, contrib/fwupd.spec.in, meson.build, meson_options.txt, plugins/amd-gpu/README.md, plugins/amd-gpu/fu-amd-gpu-atom-firmware.c, plugins/amd-gpu/fu-amd-gpu-atom-firmware.h, plugins/amd-gpu/fu-amd-gpu-atom.rs, plugins/amd-gpu/fu-amd-gpu-device.c, plugins/amd-gpu/fu-amd-gpu-plugin.c, plugins/amd-gpu/fu-amd-gpu-psp-firmware.c, plugins/amd-gpu/fu-amd-gpu-psp-firmware.h, plugins/amd-gpu/fu-amd-gpu-psp.rs, plugins/amd-gpu/meson.build, snap/snapcraft.yaml, subprojects/fwupd-efi.wrap
=> Add support for flashing AMD dGPUs

libfwupdplugin/fu-drm-device.c
=> Use a heuristic to detect internal DRM devices

libfwupdplugin/fu-drm-device.c
=> trivial: fix drm connected attribute

.github/workflows/matrix.yml, .github/workflows/pull-request-reviews.yml, contrib/ci/fwupd_setup_helpers.py, snap/snapcraft.yaml
In trying to fixup rust PR I noticed we hardcode meson version in too many places.  Try to decouple more of them.
=> Various CI improvements

plugins/logitech-bulkcontroller/README.md, plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-common.c, plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c, plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller.rs
We've worked out the state machine so we're not drowning in retry loops.
=> logitech-bulkcontroller: Speed up enumeration

libfwupdplugin/fu-device.c, libfwupdplugin/fu-device.h, plugins/nordic-hid/fu-nordic-hid-cfg-channel.c, src/fu-engine.c, src/fu-util.c
=> nordic-hid: Inhibit the dongle when there are peripheral updates pending

plugins/synaptics-prometheus/synaptics-prometheus.quirk
=> synaptics-prometheus: add PID to quirk file

plugins/mediatek-scaler/README.md, plugins/mediatek-scaler/fu-mediatek-scaler-common.c, plugins/mediatek-scaler/fu-mediatek-scaler-common.h, plugins/mediatek-scaler/fu-mediatek-scaler-device.c, plugins/mediatek-scaler/fu-mediatek-scaler-device.h, plugins/mediatek-scaler/fu-mediatek-scaler-firmware.c, plugins/mediatek-scaler/fu-mediatek-scaler-firmware.h, plugins/mediatek-scaler/fu-mediatek-scaler-plugin.c, plugins/mediatek-scaler/fu-mediatek-scaler-plugin.h, plugins/mediatek-scaler/fu-mediatek-scaler.rs
=> mediatek-scaler: update copyright statement and reviewers

plugins/vli/fu-vli-common.c, plugins/vli/fu-vli-device.c, plugins/vli/fu-vli-usbhub-device.c, plugins/vli/fu-vli-usbhub-firmware.c, plugins/vli/fu-vli.rs, plugins/vli/vli-luxshare.quirk
add code to support VL830 hub update
=> vli: add vl830

contrib/ci/debian.sh, libfwupdplugin/fu-common-darwin.c, libfwupdplugin/fu-common-linux.c, libfwupdplugin/fu-common-private.h, libfwupdplugin/fu-common-windows.c, libfwupdplugin/fu-common.c, libfwupdplugin/fu-common.h, libfwupdplugin/fu-path.c, libfwupdplugin/fu-path.h, libfwupdplugin/fu-self-test.c, libfwupdplugin/tests/localtime
=> Add fu_common_get_olson_location() for future use

docs/fwupd.conf.md, libfwupd/fwupd-client.c, src/fu-engine-helper.c, src/fu-util.c, src/org.freedesktop.fwupd.xml
=> Allow to have more than one host BKC

plugins/logitech-rallysystem/README.md, plugins/logitech-rallysystem/fu-logitech-rallysystem-audio-device.c, plugins/logitech-rallysystem/fu-logitech-rallysystem-audio-device.h, plugins/logitech-rallysystem/fu-logitech-rallysystem-plugin.c, plugins/logitech-rallysystem/fu-logitech-rallysystem-plugin.h, plugins/logitech-rallysystem/fu-logitech-rallysystem-tablehub-device.c, plugins/logitech-rallysystem/fu-logitech-rallysystem-tablehub-device.h, plugins/logitech-rallysystem/fu-logitech-rallysystem.rs, plugins/logitech-rallysystem/logitech-rallysystem.quirk, plugins/logitech-rallysystem/meson.build, plugins/meson.build
- [N/A] Implement FuFirmware->write() and include at least one fuzzer testcase in src/fuzzing/firmware for any custom FuFirmware subclass
[fwupd_fwupdmgr_console_output_trimmed.zip](https://github.com/fwupd/fwupd/files/13208846/fwupd_fwupdmgr_console_output_trimmed.zip)
=> New Plugin for Logitech RallySystem conf device

plugins/vli/fu-vli-pd-firmware.c
=> vli:add luxshare id

contrib/ci/dependencies.xml, libfwupdplugin/meson.build
=> Fix gcab parallel build

plugins/android-boot/android-boot.quirk, plugins/android-boot/fu-android-boot-plugin.c
=> android-boot: Fix enumeration by porting to fu_plugin_add_device_udev_subsystem()

plugins/colorhug/README.md, plugins/dfu-csr/README.md, plugins/dfu/README.md, plugins/ebitdo/README.md, plugins/elanfp/README.md, plugins/ep963x/README.md, plugins/fastboot/README.md, plugins/fpc/README.md, plugins/fresco-pd/README.md, plugins/goodix-moc/README.md, plugins/goodix-tp/README.md, plugins/logitech-bulkcontroller/README.md, plugins/logitech-hidpp/README.md, plugins/nitrokey/README.md, plugins/nordic-hid/README.md, plugins/nvme/README.md, plugins/qsi-dock/README.md, plugins/rts54hid/README.md, plugins/rts54hub/README.md, plugins/scsi/README.md, plugins/steelseries/README.md, plugins/synaptics-cape/README.md, plugins/synaptics-cxaudio/README.md, plugins/system76-launch/README.md, plugins/usi-dock/README.md, plugins/vendor-example/README.md.in, plugins/vli/README.md, plugins/wacom-usb/README.md, plugins/wistron-dock/README.md
=> trivial: Update the plugin README GUID sections to reflect reality

libfwupdplugin/fu-security-attrs.c
Fixes https://github.com/fwupd/fwupd/issues/6323
=> Do not save obsoleted HSI attributes in the database

libfwupdplugin/meson.build
Fixes https://github.com/fwupd/fwupd/issues/6325
=> Use an external gcab binary when cross building

libfwupd/fwupd-enums.h, libfwupd/fwupd-report.h, libfwupdplugin/fu-device.h, src/fu-self-test.c
=> trivial: Be consistent between 1ull and 1llu

plugins/wacom-raw/fu-wacom-device.c
=> wacom-raw: Prompt the user to reboot after applying firmware

src/fu-util.c
See https://github.com/fwupd/fwupd/discussions/6344
=> trivial: Tweak the review upload question

libfwupdplugin/fu-uswid-firmware.c, libfwupdplugin/fu-uswid.rs
=> Support uSWID SBoM data with LZMA compressed payloads

libfwupdplugin/fu-dpaux-device.c
Fixes https://github.com/fwupd/fwupd/issues/6308
=> Do not read the AMDGPU DM DPCD on broken firmware versions

plugins/redfish/fu-redfish-device.c
Fixes https://github.com/fwupd/fwupd/issues/6351
=> redfish: Accept any registry versions when parsing message IDs

plugins/redfish/fu-ipmi-device.c
Fixes https://github.com/fwupd/fwupd/issues/6349
=> redfish: Fix IPMI_GET_DEVICE_ID_CMD via KCS

src/fu-engine.c
=> trivial: Ignore GIOError no-supported when running device-added

.circleci/config.yml, contrib/ci/Dockerfile-fedora.in, contrib/ci/dependencies.xml, contrib/ci/fedora.sh
=> trivial: Rebase the CI to Fedora 39

libfwupd/fwupd-client.c, src/fu-engine.c
=> trivial: Do not attempt to use passim when using authentication

contrib/ci/dependencies.xml, contrib/debian/rules
=> Adjustments to handle /usr merge in Debian

plugins/redfish/redfish.quirk
See https://github.com/fwupd/fwupd/issues/6380
- [*] Feature
=> redfish: Add 'Advantech' manufacture into redfish quirk

plugins/redfish/README.md
Fixes #6385
- [*] Documentation
=> redfish: Typo in README.md from redfish plguin

plugins/tpm/fu-tpm-eventlog-common.c
Fixes some of https://github.com/fwupd/fwupd/issues/6379
=> trivial: Read SM3-256 TPM eventlog hashes

libfwupdplugin/fu-security-attrs.c
Fixes https://github.com/fwupd/fwupd/issues/6392
=> Remove obsoleted HSI attributes earlier

libfwupdplugin/fu-cab-firmware.c
The windows makecab.exe utility does not reset the compression state between CFDATA blocks, and so we have to do the same for decompression.
=> Support cabinet archives produced using makecab.exe

contrib/ci/dependencies.xml, contrib/debian/control.in, data/installed-tests/fwupd.sh, libfwupdplugin/fu-bytes.c, plugins/amd-gpu/fu-amd-gpu-device.c, plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c, plugins/mediatek-scaler/fu-mediatek-scaler-device.c, src/fu-engine.c
=> trivial: debian: fix CI failure caused by obsolete package

src/fu-util.c
Fixes https://github.com/fwupd/fwupd/issues/6379
=> Fix 'fwupdmgr get-devices' with deeply nested devices

plugins/vli/README.md, plugins/vli/fu-vli-usbhub-device.c, plugins/vli/vli-luxshare.quirk
add "attach-with-usb" flag - for dongle devices, unplug & re-plug usb cable to reboot
add  "attach-with-power" flag - for dock devices, unplug & re-plug  power cord to reboot
=> vli:add_flags

plugins/cros-ec/fu-cros-ec-usb-device.c
This regressed in 3f5daa77a0d2cec2e847600043493dd551be6a31 where the semantics changed a little.
=> cros-ec: Fix emulation

plugins/kinetic-dp/README.md, plugins/kinetic-dp/fu-kinetic-dp-device.c, plugins/kinetic-dp/fu-kinetic-dp-device.h
=> kinetic-dp: Make the matching GUID specific to the customer

src/fu-tool.c
=> Use metadata authentication if supplied when using 'fwupdtool refresh'
