- plugins/nordic-hid/nordic-hid.quirk
Change adds Product ID of nRF52 Desktop Keyboard to the quirk file.
This is needed to support nRF52 Desktop Keyboard in the plugin.
> nordic-hid: Add nRF52 Desktop Keyboard to the quirk

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- src/fu-release.c
- src/fu-self-test.c
NOTE: This can only be used to affect device write, not device enumeration.
> Allow setting device flags in the metadata

- data/installed-tests/README.md
daemon option is already removed. Use build=all
to enable daemon
> trivial: update installed-tests doc

- plugins/nordic-hid/README.md
- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
- plugins/nordic-hid/nordic-hid.quirk
Change introduces handling of devinfo configuration channel option. The option provides information about device Vendor ID, Product ID and generation.
The generation string allows to distinguish configurations that use the same board and bootloader, but are not interoperable. Fetching values of VID and PID allows the host computer to retrieve these values for peripherals connected through an nRF Desktop dongle (in that case the host computer has no direct access to VID and PID).
> plugins: nordic-hid: Add devinfo handling

- contrib/pcap2emulation.py
"UsbDevices" is already part of self.phases[n]
> trivial: contrib/pcap2emulation: Fix supplementary phase file format

- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
Change allows board to override bootloader defined in quirk file. The value defined in the quirk file can still be used for boards that do not provide information about the bootloader through the configuration channel.
> plugins: nordic-hid: Allow board to override bootloader from quirk

- plugins/dell-dock/dell-dock.quirk
- plugins/dell-dock/fu-dell-dock-plugin.c
The USB4 dock requires `usable-during-update` flag to enable updating the NVM firmware in a cycle of the Type-C cable is disconnected and re-connected.
> dell-dock: trigger passive flow for usb4 from intel-usb4 plugin

- libfwupdplugin/README.md
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-plugin.h
- libfwupdplugin/fu-self-test.c
- plugins/msr/fu-msr-plugin.c
- plugins/redfish/fu-redfish-plugin.c
- plugins/thunderbolt/fu-thunderbolt-plugin.c
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- src/fu-engine.c
This means we can ship a fwupd without any config files at all, and reduces the mental gymnastics when reading empty integer values.
> Move the expected default plugin config value to the code

- libfwupdplugin/fu-bytes.c
- libfwupdplugin/fu-bytes.h
- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-firmware.h
- libfwupdplugin/fwupdplugin.map
- plugins/mtd/README.md
- plugins/mtd/fu-mtd-device.c
- plugins/mtd/fu-mtd-plugin.c
Some MTD partitions are huge, and take a long time to dump. If we know the offset the metadata is going to be located at, allow it to be specified in the quirk file.
This speeds up reading uSWID metadata for the BMC partition by several orders of magnitude.
Also, don't fail to add the MTD device if the metdata is not found.
> mtd: Allow specifying the metadata offset and size

- data/daemon.conf
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-self-test.c
- src/fu-config.c
- src/fu-config.h
- src/fu-engine.c
- src/fu-release.h
- src/fu-self-test.c
- src/fu-util-common.c
- src/tests/daemon.conf
- src/tests/metadata-report1.xml
- src/tests/metadata-report2.xml
For instance, this could be used to only show a desktop notification if the report has been verified to work on ChromeOS, or to only auto-install the update on an automotive system if tested by Red Hat QA.
> Tag releases with an extra flag if they have a report we trust

- src/fu-daemon.c
The method change name from ModifyConfig to ModifyDaemonConfig in 7fa422744
> trivial: Fix ModifyDaemonConfig not accessible

- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
If available, use VID and PID fetched in devinfo. Otherwise, use hardcoded VID and PID of 0x00 only for devices connected via dongle. This prevents from inheriting VID and PID of the dongle.
> plugins: nordic-hid: Use VID and PID of 0x00 for dongle connection

- data/motd/fwupd-refresh.timer
Due to systemd timers applying RandomizedDelaySec upon reboot, the previous 12h maximum delay meant that the timer would rarely trigger on devices that reboot often (systemd/systemd#21166). We set the timer to trigger with a randomised delay of up to 1h, every hour.
Fixes #5731.
> Have fwupd-refresh.timer trigger once per hour on average

- data/bash-completion/fwupdmgr
- data/fish-completion/fwupdmgr.fish
- src/fu-tool.c
- src/fu-util.c
- src/fwupdmgr.md
- src/fwupdtool.md
This waits for a specific device to appear. Additionally, a new return code is returned when a specific resource (typically a device) does not exist.
Fixes https://github.com/fwupd/fwupd/issues/5740
> Add a new device-wait command to fwupdmgr

- src/fu-engine.c
We might be fixing a bug related to metadata cache generation.
> Invalidate the XMLb cache when installing new fwupd versions

- plugins/nordic-hid/README.md
- plugins/nordic-hid/fu-nordic-hid-archive.c
- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
Change introduces support for MCUboot bootloader built in direct-xip mode.
> plugins: nordic-hid: Add MCUboot direct-xip mode support

- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-plugin.h
- src/fu-engine.c
It's no longer required as we use fwupd.conf for everything.
> Remove the FuPlugin::config-changed signal

- src/fu-self-test.c
Fixes https://github.com/fwupd/fwupd/issues/5778
> trivial: Only run the spawn self tests when running slow tests

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
- plugins/thunderbolt/fu-thunderbolt-controller.c
Only do the warning for non-SUPPORTED_BUILD as it's really a programmer error and the only badness is getting 'null' in the debug to-string functions.
> Detect missing calls to register_private_flag()

- docs/fwupd.conf.md
- plugins/thunderbolt/README.md
- plugins/thunderbolt/fu-thunderbolt-plugin.c
- plugins/thunderbolt/thunderbolt.quirk
One config value is not granular enough; for the same build of fwupd on RHEL or ChromeOS we only want to target the hardware where the EC is going to actually do what we tell it to -- rather than crash...
> Enable the retimer offline mode depending on HWIDs

- plugins/steelseries/fu-steelseries-fizz-hid.c
In BlueTooth mode the sync and data channels are sharing the device descriptor with the management channel.
This is the reason why we receive "unexpected" packets with `0x01` or `0x05` Report IDs over the same descriptor on mouse connecting, waking up or just touching the mouse during the version query.
The unexpected data from the sync channel (`0x05` Report ID) contains non-printable characters (for example: `05 12 14 00 00 00`), so `fu_steelseries_fizz_hid_get_version()` return `NULL` without setting the proper error, leading to segmentation fault of the `fwupd` daemon.
Any data from the mouse input (`0x01` Report ID) is treated as error, hence the device is not detected properly but without the `fwupd` crashing.
Fixes: https://github.com/fwupd/fwupd/issues/5786
- …
> steelseries: fix the version detection for Bluetooth mode

- plugins/logitech-hidpp/logitech-hidpp.quirk
The patch enables fwupd to work with two new variants of Logitech Unifying receiver (TI).
I have tested the patch on my `C-U0012` Pico receiver and it works totally fine. Differing from previous `C-U0012`s whose PID in DFU mode is `AAAD`, mine is `AAE5`.
There is another variant get supported in this patch, whose PID in DFU mode is `AAF8`. I do not have such a receiver and the PID is documented in https://github.com/Logitech/fw_updates/blob/1ddde61310573ecea54c4204b401393a90f4bbae/RQR24/RQR24.11/RQR24.11_B0036.txt#L22. I guess it is `C-U0016`, a signal-enhanced Unifying receiver bundled with `K600` (ref: https://post.smzdm.com/p/aqnlx78p), which is known to be driven by a TI CC2544 (ref: https://fccid.io/JNZCU0016/Internal-Photos/Internal-Photos-3182497.pdf). I've …
> logitech-hidpp: Add support for more TI Unifying receiver variants

- plugins/wacom-usb/fu-wac-module-bluetooth-id6.c
- plugins/wacom-usb/fu-wac-module.c
In some cases fwupd polling the device so quickly after setting the feature report can cause the device firmware to return junk, or self-reset. Add a small delay as a pragmatic fix -- which doesn't actually slow down the firmware deploy as it's normally when 'busy' is returned.
Also, increase the maximum allowed time for an ID6 write as in some rare circumstances it can take more than the maximum 2000ms.
> wacom-usb: Allow the firmware time to process commands to avoid a device crash

- docs/fwupd.conf.md
I believe this man page needs to be updated to use `[fwupd]` as the section (consistent with the provided default fwupd.conf and with what I can see in the current source).
> Fix fwupd.conf(5) man page to use [fwupd] section

- meson.build
Fixes:
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
> trivial: Fix a meson warning

- docs/tutorial.md
- libfwupdplugin/fu-rustgen-struct.c.in
- libfwupdplugin/rustgen.py
- plugins/ebitdo/fu-ebitdo.rs
- plugins/fpc/fu-fpc-device.c
- plugins/fpc/fu-fpc.rs
- plugins/intel-usb4/fu-intel-usb4.rs
- plugins/synaptics-prometheus/fu-synaprom.rs
- plugins/synaptics-rmi/fu-synaptics-rmi.rs
- plugins/tpm/fu-tpm.rs
- plugins/uefi-capsule/fu-uefi-device.c
- plugins/uefi-capsule/fu-uefi.rs
- plugins/usi-dock/fu-usi-dock-common.h
- plugins/usi-dock/fu-usi-dock-mcu-device.c
- plugins/usi-dock/fu-usi-dock.rs
- plugins/wistron-dock/fu-wistron-dock.rs
This allows us to pick up problems using `-Wenum-conversion` -- but means we have to define the enums before the structs.
> Allow using enum types in rustgen structs

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fwupdplugin.map
- src/fu-device-list.c
Make the code match the comment; 'same object' in this sense means the same pointer address -- not just the same device ID.
> Make using the device-list simpler

- libfwupdplugin/fu-rustgen-enum.c.in
- libfwupdplugin/fu-rustgen-enum.h.in
- libfwupdplugin/fu-rustgen-struct.c.in
- libfwupdplugin/fu-rustgen-struct.h.in
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-self-test.rs
- libfwupdplugin/rustgen.py
- plugins/vli/fu-vli.rs
This turned into a bit of a rewrite; we now parse the .rs file and then generate the c and h files, rather than doing it inline.
This allows us to resolve enums in the struct generator. It also will allow us to nest structs in the future too.
> Print the enum type when parsing rustgen structs

- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
Both B0 and MCUboot bootloaders verify firmware signature.
> plugins: nordic-hid: Declare signed payload

- plugins/nordic-hid/README.md
- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
- plugins/nordic-hid/nordic-hid.quirk
Allow to use the plugin with any Nordic HID device that supports the configuration channel (check only Vendor ID).
Define common default values of generation and bootloader in quirk. The values are used for all of the Nordic HID devices. Values other than "B0" bootloader and "default" generation must be explicitly reported by device. This is needed to apply the quirk content to peripherals connected via dongle (in this scenario we do not know Product ID in advance).
> plugins: nordic-hid: Update quirk content

- data/installed-tests/fwupd.sh
autopkgtest in Ubuntu has a proxy configuration issue on some autopkgtest hosts that is causing it to sometimes fail.
This needs to get fixed on the server end but it's actually surprising it was being run in the first place because we snuck tests in with new artifacts that depended on LVFS now.
We should gate this running behind CI_NETWORK, just like we do for other test data.
Link: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/2021908
> trivial: Don't run emulation tests without CI_NETWORK set

- plugins/wacom-usb/fu-wac-module-bluetooth-id6.c
- plugins/wacom-usb/fu-wac-module.c
If the flash process gets to COMMAND_END then this fix ensures the last data packet was padded out to 512 bytes as per the specification. Although the touch, scaler and main firmware do not care, it seems the ID6 module is picky.
This at least doubles the chance of success for my device.
Fixes https://github.com/fwupd/fwupd/issues/5891
> wacom-usb: Do not truncate feature reports to fix ID6 update

- plugins/vli/fu-vli-pd-firmware.c
- plugins/vli/meson.build
- plugins/vli/vli-fujitsu.quirk
Why howdy! It's **us**, unruly characters. 
On behalf of Fujitsu Siemens Computer Monitors, we're adding their information into vli's plugin. No rush, please review at your most, convenient, leisure. Much obliged. 
Minor aside, we're delighted by all the QoL changes, you guys have worked hard.
> vli: add fujitsu

- plugins/ccgx-dmc/ccgx-dmc-noinst.quirk
- plugins/ccgx-dmc/ccgx-dmc.quirk
- plugins/ccgx-dmc/fu-ccgx-dmc-device.c
The trigger code is only used when `CcgxDmcUpdateModel` is `DownloadTrigger`.
This is on advice of Infineon.
> ccgx-dmc: Default to TriggerCode of 0x1

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util.c
UEFI capsules require a valid ESP -- and although firmware may work using a BDP [FAT32] partition -- this is not always true.
Most installers create a valid ESP, but users creating a FAT32 partition by hand will have the wrong flags set. Fixing is as easy as:
parted /dev/nvmeXnY set 1 esp on
...but isn't something we should do automatically.
Show users a wiki link explaining the problem on the console.
Fixes https://github.com/fwupd/fwupd/issues/5906
> Show the user a warning when the ESP may not be valid

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- src/fu-engine.c
- src/fu-self-test.c
- src/fu-util-common.c
For some devices, a 'newer' release may be no better than the version they have right now, or is may be unexpected or disallowed to update the firmware automatically.
In other cases it might be that per-device user-set presets would be cleared on update, or that only Best Known Configuration is allowed for regulatory reasons.
Provide a per-device flag that allows the explicit install action, but hides the device from the 'simple' GetUpgrades API call.
> Allow devices to only accept explicitly specified release versions

- plugins/flashrom/flashrom.quirk
- plugins/superio/superio.quirk
Updating quirks for TUXEDO devices:
- TUXEDO InfinityBook S 14/15 Gen6 GUID where based on older DMI strings that didn't actually ship
- New GUIDs for TUXEDO InfinityBook Pro 13 v3 (only for BIOS/flashrom plugin as EC/superio plugin is not yet tested on this device
I noticed that the fn-m-me-unlock flag doesn't actually do anything? At least from the command line. Is the promt to reboot with FN+M pressed only for GUI or am I encountering a bug?
> Update TUXEDO quirks

- libfwupdplugin/fu-efi-device-path-list.c
- libfwupdplugin/fu-efi-load-option.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60073
> trivial: Fix a fuzzing crash when parsing crazy EFI loadopts

- libfwupdplugin/fu-efivar-impl.c
- libfwupdplugin/meson.build
We used to use the Windows one for this, but now it's actually implemented.
> Fix oss-fuzz by providing a dummy efivar implementation

- plugins/genesys/fu-genesys-common.h
- plugins/genesys/fu-genesys-usbhub-codesign-firmware.c
- plugins/genesys/fu-genesys-usbhub-codesign-firmware.h
- plugins/genesys/fu-genesys-usbhub-dev-firmware.c
- plugins/genesys/fu-genesys-usbhub-dev-firmware.h
- plugins/genesys/fu-genesys-usbhub-device.c
- plugins/genesys/fu-genesys-usbhub-firmware.c
- plugins/genesys/fu-genesys-usbhub-firmware.h
- plugins/genesys/fu-genesys-usbhub-pd-firmware.c
- plugins/genesys/fu-genesys-usbhub-pd-firmware.h
- plugins/genesys/fu-genesys-usbhub.rs
- plugins/genesys/meson.build
To parse device-bridge and PD firmware then record them. Also records codesign info. 
Add `vfunc->prepare()` to collect information before `vfunc->prepare_firmware()`. 
- check fw bank is valid.
- get fw bank version.
- move from `_setup()`, it can reduce reading flash to improve running time. 
Refactor  `_write_firmware()` with specific address. 
- rename `_write_recovery()` to `_backup_hub_fw_bank1_to_bank2()` and refactor to use saved bank1 data and key.
- add `_update_firmware()` to update each FuFirmware.
- add `_compare_flash_blank()` to check erasing flash succeeded.
- add `_compare_flash_data()` to sequential check each read chunk.
> genesys: usbhub: Supporting device-bridge and PD firmware update

- libfwupdplugin/fu-progress.c
The progress hierarchy is very deep at startup -- by clearing the child signals when they are done we can save a lot of memory.
> Reduce the amount of RSS by ~700K by disconnecting signals

- data/cfi.quirk
- meson.build
- plugins/genesys-gl32xx/README.md
- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.h
- plugins/genesys-gl32xx/fu-genesys-gl32xx-firmware.c
- plugins/genesys-gl32xx/fu-genesys-gl32xx-firmware.h
- plugins/genesys-gl32xx/fu-genesys-gl32xx-plugin.c
- plugins/genesys-gl32xx/fu-genesys-gl32xx-plugin.h
- plugins/genesys-gl32xx/fu-genesys-gl32xx.rs
- plugins/genesys-gl32xx/genesys-gl32xx.quirk
- plugins/genesys-gl32xx/meson.build
- plugins/meson.build
New plugin for Genesys SD readers.
This plugin allow to update and dump firmware for GL3232 and GL3224 families SD readers.
Supported devices based on flash IDs:
- `PM25LD010` (tested)
- `MX25L1006E` (not tested)
- `GD25D10B` (not tested)
- [ X] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
> genesys_gl32xx: new plugin for Genesys SD readers

- plugins/uefi-dbx/fu-dbxtool.c
- plugins/uefi-dbx/fu-uefi-dbx-common.c
- plugins/uefi-dbx/fu-uefi-dbx-common.h
- plugins/uefi-dbx/fu-uefi-dbx-device.c
Inspired from a patch by Crag Wang <crag.wang@dell.com>, many thanks.
> uefi-dbx: Check only the efi executables from boot menu

- libfwupdplugin/fu-pefile-firmware.c
- libfwupdplugin/fu-pefile.rs
- libfwupdplugin/fu-rustgen-struct.h.in
- libfwupdplugin/meson.build
Also, use rustgen to validate PE files.
> Load PE/COFF long section names from string table

- data/device-tests/jabra-evolve2-75.json
Not entirely sure which type of PR applies.
This PR adds the device test json file for Jabra Evolve2 75, using the 3 possible GUIDs and the latest 2 firmware versions
> added device test json file for Jabra Evolve2 75

- plugins/genesys-gl32xx/README.md
- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
└─GL323x SD reader [0x0764]:
Device ID:          268092d4100a2a2e4ffe010ce476db434a0dbf47
Current version:    2960
Vendor:             Genesys (BLOCK:0x05E3)
GUIDs:              9125a0e3-fc06-5648-8044-021842ff3eed ← BLOCK\VEN_05E3&DEV_0764
ce88d98c-d36c-5b55-bac4-f07af9e0c022 ← BLOCK\VEN_05E3&DEV_0764&VER_29
Device Flags:       • Updatable
• Cryptographic hash verification is available
• Unsigned Payload
> genesys-gl32xx: Add an extra GUID to differentiate firmware streams

- libfwupdplugin/fu-srec-firmware.c
- libfwupdplugin/fu-srec-firmware.h
- plugins/wacom-usb/fu-wac-firmware.c
This regressed in https://github.com/fwupd/fwupd/commit/5ad1462de2d7d2b93376c9f55fe061b5b01d0f0b.
Fixes https://github.com/fwupd/fwupd/issues/5971
> Do not misuse the offset as an address in the SREC parser

- libfwupdplugin/fu-efi-file-path-device-path.c
- libfwupdplugin/fu-efi-load-option.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-string.c
- libfwupdplugin/fu-string.h
- plugins/acpi-phat/fu-acpi-phat-health-record.c
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-capsule/fu-uefi-cod-device.c
- plugins/uefi-capsule/fu-uefi-device.c
- plugins/uefi-capsule/fu-uefi-tool.c
I forgot that UTF-16 is usually written in host-native endian -- which isn't what the firmware is expecting.
> trivial: Fix self test failure on s390x

- plugins/genesys-gl32xx/README.md
- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
Added GUIDs with customer ID "CID" key:
```
├─GL3224 SD reader [0x0749]:
│     Device ID:          df55aa7088230719e6511a287c130e79cb203efc
│     Current version:    1539
│     Vendor:             Genesys (BLOCK:0x05E3)
│     Serial Number:      000000001539
│     GUIDs:              33bf0d51-f87e-54a0-bbfc-efb323601e31 ← BLOCK\VEN_05E3&DEV_0749
│                         94299e46-f54f-540a-a670-d075b82a477a ← BLOCK\VEN_05E3&DEV_0749&VER_15
│                         0ab7a3da-cb81-5e60-9f2d-863e6de4c0de ← BLOCK\VEN_05E3&DEV_0749&CID_FFFFFFFF
│                         388208e0-add9-5b77-b9c9-f854a2b30f3e ← BLOCK\VEN_05E3&DEV_0749&VER_15&CID_FFFFFFFF
│     Device Flags:       • Updatable
│                         • Cryptographic hash verification is available
│                         • …
```
> genesys-gl32xx: add GUIDs based of customer ID

- docs/fwupd-remotes.d.md
- docs/meson.build
- libfwupd/fwupd-remote.c
- libfwupd/fwupd-remote.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- src/fu-util-common.c
- src/fu-util.c
Using 24h is suitable for the LVFS that changes ~4 times per day, but other remotes may want a much smaller or much larger interval.
> Allow configuring the refresh interval per-remote

- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
The GL32XX readers answer queries for some partitions leading to multiple devices detected. Query only disk types to avoid duplication.
> genesys-gl32xx: do not try disk partitions

- libfwupdplugin/fu-efi-hard-drive-device-path.c
- libfwupdplugin/fu-volume.c
- libfwupdplugin/fu-volume.h
- meson.build
Unfortunately, UDisks does not provide us this in a nice-to-read D-Bus property, so do things the old way with a ioctl. This makes it Linux/BSD specific so also fallback to 0x200 as before.
Fixes https://github.com/fwupd/fwupd/issues/6023
> uefi-capsule: Do not assume the logical block size is always 0x200

- contrib/debian/rules
Thanks to Helmut Grohne <helmut@subdivi.de> for this patch
Fixes: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1041752
> trivial: debian: avoid shipping an empty systemd dir

- src/fu-util.c
Some feature flags are things that the client is *capable* of doing (e.g. the FDE warning), and not everything strictly depends on having a TTY.
Fixes https://github.com/fwupd/fwupd/issues/6036
> Set some feature flags when non-interactive

- libfwupd/README.md
- libfwupd/fwupd-remote-private.h
- libfwupd/fwupd-remote.c
- libfwupd/fwupd-remote.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
- src/fu-engine.c
- src/fu-remote-list.c
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util.c
We've about to add 2 more booleans, and this should have been a bitfield like the other objects all along. The sooner we convert it the less compat code we need.
> Convert 4 binary FwupdRemote values to a bitfield

- plugins/genesys/fu-genesys-scaler-device.c
- plugins/genesys/fu-genesys-usbhub-codesign-firmware.c
- plugins/genesys/fu-genesys-usbhub-dev-firmware.c
- plugins/genesys/fu-genesys-usbhub-device.c
- plugins/genesys/fu-genesys-usbhub-firmware.c
- plugins/genesys/fu-genesys-usbhub-pd-firmware.c
because current fwupd only depend on glib 2.68.
> genesys: revert using g_prefix_error_literal()

- plugins/pixart-rf/fu-pxi-ble-device.c
- plugins/pixart-rf/fu-pxi-common.h
- plugins/pixart-rf/fu-pxi-firmware.c
- plugins/pixart-rf/fu-pxi-firmware.h
- plugins/pixart-rf/pixart-rf.quirk
- HPAC BLE devices OTA implement.
**Checklist**
Tested on "Ubuntu 20.04.5 LTS" . And It works well.
>   Add Pixart-HPAC plugin.

- plugins/modem-manager/modem-manager.quirk
Hi，
[ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
[ ] Code fix
[*] Feature
[ ] Documentation
The Quectel new RM520N-GL product works with the Quectel's existing RM520N-GL modem settings.
But this one is designed for lenovo laptop usecase, hence Quectel got a new PID.
Thanks and happy holidays!
> Add device ID and support for Quectel RM520

- plugins/wacom-usb/wacom-usb.quirk
Define quirks to recognize the Wacom's two newly-announced "Wacom One" devices.
> wacom-usb: Define quirks for new Wacom One tablets (CTC4110WL, CTC6110WL)

- plugins/wacom-usb/fu-wac-module.c
- plugins/wacom-usb/fu-wac.rs
The recently-added ID9 module is failing to flash properly due to an oversight that occurred while merging. This pull request fixes the issue and also updates the plugin to waste less time trying to recover from unrecoverable states.
> wacom-usb: Correct flash errors with ID9 module

- plugins/modem-manager/fu-mbim-qdu-updater.c
- plugins/modem-manager/fu-mm-device.c
T99W373 is a modem device based on mbim qdu. This device needs about 12-16s to response last write mbim qdu message. So we need to increase the default timeout 10 to 20. Besides that, this device needs reboot twice to uprgade FW successfully.So we need to increase the replug time from 120s to 180s in case another timed out issue.
> modem_manager: Fix transaction timed out issue for T99W373 qdu device

- plugins/intel-me/fu-intel-me-mca-device.c
- plugins/intel-me/fu-intel-me.rs
- plugins/intel-me/meson.build
According to Intel sections 0x4 and 0x8 are only used for development testing. Using 0x0 is sufficient to get the value from either the FPF *or* NVRAM.
> intel-me: Only query one set of FILE_IDs

- src/fu-util.c
The history result comes with all the releases included and we calling GetReleases on each one adds a duplicate release.
> Fix fwupdmgr get-history --json output

- src/fu-remote-list.c
On ChromeOS the /etc path is immutable, and we have to save the remote contents into the mutable version instead.
> Fix 'fwupdmgr modify-remote' on ChromeOS

- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
The logic was all backwards; the refresh loop is already using _needs_refresh() which works per-remote now.
> trivial: Fix the refresh logic in fwupdmgr

- SECURITY.md
- contrib/ci/dependencies.xml
- contrib/ci/fedora.sh
- contrib/fwupd.spec.in
- docs/fwupd.conf.md
- libfwupd/fwupd-client.c
- libfwupd/fwupd-remote.c
- libfwupd/fwupd-remote.h
- meson.build
- meson_options.txt
- src/fu-engine-config.c
- src/fu-engine-config.h
- src/fu-engine.c
- src/fu-engine.rs
- src/fu-release.h
- src/fu-util-common.c
- src/meson.build
- subprojects/.gitignore
- subprojects/passim.wrap
Using the Passim project allows fwupd to download metadata from other machines on your local network using the SHA-256 hash.
Using Passim should reduce the bandwidth needed by fwupd from offices and homes considerably.
> Add support for Passim

- plugins/fastboot/fastboot.quirk
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-mm-device.h
- plugins/modem-manager/fu-mm-plugin.c
- plugins/modem-manager/modem-manager.quirk
FM101 device-related parameters were added to quirk files of MM and fastboot plugins.
AT command receiving problem when modem opens echo in MM plug-in.
A flag is added in the MM plug-in, so that the ModemManager can uninhibit after the fastboot flash ends, so that the modem can be found again.
> Added support for Fibocom 0x2cb7, and fixes for two issues

- contrib/debian/fwupd.install
- contrib/debian/rules
- contrib/fwupd.spec.in
- data/motd/fwupd-refresh.preset
- data/motd/meson.build
- meson.build
contrib/fwupd.spec.in: Follow presets for fwupd-refresh.timer
Ensure that the fwupd-refresh.timer unit is enabled/disabled on
install/update/removal according to the global systemd presets.
See: https://src.fedoraproject.org/rpms/fedora-release/pull-request/279
See: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd
---
Remove fwupd-refresh.preset
Fedora, CentOS Stream, openSUSE and Debian remove or wants to remove
this preset as it either enabled by default or managed somewhere else.
For example, Fedora disables all units, that have not been explicitly
enabled, by default in [1] which is part of the fedora-release package
[2].
Thus we don't need to explicitly disable those units here.
This is potentially an important change as it will enable those units on …
> Remove fwupd-refresh.preset & contrib/fwupd.spec.in: Follow presets for fwupd-refresh.timer

- plugins/modem-manager/fu-mm-device.c
ModemManager does not use the QCDM port in newer modems for anything, so ModemManager was only opening it, probing it for QCDM, closing it and setting the port type to IGNORED.
So for devices that use QCDM for upgrading, it is necessary to separately determine the port.
- [-] Code fix
> Quectel: Fix the issue of not being able to upgrade through QCDM ports

- data/cfi.quirk
1. rearrange PM25LD010 to correct .
2. add PM25Lx512x / MX25V2035F / W25X20.X
> add supporting flash in cfi.quirk

- plugins/synaptics-cape/fu-synaptics-cape-device.c
For factory firmware (v8.41.16.0) EPOS ADAPT 1x5 requires the delay about 140ms to get report after sending the firmware header to the device. Having no delay at all preventing new devices to update with error "failed to get GET_REPORT: failed to GetReport: transfer timed out".
Adding 150ms delay (+30ms for GET_REPORT) for the command should give enough time for the device to be prepared for firmware writing.
> synaptics-cape: add delay for header write

- plugins/test/fu-test-plugin.c
- src/fu-engine.c
- src/fu-self-test.c
I'm not sure we were sorting by release version, but it makes much more sense to sort by device order first.
> Sort composite updates by the device order

- contrib/build-windows.sh
- contrib/ci/build_windows.sh
- libfwupd/fwupd-client.c
- meson.build
- meson_options.txt
- src/fu-main.c
We need this on Windows and macOS -- although both platforms might have a system bus in the future.
> Add -Ddbus_p2p=true to always use a D-Bus TCP socket

- meson.build
- meson_options.txt
I've had to patch this for RHEL 8 and now also Homebrew, so lets just provide an escape hatch.
> Allow specifying the path to python during configure

- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
PR introduces configuration channel peers cache functionality support. The peers cache allows host tools to get informed about the state of nRF Desktop peripherals connected through dongle without need of complete rediscovery.
The PR also introduces a few small changes needed to integrate the peers cache functionality.
> plugins: nordic-hid: Add peers cache support

- plugins/logitech-scribe/meson.build
- plugins/logitech-tap/meson.build
This fixes a compile error when compiling with -Dgudev=disabled.
> trivial: Require GUdev for logitech-scribe and logitech-tap

- plugins/modem-manager/modem-manager.quirk
quectel's new EM160 module PCIe ID joins fwupd
> quectel:Add device ID and support for EM160 module

- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
Genesys GL32XX devices are USB card readers, so using the deepest "usb" node in the udev tree effectively allows to register multi-LUN devices.
Still need to check the partitions to avoid the device de-registration in case if user remove the SD-card.
> genesys-gl32xx: set physical id based on USB subsystem

- plugins/elantp/fu-elantp-hid-device.c
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2238139
> elantp: Fix an unset i2c device name

- plugins/wacom-usb/wacom-usb.quirk
Adding new pids to the wacom quirks file to support two new tablets.
> Adding support for new DTH134 & DTC121 Tablets

- libfwupdplugin/fu-udev-device.c
No in-tree user currently cares about the GError.code and so no regressions should be possible.
> Set more specific GError codes for FuUdevDevice pread() and pwrite()

- libfwupd/fwupd-client-sync.h
- libfwupd/fwupd-client.h
- libfwupd/fwupd-common.h
- libfwupd/fwupd-release.h
- libfwupd/fwupd-remote-private.h
- libfwupd/fwupd-remote.h
Even the docs say `G_DEPRECATED_FOR(...)` must be before the return type.
> trivial: Make usable under Visual Studio

- meson.build
- subprojects/passim.wrap
This improves the experience of using passim with fwupd. We want to make sure that it's only used with a new enough stack. Link: https://github.com/fwupd/fwupd/issues/6022
> trivial: Bump minimum passim version to 0.1.2

- plugins/mediatek-scaler/README.md
- plugins/mediatek-scaler/fu-mediatek-scaler-common.c
- plugins/mediatek-scaler/fu-mediatek-scaler-common.h
- plugins/mediatek-scaler/fu-mediatek-scaler-device.c
- plugins/mediatek-scaler/fu-mediatek-scaler-device.h
- plugins/mediatek-scaler/fu-mediatek-scaler-firmware.c
- plugins/mediatek-scaler/fu-mediatek-scaler-firmware.h
- plugins/mediatek-scaler/fu-mediatek-scaler-plugin.c
- plugins/mediatek-scaler/fu-mediatek-scaler-plugin.h
- plugins/mediatek-scaler/fu-mediatek-scaler.rs
- plugins/mediatek-scaler/meson.build
- plugins/meson.build
```
$ fwupdmgr.sh get-devices
├─Display Controller:
│     Device ID:          38bc943b48062efd204e45e616141717fc6331f1
│     Summary:            Mediatek Display Controller
│     Current version:    2.1.6
│     Vendor:             Mediatek (PCI:0x1028)
│     GUID:               82c3d3fe-f299-599f-b4df-c96a26898064 ← DISPLAY\VID_1028&PID_0C8A&HWVER_2.1.2.1
│     Device Flags:       • Internal device
│                         • Updatable
│                         • Cryptographic hash verification is available
│                         • Unsigned Payload
```
> mediatek-scaler: new plugin to support dp aux display

- data/bash-completion/fwupdmgr
- data/bash-completion/fwupdtool
- libfwupd/fwupd-client-sync.c
- libfwupd/fwupd-client-sync.h
- libfwupd/fwupd-client.c
- libfwupd/fwupd-client.h
- libfwupd/fwupd-enums-private.h
- libfwupd/fwupd-security-attr.c
- libfwupd/fwupd-security-attr.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-kernel.c
- libfwupdplugin/fu-kernel.h
- libfwupdplugin/fu-plugin-private.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-plugin.h
- libfwupdplugin/fu-security-attr.c
- plugins/iommu/fu-iommu-plugin.c
- plugins/linux-lockdown/fu-linux-lockdown-plugin.c
- policy/org.freedesktop.fwupd.policy.in
- src/fu-daemon.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-tool.c
- src/fu-util.c
- src/org.freedesktop.fwupd.xml
The idea here is that rather than limiting ourselves to setting BIOS values to fix HSI attributes, we can do per-plugin actions such as setting kernel command line options.
Add two new:
* flags for FwupdSecurityAttr
* client helpers
* PolicyKit rules
* D-Bus methods and plugin vfuncs
Then teach the iommu and linux-lockdown plugins how to set kernel arguments.
This also benefits automation frameworks such as Ansible and puppet; the framework can call the repair functions with just the AppStream ID.
Heavily based on patches by Kate Hsuan <hpa@redhat.com>, many thanks.
> Add functionality to fix specific host security attributes

- plugins/thunderbolt/thunderbolt.quirk
This reverts commit 96012791a26f5694627f11a2fda08b9a2e3dd0b0.
-enable thunderbolt retimer offline mode for rex
- [ x] Feature
> Revert "thunderbolt: disable retimer offline mode for rex"

- libfwupdplugin/fu-udev-device.c
- plugins/optionrom/fu-optionrom-device.c
This will allow other plugins that replace optionrom to be able to dump firmware too.
> Move firmware dumping out of optionrom into udev

- src/fu-engine.c
The current code failed to detect firmware updates coming from a vendor directory if the update was not for the top-level device but for a child device.
In the specific case a Thunderbolt dock had the following guid:
- 8d30b09f-bcc5-5379-bc65-9ccceeece1f4 ← USB\VID_17EF&PID_30B4
- 275e4695-9b4e-5263-835e-8681bec8cd1a ← USB\VID_17EF&PID_30B4&CID_40B0
- 57e1b971-662a-5c9d-b500-69ce8ee3ad99
and the update was available for 275e4695-9b4e-5263-835e-8681bec8cd1a.
The method GetUpgrade returned the firmware update but the flag FWUPD_DEVICE_FLAG_SUPPORTED was not set for the device.
The tool "fwupdmgr get-updates" checks he FWUPD_DEVICE_FLAG_SUPPORTED flag before even considering calling GetUpgrades for any device. So it failed to output the available update even though the fwupd itself updated …
> fu-engine: Recalculate FWUPD_DEVICE_FLAG_SUPPORTED after adopting child

- meson.build
- plugins/amd-gpu/meson.build
Fixes: https://github.com/fwupd/fwupd/issues/6246
> trivial: Explicitly look for `AMDGPU_INFO_VBIOS_INFO` to enable amd-gpu plugin

- plugins/vli/fu-vli-pd-device.c
- plugins/vli/fu-vli-usbhub-device.c
- plugins/vli/fu-vli-usbhub-msp430-device.c
If we're loading using mmap() then the process will crash if the buffer is modified as it really is read-only.
> vli: Do not treat an immutable buffer as a mutable one

- libfwupdplugin/fu-drm-device.c
- libfwupdplugin/fu-drm-device.h
- libfwupdplugin/fu-edid.c
Also, construct plausible GUIDs using the EDID if connected and enabled.
> trivial: Cache the DRM properties at ->probe()

- plugins/dfu/fu-dfu-target-avr.c
- plugins/dfu/fu-dfu-target-private.h
- plugins/dfu/fu-dfu-target-stm.c
- plugins/dfu/fu-dfu-target.c
I was checking the DFU backend to see if it was doing anything dumb with the immutable buffer and found a few other things that needed fixing instead.
> dfu: Use modern byte array functions for targets

- plugins/wacom-raw/README.md
- plugins/wacom-raw/fu-wacom-raw-plugin.c
This allows us to recover some panels that have accidentally may been flashed with the wrong firmware that changed the device DEV number. Using the three digit `PNP_ID` (which is constructed from the 2-byte manufacturer name) means we can get the user back to the correct firmware stream.
It's not ideal that we can't go from the sysfs hidraw node to the drm device with the EDID, but we do know there is only going to be one "internal" panel.
> wacom-raw: Add the PNP ID as a additional instance ID

- data/bash-completion/fwupdtool
- docs/fwupd.conf.md
- libfwupdplugin/fu-plugin-private.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-plugin.h
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-capsule/fu-uefi-device.c
- src/fu-engine.c
- src/fu-engine.h
- src/fu-tool.c
This should not be required, but then some firmware is broken.
Fixes https://github.com/fwupd/fwupd/issues/5938
> Delete BootNext as a post-reboot action

- plugins/vli/README.md
- plugins/vli/fu-vli-pd-device.c
- plugins/vli/vli-luxshare.quirk
We would like to add a private flag for PDs to skip ROM mode in the detach function. Testing in progress. Thanks!
> vli: add private flag, still testing

- plugins/thunderbolt/fu-thunderbolt-controller.c
When the thunderbolt or USB4 controller is integrated into the SoC
upgrades for applicable firmware are distributed as part of the platform.
The kernel doesn't export any type of version string in this instance so
there isn't really any reason for fwupd to both creating a device.
> trivial: thunderbolt: stop creating integrated devices

- contrib/PKGBUILD
- contrib/ci/dependencies.xml
- contrib/fwupd.spec.in
- meson.build
- plugins/amd-gpu/fu-amd-gpu-device.c
- plugins/amd-gpu/meson.build
- plugins/meson.build
I think this is the cleaner solution - it means we never need to be updating the header copy locally if we keep using future ioctls.
Fixes: #6266
> trivial: discover libdrm, and ensure it has amdgpu support using pkgconfig

- libfwupdplugin/fu-udev-device.c
Only the PCI VID/PID is disallowed from being 0xFFFF -- and in that case it would be hidden from the kernel anyway. The generic helpers should allow the maximum value to avoid a spurious console warning on some devices.
> trivial: Allow PCI devices to have 0xFFFF.. values

- snap/snapcraft.yaml
For meson upgrades to work, pip must be installed too.
> trivial: snap: make meson upgrades work

- libfwupdplugin/fu-usb-device.c
We won't retry for `_NO_DEVICE` or `_PERMISSION_DENIED` thanks to the NULL callback specified in `fu_device_retry_add_recovery()`.
> Retry claiming the USB interface if the device returns BUSY

- docs/hsi-tests.d/meson.build
- docs/hsi-tests.d/org.fwupd.hsi.Amd.RollbackProtection.json
The documentation didn't match the #define.  Adjust documentation to match.
> trivial: Adjust AMD rollback protection to be consistent

- plugins/emmc/README.md
- plugins/emmc/emmc.quirk
- plugins/emmc/fu-emmc-device.c
- plugins/emmc/fu-emmc-plugin.c
- plugins/emmc/meson.build
Here is v3 of this change.  This pull request contains few code fixes:
emmc: Check ffu features support: Only devices that support EXT_CSD_FFU_FEATURES should be checked for sectors done.
emmc: let FFU use close-ended mode - use the much-more efficient close-ended mode instead of open-ended.
emmc: Add emmc quirk - Allow to use different chunk size, and add some wdc devices that needs it.
Thanks,
Avri
> eMMC plugin changes - v3

- src/meson.build
Using meson.project_source_root() means the path emitted to include .h files are absolute, which is not going to work if the -src package was used to re-build fwupd in a different build path.
> trivial: Avoid absolute buildtime paths in generated headers

- plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-common.c
- plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-common.h
- plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
This fixes:
java.lang.IllegalArgumentException: Timezone: GMT is not an Olson ID
> logitech-bulkcontroller: Send the Olson location rather than the timezone

- docs/hsi.md.in
- libfwupdplugin/fu-security-attrs.c
- plugins/cpu/fu-cpu-device.c
- plugins/pci-mei/fu-pci-mei-plugin.c
- plugins/pci-psp/fu-pci-psp-device.c
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util.c
This is a follow up from the various bugs that complain about unable to discover security attributes.  It flips the way that the CPU attribute works so that if PCI-PSP is missing it will continue to show all the attributes but with `Failed` instead of `HSI:INVALID:missing-data`
 Type of pull request:
> Drop `HSI:INVALID:missing-data`

- plugins/wacom-usb/wacom-usb.quirk
Also remove dash ("-") typo from Cintiq Pro 27 (DTH271).
- [x ] add new devices to quirks file
> wacom-usb: Define quirks for new Wacom Cintiq Pros (DTH172, DTH227)

- plugins/genesys-gl32xx/README.md
- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
To identify customer device the pair VER and CID must be used. The GUID based on CID only is redundant and dangerous, so removing it.
> genesys-gl32xx: remove GUID based on CID only

- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
The GUID for "HIDRAW\VEN_1915" is added to HID peripherals connected through a dongle only to apply quirks. Do not display it.
> plugins: nordic-hid: Do not display GUID for "HIDRAW\VEN_1915"

- libfwupdplugin/fu-dpaux-device.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
This fixes a regression in mediatek_scaler which does not implement OUI data. The Synaptics MST plugin already checks for a specific OUI value anyway.
> Do not require a IEEE OUI to set up a DP AUX device

- plugins/amd-gpu/fu-amd-gpu-device.c
The intent should be to match to board IDs that were probed from the driver.
This doesn't actually work though for udev devices AFAICT; it seems like it's because the IDs were already added before the derived plugin runs.  I'd think this problem actually affects all the udev based  #plugins.
Here's a log of `sudo fwupdtool get-devices --plugins amd-gpu -vv` on a system:
https://dpaste.com/7Y8JP349J
@hughsie feel free to add commits to the branch to fix the underlying issue.
> trivial: amd-gpu: don't allow PCI generic GUIDs

- plugins/modem-manager/README.md
- plugins/modem-manager/fu-mm-device.c
This allows us to downgrade the firmware to get the correct carrier config.
Use a flag so that devices can 'opt-in' without having to have a flag-day on the LVFS for existing modem firmware.
> modem-manager: Optionally set the carrier configuration as the branch name

- plugins/amd-gpu/fu-amd-gpu-device.c
The model name on some dGPUs isn't really user friendly, it's better to default to the udev database for the name and instead show the description with model name info.
> trivial: amd-gpu: move name to description field

- plugins/vli/vli-luxshare.quirk
Fixed Luxshare quirk file for quad dock and added 7-in-1 hub. 
Additionally, do you remember the condition we set for `has-shared-spi-pd`? Currently I'm testing a VL822 hub with shared-SPI VL105 PD and the VL105 PD --without billboard endpoint-- is not appearing in `./fwupdtool get-devices`. For a different hub share-SPI pd device, the VL103 PD --without billboard endpoint-- does appear in `./fwupdtool get-devices`.
> vli: fix quirk

- libfwupdplugin/README.md
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- libfwupdplugin/fu-smbios.c
- libfwupdplugin/fu-smbios.h
- plugins/dell/fu-dell-plugin.c
- plugins/flashrom/fu-flashrom-plugin.c
- plugins/redfish/fu-redfish-plugin.c
- plugins/redfish/fu-redfish-smbios.c
- plugins/redfish/fu-redfish-smbios.h
- plugins/redfish/fu-redfish.rs
- plugins/uefi-capsule/fu-uefi-backend-linux.c
The reason we did not do this before is that the libfwupdplugin API only gave us the first entry. As it's perfect valid to have more than one table with the same structure type, return a list and allow the caller to filter them.
Fixes https://github.com/fwupd/fwupd/issues/6348
> redfish: Parse all the type 42 SMBIOS tables

- src/fu-security-attr-common.c
> trivial: Fix two tiny memory leaks when getting HSI descriptions

- generate-build/generate-quirk-builtin.py
Python script `generate-build/generate-quirk-builtin.py` uses `gzip` to generate the `builtin.quirk.gz` artifact during building. A timestamp is appended to the file, making fwupd unreproducible as can be seen by the diffoscope log here:
https://reproducible.archlinux.org/api/v0/builds/534033/diffoscope
Until `gzip.open()` supports `mtime` (see python/cpython#91372), I suggest using `gzip.GZipFile()` instead with `mtime=0`. This generates the same file without embedding a timestamp, making the fwupd reproducible (at least in Arch Linux).
> Remove timestamp from gzip to achieve reproducible build

- plugins/synaptics-mst/README.md
- plugins/synaptics-mst/fu-synaptics-mst-device.c
This is super slow -- the synaptics MST probes are the slowest thing in fwupd startup -- and we have to probe four relative adresses on each disovered layer. The real problem is we have never actually used the discovered remote devices!
Add a flag to stop the cascade scanning until we can rework the plugin to actually add them as child devices. I'm working with Synaptics to actually do that, although it's going to take a bit longer to complete.
> synaptics-mst: Disable scanning for cascade devices

- src/fu-engine-config.c
If a plugin is specified using a `-` character replace it inline with `_` so that users can disable plugins that match the name of the directory instead of needing to know the project internally uses `_`.
> trivial: Allow using `-` in `DisabledPlugins`

- libfwupd/fwupd-bios-setting.h
- libfwupd/fwupd-device.h
- libfwupd/fwupd-plugin.h
- libfwupd/fwupd-release.h
- libfwupd/fwupd-remote.h
- libfwupd/fwupd-report.h
- libfwupd/fwupd-request.h
- libfwupd/fwupd-security-attr.h
This means we get a compile warning when typoing fwupd_device_has_flag() instead of fwupd_device_add_flag().
> trivial: Use G_GNUC_WARN_UNUSED_RESULT when using _has_

- libfwupd/fwupd-client.c
The GSource is ref'd in g_source_attach_unlocked().
> trivial: Fix a tiny memory leak when using fwupdtool get-devices

- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fu-usb-device.h
- plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
This regressed the Hughski ColorHug plus test in 94eea8.
> Only use the USB open-retry behaviour when required

- plugins/linux-swap/fu-self-test.c
- plugins/redfish/fu-redfish-network.c
Fixes some of https://github.com/fwupd/fwupd/issues/6418
> trivial: Handle G_DBUS_ERROR_NAME_HAS_NO_OWNER in the self tests

- src/fu-polkit-agent.c
`strerror` takes the `errno` directly as its argument, negating it will result in an "Unknown error".
> trivial: Fix incorrect usage of `strerror`

- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-string.c
- libfwupdplugin/fu-string.h
- src/fu-debug.c
This keeps being pasted to public places like GitHub -- copy what curl does.
> Hide HTTP passwords in fwupd debugging logs

- plugins/vli/fu-vli-pd-device.c
Change the check flag "SKIPS_ROM" position.
If we want to skips jumping to rom, we should keep the original FW settings of GPIOS,
So move the  check position to the front.
> vli:pd_skips_rom

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-progress.c
- libfwupdplugin/fu-progress.h
- libfwupdplugin/fu-progress.rs
- libfwupdplugin/meson.build
- libfwupdplugin/rustgen.py
- src/fu-daemon.c
If the frontend quits or crashes then there is nothing that is able to handle the interactive request. This means that fwupd would wait for potentially a few minutes blocking all other requests until timing out.
> Do not send requests when the sender is no longer alive

- plugins/amd-gpu/fu-amd-gpu-device.c
While trying to fix a casting error, I accidentally broke 64 bit return addresses entirely.
Fixes: 5bb7ab869 ("trivial: amd-gpu: fix a casting error on 32 bit x86")
> amd-gpu: Fix probing mistake

- plugins/vli/fu-vli-usbhub-device.c
Added a 1 ms delay to wait for the completion of PUYA SPI flash writing data.
To patch firmware issue exposing the USB3 hub, need to wait for some time for the firmware stable before sending vendor-commands.
> vli:7-in-1 dongle

- libfwupdplugin/fu-security-attrs.c
We already start the HSI level at zero, and set it on success -- just abort on failure.
Fixes some of https://github.com/fwupd/fwupd/issues/6454
> Never show a HSI index that is impossible

- docs/fwupdplugin.toml.in
This looks like a miss from before when it was introduced and fixes a 404 on fwupd.github.io.
> trivial: create HTML docs for device emulation

- plugins/cpu/fu-cpu-device.c
- plugins/pci-mei/fu-pci-mei-plugin.c
- plugins/pci-psp/fu-pci-psp-device.c
- src/fu-engine.c
Add the org.fwupd.hsi.SupportedCpu HSI attr early in the engine -- it's always needed and we can just find it then set 'success' in each plugin.
This means we don't have to do complicated rebasing of obsoleted attributes.
> Never obsolete the wrong HSI attribute

- plugins/vli/fu-vli-usbhub-device.c
When VLI hub receives a reset command, it immediately resets itself without completing the control transfer command. So this timeout error is possible and we should ignore it.
> vli:reset_timeout

- contrib/debian/fwupd.install
This is already handled by debian/rules.
Link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057241
> trivial: debian: drop udev rules line in fwupd.install

- libfwupd/fwupd-build.h
If we've been over-eager we don't want the release builds to explode.
> trivial: Only define G_GNUC_NON_NULL for non-SUPPORTED builds

- src/fu-cabinet-common.c
- src/fu-cabinet.c
- src/fu-cabinet.h
- src/fu-engine.c
It can fail if the archive is not loaded, so set an error.
> trivial: Add a GError to fu_cabinet_get_silo()

- docs/meson.build
Fixes a series of warnings:
```
WARNING: Section aliases raised Invalid version: 'main'
WARNING: Section bitfields raised Invalid version: 'main'
WARNING: Section enums raised Invalid version: 'main'
WARNING: Section functions raised Invalid version: 'main'
WARNING: Section domains raised Invalid version: 'main'
WARNING: Section function_macros raised Invalid version: 'main'
WARNING: Section constants raised Invalid version: 'main'
WARNING: Section classes raised Invalid version: 'main'
```
> trivial: Always use project version for docgen

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Fixes https://github.com/fwupd/fwupd/issues/6035
> uefi-capsule: Prefer esp volumes over msftdata when choosing the default

- libfwupdplugin/fu-volume.c
This would have helped in https://github.com/coreos/fedora-coreos-tracker/issues/1623
> trivial: Make the error more helpful when setting EspLocation=/dev/vda2

- libfwupdplugin/fu-composite-input-stream.c
- libfwupdplugin/fu-composite-input-stream.h
- libfwupdplugin/fu-partial-input-stream.c
- libfwupdplugin/fu-partial-input-stream.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.h
- libfwupdplugin/meson.build
The idea here is that we can have a linear stripe of GInputStreams that create one virtual stream. This allows us to stream from 'segmented' archive formats, for example where one cabinet archive actually has hundreds of little blocks of uncompressed data, each with a pre-parsed header.
> Add FuCompositeInputStream for future use

- src/fu-engine.c
If the flashed version doesn't match version read from the CAB file, the upgrade must fail.
Fixes https://github.com/fwupd/fwupd/issues/6513
> Fail the update if version doesn't match expected

- libfwupdplugin/fu-dfu-firmware.rs
- libfwupdplugin/fu-efi.rs
- libfwupdplugin/fu-rustgen-struct.c.in
- libfwupdplugin/rustgen.py
Also, in some cases plugins were using validate to check for buffer correctness, so don't optimize that away even if there are no constants to check.
> trivial: Correctly validate structures of structures in all cases

- libfwupdplugin/fu-mei-device.c
It appears the `fu_mei_device_write` function intends to have a 200ms timeout. However, it actually ends up with a 200s timeout because of a miscalculation on timing. (1 millisecond = 1000 microseconds, not 100000 microseconds).
With this miscalcuation, `fwupd` hangs when running. This makes all `fwupdmgr` commands fail as they have a 25 second timeout.
> Fix miscalculation `fu_mei_device_write` timeout

- plugins/redfish/README.md
- plugins/redfish/fu-redfish-device.c
- plugins/redfish/fu-redfish-device.h
- plugins/redfish/fu-redfish-plugin.c
- plugins/redfish/redfish.quirk
It reboots automatically.
Based on a patch by Vincent Tang <vincent.tang@advantech.com.tw>, many thanks.
Fixes https://github.com/fwupd/fwupd/issues/6536
> redfish: Do not request the Advantech BMC to reboot

- contrib/ci/dependencies.xml
It's not built for this architecture.
> trivial: debian: don't install valgrind on loong64

- libfwupdplugin/meson.build
Parallel builds sometimes fail due to a header not having been generated yet. Fix by adding fwupdplugin_rs_dep to the deps for fwupdplugin-self-test.
The build error can be reliably reproduced like so:
```
$ meson setup build
$ cd build
$ ninja libfwupdplugin/fwupdplugin-self-test.p/fu-self-test.c.o
[...snip...]
In file included from ../libfwupdplugin/fu-archive-firmware.h:10,
from ../libfwupdplugin/fwupdplugin.h:13,
from ../libfwupdplugin/fu-self-test.c:11:
../libfwupdplugin/fu-archive.h:12:10: fatal error: fu-archive-struct.h: No such file or directory
12 | #include "fu-archive-struct.h"
|          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
> Add missing build dependency to fwupdplugin-self-test

- plugins/synaptics-mst/README.md
- plugins/synaptics-mst/fu-synaptics-mst-device.c
- plugins/synaptics-mst/synaptics-mst.quirk
> synaptics-mst: Add support for the Luxshare Quad USB4 Dock

- libfwupdplugin/fu-mei-device.c
- plugins/pci-psp/fu-pci-psp-device.c
In order to populate security attributes it will be required to still exist.
Fixes: https://github.com/fwupd/fwupd/issues/6576
> trivial: keep udev object around for PSP and MEI devices

- libfwupdplugin/fu-cab-firmware.c
See https://github.com/zlib-ng/zlib-ng/issues/1624
> Fix a segfault when using zlib-ng instead of zlib

- plugins/synaptics-mst/fu-synaptics-mst-device.c
- plugins/synaptics-mst/fu-synaptics-mst-firmware.c
- plugins/synaptics-mst/fu-synaptics-mst-firmware.h
- plugins/synaptics-mst/fu-synaptics-mst-plugin.c
- plugins/synaptics-mst/fu-synaptics-mst.rs
Get the device family from firmware file, using the hardware if possible.
> synaptics-mst: Add board ID firmware offset for Cayenne and Spyder

- libfwupdplugin/fu-hid-descriptor.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65454
> trivial: Set a maximum size for a HID descriptor

- libfwupdplugin/README.md
- libfwupdplugin/fu-dpaux-device.c
- libfwupdplugin/fu-i2c-device.c
- libfwupdplugin/fu-mei-device.c
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- plugins/amd-gpu/fu-amd-gpu-device.c
- plugins/android-boot/fu-android-boot-device.c
- plugins/ata/fu-ata-device.c
- plugins/elantp/fu-elantp-hid-device.c
- plugins/elantp/fu-elantp-i2c-device.c
- plugins/focalfp/fu-focalfp-hid-device.c
- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
- plugins/goodix-tp/fu-goodixtp-hid-device.c
- plugins/gpio/fu-gpio-device.c
- plugins/kinetic-dp/fu-kinetic-dp-device.c
- plugins/logitech-rallysystem/fu-logitech-rallysystem-audio-device.c
- plugins/logitech-tap/fu-logitech-tap-hdmi-device.c
- plugins/logitech-tap/fu-logitech-tap-sensor-device.c
- plugins/mtd/fu-mtd-device.c
- plugins/nvme/fu-nvme-device.c
- plugins/optionrom/fu-optionrom-device.c
- plugins/pci-bcr/fu-pci-bcr-plugin.c
- plugins/pci-mei/fu-pci-mei-plugin.c
- plugins/scsi/fu-scsi-device.c
- plugins/synaptics-mst/fu-synaptics-mst-device.c
- plugins/synaptics-rmi/fu-synaptics-rmi-ps2-device.c
- plugins/tpm/fu-tpm-device.c
- src/fu-udev-backend.c
Old versions of fwupd used to start with OPEN_READ|OPEN_WRITE and then plugins would set the new flags to be correct. This doesn't work very well when there are subclassed devices that want to *inherit* flags, rather than having to set all the same flags as the baseclass.
> Allow subclassed devices to *add* rather than *replace* FuUdevDevice open flags

- plugins/goodix-moc/fu-goodixmoc-device.c
- plugins/goodix-moc/goodixmoc.quirk
The factory firmware for the goodixmoc fingerprint readers appears to have a bug that it doesn't come back after an update even when succesful.
As this is "expected" behavior set the will-disappear and needs-reboot flags so this isn't flagged as a failure.
Link: https://community.frame.work/t/beta-lvfs-fingerprint-reader-firmware-for-framework-laptop-13-13th-gen-intel-core-amd-7040-series-fingerprint-reader-on-fedora-39-and-ubuntu-22-04/41898
> trivial: set fingerprint reader in Framework laptops as will-disappear

- plugins/bcm57xx/fu-bcm57xx-device.c
- plugins/bcm57xx/fu-bcm57xx-plugin.c
- plugins/bcm57xx/fu-bcm57xx-recovery-device.c
- plugins/bcm57xx/fu-bcm57xx-recovery-device.h
In most cases mmap is blocked by the CONFIG_IO_STRICT_DEVMEM config option.
This means we now need a system reboot for updates to take effect.
Fixes https://github.com/fwupd/fwupd/issues/6243
> bcm57xx: Never use /dev/mem when not in recovery mode

- libfwupdplugin/fu-device.c
- plugins/dfu/fu-dfu-common.h
- plugins/dfu/fu-dfu-device.c
The flag was duplicated, and we were setting the _internal_ flag in the jabra plugin, and checking the _private_ flag in the dfu plugin.
Fixes https://github.com/fwupd/fwupd/issues/5381
> jabra: Fix installing to Jabra 410, 510, 710 and 810 devices

- plugins/uefi-capsule/fu-uefi-common.c
`__loongarch64` is no longer used for historical reasons and should be replaced by `__loongarch_lp64` in new code.
https://loongson.github.io/LoongArch-Documentation/LoongArch-toolchain-conventions-EN.html#_cc_preprocessor_built_in_macro_definitions
> LoongArch: Replace __loongarch64 with __loongarch_lp64

- contrib/setup
Some distros don't configure a path for `/usr/local` by default. This makes developing fwupd a bit harder for new contributors especially when a libfwupd ABI bump has occurred.
We can either make wrappers for people to use (like `contrib/vscode/build.sh`) or we can try to set up sane defaults for people who run `meson build; ninja -C build`.
This sets up the latter.
> trivial: Update `contrib/setup` to configure the library search path

- plugins/amd-gpu/fu-amd-gpu-device.c
As APUs will also use the libdrm libraries to get a device name, set the udev flags for them too.
> trivial: amd-gpu: set udev flags on APUs too

- libfwupdplugin/fu-config.c
- libfwupdplugin/fu-plugin.c
Spotted by Coverity, although impossible to hit in practice.
> trivial: Fix an off-by-one error when using old GLib versions

- libfwupd/fwupd-security-attr.c
- src/fu-engine.c
This essentially reverts commit fa97f360e0a478344d5acf1728d2338b6f420cfa, and for an unsupported CPU we now show a failure of "Unknown".
Fixes https://github.com/fwupd/fwupd/issues/6603
> Correctly mark the CPU as supported, harder

- libfwupd/fwupd-client.c
As the remote is being enabled for the very first time, there won't yet be a checksum to compare. Check that there is actually a checksum before trying to fetch it and compare it.
> Fix an assertion when enabling lvfs-testing for the first time

- data/motd/meson.build
This should help point out possible pitfalls for the systemd bug.
> trivial: add a meson warning for DynamicUser

- libfwupdplugin/fu-input-stream.c
- libfwupdplugin/fu-input-stream.h
- plugins/vli/fu-vli-pd-firmware.c
This regressed in 62f6f19d.
Found by Comic Cho, many thanks.
> vli: Fix a regression when calculating the PD firmware CRC

- libfwupdplugin/fu-volume.c
The caller in `fu_efi_hard_drive_device_path_new_from_volume()` will fall back to `BLOCK_SIZE_FALLBACK` and show a warning.  If a way to get the block size for a random path is introduced later we can clean up that warning at that point.
Fixes: https://github.com/fwupd/fwupd/issues/6638
> Avoid crashing the daemon if not using udisks to check for size

- plugins/pci-psp/fu-pci-psp-device.c
pci-psp security attributes are funneled through the ccp driver but are system wide attributes that should only nominally be populated on the first system PCI PSP device.
If more than one ccp device was found then check if it was missing data to decide how to handle it:
* If missing data, try to load data from a second CCP device
* If populated data succesfully, then don't clear it.
* If populated data but not successfully then try to read it from second device.
Fixes: https://github.com/fwupd/fwupd/issues/6601
> pci-psp: Handle systems with more than one ccp device

- plugins/cpu/fu-cpu-device.c
AMD systems don't require IBT to mark CET available, but also it's wrong to check the same logic in multiple places.  Instead look up whether the CET platform attribute was enabled.
> cpu: Show "CET OS support" on AMD systems too

- contrib/snap/snapcraft.yaml
This will allow installing CAB files downloaded locally to the home directory.
> snap: Enable access to the home interface

- src/fu-util.c
```
This tool can add a kernel argument of '(null)', but it will only be active
after restarting the computer.
```
> trivial: Fix lockdown message

- .github/workflows/snap.yml
1.9.x releases will be on 1.9.x track, 2.0 will be on latest track.  When we start a 2_0_X branch and main moves to 2.1.x we'll open a 2.0.x track at that time too.
This reverts commit d1e895dc94c45dbe17901ac33c89d709770e900c. 
Fixes: https://github.com/fwupd/fwupd/issues/5804
> trivial: snap: Promote 1.9.x release to the 1.9.x channel

- src/fu-engine.c
This stops us switching the device state from DEVICE_BUSY to DEVICE_WRITE before the device has come back.
> Do not change the device status until the action has completed

- plugins/aver-hid/README.md
- plugins/aver-hid/fu-aver-safeisp-device.c
> aver-hid: a polling function is unnecessary in safeisp

- contrib/build-venv.sh
- contrib/setup
If the host OS has EFI binaries, try to symlink them into the fwupd dev venv environment.  This should let updates with secure boot work.
> Allow UEFI updates to work from venv

- libfwupdplugin/fu-device.c
- src/fu-self-test.c
This ensures that the update does not show up in any program that just gets the device list and checks for the updatable flag.
> Add a device problem when the device needs a reboot

- libfwupd/fwupd-client.c
- src/fu-util.c
fwupdmgr has the ability to restart the daemon itself by using `fu_util_quit` to stop it and dbus activation to start it again.
Use that instead.
> Don't require systemd for `modify-config`

- meson_options.txt
In commit 17037db4017920edda6c0917ffa881704a992205 we said that we would turn it off in about a year.
> trivial: disable thinklmi compat by default

- .gitignore
- contrib/snap/fwupd-command
- contrib/snap/fwupd.wrapper
- contrib/snap/fwupdmgr.wrapper
- contrib/snap/fwupdtool.wrapper
- contrib/snap/snapcraft.yaml
- libfwupdplugin/fu-path.c
- src/fu-engine.c
Hodge podge of snap related improvements to shrink size, and to set up directory structure to carry info from one snap to another.
Some of these should have done when first confined, but better now than never.
Also the directory remote is now accessible from host at `/var/snap/fwupd/share/fwupd/remotes.d/vendor/firmware`
CC @CragW 
> Some snap improvements

- contrib/fwupd.spec.in
- contrib/snap/snapcraft.yaml
- data/remotes.d/README.md
- data/remotes.d/meson.build
- meson_options.txt
This is useful for OStree or ChromeOS, but not for all other Linux. Add a meson option for it, but disable it by default.
> Disable the vendor remote by default

- .github/workflows/snap.yml
- contrib/debian/fwupd-tests.install
- contrib/fwupd.spec.in
- contrib/snap/snapcraft.yaml
- data/installed-tests/fwupd.test.in
- data/installed-tests/fwupdtool.sh
- data/installed-tests/fwupdtool.test.in
- data/installed-tests/meson.build
This also moves the snap CI to use `modify-config` to change plugins and adds a separate installed test for building and using a CAB file.
> Run ALL installed-tests in the snap

- src/fu-systemd.c
- src/fu-systemd.h
- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
The purpose of all of this code was to make sure that the correct unit was launched when the snap was installed.  There are two issues:
1. The confined snap isn't allowed to access this information so it's dead code now.
2. The snap daemon will prevent starting the snap version if a host version is already installed with this message: "snap.fwupd.fwupd.service: Two services allocated for the same bus name org.freedesktop.fwupd, refusing operation."
Drop the dead code.
> trivial: drop systemd unit detection

- docs/fwupd.conf.md
- docs/meson.build
- meson.build
- meson_options.txt
- src/fu-engine-config.c
Distributions and packagers that want to offer the feature but turn it off by default can do so.
This will also then be a one line change to change the upstream default if we flip to *metadata,firmware* in the future. 
Link: https://github.com/fwupd/fwupd/issues/6721
> Make the default p2p policy configurable by a meson option

- src/fu-engine.c
- src/fu-self-test.c
The UEFI capsule plugin actually sets the default to be `NUMBER` rather than `UNKNOWN`. We check for the 'same' value in fu_device_set_version_format() and so there's no penalty in always setting it to the current value.
Even if a newly-updated fwupd package changed the verfmt for the device, we'd still want to use the 'historical' verfmt when working out if the update was a success.
> Use the history-provided verfmt in more cases

- libfwupd/fwupd-enums.h
This means the 'Since:' tags are correct in the HTML documenation.
> trivial: Use new-style gtk-doc enum syntax

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-dpaux-device.c
- plugins/uefi-capsule/fu-uefi-device.c
- src/fu-engine.c
- src/fu-history.c
- src/fu-self-test.c
If we're 100% offline, we get the version format from the cab archive -- but when we reboot and check the 'new version' the verfmt is not available.
To do this, re-set the version string when the version format changes, and use FuDeviceClass->convert_version() in more places.
> Store the version format in the history database

- contrib/debian/tests/ci
> debian/tests/ci: Put all stderr into stdout. fwupdtool is pretty verbose with messages that happen to go to stderr but aren't errors.

- plugins/mtd/mtd.quirk
It's too slow -- we need a lzma streaming parser to make this efficient.
> trivial: Do not parse the IFD MTD partition at startup

- src/fu-engine.c
- src/fu-engine.rs
- src/fu-idle.c
- src/fu-idle.h
- src/fu-self-test.c
Devices that take a long time inhibit the daemon from auto-quitting on idle.
We were using that same idle for supressing the power notifications during the update -- which doesn't make sense. Split the idle inhibitor types into a bitfield to restore sanity.
> Split up the Inhibit idle types

- docs/fwupd.conf.md
- libfwupdplugin/fu-config.c
- src/fu-daemon.c
- src/fu-engine-config.c
This also allows us to decrease the value of the idle timer.
> Add a timer inhibit if the daemon took a long time to startup

- data/org.freedesktop.fwupd.metainfo.xml
Flathub now requires this.
See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer
> trivial: Add a <developer> tag into the metainfo file

- libfwupdplugin/fu-efi-section.c
This was caused by stream underflow, and was found using oss-fuzz, many thanks.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66717
> trivial: Fix an infinite loop when parsing invalid EFI firmware

- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-firmware.h
- libfwupdplugin/fu-self-test.c
This should prevent invalid firmware from deeply nesting.
> Limit the maximum depth of child firmware

- libfwupdplugin/fu-usb-device.c
This worked in all our emulated tests as the emulated device doesn't need to be open to return results.
> Open the GUsbDevice before getting the BOS descriptors

- src/fu-release.c
We want to show the thing that we compared, i.e. the new release version against the ESRT lowest version.
> trivial: Fix the error message when comparing the ESRT version_lowest

- plugins/amd-gpu/fu-amd-gpu-device.c
If an ASIC isn't found libdrm returns NULL for the marketing name. Handle this correctly in fwupd.
> trivial: amd-gpu: Handle NULL marketing name better

- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-plugin.h
- libfwupdplugin/fu-self-test.c
- plugins/wacom-usb/fu-wac-plugin.c
- plugins/wacom-usb/wacom-usb.quirk
If a vendor is using a DS-20 BOS descriptor this allows the embedded quirk to be much smaller, maybe just a single line.
> Allow plugins to opt-into a default device GType

- contrib/PKGBUILD
- contrib/ci/arch.sh
- contrib/fwupd.spec.in
- contrib/snap/snapcraft.yaml
- data/installed-tests/fwupd.sh
- docs/env.md
- generate-build/meson.build
- generate-build/unittest_inspector.py
- meson.build
- meson_options.txt
- plugins/amd-pmc/amd_pmc_test.py
- plugins/amd-pmc/meson.build
- plugins/meson.build
- plugins/pci-psp/meson.build
- plugins/pci-psp/pci_psp_test.py
- src/fu-daemon.c
- src/fu-engine.c
- src/fwupd_test.py
- src/meson.build
This allows relatively easily to mock Linux devices as the plugins will detect them.  Most immediately it allows to enumerate mocked devices in plugins, but umockdev also allows to do things like spawn other daemons and intercept ioctl calls.
I think we'll be able to add significantly more coverage by building on this, but this lays the immediate ground work with some very trivial tests.
This is done in python because it's a lot easier to have high level libraries like json to verify the data passed back from daemon to client.  My hope is we can start using this for any non-USB plugins in the future to add test infra.
A lot of this this  is leveraged from the power-profiles-daemon project but modified to fit fwupd.
It's too early for documentation on how to use this, but at a very high …
> Add some basic umockdev tests

- libfwupdplugin/fu-usb-device.c
- src/tests/usb-devices-invalid.json
- src/tests/usb-devices.json
See https://techcommunity.microsoft.com/t5/microsoft-usb-blog/usb-2-1-2-0-1-1-device-enumeration-changes-in-windows-8/ba-p/270775
Fixes https://github.com/fwupd/fwupd/issues/6871
> Only request the BOS descriptor when bcdUSB > 0x0200

- src/fu-engine.c
- src/fu-remote-list.c
- src/fu-remote-list.h
- src/fu-self-test.c
- src/tests/remotes.d/legacy-lvfs.conf
- src/tests/remotes.d/legacy.conf
Some users are using old lvfs.conf remotes for various reasons, for example copying around an embargo remote file rather than re-downloading it from the LVFS.
Also, rpm installs the file as fwupd.conf.rpmnew if there have been changes.
In this case fix up the remote to use .xz so that one day we might be able to stop generating the gz version. This also means more-releases per components and test reports become available to end users.
> Auto-fix remotes from .gz to .xz

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
No use in mounting the ESP when fwupd starts if there isn't a
valid ESRT.
Fixes: https://github.com/fwupd/fwupd/issues/6884
> uefi-capsule: Delay ESP probe until later

- data/ds20.quirk
- data/meson.build
- libfwupdplugin/fu-usb-device.c
Fixes https://github.com/fwupd/fwupd/issues/6871
> Do not probe the BOS descriptors of the Nostromo n52 gamepad

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
We used to do this in FwupdDevice which made the tests harder to write, but we can at least do it one layer higher.
> Actually set the created property when creating FuDevice

- plugins/uefi-capsule/fu-uefi-backend-freebsd.c
- plugins/uefi-capsule/fu-uefi-backend-linux.c
If a firmware update adds or removes an ESRT entry then all the indexes are shunted up or down. As we're using the sysfs path as the base for the ID we look at the 'wrong' new device version.
Use the GUID as the logical ID, and use the file index as a backend ID.
> uefi-capsule: Correctly record success if adding ESRT nodes

- data/fwupd.service.in
This introduces the ProcSubset option and drops the @clock and @cpu-emulation system calls from the service.
ProcSubset was introduced in Systemd v247 and should present no issues following the bump to minimum v249.
@clock covers calls for manipulating the system clock and time (should not be required).
@cpu-emulation covers calls for CPU emulation functionality.
More details at https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html
> Introduce ProcSubset, drop @clock @cpu-emulation

- libfwupdplugin/fu-hwids.c
- plugins/flashrom/flashrom.quirk
- plugins/flashrom/fu-flashrom-plugin.c
Based on a patch by Sean Rhodes <sean@starlabs.systems>, many thanks.
> flashrom: Always load the plugin when using coreboot

- data/fwupd.service.in
This drops the @debug and @module system calls and sets the action to be logged as "Operation not permitted" when calling a prohibited system call rather than immediate process termination.
@debug calls are related to debugging, performance monitoring and tracing functionality.
@module calls are related to loading and unloading of kernel modules (ProtectKernelModules is enabled, so this should be unobtrusive).
SystemCallErrorNumber is set to return EPERM (Operation not permitted) - this value will be returned when a deny-listed system call is triggered, instead of terminating the processes immediately.
Source: https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html
> Drop @debug & @module, apply SystemCallErrorNumber

- contrib/ci/fwupd_setup_helpers.py
Lists in python don't have `.prepend()`.  Use `.insert(0, x)` instead.
> trivial: fix mistake in de84009c39024153b92cef15d6f22e0f9c889000

- src/fu-engine.c
- src/fu-engine.h
- src/fu-tool.c
It seems macOS can't do a recursive F_OFD_SETLK -- and we shouldn't be reloading the engine anyway.
> trivial: Fix 'fwupdtool update' on macOS

- contrib/ci/dependencies.xml
- contrib/ci/fwupd_setup_helpers.py
Fixes https://github.com/fwupd/fwupd/issues/6942
> trivial: Fix ./contrib/setup when using macOS on aarch64

- src/fu-tool.c
The systemd unit is set to the snap version (snap.fwupd.fwupd.service) if the name of the snap is fwupd. This allows classic snaps to call a version of fwupd installed from classic package repositories (deb or rpm).
Fix #6946
Tested by building fwupd, then:
Running the deamon in a terminal:
```shell
$ /home/pieq/dev/work/fwupd/venv/bin/fwupd
```
while running `fwupdmgr` from the user session first:
```shell
$ /home/pieq/dev/work/fwupd/venv/bin/fwupdmgr get-devices
WARNING: This package has not been validated, it may not work properly.
Dell Inc. Precision 3570
│
(...)
```
then from a classic snap:
```shell
$ snap run --shell kate
(inside-kate-snap) $ /home/pieq/dev/work/fwupd/venv/bin/fwupdmgr get-devices
WARNING: This package has not been validated, it may not work …
```
> Allow classic snaps to call fwupd

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
Sometimes a device might have a proxy but not a parent->child relationship.
> Add an internal flag to use the proxy to open the device

- data/device-tests/qualcomm-qcc5171.json
- plugins/audio-s5gen2/README.md
- plugins/audio-s5gen2/audio-s5gen2.quirk
- plugins/audio-s5gen2/fu-audio-s5gen2-device.c
- plugins/audio-s5gen2/fu-audio-s5gen2-device.h
- plugins/audio-s5gen2/fu-audio-s5gen2-firmware.c
- plugins/audio-s5gen2/fu-audio-s5gen2-firmware.h
- plugins/audio-s5gen2/fu-audio-s5gen2-fw.rs
- plugins/audio-s5gen2/fu-audio-s5gen2-hid-device.c
- plugins/audio-s5gen2/fu-audio-s5gen2-hid-device.h
- plugins/audio-s5gen2/fu-audio-s5gen2-hid.rs
- plugins/audio-s5gen2/fu-audio-s5gen2-impl.c
- plugins/audio-s5gen2/fu-audio-s5gen2-impl.h
- plugins/audio-s5gen2/fu-audio-s5gen2-plugin.c
- plugins/audio-s5gen2/fu-audio-s5gen2-plugin.h
- plugins/audio-s5gen2/fu-audio-s5gen2.rs
- plugins/audio-s5gen2/meson.build
- plugins/meson.build
Firmware Update Plug-in for Qualcomm Voice & Music Series 5 Gen 1 and Gen 2, and Series 3 Gen 1, Gen 2 and Gen 3.
The initial variant of the plugin allows to update devices based on Qualcomm 5 series via USB HID. Tested with development board only.
- [x ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
> audio-s5gen2: plugin for updating Qualcomm audio devices

- plugins/redfish/fu-redfish-plugin.c
- src/fu-engine.c
Not sure if this will be enough to fix the issue.
Link: https://github.com/fwupd/fwupd/issues/6954
> trivial: redfish: don't reboot BMC if update failed

- plugins/uefi-capsule/fu-uefi-cod-device.c
- plugins/uefi-capsule/fu-uefi-device.c
- plugins/uefi-capsule/fu-uefi-grub-device.c
- plugins/uefi-capsule/fu-uefi-nvram-device.c
This means we can spot CoD just from a fwupdmgr get-devices.
> trivial: Include the type in the UEFI capsule device summary

- libfwupdplugin/fu-volume.c
See https://github.com/fwupd/fwupd/issues/6956
> Ignore ZFS zvols when finding the default ESP

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
> Adjust ESP detection to catch zfsbootmenu

- data/fwupd.service.in
This breaks access to /proc/cmdline and /proc/sys
```
Mar 22 16:35:43 arch-phoenix fwupd[3519]: 15:35:43.727 FuPluginIommu        failed to get kernel cmdline: Failed to open file "/proc/cmdline": No such file or directory
Mar 22 16:35:43 arch-phoenix fwupd[3519]: 15:35:43.727 FuPluginLinuxTainted could not open /proc/sys/kernel/tainted: Error opening file /proc/sys/kernel/tainted: No such file or directory
```
Fixes: 850af666d9
See: https://github.com/fwupd/fwupd/issues/6956
CC @RZR7332 
> Drop ProcSubset from systemd service

- plugins/uefi-capsule/fu-uefi-common.c
- plugins/uefi-capsule/fu-uefi-common.h
It's only used in fu-uefi-common.c.
> trivial: set fu_uefi_bootmgr_get_suffix() as static

- .git-blame-ignore-revs
It had the wrong hash to ignore initially.  Fix that hash and add hashes for the other two mass reformatting related commits.
> trivial: fixup .git-blame-ignore-revs to work correctly

- contrib/debian/control.in
libfwupd and the daemon are expected to move together.  Don't let people move them separately.
Link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1062820
> trivial: debian: set hard requirement on libfwupd version

- contrib/ci/dependencies.xml
It shouldn't be needed anymore when built with meson.
Link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064659
> trivial: debian: drop libtool dependency

- plugins/uefi-capsule/fu-uefi-device.c
Reusing the device error string is both confusing and looks terrible in the UI.
> Put the fwupd-efi verbose debugging in the journal

- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
This doesn't actually work.  Over the dbus wire devices that are returned are FwupdDevices (without order).  So they couldn't actually be sorted anyway.
FuDevice-CRITICAL **: 23:29:18.565: fu_device_get_order: assertion 'FU_IS_DEVICE(self)' failed
> trivial: stop sorting activation by order

- libfwupdplugin/fu-common.c
If any USB errors are passed up they won't be caught by `fwupd_error_convert()` but are caught by `fu_error_convert()`.  Run through `fu_error_convert()` first.
> trivial: fix critical warning on unsupported builds

- plugins/tpm/meson.build
- plugins/tpm/tpm.quirk
> tpm: Mark Pluton TPMs as part of the main CPU

- data/meson.build
This PR drops the @memlock and @pkey system calls from fwupd.
- [X ] Feature
Details of system calls will be listed in the comments section.
> Drop @memlock & @pkey system calls

- src/fu-udev-backend.c
We need to keep track of what mode fu_udev_backend_device_add() is being called from. Scanning the dp_aux OUI at hotplug is causing link failures.
Many thanks to Benson Leung <bleung@chromium.org> for all the debugging.
> Defer the dp_aux MST scanning on hotplug

- src/fu-daemon.c
- src/fu-main.c
Doing it at startup really helps to make fwupd 'look better' in ps (even though the kernel would eventually reclaim the pages on memory pressure) but refreshing the metadata allocates dozens of pages that we can discard when the engine is idle again.
Note, this doesn't change how much RSS fwupd actually uses, but it'll make the number look smaller in any kind of process explorer.
> Drop heap as part of a housekeeping action

- SECURITY.md
Currently, the link title is located after the link address, which makes the Markdown rendering look strange and the link points to a non-existing location (e.g. `https://github.com/fwupd/fwupd/security](let`)
Fix it with the correct order of link components
Validation: used the preview tab to make sure it renders correctly and clicking it works as expected
> trivial: fix link formatting in SECURITY.md

- SECURITY.md
Following @superm1 [comment](https://github.com/fwupd/fwupd/pull/7044#issuecomment-2041433470) on previous PR, update the links in this page to link to the report page itself (what the "Report a vulnerability" button links to) instead of linking to this same page
Validation: used preview to make sure it renders correctly and both links open the expected page
> trivial: update links in SECURITY.md to link to the actual report

- libfwupdplugin/fu-volume.c
Fixes: https://github.com/fwupd/fwupd/issues/7045
> trivial: ignore RAID block devices for building ESP candidates

- contrib/ci/oss-fuzz-libcbor-lto.patch
- contrib/ci/oss-fuzz.py
It seems there's no way to *disable* LTO using cmake -- and LTO isn't going to work for a static library...
> Compile libcbor without LTO to fix oss-fuzz

- contrib/snap/snapcraft.yaml
Ensure that the snap gets built with the version we have in the subproject. This should make sure it's always got "What we want" instead of "What's in Ubuntu's archive".
> trivial: snap: build with newer libxmlb

- meson.build
- subprojects/libxmlb.wrap
Fixes https://github.com/fwupd/fwupd/issues/7060
This won't work until 0.3.18 is actually tagged.
> trivial: bump libxmlb requirement to 0.3.18

- data/org.freedesktop.fwupd.metainfo.xml
Flathub requires a developer tag and developer ID. Also Appstream decided to use rdns structure for developer ID.
It allows reverse-dns IDs like sh.cozy, de.geigi or Fediverse handle (like @user@example.org)
> A developer tag with a name child tag must be present.
> Only one developer tag is allowed and the name tag also must be present only once in untranslated form.
```
<developer id="tld.vendor">
<name>Developer name</name>
</developer>
```
Source: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#name-summary-and-developer-name
> The element should have a id property, containing a unique ID to identify the component developer / development team. It is recommended to use a reverse-DNS name, like org.gnome or io.github.ximion, or a Fediverse handle …
> Appdata related changes

- src/fu-engine.c
Generic message makes sense when there is no ID, but if the ID is provided it's not generic.
> Set a generic message request flag when the ID is known

- src/fu-engine.c
At the moment we have no idea if Passim is helping with metadata distribution or not. Of course, this will be skewed to customers allowing random network access, and to those with deployed firmware updates -- but a number that's 'going up' gives us a good idea on how it is being used in the real world.
> Include the Passim download saving number in the fwupd firmware metadata

- data/meson.build
As per the systemd documentation:
Generally, allow-listing system calls (rather than deny-listing) is the safer mode of operation. It is recommended to enforce system call allow lists for all long-running system services.
Verified with no notible changes to `systemd-analyze security fwupd.service`
Many thanks to RZR7332 for the original patch.
> Change SystemCallFilter to allowlist

- plugins/cros-ec/README.md
- plugins/cros-ec/fu-cros-ec-usb-device.c
Use an instance ID of 'USB\VID_18D1&PID_501A&BOARDNAME_gingerbread' rather than just 'gingerbread' as it might accidentally match other devices.
Fixes https://github.com/fwupd/fwupd/issues/7022
> cros-ec: Do not add a generic instance ID

- .github/workflows/codeql-analysis.yml
- contrib/PKGBUILD
- contrib/ci/ubuntu.sh
- contrib/debian/rules
- contrib/freebsd/Makefile
- contrib/fwupd.spec.in
- meson_options.txt
- plugins/uefi-capsule/README.md
"Most" people doing fwupd development and packaging won't need the EFI binary by default, so don't build it.
Fixes: https://github.com/fwupd/fwupd/issues/7119
> trivial: don't build efi binary by default

- src/fu-engine.c
- src/fu-remote-list.c
- src/fu-remote-list.h
- src/fu-tool.c
Debian (currently) packages fwupd-tests as a separate package from fwupd.  If test mode is enabled a lot of test things work, but locally installed metadata specifically doesn't.
Make it clearer when test mode is enabled that the fwupd-tests remote also needs to be present.
> trivial: make fwupd-tests remote mandatory for test devices

- contrib/ci/check-source.py
- libfwupdplugin/fu-coswid-common.c
- libfwupdplugin/fu-coswid-common.h
- libfwupdplugin/fu-coswid-firmware.c
The libcbor library only does CBOR_ASSERT() on the correct item width.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68105
> Do not use cbor_get_uintXX() to access CBOR items

- libfwupdplugin/fu-coswid-firmware.c
Apparently, libcbor expects a valid pointer for a zero sized allocation.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68115
> trivial: Fix a regression from 587927

- libfwupd/fwupd-client.c
- libfwupd/fwupd-request-private.h
- libfwupd/fwupd-request.c
- libfwupd/fwupd-request.h
- libfwupd/fwupd.map
- src/fu-engine.c
Although we can do this looking at the device changed events, it's much nicer to provide a signal that GUI clients can use directly.
Fixes https://github.com/fwupd/fwupd/issues/7130
> Emit a signal when a request is no longer valid

- libfwupdplugin/fu-coswid-firmware.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68165
> trivial: Fix a crash when parsing invalid COSWID files

- docs/fwupd.conf.md
rustgen output:
FuP2pPolicy
fu_p2p_policy_from_string(const gchar *val)
{
if (g_strcmp0(val, "nothing") == 0)
return FU_P2P_POLICY_NOTHING;
if (g_strcmp0(val, "metadata") == 0)
return FU_P2P_POLICY_METADATA;
if (g_strcmp0(val, "firmware") == 0)
return FU_P2P_POLICY_FIRMWARE;
return FU_P2P_POLICY_NOTHING;
}
> trivial: Fix P2pPolicy's nothing value in docs

- data/device-tests/hughski-colorhug.json
> trivial: Use a newer ColorHug firmware for the emulated tests

- libfwupdplugin/fu-coswid-firmware.c
- libfwupdplugin/fu-coswid.rs
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68315
> Fix a buffer-overread when parsing invalid CoSWID entity data

- plugins/algoltek-aux/README.md
- plugins/algoltek-aux/algoltek-aux.quirk
- plugins/algoltek-aux/fu-algoltek-aux-device.c
- plugins/algoltek-aux/fu-algoltek-aux-device.h
- plugins/algoltek-aux/fu-algoltek-aux-firmware.c
- plugins/algoltek-aux/fu-algoltek-aux-firmware.h
- plugins/algoltek-aux/fu-algoltek-aux-plugin.c
- plugins/algoltek-aux/fu-algoltek-aux-plugin.h
- plugins/algoltek-aux/fu-algoltek-aux.rs
- plugins/algoltek-aux/meson.build
- plugins/meson.build
> Add a new plugin to update Algoltek DisplayPort devices

- libfwupd/fwupd-client.c
In b6633f4 I forgot that `fwupd_device_array_from_variant()` had the magic ability to set up the parents when converting from a GVariant.
This fixes the device nesting in 'fwupdmgr get-devices'
> trivial: Ensure device parents are setup when using FwupdClient

- plugins/pci-mei/fu-pci-mei-plugin.c
- plugins/tpm/fu-tpm-eventlog.c
- plugins/wacom-usb/fu-wac-device.c
- src/fu-release.c
- src/fu-tool.c
- src/fu-util-bios-setting.c
- src/fu-util-common.c
The recent b6633f49 commit changed semantics slightly; by unifying the behaviour of `fu_common_string_append_kv()` and `fwupd_pad_kv_str()` we made everything the same.
To show an empty 'header' we now need to pass a non-NULL value, and we can also rely on the NULL-ignore beahviour to make some callers simpler.
> trivial: Use new semantics for fwupd_codec_string_append()

- .github/workflows/codeql-analysis.yml
- contrib/build-openbmc.sh
- libfwupdplugin/meson.build
- meson.build
Stop allowing support for older releases on the 2.0.0 branch.  This isn't intended to backport.
> trivial: require libxmlb 0.3.18 or later

- libfwupd/fwupd-client.c
This also allows us to test with a localhost LVFS instance with a self-signed certificate.
> Do not verify the SSL hostname when using DISABLE_SSL_STRICT=1

- data/bash-completion/fwupdmgr
- libfwupd/fwupd-remote.c
- src/fu-util.c
It would be really helpful to go to vendors and say '12,345 Linux users are not getting firmware updates for model ABC' -- at the moment we don't have any numbers and sometimes vendors need a bit of convincing.
This would be opt-in to preserve privacy. The salted machine ID is only used to dedupe multiple uploads from the same machine.
> Allow the user to upload the entire devicelist to the LVFS

- contrib/build-venv.sh
If Meson failed partway through, it’s possible that the build directory exists but build.ninja inside doesn’t, which would make Ninja fail immediately. Fixes #7227.
> trivial: venv: check build.ninja presence

- libfwupd/fwupd-client.c
This matches the fix in 1f8ae4372ad25b003e1bf4ee5d6931db2c5f5493 and makes testing using a local LVFS instance much easier.
> trivial: Allow using DISABLE_SSL_STRICT when uploading bytes

- plugins/jabra-gnp/README.md
- plugins/jabra-gnp/fu-jabra-gnp-device.c
- plugins/jabra-gnp/fu-jabra-gnp-plugin.c
- plugins/jabra-gnp/jabra-gnp.quirk
> Jabra-gnp: Adds support to OTA updates. Includes some bug fixes

- plugins/logitech-rallysystem/fu-logitech-rallysystem-audio-device.c
Added filler to convert 3 bytes into guint32. fu_device_set_version_raw() expects 4 bytes
> Leverage 3 bytes for system version

- libfwupdplugin/fu-bluez-device.c
- libfwupdplugin/fu-bluez-device.h
Some BT devices don't provide VID, so fwupd can't detect such devices properly. In the same time, the device might announce service with unique UUID for firmware upgrading.
This commit allows to detect BT devices by UUID of the updating service, for instance:
21608f80-6c9c-5cd1-91ed-0fbf18e31958 ← BLUETOOTH\GATT_00001100-d102-11e1-9b23-00025b00a5a5
In addition, added querying of Battery service if available, and battery percentage is set according to received value
- [x ] Feature
> Detect BlueTooth devices by GATT service UUID

- data/bash-completion/fwupdmgr
- data/bash-completion/fwupdtool
Fixes: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/2065948
> trivial: fix enable-remote/disable-remote bash completion to use json interface

- libfwupdplugin/fu-firmware.c
This should fix flashing the wacom_usb touch module.
Resolves: https://github.com/fwupd/fwupd/issues/7267
> Invalidate the original input stream if using fu_firmware_set_bytes()

- plugins/logitech-tap/fu-logitech-tap-device.c
- plugins/logitech-tap/fu-logitech-tap-device.h
- plugins/logitech-tap/fu-logitech-tap-hdmi-device.c
- plugins/logitech-tap/fu-logitech-tap-plugin.c
Rename private flag name to avoid conflict with existing internal flag (FWUPD_DEVICE_FLAG_NEEDS_REBOOT)
> Rename private flag to avoid conflict

- plugins/wacom-usb/wacom-usb.quirk
The PID for Wacom new device, Movink, is added
- [ v] Feature
> Add PID for Movink(DTH135K0C)

- plugins/logitech-tap/fu-logitech-tap-hdmi-device.c
- plugins/logitech-tap/fu-logitech-tap-plugin.c
Wait for device reboot
[fwupdtool_output.txt](https://github.com/fwupd/fwupd/files/15381437/fwupdtool_output.txt)
> Wait for device reboot

- plugins/android-boot/android-boot.quirk
The SHIFTphone 8 (otter) is an upcoming smartphone based on the Qualcomm QCM6490 SoC.
As the partition table is not expected to change in future (fingers crossed), the quirk making the ABLs available to update can be added already.
Tested on postmarketOS using a DVT1 device.
Repo to generate the firmware cab files as reference: https://github.com/SHIFTPHONES/fwupd_packaging/tree/otter/abl
> android-boot: Add SHIFTphone 8 (otter) to quirk file

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Fedora 38 appears to have set up an ESP within an md array that is btrfs.  This isn't possible for a BIOS to use.
Reject this combination.
Fixes: #7277
> trivial: catch miscategorized ESP partitions

- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-volume.c
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
A user has reported an md array that is an xfs kind that with the wrong partition table flags.  Explicitly only allow vfat and ntfs for ESPs.
Fixes: b42ad1d45 ("trivial: catch miscategorized ESP partitions") Fixes https://github.com/fwupd/fwupd/issues/7298
> trivial: switch to allowlist for partition kinds

- docs/tutorial.md
TL;DR: very tiny update for _tutorial.md_ about `u16le`.
Hello. I've heard a lot about this project and recently I was getting curious about it again so I started to scout official documentation, so by pure accident I discovered [this tiny formatting mistype](https://github.com/ia/fwupd/blob/d674f9584697802c53a833d7bb5a5236ab2ca98b/docs/tutorial.md?plain=1#L914) which I'm more than happy to help to fix. But let me know if this should be modified in any other way. Thanks.
> trivial: fix markdown syntax for u16le and update its description

- libfwupdplugin/README.md
- libfwupdplugin/fu-efivars-private.h
- libfwupdplugin/fu-efivars.c
- libfwupdplugin/fu-efivars.h
- libfwupdplugin/fu-self-test.c
- plugins/linux-lockdown/fu-linux-lockdown-plugin.c
- plugins/uefi-capsule/fu-uefi-bootmgr.c
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-capsule/fu-uefi-common.c
- plugins/uefi-capsule/fu-uefi-device.c
This allows us to share the 'create a plausible UEFI system' code to be used in the other self test binaries.
> trivial: Move some EFI variable setup code to libfwupdplugin

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Might help fix https://github.com/fwupd/fwupd/issues/7351
> uefi-capsule: Only clean up an ESP that exists

- plugins/pixart-rf/fu-pxi-receiver-device.c
> pixart-rf: Only show one PixArt receiver device per physical device

- plugins/pixart-rf/fu-pxi-ble-device.c
- plugins/pixart-rf/fu-pxi-receiver-device.c
> Add 'FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG' for waiting device reset.

- libfwupdplugin/fu-backend.c
- libfwupdplugin/fu-device-event-private.h
- libfwupdplugin/fu-device-event.c
- libfwupdplugin/fu-device-event.h
- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fwupdplugin.h
- libfwupdplugin/meson.build
- src/fu-udev-backend.c
- src/fu-usb-backend.c
The medium-term aim here is to also do the FuUsbDevice type.
> Allow emulating FuUdevDevice superclasses

- libfwupdplugin/fu-elf-firmware.c
- libfwupdplugin/fu-elf.rs
The NULL and autogenerated .shrtrtab sections should not be added as images.
> Do not add nonsense sections to FuElfFirmware

- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- plugins/thunderbolt/fu-thunderbolt-controller.c
It's only used in one place and it is trivial to implement.
> trivial: Remove fu_udev_device_get_parent_name()

- libfwupdplugin/README.md
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- plugins/ata/fu-ata-device.c
- plugins/nvme/fu-nvme-device.c
The concept of "slots" only works for PCI devices.
> trivial: Rename fu_udev_device_get_slot_depth() to fu_udev_device_get_subsystem_depth()

- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- plugins/pci-bcr/fu-pci-bcr-plugin.c
- plugins/pci-mei/fu-pci-mei-plugin.c
This flag is only used in two places and makes the device path lifecycle very complicated to explain.
> trivial: Remove FU_UDEV_DEVICE_FLAG_USE_CONFIG and implement directly

- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
- plugins/genesys-gl32xx/fu-genesys-gl32xx-plugin.c
- plugins/genesys-gl32xx/genesys-gl32xx.quirk
It was just recently [announced](https://frame.work/tw/en/blog/introducing-the-new-framework-laptop-13-with-intel-core-ultra-series-1-processors) together with the Intel Core Ultra platforms.
It will be available soon here: https://frame.work/tw/en/products/sd-expansion-card
It uses a GL3230 controller, so it's already supported by the plugin, but the plugin currently does not handle non-genesys VID/PID devices.
> Add support for Framework SD Expansion Card

- contrib/ci/check-headers.py
- contrib/ci/check-license.py
- contrib/ci/check-quirks.py
- contrib/ci/flatpak.py
- contrib/ci/fwupd_setup_helpers.py
- contrib/ci/generate_debian.py
- contrib/ci/generate_docker.py
- contrib/ci/oss-fuzz.py
- contrib/ci/populate-bios-setting-translations.py
- contrib/firmware_packager/add_dfu_header.py
- contrib/generate-ds20.py
- contrib/migrate.py
- contrib/qubes/test/test_qubes_fwupdmgr.py
- contrib/standalone-installer/assets/header.py
- contrib/upload-smc-license.py
- generate-build/generate-version-script.py
- generate-build/unittest_inspector.py
- plugins/amd-gpu/amd_gpu_test.py
- plugins/nvme/nvme_test.py
- plugins/uefi-capsule/make-images.py
According to https://endoflife.date/python python 3.7 has been EOSed 27 Jun 2023.
Filter all code over `pyupgracde --py38-plus`.
> drop python<=3.7 support

- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fu-usb-device.h
- plugins/cros-ec/fu-cros-ec-usb-device.c
In GUsb this is failable, and there's a nasty `g_return_val_if_fail` that I want to handle properly longer term.
> trivial: Add a GError to fu_usb_device_get_configuration_index()

- SECURITY.md
We're past the date advertised as EoL now, update the document.
> trivial: mark 1.7.x as EOL

- plugins/nordic-hid/fu-nordic-hid-cfg-channel.c
Change adds missing udev device flags to prevent warning logs.
> plugins: nordic-hid: Add udev device flags

- plugins/usi-dock/README.md
- plugins/usi-dock/fu-usi-dock-dmc-device.c
From the next version of the FW, a new GUID will be used for differentiation.
> usi-dock: add PCB tag in uuid to distinguish different PCB versions

- data/fwupd.service.in
Setting `ProtectClock=yes` implies `DeviceAllow=char-rtc r` which seems to effectively block fwupd from accessing hidraw. Change adds missing `DeviceAllow` to let fwupd access hidraw.
Fixes: https://github.com/fwupd/fwupd/issues/7414
> data: fwupd.service.in: Add missing hidraw permission

- libfwupdplugin/fu-device-event-private.h
- libfwupdplugin/fu-device-event.c
- libfwupdplugin/fu-udev-device.c
Allow passing the actual data length back to the caller.
> trivial: Make fu_device_event_copy_data() more useful

- plugins/pci-bcr/fu-pci-bcr-plugin.c
- plugins/pci-mei/fu-pci-mei-plugin.c
Fixes some of https://github.com/fwupd/fwupd/issues/7402
> trivial: Fix two warnings when probing raw FuUdevDevices

- libfwupdplugin/fu-backend.c
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-udev-device.c
- src/fu-engine.c
- src/fu-history.c
- src/fu-self-test.c
It might have been set from emulation data.
> trivial: Only reset the device created timestamp if not already set

- libfwupdplugin/fu-device.c
> trivial: Reset the device event index when clearing events

- src/fu-engine.c
- src/fu-util.c
Calling 'fwupdmgr device-emulate data/device-tests/*.json' should not leave dozens of unremovable emulated devices in the device list.
> Remove emulated devices after doing each device test

- contrib/codespell.cfg
- contrib/migrate.py
- libfwupdplugin/fu-crc.c
- libfwupdplugin/fu-crc.h
- libfwupdplugin/fu-dfu-firmware.c
- libfwupdplugin/fu-fit-firmware.c
- libfwupdplugin/fu-input-stream.c
- libfwupdplugin/fu-input-stream.h
- libfwupdplugin/fu-self-test.c
- plugins/audio-s5gen2/fu-audio-s5gen2-firmware.c
- plugins/bcm57xx/fu-bcm57xx-common.c
- plugins/bcm57xx/fu-bcm57xx-common.h
- plugins/bcm57xx/fu-bcm57xx-dict-image.c
- plugins/bcm57xx/fu-bcm57xx-firmware.c
- plugins/bcm57xx/fu-bcm57xx-stage1-image.c
- plugins/bcm57xx/fu-bcm57xx-stage2-image.c
- plugins/corsair/fu-corsair-bp.c
- plugins/corsair/fu-corsair-common.c
- plugins/corsair/fu-corsair-common.h
- plugins/goodix-moc/fu-goodixmoc-device.c
- plugins/nordic-hid/fu-nordic-hid-firmware.c
- plugins/steelseries/fu-steelseries-firmware.c
- plugins/steelseries/fu-steelseries-sonic.c
- plugins/synaptics-cape/fu-synaptics-cape-sngl-firmware.c
- plugins/wacom-usb/fu-wac-module-bluetooth-id9.c
Many plugins are being developed with "custom" CRC-32 checksums. It turns out they're not actually custom at all, and if we support more types we can remove a lot of bit-twiddling.
> Support more CRC-32 types

- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
Other plugins can use the same heuristics to decide on the ESP, so pull the code into libfwupdplugin instead.
> libfwupdplugin: Move ESP selection heuristics out of uefi-capsule

- plugins/bios/fu-bios-plugin.c
- plugins/bios/meson.build
The BIOS plugin has an assumption that users can switch modes and that an ESRT is used for updating.
The main purpose of the plugin is to guide people what to do. This isn't strictly true for non-x86 architectures. Disable the plugin on non-x86.
> trivial: bios: don't compile other than on x86

- libfwupdplugin/fu-i2c-device.c
These are very generic and platform specific and plugins can/should add other instance IDs that are more specific and narrow.
This is useful for hiding the unused I2C GUID in AMD Kria SOM.
> libfwupdplugin: Hide i2c instance IDs by default

- contrib/codespell.cfg
- plugins/amd-kria/README.md
- plugins/amd-kria/eeprom.txt
- plugins/amd-kria/fu-amd-kria-device.c
- plugins/amd-kria/fu-amd-kria-device.h
- plugins/amd-kria/fu-amd-kria-image-reg.c
- plugins/amd-kria/fu-amd-kria-image-reg.h
- plugins/amd-kria/fu-amd-kria-persistent-reg.c
- plugins/amd-kria/fu-amd-kria-persistent-reg.h
- plugins/amd-kria/fu-amd-kria-persistent.rs
- plugins/amd-kria/fu-amd-kria-plugin.c
- plugins/amd-kria/fu-amd-kria-plugin.h
- plugins/amd-kria/fu-amd-kria-som-eeprom.c
- plugins/amd-kria/fu-amd-kria-som-eeprom.h
- plugins/amd-kria/fu-amd-kria-som-eeprom.rs
- plugins/amd-kria/kria.quirk
- plugins/amd-kria/meson.build
- plugins/meson.build
- plugins/mtd/mtd.quirk
The AMD Kria SoM https://www.amd.com/en/products/system-on-modules/kria.html is an aarch64 device that can be booted multiple ways.  When booted in UEFI mode, U-boot exports an ESRT and limited UEFI boot and runtime services such that CoD works.
When booted outside of UEFI mode U-boot can still handle updating via a capsule, but there is no ESRT to relay this information to the OS.  Instead add a plugin that detects that an ESRT is missing and pulls the version information from the MTD partition.
Note: this is draft to align on how this will work, it's still missing the ability to pull the firmware version out of the MTD partition.
> Add a plugin to handle AMD Kria SoM

- libfwupdplugin/README.md
- libfwupdplugin/fu-i2c-device.c
- libfwupdplugin/fu-i2c-device.h
- libfwupdplugin/fu-udev-device-private.h
- libfwupdplugin/fu-udev-device.c
We can just use fu_udev_device_get_number() as well -- it's the same thing!
> Remove the unused fu_i2c_device_get_bus_number()

- libfwupdplugin/fu-backend.c
- libfwupdplugin/fu-backend.h
- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-drm-device.c
- libfwupdplugin/fu-i2c-device.c
- libfwupdplugin/fu-mei-device.c
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- libfwupdplugin/fu-usb-device-private.h
- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fu-usb-device.h
- plugins/elantp/fu-elantp-i2c-device.c
- plugins/emmc/fu-emmc-device.c
- plugins/genesys/fu-genesys-plugin.c
- plugins/intel-gsc/fu-igsc-device.c
- plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
- plugins/mediatek-scaler/fu-mediatek-scaler-device.c
- plugins/nvme/fu-nvme-device.c
- plugins/pixart-rf/fu-pxi-receiver-device.c
- plugins/scsi/fu-scsi-device.c
- plugins/synaptics-rmi/fu-synaptics-rmi-hid-device.c
- plugins/thunderbolt/fu-thunderbolt-controller.c
- plugins/thunderbolt/fu-thunderbolt-device.c
- plugins/thunderbolt/fu-thunderbolt-retimer.c
- src/fu-udev-backend.c
- src/fu-usb-backend.c
In some cases the device itself doesn't have enough of a 'world-view' to understand what the parent should be.
Move this to the backend which can also create the right GType as required, e.g. creating a custom FuI2cDevice parent rather than a 'plain' FuUdevDevice.
> Move getting the device parent from the device to the backend

- plugins/dell-dock/fu-dell-dock-hub.c
- plugins/dell-dock/fu-dell-dock-i2c-ec.c
- plugins/dell-dock/fu-dell-dock-plugin.c
The device ID is being reused in the existing docks and the upcoming one, and the commands in this plugin will not work for the new dock. We will delay the hub commands until we know the dock is fully supported within this plugin.
In the ec device side, the version comparison must be removed because the hub version is detauled to `1.1` (due to delayed probing) which will always fail to be added.
> dell-dock: setup hub version until dock type is known to be supported

- meson.build
Setting `required` to a `bool` vs. `feature` behaves differently (see [meson docs](https://mesonbuild.com/Reference-manual_functions.html#dependency_required)). When `flashrom_allowed` is `false`, the flashrom dependency will still build the fallback subproject.
> trivial: Do not fall back to flashrom dependency if disabled

- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- plugins/meson.build
- plugins/uefi-sbat/README.md
- plugins/uefi-sbat/fu-uefi-sbat-device.c
- plugins/uefi-sbat/fu-uefi-sbat-device.h
- plugins/uefi-sbat/fu-uefi-sbat-firmware.c
- plugins/uefi-sbat/fu-uefi-sbat-firmware.h
- plugins/uefi-sbat/fu-uefi-sbat-plugin.c
- plugins/uefi-sbat/fu-uefi-sbat-plugin.h
- plugins/uefi-sbat/meson.build
- plugins/uefi-sbat/revocation.builder.xml
- src/fu-tool.c
> uefi-sbat: Add a new plugin that can apply revocations to SbatLevelRT

- libfwupdplugin/fu-usb-bos-descriptor.c
- libfwupdplugin/fu-usb-bos-descriptor.h
- libfwupdplugin/fu-usb-descriptor.c
- libfwupdplugin/fu-usb-descriptor.h
- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fu-usb-endpoint.c
- libfwupdplugin/fu-usb-endpoint.h
- libfwupdplugin/fu-usb-interface-private.h
- libfwupdplugin/fu-usb-interface.c
- libfwupdplugin/fu-usb-interface.h
- libfwupdplugin/fu-usb.rs
- libfwupdplugin/meson.build
- plugins/dfu/fu-dfu-device.c
Add functional descriptors as children of FuUsbInterface; just because libusb dumps them as raw blobs doesn't mean we have to copy the same broken design.
Expose them as FuUsbDescriptor, and make the other descriptor superclasses depend (and use) this new baseclass.
> Remove fu_usb_interface_get_extra()

- plugins/wacom-usb/fu-wac-device.c
If modules have no enough time to initialize, they're reporting version 0.0. This value doesn't change until device re-read with replugging or fwupd restart.
Fixes https://github.com/fwupd/fwupd/issues/7509
> wacom-usb: wait modules initialization

- libfwupdplugin/fu-dpaux-device.c
It's a very low bar to clear, and it fixes the warning when there is no branch device attached.
Fixes some of https://github.com/fwupd/fwupd/issues/7402
> Require a DPCD OUI to match DPAUX devices

- data/fwupd.service.in
This reverts commit bd82124ad438ded78900e39b92fbdd646f14321a.
This fixes a regression on 1.9.22 that caused many devices not to probe.  The change doesn't make sense on 1_9_X because ProtectClock=yes was never set there.
Fixes https://github.com/fwupd/fwupd/issues/7547
Fixes https://github.com/fwupd/fwupd/issues/7545
> Revert "data: fwupd.service.in: Add missing hidraw permission"

- contrib/launch-venv.sh
- contrib/setup
Like in many other scripts, use /usr/bin/env for maximum OS compatibility. I was trying to build on FreeBSD and they don't have their binaries in /bin.
> contrib: Use /usr/bin/env for more compatibility

- libfwupdplugin/fu-udev-device.c
Using ':' symbol for splitting to check devtype properly.
> trivial: fix delimiter symbol for udev subsystem

- plugins/logitech-hidpp/fu-logitech-hidpp-device.c
Partially fixes https://github.com/fwupd/fwupd/issues/7011
I did a test with available devices.
Probably we can remove the polling at all -- but need to be careful with devices supporting only previous protocol versions. As well as with BT/BLE devices.
> Do not ping paired with Bolt devices 

- libfwupdplugin/fu-backend-private.h
- libfwupdplugin/fu-backend.c
- src/fu-engine.c
We want to record the emaultion of the superclass device, not the backend device -- i.e. we need to capture the plugin-specific setup() actions, not just the generic backend ones...
> Fix a thinko when recording emulation of USB devices

- plugins/ccgx-dmc/fu-ccgx-dmc-device.c
This has the vendor interface as index 0, not index 1.
Fixes https://github.com/fwupd/fwupd/issues/7527
> ccgx-dmc: Add support for the CY6611 EZ-USB HX3PD evaluation kit

- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-volume.c
- libfwupdplugin/fu-volume.h
The Partition `Name` key isn't populated on many devices, but the Block `IdLabel` key is.
Use the Block `IdLabel` key instead for heuristics to skip partitions.
Fixes: https://github.com/fwupd/fwupd/issues/7546
> Use block device instead of partition to detect ESPs to skip

- plugins/uefi-capsule/README.md
We don't use `uefi_capsule.conf` anymore.
> trivial: uefi-capsule: correct configuration file

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-capsule/fu-uefi-cod-device.c
- plugins/uefi-capsule/fu-uefi-device.c
- plugins/uefi-capsule/fu-uefi-device.h
- plugins/uefi-capsule/uefi-capsule.quirk
Dell added customization for capsule on disk feature. If system manufacturer is `Dell Inc.` and the support is advertised by system firmware then use the destination.
> capsule on disk: add support for Dell systems

- plugins/redfish/fu-redfish-backend.c
Each redfish request will be a few ms slower, but most redfish requests take multiple seconds (or minutes!) to complete.
Fixes https://github.com/fwupd/fwupd/issues/7593
> redfish: Do not re-use the connection cache to fix BMC restart

- libfwupdplugin/fu-volume.c
Based on a patch by Mario Limonciello <mario.limonciello@amd.com>, many thanks.
Fixes: https://github.com/fwupd/fwupd/issues/6477
> Ensure that partition name and block name are non-zero string length

- libfwupdplugin/fu-device.c
We want to run the subclass codec not just the baseclass.
> trivial: Correctly print the proxy device in fu_device_to_string()

- libfwupdplugin/fu-volume.c
- libfwupdplugin/fu-volume.h
This is a backport of portions of the following commits:
c67531079c26bdc80c9bfffe291b764a05cb260a
5f221172736fcd460441abc62ea1c399f41512c1
c67531079c26bdc80c9bfffe291b764a05cb260a
> Exclude known recovery partitions from ESP volume building

- libfwupdplugin/fu-ifd-firmware.c
Some test IFD images were captured missing the final byte.
> Align up IFD images to fix many UEFI test ROMs

- meson.build
- plugins/modem-manager/README.md
- plugins/modem-manager/fu-cinterion-fdl-updater.c
- plugins/modem-manager/fu-cinterion-fdl-updater.h
- plugins/modem-manager/fu-cinterion-fdl-updater.rs
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/meson.build
- plugins/modem-manager/modem-manager.quirk
Adds Cinterion `AT^SFDL` 'Firmware Download Mode' based update.
When the `AT^SFDL` command has been successfully sent, the device is supposed to be in firmware download mode after 15 seconds. Reading an `ok (0x01)` byte confirms that the device is ready for firmware download.
The firmware file is written to the device chunk by chunk, where each chunk consists of:
- 8 bits indicating the current chunk's data size in bytes
- chunk data with above size in little endian format
The `cinterion-fdl` update method depends on [this merge request](https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/merge_requests/1205) in ModemManager.
> Add modem-manager cinterion fdl-based update

- meson.build
- subprojects/libjcat.wrap
These should have been bumped as part of 62f6f19d269212871493ba8343bf0d53204c7fb7
(cherry picked from commit 774b87fed0c6addd49cdc65a3ecc24923f7c76ae)
> trivial: bump libjcat and passim deps

- plugins/modem-manager/fu-mm-device.c
Currently only `VID_&PID_&REV_` and `VID_&PID_&REV_&CARRIER_` instance IDs are visible for modem-manager devices.
It would be useful to be able to select a device matching `VID_&PID_` only, independent of its revision, in LVFS metadata.
```
└─EC25:
Summary:            Quectel EG25-G/EC25 modem
...
GUID:               1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
Device Flags:       • Updatable
```
> Make modem-manager VID_PID IDs visible

- libfwupdplugin/fu-device-event-private.h
- libfwupdplugin/fu-device-event.c
- libfwupdplugin/fu-self-test.c
The Huddly USB device does a zero-length bulk transfer to reset the device, and that doesn't get saved in the emulation data. Handle NULL.
> Allow setting NULL data in fu_device_event_set_data()

- meson_options.txt
These were changed 2.5 years ago in 661990ed98870f8451015617701c50f68dc63824.
That's enough time for people to adjust.
> trivial: drop deprecated config options for meson features

- contrib/ci/check-quirks.py
- libfwupdplugin/fu-quirks.c
These were deprecated 3.5 years ago in 7d132b728c.
Drop support for them.
> trivial: drop support for deprecated quirk strings

- libfwupdplugin/tests/efi/efivars/meson.build
- meson.build
Don't pigeonhole into 0.xx series for a modern fwupd.
> trivial: bump meson version to a more modern version

- libfwupdplugin/fu-backend.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-udev-device.c
- src/fu-bluez-backend.c
- src/fu-engine.c
- src/fu-self-test.c
- src/fu-usb-backend.c
Since FuUdevBackend is actually creating FuUsbDevice objects on Linux we can't rely on one backend handling just one kind of emulated device GType.
Lets simplify loading and saving the emulation data. Rather than splitting up the arrays per-backend just load everything and respect the device GType, but defaulting to FuUsbDevice to allow older emulation data to run.
> Fix loading USB emulation data

- meson.build
- plugins/cpu/fu-cpu-device.c
This will let us drop some special cased code for older glib versions.
> trivial: set minimum glib version to 2.80

- contrib/ci/check-source.py
- data/device-tests/qualcomm-qcc5171.json
- plugins/audio-s5gen2/README.md
- plugins/audio-s5gen2/audio-s5gen2.quirk
- plugins/audio-s5gen2/fu-audio-s5gen2-ble-device.c
- plugins/audio-s5gen2/fu-audio-s5gen2-ble-device.h
- plugins/audio-s5gen2/fu-audio-s5gen2-ble.rs
- plugins/audio-s5gen2/fu-audio-s5gen2-device.c
- plugins/audio-s5gen2/fu-audio-s5gen2-hid-device.c
- plugins/audio-s5gen2/fu-audio-s5gen2-impl.c
- plugins/audio-s5gen2/fu-audio-s5gen2-impl.h
- plugins/audio-s5gen2/fu-audio-s5gen2-plugin.c
- plugins/audio-s5gen2/fu-audio-s5gen2.rs
- plugins/audio-s5gen2/meson.build
Typically, BlueTooth devices should be detected by GAIA primary service with if default vendor ID has been used:
* BLUETOOTH\GATT_00001100-d102-11e1-9b23-00025b00a5a5
Unique GUID is constructed with the info read from device:
* BLUETOOTH\GAIA_QCC5171
Example:
├─QCC5171:
│     Device ID:          b67d007c2e3436dd21838d08c9053e07e7902ef6
│     Current version:    1.1.2
│     Vendor:             BLUETOOTH:001D
│     Serial Number:      ABCDEF0123456789
│     Battery:            96% (threshold 10%)
│     GUIDs:              2216161a-9f4e-59f4-ba05-b202e0c28e16 ← BLUETOOTH\NAME_QCC5171
│                         61497166-1419-572c-8da9-15d8460e0d0f ← BLUETOOTH\GAIA_QCC5171
│     Device Flags:       • Updatable
│                         • Device stages updates
│                         • Device …
> audio-s5gen2: initial support of BLE devices

- libfwupdplugin/fu-usb-config-descriptor-private.h
- libfwupdplugin/fu-usb-config-descriptor.c
- libfwupdplugin/fu-usb-config-descriptor.h
- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/meson.build
When using udev to enumerate USB devices we don't use `libusb_config_descriptor` and reimplementing it I misunderstood what the config descriptor was used for.
Add support for mapping the `configuration_value` to a `configuration index`, and in the process unbreak enumerating the Acer D501 dock, and anything else using the cros_ec plugin.
> Parse the config descriptor to unbreak fu_usb_device_get_configuration_index()

- contrib/build-venv.sh
- plugins/mediatek-scaler/README.md
- plugins/mediatek-scaler/fu-mediatek-scaler-device.c
- plugins/mediatek-scaler/fu-mediatek-scaler.rs
- plugins/mediatek-scaler/mediatek-scaler.quirk
Starting from scaler chip 7430, the firmware will go bank 1 in addition to bank 2. The chip will do a self-reboot and update bank 1 internally.
> medaitek-scaler: update bank 1 and add quirk key bank2-only for backward support

- plugins/mediatek-scaler/README.md
- plugins/mediatek-scaler/fu-mediatek-scaler-device.c
- plugins/mediatek-scaler/fu-mediatek-scaler.rs
- plugins/mediatek-scaler/mediatek-scaler.quirk
1. add error tolerance and data verification on byte writing
2. add flag bank2-only for backward compatibility
(cherry picked from commit 4ce7684b5f02a7de22482eb6a7a5f59ace93ebbf)
> mediatek_scaler: update bank 1 with backward support for bank 2

- libfwupdplugin/fu-udev-device-private.h
- libfwupdplugin/fu-udev-device.c
This is better than splitting the `key=value` for each call to `fu_udev_device_read_property()` and also allows us to pre-seed properties when listening on the netlink socket.
> Store the udev properties in a hash table

- contrib/ci/check-source.py
- libfwupdplugin/fu-backend.c
- libfwupdplugin/fu-backend.h
- libfwupdplugin/fu-context-helper.h
- libfwupdplugin/fu-context-private.h
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-security-attr.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fwupdplugin.h
- plugins/redfish/fu-redfish-network.c
- plugins/redfish/fu-redfish-network.h
- plugins/redfish/fu-redfish-plugin.c
- plugins/redfish/fu-self-test.c
- src/fu-device-list.c
- src/fu-device-list.h
- src/fu-engine.c
- src/fu-plugin-list.c
- src/fu-plugin-list.h
- src/fu-self-test.c
- src/fu-udev-backend.c
This allows plugins to get the backend object, which is needed when interfacing with daemons such as NetworkManager that say 'here's a sysfs path' and we need a FuDevice without using GUdevClient.
> trivial: Add the backends to the FuContext

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-i2c-device.c
Also, only add the flags when they're actually used. This saves 600kb of RSS!
> trivial: Use interned refstrings for FuDevice flags

- src/fu-engine.c
Additionally, make sure we recalculate the parent and the child to fix hotplug of the Lenovo ThinkPad Thunderbolt Dock 4.
Fixes https://github.com/fwupd/firmware-lenovo/issues/468
> Recalculate the device supported flag when reparenting devices using ParentGuid

- libfwupdplugin/fu-io-channel.c
If HAVE_POLL_H is defined the non-block behaviour should be used for all modes by default.
> fix: set non-block fu-io-channel behavior by default for RDWR mode

- libfwupdplugin/fu-hidraw-device.c
Tested with the "Nordic Semiconductor ASA Mouse nRF52 Desktop" board.
This was missed in f0e5444, mea culpa.
Fixes https://github.com/fwupd/fwupd/issues/7759
> Add the vendor-id for FuHidrawDevice subclasses

- plugins/amd-gpu/fu-amd-gpu-device.c
This should help with failures triggering the write process in the kernel.
Suggested-by: Richard Hughes <richard@hughsie.com>
> trivial: amd-gpu: read 1 byte instead of 0 bytes

- src/fu-device-list.c
- src/fu-self-test.c
This allows us to use the equivalent-id on a device we'd rather use with a different device-id.
> Respect the device priority when matching in the device list

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
This happens when the device has the same name as the vendor -- which does not make for great UI and is probably a USB descriptor issue.
> Do not set a zero-length device name when matching the vendor name

- libfwupdplugin/fu-usb-device.c
- meson.build
- plugins/dell-k2/fu-dell-k2-pd-firmware.c
- plugins/dell-k2/fu-dell-k2-plugin.c
- plugins/hpi-cfu/fu-hpi-cfu-device.c
This means we can use build-fwupd in the venv like every other target.
> trivial: Add the default homebrew path when looking for usb.ids

- plugins/uefi-capsule/fu-uefi-bootmgr.c
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-capsule/fu-uefi-common.c
- plugins/uefi-capsule/fu-uefi-common.h
- plugins/uefi-capsule/fu-uefi-grub-device.c
- plugins/uefi-capsule/fu-uefi-nvram-device.c
When using systemd-boot, assets aren't stored in a distro lsb-release directory. Look for this first as a preference.
> trivial: look for 'systemd' directory on ESPs

- plugins/amd-gpu/amd_gpu_test.py
- plugins/amd-gpu/fu-amd-gpu-device.c
Apparently the rest of the characters are not relevant for the purpose of making sure a firmware applies to a given part.
So shorten the GUID and only compare 10 characters from the rest.
> amd-gpu: Only compare the first 10 characters of part number

- meson.build
- src/fu-daemon.c
- src/fu-engine.c
- src/fu-util.c
The SOURCE_VERSION key when used elsewhere can cause the wrong results
for user agent or for comparisons of daemon vs client.
(cherry picked from commit 7c8ec80660bca1adf1a783f18a6ed47fbb4e558f)
> Only use SOURCE_VERSION for displaying to a user in --version output

- src/fu-device-list.c
Plugins may look at the runtime version through the bootloader device
and need to have accurate values.
> trivial: copy raw version to bootloader device

- libfwupd/README.md
- libfwupd/fwupd-device.c
- libfwupd/fwupd-device.h
- libfwupd/fwupd.map
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- src/fu-engine.c
- src/fu-util-common.c
We only need this in the daemon, and the client does not need to interact with this in any way.
> Unexport FwupdDevice:UpdateMessage

- libfwupdplugin/meson.build
- meson.build
- plugins/meson.build
- plugins/mtd/fu-self-test.c
- plugins/redfish/fu-redfish-network.c
- src/fu-engine.rs
- src/fu-udev-backend.c
- src/fu-usb-backend.c
- src/meson.build
This is way more efficient as we only need the sysfs path and do all the probing ourselves. It might even work on Android.
> Listen to the netlink udev socket rather than using GUdevClient

- libfwupdplugin/fu-drm-device.c
fwupd doesn't need to look at render nodes, and these also are not accessible for DRM resources when the screen is off.
Fixes: https://github.com/fwupd/fwupd/issues/7816
> trivial: exclude non-card DRM devices

- plugins/vli/meson.build
- plugins/vli/vli-cablematters.quirk
Why Howdy, 
It's us; inconspicuous, reoccurring, characters. On behalf of Cable Matters, we're adding support for their device. We also have some questions about using pre-commit hooks:
1. Is it intentional to have the developer `git add .pre-commit-config.yaml` in every PR?
2. Is there an official, unofficial guide for pushing branches and restoring files when using venv/hooks?
Thanks!
reference: [guide](https://fwupd.github.io/libfwupdplugin/building.html?q=pre-commit)
> vli: add Cable Matters

- data/bash-completion/fwupdmgr
- data/bash-completion/fwupdtool
- docs/device-emulation.md
- docs/fwupd.conf.md
- libfwupdplugin/fu-config.c
- src/fu-engine-config.c
- src/fu-engine-config.h
- src/fu-engine.c
This allows us to record the emulations of devices we can't hotplug, for instance NVMe drives.
> Allow specifying devices to emulate in the config file

- libfwupdplugin/fu-device-event-private.h
- libfwupdplugin/fu-device-event.c
- libfwupdplugin/fu-device-event.h
- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.h
In some plugins like nvme we have to record the structure contents, rather than just the byte array as a 2nd buffer is passed by pointer address.
Make some of the API non-private to make this possible.
> Allow plugins to save emulation data directly

- data/device-tests/legion-hid2.json
- data/device-tests/meson.build
This doesn't seem to be working but I'm not really sure why at this point.
> trivial: Add emulation data for legion-hid2

- libfwupd/fwupd-plugin.c
This makes it easier to compare the output of 1_9_X and the main branch.
> trivial: Don't show plugin flags if they're unset

- contrib/PKGBUILD
- contrib/ci/dependencies.xml
- contrib/fwupd.spec.in
- contrib/snap/snapcraft.yaml
- meson.build
- plugins/thunderbolt/meson.build
We're only using it in the thunderbolt tests, and we can redesign those to use emulation for 2.0.x.
It's a much clearer message dropping the dep completely.
> Remove gudev as a required dep

- meson.build
when git is not found the whole conf var is skipped, and that fails to compile
> meson: fix source version outside git

- contrib/pcap2emulation.py
These get the script at least closer to working with 
https://gitlab.com/asus-linux/reverse-engineering/-/blob/master/rog-ally-x/update-capture/update-312-to-312/ally-x-312_t01_update.pcap?ref_type=heads
but there still seems to be some other mismatches with how the endpoints have more HID descriptors than the script expects.
> Fixes for pcap2emulation

- libfwupdplugin/fu-block-device.c
- libfwupdplugin/fu-serio-device.c
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-udev-device.h
- plugins/scsi/fu-scsi-device.c
Splitting on /sys isn't the right thing to do, as on ChromeOS we have a path like `~/sys-apps/fwupd/src/tests/sys/devices` -- and we only want the right-most /sys suffix.
> trivial: Provide a helper to get the FuUdevDevice devpath

- data/bash-completion/fwupdmgr
- data/bash-completion/fwupdtool
- data/tests/fwupd.sh
- docs/device-emulation.md
- docs/fwupd.conf.md
- libfwupdplugin/fu-config.c
- policy/org.freedesktop.fwupd.policy.in
- src/fu-dbus-daemon.c
- src/fu-engine-config.c
- src/fu-engine-config.h
- src/fu-engine.c
- src/fu-self-test.c
- src/fu-util.c
There isn't any reason to keep the turned off, it just makes it more
difficult for users to record and load emulation data which would
mean that a graphical client that wants to onboard an emulation flow
would have a harder time.
Enable it by default instead.
> trivial: Enable emulation support by default

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupdplugin/fu-udev-device.c
- plugins/amd-gpu/amd_gpu_test.py
- src/fu-engine.c
- src/fu-util-common.c
- src/fu-util.c
This means we only show supported devices when using 'fwupdmgr emulation-tag' and in any future gnome-firmware GUI elements.
> Tag devices that can be emulated

- plugins/kinetic-dp/fu-kinetic-dp-plugin.c
> kinetic-dp: Load GUIDs before adding the device to the daemon

- policy/org.freedesktop.fwupd.policy.in
- src/fu-dbus-daemon.c
This lets the GUI restart the daemon to automatically tag for emulation internal firmware devices.
> Add Polkit authentication action for quitting the daemon

- data/bash-completion/fwupdmgr
- data/bash-completion/fwupdtool
- docs/fwupd.conf.md
- libfwupd/fwupd-request.c
- libfwupd/fwupd-request.h
- libfwupdplugin/fu-config.c
- policy/org.freedesktop.fwupd.policy.in
- src/fu-engine-config.c
- src/fu-engine-config.h
- src/fu-engine.c
- src/fu-history.c
- src/fu-history.h
- src/fu-self-test.c
This also simplifies loading the daemon -- rather than having an in-memory hashtable of IDs *and* a config file array, we can instead use the database like a database and only have one codepath for internal and hotplugged devices.
The tagged-for-emulation device ID is also not the kind of thing an admin would want to set anyway.
> Save the emulation-tag devices to the database rather than the config file

- subprojects/libxmlb.wrap
This will make subprojected builds like snap pick up the new release.
> trivial: subprojects: bump the libxmlb version to 0.3.20

- libfwupdplugin/meson.build
Currently cross compiling for android gives undefined symbols. This reuses the linux ones.
> Use 'fu-common-linux.c' when compiling for android

- libfwupdplugin/fu-intel-thunderbolt-nvm.c
This regressed in d1c5d5bd9d050f204c59e25bc9792dc95b780d3f -- for some reason `FuIntelThunderboltNvm` was reading back the entire byte buffer of the parent `FuIntelThunderboltFirmware` for every NVM read.
If we use the actual stream we can avoid loading a `GMemoryInputStream` and don't also have to worry about setting the DIGITAL offset to the NVM offset. It should also be quicker to load too!
> Fix loading FuIntelThunderboltNvm

- meson.build
This reverts commit 774b87fed0c6addd49cdc65a3ecc24923f7c76ae.
We can update the subproject, but we can't raise the deps in a stable branch otherwise we make it really hard to build for RHEL and Ubuntu LTS.
> Revert "trivial: bump libjcat and passim deps"

- subprojects/json-glib.wrap
Currently building using the libjcat and json-glib-1.0 subprojects
```bash
meson setup _build --force-fallback-for json-glib-1.0,libjcat -Djson-glib:documentation=disabled
```
will fail with
```
Dependency json-glib-1.0 found: NO found 1.5.1 but need: '>= 1.6.0' (cached)
```
This is because libjcat includes a wrap file for json-glib `1.5.1` but fwupd specifies `1.6.0`.
This solves the issue by adding a wrap file pulling in the most recent version. An alternative option would be bumping the libjcat wrap file to `1.6.0`.
> Add json-glib wrap file to override libjcat

- .github/workflows/matrix.yml
> trivial: Use macos-latest in CI as macos-12 is going away soon

- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-pci-device.c
- libfwupdplugin/fu-quirks.c
- libfwupdplugin/fu-quirks.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-usb-device-fw-ds20.c
This doubles the size of the quirk database, but means we're much less likely to show 'Unknown Device' as the device name.
> Save the usb.ids and pci.ids name in the quirk database

- contrib/ci/debian.sh
The libxmlb 0.3.20 package causes CI failures but 0.3.21 hasn't migrated to testing yet.  Force it to install to avoid issues for now.
> trivial: ci: add a workaround for Debian CI failure

- data/bash-completion/fwupdtool
- data/tests/fwupdtool.sh
- src/fu-tool.c
This makes it easy to explain to OEMs how semver comparisons are made.
> Add a vercmp command to fwupdtool

- libfwupdplugin/fu-coswid-common.c
Use the correct getter for a bytestring.
> trivial: Fix a cbor test failure on Debian 12

- plugins/cros-ec/fu-cros-ec-usb-device.c
Copy private flags on device replacement, since the update logic is based on them. Added cleanup to drop all flags set during the update.
Added some useful verbosity during debug logging.
Allow to detect and repair the device in case if RW section is broken due some reason, like power failure during flashing for instance.
> cros-ec: fix the update flow

- plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
Prior to 2.x, device response was only validated against NULL. New 2.x refactored code, validate response payload length as well. Skip length validation for responses that has no payload.
[fwupdtool_vv.log](https://github.com/user-attachments/files/17498953/fwupdtool_vv.log)
> Skip payload validation for uninit buffer response

- data/device-tests/gigadevice-gd32vf103.json
- data/device-tests/meson.build
- src/fu-util.c
This is for devices that don't have updates on the LVFS (yet?), but we do want to test that they enumerated correctly.
> Add support for enumerate-only device emulation data

- plugins/vli/fu-vli-pd-device.c
> vli: Ignore LIBUSB_ERROR_NO_DEVICE when rebooting VL103

- libfwupd/meson.build
This is needed when building with `-Dwrap_mode=nodownload` since fwupd.h
is including header files from json-glib.
Fixes #7988
Ping: @superm1 
> trivial: add a dependency on json-glib to the generated pkgconfig file

- libfwupdplugin/fu-cfi-device.c
- plugins/ccgx-dmc/fu-ccgx-dmc-devx-device.c
- plugins/ch341a/fu-ch341a-cfi-device.c
- plugins/pixart-rf/fu-pxi-common.c
- plugins/qsi-dock/fu-qsi-dock-mcu-device.c
- plugins/usi-dock/fu-usi-dock-mcu-device.c
> trivial: Fix some harmless -Wformat warnings with clang 19

- src/fu-device-list.c
Emulation tags are by device ID.  If a device ID has two fwupd devices of different priorities the tag gets added to both.
Lower priority devices aren't added to the engine, but the engine still tries to gather emulation data.
Drop the emulation tag device flag from the lower priority device to ensure the emulation data isn't lost for the higher priority device.
> trivial: remove emulation-tag from lower priority devices

- plugins/dell-k2/dell-k2.quirk
- plugins/dell-k2/fu-dell-k2-dpmux.c
- plugins/dell-k2/fu-dell-k2-ec-hid.c
- plugins/dell-k2/fu-dell-k2-ec-hid.h
- plugins/dell-k2/fu-dell-k2-ec.c
- plugins/dell-k2/fu-dell-k2-ec.h
- plugins/dell-k2/fu-dell-k2-ec.rs
- plugins/dell-k2/fu-dell-k2-ilan.c
- plugins/dell-k2/fu-dell-k2-package.c
- plugins/dell-k2/fu-dell-k2-pd.c
- plugins/dell-k2/fu-dell-k2-plugin.c
- plugins/dell-k2/fu-dell-k2-rmm.c
- plugins/dell-k2/fu-dell-k2-rmm.h
- plugins/dell-k2/fu-dell-k2-rtshub.c
- plugins/dell-k2/fu-dell-k2-wtpd.c
1. Consolidate the update code for the devices managed by ec
2. Use chunk and page for ec relevant update
3. RMM has its own usb handle so separate it from ec subcomponents
4. Add delay time for chunk and page to improve the stability
5. Move per device prepare to the composite level
(cherry picked from commit 6be958827569a116f2890ecdffdc225e8ec6a99b)
> dell-k2: rework the update flow for ec managed devices

- .github/workflows/matrix.yml
- README.md
I'm generally more happy with codecov having seen it in action the last few days.  I like the inline warnings on missing coverage, the view of coverage of patches and project and it's a lot faster UI.
Drop coveralls from CI.
> trivial: ci: drop coveralls

- .github/workflows/matrix.yml
- contrib/PKGBUILD
- contrib/ci/arch-test.sh
- contrib/ci/fedora-test.sh
- contrib/fwupd.spec.in
Some specific distro builds are the only ones covering certain thing and codecov is supposed to merge automatically.
Link: https://docs.codecov.com/docs/merging-reports
> trivial: enable code coverage for all 'matrix' builds

- .github/workflows/matrix.yml
Until we have https://github.com/fwupd/fwupd/issues/8024 figured out.
> trivial: disable codecov for Fedora for now

- contrib/ci/fedora-test.sh
- libfwupdplugin/fu-string.c
- libfwupdplugin/fu-string.h
- src/fu-engine.c
I don't really expect this to work right now, but want to see if it stands out what's wrong.
> trivial: enable emulation-tag during Fedora testing

- contrib/launch-venv.sh
Due to the wrapper launching fwupdmgr with sudo the default owner for any saved emulations is root.  This makes working with saved emulations more annoying.  Adjust the owner to the user after successfully saving the emulation.
> trivial: venv: Adjust permissions of saved emulation

- contrib/ci/dependencies.xml
- libfwupdplugin/fu-bios-settings.c
- libfwupdplugin/fu-self-test.c
Some Lenovo systems the thinklmi driver fails on random attributes. Rather than fail the remaining attributes skip the bad ones.
Fixes: https://github.com/fwupd/firmware-lenovo/issues/456
> Allow individual attributes to fail setup

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-dbx/fu-uefi-dbx-device.c
Addresses https://github.com/fwupd/fwupd/issues/7939
tl;dr: Duplicate the FDE flag code from the UEFI Capsule plugin for UEFI DBX updates
In the issue we discovered that PCR7 is expected to get changed by a `dbx` update:
From https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClientSpecPlat_TPM_2p0_1p04_pub.pdf
Section 2.3.4.8 PCR[7] – Secure Boot Policy Measurements has:
> Platform` Firmware adhering to the policy MUST therefore measure the following values into PCR[7]:
...
6. Entries in the UEFI_IMAGE_SECURITY_DATABASE that are used to validate UEFI Drivers or UEFI Boot Applications in the boot path
Primarily relying on CI runs, `test-fwupd` passed locally.
Output without this patch applied:
```
$ fwupdtool --plugins uefi_dbx get-devices 
Loading… …
```
> Mark UEFI dbx updates as FWUPD_DEVICE_FLAG_AFFECTS_FDE (#7939)

- plugins/asus-hid/README.md
- plugins/asus-hid/asus-hid.quirk
- plugins/asus-hid/fu-asus-hid-child-device.c
- plugins/asus-hid/fu-asus-hid-child-device.h
- plugins/asus-hid/fu-asus-hid-device.c
- plugins/asus-hid/fu-asus-hid-device.h
- plugins/asus-hid/fu-asus-hid-firmware.c
- plugins/asus-hid/fu-asus-hid-firmware.h
- plugins/asus-hid/fu-asus-hid-plugin.c
- plugins/asus-hid/fu-asus-hid-plugin.h
- plugins/asus-hid/fu-asus-hid.rs
- plugins/asus-hid/meson.build
- plugins/asus-hid/tests/asus-hid-setup.json
- plugins/asus-hid/tests/asus-hid.json
- plugins/meson.build
This is only for querying the MCU firmware version for now.  The sequence for writing the firmware update either needs some more RE or some help from ASUS.
@flukejones can I please ask you to test this branch on Ally and Ally X and show the versions it pulls up to see if everything looks sane?
> Add a fwupd plugin for ASUS ROG ally and ROG ally X

- plugins/scsi/fu-scsi-device.c
Properties "device_descriptor" are attached to the UFS host controller, not the UFS memory device. Using Samsung UFS KLUDG4UHGC-B0E1 as an example:
Before:
??KLUDG4UH:
Device ID:          645dd3eabfbffd6d82917cc4a4cddc0487c3187d
Summary:            SCSI device
...
Device Flags:       ? Internal device
? Can tag for emulation
After:
Device ID:          645dd3eabfbffd6d82917cc4a4cddc0487c3187d
Summary:            UFS device
...
Device Flags:       ? Internal device
? Updatable
? Can tag for emulation
fixes: afb22f7cc0 ("trivial: Convert from fu_udev_device_get_sysfs_attr_uint64() to fu_udev_device_read_sysfs()")
> plugins: scsi: Fix UFS device feature discovery

- plugins/scsi/fu-scsi-device.c
The Product ID is 16 bytes long.
Using Samsung UFS KLUDG4UHGC-B0E1 as an example:
Before:
??KLUDG4UH:
Device ID:          645dd3eabfbffd6d82917cc4a4cddc0487c3187d
Vendor:             SAMSUNG (SCSI:SAMSUNG)
GUIDs:              906223b2-9aee-5f6a-b78c-facb87a09056 ?  SCSI\VEN_SAMSUNG&DEV_KLUDG4UH
After: (as expected and like 1.9.22 branch)
??KLUDG4UHGC-B0E1:
Device ID:          645dd3eabfbffd6d82917cc4a4cddc0487c3187d
Vendor:             SAMSUNG (SCSI:SAMSUNG)
GUIDs:              41a057a2-a1ff-5764-bc6f-71aa045706ff ?  SCSI\VEN_SAMSUNG&DEV_KLUDG4UHGC-B0E1
fixes: e915154a8bf ("scsi: Do SG_IO INQUIRY_CMD rather than relying on the udev prober")
> plugins: scsi: Fix SCSI INQUIRY DATA decoding

- plugins/pixart-rf/fu-pxi-ble-device.c
Fix bug in 'fu-pxi-ble-device' where 'set_feature' length was incorrect.
Also correct the typo of debug msg 'self->retransmit_id' to 'self->feature_report_id'.
- [ *] Code fix
>  Fix bug in 'fu-pxi-ble-device' where 'set_feature' length was incorrect

- plugins/asus-hid/asus-hid.quirk
- plugins/asus-hid/fu-asus-hid-child-device.c
- plugins/asus-hid/fu-asus-hid-device.c
During detach to bootloader mode the proxy pointer becomes invalid because the device changes.  Update it explicitly when the children are adopted to the new parent.
> trivial: asus-hid: update the proxy on detach

- libfwupdplugin/fu-io-channel.c
The behaviour was copied in dc3758e -- but it's completely wrong -- we already have `FU_IO_CHANNEL_OPEN_FLAG_NONBLOCK` for when non-blocking opens are needed.
Fixes https://github.com/fwupd/fwupd/issues/8086
> Remove the unconditional O_NONBLOCK flag when opening a FuIOChannel

- plugins/steelseries/fu-steelseries-fizz-tunnel.c
- plugins/steelseries/fu-steelseries-fizz.c
- plugins/steelseries/fu-steelseries-gamepad.c
- plugins/steelseries/fu-steelseries-sonic.c
Removed unneeded equivalent ID causing error message.
Added flag indicating unsigned payload for gamepads and Rival 3 mose.
> Minor fixes for steelseries

- plugins/algoltek-aux/fu-algoltek-aux-firmware.c
- plugins/algoltek-usb/fu-algoltek-usb-firmware.c
- plugins/amd-gpu/fu-amd-gpu-atom-firmware.c
- plugins/asus-hid/fu-asus-hid-child-device.c
- plugins/asus-hid/fu-asus-hid-firmware.c
afaict, these always will return newly allocated char arrays because it may be necessary to insert a trailing null byte.
I tried to check all plugins but I still may have missed some and there is more potential from at least getters for nested structs which return `GByteArray`s that I did not check.
Plugin maintainers please verify that I am not totally wrong here: @YiJaneWu @MasonLyu @superm1
> fix: plug memory leaks from rustgen char* getters

- libfwupdplugin/fu-pefile-firmware.c
- libfwupdplugin/fu-pefile.rs
I tried the `fwupdtool firmware-parse` with `pefile`. I don't have a particular use for it right now, but it seems useful if it decoded the subsystem.
That makes it easy to tell Windows, EFI App, EFI driver apart from oneanother.
Currently it just prints, but might be useful to add to the XML. As a child with `authenticode_hash` seems appropriate?
Sample:
```
> ./venv/bin/fwupdtool firmware-parse CapsuleApp.efi pefile
03:49:57.618 FuFirmware           PE Subsystem 0x000a efi-application
<firmware gtype="FuPefileFirmware">
<data size="0x15408">[GInputStream]</data>
<authenticode_hash>dccba699b7337f8bdba60cfb2c3acbc629661e91654d1666405230963fa23658</authenticode_hash>
<subsystem>efi-application</subsystem>
<firmware>
<id>.text</id>
<offset>0x240</offset>
<data …
```
> pefile: Parse PE subsystem

- plugins/rp-pico/fu-rp-pico-device.c
We already ignore an error but I encounter a different error. This might be because I'm not using the official pico-sdk but instead a rp-rs Rust based one.
https://github.com/ithinuel/usbd-picotool-reset/blob/4aaff7b60ce22d07594185e13690c71f8c8f18ed/src/lib.rs#L117 instead of
https://github.com/raspberrypi/pico-sdk/blob/2.0.0/src/rp2_common/pico_stdio_usb/reset_interface.c#L131
It looks like the code is the same, both don't return anything on the control transfer, just call the bootrom function. So I'm not sure if the behavior I'm seeing is because of the different SDK.
With this change, I can update my device.
Tested on an Adafruit QT Py RP2040.
```
> sudo ./venv/bin/fwupdtool install ~/clone/inputmodule-rs/fwupd/qtpy.cab --allow-reinstall
Loading…                 [********* …
```
> plugins/rp_pico: Ignore expected error

- contrib/ci/debian-x86_64-test.sh
- contrib/fwupd-systemd-fatal-criticals.conf
Inject G_DEBUG=fatal-criticals into the environment for it instead
> trivial: ci: debian: run daemon as a service again

- src/fu-udev-backend.c
It seems `minijail -p` sandboxes getpid() which means we get the very confusing reported PID of *2*. Report this as the error, rather than the very unhelpful `bind to udev socket failed` text.
> Check that getpid() returned a sensible PID

- contrib/launch-venv.sh
This mirrors what the systemd unit does too.
> trivial: venv: set GLIBC_TUNABLES if not set

- plugins/vli/fu-vli-usbhub-device.c
Spotted by Coverity.
Fixes https://github.com/fwupd/fwupd/issues/8104
> vli: Check the USB3 firmware size before erasing

- plugins/asus-hid/fu-asus-hid-device.c
The datasz is the number of bytes returned, not the size of the source buffer.
> asus-hid: Actually be safe when using fu_memcpy_safe()

- docs/hsi-tests.d/org.fwupd.hsi.Amd.SmmLocked.json
- libfwupdplugin/fu-device-metadata.h
- plugins/cpu/README.md
- plugins/cpu/cpu.quirk
- plugins/cpu/fu-cpu-device.c
- plugins/cpu/fu-cpu-plugin.c
- plugins/msr/fu-msr-plugin.c
This adds checks for the microcode versions in all datacenter CPU processors, and Zen 1, Zen 2, Zen 3, and 4 client processors.
Datacenter graphics and embedded processors are currently excluded.
> Add additional version checks for AMD Sinkclose

- .github/workflows/ci.yml
- .github/workflows/matrix.yml
- .github/workflows/pull-request-reviews.yml
- .github/workflows/release.yml
This should ensure that the artifacts are created and always tied to the same job.
> ci: Move docs and Windows publishing into the matrix reusable workflow

- plugins/dell-kestrel/fu-dell-kestrel-ec.c
- plugins/dell-kestrel/fu-dell-kestrel-ec.rs
1. Use a generic name for the PD device.
2. Restrict the firmware size for the LAN device.
3. Improve code readability for device locking.
> dell-kestrel: restrict firmware size according to hardware

- docs/tutorial.md
And bring `fu_device_sleep` up to date.
> docs: clarify difference prepare/prepare_firmware

- plugins/msr/fu-msr-plugin.c
Any CPUs that are not vulnerable to Sinkclose don't have any known mitigations needed right now.  Don't crash the MSR plugin for this scenario.
Fixes: https://github.com/fwupd/fwupd/issues/8161
> trivial: msr: fix a crash on unrecognized AMD CPUs

- libfwupdplugin/fu-fdt-firmware.c
This seems to affect all MediaTek-based Chromebooks.
> Parse FDTs with missing END tokens

- libfwupdplugin/fu-rustgen-struct.h.in
- plugins/ccgx-dmc/fu-ccgx-dmc-devx-device.c
- plugins/genesys/fu-genesys-usbhub-device.c
- plugins/genesys/fu-genesys-usbhub-firmware.c
- plugins/vli/fu-vli-usbhub-pd-device.c
(cherry picked from commit d2b5dcef027d99538a99bf836ef5aefde41083e6)
> rustgen: Define an 'unref' function for custom structs

- contrib/ci/check-source.py
- libfwupd/fwupd-thread-test.c
- plugins/genesys/fu-genesys-usbhub-device.c
- plugins/mediatek-scaler/fu-mediatek-scaler-device.c
- plugins/redfish/fu-redfish-plugin.c
- src/fu-dbus-daemon.c
- src/fu-idle.c
Use a predicatable token value to make emulation possible.
> trivial: Do not allow plugins to use g_random_int_range()

- plugins/realtek-mst/fu-realtek-mst-device.c
The original reference to the `GBytes` is never going to be unref'ed, `fu_firmware_new_from_bytes()` takes its own reference to the supplied `GBytes`.
> fix(realtek-mst): fix refcounting memory leak

- meson.build
- meson_options.txt
When setting meson's dependency `required` argument to `false`, meson will automatically enable or disable the dependency based on the build environment.
Adds two meson options to manually disable `blkid` and `valgrind` dependencies to guarantee a consistent build with the same runtime dependencies independent of the build environment.
Similar: #7877
> trivial: allow controlling unrequired dependencies

- plugins/logitech-hidpp/fu-logitech-hidpp-device.c
Device might send additional debug bytes in the response, which were included into the next query, potentially affecting to device internals. Recreate the send buffer before querying entities.
Example, before the patch:
```
16:40:23.201 FuPluginLogitechHidpp host->device:   10 06 02 07 00 00 00 
16:40:23.216 FuPluginLogitechHidpp device->host:   11 06 02 07 04 **66 40** 11 9e 00 02 b3 4e 00 00 00 00 00 01 00 
16:40:23.217 FuPluginLogitechHidpp firmware entity count is 4
16:40:23.217 FuPluginLogitechHidpp host->device:   10 06 02 17 00 **66 40** 
16:40:23.239 FuPluginLogitechHidpp device->host:   11 06 02 17 01 **4c 44** 00 01 00 00 00 00 00 00 e5 4a d6 8d 00 
16:40:23.240 FuPluginLogitechHidpp host->device:   10 06 02 17 01 **4c 44** 
16:40:23.254 FuPluginLogitechHidpp device->host:   11 …
```
> logitech-hidpp: trivial cleanup while fetching info

- plugins/amd-gpu/fu-amd-gpu-device.c
This should release the fd so that fwupd doesn't show up as drm master anymore.
Fixes: https://github.com/fwupd/fwupd/issues/7929
> amd-gpu: Deinitialize after getting marketing name

- plugins/dell-kestrel/fu-dell-kestrel-ec.c
- plugins/dell-kestrel/fu-dell-kestrel-rmm.c
- plugins/dell-kestrel/fu-dell-kestrel-rtshub.c
Add ONLY_WAIT_FOR_REPLUG to all final devices or subclasses.
Fixes https://github.com/fwupd/fwupd/issues/8183
> dell-kestrel: Do not show 'Device has been removed' as the device error

- contrib/ci/oss-fuzz.py
- subprojects/gi-docgen.wrap
- subprojects/json-glib.wrap
This should make CI more impervious to GNOME server issues.
> trivial: ci: check out from Github mirrors for GNOME content

- contrib/ci/check-source.py
- libfwupd/fwupd-common.c
- libfwupdplugin/fu-hwids.c
- libfwupdplugin/fu-mem.c
- plugins/bcm57xx/fu-bcm57xx-device.c
- plugins/bcm57xx/fu-bcm57xx-recovery-device.c
- plugins/dell-dock/fu-dell-dock-ec.c
- plugins/dell-dock/fu-dell-dock-hid.c
- plugins/dell-dock/fu-dell-dock-mst.c
- plugins/dfu/fu-dfu-target-avr.c
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/synaptics-rmi/fu-synaptics-rmi-firmware.c
- plugins/tpm/fu-tpm-v2-device.c
- plugins/wacom-usb/fu-wac-device.c
They should be using one of the safe helpers or rustgen instead.
> trivial: Do not allow new plugins to use GUINT32_FROM_BE

- plugins/pci-mei/fu-pci-mei-plugin.c
I don't know what Hfsts is, but we store the data in elements 1 through 6, leaving element 0 unused, so we're iterating through the data incorrectly.
> pci-mei: fix debug logging of Hfsts data

- plugins/thunderbolt/fu-thunderbolt-controller.c
- plugins/thunderbolt/fu-thunderbolt-device.c
- plugins/thunderbolt/fu-thunderbolt-device.h
- plugins/thunderbolt/fu-thunderbolt-retimer.c
TBT3 devices: keep at 50
USB4 devices: adjust to 1
retimers: adjust to 1
This will help avoid running into a kernel bug that makes fwupd retry reading retimer NVM version 50 times.
Link: https://github.com/fwupd/fwupd/issues/8200
> Adjust number of retries to read thunderbolt nvm version

- data/meson.build
We need `block-blkext rw` for `ioctl(BLKSSZGET)`, otherwise we fall back to the default of 512 bytes.
Fixes https://github.com/fwupd/fwupd/issues/7967
> Fix UEFI capsule updates when using 4096 byte NVME blocksize

- src/fu-self-test.c
Just disable the vendor mapping; we're not supposed to be testing the quirk loading, we're testing the device setup.
> trivial: Fix a self test failure on ChromeOS

- libfwupdplugin/fu-progress-private.h
- libfwupdplugin/fu-progress.c
- libfwupdplugin/fu-self-test.c
This reduces startup time a little.
> trivial: Do not connect percentage-changed if the fraction is less than 0.1%

- libfwupdplugin/fu-composite-input-stream.c
- libfwupdplugin/fu-input-stream.c
- libfwupdplugin/fu-self-test.c
We need to keep track of the current offset of the composite stream, rather than just the offset within the partial stream.
> Never read more of the composite stream from a partial stream

- plugins/vli/fu-vli-usbhub-device.c
When the device receives the attach command, it immediately resets itself and does not complete the command. So  it may cause LIBUSB_ERROR_IO and get error _code FWUPD_ERROR_READ.
> vli: hub attach command result

- data/fwupd.service.in
Necessary for "DeviceAllow=block-sd rw" to be resolved by systemd at unit startup. rp2040 and other UF2 devices will present an USB Storage (which uses the sd_mod kernel module), and some of them (notably rp2040) only show up in a replug sequence.
See systemd.resource-control(5) for documentation. https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#DeviceAllow=
Fixes: fwupd/fwupd#8265
> Probe sd_mod before starting

- contrib/ci/arch-test.sh
Base containers are only created once per day, but if the arch metadata is out of date then the test job could fail.  Always update arch metadata during test to avoid this failure.
> trivial: ci: update metadata during arch tests

- docs/tutorial.md
- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-device.rs
- libfwupdplugin/fu-mei-device.c
- libfwupdplugin/fu-plugin.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/meson.build
- plugins/ata/fu-ata-device.c
- plugins/colorhug/fu-colorhug-device.c
- plugins/dell-dock/fu-dell-dock-plugin.c
- plugins/ebitdo/fu-ebitdo-device.c
- plugins/intel-usb4/fu-intel-usb4-plugin.c
- plugins/lenovo-thinklmi/fu-lenovo-thinklmi-plugin.c
- plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
- plugins/nvme/fu-nvme-device.c
- plugins/redfish/fu-redfish-device.c
- plugins/test/fu-test-plugin.c
- plugins/thelio-io/fu-thelio-io-device.c
- plugins/uefi-capsule/fu-uefi-device.c
- plugins/uefi-recovery/fu-uefi-recovery-plugin.c
- plugins/vbe/fu-vbe-simple-device.c
- plugins/wacom-raw/fu-wacom-emr-device.c
- src/fu-device-list.c
- src/fu-engine.c
- src/fu-history.c
- src/fu-release.c
- src/fu-self-test.c
The old code just removed all the FwupdDevice baseclass instance IDs before copying the new superclass IDs -- which was a bit of a hack and only just about worked.
The new code adds the instance IDs to a FuDevice-specific list, which is then moved into the baseclass when running FuDevice->setup(). This allows two things; only doing the quirk match once per duplicate ID, and also doing the incorporate of IDs in the proper way.
> Properly handle FU_DEVICE_PRIVATE_FLAG_NO_GENERIC_GUIDS

- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fu-usb-device.h
- plugins/qc-s5gen2/README.md
- plugins/qc-s5gen2/fu-qc-s5gen2-hid-device.c
- plugins/qc-s5gen2/qc-s5gen2.quirk
0A12:4007 pair is owned by Qualcomm and set as example in their ADK. However a lot of vendors are using that VID:PID pair as is for their products, so we can't distinguish devices.
Hopefully ADK requires to set manufacturer and product names in `subsys7_config3.htf`: USBProductString and USBManufString.
For USB device they are recognized as iManufacturer and iProduct.
Access to iManufacturer and iProduct is required, so exposing `fu_usb_device_get_manufacturer_index()` and `fu_usb_device_get_product_index()` from USB devices.
That allows to identify the target device with unique GUID, based on 4 parameters: VID, PID, Manufacturer and Product name.
Setting the `no-generic-guids` flag prevents devices from updating for generic GUID but allows to detect devices with it, showing unique GUID …
> qc-s5gen2: custom GUID for USB devices

- plugins/uefi-capsule/fu-uefi-device.c
Seen on the LVFS from a CoD update, and matches what we do further up the file...
> uefi-capsule: Do not record the ESP path if it is not set

- src/fu-tool.c
Update calls install release which calls install.  The device changed signal is connected in update.
This fixes pre-emptively trying to match devices to releases causing the signal to apply to wrong devices.
Fixes: https://github.com/fwupd/fwupd/issues/8282
> trivial: fu-tool don't connect device changed signal for update

- plugins/modem-manager/fu-firehose-updater.c
- plugins/modem-manager/fu-firehose-updater.h
- plugins/modem-manager/fu-mm-device.c
- plugins/modem-manager/fu-mm-device.h
- plugins/modem-manager/fu-sahara-loader.c
- plugins/modem-manager/fu-sahara-loader.h
- plugins/modem-manager/modem-manager.quirk
Some devices do not support the zero-length packet (zlp) feature. Adds a new flag `disable-zlp` that removes zlp support for devices requiring to do so.
Also adds Fibocom NL668-EAU to supported devices which depends on this flag.
> modem-manager: Add support for devices without zero-length packets

- plugins/modem-manager/fu-firehose-updater.c
When getting a `FuChunk *` with `fu_chunk_array_index` and then setting that `FuChunk`'s bytes, we won't update the bytes in the chunk array since `fu_chunk_array_index` gives a copy of the chunk, not a reference to it.
> modem-manager: Fix Firehose padding

- plugins/acpi-dmar/fu-self-test.c
- plugins/acpi-facp/fu-self-test.c
- plugins/acpi-ivrs/fu-self-test.c
- plugins/ata/fu-self-test.c
- plugins/nvme/fu-self-test.c
- plugins/synaptics-mst/fu-self-test.c
- plugins/synaptics-prometheus/fu-self-test.c
- plugins/tpm/fu-self-test.c
This should help coverage for any installed tests that are launched through gnome-desktop-test-runner.
If the files are missing they'll be skipped, just as before.
> trivial: drop requirement for `CI_NETWORK` variable in tests

- .codecov.yml
We're not adding to the blocklist, instead we're just remapping >40% as yellow, and >60% as green. As we're dealing with real hardware, trying to cover every error path is essentially impossible, and not useful.
> Make the coverage stats less scary

- contrib/ci/arch.sh
- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- plugins/uefi-dbx/fu-self-test.c
- plugins/uefi-dbx/fu-uefi-dbx-device.c
- plugins/uefi-dbx/fu-uefi-dbx-device.h
- plugins/uefi-dbx/fu-uefi-dbx-plugin.c
- plugins/uefi-dbx/fu-uefi-dbx-snapd-notifier.c
- plugins/uefi-dbx/fu-uefi-dbx-snapd-notifier.h
- plugins/uefi-dbx/meson.build
- plugins/uefi-dbx/tests/snapd.py
This a v2 draft PR (see https://github.com/fwupd/fwupd/pull/7861 for previous proposal) which introduces integration of fwupd with snapd in the context of UEFI DBX updates. The main use case is Ubuntu Core systems, especially those with full-disk encryption (FDE).
In detail, in Ubuntu Core system and hybrid Ubuntu installations using FDE, snapd plays a role in resealing the encryption keys to the TPM. The constructed boot policy includes contents of DBX. In order to have the encryption key unsealed and to keep the system bootable, the DBX update payload must presented to snapd, such that a boot policy will account for the updated content.
The high level idea is for snapd to be notified of a DBX update in progress just before the new content is written to efivars. …
> plugins/uefi-dbx: snapd integration for UEFI DBX updates (v2)

- contrib/ci/arch-test.sh
- contrib/ci/arch.sh
- data/tests/fwupd.sh
- data/tests/fwupdtool.sh
- plugins/logitech-hidpp/meson.build
- plugins/tpm/meson.build
Coverage data is generated and captured in test phase not build phase.
> Run arch simulators during test phase

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
VFAT is a little bit unusual for a filesystem in that it's case-insensitive. This means that if a distro happens to inconsistently use `EFI` vs `efi` cleanup may fail.
For me this happened on a system with a very small (~150MB) ESP, which meant that I couldn't run updates back to back without manually cleaning.
> Fix an issue where UEFI capsule reboot_cleanup wasn't running

- contrib/ci/arch-test.sh
Pass a path to uefi-dbx test artifacts when running mock snapd API service.
Maybe fixes: #8327
> trivial: ci: pass a path to uefi-dbx test artifacts

- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-self-test.c
- libfwupd/fwupd.map
Unlike other libfwupd enums `fwupd_install_flags_to_string()` is missing the matching function to convert back.  Add that function and test coverage for both.
> trivial: Add missing `fwupd_install_flags_from_string()`

- libfwupd/fwupd-client.c
The address returned from `g_network_address_parse()` needs to be freed.
Fixes: 785288abb ("libfwupd: Detect if network is reachable before downloading metadata")
> trivial: fix a small memory leak

- plugins/amd-gpu/fu-amd-gpu-device.c
- plugins/amd-gpu/tests/amd-apu.json
- plugins/amd-gpu/tests/amd-dgpu-navi3x.json
- plugins/amd-gpu/tests/amd-dgpu.json
Recently there have been some cases that the amd-gpu plugin isn't showing update that /should/ be present. This is because the version string was being misinterpreted.
The version string is supposed to be populated by the VBIOS P/N not "the legacy" CSM version string.
A typical string is:
```
XXX-YYYYYYZZ-WWW
```
`XXX-YYYYYY` is used for matching a given board.  This is what was done as part of commit ea8ee1b69 ("amd-gpu: Only compare the first 10 characters of part number").
But the `WWW` is actually a collection of ALL firmware changes and will change any time the firmware is changed in ANY way.  It should be used to reflect the version.
Adjust the `setup()` callback to tokeninze the string and split it. If tokenization fails (such as on really old parts) then just show the CSM string …
> amd-gpu: Split up the VBIOS P/N for the version

- libfwupdplugin/fu-string.c
Strings that failed to convert to an integer aren't necesssarily safe.  Don't show them in error messages.
Link: https://github.com/fwupd/fwupd/issues/8252
> trivial: avoid parsing unsafe strings in error messages

- plugins/audio-s5gen2/README.md
- plugins/audio-s5gen2/audio-s5gen2.quirk
- plugins/audio-s5gen2/fu-audio-s5gen2-hid-device.c
Backported from commit 2e7d708654bda112a7b3d8df2ced3fbc365e58e8:
- used GUsb, see https://github.com/fwupd/fwupd/pull/7412
- GUID is correct, but `fwupd` doesn't show the appropriate instance ID
fixed in https://github.com/fwupd/fwupd/pull/8250, but not backported
```
└─CCC5171X:
Device ID:          c0170efdf195b8590000fa21474253c0d97e7335
Current version:    1.0.1
Vendor:             Collabora (USB:0x0A12)
Serial Number:      5B23541510FF00B52000
GUID:               bf2dbb2f-2174-5041-a77b-0661e752f3ac
Device Flags:       • Updatable
• Device stages updates
• Device can recover flash failures
• Device is usable for the duration of the update
• Signed Payload
```
> (backport) qc-s5gen2: added custom GUID for USB devices

- libfwupdplugin/fu-block-device.c
- plugins/ata/fu-ata-device.c
- plugins/scsi/fu-scsi-device.c
We need to include stddef.h before scsi/sg.h for builds to work with uclibc.
Fixes:
```c
In file included from ../libfwupdplugin/fu-block-device.c:12:
/usr/include/scsi/sg.h:38:3: error: unknown type name ‘size_t’
38 |   size_t iov_len;             /* Length in bytes  */
|   ^~~~~~
```
```c
In file included from ../plugins/ata/fu-ata-device.c:9:
/usr/include/scsi/sg.h:38:3: error: unknown type name ‘size_t’
38 |   size_t iov_len;             /* Length in bytes  */
|   ^~~~~~
```
```c
In file included from ../plugins/scsi/fu-scsi-device.c:9:
/usr/include/scsi/sg.h:38:3: error: unknown type name ‘size_t’
38 |   size_t iov_len;             /* Length in bytes  */
|   ^~~~~~
```
> trivial: fix build with uclibc

- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- plugins/uefi-dbx/fu-dbxtool.c
- plugins/uefi-dbx/fu-uefi-dbx-device.c
We now check *all* ESPs, and so we don't need the additional check.
> trivial: Remove fu_common_is_live_media()

- policy/org.freedesktop.fwupd.policy.in
Allowing this operation for local users without admin authentication seems unnecessary. Raise the setting to `auth_admin` as for the other emulation related actions.
Link: https://github.com/fwupd/fwupd/issues/8360
> Raise authentication requirements for emulation-load

- libfwupdplugin/fu-device.h
- plugins/uefi-dbx/fu-uefi-dbx-device.c
- src/fu-release.c
This also means we can't play the game with unsetting `updatable` as we need this to be true to match the release.
> Only match the device checksum if the protocol matches

- plugins/algoltek-usbcr/fu-algoltek-usbcr-device.c
This avoids showing (null) for a device title.
Fixes: https://github.com/fwupd/fwupd/issues/7909
> trivial: algotek-usbcr: Add a name

- libfwupdplugin/fu-device.c
Change the warning messages for version format conversion to be critical when not a supported build.  This will cause CI failures to avoid letting anything that introduces them get committed.
> trivial: catch version format warnings in CI

- meson.build
- plugins/uefi-dbx/fu-uefi-dbx-common.c
- plugins/uefi-dbx/fu-uefi-dbx-common.h
- plugins/uefi-dbx/fu-uefi-dbx-device.c
The dbx is updated using a kernel interface, and the platform architecture (e.g. is using 32 bit glibc) is not relevant.
> Use the kernel architecture when building the dbx instance ID

- data/tests/fwupd.sh.orig
- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- patch
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-dbx/fu-uefi-dbx-device.c
Whether FDE is detected won't change for the lifecycle of the daemon run and multiple plugins use it.
Move the detection into the context and then let plugins get the information from the context.
> Move FDE detection into the context

- src/fu-tool.c
- src/fu-util.c
This will break json parsing tools.
> trivial: don't show plugin warnings in json mode

- plugins/uefi-dbx/fu-uefi-dbx-plugin.c
As part of the uefi-dbx plugin install process all disks on the system that identify as an ESP are checked for binaries that have been revoked.
On a UEFI system if no ESP was found this typically means that the user hasn't installed udisks and can not properly identify the ESP.
Mark the uefi-dbx device as not updatable and show the user a warning. This matches what the uefi-capsule plugin does.
> uefi-dbx: Don't allow updates when no ESP was found

- plugins/qc-s5gen2/qc-s5gen2.quirk
> qc-s5gen2: add transitional entry for GID8 device

- libfwupdplugin/fu-context.c
- libfwupdplugin/fu-context.h
- plugins/uefi-dbx/fu-self-test.c
- plugins/uefi-dbx/fu-uefi-dbx-plugin.c
- plugins/uefi-dbx/fu-uefi-dbx-snapd-notifier.c
This PR builds on the work that was started in https://github.com/fwupd/fwupd/pull/8210.
This change makes it so we can inhibit DBX updates on systems where fwupd isn't running inside of a snap. To determine if we should inhibit the update, we check if there are any `crypto_LUKS` partitions with an `ubuntu-data-enc` label. The existence of this should indicate an Ubuntu-style FDE system, which requires fwupd to coordinate with snapd to ensure that the system remains bootable.
Note that this may incur some false positives, given that it is possible for a user to have a LUKS partition with that label while not on a system where snapd is managing the FDE setup.
> uefi-dbx: inhibit dbx updates when on an ubuntu-style FDE system

- src/fu-engine.c
> trivial: explicitly set the device for a release when getting history

- libfwupdplugin/fu-device-event.c
- libfwupdplugin/fu-device-event.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-udev-device.c
We need to return with the correct error code if the emulated read is supposed to timeout -- like the bolt receiver expects.
> Save an error event if fu_udev_device_read() fails

- policy/org.freedesktop.fwupd.policy.in
This stops prompting again and again when using multiple emulated files.
> trivial: Use auth_admin_keep when loading emulations

- libfwupdplugin/fu-device.c
- plugins/cros-ec/tests/google-servo-micro.json
These could lead to a false sense of things working correctly when porting a plugin.
Require all emulation events to come in the EXACT same order.
Draft to see if any existing emulations blow up from this.  If they do, it might be better to have a configurable behavior.
 
> trivial: don't allow out of order emulation events

- libfwupdplugin/fu-backend.c
- plugins/uefi-pk/tests/uefi-pk-setup.json
- src/fu-util.c
> trivial: Do not replace the built-in UEFI PK device when emulating

- plugins/thunderbolt/README.md
- plugins/thunderbolt/fu-thunderbolt-common.c
- plugins/thunderbolt/fu-thunderbolt-common.h
- plugins/thunderbolt/fu-thunderbolt-controller.c
- plugins/thunderbolt/fu-thunderbolt-plugin.c
- plugins/thunderbolt/fu-thunderbolt-retimer.c
- plugins/thunderbolt/fu-thunderbolt-retimer.h
- plugins/thunderbolt/thunderbolt.quirk
Also, discover retimers even if the host controller is not-updatable.
> thunderbolt: Reload the retimer version after the payload is deployed

- libfwupd/fwupd-self-test.c
The documentation says:
```
Respawns the test program to run only test_path in a subprocess.
```
So I'm suspicious that maybe we're not running the right tests! Hopefully fixes https://github.com/fwupd/fwupd/issues/8466
> libfwupd: Add a test path to `g_test_trap_subprocess()` calls

- data/tests/fwupdmgr.sh
- data/tests/fwupdtool.sh
HSI isn't supported on non-x86 currently, and this causes autopkgtest failures for Debian.
```
43s Showing security
43s cmd: fwupdtool -v security
43s 19:07:31.573 FuDebug              verbose to info (on console 0)
43s 19:07:31.573 FuEngine             starting fwupd 2.0.6...
43s Host Security ID (HSI) is not supported
43s FAIL: fwupd/fwupdtool.test (Child process exited with code 1)
```
> trivial: tests: Only run fwupdmgr security tests on x86_64

- meson_options.txt
This has been deprecated since meson 1.1.0 and the project now targets >=1.3.0.
Prevents the following warning during configure: 
```
meson_options.txt:339: WARNING: Project targets '>=1.3.0' but uses feature deprecated since '1.1.0': "boolean option" keyword argument "value" of type str. use a boolean, not a string
```
> meson: don't pass strings to boolean options

- libfwupdplugin/fu-self-test.c
We fixed the collapse-empty bug in https://github.com/hughsie/libxmlb/pull/233
> trivial: Fix the self tests with the new libxmlb installed

- libfwupdplugin/fu-firmware.c
> trivial: Fix a critical warnings when exporting empty firmware

- libfwupdplugin/fu-cab-firmware.c
- src/fu-cabinet.c
When the archive is greater in size than 2GB, the `FuStructCabFolder.ndatab` property looks completely wrong as it is truncated to a `uint16_t`.
Looking at the specification, it says:
u2 cCFData: Number of CFDATA structures for this folder.
In reality, however, `gcab` and `cabextract` are a bit more relaxed and keep decoding `CFDATA` structures -- ignoring the value of `cCFData` completely.
We could fix this one of three ways:
* Increasing the block size to 0xFFFF, and redefine it as a `uint16_t`.
- This would mean we'd have to use `fwupdtool` to generate the .cab archive which would give us a maximum payload of still only ~4GB
* Split the data up into multiple CFOLDER sections, and allow CFFILEs to span folders
- This would upset other decoders as it's somewhat out-of-spec
* Use the …
> Support cabinet archives greater in size than 2GB

- libfwupdplugin/fu-cab-firmware.c
- libfwupdplugin/fu-composite-input-stream.c
- libfwupdplugin/fu-efi-common.c
- libfwupdplugin/fu-efi-file.c
- libfwupdplugin/fu-efi-filesystem.c
- libfwupdplugin/fu-efi-section.c
- libfwupdplugin/fu-efi-volume.c
- libfwupdplugin/fu-elf-firmware.c
- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-fmap-firmware.c
- libfwupdplugin/fu-hid-report-item.c
- libfwupdplugin/fu-ifd-firmware.c
- libfwupdplugin/fu-ifwi-cpd-firmware.c
- libfwupdplugin/fu-ifwi-fpt-firmware.c
- libfwupdplugin/fu-intel-thunderbolt-firmware.c
- libfwupdplugin/fu-linear-firmware.c
- libfwupdplugin/fu-pefile-firmware.c
- libfwupdplugin/fu-sbatlevel-section.c
- libfwupdplugin/fu-string.c
- libfwupdplugin/fu-usb-bos-descriptor.c
- libfwupdplugin/fu-usb-descriptor.c
- libfwupdplugin/fu-uswid-firmware.c
Given a bug report of the form:
base was 0xY bytes in size, and tried to create partial @0x0 of 0xZ bytes
..it's not always obvious where to even *start* debugging.
> trivial: Add some error context to fu_partial_input_stream_new()

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-self-test.c
Fixes https://github.com/fwupd/fwupd/issues/8518
> Fix a critical warning when rescanning a device with no GUIDs

- libfwupdplugin/fu-device-private.h
- libfwupdplugin/fu-device.h
The idea here is that a backend can directly tag which plugin to use.
> trivial: Allow plugins to use fu_device_add_possible_plugin()

- plugins/fastboot/fu-fastboot-device.c
This makes it work when switching from modem 'AT' mode.
> fastboot: Retry claiming the interface for 2500ms

- plugins/modem-manager/fu-mm-device.c
Allows modem-manager devices to be specified by GUIDs with PCI SSVID and SSPID as well in LVFS metadata.
> modem-manager: Make PCI SSVID_SSPID based IDs visible

- plugins/modem-manager/modem-manager.quirk
This is not supported on the other variants, and this speeds up enumeration by about 30%.
> modem-manager: Only do the branch detection on EG25GGB

- .editorconfig
- meson.build
With e.g. some European locales you would otherwise get test failures like this:
```
+++ /tmp/a	2025-03-05 12:42:41.767258633 +0100
@@ -15,7 +15,7 @@ FwupdRelease:
Checksum:             SHA1(checksum)
Tags:                 tag
License:              license
-  Size:                 1.2 kB
+  Size:                 1,2 kB
Created:              1970-01-01
Uri:                  location
Homepage:             homepage
```
> fix test failure for certain locales

- data/tests/fwupd.sh
- docs/hsi-tests.d/meson.build
- docs/hsi-tests.d/org.fwupd.hsi.Uefi.MemoryProtection.json
- libfwupd/fwupd-security-attr-private.h
- libfwupd/fwupd-security-attr.c
- plugins/meson.build
- plugins/uefi-mok/README.md
- plugins/uefi-mok/fu-self-test.c
- plugins/uefi-mok/fu-uefi-mok-common.c
- plugins/uefi-mok/fu-uefi-mok-common.h
- plugins/uefi-mok/fu-uefi-mok-plugin.c
- plugins/uefi-mok/fu-uefi-mok-plugin.h
- plugins/uefi-mok/fu-uefi-mok.rs
- plugins/uefi-mok/meson.build
- plugins/uefi-mok/tests/HSIStatus-nx-disabled
- plugins/uefi-mok/tests/HSIStatus-nx-invalid
- plugins/uefi-mok/tests/HSIStatus-nx-valid
- src/tests/efi/mok-variables/HSIStatus
> uefi-mok: Add a plugin to verify UEFI memory protection attributes

- libfwupdplugin/fu-volume-private.h
- libfwupdplugin/fu-volume.c
- plugins/uefi-capsule/README.md
- plugins/uefi-capsule/fu-self-test.c
- plugins/uefi-capsule/fu-uefi-capsule-device.c
- plugins/uefi-capsule/fu-uefi-capsule-device.h
As this is a device flag, this can be set in the quirk file, in the metadata at firmware upload time or added to existing firmware on the LVFS.
Fixes https://github.com/fwupd/fwupd/issues/8462
> uefi-capsule: Add a device quirk to signify that no additional ESP space is required

- plugins/uefi-capsule/fu-uefi-capsule-device.c
- plugins/uefi-capsule/fu-uefi-capsule-device.h
- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-capsule/fu-uefi-nvram-device.c
This allows capsules to be installed by the system's regular bootloader, instead of fwupd-efi.
The bootloader signals support by creating a runtime-accessible UEFI var called `BootloaderSupportsFwupd` with the vendor set to `FU_EFIVARS_GUID_FWUPDATE`, and a one-byte value of 1.
Closes https://github.com/fwupd/fwupd/issues/8504
> uefi-capsule: Add support for capsule installation in the bootloader

- plugins/redfish/fu-redfish-device.c
This matches what the README file and the comment, so make it true in reality.
Based on a patch by Arno DUBOIS <a.dubois@criteo.com>, many thanks.
> redfish: Only use the 'ID' instance ID for quirks

- data/device-tests/meson.build
Since all members of device_tests are returned by the `files()` function, we can just use them regardless of the current working directory.
```
../data/device-tests/meson.build:14: DEPRECATION: Project uses feature that was always broken, and is now deprecated since '1.3.0': str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof..
```
> fix(meson): silence warning about str fmt files

- contrib/test-venv.sh
- data/tests/fwupd_test.py
- data/tests/meson.build
- plugins/meson.build
- plugins/pci-psp/pci_psp_test.py
With the introduction of pygobject 3.52, accessing GIRepository 2.0 is
no longer permitted.
Instead of complicating the test code with conditionalizing between
GIRepository 2.0 and GIRepository 3.0 in override_gi_search_path,
we can drop override_gi_search_path entirely and rely on GIRepository's
own envvar GI_TYPELIB_PATH to help it find our freshly built typelib
Fixes #8569
> Fix build against pygobject 3.52

- plugins/logitech-rallysystem/fu-logitech-rallysystem-plugin.c
Found using `meson configure -Dc_args="-fanalyzer"`
> logitech-rallysystem: Fix a small memory leak when emumerating devices

- contrib/firmware_packager/install_dell_bios_exe.py
Adjust the script to use the correct value.
Suggested-by: Adrien Dorsaz <adrien@adorsaz.ch>
Link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1093432
> trivial: fix "** Expected a Fwupd.DeviceFlags, but got int ***"

- libfwupdplugin/fu-rustgen-enum.h.in
If we see an enum entry of 'Last' then don't create the _LAST auto-define.
Based on a patch by Denis Pynkin <denis.pynkin@collabora.com>, many thanks.
Fixes https://github.com/fwupd/fwupd/issues/8592
> qc-s5gen2: Use the explicit Last value

- plugins/qc-s5gen2/fu-qc-s5gen2-device.c
- plugins/qc-s5gen2/fu-qc-s5gen2.rs
The ac473b8 commit added redefinition of the FU_QC_MORE_DATA_LAST value.
See https://github.com/fwupd/fwupd/issues/8592 for details.
Explicitly rename the value to avoid even occasional intersections.
> qc-s5gen2: rename enum value Last

- plugins/usi-dock/fu-usi-dock-mcu-device.c
This prevents a critical warning of:
1.94.ff is not a valid triplet (guessed plain)
> usi-dock: Correctly format triplet numbers

- plugins/qc-firehose/fu-qc-firehose-impl.c
- plugins/qc-firehose/fu-qc-firehose-impl.h
- plugins/qc-firehose/fu-qc-firehose-raw-device.c
- plugins/qc-firehose/fu-qc-firehose-usb-device.c
- plugins/qc-firehose/tests/qc-eg25ggc.json
- src/fu-engine.c
If the FuDevice->write_firmware() fails then we want to 'recover' the device back to runtime so that the user does not think the modem is bricked.
> qc-firehose: Split out FuDevice->attach() to allow device recovery

- plugins/redfish/fu-self-test.c
Due to bad initialization, tests were not run on the HPE side. This should now be fixed
(as mentioned on #8574)
> redfish: Fix HPE tests

- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- libfwupdplugin/fu-self-test.c
- plugins/qc-firehose/fu-qc-firehose-impl.c
- plugins/test/fu-test-plugin.c
- src/fu-engine.c
- src/fu-self-test.c
> trivial: Allow plugins to restart the install-loop without using hacks

- src/fu-engine.c
- src/fu-engine.h
- src/fu-tool.c
This makes it a lot more valuable as you can use `--plugins` to speed up the engine startup and increase the speed of debugging.
> trivial: Allow installing firmware from emulations in fwupdtool

- plugins/qc-firehose/fu-qc-firehose-impl-common.c
- plugins/qc-firehose/fu-qc-firehose-impl-common.h
- plugins/qc-firehose/fu-qc-firehose-impl.c
- plugins/qc-firehose/fu-qc-firehose-impl.h
- plugins/qc-firehose/fu-qc-firehose-raw-device.c
- plugins/qc-firehose/fu-qc-firehose-sahara-impl.c
- plugins/qc-firehose/fu-qc-firehose-sahara-impl.h
- plugins/qc-firehose/fu-qc-firehose-usb-device.c
- plugins/qc-firehose/fu-self-test.c
- plugins/qc-firehose/meson.build
This also re-implements the FuDevice retry logic in a way that suits firehose; i.e. that we only return with timeout if *all* the requests timeouts add up to the maximum value.
This also allows the given vfunc to end the polling (setting `*done = TRUE`) when we *know* that the command stream is complete.
> qc-firehose: Detect the protocol features if not automatically sent

- libfwupdplugin/fu-context.c
When checking if FUVolume is a valid ESP, also test mount point + lowercase "/efi"
> When checking for ESP, also check for lowercase efi

- src/fu-remote-list.c
We only need to monitor one file, not the entire filesystem.
May help towards https://issues.redhat.com/browse/RHEL-85941
> trivial: Reduce spinlock contention when checking inotify

- data/motd/fwupd-refresh.service.md
The man page is installed to section 8, update the markdown to match.
> trivial: motd: correct fwupd-refresh.service man page location

- libfwupdplugin/fu-efi-load-option.c
- libfwupdplugin/fu-self-test.c
Fixes https://github.com/fwupd/fwupd/issues/8577
> Make the EFI LOADOPT either a path or ShimHive when setting metadata

- src/fu-util.c
Scripts shouldn't be interacting with non-json output.  So add checks to all cases that would prompt for internet connection and adjust behavior accordingly.
> fu-util: Don't show prompts in --json mode

- libfwupd/fwupd-codec.h
- libfwupdplugin/fu-device-event.c
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-usb-device.c
Automatically switch to the compressed version if there are over 1000 events -- it's more useful to see the actual values when debugging emulation failures.
> Record the emulations uncompressed by default

- plugins/redfish/fu-redfish-backend.c
- plugins/redfish/fu-self-test.c
- plugins/redfish/tests/redfish.py
It seems (well, it does not "seems", it just does) that since the "SMC update path" is Redfish standard, it will match other standard Redfish implementations and fail later on. I'm not 100% sure about this matching, I hope it is correct but needs checking and I don't have a Supermicro machine with me.
Would be cool if @flanfly could take a quick look on their side :)
> redfish: Do not match SMC updating method accidentally

- data/meson.build
> trivial: Allow char-wwan_port when using the modem-manager plugin

- data/meson.build
- data/org.freedesktop.fwupd.service.in
This allows the daemon to start automatically even where systemd is unavailable. For context, without the D-Bus service file, fwupdmgr would fail with the following error message:
```
Failed to connect to daemon: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.fwupd was not provided by any .service files
```
I'm not sure whether this should be considered a feature or a bug fix.
> Always build the D-Bus service

- plugins/robots.json
The AI robots have learned how to read the JSON emulation data files and are now downloading files that were only supposed to be used from the CI tests.
Give them some poison instead.
> trivial: Add a dummy JSON linking to the LVFS poison pill firmware

- meson.build
This has libusb_init_context() support needed for binding to udev.
Closes: https://github.com/fwupd/fwupd/issues/8701
> trivial: require libusb 1.0.27

- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/tests/meson.build
- libfwupdplugin/tests/uevent
Fixes https://github.com/fwupd/fwupd/issues/8707
> Fix a crash when paring uevents that are not KEY=VALUE

- docs/hsi-tests.d/org.fwupd.hsi.Amd.SpiReplayProtection.json
- docs/hsi-tests.d/org.fwupd.hsi.Amd.SpiWriteProtection.json
I noticed that `name` and `description` fields were swapped in these two files, so I adjusted them accordingly.
AFAIK Write protection is supposed to be HSI level 2 and Replay protection level 3, so I adjusted the `hsi-level` value accordingly as well.
> trivial/documentation: Swap around SPI Write and Replay protection

- plugins/fastboot/ci.quirk
- plugins/fastboot/fastboot.quirk
- plugins/fastboot/meson.build
This is marked as a pixel3a, but it actually applies to a pixel 9 as well.  We don't plan to be flashing pixel devices with fwupd and this could cause problems with things like /usr/bin/fastboot if fwupd takes the device.
> trivial: drop google pixel fastboot device

- plugins/redfish/fu-redfish-device.c
I don't think this is ever useful.
> redfish: Do not export backup partitions as devices

- plugins/flashrom/fu-flashrom-plugin.c
According to the SMBIOS 3.x spec, if the value for the ROM size at offset 0x9 is 0xff, then the Extended ROM Size field at offset 0x18 should be used instead. Implement this per the SMBIOS 3.x spec.
Reading of BIOS characteristics is moved ahead of the ROM size in order to facilitate cleaner exiting of the function should either of the reads from SMBIOS fail.
Addresses issue #8570
> fu-flashrom-plugin: Fix SMBIOS parsing for ROM size >= 16MiB

- libfwupdplugin/fu-efi-signature-list.c
- libfwupdplugin/fu-efi-x509-signature-private.h
- libfwupdplugin/fu-efi-x509-signature.c
I've confirmed with Microsoft that the new 'Windows' cert is supposed to replace the 'PCA' 2011 one.
> uefi-db: Dedupe the Microsoft Windows Signature Database entry

- libfwupdplugin/fu-context.h
- libfwupdplugin/fu-firmware.h
- libfwupdplugin/fu-progress.h
- src/fu-client.h
- src/fu-engine-request.h
My code was doing fu_firmware_has_flag() rather than fu_firmware_add_flag() and the compiler said nothing...
> trivial: Enforce that we check the return value of fu_firmware_has_flag()

- libfwupdplugin/fu-input-stream.c
- libfwupdplugin/fu-input-stream.h
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-usb-bos-descriptor.c
- libfwupdplugin/fu-usb-descriptor.c
- libfwupdplugin/fu-usb-device.c
- libfwupdplugin/fu-usb-interface.c
Storing the partial stream in the FuUsbDescriptor caused all kinds of lifecycle issues for the file descriptor. Rip it all out and make it simpler, fixing various fd-not-closed issues in the process...
Fixes https://github.com/fwupd/fwupd/issues/8712
> Simplify parsing USB descriptors

- plugins/wacom-usb/fu-wac-module-sub-cpu.c
The fu_srec_firmware_get_records() method is {transfer none) and so we don't need to unref the container.
> wacom-usb: Fix a crash when cleaning up the FuWacModuleSubCpu

- plugins/bnr-dp/meson.build
Just like the other plugins under drm_dp_aux_dev subsystem, the plugin depends on udev support and should check if the host machine is Linux.
> bnr-dp: Build only for Linux host machine

- plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
- plugins/mtd/fu-mtd-device.c
- plugins/synaptics-vmm9/fu-synaptics-vmm9-device.c
Otherwise we cannot dump the blob to disk...
> trivial: Cache the stream when using FuDevice->read_firmware()

- plugins/uefi-dbx/uefi-dbx.quirk
> uefi-dbx: Do not allow updates on the HP 84G22PC (Elitebook 845 Gen10)

- docs/hsi-tests.d/org.fwupd.hsi.Uefi.Db.json
Maybe fixes https://github.com/fwupd/fwupd/issues/8787
> trivial: Link into the UEFI Secure Boot Certificates page from the HSI failure

- libfwupdplugin/fu-device.c
- src/fu-self-test.c
If we forget then `FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG` will do the non-obvious thing and only wait if the device uevent if already pending.
> trivial: Check that the plugin author has used fu_device_set_remove_delay()

- data/bash-completion/fwupdmgr
- libfwupd/fwupd-enums.c
- libfwupd/fwupd-enums.h
- libfwupd/fwupd-self-test.c
- src/fu-dbus-daemon.c
- src/fu-util.c
This allows me to do `fwupdmgr device-emulation` when an actual physical device is plugged into a different USB socket than the emulation was recorded for.
> Provide a way for the client to restrict the GUID list to an emulated device

- plugins/uefi-pk/fu-uefi-pk-device.c
- plugins/uefi-pk/fu-uefi-pk-device.h
- plugins/uefi-pk/fu-uefi-pk-plugin.c
This will be very useful to debug and filter KEK deployment failures.
> uefi-pk: Include the UEFI PK certificate key ID in the uploaded report

- src/fu-engine-emulator.c
This fixes a regression from 213f551.
> Fix fwupdmgr emulation-save when recording FuUdevDevice superclass devices

- libfwupdplugin/fu-efi-x509-device.c
The enhancement in 5ced1c18 broke installing KEKs as an EFI_SIGNATURE_LIST has a list of signature images. Check the firmware GType to decide on what to do.
> uefi-kek: Fix regression preventing installation of KEKs

- libfwupdplugin/fu-device-event.c
- libfwupdplugin/fu-device.c
- libfwupdplugin/fu-device.h
- plugins/pci-psp/fu-pci-psp-device.c
- plugins/pci-psp/meson.build
- plugins/pci-psp/tests/pci-psp-strix-enumerate.json
- plugins/pci-psp/tests/pci-psp-strix.json
The AGESA version on AMD platforms is like a meta version to indicate what platform initialization code the BIOS was built with.
On newer platforms this is stored in an SMBIOS type 40 entry.
> Include AGESA version in summary of secure processor device

- plugins/intel-cvs/fu-intel-cvs-device.c
The ioext-main branch of usbio cannot cope with a device replug.
> intel-cvs: Do not wait for the device to 'come back'

- plugins/legion-hid2/fu-legion-hid2-child-device.c
- plugins/legion-hid2/fu-legion-hid2-child-device.h
- plugins/legion-hid2/fu-legion-hid2-device.c
- plugins/legion-hid2/fu-legion-hid2-plugin.c
- plugins/legion-hid2/fu-legion-hid2.rs
- plugins/legion-hid2/meson.build
- plugins/legion-hid2/tests/legion-hid2.json
On Legion-hid2 devices the touchpad is connected to the MCU and some information can be queried from that. Create child devices as such.
Update support for this device will be later - this is read only for now.
> legion-hid2: Add support for reading touchpad child device

- plugins/synaptics-vmm9/fu-synaptics-vmm9-device.c
There is a timing issue where `RC_CMD_ENABLE` intercepts `RC_CMD_DISABLE` and continues to receive status report from previous command (i.e. `RC_CMD_DISABLE`).  Adding 500 ms delay between `disable` and `enable` givens sufficient time to ensure that `RC_CMD_DISABLE` is completed.
<details>
```
01:50:56.124 FuDevice             using 963961de6b2409c2b3185b18fd3d322bd136ae7c for 3-1.3.4.2
01:50:56.125 FuPluginSynapticsVmm9 FuStructHidSetCommand:
size: 0xc
payload: FuStructHidPayload:
cap: 0x0
state: 0x0
ctrl: 0x82 [disable-rc-busy]
sts: 0x0 [success]
offset: 0x0
length: 0x0
fifo: 0x7200000000000000000000000000000000000000000000000000000000000000
checksum: 0x0
01:50:56.125 FuHidDevice          HID::SetReport [wValue=0x0201, wIndex=0]:
01 00 0c 00 00 82 00 00 00 00 00 00 …
```
> synaptics-vmm9: add delay between rc_disable and rc_enable

- plugins/uefi-db/fu-uefi-db-plugin.c
- plugins/uefi-dbx/fu-uefi-dbx-plugin.c
- plugins/uefi-kek/fu-uefi-kek-plugin.c
This fixes 19bd0257 to actually work from other plugins.
> Use the UEFI PK report attributes for the other UEFI plugins

- plugins/thunderbolt/fu-thunderbolt-controller.c
The only vendor for TBT3 controllers is Intel, and all the Intel controllers use signed payloads.
> trivial: thunderbolt: set all gen 3 controllers as signed

- plugins/legion-hid2/fu-legion-hid2-device.c
Downgrades need to be opted in from the client and this will work as long as the firmware doesn't reject it.  If/when the firmware rejects it, it will happen at end of process instead.
See https://github.com/fwupd/fwupd/issues/8841
> legion-hid2: Allow downgrades without --force

- src/fu-tool.c
Reboot is already prompted by all callers to fu_util_install(), it's
not necessary to call for individual releases.
Fixes: #8846
> fu-tool: drop an extra call to prompt for reboot

- src/fu-device-list.c
This ensures that if we process all the pending events -- which could be a *lot* in the case of composite devices like docks.
We shouldn't have to set a longer timeout just to process pending events.
> Process all pending event sources when waiting for replug

- plugins/intel-gsc/igsc.quirk
This PR updates the intel-gsc/igsc.quirk with the following:
- Adds Arc Pro B50 and B60 Battlemage products.
- Adds `Name` param for each existing & new Battlemage product.
> Update igsc.quirk for Intel Arc Battlemage products

- plugins/modem-manager/modem-manager.quirk
Quectel EC25/EG25 allow updating with either DFOTA, Firehose or Fastboot.
Fall back to ModemManager's `get_update_settings` for those devices since setting the `GType = ` quirk does not allow more than one type.
> modem-manager: Allow multiple GTypes for Quectel EC25/EG25

- src/fu-engine.c
- src/fu-engine.h
- src/fu-release.c
- src/fu-release.h
- src/fu-self-test.c
- src/fu-tool.c
This means passing around the FuRelease for longer.
> Allow plugins to know the firmware filename

- plugins/logitech-scribe/fu-logitech-scribe-device.c
- plugins/logitech-scribe/logitech-scribe.quirk
fwupdmgr reporting same firmware, after the upgrade. Added missing FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG 
Moved config setting from quirk to device class
> logitech-scribe: add wait for replug

- libfwupdplugin/tests/meson.build
> Fix warning during install because of missing follow_symlinks setting

- src/fu-engine-requirements.c
- src/fu-engine.rs
- src/fu-self-test.c
With this commit it is now possible to say:
* Require fwupd 1.9.7 if fwupd branch 1.9.x, or
* Require fwupd 2.0.12 otherwise
This allows us to backport fixes and features to other branches, and be able to restrict the firmware deployment to only fixed version.
This feature also allows us to add glob-aware requirements to other IDs too, for example:
org.kernel -> 6.13.*=6.13.21|6.14.*=6.14.11|6.15.1
> Add support for glob-aware version comparison requirements

- plugins/uefi-capsule/fu-uefi-capsule-plugin.c
- plugins/uefi-dbx/fu-uefi-dbx-device.c
- src/fu-engine.c
This also makes the warning for the dbx correctly show up when using Snap FDE.
Fixes https://github.com/fwupd/fwupd/issues/8963
> Only show the 'Full Disk Encryption Detected' warning when required

- contrib/build-venv.sh
- libfwupd/fwupd-binder-variant-hack.h
- meson.build
`fwupd-binder` shouldn't be built by default -- it breaks the normal build workflow.
Also applied patches from https://github.com/fwupd/fwupd/tree/hughsie/binder-fixes
> Don't build with Android binder by default

- src/fu-util.c
We carefully removed the FWUPD_DEVICE_FLAG_REPORTED flag on the original device list, but then re-requested a new version.
> Fix fwupdmgr report-history --force

- libfwupdplugin/fu-firmware.c
> trivial: Fix a critical warning when using fu_firmware_get_image_by_id()

- src/fu-tool.c
- src/fu-util-common.c
- src/fu-util-common.h
- src/fu-util.c
This worked in fwupdtool as it was using fwupd_device_get_children() -- which is only set up when adding devices to the engine. This meant we were hiding any non-updatable device that had updatable children -- like the KEK devices.
Use the parent like the comment in fwupd_device_add_child() suggests we do. This also allows us to use the same implementation to build the tree for fwupdtool and fwupdmgr.
Fixes https://github.com/fwupd/fwupd/issues/8971
> Show KEK child devices in fwupdmgr

- plugins/mtd/fu-mtd-device.c
Useful for cases where the MTD device driver does not allow erases that are multiples of the `erasesize` and the firmware is not padded or aligned according to the specific `erasesize`.
> Add erase align up flag

- plugins/logitech-tap/fu-logitech-tap-touch-device.c
This is already set in FuHidrawDevice.
> logitech-tap: Only set the physical ID once

- plugins/modem-manager/fu-mm-qcdm-device.c
When using a port that was not previously configured by ModemManager (e.g. ModemManager 'ignored' port), we need to configure the serial ourselves (see [MM serial port config](https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/blob/adb6dc9b44224136ccdd087f29f4796e0bfa54ed/src/mm-port-serial.c#L472)).
> modem-manager: Set QCDM device to raw mode

- docs/env.md
- libfwupd/fwupd-client.c
If a user has a complicated network setup they may be gated behind
GLib checks for network connectivity in order to use fwupd.
Add an escape hatch for glib bugs.
Link: https://gitlab.gnome.org/GNOME/glib/-/issues/3737
Closes: https://github.com/fwupd/fwupd/issues/9061
Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>
> Add support for ignoring network connectivity

- libfwupdplugin/README.md
- libfwupdplugin/fu-bios-settings.c
- libfwupdplugin/fu-common.c
- libfwupdplugin/fu-common.h
- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-oprom-device.c
- libfwupdplugin/fu-path.c
- libfwupdplugin/fu-smbios.c
- libfwupdplugin/fu-udev-device.c
- libfwupdplugin/fu-usb-device.c
- plugins/cros-ec/fu-cros-ec-usb-device.c
- plugins/fpc/fu-fpc-device.c
- plugins/fresco-pd/fu-fresco-pd-device.c
- plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
- plugins/modem-manager/fu-mm-mbim-device.c
- plugins/wacom-usb/fu-wac-module.c
- src/fu-dbus-daemon.c
- src/fu-engine-emulator.c
- src/fu-engine.c
The functionality is the same, so the internal one provides no benefit.
> trivial: Use fwupd_error_convert() in more places

- src/fu-device-list.c
Hello!
I was testing with cros-ec plugin; it usually requires multiple ANOTHER_WRITE_REQUIRED, but I found that it only does one writing round then it stops.
I think it might have stopped working after this PR https://github.com/fwupd/fwupd/pull/8597, so I tried to put that line back and it fixed it, not sure though if that breaks something related with emulations?
> Incorporate ANOTHER_WRITE_REQUIRED flag within fu_device_list_replace()

- contrib/generate-ds20.py
When adding the DS20 descriptor in the firmware I have to specify the length, so it's useful if the tool tells me about it.
Example:
```
> ./contrib/generate-ds20.py fwupd.quirk
DS20 descriptor control transfer data (89 Bytes):
0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x3d, 0x72, 0x70, 0x5f, 0x70, 0x69, 0x63, 0x6f, 0x0a, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x3d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x0a, 0x49, 0x63, 0x6f, 0x6e, 0x3d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2d, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x47, 0x75, 0x69, 0x64, 0x3d, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5c, 0x56, 0x45, 0x4e, 0x5f, 0x32, 0x45, 0x38, 0x41, 0x26, 0x44, 0x45, 0x56, 0x5f, 0x30, 0x30, 0x30, 0x33 …
```
> generate-ds20.py: Print number of bytes

- plugins/modem-manager/fu-mm-backend.c
- plugins/modem-manager/fu-mm-device.c
`mm_modem_get_ports` and `mm_modem_get_ignored_ports` return `FALSE` and set `MMModemPortInfo *` to `NULL` if the number of ports is zero, so we shouldn't treat this as an error directly.
> modem-manager: Do not fail if no ports found

- plugins/nvme/nvme.quirk
Lexar versioning is "unique"; one update is from version `12544` to `SN13767`. Strip the characters so vercomp evaluates this correctly.
> plugins/nvme: Set ensure-semver for Lexar drives

- plugins/modem-manager/fu-mm-mhi-qcdm-device.c
Uses the same expression as in the `qc-firehose` Sahara implementation to get the firmware-loader, which allows using vendor-provided firmware directly also for mhi-qcdm.
```
├── appsboot.mbn
├── ENPRG9x07.mbn
├── partition_complete_p4K_b256K.mbn
├── prog_nand_firehose_9x07.mbn
├── rawprogram_nand_p4K_b256K_update.xml
├── sbl1.mbn
└── tz.mbn
```
> modem-manager: Get Firehose loader using glob

- libfwupdplugin/fu-elf.rs
- libfwupdplugin/fu-ifd.rs
- libfwupdplugin/fu-self-test.c
- libfwupdplugin/fu-self-test.rs
- libfwupdplugin/rustgen.py
- plugins/aver-hid/fu-aver-hid.rs
- plugins/dell-kestrel/fu-dell-kestrel-hid.rs
- plugins/telink-dfu/fu-telink-dfu.rs
For example:
```
struct FuStructFoo {
bar: [u8; 30] == [0xFE; 30],
}
```
instead of having to to 0xFEFEFEFEFEFEFEFE..........
https://doc.rust-lang.org/std/primitive.array.html#examples
> rustgen: Support initializing array with values

- plugins/rts54hub/fu-rts54hub-plugin.c
Fixes #9164
I'm seeing this error:
failed to add device
/sys/devices/pci0000:00/0000:00:08.3/0000:c5:00.0/usb4/4-2: too many GTypes to choose a default, got:
FuRts54HubDevice,FuRts54hubRtd21xxBackground,FuRts54hubRtd21xxForeground
With this change I can see the firmware version:
```
> fwupdtool get-devices --plugins rts54hub
[sudo] password for zoid: 
Loading…                 [************************************** ]
Framework Laptop 16 (AMD Ryzen AI 300 Series)
│
└─4-Port USB 3.0 Hub:
Device ID:          a36485667d707d3146ca8dd945fe82adb031e9b2
Current version:    0.7
Vendor:             Realtek Semiconductor Corp. (USB:0x0BDA)
Update Error:       device does not support authentication
GUIDs:              e08c4b70-8556-5634-9628-e5dd44b9bdae ← USB\VID_0BDA&PID_0432 …
```
> rts54hub: Assign a default gtype

- plugins/modem-manager/fu-mm-mbim-device.c
All MBIM message responses are sent to the main context the device was opened with.
If using a new context for each MBIM action (open/command/close), we are never going to see any response (except for the first time).
-> Use a single context per MBIM device and reuse it for every of its MBIM actions.
Fixes: #9071
> modem-manager: per-device main context

- contrib/setup
Let agents like Copilot and Claude set CI=1 in the environment so that they don't get asked questions they can't figure out how to answer.
> trivial: contrib/setup: Don't prompt questions when CI=1

- libfwupdplugin/fu-device.c
- plugins/modem-manager/tests/lenovo-em061kgl-mbim.json
- plugins/qc-firehose/fu-qc-firehose-impl.c
- plugins/qc-firehose/fu-qc-firehose-usb-device.c
- plugins/qc-firehose/tests/qc-eg25ggc.json
Fix a bug where a vendor-specific firehose `<erase>` attributes were mis-copied which lead to a complete device erasure.
See https://github.com/hughsie/libxmlb/pull/260 for the new libxmlb API needed.
Hopefully fixes https://github.com/fwupd/fwupd/issues/8382
> modem-manager: Erase the RM520N-GL correctly

- plugins/devlink/fu-devlink-device.c
This fixes bug of instance ID creation for component device. VEN and DEV instance strings were not inherited from parent device and therefore never filled. Fix that by incorporating parent keys before component probe.
> devlink: Fix PCI instance ID for component device

- contrib/ci/dependencies.xml
- contrib/ci/fwupd_setup_helpers.py
- contrib/setup
Now we can run `./contrib/setup` like on many linux distros and get the necessary dependencies :)
And also run `build-fwupd`, though compilation still has some errors.
> contribu/setup: Allow bootstrapping on FreeBSD

- meson.build
The usb.ids is normally installed by homebrew. However, homebrew change its default path to /opt/homebrew/. We add the /opt/homebrew to default search path in usb.ids.
> Allow new default path for homebrew

- meson.build
- plugins/elantp/meson.build
- src/meson.build
Enabling I2c devices for android by changing meson.build files
> I2C changes for android

- libfwupdplugin/fu-chunk.c
- libfwupdplugin/fu-self-test.c
To fix #9291 
because `offset + packet_sz` may align to `page_sz` then cause `chunksz` become 0.
> fix fu_chunk_array_new may hand and timeout

- libfwupdplugin/fu-efi-vss-auth-variable.c
This allows us to compare NVRAM using `fwupdtool firmware-export custom_VARS.fd` -- which is so awesome when booting qemu and doing some UEFI updates.
> Parse the FuEfiSignatureList child when parsing FuEfiVssAuthVariable

- libfwupdplugin/fu-firmware.c
- libfwupdplugin/fu-firmware.rs
- libfwupdplugin/fu-self-test.c
- src/fu-tool.c
If the parent image has dedupe-id or dedupe-idx then the order of the children may not be stable.
Sort the output of the 'fwupdtool firmware-export' command so we can compare these kinds of sortable firmware.
> Optionally sort the child images when exporting firmware

- src/fu-engine-helper.c
Having this would have made finding the libjcat memory leak much easier...
> trivial: Allow parsing as a full-fat cabinet file

- plugins/bnr-dp/fu-bnr-dp-device.c
Thankfully, this is functionally not critical in any of the instances where the function is called.
All of the rustgen types are aliases of GByteArray anyway but that also means that type checking doesn't really work, at least not with just the compiler and settings.
> bnr-dp: fix return type annotation

- libfwupdplugin/meson.build
This allows us to do 'ninja libfwupdplugin/fwupdplugin-self-test' from a clean configured checkout.
> trivial: Fix deps when building the fwupdplugin self tests
