plugins/uefi-capsule/fu-uefi-capsule-plugin.c
src/fu-engine.c
src/fu-tool.c

The system is probably broken, but we shouldn't explode.
Fixes https://github.com/fwupd/fwupd/issues/6406

Fix a critical warning when listing the ESP

---

RELEASE
contrib/generate-release.py
contrib/generate-release.xml

trivial: Add a tool to generate the release notes

---

contrib/debian/fwupd.install
contrib/debian/rules
data/org.freedesktop.fwupd.metainfo.xml

Let the package work in both cases to make for easier backports. commit.

trivial: debian: Adjust /usr merge handling

---

plugins/redfish/fu-redfish-plugin.c
plugins/redfish/fu-redfish-request.c

Fixes https://github.com/fwupd/fwupd/issues/6381

redfish: Attempt to replace the fwupd KCS user if required

---

meson.build
plugins/uefi-capsule/fu-uefi-common.c

Add support for loongarch64

---

plugins/pixart-rf/pixart-rf.quirk

Change PID of Twinkies mouse & keyboard to support Twinkies devices.

Change PID of Twinkies mouse & keyboard.

---

meson.build

trivial: Include GPG and PKCS7 in summary

---

contrib/debian/fwupd.postrm
contrib/debian/fwupd.preinst

trivial: debian: add some packaging cleanups for upgrades

---

contrib/qubes/test/fwupd_logs.py
libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
plugins/amd-gpu/fu-amd-gpu-device.c
plugins/amd-pmc/fu-amd-pmc-device.c
plugins/cpu/fu-cpu-device.c
plugins/flashrom/fu-flashrom-device.c
plugins/intel-me/fu-intel-me-amt-device.c
plugins/intel-me/fu-intel-me-mca-device.c
plugins/intel-me/fu-intel-me-mkhi-device.c
plugins/pci-bcr/fu-pci-bcr-plugin.c
plugins/pci-psp/fu-pci-psp-device.c
plugins/tpm/fu-tpm-plugin.c
plugins/uefi-capsule/README.md
plugins/uefi-capsule/fu-uefi-device.c
plugins/uefi-dbx/fu-uefi-dbx-device.c
plugins/vbe/fu-vbe-device.c
src/fu-engine.c
src/tests/host-emulate/thinkpad-p1-iommu.json

Do not use the `main-system-firmware` and `cpu` GUIDs

---

data/pki/meson.build

Alternative proposal to https://github.com/fwupd/fwupd/pull/6433

trivial: Use default_value when getting pkgconfig values

---

src/fu-util.c

trivial: Fix a critical warning when calling 'fwupdmgr get-details'

---

libfwupdplugin/fu-gcab.c
plugins/dfu/fu-dfu-tool.c
plugins/tpm/fu-tpm-eventlog.c
plugins/uefi-capsule/fu-uefi-tool.c
plugins/uefi-dbx/fu-dbxtool.c
src/fu-main.c
src/fu-offline.c
src/fu-tool.c
src/fu-util.c

Make all critical warnings into backtraces for non-release builds

---

libfwupdplugin/fu-dump.c

Found by Linux Verification Center (portal.linuxtesting.ru) with SVACE.
Fixes https://github.com/fwupd/fwupd/issues/6479

trivial: Fix a theoretical division by zero

---

libfwupd/fwupd-device.c
libfwupd/fwupd-device.h
libfwupd/fwupd-enums-private.h
libfwupd/fwupd-request.c
libfwupd/fwupd-request.h
libfwupd/fwupd.map
libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
plugins/analogix/fu-analogix-device.c
plugins/ccgx-dmc/fu-ccgx-dmc-device.c
plugins/ebitdo/fu-ebitdo-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-device.c
plugins/steelseries/fu-steelseries-fizz-hid.c
plugins/steelseries/fu-steelseries-sonic.c
plugins/system76-launch/fu-system76-launch-device.c
plugins/test/fu-test-plugin.c
plugins/usi-dock/fu-usi-dock-mcu-device.c
plugins/vli/fu-vli-usbhub-device.c
plugins/wistron-dock/fu-wistron-dock-device.c
src/fu-engine.c
src/fu-self-test.c
src/fu-util-common.c

This allows us to filter results based on the level of interaction.
Fixes https://github.com/fwupd/fwupd/issues/6467

Let the client know what interaction is expected

---

libfwupdplugin/fu-cab-firmware.c

The fuzzer managed to come up with a binary with 49153 CFFOLDERs which took 26 seconds to parse...
https://oss-fuzz.com/testcase-detail/5737299081822208

trivial: Fix a fuzzing timeout in the cab parser

---

libfwupd/fwupd-security-attr.c

Do not ensure the current value is unknown.

Correctly mark the CPU as supported

---

docs/fwupdplugin.toml.in

trivial: Fix a 404 on https://fwupd.github.io/libfwupdplugin/supermicro-license.html

---

libfwupdplugin/fu-firmware.c
libfwupdplugin/fu-firmware.h
libfwupdplugin/fu-input-stream.c
libfwupdplugin/fu-input-stream.h
libfwupdplugin/fu-partial-input-stream.c
libfwupdplugin/fu-partial-input-stream.h
libfwupdplugin/fu-self-test.c
libfwupdplugin/fwupdplugin.h
libfwupdplugin/meson.build

trivial: Add some GInputStream helpers for future use

---

libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-udev-device.h
plugins/mtd/fu-mtd-device.c

mtd: Only open the device O_RDWR if writable

---

libfwupdplugin/fu-drm-device.c
libfwupdplugin/fu-firmware.c
libfwupdplugin/fu-firmware.h
libfwupdplugin/fu-self-test.c
plugins/mtd/fu-mtd-device.c
plugins/redfish/fu-redfish-plugin.c
plugins/uefi-capsule/fu-uefi-bootmgr.c
plugins/uefi-capsule/fu-uefi-capsule-plugin.c
plugins/uefi-dbx/fu-dbxtool.c
plugins/wacom-usb/fu-self-test.c
src/fu-engine.c
src/fu-tool.c

trivial: Add fu_firmware_parse_stream() to allow loading large files

---

libfwupdplugin/fu-gcab.c

This allows us to use a streaming interface in the future.

trivial: Use fu_firmware_parse_file() in the gcab CLI

---

libfwupdplugin/fu-firmware.c

trivial: Do not overread the stream when converting to bytes

---

libfwupdplugin/fu-composite-input-stream.c
libfwupdplugin/fu-partial-input-stream.c
libfwupdplugin/fu-self-test.c

Match the behaviour of GMemoryInputStream and GFileInputStream.

trivial: Make FuPartialInputStream and FuCompositeInputStream more standard

---

libfwupdplugin/fu-chunk-array.c
libfwupdplugin/fu-chunk-array.h

trivial: Add fu_chunk_array_new_from_stream() for future usage

---

plugins/uefi-capsule/fu-uefi-capsule-plugin.c

Match Lenovo `PQSERVICE` partition to skip ESP selection as well.

---

libfwupdplugin/fu-input-stream.c
libfwupdplugin/fu-input-stream.h
src/fu-engine.c
src/fu-self-test.c
src/fu-unix-seekable-input-stream.c
src/fu-unix-seekable-input-stream.h
src/meson.build

See https://gitlab.gnome.org/GNOME/glib/-/issues/3200 for why this is needed.

Add fu_unix_seekable_input_stream_new() for future use

---

libfwupdplugin/fu-oprom-firmware.c

trivial: Fix parsing IFWI firmware from OptionROM

---

libfwupdplugin/fu-bytes.c
libfwupdplugin/fu-bytes.h
libfwupdplugin/fu-chunk-array.c
libfwupdplugin/fu-firmware.c
libfwupdplugin/fu-firmware.h
libfwupdplugin/fu-input-stream.c
libfwupdplugin/fu-input-stream.h
libfwupdplugin/fu-kernel.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/fu-uswid-firmware.c
plugins/uf2/fu-uf2-device.c
src/fu-engine.c

trivial: Add fu_input_stream_read_uXX helpers

---

plugins/aver-hid/aver-hid.quirk
plugins/aver-hid/fu-aver-hid-device.c
plugins/aver-hid/fu-aver-hid.rs

aver-hid: Add support for AVer VB342 Pro

aver-hid: Add support for AVer VB342 Pro

---

contrib/debian/fwupd.maintscript
contrib/debian/fwupd.postinst
contrib/debian/fwupd.postrm
contrib/debian/fwupd.preinst

debian maintainer script cleanup

---

.github/workflows/pull-request-reviews.yml
src/fu-util-common.c

Actually check the correct thing...

Do not show spurious device request flags

---

libfwupdplugin/fu-device.c

Check the GType was valid from the quirk file

---

plugins/synaptics-mst/fu-synaptics-mst-device.c

synaptics-mst: Allow updating devices for whitebox customers

---

data/bash-completion/fwupdmgr
data/fish-completion/fwupdmgr.fish
src/fu-util.c

Allow exporting 'offline' reports for manual upload

---

src/fu-util.c

This is optional, but allows a flow where reports can pass to multiple users and be verified they haven't been tampered with.

trivial: Add --sign support for exported reports

---

src/fu-util.c

This allows us to upload *one* file to the LVFS when including a signature.

Include the offline report in an archive

---

plugins/amd-gpu/fu-amd-gpu-device.c

libdrm has a table that will show the proper marketing name for GPUs as they get released.  Use this for device name.

amd-gpu: Set the GPU name from libdrm

---

plugins/dell/dell.quirk

Fixes: https://github.com/fwupd/fwupd/issues/6578

bugfix: remove unused device

---

libfwupdplugin/fu-security-attr.c

Link: https://github.com/fwupd/fwupd/issues/6585

Don't offer to change BIOS settings that are already set

---

libfwupdplugin/fu-device.c
src/fu-engine.c

Fixes half of https://github.com/fwupd/fwupd/issues/6589

Assume the legacy LVFS::UpdateRequestId tag is a non-generic ID

---

plugins/bcm57xx/fu-bcm57xx-device.c

bcm57xx: Ask the user to shutdown for 30 seconds to force a reset

---

libfwupdplugin/fu-dpaux-device.c
libfwupdplugin/fu-udev-device.c
plugins/synaptics-mst/fu-synaptics-mst-device.c

Adjust handling for downstream MST devices

---

src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

trivial: show full path for `fwupdtool --help` output

---

plugins/dfu/dfu.quirk

dfu: Update dfu quirk file for new chips of SPIT pccams

---

src/fu-engine.c

trivial: Make an error string more useful

---

libfwupd/fwupd-security-attr.c
plugins/pci-psp/fu-pci-psp-device.c

…upported
Fixes: https://github.com/fwupd/fwupd/issues/6610

Fix supported CPU flipping on AMD systems

---

docs/building.md
docs/index.html

A few changes after playing with the live version to improve discoverability.

Minor documentation changes

---

meson.build

Instead of one line for each plugin make it one line for enabled and one for disabled.

trivial: make the plugin summary more readable

---

contrib/setup
contrib/vscode/tasks.json

This will be used when pressing ctrl-shift-b or
"Terminal->Run Build task"

trivial: contrib: add default build task for vscode

---

generate-build/generate-man.py

These aren't needed and look off.

trivial: man: strip `##` from man page sections

---

generate-build/generate-man.py

This fixes the section headings to show up in bold.

trivial: man: strip leading whitespace too

---

contrib/snap/snapcraft.yaml

trivial: snap: add license field to snap

---

data/org.freedesktop.fwupd.metainfo.xml

- Add vcs-browser URL
- Update content_raiting version

appdata: Update appdata

---

README.md

Let's just keep the list of other clients in one place for a better chance at keeping it up to date.

trivial: drop GUI list in top level `README.md`

---

libfwupdplugin/fu-path.c
libfwupdplugin/fu-path.h
plugins/cpu/fu-cpu-device.c

The CET helper location needs to be launched from the right place.

Fix CET detection in the snap

---

plugins/aver-hid/aver-hid.quirk
plugins/aver-hid/fu-aver-hid-device.c
plugins/aver-hid/fu-aver-hid-plugin.c
plugins/aver-hid/fu-aver-hid.rs
plugins/aver-hid/fu-aver-safeisp-device.c
plugins/aver-hid/fu-aver-safeisp-device.h
plugins/aver-hid/meson.build

aver-hid: Add support for AVer CAM340plus

aver-hid: Add support for AVer CAM340plus

---

contrib/ci/dependencies.xml
contrib/launch-venv.sh

Make venv work better in arch

---

contrib/dump-mtd-ifd.py

trivial: Call mtdinfo when dumping IFD firmware

---

docs/fwupd.conf.md
src/fu-engine-config.c

trivial: Include the fwupd.conf IdleTimeout default in the man page

---

.github/workflows/snap.yml
contrib/firmware_packager/README.md
contrib/firmware_packager/firmware_packager.py
contrib/fwupd.spec.in
contrib/qubes/README.md
contrib/qubes/test/test_qubes_fwupdmgr.py
docs/only-trusted.md
plugins/uefi-capsule/tests/example/build.sh
plugins/vbe/README.md
plugins/vbe/example/build.sh
src/fu-tool.c

Use the *Integrated Webcam* test device to check that the snap can update devices using the local vendor directory.

trivial: ci: add a test that the snap works

---

.github/workflows/snap.yml
contrib/ci/fedora.sh
contrib/debian/fwupd-tests.postinst
contrib/debian/fwupd-tests.postrm
contrib/debian/tests/ci
contrib/launch-venv.sh
data/bash-completion/fwupdtool
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

This is smaller chunk split off from #6712.
 Type of pull request:

Add and use fwupdtool modify-config

---

libfwupdplugin/fu-config.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/tests/fwupd/fwupd.conf

Fixes https://github.com/fwupd/fwupd/issues/6707

Only write fwupd.conf contents with the current values

---

libfwupdplugin/fu-config.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/tests/fwupd/fwupd.conf

Fix immutable test more properly

---

.github/workflows/matrix.yml
.github/workflows/snap.yml
contrib/ci/dependencies.xml
contrib/ci/fedora.sh
contrib/ci/ubuntu.sh
contrib/fwupd.spec.in

More CI testing changes

---

src/fu-engine.c

trivial: Improve profiling results when starting plugins

---

plugins/uefi-capsule/fu-uefi-capsule-plugin.c

Do not warn the user about ESP when using MBR

---

libfwupdplugin/fu-config.c

Leave /etc to whatever the distro decides.

Only save config values to the mutable config file

---

src/fu-client-list.c
src/fu-client-list.h
src/fu-client.c
src/fu-client.h
src/fu-daemon.c
src/fu-engine.c
src/fu-engine.h
src/fu-engine.rs
src/fu-self-test.c
src/meson.build

This means we have to keep track of DBus clients using the D-Bus interface.

Do not idle-quit the daemon if there is a connected D-Bus client

---

contrib/ci/debian.sh
data/installed-tests/fwupdtool.sh
libfwupdplugin/fu-self-test.c

Split out some fixes from coveralls CI

---

meson.build
subprojects/libjcat.wrap

These should have been bumped as part of 62f6f19d269212871493ba8343bf0d53204c7fb7

trivial: bump libjcat and passim deps

---

.github/workflows/matrix.yml
README.md
contrib/ci/arch-test.sh
contrib/ci/debian-x86_64-test.sh
contrib/ci/debian.sh
contrib/ci/dependencies.xml
contrib/ci/fedora-test.sh
contrib/debian/rules

Create and upload a test coverage report to coveralls

---

data/installed-tests/fwupdtool.sh

trivial: ci: Add a test flow for verify update

---

plugins/dfu/dfu.quirk

Specify the Flags in dfu.qurik for Poly Studio V52 usb device.

dfu: Add support for Poly Studio V52 usb device

---

README.md

fix privacy link

---

libfwupdplugin/fu-device-private.h
libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
libfwupdplugin/fu-self-test.c
plugins/uefi-capsule/fu-uefi-capsule-plugin.c
src/fu-engine.c

Remove fu_device_set_alternate() as it is unused

---

SECURITY.md

trivial: Estimate some EOL dates into the future

---

meson.build

Link: https://github.com/fwupd/fwupd-efi/commit/1a794fc7ce481176926687f4e88e6e0c8d5e9699

uefi-capsule: add riscv EFI_MACHINE_TYPE

---

plugins/uefi-capsule/fu-uefi-common.c

uefi-capsule: RISC-V and ARM32 efi binary search fix

---

libfwupdplugin/fu-volume.c

trivial: Do not use magic GUIDs when converting from MBR types

---

src/fu-daemon.c
src/fu-daemon.h
src/fu-daemon.rs
src/meson.build

trivial: Use rustgen in FuDaemon

---

libfwupd/fwupd-device.c
libfwupd/fwupd-device.h
libfwupd/fwupd.map
plugins/redfish/fu-redfish-device.c
src/fu-engine.c
src/fu-release.h
src/fu-util-common.c

Remove the almost unused fwupd_device_get_description()

---

plugins/aver-hid/fu-aver-hid-device.c

aver-hid: a polling function is unnecessary

---

libfwupdplugin/fu-device.c

trivial: Print the specialized GType in FuDevice->to_string

---

docs/fwupd.conf.md
libfwupd/fwupd-report.c
libfwupd/fwupd-report.h
src/fu-engine-config.c
src/fu-engine.c
src/fu-release.c
src/fu-self-test.c
src/tests/fwupd.conf
src/tests/metadata-report4.xml

Allow the trusted report policy to require version upgrade

---

contrib/firmware_packager/install_dell_bios_exe.py
contrib/firmware_packager/simple_client.py
data/bash-completion/fwupdmgr
data/bash-completion/fwupdtool
libfwupd/README.md
libfwupd/fwupd-client-sync.c
libfwupd/fwupd-client-sync.h
libfwupd/fwupd-client.c
libfwupd/fwupd-client.h
libfwupd/fwupd.map
libfwupdplugin/fu-plugin-private.h
libfwupdplugin/fu-plugin.c
libfwupdplugin/fu-plugin.h
libfwupdplugin/fu-self-test.c
plugins/msr/fu-msr-plugin.c
plugins/redfish/fu-redfish-plugin.c
plugins/test/fu-test-plugin.c
plugins/thunderbolt/fu-thunderbolt-plugin.c
plugins/uefi-capsule/fu-uefi-capsule-plugin.c
src/fu-daemon.c
src/fu-engine.c
src/fu-engine.h
src/fu-tool.c
src/fu-util.c
src/org.freedesktop.fwupd.xml

This means we do not have to encode it into the key name.
Breaks API, so unsuitable for backporting.

Add a 'section' parameter to ModifyConfig

---

plugins/vli/fu-vli-pd-firmware.c
plugins/vli/vli-goodway.quirk

Add PID & quirk file to support Goodway's Asus DC201 dongle.

vli:dc201_add

---

docs/ds20.md

trivial: Update the DS-20 version requirement to reality

---

plugins/logind/fu-logind-plugin.c

Whilst it *should* work out okay, it's probably not a good idea.

logind: Do not allow suspend in the middle of a composite update

---

src/fwupd_test.py

trivial: umockdev: drop some boilerplate unnecssary with dbusmock

---

contrib/ci/dependencies.xml
contrib/fwupd.spec.in
data/fwupd.service.in
data/meson.build
meson.build

Bump systemd requirement to 249

---

plugins/wacom-raw/README.md
plugins/wacom-raw/fu-wacom-aes-device.c
plugins/wacom-raw/fu-wacom-device.c
plugins/wacom-raw/fu-wacom-device.h
plugins/wacom-raw/fu-wacom-emr-device.c
plugins/wacom-raw/wacom-raw.quirk

wacom-raw: Wait for device replug for some future devices

---

data/tests/fwupd.sh

Quit the daemon after running the emulation self tests in CI

---

plugins/redfish/fu-redfish-device.c

This matches the behaviour of fu_device_retry() and also means we get an accurate status for the task.
Fixes https://github.com/fwupd/fwupd/issues/6879

Keep polling in fu_redfish_device_poll_task() even for task errors

---

libfwupd/fwupd-common.c
src/fu-engine.c
src/fu-history.c

This will let us find out if the plugin predicted values are correct.
Fixes https://github.com/fwupd/fwupd/issues/6896

Store the install duration in the history database

---

contrib/fwupd.spec.in

trivial: Sync example spec with downstream

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fu-device-locker.c
libfwupdplugin/fu-hid-device.c
libfwupdplugin/fu-usb-device.c
plugins/aver-hid/fu-aver-hid-device.c
plugins/cros-ec/fu-cros-ec-usb-device.c
plugins/fresco-pd/fu-fresco-pd-device.c
plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c
plugins/steelseries/fu-steelseries-device.c
plugins/steelseries/fu-steelseries-fizz-tunnel.c
plugins/synaptics-cape/fu-synaptics-cape-device.c
plugins/synaptics-cxaudio/fu-synaptics-cxaudio-device.c
plugins/thunderbolt/fu-thunderbolt-device.c
plugins/ti-tps6598x/fu-ti-tps6598x-device.c
plugins/wacom-usb/fu-wac-module.c
src/fu-daemon.c

See https://github.com/fwupd/fwupd/discussions/6907

Convert GUsbError to FwupdError domains

---

plugins/flashrom/flashrom.quirk

Tidy quirk entries

---

plugins/test/fu-test-plugin.c
src/fu-self-test.c
src/tests/fakedevice123.bin

Small test fixes

---

data/fwupd.service.in
data/meson.build
meson.build
plugins/flashrom/meson.build

Dynamic implementation of https://github.com/fwupd/fwupd/pull/6927

Only allow raw-io when flashrom plugin is enabled

---

plugins/fpc/fpc.quirk

Add fpc moc lenfy pid

---

libfwupd/fwupd-remote.c

trivial: Fix a tint memory leak when modifying remotes

---

contrib/ci/void.sh
contrib/freebsd/Makefile
contrib/fwupd.spec.in
data/bash-completion/fwupdmgr
data/bash-completion/meson.build
data/fish-completion/fwupdmgr.fish
data/meson.build
meson.build
meson_options.txt
plugins/genesys/fu-genesys-usbhub-device.c
src/fu-daemon.c
src/fu-engine.c
src/fu-self-test.c
src/fu-util.c
src/fwupdmgr.md
src/meson.build

Disable offline mode by default

---

plugins/uefi-capsule/meson.build
po/test-deps

Rather than saying it fails, show the message that po/test-deps emitted.
Fixes: #6913

trivial: show po/test-deps messages

---

contrib/reformat-code.py
libfwupd/fwupd-client-sync.h
plugins/flashrom/fu-flashrom-plugin.c
plugins/uefi-capsule/fu-uefi-capsule-plugin.c
plugins/uefi-capsule/fu-uefi-common.c
plugins/uefi-capsule/fu-uefi-common.h
plugins/uefi-capsule/meson.build
po/test-deps

More 1_9_X backports

---

contrib/ci/check-unused.py
contrib/ci/ubuntu.sh

Restore check-unused.py in CI

---

plugins/vli/fu-vli-common.c
plugins/vli/fu-vli-device.c
plugins/vli/fu-vli-usbhub-device.c
plugins/vli/fu-vli-usbhub-firmware.c
plugins/vli/fu-vli.rs

Add new hub of VL822 C0 into device kind.

vli:Add support VL822 C0

---

plugins/intel-spi/fu-intel-spi-common.c
plugins/intel-spi/fu-intel-spi-device.c

For some reason this was missed on review.

intel-spi: Relicense all plugin files to LGPL-2.1+

---

plugins/cpu/fu-cpu-device.c

For some reason this was missed on review.

cpu: Relicense all plugin files to LGPL-2.1+

---

plugins/emmc/fu-emmc-device.c

For some reason this was missed on review.

emmc: Relicense all plugin files to LGPL-2.1+

---

data/cfi.quirk

Add support for several Puya SPI chips

---

plugins/bcm57xx/fu-bcm57xx-common.c
plugins/bcm57xx/fu-bcm57xx-device.c
plugins/bcm57xx/fu-bcm57xx-recovery-device.c

For some reason this was missed on review.

bcm57xx: Relicense all plugin files to LGPL-2.1+

---

plugins/rts54hub/rts54hub.quirk

Changed Goodway VID to Acer VID

Update rts54hub.quirk changed to Acer VID

---

data/remotes.d/meson.build
meson.build
src/fu-engine.c
src/fu-remote-list.c
src/fu-remote-list.h
src/fu-self-test.c
src/tests/remotes.d/legacy-lvfs-xz.conf

It turns out xz is an undesirable dep...

Prefer zstd for metadata

---

.github/workflows/scorecard.yml
README.md

Create OSSF scorecard

---

SECURITY.md

trivial: Fix SECURITY.md

---

libfwupdplugin/fu-linear-firmware.c

trivial: Do not use FuLinearFirmware for 'auto' matches

---

plugins/synaptics-mst/fu-synaptics-mst-firmware.c
plugins/synaptics-mst/tests/synaptics-mst.builder.xml

synaptics-mst: Allow setting the family when building the firmware

---

plugins/genesys/fu-genesys-usbhub-firmware.c

genesys: Write the file version before writing the checksum

---

contrib/ci/dependencies.xml

trivial: Fix ./contrib/setup on aarch64 Ubuntu

---

meson.build
src/fu-remote-list.c
src/fu-self-test.c

Use zst as the file extension for zstd

---

data/meson.build

This PR aims to drop the below system calls from fwupd:
- @reboot
- @resources
- @swap
The contents of each group of system calls will be detailed in the comments.

Drop @reboot/@resources/@swap system calls

---

src/fu-engine.c

Finding the component with a specific container or artifact checksum throws away a crucial bit of information -- *which* specific release it matched. This worked before as the latest release was typically what the user upgraded to, and fu_release_load() happened to load the first [default] release.
To make this work correctly for downgrades, return the *release* node not the *component* when returning results, and fix up the various users to look two levels deeper when needing the shared component data.
Fixes https://github.com/fwupd/fwupd/issues/6977

Use the specific release when fixing up device history

---

src/fu-util.c

Fixes https://github.com/fwupd/fwupd/issues/7009

Warn users needing to fwupdmgr activate before uploading signed reports

---

README.md

trivial: Add badge for OpenSFF best practices

---

src/fu-engine.c

This matches the negative which is currently not tainted.

trivial: correct tainted plugin from Disabled to Tainted

---

libfwupdplugin/fu-volume.c
libfwupdplugin/fu-volume.h

If a given block device doesn't advertise it, then don't check for it!.

trivial: make udisks partition proxy optional

---

plugins/audio-s5gen2/README.md

Rephrase update behavior description for commit command.
- [ x] Documentation

trivial: rephrase behavior description for audio-s5gen2

---

contrib/ci/oss-fuzz.py
libfwupdplugin/fu-coswid-firmware.c
meson.build

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67951

Limit the size of the allocations in libcbor

---

libfwupdplugin/fu-coswid-firmware.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67957

trivial: Fix a several possible memory leaks for an invalid coswid file

---

contrib/ci/debian-x86_64-test.sh

Be explicit what to include when calculating coverage stats

---

plugins/optionrom/fu-optionrom-plugin.c
plugins/optionrom/meson.build
plugins/optionrom/optionrom.quirk

Fixes https://github.com/fwupd/fwupd/issues/7050

optionrom: Do not read OptionROM on Apple hardware

---

libfwupdplugin/fu-coswid-common.c
libfwupdplugin/fu-coswid-common.h
libfwupdplugin/fu-coswid-firmware.c
libfwupdplugin/meson.build

Use more paranoid helpers when parsing using libcbor

---

.github/workflows/codeql-analysis.yml
contrib/ci/ubuntu.sh
plugins/uefi-capsule/meson.build
subprojects/fwupd-efi.wrap

Bump fwupd-efi requirement to 1.6

---

libfwupdplugin/fu-crc.c
libfwupdplugin/fu-crc.h
libfwupdplugin/fu-self-test.c

Based on a patch by Randy Lai <randy.lai@weidahitech.com>, many thanks.

Add fu_misr16() for future use

---

data/meson.build

trivial: Do not rely on @memlock not being part of @system-service

---

src/fu-util-common.c

Properly show SPDX project licenses with AND as a delimiter

---

libfwupdplugin/fu-crc.c
libfwupdplugin/fu-self-test.c

This fixes the aarch64 self test failures.

trivial: Fix the MISR calculation

---

contrib/fwupd.spec.in
libfwupd/fwupd-client.h
libfwupdplugin/fu-byte-array.c
libfwupdplugin/fu-byte-array.h
libfwupdplugin/fu-crc.c
libfwupdplugin/fu-self-test.c
plugins/superio/fu-superio-it85-device.c
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

Run the Fedora CI build with -Db_sanitize=address,undefined

---

contrib/ci/Dockerfile-fedora.in

trivial: Move the CI to Fedora 40

---

.github/workflows/codeql-analysis.yml
.github/workflows/matrix.yml

trivial: Workaround apt issues in the GitHub runners

---

libfwupd/fwupd-common.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68255

Fix a logic thinko when parsing GUID strings

---

plugins/pci-mei/fu-pci-mei-plugin.c

We can put a limit on this if Intel comes up with a new marketing name.
Fixes https://github.com/fwupd/fwupd/issues/7159

pci-mei: Assume new ME versions are called CSME

---

plugins/pixart-rf/pixart-rf.quirk

Add new PID/VID devices for pixart plugin.

---

data/bash-completion/fwupdmgr
data/tests/fwupd.sh
data/tests/fwupdmgr.sh
libfwupd/fwupd-client.c
libfwupd/fwupd-client.h
libfwupd/fwupd.map
src/fu-util.c

Retry downloads to workaround flaky network in CI

---

libfwupdplugin/fu-common.rs
libfwupdplugin/fu-coswid-firmware.c
libfwupdplugin/fu-coswid.rs
libfwupdplugin/fu-intel-thunderbolt.rs
libfwupdplugin/fu-rustgen-enum.h.in
libfwupdplugin/rustgen.py
plugins/ccgx-dmc/fu-ccgx-dmc.rs
plugins/ccgx/fu-ccgx.rs
plugins/uefi-capsule/fu-uefi.rs
src/fu-engine.rs

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68315

Fix a buffer-overread when parsing invalid CoSWID entity data

---

.circleci/config.yml
contrib/ci/build_windows.sh
contrib/ci/dependencies.xml
contrib/fwupd.wxs.in
libfwupd/fwupd-client.c
libfwupdplugin/fu-usb-device.c

trivial: Move the CI Win32 build to Fedora 40

---

.github/workflows/matrix.yml
plugins/tpm/lsan-suppressions.txt
plugins/tpm/meson.build

trivial: Ignore a memory leak in Esys_Initialize only seen in CI

---

plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c

This didn't actually serve a purpose, and probably makes the device use more power than it has to.
Fixes half of https://github.com/fwupd/fwupd/issues/7011

logitech-hidpp: Remove the device polling for Unifying receivers

---

plugins/algoltek-usb/fu-algoltek-usb-device.c

algoltek-usb: Fix a buffer overread when reading the version number

---

libfwupd/fwupd-client.c

This allows us to filter requests in the LVFS.

Add if running in CI to the useragent

---

data/device-tests/algoltek-ag9421.json

Fixes https://github.com/fwupd/fwupd/issues/7084

Add a device test for Algoltek AG9421

---

plugins/cpu/meson.build

trivial: only build cet helper on x86-64

---

plugins/synaptics-prometheus/fu-synaprom-config.c
plugins/synaptics-prometheus/fu-synaprom-device.c

synaptics-prometheus: Use an icon that exists for the device

---

src/fu-util.c

trivial: Actually include HSI events in the uploaded report

---

contrib/fwupd.spec.in

See https://bugzilla.redhat.com/show_bug.cgi?id=2280157

trivial: Fix example Fedora spec file to include directories

---

contrib/create-plugin.py
plugins/vendor-example/README.md.in
plugins/vendor-example/fu-vendor-example-common.c.in
plugins/vendor-example/fu-vendor-example-common.h.in
plugins/vendor-example/fu-vendor-example-device.c.in
plugins/vendor-example/fu-vendor-example-device.h.in
plugins/vendor-example/fu-vendor-example-firmware.c.in
plugins/vendor-example/fu-vendor-example-firmware.h.in
plugins/vendor-example/fu-vendor-example-plugin.c.in
plugins/vendor-example/fu-vendor-example-plugin.h.in
plugins/vendor-example/fu-vendor-example.rs
plugins/vendor-example/meson.build.in
plugins/vendor-example/vendor-example.quirk.in

Allow using create-plugin with more complicated example names

---

README.md

Add a section about Passim in the top-level README file

---

plugins/fpc/fu-fpc-device.c
plugins/fpc/fu-fpc-ff2-firmware.c
plugins/fpc/fu-fpc-ff2-firmware.h
plugins/fpc/fu-fpc-plugin.c
plugins/fpc/fu-fpc.rs
plugins/fpc/meson.build

Update to support new firmware format for latest devices.

FPC: Update to support FPC firmware format version 2

---

plugins/fpc/fu-fpc-device.c
plugins/fpc/fu-fpc-ff2-firmware.c
plugins/fpc/fu-fpc-ff2-firmware.h
plugins/fpc/fu-fpc-plugin.c
plugins/fpc/fu-fpc.rs
plugins/fpc/meson.build

(cherry picked from commit 0299fd95770a48ad35bfa3ef1390a7237d2f6f93)

fpc: Add support for devices that use FPC FF2

---

libfwupdplugin/fu-bluez-device.c

trivial: Fix a recently added Bluez potential buffer-overread

---

data/tests/fwupd.sh
plugins/uefi-dbx/uefi-dbx.quirk
src/fu-debug.c
src/fu-engine-config.c
src/fu-util.c

Fixes https://github.com/fwupd/firmware-lenovo/issues/437

uefi-dbx: Do not offer the UEFI DBX update on Lenovo ideacentre 300-20ISH

---

data/device-tests/synaptics-vmm9430evb.json
plugins/meson.build
plugins/synaptics-vmm9/README.md
plugins/synaptics-vmm9/fu-synaptics-vmm9-device.c
plugins/synaptics-vmm9/fu-synaptics-vmm9-device.h
plugins/synaptics-vmm9/fu-synaptics-vmm9-firmware.c
plugins/synaptics-vmm9/fu-synaptics-vmm9-firmware.h
plugins/synaptics-vmm9/fu-synaptics-vmm9-plugin.c
plugins/synaptics-vmm9/fu-synaptics-vmm9-plugin.h
plugins/synaptics-vmm9/fu-synaptics-vmm9.rs
plugins/synaptics-vmm9/meson.build
plugins/synaptics-vmm9/parse-pcap.py
plugins/synaptics-vmm9/synaptics-vmm9.quirk

synaptics-mst: Add support for VMM9xxx 'Carrera' devices

---

src/fu-util-common.c

Fixes https://github.com/fwupd/fwupd/issues/7284

trivial: Fix the wording for the problem when the lid is closed

---

plugins/steelseries/steelseries.quirk

Fixes https://github.com/fwupd/fwupd/issues/6689

steelseries: Fix again the CounterpartGuid for the Aerox 3 Wireless Mouse

---

src/fu-engine.c

Check for needs-shutdown like we do needs-reboot

---

src/fu-engine.c

Allow using IgnoreRequirements=true when getting releases

---

contrib/ci/dependencies.xml

Add a missing dependency for fedora on aarch64

---

contrib/reformat-code.py
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

Fixes for `fwupdmgr get-plugins`

---

plugins/synaptics-mst/fu-synaptics-mst-common.c
plugins/synaptics-mst/fu-synaptics-mst-device.c
plugins/synaptics-mst/fu-synaptics-mst-firmware.c
plugins/synaptics-mst/fu-synaptics-mst.rs
plugins/synaptics-mst/synaptics-mst-evb.quirk

synaptics-mst: Add support VMM9 series (code name Carrera)

---

src/fu-engine.c

This saves about 900Kb of runtime RSS on my Lenovo P1 gen 3.

Remove useless devices from the FuBackend cache

---

libfwupdplugin/fu-device.c

Reduce runtime RSS by ~90Kb by delaying-init of more FuDevice structures

---

data/remotes.d/lvfs-testing.conf
data/remotes.d/lvfs.conf
libfwupd/fwupd-remote-private.h
libfwupd/fwupd-remote.c
libfwupd/fwupd-remote.h
libfwupd/fwupd.map
src/fu-remote.c

Set the privacy policy URL in the remote config

---

data/device-tests/meson.build
data/device-tests/pixart-rf-GCBBTM25.json

Support GCBBTM25 BT mouse.
- [*] Code fix

Add 'pixart-rf-GCBBTM25.json' for device tests.

---

libfwupd/fwupd-bios-setting.h
libfwupd/fwupd-client.h
libfwupd/fwupd-codec.h
libfwupd/fwupd-common.h
libfwupd/fwupd-error.h
libfwupd/fwupd-remote.h
libfwupd/fwupd-request.h
libfwupd/fwupd-security-attr.h

trivial: Convert more enum fields into gtk-doc format

---

libfwupdplugin/fu-elf-firmware.c

trivial: Do not return with unset GError when parsing ELF files

---

docs/building.md

trivial: docs: Fixed typo

---

libfwupdplugin/fu-device.c

In the case where you have `FuAaa->FuBbb->FuCcc` and `FuAaa->FuBbb->FuXXX` you want to incorporate `FuAaa` and `FuBbb` only.

trivial: Incorporate correctly in more situations

---

contrib/ci/check-source.py
libfwupdplugin/fu-usb-device.c

trivial: Add checks for direct GUsb calls

---

libfwupdplugin/fu-udev-device.c

It doesn't seem to be used by anything...

Remove the MODALIAS quirk-only GUID

---

plugins/ata/ata.quirk
plugins/ata/fu-ata-device.c

ata: Use a more standard OUI vendor name match

---

contrib/ci/oss-fuzz.py
libfwupdplugin/fu-elf-firmware.c
libfwupdplugin/fu-elf.rs
libfwupdplugin/fu-self-test.c
libfwupdplugin/tests/elf.builder.xml
libfwupdplugin/tests/meson.build

With much help from Aidan S <548786@chrome.escg.ac.uk>

elf: Add support for writing an ELF binary to enable fuzzing

---

libfwupdplugin/fu-elf-firmware.c

trivial: Do not crash when constructing an invalid ELF file

---

libfwupdplugin/fu-device.c

trivial: Use the device proxy when looking for emulated events

---

libfwupdplugin/fu-drm-device.c
libfwupdplugin/fu-mei-device.c
libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-udev-device.h
plugins/elantp/fu-elantp-i2c-device.c
plugins/intel-gsc/fu-igsc-device.c
plugins/mediatek-scaler/fu-mediatek-scaler-device.c
plugins/pixart-rf/fu-pxi-receiver-device.c
plugins/scsi/fu-scsi-device.c
plugins/thunderbolt/fu-thunderbolt-controller.c
plugins/thunderbolt/fu-thunderbolt-device.c

Add fu_udev_device_get_parent_with_subsystem_devtype() for future use

---

plugins/rts54hub/fu-rts54hub-rtd21xx-background.c

At the moment there is no delay defined, and so we retry as quick as possible -- which may have different results on different machines.

rts54hub: Be explicit with the detach retry delay

---

libfwupdplugin/README.md
libfwupdplugin/fu-usb-device.c
libfwupdplugin/fu-usb-device.h
plugins/modem-manager/fu-sahara-loader.c

trivial: Remove the largly pointless fu_usb_device_is_open()

---

libfwupdplugin/fu-intel-thunderbolt-nvm.c
plugins/thunderbolt/fu-self-test.c
plugins/thunderbolt/fu-thunderbolt-device.c

Intel thunderbolt firmware versioning convention updated

---

libfwupdplugin/fu-device.c

Some quirk matches are addative, e.g. 'Children' and running the query multiple times isn't just wasteful, it means we're showing too many child devices -- each of which that might need hardware access.

Do not run the quirk query multiple times on the same device

---

libfwupdplugin/fu-device.c

trivial: Disconnect from the old proxy notify::flags if replaced

---

libfwupdplugin/README.md
libfwupdplugin/fu-bios-setting.c
libfwupdplugin/fu-io-channel.c
libfwupdplugin/fu-io-channel.h
plugins/amd-gpu/fu-amd-gpu-device.c
plugins/elantp/fu-elantp-i2c-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
plugins/modem-manager/fu-firehose-updater.c
plugins/modem-manager/fu-mm-device.c
plugins/synaptics-rmi/fu-synaptics-rmi-common.c
plugins/thelio-io/fu-thelio-io-device.c

We want to avoid using open() as much as possible.

trivial: Add FuIOChannelOpenFlags to fu_io_channel_new_file()

---

contrib/ci/dependencies.xml
libfwupdplugin/fu-device.c
plugins/mtd/meson.build
plugins/mtd/mtd.quirk
src/fu-tool.c
src/fu-util.c

Minor random fixes found on aarch64

---

libfwupdplugin/fu-self-test.c
libfwupdplugin/fu-test-device.c
libfwupdplugin/fu-test-device.h
libfwupdplugin/meson.build

trivial: Do not use FuUsbDevice in self tests

---

plugins/ep963x/meson.build
plugins/nitrokey/meson.build
plugins/thelio-io/meson.build

Disable some plugins that need usb support if usb not found

---

libfwupdplugin/README.md
libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-udev-device.h
plugins/intel-gsc/fu-igsc-device.c
plugins/synaptics-rmi/fu-synaptics-rmi-ps2-device.c
plugins/thunderbolt/fu-thunderbolt-common.c
plugins/thunderbolt/fu-thunderbolt-common.h
plugins/thunderbolt/fu-thunderbolt-device.c

trivial: Add a IO timeout to fu_udev_device_write_sysfs()

---

libfwupdplugin/fu-plugin.c
plugins/dfu/fu-dfu-device.c
src/fu-device-list.c
src/fu-engine.c
src/fu-plugin-list.c
src/fu-self-test.c

Maybe fixes https://github.com/fwupd/fwupd/issues/7451

Use GObjectClass->dispose() to break FuDevice refcount loops

---

libfwupdplugin/fu-hwids-fdt.c

This regressed in 2b0f925.
Fixes https://github.com/fwupd/fwupd/issues/7437

Set the Blackbird and Talos II baseboard details again

---

libfwupdplugin/fu-context.c

ESP detection improvements

---

src/fu-usb-backend.c

trivial: Do not show USB messages when non-verbose

---

contrib/snap/snapcraft.yaml

snap: Refresh metadata on timer

---

libfwupdplugin/fu-udev-device.c

trivial: Add the device number to the FuUdevDevice debugging

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-device.c
libfwupdplugin/fu-string.c
libfwupdplugin/fu-volume.c
plugins/genesys-gl32xx/fu-genesys-gl32xx-device.c
plugins/intel-gsc/fu-igsc-device.c
plugins/wacom-usb/fu-wac-module-sub-cpu.c

trivial: clang-format fixes

---

plugins/nvme/fu-nvme-device.c

nvme: Use fu_udev_device_get_parent_with_subsystem()

---

plugins/synaptics-rmi/fu-synaptics-rmi-hid-device.c

synaptics-rmi: Do not use GUdevDevice directly

---

contrib/ci/build_windows.sh

This is probably a wine regression, and will be debugged later.

trivial: Disable the Win32 tests

---

libfwupdplugin/fu-udev-device.c

trivial: Do not use GUdevDevice in fu_udev_device_find_usb_device()

---

libfwupdplugin/fu-udev-device.c

trivial: Use the new setters from fu_udev_device_incorporate()

---

plugins/thunderbolt/fu-thunderbolt-controller.c
plugins/thunderbolt/fu-thunderbolt-retimer.c

thunderbolt: Do not use GUdevDevice directly

---

libfwupdplugin/fu-path.c
libfwupdplugin/fu-path.h

trivial: Add FU_PATH_KIND_SYSFSDIR

---

plugins/scsi/fu-scsi-device.c

This allows us to emulate the device, and also means we can work without udev.

scsi: Do SG_IO INQUIRY_CMD rather than relying on the udev prober

---

libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-udev-device.h
plugins/amd-kria/fu-amd-kria-device.c
plugins/android-boot/fu-android-boot-device.c
plugins/ata/fu-ata-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
plugins/logitech-scribe/fu-logitech-scribe-device.c
plugins/logitech-tap/fu-logitech-tap-hdmi-device.c
plugins/scsi/fu-scsi-device.c
plugins/thunderbolt/fu-thunderbolt-controller.c
plugins/uf2/fu-uf2-device.c

Add fu_udev_device_read_property() to allow emulation of UDev devices

---

libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-udev-device.h

trivial: Export fu_udev_device_set_vendor() for future use

---

libfwupdplugin/fu-usb-device.c

trivial: Use the EMULATE flag to detect emulated devices

---

plugins/usi-dock/fu-usi-dock-dmc-device.c

usi-dock: adjust the serial number judgment logic

---

contrib/ci/dependencies.xml

trivial: ci: arch: install gsettings-desktop-schemas

---

contrib/build-openbmc.sh
contrib/build-venv.sh
contrib/debian/rules
contrib/fwupd.spec.in
contrib/snap/snapcraft.yaml
data/90-fwupd-devices.rules
data/meson.build
meson.build
meson_options.txt

With the switch to reading pci.ids we don't need this at all.

Remove the fwupd rules file

---

meson.build

Only require udevdir when gudev support is enabled

---

plugins/algoltek-usb/fu-algoltek-usb-device.c

This regressed in bf223e2ddea4c598ed24ca6c6b864480751c0280.

algoltek-usb: Fix untrusted value as argument, harder

---

contrib/PKGBUILD
contrib/ci/arch-test.sh
contrib/ci/arch.sh
contrib/ci/dependencies.xml
libfwupd/fwupd-self-test.c
libfwupdplugin/fu-bluez-device.c
libfwupdplugin/fu-quirks.c
libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-usb-device.c
src/fu-engine.c
src/fu-polkit-authority.c
src/fu-udev-backend.c

trivial: Ensure polkit is installed in Arch CI

---

plugins/dell-dock/fu-dell-dock-hub.c
plugins/dell-dock/fu-dell-dock-i2c-ec.c
plugins/dell-dock/fu-dell-dock-plugin.c

dell-dock: setup hub version until dock type is known supported

---

libfwupdplugin/fu-intel-thunderbolt-nvm.c

thunderbolt: BR uses the same offset for versioning

---

src/fu-device-list.c

trivial: copy child devices to new returned parent

---

data/fwupd.service.in

Fixes: https://github.com/fwupd/fwupd/pull/7554#issuecomment-2257679517

Add aux devices to DeviceAllow

---

plugins/mediatek-scaler/mediatek-scaler.quirk

mediatek_scalar: add new hardware systems

---

docs/hsi-tests.d/org.fwupd.hsi.SuspendToIdle.json

We want suspend to idle enabled to pass.
Fixes: https://github.com/fwupd/fwupd/issues/5980

trivial: correct HSI documentation for suspend to idle

---

libfwupdplugin/fu-i2c-device.c

These usually have very unhelpful names, e.g. `AUX A DDC` -- and MST plugins are doing various crazy and fragile things to match the correct one.
Lets help by providing the HwId as part of the matched instance ID, e.g.
FuEngine             /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-1/i2c-5 added FuI2cDevice:
Flags:                none
Guid[quirk]:          8a8c2f6d-6256-5d5f-9d20-6b5263af613d <- I2C\NAME_AUX-B-DDI-B-PHY-B
Guid[quirk]:          c03110b9-e7ce-5b41-9bea-775f6f3f531c <- I2C\NAME_AUX-B-DDI-B-PHY-B&HWID_4ba7930e-afa6-547a-9155-e6d02898db42
...
BackendId:            /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-1/i2c-5
Number:               0x5
Subsystem:            i2c
DeviceFile:           /dev/i2c-5
FuEngine             removing …

Add HWID-specific quirk-only GUIDs to I2C devices

---

plugins/ccgx-dmc/ccgx-dmc.quirk

Update quirk file to include HP Engage One Pro Aio system

Update quirk file to include HP Engage One Pro Aio system

---

contrib/launch-venv.sh

Fixes: https://github.com/fwupd/fwupd/issues/7557

venv: Prompt to copy in dbus configuration to filesystem if missing

---

libfwupd/fwupd-device.c

trivial: Notify when FwupdDevice::id is changed

---

src/fu-util.c

Fixes: https://github.com/fwupd/fwupd/issues/7562

trivial: update message about supported devices

---

libfwupdplugin/fu-bluez-device.c

Since Alias could be changed by end-user we can't rely to Alias-based GUID, so have to use Name-based one. In the same time alias is still needed to show proper name for the device, also Alias-based GUID is useful for developent purposes:
```
Name:                 QCC5171 SomeAlias
Guid:                 2216161a-9f4e-59f4-ba05-b202e0c28e16 <- BLUETOOTH\NAME_QCC5171 ?
Guid[quirk]:          794a101b-800d-5b6a-81d4-e6df2891ec83 <- BLUETOOTH\ALIAS_QCC5171 SomeAlias
```
Partially reverting 93dcfd54

trivial: return back Name-based GUID for bluetooth devices

---

plugins/parade-lspcon/README.md
plugins/parade-lspcon/fu-parade-lspcon-device.c
plugins/parade-lspcon/fu-parade-lspcon-plugin.c
plugins/parade-lspcon/fu-parade-lspcon.rs
plugins/parade-lspcon/meson.build
plugins/parade-lspcon/parade-lspcon.quirk

parade-lspcon: Convert some defines to rs format

---

libfwupdplugin/fu-i2c-device.c
libfwupdplugin/fu-i2c-device.h
meson.build
plugins/elantp/fu-elantp-i2c-device.c
plugins/parade-lspcon/fu-parade-lspcon-device.c
plugins/realtek-mst/fu-realtek-mst-device.c

This allows us to put the #ifdef complexity in just one place.

Add fu_i2c_device_set_address() moving all common code

---

libfwupd/fwupd-enums.c
libfwupd/fwupd-enums.h
libfwupdplugin/fu-version-common.c

trivial: move the new added dell-bios-msb to enum's tail

---

src/fu-dbus-daemon.c

trivial: allow running HSI on privileged Xen

---

plugins/uefi-capsule/fu-uefi-capsule-plugin.c
plugins/uefi-capsule/fu-uefi-cod-device.c
plugins/uefi-capsule/fu-uefi-device.c
plugins/uefi-capsule/fu-uefi-device.h
plugins/uefi-capsule/uefi-capsule.quirk

capsule on disk: add support for Dell systems

---

libfwupdplugin/fu-device-private.h
libfwupdplugin/fu-device.c
src/fu-engine.c

Do not add inhibits for non-updatable devices

---

plugins/vli/fu-vli-usbhub-device.c

vli: Fix the usb3 private flag registration

---

data/device-tests/meson.build
data/device-tests/parade-ps5512evb.json
plugins/meson.build
plugins/parade-usbhub/README.md
plugins/parade-usbhub/fu-parade-usbhub-common.h
plugins/parade-usbhub/fu-parade-usbhub-device.c
plugins/parade-usbhub/fu-parade-usbhub-device.h
plugins/parade-usbhub/fu-parade-usbhub-firmware.c
plugins/parade-usbhub/fu-parade-usbhub-firmware.h
plugins/parade-usbhub/fu-parade-usbhub-plugin.c
plugins/parade-usbhub/fu-parade-usbhub-plugin.h
plugins/parade-usbhub/fu-parade-usbhub.rs
plugins/parade-usbhub/meson.build
plugins/parade-usbhub/parade-usbhub.quirk

parade-usbhub: Add plugin to update USB hubs

---

contrib/ci/check-source.py
libfwupd/fwupd-client.c
libfwupdplugin/fu-crc.c
libfwupdplugin/fu-intel-thunderbolt-nvm.c
libfwupdplugin/fu-self-test.c
plugins/modem-manager/fu-mbim-qdu-updater.c
plugins/uefi-capsule/fu-uefi-capsule-plugin.c
src/fu-dbus-daemon.c
src/fu-engine.c
src/fu-polkit-agent.c
src/fu-usb-backend.c

This seems to be something that a lot of new submissions get wrong.

trivial: Check new plugins for g_print()

---

libfwupdplugin/fu-context.c
libfwupdplugin/fu-volume.c

This will make sure that they are not even added to
possible list instead of just set as proper priority
in the plugins.
Fixes: https://github.com/fwupd/fwupd/issues/6477

Avoid adding blocked partitions to ESP volume list

---

libfwupdplugin/fu-drm-device.c

trivial: Use the EDID PNP ID as the DRM vendor ID

---

plugins/uf2/uf2.quirk

trivial: Sync the family list with https://github.com/microsoft/uf2

---

src/fu-dbus-daemon.c

trivial: Correctly detect Xen

---

plugins/logitech-hidpp/fu-logitech-hidpp-device.c

Cherry-pick of 61d8d6219b28d73d2add34b630217725e5216cd5
Tested with M750
Fixes https://github.com/fwupd/fwupd/issues/7011 for stable branch.

logitech-hidpp: do not ping paired devices

---

contrib/ci/check-source.py
libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-usb-device.c
plugins/modem-manager/fu-mm-utils.c
plugins/mtd/fu-self-test.c
plugins/redfish/fu-redfish-network.c
plugins/thunderbolt/fu-self-test.c

trivial: Add two more functions to check-source.py

---

plugins/mediatek-scaler/fu-mediatek-scaler-common.c

mediatek_scaler: bugfix for device firmware version

---

libfwupdplugin/fu-msgpack.c
libfwupdplugin/fu-msgpack.h
libfwupdplugin/fu-self-test.c

Add fu_msgpack_map_lookup() for future use

---

contrib/ci/check-source.py
libfwupd/fwupd-bios-setting.c
libfwupdplugin/fu-cab-firmware.c
libfwupdplugin/fu-efi-lz77-decompressor.c
libfwupdplugin/fu-fdt-firmware.c
libfwupdplugin/fu-input-stream.c
libfwupdplugin/fu-io-channel.c
libfwupdplugin/fu-string.c
libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-version-common.c
libfwupdplugin/fu-volume.c
plugins/dfu/fu-dfu-device.c
plugins/dfu/fu-dfu-target.c
plugins/logitech-hidpp/fu-logitech-hidpp-common.c
plugins/modem-manager/fu-mm-utils.c
plugins/mtd/fu-self-test.c
plugins/redfish/fu-redfish-network.c
plugins/thunderbolt/fu-self-test.c
src/fu-unix-seekable-input-stream.c
src/fu-usb-backend.c
src/fu-util-common.c

trivial: Qualify the nocheck skipped CI tests

---

contrib/ci/check-source.py
src/fu-dbus-daemon.c
src/fu-engine-helper.c
src/fu-engine-request.c
src/fu-engine-request.h
src/fu-engine.c
src/fu-self-test.c
src/fu-tool.c
src/fu-util.c

At 953 lines it's pretty obscene. Also, add a check when running precommit.
No logic changes.

Split up fu_dbus_daemon_method_call()

---

libfwupdplugin/fu-i2c-device.c

On Kria devices the I2C string has extra components, so it can't
be taken as the last argument:
"/sys/devices/platform/axi/ff030000.i2c/i2c-1/1-0050"
So look for the first token that starts with "i2c-" instead.

Fix getting device number from AMD Kria devices

---

libfwupdplugin/fu-device.c

Should fix a regression in the qualcomm code.

Do not incorporate proxies if refcounted

---

src/fu-util.c

trivial: Be less passive when showing local updates

---

libfwupd/README.md
libfwupd/fwupd-client-sync.c
libfwupd/fwupd-client-sync.h
libfwupd/fwupd-client.c
libfwupd/fwupd-client.h
libfwupd/fwupd-common-private.h
libfwupd/fwupd-common.c
libfwupd/fwupd.map
src/fu-dbus-daemon.c
src/fu-engine.c
src/fu-engine.h
src/fu-util.c
src/org.freedesktop.fwupd.xml

Pushing ~300MB files over the bus is a huge amount of IO.

Create emulation data using a file descriptor

---

libfwupdplugin/fu-msgpack-item.c
libfwupdplugin/fu-msgpack-item.h
libfwupdplugin/fu-self-test.c

Add fu_msgpack_item_new_binary_stream() for future use

---

data/org.freedesktop.fwupd.metainfo.xml

It's not ready for tagging yet, but maybe soon.

trivial: Start writing some release notes for 2.0.0

---

data/device-tests/huddly-s1.json
data/device-tests/meson.build
plugins/huddly-usb/README.md
plugins/huddly-usb/fu-huddly-usb-common.c
plugins/huddly-usb/fu-huddly-usb-common.h
plugins/huddly-usb/fu-huddly-usb-device.c
plugins/huddly-usb/fu-huddly-usb-device.h
plugins/huddly-usb/fu-huddly-usb-plugin.c
plugins/huddly-usb/fu-huddly-usb-plugin.h
plugins/huddly-usb/fu-huddly-usb.rs
plugins/huddly-usb/huddly-usb.quirk
plugins/huddly-usb/meson.build
plugins/meson.build

Add support for Huddly USB cameras

---

meson_options.txt

We could get in a better habit of doing this with new options going
forward.

trivial: sort meson options alphabetically

---

meson.build
src/fu-polkit-authority.c

Drop support for compiling against older polkit.

trivial: require polkit 0.114 or later

---

contrib/ci/ubuntu.sh
meson.build
src/fu-engine.c
subprojects/flashrom.wrap
subprojects/gi-docgen.wrap
subprojects/libxmlb.wrap
subprojects/passim.wrap

trivial: update all subprojects to current versions

---

contrib/ci/check-source.py
libfwupdplugin/fu-common.h
libfwupdplugin/fu-coswid-firmware.c
libfwupdplugin/fu-crc.c
libfwupdplugin/fu-self-test.c
plugins/ccgx/fu-ccgx-hpi-device.c
plugins/dell-dock/fu-dell-dock-ec.c
plugins/dfu/fu-dfu-device.c
plugins/parade-usbhub/fu-parade-usbhub-device.c
plugins/synaptics-cxaudio/fu-synaptics-cxaudio-device.c
plugins/synaptics-rmi/fu-synaptics-rmi-common.c
plugins/wacom-usb/fu-wac-module-bluetooth.c

@superm1 I'm not sure if these would be more understandable as `FU_BITWISE_SET`. I'm also not against `FU_BIT_SET` if that's the convention.

Add some helpers for common bitwise operations

---

plugins/algoltek-usbcr/README.md
plugins/algoltek-usbcr/algoltek-usbcr.quirk
plugins/algoltek-usbcr/fu-algoltek-usbcr-common.h
plugins/algoltek-usbcr/fu-algoltek-usbcr-device.c
plugins/algoltek-usbcr/fu-algoltek-usbcr-device.h
plugins/algoltek-usbcr/fu-algoltek-usbcr-firmware.c
plugins/algoltek-usbcr/fu-algoltek-usbcr-firmware.h
plugins/algoltek-usbcr/fu-algoltek-usbcr-plugin.c
plugins/algoltek-usbcr/fu-algoltek-usbcr-plugin.h
plugins/algoltek-usbcr/fu-algoltek-usbcr.rs
plugins/algoltek-usbcr/meson.build
plugins/meson.build

Add support for Algoltek USB card reader devices

---

libfwupdplugin/fu-device.c

trivial: Fix a logic thinko when incorporating proxies

---

plugins/elanfp/elanfp.quirk
plugins/elanfp/fu-elanfp-device.c

Add hardware reset command when firmware update finished.

elanfp: Add PID 0x0C9F

---

libfwupdplugin/fu-io-channel.c
src/fu-engine.c
src/fu-udev-backend.c

Quiet down some warnings about failed to probe devices 

---

libfwupdplugin/fu-backend.c
libfwupdplugin/fu-backend.h
libfwupdplugin/fu-self-test.c
plugins/redfish/fu-redfish-backend.c
plugins/redfish/fu-redfish-plugin.c
plugins/uefi-capsule/fu-uefi-backend-freebsd.c
plugins/uefi-capsule/fu-uefi-backend-linux.c
plugins/uefi-capsule/fu-uefi-capsule-plugin.c
src/fu-bluez-backend.c
src/fu-dbus-daemon.c
src/fu-engine.c
src/fu-engine.h
src/fu-self-test.c
src/fu-tool.c
src/fu-usb-backend.c

trivial: Do not set up device hotplug in the self tests

---

plugins/mtd/fu-mtd-device.c
plugins/mtd/fu-self-test.c

mtd: Fix the unit test to not depend on GUdevClient

---

libfwupdplugin/fu-usb-device.c

This saves an incredible 2.5MB of RSS allocations at startup.

Read from the USB descriptors fd and work around weirdness

---

libfwupdplugin/fu-context-private.h
libfwupdplugin/fu-context.c
libfwupdplugin/fu-context.h
libfwupdplugin/fu-quirks.c
libfwupdplugin/fu-quirks.h
libfwupdplugin/fu-self-test.c
src/fu-daemon.c
src/fu-engine.c
src/fu-history.c
src/fu-history.h
src/fu-self-test.c
src/fu-tool.c

Use sqlite3_db_release_memory() to reduce post-load RSS by 400Kb

---

plugins/dell-k2/fu-dell-k2-ec-hid.c

dell-k2: add HID address to communicate with predecessor docks

---

plugins/huddly-usb/huddly-usb.quirk

Add support for Huddly Crew

---

plugins/nordic-hid/fu-nordic-hid-archive.c

Change introduces support for dfu_application.zip with "format-version" of "1".

plugins: nordic-hid: Support dfu_application.zip version 1

---

libfwupdplugin/fu-v4l-device.c
libfwupdplugin/fu-v4l-device.h
libfwupdplugin/fu-v4l.rs
libfwupdplugin/fwupdplugin.h
libfwupdplugin/meson.build
meson.build
plugins/logitech-scribe/fu-logitech-scribe-device.c
plugins/logitech-scribe/fu-logitech-scribe-device.h
plugins/logitech-tap/fu-logitech-tap-hdmi-device.c
plugins/logitech-tap/fu-logitech-tap-hdmi-device.h
src/fu-udev-backend.c

Create a FuV4lDevice to avoid relying on udev for ID_V4L_CAPABILITIES

---

plugins/nordic-hid/fu-nordic-hid-archive.c

plugins: nordic-hid: Support dfu_application.zip version 1 backport

---

plugins/logitech-rallysystem/fu-logitech-rallysystem-plugin.c

overwrite tablehub version with system version

---

src/fu-udev-backend.c

trivial: add udev device only if the sysfs path exists

---

libfwupd/fwupd-device.c
libfwupd/fwupd-self-test.c
libfwupdplugin/fu-device.c
libfwupdplugin/fu-self-test.c

trivial: Ensure the ID, parent ID and equivalent ID are all SHA1 checksums

---

libfwupd/fwupd-enums.c
libfwupd/fwupd-enums.h
libfwupdplugin/fu-device.c
plugins/usi-dock/fu-usi-dock-child-device.c
plugins/usi-dock/fu-usi-dock-child-device.h
plugins/usi-dock/fu-usi-dock-plugin.c
plugins/usi-dock/fu-usi-dock.rs
src/fu-engine.c
src/fu-self-test.c
src/fu-util-common.c

Fixes some of https://github.com/fwupd/fwupd/issues/7769

Add a device problem for a lower-priority equivalent device

---

plugins/logitech-hidpp/fu-logitech-hidpp-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime-bolt.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime-unifying.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime.h

This fixes a recent regression and removes a lot of extra code.

logitech-hidpp: Port FuLogitechHidppRuntime to use FuHidrawDevice

---

libfwupdplugin/fu-input-stream.c
libfwupdplugin/fu-input-stream.h
libfwupdplugin/fu-self-test.c

Add fu_input_stream_find() for future use

---

src/fu-engine.c

Found by Oliver Gutierrez, many thanks.

Allow UEFI capsule config values to be set with fwupdmgr modify-config

---

libfwupdplugin/fu-rustgen-struct.c.in
libfwupdplugin/fu-rustgen-struct.h.in
libfwupdplugin/rustgen.py

trivial: Support signed integers in rustgen

---

plugins/logitech-tap/fu-logitech-tap-plugin.c
plugins/logitech-tap/fu-logitech-tap-sensor-device.c
plugins/logitech-tap/fu-logitech-tap-sensor-device.h
plugins/logitech-tap/fu-logitech-tap-touch-common.h
plugins/logitech-tap/fu-logitech-tap-touch-device.c
plugins/logitech-tap/fu-logitech-tap-touch-device.h
plugins/logitech-tap/fu-logitech-tap-touch-firmware.c
plugins/logitech-tap/fu-logitech-tap-touch-firmware.h
plugins/logitech-tap/fu-logitech-tap.rs
plugins/logitech-tap/logitech-tap.quirk
plugins/logitech-tap/meson.build

Add support for logitech TAP devices

---

libfwupdplugin/fu-usb-device.c

Fixes https://github.com/fwupd/fwupd/issues/7776

Fix a regression when enumerating USB devices

---

plugins/amd-gpu/fu-amd-gpu-device.c

Apparently the rest of the characters are not relevant for the purpose of making sure a firmware applies to a given part.
So shorten the GUID and only compare 10 characters from the rest.
(cherry picked from commit beb36b0ae846dd02dbb9e7faa1f2da0feb02edda)

amd-gpu: Only compare the first 10 characters of part number

---

meson.build
src/fu-dbus-daemon.c
src/fu-engine.c
src/fu-util.c

This fixes user agent issues when the package source happens to be
part of a different git tree.

trivial: don't use git tags for supported builds

---

libfwupd/fwupd-device.c
libfwupd/fwupd-release.c

This reduces the RSS churn by about 2MB when probing devices.

Only create FwupdDevice synamic arrays when required

---

plugins/uefi-capsule/fu-uefi-bootmgr.c
plugins/uefi-capsule/fu-uefi-capsule-plugin.c
plugins/uefi-capsule/fu-uefi-common.c
plugins/uefi-capsule/fu-uefi-common.h
plugins/uefi-capsule/fu-uefi-grub-device.c
plugins/uefi-capsule/fu-uefi-nvram-device.c

Minor changes for surrounding code in the cherry-pick.

Backport changes for looking in systemd directory on 1.9.x

---

contrib/ci/check-quirks.py
plugins/vli/vli-fujitsu.quirk

trivial: Check the quirk GTypes are valid

---

src/fu-self-test.c

5291414f450d66c8943ca15cc39853dfd4db2783 was merged a bit prematurely.

trivial: fix a ci failure on supported builds

---

src/fu-udev-backend.c

trivial: Don't shout about transient HID devices

---

libfwupdplugin/fu-device.c
src/fu-util-common.c

Fixes https://github.com/fwupd/fwupd/issues/7827

Add X-InputController for future hardware

---

src/fu-udev-backend.c

trivial: Split out the subsystem->GType code for future use

---

libfwupdplugin/fu-efi.rs

trivial: Fix the self test failure on s390x

---

plugins/amd-gpu/fu-amd-gpu-plugin.c
src/fu-device-list.c
src/fu-self-test.c

Fix FU_PLUGIN_RULE_BETTER_THAN to ignore lower priority devices

---

src/fu-engine-helper.c

Fixes https://app.transifex.com/freedesktop/fwupd/translate/#pt_BR/main/476674885

trivial: Use a placeholder for fwupdmgr commands

---

src/fu-console.c

trivial: Use placeholders for Y/N

---

libfwupdplugin/rustgen.py

trivial: Add the derived Getters trait on each nested struct type

---

libfwupdplugin/fu-input-stream.c
libfwupdplugin/fu-input-stream.h
libfwupdplugin/fu-self-test.c

Also ensure the data is aligned correctly.

trivial: Add fu_input_stream_compute_sum32() for future use

---

.editorconfig
libfwupdplugin/fu-io-channel.c

Minor fixes

---

src/fu-self-test.c

Skip the serio self tests if gnutls support was disabled

---

src/fu-engine.c

We were calling it once in fu_engine_get_result_from_component() with the wrong flags, and then again in fu_engine_get_details() with the correct flags.
Just do the first one correctly.

Only call fu_engine_load_release() once per get-details call

---

libfwupd/fwupd-client.c
libfwupd/fwupd-client.h
libfwupd/fwupd.map

We already had a sync version, but GUI software needs an async version too.

Add fwupd_client_get_details_async()

---

libfwupdplugin/fu-backend.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-udev-device.h

trivial: Add fu_udev_device_read_sysfs_bytes() for future use

---

docs/device-emulation.md

Should hopefully make it easier for a n00b to follow.

trivial: Update emulation documentation

---

plugins/wacom-usb/fu-wac-device.c
plugins/wacom-usb/fu-wac.rs

wacom-usb: Convert the descriptor parsing to rustgen

---

plugins/logitech-tap/fu-logitech-tap-sensor-device.c
plugins/logitech-tap/fu-logitech-tap.rs

[fwupdtool_vv_get-devices.zip](https://github.com/user-attachments/files/17298938/fwupdtool_vv_get-devices.zip)

Initial version, leverage rust for hid transfer

---

contrib/pcap2emulation.py

This get the Ally Windows dump into something that actually "loads" by fwupd.

Fixups for pcap2emulation

---

src/fu-self-test.c

trivial: Fix self tests when compiling with -Dplugin_scsi=disabled

---

libfwupdplugin/fu-composite-input-stream.c
libfwupdplugin/fu-intel-thunderbolt-nvm.c
libfwupdplugin/fu-partial-input-stream.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/fu-string.c
plugins/synaptics-cape/fu-synaptics-cape-sngl-firmware.c

trivial: Make it easier to contruct a partial input stream

---

meson.build
meson_options.txt

Fixes https://github.com/fwupd/fwupd/issues/7877

Allow controlling the libdrm dependency

---

libfwupdplugin/fu-device.c

Based on a patch from Mario Limonciello, many thanks.

trivial: Do not allow recording emulation from emulated devices

---

plugins/intel-usb4/fu-intel-usb4-device.c
plugins/intel-usb4/fu-intel-usb4.rs

intel-usb4: Make reading the NVM less scary

---

src/fu-engine.c

Link: https://buildd.debian.org/status/fetch.php?pkg=fwupd&arch=amd64&ver=1.9.26-1&stamp=1728947877&raw=0

trivial: fix FTBFS without SOURCE_VERSION

---

policy/org.freedesktop.fwupd.policy.in

Fix policykit message for "emulation data collection"

---

subprojects/libxmlb.wrap

Use libxmlb 0.3.21 when building a subproject

---

libfwupdplugin/fu-udev-device.c
libfwupdplugin/fu-usb-device.c

trivial: Clear the uevent cache for FuDevice->invalidate()

---

libfwupdplugin/fu-rustgen.c.in
libfwupdplugin/fu-rustgen.h.in
libfwupdplugin/rustgen.py

This helps us in the future with circular header deps.

trivial: Include less headers when they're not needed

---

contrib/generate-ds20.py

We don't always need to pad the data.

trivial: Make generate-ds20.py slightly more useful

---

libfwupdplugin/fu-crc.c
libfwupdplugin/fu-crc.h
libfwupdplugin/fu-fit-firmware.c
plugins/bcm57xx/fu-bcm57xx-dict-image.c
plugins/bcm57xx/fu-bcm57xx-stage2-image.c
plugins/corsair/fu-corsair-bp.c

Add fu_crc32_bytes() for future use

---

plugins/cros-ec/fu-cros-ec-usb-device.c

Backported https://github.com/fwupd/fwupd/pull/7881 to 1.9.X stable branch 

Backport: cros-ec: fix the update flow

---

plugins/realtek-mst/fu-realtek-mst-device.c

realtek-mst: Fix a small memory leak when writing firmware

---

plugins/wacom-raw/README.md
plugins/wacom-raw/fu-wacom-device.c
plugins/wacom-raw/wacom-raw.quirk

wacom-raw: Use FirmwareSizeMax rather than a homegrown quirk key

---

data/device-tests/hp-dock-g6-ultra.json
data/device-tests/meson.build

Add a device test for HP TBT4 Ultra G6 Dock

---

plugins/logitech-bulkcontroller/logitech-bulkcontroller.quirk

[fwupdtool_v_output.log](https://github.com/user-attachments/files/17503027/fwupdtool_v_output.log)

Support Logitech Sight as standalone camera device

---

contrib/firmware_packager/README.md

Type of pull request: Documentation

Update README, resolves "Error in the firmwarepackager.py README.md (Issue #7955)"

---

.editorconfig
libfwupdplugin/fu-rustgen-struct.c.in
libfwupdplugin/fu-rustgen-struct.h.in

Rustgen constness

---

plugins/logitech-rallysystem/fu-logitech-rallysystem-tablehub-device.c

Increase delay for new firmware

---

plugins/amd-gpu/fu-amd-gpu-device.c

amd-gpu: Allow emulating DRM_IOCTL_AMDGPU_INFO

---

meson.build

This should let projects that subproject fwupd get the dep
Link: https://gitlab.gnome.org/World/gnome-firmware/-/issues/67

trivial: add fallback for jsonglib

---

src/fu-self-test.c

trivial: Fix self tests when compiling with -Dplugin_nvme=disabled

---

src/fu-dbus-daemon.c

Parse install flags from apps compiled against old libfwupd versions

---

data/device-tests/hailuck-keyboard.json
data/device-tests/meson.build

hailuck: Add an enumerate-only test

---

libfwupdplugin/fu-context.c
libfwupdplugin/fu-context.h
src/fu-self-test.c

trivial: Do not try to mount volumes in self tests

---

.codecov.yml
.github/workflows/ci.yml
.github/workflows/matrix.yml
.github/workflows/pull-request-reviews.yml

Switch from Coveralls to Codecov

---

.codecov.yml
libfwupdplugin/fu-udev-device.c
plugins/emmc/fu-emmc-device.c

emmc: Fix probing regression in 2.0.x

---

libfwupdplugin/fu-self-test.c

Fixes https://github.com/fwupd/fwupd/issues/8004

trivial: Don't do the polling self tests by default

---

plugins/dell-k2/dell-k2.quirk
plugins/dell-k2/fu-dell-k2-dpmux.c
plugins/dell-k2/fu-dell-k2-ec-hid.c
plugins/dell-k2/fu-dell-k2-ec-hid.h
plugins/dell-k2/fu-dell-k2-ec.c
plugins/dell-k2/fu-dell-k2-ec.h
plugins/dell-k2/fu-dell-k2-ec.rs
plugins/dell-k2/fu-dell-k2-ilan.c
plugins/dell-k2/fu-dell-k2-package.c
plugins/dell-k2/fu-dell-k2-pd.c
plugins/dell-k2/fu-dell-k2-plugin.c
plugins/dell-k2/fu-dell-k2-rmm.c
plugins/dell-k2/fu-dell-k2-rmm.h
plugins/dell-k2/fu-dell-k2-rtshub.c
plugins/dell-k2/fu-dell-k2-wtpd.c

Wip/cragw/dell k2 fix write fw 1.9.27

---

plugins/dell-k2/fu-dell-k2-plugin.c
plugins/synaptics-vmm9/fu-synaptics-vmm9-device.c

synaptics-vmm9: dell-k2: skip device restart after fw updated

---

contrib/snap/snapcraft.yaml
data/tests/fwupdmgr.sh
data/tests/fwupdtool.sh
libfwupd/fwupd-self-test.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/tests/meson.build
src/fu-self-test.c
src/fu-tool.c

Add some more test coverage

---

libfwupdplugin/fu-rustgen-struct.h.in
plugins/ata/fu-ata-device.c
plugins/redfish/fu-ipmi-device.c
plugins/synaptics-mst/fu-synaptics-mst-device.c
plugins/telink-dfu/fu-telink-dfu-ble-device.c
plugins/vli/fu-vli-usbhub-device.c
src/fu-device-list.c
src/fu-tool.c
src/fu-util-common.c
src/fu-util-common.h
src/fu-util.c

Ask the compiler to check more autogenerated rustgen code

---

plugins/dell-k2/fu-dell-k2-ec.c
plugins/dell-k2/fu-dell-k2-plugin.c

dell-k2: fix coverity issue and remove page delay time

---

contrib/ci/arch-test.sh
contrib/ci/debian-x86_64-test.sh
contrib/ci/fedora-test.sh
data/bash-completion/fwupdtool
data/tests/fwupdmgr.sh
data/tests/fwupdtool.sh
plugins/test/fu-test-plugin.c
src/fu-tool.c
src/fu-util.c

Add some more coverage on the test plugin

---

contrib/create-plugin.py
docs/device-emulation.md
plugins/vendor-example/meson.build.in
plugins/vendor-example/tests/vendor-example-setup.json
plugins/vendor-example/tests/vendor-example.json

vendor-example: Add test JSON files

---

libfwupdplugin/fu-elf-firmware.c

Fixes https://issues.oss-fuzz.com/u/1/issues/377100052

Fix a critical warning when parsing a corrupt ELF file

---

contrib/launch-venv.sh

fwupd 2.0.0 introduced org.freedesktop.fwupd.emulation-save but this needs to be recognized by the PK in the host environment rootfs.
When launching a venv based fwupdmgr check whether the PK policy exists and has this action.
If it doesn't, prompt the user to update it.

trivial: venv: Check for out of date PK policy on launch

---

plugins/amd-gpu/fu-amd-gpu-device.c
plugins/amd-gpu/meson.build
plugins/amd-gpu/tests/amd-dgpu-navi3x.json

Add an emulation for navi3x dGPU

---

libfwupdplugin/fu-archive.c
plugins/steelseries/fu-steelseries-device.c
plugins/steelseries/fu-steelseries-device.h
plugins/steelseries/fu-steelseries-fizz-gen1.c
plugins/steelseries/fu-steelseries-fizz-gen2.c
plugins/steelseries/fu-steelseries-fizz-hid.c
plugins/steelseries/fu-steelseries-fizz-impl.c
plugins/steelseries/fu-steelseries-fizz-impl.h
plugins/steelseries/fu-steelseries-fizz-tunnel.c
plugins/steelseries/fu-steelseries-fizz.c
plugins/steelseries/fu-steelseries-fizz.h
plugins/steelseries/fu-steelseries-fizz.rs
plugins/steelseries/fu-steelseries-gamepad.c
plugins/steelseries/fu-steelseries-gamepad.rs
plugins/steelseries/fu-steelseries-mouse.c
plugins/steelseries/fu-steelseries-sonic.c
plugins/steelseries/fu-steelseries-sonic.rs
plugins/steelseries/meson.build
plugins/steelseries/tests/steelseries-aerox-3-wireless.json
plugins/steelseries/tests/steelseries-rival-3-wireless.json
plugins/steelseries/tests/steelseries-stratus-duo-rx.json
plugins/steelseries/tests/steelseries-stratus-duo.json
src/fu-engine.c
src/fu-util.c

steelseries: Convert to rustgen

---

contrib/ci/coverage.sh
plugins/corsair/fu-corsair-device.c
plugins/genesys/fu-genesys-usbhub-device.c
src/fu-self-test.c

trivial: Ignore more self test asserts

---

contrib/ci/dependencies.xml
libfwupdplugin/fu-bios-settings.c
plugins/uefi-capsule/fu-uefi-capsule-plugin.c
plugins/uefi-dbx/fu-uefi-dbx-device.c

Backport some 1-9-x fixes 

---

data/tests/fwupdtool.sh
src/fu-tool.c

Some more coverage checks for fwupdtool

---

plugins/telink-dfu/README.md
plugins/telink-dfu/fu-telink-dfu-archive.c
plugins/telink-dfu/fu-telink-dfu-ble-device.c
plugins/telink-dfu/fu-telink-dfu-common.c
plugins/telink-dfu/fu-telink-dfu-common.h
plugins/telink-dfu/fu-telink-dfu-hid-device.c
plugins/telink-dfu/fu-telink-dfu-hid-device.h
plugins/telink-dfu/fu-telink-dfu-plugin.c
plugins/telink-dfu/fu-telink-dfu.rs
plugins/telink-dfu/meson.build
plugins/telink-dfu/telink-dfu.quirk
plugins/telink-dfu/tests/telink-ryder-dongle.json

add VID/PID to support Ryder and Telink 8272 2.4g dongle
- [x ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [v] Feature

support DFU over USB HID for dongle devices

---

libfwupdplugin/rustgen.py

trivial: Add a private export for rustgen struct-in-struct `derive(New)`

---

plugins/uefi-capsule/fu-uefi-device.c
plugins/uefi-capsule/fu-uefi-device.h
plugins/uefi-capsule/fu-uefi-grub-device.c
plugins/uefi-capsule/fu-uefi-nvram-device.c

Fixes https://github.com/fwupd/fwupd/issues/7350

uefi-capsule: Only check for fwupdx64.efi when NOT using CoD

---

data/tests/fwupd.sh

trivial: enable ivrs self tests for CI

---

plugins/meson.build
plugins/rp-pico/README.md
plugins/rp-pico/fu-rp-pico-device.c
plugins/rp-pico/fu-rp-pico-device.h
plugins/rp-pico/fu-rp-pico-plugin.c
plugins/rp-pico/fu-rp-pico-plugin.h
plugins/rp-pico/fu-rp-pico.rs
plugins/rp-pico/meson.build
plugins/rp-pico/tests/mnt-pocket-reform-sysctl-setup.json
plugins/rp-pico/tests/mnt-pocket-reform-sysctl.json
plugins/uf2/README.md
plugins/uf2/fu-uf2-device.c
plugins/uf2/uf2.quirk
src/fu-daemon.c

Mostly soliciting feedback for now. This branch includes hughsie/subsystem_devtype and zeha/uf2-reenum.
plugin checklist:

Add rp_pico plugin

---

plugins/intel-usb4/meson.build
plugins/intel-usb4/tests/intel-gatkex-setup.json
plugins/intel-usb4/tests/intel-gatkex.json

intel-usb4: Add an enumeration-only test

---

plugins/ccgx-dmc/fu-ccgx-dmc-devx-device.c
plugins/ccgx-dmc/fu-ccgx-dmc.rs

- [*] Feature
Add new supported CCGx/DMC IC types.

trivial: Add more component types to ccgx-dmc for new generation Dock

---

plugins/scsi/fu-scsi-device.c
plugins/scsi/fu-scsi.rs

Use rust format to define SCSI_INQ

---

plugins/asus-hid/asus-hid.quirk
plugins/asus-hid/fu-asus-hid-child-device.c
plugins/asus-hid/fu-asus-hid-child-device.h
plugins/asus-hid/fu-asus-hid-device.c
plugins/asus-hid/fu-asus-hid-plugin.c
plugins/asus-hid/tests/asus-hid-setup.json

asus-hid parent/child model changes

---

plugins/parade-usbhub/README.md
plugins/parade-usbhub/fu-parade-usbhub-device.c
plugins/parade-usbhub/fu-parade-usbhub-plugin.c
plugins/parade-usbhub/fu-parade-usbhub.rs
plugins/parade-usbhub/parade-usbhub.quirk

parade-usbhub: Add support for PS188

---

plugins/synaptics-prometheus/synaptics-prometheus.quirk

synaptics-prometheus: add PID 0x108 to quirk file

---

plugins/uefi-dbx/uefi-dbx.quirk

Fixes https://github.com/fwupd/fwupd/issues/7645

uefi-dbx: Disallow DBX updates on the Samsung Galaxy Book2 360

---

contrib/vscode/README.md

PR fixes the `building.md` reference in `contrib/vscode/README.md`.

trivial: fix `building.md` reference

---

contrib/meson.build
contrib/sbom.cdx.json

This is designed as a proof-of-concept we can argue about before submitting to other projects that *do* get built into firmware.

Add a CycloneDX SBOM file

---

plugins/android-boot/fu-android-boot-device.c

trivial: Reduce the debugging spew when a partition has no UUID

---

libfwupdplugin/fu-rustgen-struct.c.in
libfwupdplugin/fu-rustgen-struct.h.in
libfwupdplugin/fu-self-test.c
libfwupdplugin/fu-self-test.rs
libfwupdplugin/rustgen.py

Add support for getting and setting rustgen array members

---

libfwupdplugin/fu-device.c
src/fu-util-common.c

trivial: Add two more hardware categories

---

plugins/qc-s5gen2/qc-s5gen2.quirk

qc-s5gen2: added VID/PID for GID8 headset

---

plugins/parade-usbhub/fu-parade-usbhub-device.c
plugins/parade-usbhub/parade-usbhub.quirk

Parade PS5511

---

libfwupdplugin/fu-device.c
plugins/steelseries/fu-steelseries-plugin.c
src/fu-device-list.c
src/fu-engine.c

steelseries: Assign the equivalent ID based on the device serial number

---

plugins/audio-s5gen2/audio-s5gen2.quirk

(cherry-picked from commit db4d7b69afe32ffa81e4110e34adec7b55715bfd)

audio-s5gen2: added VID/PID for GID8 headset

---

contrib/lsan-suppressions.txt
plugins/redfish/meson.build
plugins/tpm/lsan-suppressions.txt
plugins/tpm/meson.build

trivial: Ignore a tiny memory leak in OPENSSL_init_ssl()

---

libfwupdplugin/fu-cab-firmware-private.h
libfwupdplugin/fu-cab-firmware.c
libfwupdplugin/fu-self-test.c

Speed up decompressing large cab archives by 30%

---

data/meson.build
meson_options.txt

Closes: https://github.com/fwupd/fwupd/issues/8078

trivial: allow compiling without systemd system call filter support

---

plugins/jabra-file/fu-jabra-file-device.c
plugins/jabra-file/fu-jabra-file.rs

Adding some more stability to the plugin

fixing a few things to decrease chances of failure

---

plugins/dell-kestrel/fu-dell-kestrel-ec.c
plugins/dell-kestrel/fu-dell-kestrel-ec.rs

Fixes https://github.com/fwupd/fwupd/issues/8168

dell-kestrel: Fix a weird LE->BE conversion

---

plugins/jabra-gnp/tests/jabra-evolve2-75.json

jabra-gnp: Emulate updating a Jabra Evolve2 75 in CI

---

plugins/dell-kestrel/fu-dell-kestrel-hid-device.c

This works fine on LE hardware, less so on BE hardware.

dell-kestrel: Fix some big-endian issues

---

libfwupdplugin/fu-context-private.h
libfwupdplugin/fu-context.c
libfwupdplugin/fu-udev-device.c
plugins/ch347/fu-ch347-device.c
plugins/dell-kestrel/fu-dell-kestrel-hid-device.c
plugins/steelseries/fu-steelseries-fizz.c
plugins/telink-dfu/fu-telink-dfu-hid-device.c
src/fu-dbus-daemon.c
src/fu-self-test.c

trivial: Fix up several -Wunused-variable seen on macOS

---

plugins/pci-mei/fu-mei-common.h
plugins/pci-mei/fu-mei.rs
plugins/pci-mei/fu-pci-mei-plugin.c

pci-mei: Add some plugin debugging

---

plugins/dell-dock/fu-dell-dock-ec.c
plugins/dell-dock/fu-dell-dock-plugin.c

dell-dock: bugfix for removing the parent and children devices

---

plugins/dell-kestrel/fu-dell-kestrel-ec.rs
plugins/dell-kestrel/fu-dell-kestrel-hid-device.c
plugins/dell-kestrel/fu-dell-kestrel-hid.rs

dell-kestrel: early finish the writing if already success

---

libfwupdplugin/fu-context.c

Fixes https://github.com/fwupd/fwupd/issues/8005

Skip checking BootXXXX entries when the partition does not exist

---

plugins/jabra-file/meson.build
plugins/jabra-file/tests/jabra-panacast-50-setup.json
plugins/jabra-file/tests/jabra-panacast-50.json

jabra-file: Emulate updating a Jabra PanaCast 50 in CI

---

plugins/modem-manager/fu-sahara-loader.c
plugins/modem-manager/fu-sahara.rs
plugins/modem-manager/meson.build

modem-manager: Convert the Sahara loader to Rust format

---

plugins/synaptics-cape/fu-synaptics-cape-device.c
plugins/synaptics-cape/fu-synaptics-cape.rs

synaptics-cape: Move more code to Rust format

---

contrib/fwupd.spec.in

trivial: Sync example spec file with downstream Fedora

---

src/fu-engine-requirements.c

This regressed in bfa5fe6.
Fixes https://github.com/fwupd/fwupd/issues/8219

Show updates with problems when using 'fwupdmgr get-releases'

---

plugins/pixart-rf/pixart-rf.quirk

Add new VID/PID device in pixart-rf.quirk

---

libfwupdplugin/fu-context.c

trivial: Exclude directories from second stage bootloader checks

---

libfwupdplugin/fu-device.c

trivial: Speed up registering private flags

---

data/tests/fwupdmgr-p2p.sh
data/tests/fwupdtool.sh

trivial: Make sure the verbose debugging gets covered in CI

---

plugins/modem-manager/fu-mm-device.c

Switches any Sahara capable devices into the EDL mode in `->detach()` just like `fastboot` does to switch the bootloader.
This should enable/fix switching to EDL for all devices except MHI PCI.
MHI PCI devices do not use Sahara, but require copying a Firehose bootloader file from the cabinet archive before switching, which is not yet available in `->detach()`. I don't know if this fixes any issues with MHI PCI modems, I also do not have any hardware to test it with.

modem-manager: Detach Sahara devices

---

plugins/vli/fu-vli-pd-firmware.c
plugins/vli/vli-lenovo.quirk

Why Yuletide greetings, 
WIP: fixed initial CRC16 value for PD and added another Lenovo device. Much obliged.

vli:pd crc fix, add to lenovo

---

data/meson.build

Fixes https://github.com/fwupd/fwupd/issues/7408

Add fadvise64 to the systemd syscall allowlist

---

libfwupdplugin/fu-device.c
src/fu-util-common.c

Fixes https://github.com/fwupd/fwupd/issues/8258

trivial: Fix a string to be less misleading

---

generate-build/generate-man.py

trivial: Fix the man generator to include daemon-default values

---

src/fu-daemon.c

trivial: Dump the report metadata to the console when verbose debugging

---

plugins/logitech-scribe/fu-logitech-scribe-device.c
plugins/logitech-scribe/fu-logitech-scribe.rs
plugins/logitech-scribe/meson.build

logitech-scribe: Move an enum to rust format

---

src/fu-engine.c
src/fu-self-test.c

Dedupe releases using the checksum and the component version combined to avoid removing the final "target" release for a single-device multi-step one-archive composite update.
Fixes https://github.com/fwupd/fwupd/issues/8257

Show the correct version when installing a same-device composite update

---

libfwupd/fwupd-client.c

If the network address isn't reachable, return NOTHING_TO_DO.
Fixes: https://github.com/fwupd/fwupd/issues/8144

libfwupd: Detect if network is reachable before downloading metadata

---

plugins/nordic-hid/fu-nordic-hid-cfg-channel.c

PR fixes communication with peripherals connected via dongle.

nordic-hid: Fix communication with dongle connected devices

---

data/motd/fwupd-refresh.service.in
libfwupd/fwupd-client.c
libfwupd/fwupd-error.c
libfwupd/fwupd-error.h
src/fu-tool.c
src/fu-util-common.h
src/fu-util.c

Use a custom return code for network connectivity failures on refresh

---

src/fu-engine.c

Check if passim is enabled before calling the symbol to try to connect to it in the first place.
Fixes: #8254

trivial: Lazy load the connection to Passim

---

docs/nda.md

I'm often asked to sign NDAs and I'm getting a bit sick of re-typing the email.

Add some notes about NDAs

---

data/tests/fwupdmgr.sh
data/tests/meson.build

trivial: fu-util: add some more coverage for fwupdmgr

---

data/tests/fwupdtool.sh

trivial: fu-tool: add some more simple command coverage

---

contrib/ci/arch-test.sh

trivial: ci: compile qt5-thread-check for coverage

---

data/tests/fwupdmgr.sh

trivial: ci: add coverage for enable/disable remotes

---

libfwupd/fwupd-enums.c
libfwupd/fwupd-self-test.c

Test coverage for device flags

---

contrib/ci/arch-test.sh
data/tests/fwupdmgr.sh
libfwupdplugin/fu-device.c

trivial: ci: run fwupd.sh tests in arch

---

libfwupd/fwupd-self-test.c

3 major changes:
* By using `g_test_undefined()` then coverage for things like setters and getters which will cause an abort can be covered.
* Cover some missing areas for libfwupd API.
* Experiment with using `GCOVR_EXCL_START` to see how it would work in practice for specific error or warning paths we don't care about for coverage.

Add some more test coverage for libfwupd

---

libfwupdplugin/fu-device.c

trivial: Split out fu_device_get_common_class_parents() for future use

---

contrib/ci/dependencies.xml
contrib/ci/fwupd_setup_helpers.py

Perhaps fixes https://github.com/fwupd/fwupd/issues/8330

trivial: Fix ./contrib/setup on RHEL 9

---

libfwupdplugin/fu-self-test.c

trivial: add test coverage for `fu_common_guid_is_plausible()`

---

libfwupdplugin/fu-self-test.c

trivial: add test coverage for kernel search path modifications

---

libfwupd/fwupd-client.c

See https://github.com/fwupd/fwupd/pull/8335#discussion_r1917915981

trivial: Only call g_network_monitor_can_reach() once per download request

---

plugins/amd-gpu/fu-amd-gpu-device.c

Recently there have been some cases that the amd-gpu plugin isn't showing update that /should/ be present. This is because the version string was being misinterpreted.
The version string is supposed to be populated by the VBIOS P/N not "the legacy" CSM version string.
A typical string is:
```
XXX-YYYYYYZZ-WWW
```
`XXX-YYYYYY` is used for matching a given board.  This is what was done as part of commit ea8ee1b69 ("amd-gpu: Only compare the first 10 characters of part number").
But the `WWW` is actually a collection of ALL firmware changes and will change any time the firmware is changed in ANY way.  It should be used to reflect the version.
Adjust the `setup()` callback to tokeninze the string and split it. If tokenization fails (such as on really old parts) then just show the CSM string …

amd-gpu: Split up the VBIOS P/N for the version

---

data/tests/fwupd.sh
data/tests/lsan-suppressions.txt
data/tests/meson.build
plugins/redfish/meson.build
plugins/tpm/meson.build

trivial: Ignore SSL_CTX_new_ex when running the installed tests

---

.github/workflows/matrix.yml

As discussed in https://github.com/fwupd/fwupd/issues/8327#issuecomment-2593366381

trivial: ci: tweak formatting of matrix job steps, consistently pass CI and CI_NETWORK

---

libfwupdplugin/fu-bytes.c
libfwupdplugin/fu-bytes.h
libfwupdplugin/fu-efi-signature.c
plugins/tpm/fu-tpm-eventlog-common.c
plugins/tpm/fu-tpm-eventlog-common.h
plugins/tpm/fu-tpm-eventlog-parser.c
plugins/tpm/fu-tpm-plugin.c

trivial: Export fu_bytes_to_string() in libfwupdplugin

---

libfwupdplugin/fu-plugin.c
plugins/dell-kestrel/fu-dell-kestrel-plugin.c

dell-kestrel: cleanup the devices when disconnected

---

libfwupdplugin/fu-device.c

trivial: Use the device firmware GType when dumping firmware

---

src/fu-util.c

Allow skipping device tests by CPU architecture

---

plugins/elanfp/elanfp.quirk

elanfp: Add PID 0x0CA3

---

libfwupdplugin/fu-usb-device.c

Some devices export multiple HID descriptors, where the one cannot be read.
In `libusb -v` this would show as `** UNAVAILABLE **` so it should not be fatal.

trivial: Ignore HID descriptors that cannot be read

---

src/fu-util.c

If a given firmware upgrade fails when running install or downgrade
the user should ideally still be prompted to upload the failure
report when the tool is run interactively.

Request to upload failed reports for install/downgrade too

---

.github/ISSUE_TEMPLATE/bug-report-general.md
.github/ISSUE_TEMPLATE/bug-report-uefi.md
.github/ISSUE_TEMPLATE/bug-report-wd19.md
.github/ISSUE_TEMPLATE/question.md
contrib/ci/arch-test.sh
contrib/ci/fedora-test.sh
data/tests/fwupd.sh
data/tests/fwupdmgr-p2p.sh
data/tests/fwupdmgr.sh
data/tests/fwupdtool.sh

Use `fwupdtool get-report-metadata` in bug reports

---

data/tests/fwupd.sh
data/tests/fwupdmgr.sh
data/tests/fwupdtool.sh
src/fu-console.c

Remove progress prints from CI

---

data/tests/fwupd.sh

trivial: ci: run device tests in json mode

---

src/fu-tool.c
src/fu-util.c

More json handling improvements for tools

---

plugins/uefi-dbx/fu-self-test.c

uefi-dbx: Do not show a Polkit dialog when running self tests

---

meson.build

This gets us one step closer to the nice new stuff in C23.

trivial: Compile as ISO/IEC 9899:2018

---

src/fu-util.c

trivial: Fix a Coverity-discovered false positive

---

libfwupdplugin/fu-uswid-firmware.c

Do not close the base stream when decompressing uSWID firmware

---

libfwupdplugin/fu-pefile-firmware.c

The VeraCrypt binary has a PE/COFF section of `\0\0\0\0\0\0\0\0` -- which although isn't really in the spirit of the PE/COFF specification is actually perfectly valid. Just create something plausible and use the idx to identify the section.
See also: https://github.com/veracrypt/VeraCrypt/issues/1480

Fix dbx deployment by ignoring missing PE/COFF sections

---

.gitignore
contrib/test-venv.sh
src/fu-tool.c

Eventually I want to make this more usable/configurable for people to use.  But for now this will extend coverage for local testing.

Run some installed tests in the venv

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
libfwupdplugin/fu-hidraw-device.c

Allow USB-provided hidraw devices to use DS-20 descriptors

---

.github/workflows/snap.yml

trivial: snap: ci: set up and use snap specific TMPDIR, enable efiboot tests with a snap

---

plugins/logitech-hidpp/fu-logitech-hidpp-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-runtime-bolt.c

Explicitly open the communication channel for child.
See ab54573ad8494a574c0dc6eff478cdc3c8b6079a

logitech-hidpp: fix children detection

---

plugins/uefi-capsule/fu-uefi-capsule-backend-linux.c

This was changed in GLib in aac56f1618.

trivial: Do not use the deprecated g_unix_mount_at()

---

data/tests/fwupdmgr.sh
libfwupd/fwupd-bios-setting.c
libfwupd/fwupd-bios-setting.h
libfwupdplugin/fu-bios-setting.c
libfwupdplugin/fu-bios-settings-private.h
libfwupdplugin/fu-bios-settings.c
src/fu-engine.c
src/fu-util.c

trivial: Test `fwupdmgr get-bios-setting` in CI

---

contrib/ci/check-source.py
libfwupdplugin/fu-efi.rs
libfwupdplugin/rustgen.py
plugins/amd-kria/fu-amd-kria-persistent-firmware.c
plugins/amd-kria/fu-amd-kria-persistent.rs
plugins/amd-kria/fu-amd-kria-som-eeprom.rs
plugins/cros-ec/fu-cros-ec.rs
plugins/intel-gsc/fu-igsc-aux-device.c
plugins/intel-gsc/fu-igsc-device.c
plugins/intel-gsc/fu-igsc-device.h
plugins/intel-gsc/fu-igsc-heci.h
plugins/intel-gsc/fu-igsc-oprom-device.c
plugins/intel-gsc/fu-igsc-oprom-device.h
plugins/intel-gsc/fu-igsc.rs
plugins/kinetic-dp/fu-kinetic-dp.rs
plugins/pixart-rf/fu-pxi-ble-device.c
plugins/pixart-rf/fu-pxi-common.h
plugins/pixart-rf/fu-pxi-receiver-device.c
plugins/pixart-rf/fu-pxi-wireless-device.c
plugins/pixart-rf/fu-pxi.rs
plugins/qc-s5gen2/fu-qc-s5gen2.rs
plugins/synaptics-prometheus/fu-synaprom.rs
plugins/synaptics-rmi/fu-synaptics-rmi-ps2-device.c
plugins/synaptics-rmi/fu-synaptics-rmi.rs
plugins/system76-launch/fu-system76-launch-device.c
plugins/system76-launch/fu-system76-launch.rs
plugins/system76-launch/meson.build
plugins/thunderbolt/fu-self-test.c

synaptics-rmi: Convert some enumerations to Rust format

---

libfwupdplugin/fu-progress.c

Speed up startup by ~1% by limiting of precision of percentage updates

---

plugins/dell-kestrel/fu-dell-kestrel-hid-device.c

dell-kestrel: increase timeout for RMM ack

---

plugins/uefi-dbx/fu-self-test.c

Although it doesn't matter now, soon we will be using actual progress steps in `->write_firmware()`.

uefi-dbx: Use FuProgress properly in the self tests

---

plugins/hpi-cfu/fu-hpi-cfu-device.c
plugins/hpi-cfu/fu-hpi-cfu-device.h
plugins/hpi-cfu/fu-hpi-cfu-plugin.c
plugins/hpi-cfu/fu-hpi-cfu-plugin.h
plugins/hpi-cfu/fu-hpi-cfu.rs

hpi-cfu Copyright header update

---

plugins/dell-dock/fu-dell-dock-mst.c
plugins/dell-dock/fu-dell-dock-mst.h
plugins/dell-dock/fu-dell-dock-plugin.c
plugins/dell-dock/fu-dell-dock-status.c
plugins/dell-dock/fu-dell-dock-status.h

dell-dock: bugfix for mst instance id

---

plugins/dell-kestrel/fu-dell-kestrel-hid-device.c

dell-kestrel rmm cherrypick for 19x

---

.gitignore
.pre-commit-config.yaml

Add pre-commit hook to prevent committing any new binaries

---

plugins/dell-kestrel/fu-dell-kestrel-plugin.c

dell-kestrel: remove needs-activation for usb4 when device is added

---

contrib/ci/Dockerfile-arch.in
contrib/ci/Dockerfile-debian.in
contrib/ci/Dockerfile-fedora.in
contrib/ci/Dockerfile-precommit.in
contrib/ci/Dockerfile-ubuntu.in
contrib/ci/fedora-test.sh
contrib/ci/generate_docker.py

trivial: Do not use the legacy ENV format in Dockerfiles

---

libfwupdplugin/fu-linux-efivars.c

This works around a kernel regression (908af31f) that means it's now not possible to create a zero-size variable in efivarfs. Instead of creating an empty file so we can make it mutable -- then writing the contents -- just create it directly [mutable] and write directly.
Fixes: https://github.com/fwupd/fwupd/issues/8495
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2346831

Fix writing new EFI variables

---

libfwupdplugin/README.md
libfwupdplugin/fu-bytes.c
libfwupdplugin/fu-bytes.h
libfwupdplugin/fu-firmware.c
libfwupdplugin/fu-pefile-firmware.c
plugins/algoltek-aux/fu-algoltek-aux-firmware.c
plugins/ccgx-dmc/fu-ccgx-dmc-firmware.c
plugins/modem-manager/fu-dfota-updater.c
plugins/modem-manager/fu-firehose-updater.c
plugins/wacom-usb/fu-wac-device.c

trivial: Add the pad byte value to fu_bytes_pad()

---

plugins/uefi-capsule/fu-uefi-cod-device.c

Fixes https://github.com/fwupd/fwupd/issues/8512

Prepend the capsule header when using CoD

---

libfwupdplugin/fu-firmware.c
libfwupdplugin/fu-self-test.c

trivial: Allow fu_firmware_get_image_by_id() to take a full fnmatch glob

---

libfwupdplugin/fu-linux-efivars.c

trivial: Only set bare-metal efivarfs files as immutable

---

plugins/meson.build
plugins/qc-firehose/README.md
plugins/qc-firehose/fu-qc-firehose-device.c
plugins/qc-firehose/fu-qc-firehose-device.h
plugins/qc-firehose/fu-qc-firehose-plugin.c
plugins/qc-firehose/fu-qc-firehose-plugin.h
plugins/qc-firehose/fu-qc-firehose.rs
plugins/qc-firehose/meson.build
plugins/qc-firehose/qc-firehose.quirk
plugins/qc-firehose/tests/qc-ec25au-setup.json
plugins/qc-firehose/tests/qc-ec25au.json
plugins/qc-firehose/tests/qc-eg25ggc.json

qc-firehose: Add a standalone plugin that can update modems using Sahara

---

libfwupdplugin/fu-backend.c
libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
libfwupdplugin/fu-dpaux-device.c
libfwupdplugin/fu-udev-device.c
plugins/synaptics-mst/meson.build
plugins/synaptics-mst/tests/synaptics-panamera-setup.json
plugins/synaptics-mst/tests/synaptics-panamera.json

Allow emulating devices that derive from FuDpauxDevice

---

plugins/dell-kestrel/fu-dell-kestrel-ec.c
plugins/dell-kestrel/fu-dell-kestrel-ec.rs
plugins/dell-kestrel/fu-dell-kestrel-hid-device.c
plugins/dell-kestrel/fu-dell-kestrel-hid-device.h

dell-kestrel: bugfix for the passive bitmap for usb4 device

---

plugins/dell-kestrel/fu-dell-kestrel-ec.c
plugins/dell-kestrel/fu-dell-kestrel-ec.rs
plugins/dell-kestrel/fu-dell-kestrel-hid-device.c
plugins/dell-kestrel/fu-dell-kestrel-hid-device.h

dell-kestrel: bugfix for device uod bitmap in rust way

---

plugins/synaptics-mst/synaptics-mst.quirk

synaptics-mst: Add support for Lenovo USB-C Dual Display Travel Dock

---

libfwupd/fwupd-enums-private.h
libfwupd/fwupd-release.c
libfwupd/fwupd-release.h
libfwupd/fwupd-self-test.c
libfwupd/fwupd.map
src/fu-release.c
src/fu-util-common.c

Add support for showing the SBOM release URL

---

libfwupdplugin/fu-security-attrs.c
plugins/uefi-mok/fu-self-test.c
plugins/uefi-mok/fu-uefi-mok-common.c
src/fu-security-attr-common.c
src/fu-util-common.c

trivial: Add translations for org.fwupd.hsi.Uefi.MemoryProtection

---

libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.h
libfwupdplugin/fu-self-test.c
libfwupdplugin/tests/cpuinfo
libfwupdplugin/tests/meson.build
plugins/msr/fu-msr-plugin.c
src/fu-main.c

trivial: Move reading /proc/cpuinfo to common code

---

plugins/redfish/fu-redfish-device.c

redfish: Do not add a release date if set to 00:00:00Z

---

plugins/logitech-bulkcontroller/fu-logitech-bulkcontroller-device.c

New firmware publish quite a few events, that are not applicable during setup. Raise the retry attempts to skip these unwanted events

logitech-bulkcontroller: increase retry attempts during setup

---

plugins/uefi-capsule/make-images.py

Fixes https://github.com/fwupd/fwupd/issues/8587

trivial: Fix compile when using Pango >= 1.56.2

---

plugins/redfish/README.md
plugins/redfish/fu-redfish-backend.c
plugins/redfish/fu-redfish-device.c
plugins/redfish/fu-redfish-plugin.c
plugins/redfish/fu-redfish-plugin.h
plugins/redfish/fu-self-test.c
plugins/redfish/tests/redfish.py

Heavily based on a patch by Arno DUBOIS <a.dubois@criteo.com>, many thanks.

redfish: Add additional instance IDs for Dell hardware

---

meson.build
plugins/flashrom/fu-flashrom-device.c

trivial: Use API from flashrom >= 1.6 to show user progress

---

plugins/dell-kestrel/fu-dell-kestrel-plugin.c

dell-kestrel: add the cached rmm device

---

src/fu-device-list.c
src/fu-engine-emulator.c
src/fu-engine-emulator.h
src/fu-engine.c

Support loading and saving emulations for plugins using ANOTHER_WRITE_REQUIRED

---

libfwupdplugin/fu-context.c
src/fu-tool.c

trivial: Ensure that a volume contains /EFI to be considered an ESP

---

libfwupdplugin/fu-firmware.c

trivial: Re-arrange some code to make PVS happy

---

meson.build

Only allow UEFI capsule updates on UEFI-capable architectures

---

plugins/uefi-dbx/fu-uefi-dbx-device.c
plugins/uefi-sbat/fu-uefi-sbat-device.c

trivial: Use a better icon for certificate devices

---

BUILD_ANDROID_NDK.md
meson.build
subprojects/.gitignore
subprojects/android_frameworks.wrap
subprojects/packagefiles/android_frameworks/meson.build
subprojects/packagefiles/android_frameworks/types.patch

Install header files for binder_ndk as subproject

---

src/fu-remote-list.c

Apparently the previous behaviour is undefined.

trivial: Do not use 0 for the inotify mask

---

src/fu-engine.c
src/fu-engine.h
src/fu-release.c
src/fu-release.h
src/fu-self-test.c
src/fu-tool.c

Fixes https://github.com/fwupd/fwupd/issues/8667

Set the MD_SET_XXX attributes when using fwupdtool install

---

libfwupdplugin/fu-backend.c
libfwupdplugin/fu-device-private.h
libfwupdplugin/fu-device.c
libfwupdplugin/fu-self-test.c
src/fu-engine-emulator.c
src/tests/usb-devices.json

Be more careful falling back to older emulation versions

---

src/fu-tool.c
src/fu-util.c

fu-util/fu-tool: Don't show non-json output for `update` command

---

src/fu-tool.c
src/fu-util.c

trivial: fu-util: Don't show device prompts in --json

---

src/fu-util.c

See-also: https://github.com/fwupd/fwupd/pull/8668#issuecomment-2788570422

trivial: Do not force --allow-reinstall and --allow-older in fwupdmgr install

---

.github/workflows/matrix.yml
contrib/ci/build_macos.sh
contrib/ci/build_windows.sh
contrib/ci/dependencies.xml
contrib/fwupd.spec.in
contrib/snap/snapcraft.yaml
meson.build
src/fu-console.c
src/meson.build

This will allow letting readline handle things like ctrl-c.
Closes: https://github.com/fwupd/fwupd/issues/8654

Use readline() to look up inputs from user

---

libfwupdplugin/fu-efi-x509-device.c
plugins/uefi-pk/fu-uefi-pk-device.c

Fixes https://github.com/fwupd/fwupd/issues/8677

Fix PK and KEK enumeration failure on some systems

---

plugins/uefi-capsule/README.md
plugins/uefi-db/fu-uefi-db-device.c
plugins/uefi-kek/fu-uefi-kek-device.c
plugins/uefi-pk/fu-uefi-pk-device.c

Fix the parents and grandparents for KEK and DB devices

---

.github/ISSUE_TEMPLATE/bug-report-general.md
.github/ISSUE_TEMPLATE/bug-report-uefi.md

trivial: Ask the user for the CHIDs in the issue template

---

plugins/uefi-dbx/uefi-dbx.quirk

Fixes https://github.com/fwupd/fwupd/issues/8710

uefi-dbx: Do not allow updates on the HP 479K6EA

---

src/fu-tool.c

This still shows them with available releases in get-devices, but stops us trying to update devices with inhibits in fwupdtool. This matches the behaviour from fwupdmgr.
Fixes https://github.com/fwupd/fwupd/issues/8697

Never allow updating updatable-hidden devices with fwupdtool

---

libfwupdplugin/fu-efi-signature-list.c

uefi-db: Fix a critical warning when parsing newest certificates

---

plugins/intel-cvs/fu-intel-cvs-device.c

intel-cvs: Require a reboot as the auxiliary bus cannot deal with a USB reconnect

---

src/fu-engine.c

trivial: Relax the 'no visible GUIDs' warning for non-updatable devices

---

libfwupdplugin/fu-device.c

trivial: Add emulated children for emulated parents

---

docs/fwupdplugin.toml.in
docs/uefi-db.md

Add some documentation about updating the KEK and db

---

libfwupdplugin/fu-efi-x509-device.c

uefi-kek: Ensure the device ID does not change post-update

---

libfwupdplugin/fu-x509-certificate.c

Do not assume the FuFirmware bytes cache is set before parsing

---

libfwupdplugin/fu-heci-device.c
libfwupdplugin/fu-mei-device.c
meson.build
meson_options.txt
src/fu-console.c

It gives both Android and MacOS a headache.

Make readline optional

---

plugins/uefi-dbx/uefi-dbx.quirk

See-also: https://github.com/fwupd/fwupd/issues/8696

uefi-dbx: Add CHUWI MiniBook X to the blocklist

---

libfwupdplugin/fu-efi-x509-device.c

Microsoft have chosen to split the 'Microsoft UEFI CA 2011' update into 'Microsoft UEFI CA 2023' and 'Microsoft Option ROM UEFI CA 2023' which means we need to dploy two new db's to one FuEfiX509Device.
Support using an archive (e.g. zip) of `FuEfiVariableAuthentication2` objects as well as a bare `FuEfiVariableAuthentication2` binary.

uefi-db: Allow installing multiple certificate updates at the same time

---

plugins/redfish/fu-redfish-multipart-device.c
plugins/redfish/fu-redfish-request.c
plugins/redfish/tests/redfish.py

With those two commits, it should match more closely the Redfish spec while being compatible with the already existing flow.
I also made sure that Redfish errors were still parsed when needed.
(please see individual commit messages for more details!)

redfish: Proper location handling when updating firmware, with better logging

---

plugins/flashrom/fu-flashrom-plugin.c

Fixes https://github.com/fwupd/fwupd/issues/8455

trivial: Downgrade a warning message

---

plugins/modem-manager/fu-mm-backend.c
plugins/modem-manager/fu-mm-device.c

I've been working on exposing ports that were probed by ModemManager but still appeared as ignored due to ModemManager not actively using them (mostly QCDM ports). [ModemManager!1250](https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/merge_requests/1250)
This change requires checking both regular ports (just like before) and with version 1.26 also the added ignored ports to get a list of _all_ ports known to ModemManager. Mainly it removes the need to detect QCDM ports by searching for a `"qcdm"` substring in their `/dev/...` name starting with ModemManager version 1.26.

modem-manager: check ignored ports

---

plugins/intel-gsc/fu-igsc-aux-firmware.c
plugins/intel-gsc/fu-igsc-code-firmware.c
plugins/intel-gsc/fu-igsc-oprom-firmware.c
plugins/intel-gsc/fu-igsc.rs

This avoids converting the blob->stream multiple times.

intel-gpu: Convert more firmware parsing to Rust format

---

libfwupdplugin/fu-oprom-firmware.c
libfwupdplugin/fu-oprom-firmware.h
libfwupdplugin/fu-oprom.rs
plugins/intel-gsc/fu-igsc-oprom-firmware.c

trivial: Define the OptionROM constants as Rust types

---

plugins/uefi-capsule/fu-uefi-capsule-plugin.c
src/fu-self-test.c

trivial: Build a plausible EFI system in the self tests

---

src/fu-tool.c
src/fu-util.c

Fix `--json` for various commands

---

data/power.quirk
libfwupdplugin/fu-common.c
libfwupdplugin/fu-common.rs
libfwupdplugin/fu-context.c
libfwupdplugin/fu-self-test.c
plugins/powerd/fu-powerd-plugin.c
plugins/upower/fu-upower-plugin.c

Use `OnBattery` for deciding whether on AC or DC

---

plugins/logitech-hidpp/fu-logitech-hidpp-device.c
plugins/logitech-hidpp/fu-logitech-hidpp-plugin.c
plugins/logitech-hidpp/fu-logitech-hidpp-rdfu.rs
plugins/logitech-hidpp/fu-logitech-hidpp.rs
plugins/logitech-hidpp/fu-logitech-rdfu-firmware.c
plugins/logitech-hidpp/fu-logitech-rdfu-firmware.h
plugins/logitech-hidpp/logitech-hidpp.quirk
plugins/logitech-hidpp/meson.build

Added support of resumable DFU feature.
Added support of new RDFU firmware format.
Added MX Mechanical device.

logitech-hidpp: add 0x00d1 feature

---

src/fu-tool.c
src/fu-util.c

trivial: clarify help text for `--json`

---

contrib/fwupd.spec.in

trivial: Sync the example spec file with downstream

---

plugins/uefi-dbx/uefi-dbx.quirk

uefi-dbx: Do not allow updates on the AiStone X5KK4NAG (TongFang)

---

plugins/elanfp/elanfp.quirk

elanfp: Add PID 0x0CA8

---

src/fu-tool.c
src/fu-util.c

Hello,
This PR will allow the get-updates command to get multiple DEVICE-ID https://github.com/fwupd/fwupd/issues/8817

trivial: allow multiple DEVICE-ID to get-updates command

---

src/fu-cabinet.c
src/fu-engine.c
src/fu-self-test.c
src/fu-tool.c

Closes: https://github.com/fwupd/fwupd/issues/8829
Suggested-by: Richard Hughes <richard@hughsie.com>

Cache the stream when building cabinet

---

plugins/rts54hub/README.md
plugins/rts54hub/fu-rts54hub-device.c
plugins/rts54hub/fu-rts54hub-plugin.c

add quirk key Rts54BlockSize for chunk blocksize
default size keep 4KB for chunk size
- [* ] Feature

plugins: rts54hub: add quirk key Rts54BlockSize

---

plugins/dell-kestrel/fu-dell-kestrel-ec.c
plugins/dell-kestrel/fu-dell-kestrel-ec.h
plugins/dell-kestrel/fu-dell-kestrel-hid-device.c

dell-kestrel: filter rmm device type before casting to ec

---

plugins/uefi-dbx/uefi-dbx.quirk

Added HP Elitedesk G6 mini to not get dbx-updates

---

contrib/qubes/src/fwupd_receive_updates.py

trivial: display file path on error

---

plugins/uefi-capsule/fu-self-test.c

Fixes, indirectly: https://github.com/fwupd/firmware-hp/issues/4

Fix self tests when building with -Defi_os_dir

---

plugins/modem-manager/modem-manager.quirk

modem-manager: add more Foxconn products and add proper GType

---

plugins/modem-manager/fu-mm-device.c
plugins/modem-manager/fu-mm-device.h
plugins/modem-manager/fu-self-test.c
plugins/modem-manager/modem-manager.quirk

Fixes https://github.com/fwupd/fwupd/issues/8869, harder.

modem-manager: Be much cleverer when adding device Instance IDs

---

plugins/vli/fu-vli-usbhub-pd-device.c

For hub pd share spi case, we need to add the flag "UNSIGNED_PAYLOAD".

vli:add unsigned flag

---

plugins/uefi-kek/fu-uefi-kek-device.c

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2371482

Mark the KEK updates as affecting FDE like BitLocker

---

libfwupdplugin/fu-coswid-firmware.c

trivial: Do not use g_critical() when building invalid firmware

---

libfwupdplugin/fu-context.c
libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.h
libfwupdplugin/fu-uefi-device.c
plugins/uefi-db/fu-uefi-db-device.c
plugins/uefi-dbx/fu-uefi-dbx-device.c
plugins/uefi-dbx/fu-uefi-dbx-plugin.c
plugins/uefi-kek/fu-uefi-kek-device.c
plugins/uefi-pk/fu-uefi-pk-device.c
src/fu-self-test.c

Do the efivarfs free space checks for db, KEK and PK devices

---

plugins/modem-manager/fu-mm-device.c

modem-manager: Fix two Coverity-spotted potential memory leaks

---

src/fu-dbus-daemon.c
src/fu-device-list.c
src/fu-self-test.c

trivial: Remove fu_dbus_daemon_device_id_valid() and verify in the device list

---

plugins/mediatek-scaler/mediatek-scaler.quirk

Add New hardware system for fwupd main branch to update mediatek scaler FW

mediatek_scaler: add new hardware system for fwupd 2.0.0 and above

---

plugins/mediatek-scaler/mediatek-scaler.quirk

Add New hardware system for fwupd 1.9.x to update mediatek scaler FW

mediatek_scaler: add new hardware systems for 1_9_X

---

libfwupdplugin/rustgen.py
plugins/bnr-dp/fu-bnr-dp-device.c
plugins/bnr-dp/fu-bnr-dp-firmware.c
plugins/logitech-hidpp/fu-logitech-hidpp-device.c

trivial: Rename rustgen flag enums to be singular

---

libfwupdplugin/fu-rustgen-struct.c.in
libfwupdplugin/rustgen.py

Also show what we were expecting in the debug message; this very much helps with debugging.

trivial: Show the rustgen parsed structure before running validate

---

.github/workflows/matrix.yml
contrib/ci/build_windows.sh
contrib/fwupd.wxs.in
contrib/mingw64.cross

Many thanks to Otto Fowler for the suggestion.
Fixes https://github.com/fwupd/fwupd/issues/8987

Make sure fwupdtool.exe is available in the win32 PATH

---

plugins/logitech-scribe/meson.build
plugins/logitech-scribe/tests/logi-scribe-setup.json
plugins/logitech-scribe/tests/logi-scribe.json
src/fu-util.c

Ref: https://github.com/fwupd/fwupd/issues/7093

logitech-scribe: Add emulation test files

---

plugins/mediatek-scaler/mediatek-scaler.quirk

mediatek_scaler: add new hardware system

mediatek_scaler: add new hardware system

---

contrib/build-openbmc.sh
libfwupdplugin/fu-x509-certificate.c
src/fu-udev-backend.c

This will be useful for OpenWRT and Android.
See-also: https://github.com/fwupd/fwupd/issues/8969

Allow using the kernel netlink hotplug socket

---

src/fu-engine-config.c

Fixes https://github.com/fwupd/fwupd/issues/9014

Remove the trailing slash from EspLocation

---

libfwupdplugin/fu-progress.c

Optimize calculating startup progress to speedup coldplug by 0.4%

---

libfwupdplugin/fu-device-private.h
libfwupdplugin/fu-device.c
libfwupdplugin/fu-self-test.c

trivial: Add fu_device_check_fwupd_version() for future use

---

plugins/intel-gsc/README.md

intel-gsc: trivial: update readme guids and owners.

---

contrib/ci/check-cpu.py
contrib/ci/check-rss.py
contrib/ci/ubuntu.sh

This should catch changes that accidentally slow down coldplug or increase memory usage significantly.

Add regression checks for CPU and RSS in CI

---

plugins/qc-s5gen2/fu-qc-s5gen2-ble-device.c
plugins/qc-s5gen2/fu-qc-s5gen2-plugin.c
plugins/qc-s5gen2/qc-s5gen2.quirk

qc_s5gen2: Namespace the quirk properly

---

src/fu-udev-backend.c

trivial: Lower the log verbosity when a udev device was not found

---

.github/workflows/matrix.yml

trivial: ci: set fetch depth for Windows publishing to 0

---

libfwupdplugin/fu-device.c
libfwupdplugin/fu-device.rs

Add a way to deprecated device instance IDs

---

plugins/uefi-dbx/fu-self-test.c
plugins/uefi-dbx/fu-uefi-dbx-device.c

Fixes https://github.com/fwupd/fwupd/issues/9121

uefi-dbx: Allow upgrading from a zero 'empty' dbx

---

plugins/qc-firehose/fu-qc-firehose-impl.c

The patch command is deprecated and if the `<patch />` `filename="..."` is not 'DISK', which for newer devices always seems to be the case, it effectively does nothing. I don't think there is any reason to keep this then.

Revert "qc-firehose: Apply patch file"

---

plugins/egis-moc/fu-egis-moc-common.c
plugins/egis-moc/fu-self-test.c

egis-moc: Fix build when compiling for s390x

---

plugins/uefi-capsule/uefi-capsule.quirk

uefi-capsule: cod: remove cod-dell-recovery hwid match

---

meson.build

trivial: Disable -Wdeprecated-declarations until we can fix flashrom

---

plugins/modem-manager/fu-mm-qdu-mbim-device.c

ModemManager: qdu: Make chunk updated in the loop

---

libfwupdplugin/fu-drm-device-private.h
libfwupdplugin/fu-drm-device.c
libfwupdplugin/fu-edid.c
libfwupdplugin/fu-edid.h
src/fu-self-test.c

trivial: Increase coverage by registering a DRM device in tests

---

plugins/synaptics-rmi/fu-synaptics-rmi-hid-device.c

-  Code fix
These changes resolve communication issues with Synaptics RMI HID devices by ensuring proper buffer allocation for data transfers and enabling write operations to HID devices.

Fix synaptics-rmi hid communication issues

---

meson.build
plugins/flashrom/fu-flashrom-plugin.c
subprojects/flashrom.wrap

flashrom: Do not use deprecated API

---

.github/workflows/matrix.yml

Closes: https://github.com/fwupd/fwupd/issues/8477

trivial: ci: set correct Windows file glob

---

plugins/modem-manager/fu-mm-mhi-qcdm-device.c

Fixes https://github.com/fwupd/fwupd/issues/8382

modem-manager: Fix installing on RM520N by altering the write order

---

.gitignore
contrib/ci/check-meson-install-tags.py

Meson install tags again

---

plugins/devlink/devlink.quirk

Just and extension of quirk file.

devlink: add couple other ConnectX devices to quirk files

---

plugins/jabra-gnp/fu-jabra-gnp-child-device.c
plugins/jabra-gnp/fu-jabra-gnp-child-device.h
plugins/jabra-gnp/fu-jabra-gnp-common.c
plugins/jabra-gnp/fu-jabra-gnp-common.h
plugins/jabra-gnp/fu-jabra-gnp-device.c
plugins/jabra-gnp/fu-jabra-gnp-device.h
plugins/jabra-gnp/fu-jabra-gnp-firmware.c
plugins/jabra-gnp/fu-jabra-gnp-firmware.h
plugins/jabra-gnp/fu-jabra-gnp-image.c
plugins/jabra-gnp/meson.build
plugins/jabra-gnp/tests/jabra-evolve2-75.json

Fixing a couple of bugs with the plugin when it comes to child devices, and added the code to support an extension to the firmware update protocol. 
Code is still untested due to some internal constraints, so some byte values may be wrong, but I wanted to get the PR started, and I will be able to test next week already.

Added an extended version and fixed a few bugs on jabra-gnp

---

meson_options.txt

#
- Sorts options alphabetically (again)
- Removes leading space from `' Host Security Information'`
- Applies `meson.format` to `meson_options.txt`

Reformat meson_options.txt

---

plugins/framework-qmk/framework-qmk.quirk

New keyboard type shipping soon for prebuilt systems as required by Microsoft. Ships with latest firmware, no update needed yet.

framework-qmk: Add quirk for Copilot keyboard

---

contrib/ci/dependencies.xml

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1110022

drop python3-toml for Debian/Ubuntu

---

libfwupd/fwupd-client.c
libfwupd/fwupd-client.h
libfwupd/fwupd.map
src/fu-dbus-daemon.c
src/fu-tool.c
src/fu-util.c
src/org.freedesktop.fwupd.xml

Allow calling 'fwupdmgr hwids' by exposing another daemon property

---

plugins/dfu/fu-dfu-device.c
plugins/dfu/fu-dfu-device.h
plugins/dfu/fu-dfu-target.c

See-also: https://github.com/fwupd/fwupd/issues/9261

dfu: Use fu_usb_device_add_interface() rather than re-inventing the wheel

---

libfwupdplugin/fu-common-linux.c

The UDisk2 daemon in Ubuntu 16.04 (v2.1.7) does not support the GetBlockDevices() method.
Use GDBusObjectManager and filter the list client side to achieve the same result.
This fixes running very new fwupd on very old operating systems.

Support very old versions of UDisks

---

libfwupdplugin/fu-block-partition.c

This means we need to less of the libblkid prober in the common case.

Get the partition UUID as an attribute when available

---

src/fu-tool.c

Make fwupdtool extract work with deeply nested images

---

contrib/android/android_amd64-cross-file.ini

Changing android_amd-cross-file to run in all environments

---

contrib/ci/debian.sh
libfwupdplugin/fu-efi-common.c
libfwupdplugin/fu-efi-common.h
libfwupdplugin/fu-efi-ftw-store.c
libfwupdplugin/fu-efi-ftw-store.h
libfwupdplugin/fu-efi-vss-auth-variable.c
libfwupdplugin/fu-efi-vss-auth-variable.h
libfwupdplugin/fu-efi.rs
libfwupdplugin/fu-self-test.c
libfwupdplugin/fwupdplugin.h
libfwupdplugin/meson.build
libfwupdplugin/tests/efi-ftw-store.builder.xml
libfwupdplugin/tests/efi-vss-auth-variable.builder.xml
libfwupdplugin/tests/meson.build
meson.build
src/fu-engine-helper.c
src/fu-engine-helper.h
src/fu-engine.c

Add FuEfiFtwStore for future use

---

plugins/parade-usbhub/parade-usbhub.quirk

parade-usbhub: add dell vid/pid to quirk

---

contrib/android/android_amd64-cross-file.ini

Hard coding Cross file ini changes for testing purpose

---

contrib/ci/debian.sh
plugins/parade-usbhub/parade-usbhub.quirk

(cherry picked from commit 0de846a2f868969e6b17d4b15acbcc4df45d5541)

(cherry-pick) parade-usbhub: add dell vid/pid to quirk

---

libfwupdplugin/fu-efi-volume.c
libfwupdplugin/fu-self-test.c
libfwupdplugin/tests/efi-volume.builder.xml

trivial: Preserve the exact padding between EVSA stores

---

libfwupdplugin/fu-efi-ftw-store.c
libfwupdplugin/tests/efi-ftw-store.builder.xml
libfwupdplugin/tests/efi-volume.builder.xml

trivial: Do not assume the FTW area is all 0xFF

---

contrib/create-plugin.py

Fixing capitalization in comments of default plugin files

---

plugins/dell-kestrel/fu-dell-kestrel-hid-device.c
plugins/dell-kestrel/fu-dell-kestrel-hid.rs

dell-kestrel: Fix a potential OOB read

---

plugins/ilitek-its/fu-ilitek-its-device.c
plugins/ilitek-its/fu-ilitek-its.rs

ilitek-its: Actually validate the returned device buffer

---

plugins/jabra-file/fu-jabra-file-firmware.c

jabra-file: Fix a critical warning when parsing invalid firmware

---

data/tests/fwupd.sh
data/tests/fwupd.test.in
data/tests/fwupdmgr-online.sh
data/tests/fwupdmgr-online.test.in
data/tests/fwupdmgr-p2p.sh
data/tests/fwupdmgr-p2p.test.in
data/tests/fwupdmgr.sh
data/tests/fwupdmgr.test.in
data/tests/fwupdtool-efiboot.sh
data/tests/fwupdtool-efiboot.test.in
data/tests/fwupdtool.sh
data/tests/fwupdtool.test.in
data/tests/meson.build
src/fu-engine.c
src/fu-self-test.c
src/fu-util.c

Correctly run the installed tests
